#pragma once

#include "enums.hpp"

namespace arm
{
    /*
    // ARM insn.auxpref bits
     */
    enum aux_e
    {
        aux_cond = 0x0001,          // set condition codes (S postfix is required)
        aux_byte = 0x0002,          // byte transfer (B postfix is required)
        aux_npriv = 0x0004,         // non-privileged transfer (T postfix is required)
        aux_regsh = 0x0008,         // shift count is held in a register (see o_shreg)
        aux_negoff = 0x0010,        // memory offset is negated in LDR,STR
        aux_immcarry = 0x0010,      // carry flag is set to bit 31 of the immediate operand (see may_set_carry)
        aux_wback = 0x0020,         // write back (! postfix is required)
        aux_wbackldm = 0x0040,      // write back for LDM/STM (! postfix is required)
        aux_postidx = 0x0080,       // post-indexed mode in LDR,STR
        aux_ltrans = 0x0100,        // long transfer in LDC/STC (L postfix is required)
        aux_wimm = 0x0200,          // thumb32 wide encoding of immediate constant (MOVW)
        aux_sb = 0x0400,            // signed byte (SB postfix)
        aux_sh = 0x0800,            // signed halfword (SH postfix)
        aux_sw = (aux_sb | aux_sh), // signed word (SW postfix)
        aux_h = 0x1000,             // halfword (H postfix)
        aux_x = (aux_h | aux_byte), // doubleword (X postfix in A64)
        aux_d = aux_x,              // dual (D postfix in A32/T32)
        aux_p = 0x2000,             // priviledged (P postfix)
        aux_coproc = 0x4000,        // coprocessor instruction
        aux_wide = 0x8000,          // wide (32-bit) thumb instruction (.W suffix)
        aux_pac = 0x10000,          // Pointer Authentication Code instruction (see PAC_ flags)
        aux_ns = 0x20000,           // non-secure branch (NS suffix)
        aux_thumb32 = 0x40000,      // (aux_wide is sometimes turned off for pretty-printing)
        aux_vpt_mask = 0x780000,    // (MVE) we cannot use INSNPREF for the mask of a VFP insn because
                                    // it is used to store Neon suffixes (like .f16, .i8, ...).
                                    // so we store the mask in AUXPREF, see get_vpt_mask()
        aux_vpt_pred = 0x180000,    // (MVE) also we use these bits to store the predicate of the
                                    // instruction in a VPT predication block, see VPT_THEN, VPT_ELSE
        aux_vpt_then = 0x180000,    // (MVE) the insn is in the THEN section of a VPT predication block
        aux_vpt_else = 0x080000,    // (MVE) the insn is in the ELSE section of a VPT predication block

    };

    constexpr auto auxpref_flags = std::to_array(
        {TO_ENUM(aux_sw, "signed word (SW postfix)"),
         TO_ENUM(aux_x, "doubleword (X postfix in A64)"),
         TO_ENUM(aux_cond, "set condition codes (S postfix is required)"),
         TO_ENUM(aux_byte, "byte transfer (B postfix is required)"),
         TO_ENUM(aux_npriv, "non-privileged transfer (T postfix is required)"),
         TO_ENUM(aux_regsh, "shift count is held in a register (see o_shreg)"),
         TO_ENUM(aux_negoff, "memory offset is negated in LDR,STR"),
         TO_ENUM(aux_immcarry, "carry flag is set to bit 31 of the immediate operand (see may_set_carry)"),
         TO_ENUM(aux_wback, "write back (! postfix is required)"),
         TO_ENUM(aux_wbackldm, "write back for LDM/STM (! postfix is required)"),
         TO_ENUM(aux_postidx, "post-indexed mode in LDR,STR"),
         TO_ENUM(aux_ltrans, "long transfer in LDC/STC (L postfix is required)"),
         TO_ENUM(aux_wimm, "thumb32 wide encoding of immediate constant (MOVW)"),
         TO_ENUM(aux_sb, "signed byte (SB postfix)"),
         TO_ENUM(aux_sh, "signed halfword (SH postfix)"),
         TO_ENUM(aux_h, "halfword (H postfix)"),
         TO_ENUM(aux_d, "dual (D postfix in A32/T32)"),
         TO_ENUM(aux_p, "privileged (P postfix)"),
         TO_ENUM(aux_coproc, "coprocessor instruction"),
         TO_ENUM(aux_wide, "wide (32-bit) thumb instruction (.W suffix)"),
         TO_ENUM(aux_pac, "Pointer Authentication Code instruction (see PAC_ flags)"),
         TO_ENUM(aux_ns, "non-secure branch (NS suffix)"),
         TO_ENUM(aux_thumb32, "(aux_wide is sometimes turned off for pretty-printing)"),
         TO_ENUM(aux_vpt_mask, "(MVE) we cannot use INSNPREF for the mask of a VFP insn because"),
         TO_ENUM(aux_vpt_pred, "(MVE) also we use these bits to store the predicate of the"),
         TO_ENUM(aux_vpt_then, "(MVE) the insn is in the THEN section of a VPT predication block"),
         TO_ENUM(aux_vpt_else, "(MVE) the insn is in the ELSE section of a VPT predication block")});

    enum RegNo
    {
        R0,
        R1,
        R2,
        R3,
        R4,
        R5,
        R6,
        R7,
        R8,
        R9,
        R10,
        R11,
        R12,
        R13,
        R14,
        R15,
        CPSR,
        CPSR_flg,
        SPSR,
        SPSR_flg,
        T,
        rVcs,
        rVds,  // virtual registers for code and data segments
        Racc0, // Intel xScale coprocessor accumulator
        FPSID,
        FPSCR,
        FPEXC, // VFP system registers
        FPINST,
        FPINST2,
        MVFR0,
        MVFR1,
        // msr system registers
        SYSM_APSR,
        SYSM_IAPSR,
        SYSM_EAPSR,
        SYSM_XPSR,
        SYSM_IPSR,
        SYSM_EPSR,
        SYSM_IEPSR,
        SYSM_MSP,
        SYSM_PSP,
        SYSM_PRIMASK,
        SYSM_BASEPRI,
        SYSM_BASEPRI_MAX,
        SYSM_FAULTMASK,
        SYSM_CONTROL,
        Q0,
        Q1,
        Q2,
        Q3,
        Q4,
        Q5,
        Q6,
        Q7,
        Q8,
        Q9,
        Q10,
        Q11,
        Q12,
        Q13,
        Q14,
        Q15,
        D0,
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9,
        D10,
        D11,
        D12,
        D13,
        D14,
        D15,
        D16,
        D17,
        D18,
        D19,
        D20,
        D21,
        D22,
        D23,
        D24,
        D25,
        D26,
        D27,
        D28,
        D29,
        D30,
        D31,
        S0,
        S1,
        S2,
        S3,
        S4,
        S5,
        S6,
        S7,
        S8,
        S9,
        S10,
        S11,
        S12,
        S13,
        S14,
        S15,
        S16,
        S17,
        S18,
        S19,
        S20,
        S21,
        S22,
        S23,
        S24,
        S25,
        S26,
        S27,
        S28,
        S29,
        S30,
        S31,
        FIRST_FPREG = Q0,
        LAST_FPREG = S31,
        CF,
        ZF,
        NF,
        VF,

        // AArch64 registers
        // general-purpose registers
        X0,
        X1,
        X2,
        X3,
        X4,
        X5,
        X6,
        X7,
        X8,
        X9,
        X10,
        X11,
        X12,
        X13,
        X14,
        X15,
        X16,
        X17,
        X18,
        X19,
        X20,
        X21,
        X22,
        X23,
        X24,
        X25,
        X26,
        X27,
        X28,
        X29,
        XFP = X29, // frame pointer
        X30,
        XLR = X30, // link register

        XZR, // zero register (special case of GPR=31)

        XSP, // stack pointer (special case of GPR=31)

        XPC, // PC (not available as actual register)

        // 128-bit SIMD registers
        V0,
        V1,
        V2,
        V3,
        V4,
        V5,
        V6,
        V7,
        V8,
        V9,
        V10,
        V11,
        V12,
        V13,
        V14,
        V15,
        V16,
        V17,
        V18,
        V19,
        V20,
        V21,
        V22,
        V23,
        V24,
        V25,
        V26,
        V27,
        V28,
        V29,
        V30,
        V31,

        ARM_MAXREG, // must be the last entry
    };

    constexpr auto registers = std::to_array(
        {
            TO_ENUM(R0, "R0"),
            TO_ENUM(R1, "R1"),
            TO_ENUM(R2, "R2"),
            TO_ENUM(R3, "R3"),
            TO_ENUM(R4, "R4"),
            TO_ENUM(R5, "R5"),
            TO_ENUM(R6, "R6"),
            TO_ENUM(R7, "R7"),
            TO_ENUM(R8, "R8"),
            TO_ENUM(R9, "R9"),
            TO_ENUM(R10, "R10"),
            TO_ENUM(R11, "R11"),
            TO_ENUM(R12, "R12"),
            TO_ENUM(R13, "R13"),
            TO_ENUM(R14, "R14"),
            TO_ENUM(R15, "R15"),
            TO_ENUM(CPSR, "CPSR"),
            TO_ENUM(CPSR_flg, "CPSR_flg"),
            TO_ENUM(SPSR, "SPSR"),
            TO_ENUM(SPSR_flg, "SPSR_flg"),
            TO_ENUM(T, "T"),
            TO_ENUM(rVcs, "rVcs"),
            TO_ENUM(rVds, "rVds"),
            // virtual registers for code and data segments
            TO_ENUM(Racc0, "Racc0"),
            // Intel xScale coprocessor accumulator
            TO_ENUM(FPSID, "FPSID"),
            TO_ENUM(FPSCR, "FPSCR"),
            TO_ENUM(FPEXC, "FPEXC"),
            // VFP system registers
            TO_ENUM(FPINST, "FPINST"),
            TO_ENUM(FPINST2, "FPINST2"),
            TO_ENUM(MVFR0, "MVFR0"),
            TO_ENUM(MVFR1, "MVFR1"),
            // msr system registers
            TO_ENUM(SYSM_APSR, "SYSM_APSR"),
            TO_ENUM(SYSM_IAPSR, "SYSM_IAPSR"),
            TO_ENUM(SYSM_EAPSR, "SYSM_EAPSR"),
            TO_ENUM(SYSM_XPSR, "SYSM_XPSR"),
            TO_ENUM(SYSM_IPSR, "SYSM_IPSR"),
            TO_ENUM(SYSM_EPSR, "SYSM_EPSR"),
            TO_ENUM(SYSM_IEPSR, "SYSM_IEPSR"),
            TO_ENUM(SYSM_MSP, "SYSM_MSP"),
            TO_ENUM(SYSM_PSP, "SYSM_PSP"),
            TO_ENUM(SYSM_PRIMASK, "SYSM_PRIMASK"),
            TO_ENUM(SYSM_BASEPRI, "SYSM_BASEPRI"),
            TO_ENUM(SYSM_BASEPRI_MAX, "SYSM_BASEPRI_MAX"),
            TO_ENUM(SYSM_FAULTMASK, "SYSM_FAULTMASK"),
            TO_ENUM(SYSM_CONTROL, "SYSM_CONTROL"),
            TO_ENUM(Q0, "Q0"),
            TO_ENUM(Q1, "Q1"),
            TO_ENUM(Q2, "Q2"),
            TO_ENUM(Q3, "Q3"),
            TO_ENUM(Q4, "Q4"),
            TO_ENUM(Q5, "Q5"),
            TO_ENUM(Q6, "Q6"),
            TO_ENUM(Q7, "Q7"),
            TO_ENUM(Q8, "Q8"),
            TO_ENUM(Q9, "Q9"),
            TO_ENUM(Q10, "Q10"),
            TO_ENUM(Q11, "Q11"),
            TO_ENUM(Q12, "Q12"),
            TO_ENUM(Q13, "Q13"),
            TO_ENUM(Q14, "Q14"),
            TO_ENUM(Q15, "Q15"),
            TO_ENUM(D0, "D0"),
            TO_ENUM(D1, "D1"),
            TO_ENUM(D2, "D2"),
            TO_ENUM(D3, "D3"),
            TO_ENUM(D4, "D4"),
            TO_ENUM(D5, "D5"),
            TO_ENUM(D6, "D6"),
            TO_ENUM(D7, "D7"),
            TO_ENUM(D8, "D8"),
            TO_ENUM(D9, "D9"),
            TO_ENUM(D10, "D10"),
            TO_ENUM(D11, "D11"),
            TO_ENUM(D12, "D12"),
            TO_ENUM(D13, "D13"),
            TO_ENUM(D14, "D14"),
            TO_ENUM(D15, "D15"),
            TO_ENUM(D16, "D16"),
            TO_ENUM(D17, "D17"),
            TO_ENUM(D18, "D18"),
            TO_ENUM(D19, "D19"),
            TO_ENUM(D20, "D20"),
            TO_ENUM(D21, "D21"),
            TO_ENUM(D22, "D22"),
            TO_ENUM(D23, "D23"),
            TO_ENUM(D24, "D24"),
            TO_ENUM(D25, "D25"),
            TO_ENUM(D26, "D26"),
            TO_ENUM(D27, "D27"),
            TO_ENUM(D28, "D28"),
            TO_ENUM(D29, "D29"),
            TO_ENUM(D30, "D30"),
            TO_ENUM(D31, "D31"),
            TO_ENUM(S0, "S0"),
            TO_ENUM(S1, "S1"),
            TO_ENUM(S2, "S2"),
            TO_ENUM(S3, "S3"),
            TO_ENUM(S4, "S4"),
            TO_ENUM(S5, "S5"),
            TO_ENUM(S6, "S6"),
            TO_ENUM(S7, "S7"),
            TO_ENUM(S8, "S8"),
            TO_ENUM(S9, "S9"),
            TO_ENUM(S10, "S10"),
            TO_ENUM(S11, "S11"),
            TO_ENUM(S12, "S12"),
            TO_ENUM(S13, "S13"),
            TO_ENUM(S14, "S14"),
            TO_ENUM(S15, "S15"),
            TO_ENUM(S16, "S16"),
            TO_ENUM(S17, "S17"),
            TO_ENUM(S18, "S18"),
            TO_ENUM(S19, "S19"),
            TO_ENUM(S20, "S20"),
            TO_ENUM(S21, "S21"),
            TO_ENUM(S22, "S22"),
            TO_ENUM(S23, "S23"),
            TO_ENUM(S24, "S24"),
            TO_ENUM(S25, "S25"),
            TO_ENUM(S26, "S26"),
            TO_ENUM(S27, "S27"),
            TO_ENUM(S28, "S28"),
            TO_ENUM(S29, "S29"),
            TO_ENUM(S30, "S30"),
            TO_ENUM(S31, "S31"),
            TO_ENUM(FIRST_FPREG, "FIRST_FPREG"),
            TO_ENUM(LAST_FPREG, "LAST_FPREG"),
            TO_ENUM(CF, "CF"),
            TO_ENUM(ZF, "ZF"),
            TO_ENUM(NF, "NF"),
            TO_ENUM(VF, "VF"),

            // AArch64 registers
            // general-purpose registers
            TO_ENUM(X0, "X0"),
            TO_ENUM(X1, "X1"),
            TO_ENUM(X2, "X2"),
            TO_ENUM(X3, "X3"),
            TO_ENUM(X4, "X4"),
            TO_ENUM(X5, "X5"),
            TO_ENUM(X6, "X6"),
            TO_ENUM(X7, "X7"),
            TO_ENUM(X8, "X8"),
            TO_ENUM(X9, "X9"),
            TO_ENUM(X10, "X10"),
            TO_ENUM(X11, "X11"),
            TO_ENUM(X12, "X12"),
            TO_ENUM(X13, "X13"),
            TO_ENUM(X14, "X14"),
            TO_ENUM(X15, "X15"),
            TO_ENUM(X16, "X16"),
            TO_ENUM(X17, "X17"),
            TO_ENUM(X18, "X18"),
            TO_ENUM(X19, "X19"),
            TO_ENUM(X20, "X20"),
            TO_ENUM(X21, "X21"),
            TO_ENUM(X22, "X22"),
            TO_ENUM(X23, "X23"),
            TO_ENUM(X24, "X24"),
            TO_ENUM(X25, "X25"),
            TO_ENUM(X26, "X26"),
            TO_ENUM(X27, "X27"),
            TO_ENUM(X28, "X28"),
            TO_ENUM(X29, "X29"),
            TO_ENUM(XFP, "XFP"),

            // frame pointer
            TO_ENUM(X30, "X30"),
            TO_ENUM(XLR, "XLR"),

            // link register

            TO_ENUM(XZR, "XZR"),
            // zero register (special case of GPR=31),

            TO_ENUM(XSP, "XSP"),
            // stack pointer (special case of GPR=31),

            TO_ENUM(XPC, "XPC"),
            // PC (not available as actual register),

            // 128-bit SIMD registers
            TO_ENUM(V0, "V0"),
            TO_ENUM(V1, "V1"),
            TO_ENUM(V2, "V2"),
            TO_ENUM(V3, "V3"),
            TO_ENUM(V4, "V4"),
            TO_ENUM(V5, "V5"),
            TO_ENUM(V6, "V6"),
            TO_ENUM(V7, "V7"),
            TO_ENUM(V8, "V8"),
            TO_ENUM(V9, "V9"),
            TO_ENUM(V10, "V10"),
            TO_ENUM(V11, "V11"),
            TO_ENUM(V12, "V12"),
            TO_ENUM(V13, "V13"),
            TO_ENUM(V14, "V14"),
            TO_ENUM(V15, "V15"),
            TO_ENUM(V16, "V16"),
            TO_ENUM(V17, "V17"),
            TO_ENUM(V18, "V18"),
            TO_ENUM(V19, "V19"),
            TO_ENUM(V20, "V20"),
            TO_ENUM(V21, "V21"),
            TO_ENUM(V22, "V22"),
            TO_ENUM(V23, "V23"),
            TO_ENUM(V24, "V24"),
            TO_ENUM(V25, "V25"),
            TO_ENUM(V26, "V26"),
            TO_ENUM(V27, "V27"),
            TO_ENUM(V28, "V28"),
            TO_ENUM(V29, "V29"),
            TO_ENUM(V30, "V30"),
            TO_ENUM(V31, "V31"),
            TO_ENUM(ARM_MAXREG, "ARM_MAXREG"),
        });

}