auto instructions_PLFM_ALPHA = flags_vector_t{
	TO_ENUM(ALPHA_null, "Undocumented instruction ALPHA_null"),
	TO_ENUM(ALPHA_addf, "Add F_floating"),
	TO_ENUM(ALPHA_addg, "Add G_floating"),
	TO_ENUM(ALPHA_addl, "Add longword"),
	TO_ENUM(ALPHA_addl_v, "Add longword with overflow"),
	TO_ENUM(ALPHA_addq, "Add quadword"),
	TO_ENUM(ALPHA_addq_v, "Add quadword with overflow"),
	TO_ENUM(ALPHA_adds, "Add S_floating"),
	TO_ENUM(ALPHA_addt, "Add T_floating"),
	TO_ENUM(ALPHA_amask, "Architecture mask"),
	TO_ENUM(ALPHA_and, "Logical product"),
	TO_ENUM(ALPHA_beq, "Branch if = zero"),
	TO_ENUM(ALPHA_bge, "Branch if >= zero"),
	TO_ENUM(ALPHA_bgt, "Branch if > zero"),
	TO_ENUM(ALPHA_bic, "Bit clear"),
	TO_ENUM(ALPHA_bis, "Logical sum"),
	TO_ENUM(ALPHA_blbc, "Branch if low bit clear"),
	TO_ENUM(ALPHA_blbs, "Branch if low bit set"),
	TO_ENUM(ALPHA_ble, "Branch if <= zero"),
	TO_ENUM(ALPHA_blt, "Branch if < zero"),
	TO_ENUM(ALPHA_bne, "Branch if != zero"),
	TO_ENUM(ALPHA_br, "Unconditional branch"),
	TO_ENUM(ALPHA_bsr, "Branch to subroutine"),
	TO_ENUM(ALPHA_call_pal, "Trap to PALcode"),
	TO_ENUM(ALPHA_cmoveq, "CMOVE if = zero"),
	TO_ENUM(ALPHA_cmovge, "CMOVE if >= zero"),
	TO_ENUM(ALPHA_cmovgt, "CMOVE if > zero"),
	TO_ENUM(ALPHA_cmovlbc, "CMOVE if low bit clear"),
	TO_ENUM(ALPHA_cmovlbs, "CMOVE if low bit set"),
	TO_ENUM(ALPHA_cmovle, "CMOVE if <= zero"),
	TO_ENUM(ALPHA_cmovlt, "CMOVE if < zero"),
	TO_ENUM(ALPHA_cmovne, "CMOVE if != zero"),
	TO_ENUM(ALPHA_cmpbge, "Compare byte"),
	TO_ENUM(ALPHA_cmpeq, "Compare signed quadword equal"),
	TO_ENUM(ALPHA_cmpgeq, "Compare G_floating equal"),
	TO_ENUM(ALPHA_cmpgle, "Compare G_floating less than or equal"),
	TO_ENUM(ALPHA_cmpglt, "Compare G_floating less than"),
	TO_ENUM(ALPHA_cmple, "Compare signed quadword less than or equal"),
	TO_ENUM(ALPHA_cmplt, "Compare signed quadword less than"),
	TO_ENUM(ALPHA_cmpteq, "Compare T_floating equal"),
	TO_ENUM(ALPHA_cmptle, "Compare T_floating less than or equal"),
	TO_ENUM(ALPHA_cmptlt, "Compare T_floating less than"),
	TO_ENUM(ALPHA_cmptun, "Compare T_floating unordered"),
	TO_ENUM(ALPHA_cmpule, "Compare unsigned quadword less than or equal"),
	TO_ENUM(ALPHA_cmpult, "Compare unsigned quadword less than"),
	TO_ENUM(ALPHA_cpys, "Copy sign"),
	TO_ENUM(ALPHA_cpyse, "Copy sign and exponent"),
	TO_ENUM(ALPHA_cpysn, "Copy sign negate"),
	TO_ENUM(ALPHA_ctlz, "Count leading zero"),
	TO_ENUM(ALPHA_ctpop, "Count population"),
	TO_ENUM(ALPHA_cttz, "Count trailing zero"),
	TO_ENUM(ALPHA_cvtdg, "Convert D_floating to G_floating"),
	TO_ENUM(ALPHA_cvtgd, "Convert G_floating to D_floating"),
	TO_ENUM(ALPHA_cvtgf, "Convert G_floating to F_floating"),
	TO_ENUM(ALPHA_cvtgq, "Convert G_floating to quadword"),
	TO_ENUM(ALPHA_cvtlq, "Convert longword to quadword"),
	TO_ENUM(ALPHA_cvtqf, "Convert quadword to F_floating"),
	TO_ENUM(ALPHA_cvtqg, "Convert quadword to G_floating"),
	TO_ENUM(ALPHA_cvtql, "Convert quadword to longword"),
	TO_ENUM(ALPHA_cvtqs, "Convert quadword to S_floating"),
	TO_ENUM(ALPHA_cvtqt, "Convert quadword to T_floating"),
	TO_ENUM(ALPHA_cvtst, "Convert S_floating to T_floating"),
	TO_ENUM(ALPHA_cvttq, "Convert T_floating to quadword"),
	TO_ENUM(ALPHA_cvtts, "Convert T_floating to S_floating"),
	TO_ENUM(ALPHA_divf, "Divide F_floating"),
	TO_ENUM(ALPHA_divg, "Divide G_floating"),
	TO_ENUM(ALPHA_divs, "Divide S_floating"),
	TO_ENUM(ALPHA_divt, "Divide T_floating"),
	TO_ENUM(ALPHA_ecb, "Evict cache block"),
	TO_ENUM(ALPHA_eqv, "Logical equivalence"),
	TO_ENUM(ALPHA_excb, "Exception barrier"),
	TO_ENUM(ALPHA_extbl, "Extract byte low"),
	TO_ENUM(ALPHA_extlh, "Extract longword high"),
	TO_ENUM(ALPHA_extll, "Extract longword low"),
	TO_ENUM(ALPHA_extqh, "Extract quadword high"),
	TO_ENUM(ALPHA_extql, "Extract quadword low"),
	TO_ENUM(ALPHA_extwh, "Extract word high"),
	TO_ENUM(ALPHA_extwl, "Extract word low"),
	TO_ENUM(ALPHA_fbeq, "Floating branch if = zero"),
	TO_ENUM(ALPHA_fbge, "Floating branch if >= zero"),
	TO_ENUM(ALPHA_fbgt, "Floating branch if > zero"),
	TO_ENUM(ALPHA_fble, "Floating branch if <= zero"),
	TO_ENUM(ALPHA_fblt, "Floating branch if < zero"),
	TO_ENUM(ALPHA_fbne, "Floating branch if != zero"),
	TO_ENUM(ALPHA_fcmoveq, "FCMOVE if = zero"),
	TO_ENUM(ALPHA_fcmovge, "FCMOVE if >= zero"),
	TO_ENUM(ALPHA_fcmovgt, "FCMOVE if > zero"),
	TO_ENUM(ALPHA_fcmovle, "FCMOVE if <= zero"),
	TO_ENUM(ALPHA_fcmovlt, "FCMOVE if < zero"),
	TO_ENUM(ALPHA_fcmovne, "FCMOVE if != zero"),
	TO_ENUM(ALPHA_fetch, "Prefetch data"),
	TO_ENUM(ALPHA_fetch_m, "Prefetch data, modify intent"),
	TO_ENUM(ALPHA_ftois, "Floating to integer move, S_floating"),
	TO_ENUM(ALPHA_ftoit, "Floating to integer move, T_floating"),
	TO_ENUM(ALPHA_implver, "Implementation version"),
	TO_ENUM(ALPHA_insbl, "Insert byte low"),
	TO_ENUM(ALPHA_inslh, "Insert longword high"),
	TO_ENUM(ALPHA_insll, "Insert longword low"),
	TO_ENUM(ALPHA_insqh, "Insert quadword high"),
	TO_ENUM(ALPHA_insql, "Insert quadword low"),
	TO_ENUM(ALPHA_inswh, "Insert word high"),
	TO_ENUM(ALPHA_inswl, "Insert word low"),
	TO_ENUM(ALPHA_itoff, "Integer to floating move, F_floating"),
	TO_ENUM(ALPHA_itofs, "Integer to floating move, S_floating"),
	TO_ENUM(ALPHA_itoft, "Integer to floating move, T_floating"),
	TO_ENUM(ALPHA_jmp, "Jump"),
	TO_ENUM(ALPHA_jsr, "Jump to subroutine"),
	TO_ENUM(ALPHA_jsr_coroutine, "Jump to subroutine return"),
	TO_ENUM(ALPHA_lda, "Load address"),
	TO_ENUM(ALPHA_ldah, "Load address high"),
	TO_ENUM(ALPHA_ldbu, "Load zero-extended byte"),
	TO_ENUM(ALPHA_ldwu, "Load zero-extended word"),
	TO_ENUM(ALPHA_ldf, "Load F_floating"),
	TO_ENUM(ALPHA_ldg, "Load G_floating"),
	TO_ENUM(ALPHA_ldl, "Load sign-extended longword"),
	TO_ENUM(ALPHA_ldl_l, "Load sign-extended longword locked"),
	TO_ENUM(ALPHA_ldq, "Load quadword"),
	TO_ENUM(ALPHA_ldq_l, "Load quadword locked"),
	TO_ENUM(ALPHA_ldq_u, "Load unaligned quadword"),
	TO_ENUM(ALPHA_lds, "Load S_floating"),
	TO_ENUM(ALPHA_ldt, "Load T_floating"),
	TO_ENUM(ALPHA_maxsb8, "Vector signed byte maximum"),
	TO_ENUM(ALPHA_maxsw4, "Vector signed word maximum"),
	TO_ENUM(ALPHA_maxub8, "Vector unsigned byte maximum"),
	TO_ENUM(ALPHA_maxuw4, "Vector unsigned word maximum"),
	TO_ENUM(ALPHA_mb, "Memory barrier"),
	TO_ENUM(ALPHA_mf_fpcr, "Move from FPCR"),
	TO_ENUM(ALPHA_minsb8, "Vector signed byte minimum"),
	TO_ENUM(ALPHA_minsw4, "Vector signed word minimum"),
	TO_ENUM(ALPHA_minub8, "Vector unsigned byte minimum"),
	TO_ENUM(ALPHA_minuw4, "Vector unsigned word minimum"),
	TO_ENUM(ALPHA_mskbl, "Mask byte low"),
	TO_ENUM(ALPHA_msklh, "Mask longword high"),
	TO_ENUM(ALPHA_mskll, "Mask longword low"),
	TO_ENUM(ALPHA_mskqh, "Mask quadword high"),
	TO_ENUM(ALPHA_mskql, "Mask quadword low"),
	TO_ENUM(ALPHA_mskwh, "Mask word high"),
	TO_ENUM(ALPHA_mskwl, "Mask word low"),
	TO_ENUM(ALPHA_mt_fpcr, "Move to FPCR"),
	TO_ENUM(ALPHA_mulf, "Multiply F_floating"),
	TO_ENUM(ALPHA_mulg, "Multiply G_floating"),
	TO_ENUM(ALPHA_mull, "Multiply longword"),
	TO_ENUM(ALPHA_mull_v, "Multiply longword with overflow"),
	TO_ENUM(ALPHA_mulq, "Multiply quadword"),
	TO_ENUM(ALPHA_mulq_v, "Multiply quadword with overflow"),
	TO_ENUM(ALPHA_muls, "Multiply S_floating"),
	TO_ENUM(ALPHA_mult, "Multiply T_floating"),
	TO_ENUM(ALPHA_ornot, "Logical sum with complement"),
	TO_ENUM(ALPHA_perr, "Pixel error"),
	TO_ENUM(ALPHA_pklb, "Pack longwords to bytes"),
	TO_ENUM(ALPHA_pkwb, "Pack words to bytes"),
	TO_ENUM(ALPHA_rc, "Read and clear"),
	TO_ENUM(ALPHA_ret, "Return from subroutine"),
	TO_ENUM(ALPHA_rpcc, "Read process cycle counter"),
	TO_ENUM(ALPHA_rs, "Read and set"),
	TO_ENUM(ALPHA_s4addl, "Scaled add longword by 4"),
	TO_ENUM(ALPHA_s4addq, "Scaled add quadword by 4"),
	TO_ENUM(ALPHA_s4subl, "Scaled subtract longword by 4"),
	TO_ENUM(ALPHA_s4subq, "Scaled subtract quadword by 4"),
	TO_ENUM(ALPHA_s8addl, "Scaled add longword by 8"),
	TO_ENUM(ALPHA_s8addq, "Scaled add quadword by 8"),
	TO_ENUM(ALPHA_s8subl, "Scaled subtract longword by 8"),
	TO_ENUM(ALPHA_s8subq, "Scaled subtract quadword by 8"),
	TO_ENUM(ALPHA_sextb, "Sign extend byte"),
	TO_ENUM(ALPHA_sextw, "Sign extend word"),
	TO_ENUM(ALPHA_sll, "Shift left logical"),
	TO_ENUM(ALPHA_sqrtf, "Square root F_floating"),
	TO_ENUM(ALPHA_sqrtg, "Square root G_floating"),
	TO_ENUM(ALPHA_sqrts, "Square root S_floating"),
	TO_ENUM(ALPHA_sqrtt, "Square root T_floating"),
	TO_ENUM(ALPHA_sra, "Shift right arithmetic"),
	TO_ENUM(ALPHA_srl, "Shift right logical"),
	TO_ENUM(ALPHA_stb, "Store byte"),
	TO_ENUM(ALPHA_stf, "Store F_floating"),
	TO_ENUM(ALPHA_stg, "Store G_floating"),
	TO_ENUM(ALPHA_sts, "Store S_floating"),
	TO_ENUM(ALPHA_stl, "Store longword"),
	TO_ENUM(ALPHA_stl_c, "Store longword conditional"),
	TO_ENUM(ALPHA_stq, "Store quadword"),
	TO_ENUM(ALPHA_stq_c, "Store quadword conditional"),
	TO_ENUM(ALPHA_stq_u, "Store unaligned quadword"),
	TO_ENUM(ALPHA_stt, "Store T_floating"),
	TO_ENUM(ALPHA_stw, "Store word"),
	TO_ENUM(ALPHA_subf, "Subtract F_floating"),
	TO_ENUM(ALPHA_subg, "Subtract G_floating"),
	TO_ENUM(ALPHA_subl, "Subtract longword"),
	TO_ENUM(ALPHA_subl_v, "Subtract longword with overflow"),
	TO_ENUM(ALPHA_subq, "Subtract quadword"),
	TO_ENUM(ALPHA_subq_v, "Subtract quadword with overflow"),
	TO_ENUM(ALPHA_subs, "Subtract S_floating"),
	TO_ENUM(ALPHA_subt, "Subtract T_floating"),
	TO_ENUM(ALPHA_trapb, "Trap barrier"),
	TO_ENUM(ALPHA_umulh, "Unsigned multiply quadword high"),
	TO_ENUM(ALPHA_unpkbl, "Unpack bytes to longwords"),
	TO_ENUM(ALPHA_unpkbw, "Unpack bytes to words"),
	TO_ENUM(ALPHA_wh64, "Write hint 64 bytes"),
	TO_ENUM(ALPHA_wmb, "Write memory barrier"),
	TO_ENUM(ALPHA_xor, "Logical difference"),
	TO_ENUM(ALPHA_zap, "Zero bytes"),
	TO_ENUM(ALPHA_zapnot, "Zero bytes not"),
	TO_ENUM(ALPHA_unop, "Universal NOP"),
	TO_ENUM(ALPHA_nop, "Integer NOP"),
	TO_ENUM(ALPHA_fnop, "Floating point NOP"),
	TO_ENUM(ALPHA_clr, "Clear"),
	TO_ENUM(ALPHA_fabs, "Floating point absolute value"),
	TO_ENUM(ALPHA_fclr, "Floating point clear"),
	TO_ENUM(ALPHA_fmov, "Floating point register move"),
	TO_ENUM(ALPHA_fneg, "Floating point negate"),
	TO_ENUM(ALPHA_mov, "Move to register"),
	TO_ENUM(ALPHA_negl, "Negate longword"),
	TO_ENUM(ALPHA_negl_v, "Negate longword with overflow"),
	TO_ENUM(ALPHA_negq, "Negate quadword"),
	TO_ENUM(ALPHA_negq_v, "Negate quadword with overflow"),
	TO_ENUM(ALPHA_negf, "Negate F_floating"),
	TO_ENUM(ALPHA_negg, "Negate G_floating"),
	TO_ENUM(ALPHA_negs, "Negate S_floating"),
	TO_ENUM(ALPHA_negt, "Negate T_floating"),
	TO_ENUM(ALPHA_not, "Bitwise NOT"),
	TO_ENUM(ALPHA_sextl, "Move sign extended"),
	TO_ENUM(ALPHA_or, "Bitwise OR"),
	TO_ENUM(ALPHA_andnot, "Bit clear"),
	TO_ENUM(ALPHA_xornot, "Logical equivalence"),
	TO_ENUM(ALPHA_br0, "Branch"),
	TO_ENUM(ALPHA_last, "Undocumented instruction ALPHA_last")
};
