auto instructions_PLFM_M7900 = flags_vector_t{
	TO_ENUM(m7900_null, "Undocumented instruction m7900_null"),
	TO_ENUM(m7900_abs, "ABSolute"),
	TO_ENUM(m7900_absd, "ABSolute at Double-word"),
	TO_ENUM(m7900_adc, "ADd with Carry"),
	TO_ENUM(m7900_adcb, "ADd with Carry at Byte"),
	TO_ENUM(m7900_adcd, "ADd with Carry at Double-word"),
	TO_ENUM(m7900_add, "Addition"),
	TO_ENUM(m7900_addb, "ADD at Byte"),
	TO_ENUM(m7900_addd, "ADD at Double-word"),
	TO_ENUM(m7900_addm, "ADD immediate and Memory"),
	TO_ENUM(m7900_addmb, "ADD immediate and Memory at Byte"),
	TO_ENUM(m7900_addmd, "ADD immediate and Memory at Double-word"),
	TO_ENUM(m7900_adds, "ADD Stack pointer and immediate"),
	TO_ENUM(m7900_addx, "ADD index register X and immediate"),
	TO_ENUM(m7900_addy, "ADD index register Y and immediate"),
	TO_ENUM(m7900_and, "Logical AND"),
	TO_ENUM(m7900_andb, "logical AND between immediate (Byte)"),
	TO_ENUM(m7900_andm, "logical AND between immediate value and Memory"),
	TO_ENUM(m7900_andmb, "logical AND between immediate value and Memory (Byte)"),
	TO_ENUM(m7900_andmd, "logical AND between immediate value and Memory (Double word)"),
	TO_ENUM(m7900_asl, "Arithmetic Shift to Left"),
	TO_ENUM(m7900_asln, "Arithmetic Shift to Left by n bits"),
	TO_ENUM(m7900_asldn, "Arithmetic Shift to Left by n bits (Double word)"),
	TO_ENUM(m7900_asr, "Arithmeticshift to the right"),
	TO_ENUM(m7900_asrn, "Arithmetic Shift to Right by n bits"),
	TO_ENUM(m7900_asrdn, "Arithmetic Shift to Right by n bits (Double word)"),
	TO_ENUM(m7900_bbc, "Branch on Bit Clear"),
	TO_ENUM(m7900_bbcb, "Branch on Bit Clear (Byte)"),
	TO_ENUM(m7900_bbs, "Branch on Bit Set"),
	TO_ENUM(m7900_bbsb, "Branch on Bit Set (Byte)"),
	TO_ENUM(m7900_bcc, "Branch on Carry Clear"),
	TO_ENUM(m7900_bcs, "Branch on Carry Set"),
	TO_ENUM(m7900_beq, "Branch on EQual"),
	TO_ENUM(m7900_bge, "Branch on Greater or Equal"),
	TO_ENUM(m7900_bgt, "Branch on Greater Than"),
	TO_ENUM(m7900_bgtu, "Branch on Greater Than with Unsign"),
	TO_ENUM(m7900_ble, "Branch on Less or Equal"),
	TO_ENUM(m7900_bleu, "Branch on Less Equal with Unsign"),
	TO_ENUM(m7900_blt, "Branch on Less Than"),
	TO_ENUM(m7900_bmi, "Branch on result MInus"),
	TO_ENUM(m7900_bne, "Branch on Not Equal"),
	TO_ENUM(m7900_bpl, "Branch on result PLus"),
	TO_ENUM(m7900_bra, "BRanch Always"),
	TO_ENUM(m7900_bral, "BRanch Always"),
	TO_ENUM(m7900_brk, "force BReaK"),
	TO_ENUM(m7900_bsc, "Branch on Single bit Clear"),
	TO_ENUM(m7900_bsr, "Branch to SubRoutine"),
	TO_ENUM(m7900_bss, "Branch on Single bit Set"),
	TO_ENUM(m7900_bvc, "Branch on oVerflow Clear"),
	TO_ENUM(m7900_bvs, "Branch on oVerflow Set"),
	TO_ENUM(m7900_cbeq, "Compare immediate and Branch on EQual"),
	TO_ENUM(m7900_cbeqb, "Compare immediate and Branch on EQual at Byte"),
	TO_ENUM(m7900_cbne, "Compare immediate and Branch on Not Equal"),
	TO_ENUM(m7900_cbneb, "Compare immediate and Branch on Not Equal at Byte"),
	TO_ENUM(m7900_clc, "CLear Carry flag"),
	TO_ENUM(m7900_cli, "CLear Interrupt disable status"),
	TO_ENUM(m7900_clm, "CLear M flag"),
	TO_ENUM(m7900_clp, "CLear Processor status"),
	TO_ENUM(m7900_clr, "CLeaR accumulator"),
	TO_ENUM(m7900_clrb, "CLeaR accumulator at Byte"),
	TO_ENUM(m7900_clrm, "CLeaR Memory"),
	TO_ENUM(m7900_clrmb, "CLeaR Memory at Byte"),
	TO_ENUM(m7900_clrx, "CLeaR index register X"),
	TO_ENUM(m7900_clry, "CLeaR index register Y"),
	TO_ENUM(m7900_clv, "CLear oVerflow flag"),
	TO_ENUM(m7900_cmp, "CoMPare"),
	TO_ENUM(m7900_cmpb, "CoMPare at Byte"),
	TO_ENUM(m7900_cmpd, "CoMPare at Double-word"),
	TO_ENUM(m7900_cmpm, "CoMPare immediate with Memory"),
	TO_ENUM(m7900_cmpmb, "CoMPare immediate with Memory at Byte"),
	TO_ENUM(m7900_cmpmd, "CoMPare immediate with Memory at Double-word"),
	TO_ENUM(m7900_cpx, "ComPare memory and index register X"),
	TO_ENUM(m7900_cpy, "ComPare memory and index register Y"),
	TO_ENUM(m7900_debne, "DEcrement memory and Branch on Not Equal"),
	TO_ENUM(m7900_dec, "DECrement by one"),
	TO_ENUM(m7900_dex, "DEcrement index register X by one"),
	TO_ENUM(m7900_dey, "DEcrement index register Y by one"),
	TO_ENUM(m7900_div, "DIVide unsigned"),
	TO_ENUM(m7900_divs, "DIVide with Sign"),
	TO_ENUM(m7900_dxbne, "Decrement index register X and Branch on Not Equal"),
	TO_ENUM(m7900_dybne, "Decrement index register Y and Branch on Not Equal"),
	TO_ENUM(m7900_eor, "Exclusive OR memory with accumulator"),
	TO_ENUM(m7900_eorb, "Exclusive OR immediate with accumulator at Byte"),
	TO_ENUM(m7900_eorm, "Exclusive OR immediate with Memory"),
	TO_ENUM(m7900_eormb, "Exclusive OR immediate with Memory at Byte"),
	TO_ENUM(m7900_eormd, "Exclusive OR immediate with Memory at Double-word"),
	TO_ENUM(m7900_exts, "EXTension Sign"),
	TO_ENUM(m7900_extsd, "EXTension Sign at Double-word"),
	TO_ENUM(m7900_extz, "EXTension Zero"),
	TO_ENUM(m7900_extzd, "EXTension Zero at Double-word"),
	TO_ENUM(m7900_inc, "INCrement by one"),
	TO_ENUM(m7900_inx, "INcrement index register X by one"),
	TO_ENUM(m7900_iny, "INcrement index register y by one"),
	TO_ENUM(m7900_jmp, "Jump"),
	TO_ENUM(m7900_jmpl, "Jump"),
	TO_ENUM(m7900_jsr, "Jump to SubRoutine"),
	TO_ENUM(m7900_jsrl, "Jump to SubRoutine"),
	TO_ENUM(m7900_lda, "LoaD Accumulator from memory"),
	TO_ENUM(m7900_ldab, "LoaD Accumulator from memory at Byte"),
	TO_ENUM(m7900_ldad, "LoaD Accumulator from memory at Double-word"),
	TO_ENUM(m7900_lddn, "LoaD immediate to Direct page register n"),
	TO_ENUM(m7900_ldt, "LoaD immediate to DaTa bank register"),
	TO_ENUM(m7900_ldx, "LoaD index register X from memory"),
	TO_ENUM(m7900_ldxb, "LoaD index register X from memory at Byte"),
	TO_ENUM(m7900_ldy, "LoaD index register Y from memory"),
	TO_ENUM(m7900_ldyb, "LoaD index register Y from memory at Byte"),
	TO_ENUM(m7900_lsr, "Logical Shift Right"),
	TO_ENUM(m7900_lsrn, "Logical n bits Shift Right"),
	TO_ENUM(m7900_lsrdn, "Logical n bits Shift Right at Double-word"),
	TO_ENUM(m7900_movm, "MOVe Memory to memory"),
	TO_ENUM(m7900_movmb, "MOVe Memory to memory at Byte"),
	TO_ENUM(m7900_movr, "MOVe Repeat memory to memory"),
	TO_ENUM(m7900_movrb, "MOVe Repeat memory to memory at Byte"),
	TO_ENUM(m7900_mpy, "MultiPlY"),
	TO_ENUM(m7900_mpys, "MultiPlY with Sign"),
	TO_ENUM(m7900_mvn, "MoVe Negative"),
	TO_ENUM(m7900_mvp, "MoVe Positive"),
	TO_ENUM(m7900_neg, "NEGative"),
	TO_ENUM(m7900_negd, "NEGative at Double-word"),
	TO_ENUM(m7900_nop, "No OPeration"),
	TO_ENUM(m7900_ora, "OR memory with Accumulator"),
	TO_ENUM(m7900_orab, "OR immediate with Accumulator at Byte"),
	TO_ENUM(m7900_oram, "OR immediAte with Memory"),
	TO_ENUM(m7900_oramb, "OR immediAte with Memory at Byte"),
	TO_ENUM(m7900_oramd, "OR immediAte with Memory at Double-word"),
	TO_ENUM(m7900_pea, "Push Effective Address"),
	TO_ENUM(m7900_pei, "Push Effective Indirect address"),
	TO_ENUM(m7900_per, "Push Effective program counter Relative address"),
	TO_ENUM(m7900_pha, "PusH accumulator A on stack"),
	TO_ENUM(m7900_phb, "PusH accumulator B on stack"),
	TO_ENUM(m7900_phd, "PusH Direct page register on stack"),
	TO_ENUM(m7900_phdn, "PusH Direct page register n on stack"),
	TO_ENUM(m7900_phg, "PusH proGram bank register on stack"),
	TO_ENUM(m7900_phldn, "PusH dpr n to stack and Load immediate to Dpr n"),
	TO_ENUM(m7900_php, "PusH Processor status on stack"),
	TO_ENUM(m7900_pht, "PusH daTa bank register on stack"),
	TO_ENUM(m7900_phx, "PusH index register X on stack"),
	TO_ENUM(m7900_phy, "PusH index register Y on stack"),
	TO_ENUM(m7900_pla, "PuLl accumulator A from stack"),
	TO_ENUM(m7900_plb, "PuLl accumulator B from stack"),
	TO_ENUM(m7900_pld, "PuLl Direct page register from stack"),
	TO_ENUM(m7900_pldn, "PuLl Direct page register n from stack"),
	TO_ENUM(m7900_plp, "PuLl Processor status from stack"),
	TO_ENUM(m7900_plt, "PuLl daTa bank register from stack"),
	TO_ENUM(m7900_plx, "PuLl index register X from stack"),
	TO_ENUM(m7900_ply, "PuLl index register Y from stack"),
	TO_ENUM(m7900_psh, "PuSH"),
	TO_ENUM(m7900_pul, "PuLl"),
	TO_ENUM(m7900_rla, "Rotate Left accumulator A"),
	TO_ENUM(m7900_rmpa, "Repeat Multiply and Accumulate"),
	TO_ENUM(m7900_rol, "ROtate one bit Left"),
	TO_ENUM(m7900_roln, "n bits ROtate Left"),
	TO_ENUM(m7900_roldn, "n bits ROtate Left at Double-word"),
	TO_ENUM(m7900_ror, "ROtate one bit Right"),
	TO_ENUM(m7900_rorn, "n bits ROtate Right"),
	TO_ENUM(m7900_rordn, "n bits ROtate Right at Double-word"),
	TO_ENUM(m7900_rti, "Return from Interrupt"),
	TO_ENUM(m7900_rtl, "ReTurn from subroutine Long"),
	TO_ENUM(m7900_rtld, "ReTurn from subroutine Long and pull Direct page register n"),
	TO_ENUM(m7900_rts, "ReTurn from Subroutine"),
	TO_ENUM(m7900_rtsdn, "ReTurn from Subroutine and pull Direct page register n"),
	TO_ENUM(m7900_sbc, "SuBtract with Carry"),
	TO_ENUM(m7900_sbcb, "SuBtract with Carry at Byte"),
	TO_ENUM(m7900_sbcd, "SuBtract with Carry at Double-word"),
	TO_ENUM(m7900_sec, "SEt Carry flag"),
	TO_ENUM(m7900_sei, "SEt Interrupt disable status"),
	TO_ENUM(m7900_sem, "SEt M flag"),
	TO_ENUM(m7900_sep, "SEt Processor status"),
	TO_ENUM(m7900_sta, "STore Accumulator in memory"),
	TO_ENUM(m7900_stab, "STore Accumulator in memory at Byte"),
	TO_ENUM(m7900_stad, "STore Accumulator in memory at Double-word"),
	TO_ENUM(m7900_stp, "SToP"),
	TO_ENUM(m7900_stx, "STore index register X in memory"),
	TO_ENUM(m7900_sty, "STore index register Y in memory"),
	TO_ENUM(m7900_sub, "SUBtract"),
	TO_ENUM(m7900_subb, "SUBtract at Byte"),
	TO_ENUM(m7900_subd, "SUBtract at Double-word"),
	TO_ENUM(m7900_subm, "SUBtract immediate from Memory"),
	TO_ENUM(m7900_submb, "SUBtract immediate from Memory at Byte"),
	TO_ENUM(m7900_submd, "SUBtract immediate from Memory at Double-word"),
	TO_ENUM(m7900_subs, "SUBtract Stack pointer"),
	TO_ENUM(m7900_subx, "SUBtract immediate from index register X"),
	TO_ENUM(m7900_suby, "SUBtract immediate from index register Y"),
	TO_ENUM(m7900_tadn, "Transfer accumulator A to Direct page register n"),
	TO_ENUM(m7900_tas, "Transfer accumulator A to Stack pointer"),
	TO_ENUM(m7900_tax, "Transfer accumulator A to index register X"),
	TO_ENUM(m7900_tay, "Transfer accumulator A to index register Y"),
	TO_ENUM(m7900_tbdn, "Transfer accumulator B to Direct page register n"),
	TO_ENUM(m7900_tbs, "Transfer accumulator B to Stack pointer"),
	TO_ENUM(m7900_tbx, "Transfer accumulator B to index register X"),
	TO_ENUM(m7900_tby, "Transfer accumulator B to index register Y"),
	TO_ENUM(m7900_tdan, "Transfer Direct page register n to accumulator A"),
	TO_ENUM(m7900_tdbn, "Transfer Direct page register n to accumulator B"),
	TO_ENUM(m7900_tds, "Transfer Direct page register to Stack pointer"),
	TO_ENUM(m7900_tsa, "Transfer Stack pointer to accumulator A"),
	TO_ENUM(m7900_tsb, "Transfer Stack pointer to accumulator B"),
	TO_ENUM(m7900_tsd, "Transfer Stack pointer to Direct page register"),
	TO_ENUM(m7900_tsx, "Transfer Stack pointer to index register X"),
	TO_ENUM(m7900_txa, "Transfer index register X to accumulator A"),
	TO_ENUM(m7900_txb, "Transfer index register X to accumulator B"),
	TO_ENUM(m7900_txs, "Transfer index register X to Stack pointer"),
	TO_ENUM(m7900_txy, "Transfer index register X to Y"),
	TO_ENUM(m7900_tya, "Transfer index register Y to accumulator A"),
	TO_ENUM(m7900_tyb, "Transfer index register Y to accumulator B"),
	TO_ENUM(m7900_tyx, "Transfer index register Y to X"),
	TO_ENUM(m7900_wit, "WaIT"),
	TO_ENUM(m7900_xab, "eXchange accumulator A and B"),
	TO_ENUM(m7900_last, "Undocumented instruction m7900_last")
};
