auto instructions_PLFM_H8500 = flags_vector_t{
	TO_ENUM(H8500_null, "Undocumented instruction H8500_null"),
	TO_ENUM(H8500_mov_g, "B/W Move data"),
	TO_ENUM(H8500_mov_e, "B   Move data"),
	TO_ENUM(H8500_mov_i, "W   Move data"),
	TO_ENUM(H8500_mov_f, "B/W Move data"),
	TO_ENUM(H8500_mov_l, "B/W Move data"),
	TO_ENUM(H8500_mov_s, "B/W Move data"),
	TO_ENUM(H8500_ldm, "W   Pop data from the stack to one or more registers"),
	TO_ENUM(H8500_stm, "W   Push data from one or more registers onto the stack"),
	TO_ENUM(H8500_xch, "W   Exchange data between two general registers"),
	TO_ENUM(H8500_swap, "B   Exchange the upper and lower bytes in a general register"),
	TO_ENUM(H8500_movtpe, "B   Transfer data from a general register to memory"),
	TO_ENUM(H8500_movfpe, "B   Transfer data from memory to a general register"),
	TO_ENUM(H8500_add_g, "B/W Addition"),
	TO_ENUM(H8500_add_q, "B/W Addition"),
	TO_ENUM(H8500_sub, "B/W Subtraction"),
	TO_ENUM(H8500_adds, "B/W Addition"),
	TO_ENUM(H8500_subs, "B/W Subtraction"),
	TO_ENUM(H8500_addx, "B/W Addition with carry"),
	TO_ENUM(H8500_subx, "B/W Subtraction with borrow"),
	TO_ENUM(H8500_dadd, "B   Decimal addition"),
	TO_ENUM(H8500_dsub, "B   Decimal subtraction"),
	TO_ENUM(H8500_mulxu, "B/W Unsigned multiplication"),
	TO_ENUM(H8500_divxu, "B/W Unsigned division"),
	TO_ENUM(H8500_cmp_g, "B/W Compare data"),
	TO_ENUM(H8500_cmp_e, "B   Compare data"),
	TO_ENUM(H8500_cmp_i, "W   Compare data"),
	TO_ENUM(H8500_exts, "B   Convert byte to word by extending the sign bit"),
	TO_ENUM(H8500_extu, "B   Convert byte to word data by padding with zero bits"),
	TO_ENUM(H8500_tst, "B/W Compare with 0"),
	TO_ENUM(H8500_neg, "B/W Negate"),
	TO_ENUM(H8500_clr, "B/W Make zero"),
	TO_ENUM(H8500_tas, "B   Test and set"),
	TO_ENUM(H8500_and, "B/W Logical AND"),
	TO_ENUM(H8500_or, "B/W Logical OR"),
	TO_ENUM(H8500_xor, "B/W Exclusive OR"),
	TO_ENUM(H8500_not, "B/W Bitwise NOT"),
	TO_ENUM(H8500_shal, "B/W Arithmetic shift left"),
	TO_ENUM(H8500_shar, "B/W Arithmetic shift right"),
	TO_ENUM(H8500_shll, "B/W Logical shift left"),
	TO_ENUM(H8500_shlr, "B/W Logical shift right"),
	TO_ENUM(H8500_rotl, "B/W Rotate left"),
	TO_ENUM(H8500_rotr, "B/W Rotate right"),
	TO_ENUM(H8500_rotxl, "B/W Rotate through carry left"),
	TO_ENUM(H8500_rotxr, "B/W Rotate through carry right"),
	TO_ENUM(H8500_bset, "B/W Test bit and set"),
	TO_ENUM(H8500_bclr, "B/W Test bit and clear"),
	TO_ENUM(H8500_bnot, "B/W Test bit and invert"),
	TO_ENUM(H8500_btst, "B/W Test bit"),
	TO_ENUM(H8500_bra, "Branch Always"),
	TO_ENUM(H8500_brn, "Branch Never"),
	TO_ENUM(H8500_bhi, "Branch if High (C|Z = 0)"),
	TO_ENUM(H8500_bls, "Branch if Low or Same (C|Z = 1)"),
	TO_ENUM(H8500_bcc, "Branch if Carry Clear (C = 0)"),
	TO_ENUM(H8500_bcs, "Branch if Carry Set (C = 1)"),
	TO_ENUM(H8500_bne, "Branch if Not Equal (Z = 0)"),
	TO_ENUM(H8500_beq, "Branch if Equal (Z = 1)"),
	TO_ENUM(H8500_bvc, "Branch if Overflow Clear (V = 0)"),
	TO_ENUM(H8500_bvs, "Branch if Overflow Set (V = 1)"),
	TO_ENUM(H8500_bpl, "Branch if Plus (N = 0)"),
	TO_ENUM(H8500_bmi, "Branch if Minus (N = 1)"),
	TO_ENUM(H8500_bge, "Branch if Greater or Equal (N^V = 0)"),
	TO_ENUM(H8500_blt, "Branch if Less Than (N^V = 1)"),
	TO_ENUM(H8500_bgt, "Branch if Greater Than (Z|(N^V) = 0)"),
	TO_ENUM(H8500_ble, "Branch if Less or Equal (Z|(N^V) = 1)"),
	TO_ENUM(H8500_jmp, "Branch unconditionally (same page)"),
	TO_ENUM(H8500_pjmp, "Branch unconditionally (specified page)"),
	TO_ENUM(H8500_bsr, "Branch to subroutine (same page)"),
	TO_ENUM(H8500_jsr, "Branch to subroutine (same page)"),
	TO_ENUM(H8500_pjsr, "Branch to subroutine (specified page)"),
	TO_ENUM(H8500_rts, "Return from subroutine (same page)"),
	TO_ENUM(H8500_prts, "Return from subroutine (different page)"),
	TO_ENUM(H8500_rtd, "Return from subroutine (same page) and adjust SP"),
	TO_ENUM(H8500_prtd, "Return from subroutine (different page) and adjust SP"),
	TO_ENUM(H8500_scb, "Control loop"),
	TO_ENUM(H8500_trapa, "Generate trap exception"),
	TO_ENUM(H8500_trap_vs, "Generate trap exception if the V bit is set"),
	TO_ENUM(H8500_rte, "Return from exception-handling routine"),
	TO_ENUM(H8500_link, "Create stack frame"),
	TO_ENUM(H8500_unlk, "Deallocate stack frame"),
	TO_ENUM(H8500_sleep, "Go to power-down state"),
	TO_ENUM(H8500_ldc, "B/W Move to control register"),
	TO_ENUM(H8500_stc, "B/W Move from control register"),
	TO_ENUM(H8500_andc, "B/W Logically AND control register"),
	TO_ENUM(H8500_orc, "B/W Logically OR control register"),
	TO_ENUM(H8500_xorc, "B/W Logically exclusive-OR control register"),
	TO_ENUM(H8500_nop, "No operation"),
	TO_ENUM(H8500_bpt, "Undocumented instruction H8500_bpt"),
	TO_ENUM(H8500_last, "Undocumented instruction H8500_last")
};
