auto instructions_PLFM_NEC_V850X = flags_vector_t{
	TO_ENUM(NEC850_Instructions, "Undocumented instruction NEC850_Instructions"),
	TO_ENUM(NEC850_NULL, "Undocumented instruction NEC850_NULL"),
	TO_ENUM(NEC850_BREAKPOINT, "undefined instruction"),
	TO_ENUM(NEC850_XORI, "Exclusive Or Immediate"),
	TO_ENUM(NEC850_XOR, "Exclusive OR"),
	TO_ENUM(NEC850_TST1, "Test bit"),
	TO_ENUM(NEC850_TST, "Test"),
	TO_ENUM(NEC850_TRAP, "Software trap"),
	TO_ENUM(NEC850_SUBR, "Substract reverse"),
	TO_ENUM(NEC850_SUB, "Substract"),
	TO_ENUM(NEC850_STSR, "Store Contents of System Register"),
	TO_ENUM(NEC850_ST_B, "Store byte"),
	TO_ENUM(NEC850_ST_H, "Store half-word"),
	TO_ENUM(NEC850_ST_W, "Store word"),
	TO_ENUM(NEC850_SST_B, "Store byte (use EP)"),
	TO_ENUM(NEC850_SST_H, "Store half-word (use EP)"),
	TO_ENUM(NEC850_SST_W, "Store word (use EP)"),
	TO_ENUM(NEC850_SLD_B, "Load byte (use EP)"),
	TO_ENUM(NEC850_SLD_H, "Load half-word (use EP)"),
	TO_ENUM(NEC850_SLD_W, "Load word (use EP)"),
	TO_ENUM(NEC850_SHR, "Shift Logical Right"),
	TO_ENUM(NEC850_SHL, "Shift Logical Left"),
	TO_ENUM(NEC850_SET1, "Set Bit"),
	TO_ENUM(NEC850_SETF, "Set register to 1 if condition is satisfied"),
	TO_ENUM(NEC850_SATSUBR, "Saturated Subtract Reverse"),
	TO_ENUM(NEC850_SATSUBI, "Saturated Subtract Immediate"),
	TO_ENUM(NEC850_SATSUB, "Saturated Subtract"),
	TO_ENUM(NEC850_SATADD, "Saturated Add"),
	TO_ENUM(NEC850_SAR, "Shift Arithmetic Right"),
	TO_ENUM(NEC850_RETI, "Return from Trap or Interrupt"),
	TO_ENUM(NEC850_ORI, "OR immediate"),
	TO_ENUM(NEC850_OR, "OR"),
	TO_ENUM(NEC850_NOT1, "Not Bit"),
	TO_ENUM(NEC850_NOT, "Not"),
	TO_ENUM(NEC850_NOP, "No Operation"),
	TO_ENUM(NEC850_MULHI, "Multiply Half-Word Immediate"),
	TO_ENUM(NEC850_MULH, "Multiply Half-Word"),
	TO_ENUM(NEC850_MOVHI, "Move High Half-Word"),
	TO_ENUM(NEC850_MOVEA, "Move Effective Address"),
	TO_ENUM(NEC850_MOV, "Move"),
	TO_ENUM(NEC850_LDSR, "Load to system register"),
	TO_ENUM(NEC850_LD_B, "Load byte"),
	TO_ENUM(NEC850_LD_H, "Load half-word"),
	TO_ENUM(NEC850_LD_W, "Load word"),
	TO_ENUM(NEC850_JR, "Jump Relative"),
	TO_ENUM(NEC850_JMP, "Jump Register"),
	TO_ENUM(NEC850_JARL, "Jump and Register Link"),
	TO_ENUM(NEC850_HALT, "Halt"),
	TO_ENUM(NEC850_EI, "Enable interrupt"),
	TO_ENUM(NEC850_DIVH, "Divide Half-Word"),
	TO_ENUM(NEC850_DI, "Disable Interrupt"),
	TO_ENUM(NEC850_CMP, "Compare"),
	TO_ENUM(NEC850_CLR1, "Clear bit"),
	TO_ENUM(NEC850_BV, "Branch if overflow"),
	TO_ENUM(NEC850_BL, "Branch if less"),
	TO_ENUM(NEC850_BZ, "Branch if zero"),
	TO_ENUM(NEC850_BNH, "Branch if not higher"),
	TO_ENUM(NEC850_BN, "Branch if negative"),
	TO_ENUM(NEC850_BR, "Branch if always"),
	TO_ENUM(NEC850_BLT, "Branch if less than (signed)"),
	TO_ENUM(NEC850_BLE, "Branch if less than or equal (signed)"),
	TO_ENUM(NEC850_BNV, "Branch if no overflow"),
	TO_ENUM(NEC850_BNC, "Branch if no carry"),
	TO_ENUM(NEC850_BNZ, "Branch if not zero"),
	TO_ENUM(NEC850_BH, "Branch if higher than"),
	TO_ENUM(NEC850_BP, "Branch if positive"),
	TO_ENUM(NEC850_BSA, "Branch if saturated"),
	TO_ENUM(NEC850_BGE, "Branch if greater than or equal (signed)"),
	TO_ENUM(NEC850_BGT, "Branch if greater than (signed)"),
	TO_ENUM(NEC850_ANDI, "And immediate"),
	TO_ENUM(NEC850_AND, "And"),
	TO_ENUM(NEC850_ADDI, "Add Immediate"),
	TO_ENUM(NEC850_ADD, "Add"),
	TO_ENUM(NEC850_SWITCH, "Jump with table look up"),
	TO_ENUM(NEC850_ZXB, "Zero-extend byte"),
	TO_ENUM(NEC850_SXB, "Sign-extend byte"),
	TO_ENUM(NEC850_ZXH, "Zero-extend halfword"),
	TO_ENUM(NEC850_SXH, "Sign-extend halfword"),
	TO_ENUM(NEC850_DISPOSE_r0, "Function dispose"),
	TO_ENUM(NEC850_DISPOSE_r, "Function dispose"),
	TO_ENUM(NEC850_CALLT, "Call with table look up"),
	TO_ENUM(NEC850_DBTRAP, "Debug trap"),
	TO_ENUM(NEC850_DBRET, "Return from debug trap or interrupt"),
	TO_ENUM(NEC850_CTRET, "Return from CALLT"),
	TO_ENUM(NEC850_SASF, "Shift and set flag condition"),
	TO_ENUM(NEC850_PREPARE_sp, "Function prepare"),
	TO_ENUM(NEC850_PREPARE_i, "Function prepare"),
	TO_ENUM(NEC850_MUL, "Multiply word"),
	TO_ENUM(NEC850_MULU, "Multiply word unsigned"),
	TO_ENUM(NEC850_DIVH_r3, "Divide halfword"),
	TO_ENUM(NEC850_DIVHU, "Divide halfword unsigned"),
	TO_ENUM(NEC850_DIV, "Divide word"),
	TO_ENUM(NEC850_DIVU, "Divide word unsigned"),
	TO_ENUM(NEC850_BSW, "Byte swap word"),
	TO_ENUM(NEC850_BSH, "Byte swap halfword"),
	TO_ENUM(NEC850_HSW, "Halfword swap word"),
	TO_ENUM(NEC850_CMOV, "Conditional move"),
	TO_ENUM(NEC850_SLD_BU, "Short format load byte unsigned"),
	TO_ENUM(NEC850_SLD_HU, "Short format load halfword unsigned"),
	TO_ENUM(NEC850_LD_BU, "load byte unsigned"),
	TO_ENUM(NEC850_LD_HU, "load halfword unsigned"),
	TO_ENUM(NEC850_ADF, "Add on condition flag"),
	TO_ENUM(NEC850_HSH, "Halfword swap halfword"),
	TO_ENUM(NEC850_MAC, "Multiply and add word"),
	TO_ENUM(NEC850_MACU, "Multiply and add word unsigned"),
	TO_ENUM(NEC850_SBF, "Subtract on condition flag"),
	TO_ENUM(NEC850_SCH0L, "Search zero from left"),
	TO_ENUM(NEC850_SCH0R, "Search zero from right"),
	TO_ENUM(NEC850_SCH1L, "Search one from left"),
	TO_ENUM(NEC850_SCH1R, "Search one from right"),
	TO_ENUM(NEC850_CAXI, "Compare and exchange for interlock"),
	TO_ENUM(NEC850_DIVQ, "Divide word quickly"),
	TO_ENUM(NEC850_DIVQU, "Divide word unsigned quickly"),
	TO_ENUM(NEC850_EIRET, "Return from EI level exception"),
	TO_ENUM(NEC850_FERET, "Return from FE level exception"),
	TO_ENUM(NEC850_FETRAP, "FE-level Trap"),
	TO_ENUM(NEC850_RMTRAP, "Runtime monitor trap"),
	TO_ENUM(NEC850_RIE, "Reserved instruction exception"),
	TO_ENUM(NEC850_SYNCE, "Synchronize exceptions"),
	TO_ENUM(NEC850_SYNCM, "Synchronize memory"),
	TO_ENUM(NEC850_SYNCP, "Synchronize pipeline"),
	TO_ENUM(NEC850_SYSCALL, "System call"),
	TO_ENUM(NEC850_CVT_SW, "Real to integer conversion"),
	TO_ENUM(NEC850_TRNC_SW, "Real to integer conversion"),
	TO_ENUM(NEC850_CVT_WS, "Integer to real conversion"),
	TO_ENUM(NEC850_LDFC, "Load to Floating Controls"),
	TO_ENUM(NEC850_LDFF, "Load to Floating Flags"),
	TO_ENUM(NEC850_STFC, "Store Floating Controls"),
	TO_ENUM(NEC850_STFF, "Store Floating Flags"),
	TO_ENUM(NEC850_TRFF, "Transfer Floating Flags"),
	TO_ENUM(NEC850_ABSF_D, "Floating-point Absolute Value (Double)"),
	TO_ENUM(NEC850_ABSF_S, "Floating-point Absolute Value (Single)"),
	TO_ENUM(NEC850_ADDF_D, "Floating-point Add (Double)"),
	TO_ENUM(NEC850_ADDF_S, "Floating-point Add (Single)"),
	TO_ENUM(NEC850_DIVF_D, "Floating-point Divide (Double)"),
	TO_ENUM(NEC850_DIVF_S, "Floating-point Divide (Single)"),
	TO_ENUM(NEC850_MAXF_D, "Floating-point Maximum (Double)"),
	TO_ENUM(NEC850_MAXF_S, "Floating-point Maximum (Single)"),
	TO_ENUM(NEC850_MINF_D, "Floating-point Minimum (Double)"),
	TO_ENUM(NEC850_MINF_S, "Floating-point Minimum (Single)"),
	TO_ENUM(NEC850_MULF_D, "Floating-point Multiply (Double)"),
	TO_ENUM(NEC850_MULF_S, "Floating-point Multiply (Single)"),
	TO_ENUM(NEC850_NEGF_D, "Floating-point Negate (Double)"),
	TO_ENUM(NEC850_NEGF_S, "Floating-point Negate (Single)"),
	TO_ENUM(NEC850_RECIPF_D, "Reciprocal of a floating-point value (Double)"),
	TO_ENUM(NEC850_RECIPF_S, "Reciprocal of a floating-point value (Single"),
	TO_ENUM(NEC850_RSQRTF_D, "Reciprocal of the square root of a floating-point value (Double)"),
	TO_ENUM(NEC850_RSQRTF_S, "Reciprocal of the square root of a floating-point value (Single)"),
	TO_ENUM(NEC850_SQRTF_D, "Floating-point Square Root (Double)"),
	TO_ENUM(NEC850_SQRTF_S, "Floating-point Square Root (Single)"),
	TO_ENUM(NEC850_SUBF_D, "Floating-point Subtract (Double)"),
	TO_ENUM(NEC850_SUBF_S, "Floating-point Subtract (Single)"),
	TO_ENUM(NEC850_MADDF_S, "Floating-point Multiply-Add (Single)"),
	TO_ENUM(NEC850_MSUBF_S, "Floating-point Multiply-Subtract (Single)"),
	TO_ENUM(NEC850_NMADDF_S, "Floating-point Negate Multiply-Add (Single)"),
	TO_ENUM(NEC850_NMSUBF_S, "Floating-point Negate Multiply-Subtract (Single)"),
	TO_ENUM(NEC850_CEILF_DL, "Floating-point Truncate to Long Fixed-point Format, rounded toward +inf (Double)"),
	TO_ENUM(NEC850_CEILF_DW, "Floating-point Truncate to Single Fixed-point Format, rounded toward +inf (Double)"),
	TO_ENUM(NEC850_CEILF_SL, "Floating-point Truncate to Long Fixed-point Format, rounded toward +inf (Single)"),
	TO_ENUM(NEC850_CEILF_SW, "Floating-point Truncate to Single Fixed-point Format, rounded toward +inf (Single)"),
	TO_ENUM(NEC850_CEILF_DUL, "Floating-point Truncate to Unsigned Long, rounded toward +inf (Double)"),
	TO_ENUM(NEC850_CEILF_DUW, "Floating-point Truncate to Unsigned Word, rounded toward +inf (Double)"),
	TO_ENUM(NEC850_CEILF_SUL, "Floating-point Truncate to Unsigned Long, rounded toward +inf (Single)"),
	TO_ENUM(NEC850_CEILF_SUW, "Floating-point Truncate to Unsigned Word, rounded toward +inf (Single)"),
	TO_ENUM(NEC850_CVTF_DL, "Floating-point Convert to Long Fixed-point Format (Double)"),
	TO_ENUM(NEC850_CVTF_DS, "Floating-point Convert to Single Floating-point Format (Double)"),
	TO_ENUM(NEC850_CVTF_DUL, "Floating-point Convert Double to Unsigned-Long (Double)"),
	TO_ENUM(NEC850_CVTF_DUW, "Floating-point Convert Double to Unsigned-Word (Double)"),
	TO_ENUM(NEC850_CVTF_DW, "Floating-point Convert to Single Fixed-point Format (Double)"),
	TO_ENUM(NEC850_CVTF_LD, "Floating-point Convert to Single Floating-point Format (Double)"),
	TO_ENUM(NEC850_CVTF_LS, "Floating-point Convert to Single Floating-point Format (Single)"),
	TO_ENUM(NEC850_CVTF_SD, "Floating-point Convert to Double Floating-point Format (Double)"),
	TO_ENUM(NEC850_CVTF_SL, "Floating-point Convert to Long Fixed-point Format (Single)"),
	TO_ENUM(NEC850_CVTF_SUL, "Floating-point Convert Single to Unsigned-Long (Single)"),
	TO_ENUM(NEC850_CVTF_SUW, "Floating-point Convert Single to Unsigned-Word (Single)"),
	TO_ENUM(NEC850_CVTF_SW, "Floating-point Convert to Single Fixed-point Format (Single)"),
	TO_ENUM(NEC850_CVTF_ULD, "Floating-point Convert Unsigned-Long to Double (Double)"),
	TO_ENUM(NEC850_CVTF_ULS, "Floating-point Convert Unsigned-Long to Single (Single)"),
	TO_ENUM(NEC850_CVTF_UWD, "Floating-point Convert Unsigned-Word to Double (Double)"),
	TO_ENUM(NEC850_CVTF_UWS, "Floating-point Convert Unsigned-Word to Single (Single)"),
	TO_ENUM(NEC850_CVTF_WD, "Floating-point Convert to Single Floating-point Format (Double)"),
	TO_ENUM(NEC850_CVTF_WS, "Floating-point Convert to Single Floating-point Format (Single)"),
	TO_ENUM(NEC850_FLOORF_DL, "Floating-point Truncate to Long Fixed-point Format, rounded toward -inf (Double)"),
	TO_ENUM(NEC850_FLOORF_DW, "Floating-point Truncate to Single Fixed-point Format, rounded toward -inf (Double)"),
	TO_ENUM(NEC850_FLOORF_SL, "Floating-point Truncate to Long Fixed-point Format, rounded toward -inf (Single)"),
	TO_ENUM(NEC850_FLOORF_SW, "Floating-point Truncate to Single Fixed-point Format, rounded toward -inf (Single)"),
	TO_ENUM(NEC850_FLOORF_DUL, "Floating-point Truncate to Unsigned Long, rounded toward -inf (Double)"),
	TO_ENUM(NEC850_FLOORF_DUW, "Floating-point Truncate to Unsigned Word, rounded toward -inf (Double)"),
	TO_ENUM(NEC850_FLOORF_SUL, "Floating-point Truncate to Unsigned Long, rounded toward -inf (Single)"),
	TO_ENUM(NEC850_FLOORF_SUW, "Floating-point Truncate to Unsigned Word, rounded toward -inf (Single)"),
	TO_ENUM(NEC850_TRNCF_DL, "Floating-point Truncate to Long Fixed-point Format, rounded to zero (Double)"),
	TO_ENUM(NEC850_TRNCF_DUL, "Floating-point Truncate Double to Unsigned-Long (Double)"),
	TO_ENUM(NEC850_TRNCF_DUW, "Floating-point Truncate Double to Unsigned-Word (Double)"),
	TO_ENUM(NEC850_TRNCF_DW, "Floating-point Truncate to Single Fixed-point Format, rounded to zero (Double)"),
	TO_ENUM(NEC850_TRNCF_SL, "Floating-point Truncate to Long Fixed-point Format, rounded to zero (Single)"),
	TO_ENUM(NEC850_TRNCF_SUL, "Floating-point Truncate Single to Unsigned-Long (Single)"),
	TO_ENUM(NEC850_TRNCF_SUW, "Floating-point Truncate Single to Unsigned-Word (Single)"),
	TO_ENUM(NEC850_TRNCF_SW, "Floating-point Truncate to Single Fixed-point Format, rounded to zero (Single)"),
	TO_ENUM(NEC850_CMPF_S, "Compares floating-point values (Single)"),
	TO_ENUM(NEC850_CMPF_D, "Compares floating-point values (Double)"),
	TO_ENUM(NEC850_CMOVF_S, "Floating-point conditional move (Single)"),
	TO_ENUM(NEC850_CMOVF_D, "Floating-point conditional move (Double)"),
	TO_ENUM(NEC850_TRFSR, "Transfers specified CC bit to Zero flag in PSW (Single)"),
	TO_ENUM(NEC850_SYNCI, "Synchronize instruction pipeline"),
	TO_ENUM(NEC850_SNOOZE, "Snooze"),
	TO_ENUM(NEC850_BINS, "Bitfield Insert"),
	TO_ENUM(NEC850_ROTL, "Rotate Left"),
	TO_ENUM(NEC850_LOOP, "Loop"),
	TO_ENUM(NEC850_LD_DW, "Load Double Word"),
	TO_ENUM(NEC850_ST_DW, "Store Double Word"),
	TO_ENUM(NEC850_LDL_W, "Load Linked"),
	TO_ENUM(NEC850_STC_W, "Store Conditional"),
	TO_ENUM(NEC850_CLL, "Clear Load Link"),
	TO_ENUM(NEC850_CACHE, "Cache operation"),
	TO_ENUM(NEC850_PREF, "Prefetch"),
	TO_ENUM(NEC850_PUSHSP, "Push registers to Stack"),
	TO_ENUM(NEC850_POPSP, "Pop registers from Stack"),
	TO_ENUM(NEC850_CVTF_HS, "Floating-point Convert Half to Single (Single)"),
	TO_ENUM(NEC850_CVTF_SH, "Floating-point Convert Single to Half (Single)"),
	TO_ENUM(NEC850_FMAF_S, "Floating-point Fused-Multiply-add (Single)"),
	TO_ENUM(NEC850_FMSF_S, "Floating-point Fused-Multiply-subtract (Single)"),
	TO_ENUM(NEC850_FNMAF_S, "Floating-point Fused-Negate-Multiply-add (Single)"),
	TO_ENUM(NEC850_FNMSF_S, "Floating-point Fused-Negate-Multiply-subtract (Single)"),
	TO_ENUM(NEC850_DBPUSH, "Output registers as software trace data"),
	TO_ENUM(NEC850_DBCP, "Output current PC value as software trace data"),
	TO_ENUM(NEC850_DBTAG, "Output immediate value as software trace data"),
	TO_ENUM(NEC850_DBHVTRAP, "Debug hypervisor trap"),
	TO_ENUM(NEC850_EST, "Enable Single Thread mode"),
	TO_ENUM(NEC850_DST, "Disable Single Thread mode"),
	TO_ENUM(NEC850_HVTRAP, "Debug hypervisor trap"),
	TO_ENUM(NEC850_HVCALL, "Hypervisor call"),
	TO_ENUM(NEC850_LDVC_SR, "Load to virtual machine context (SR)"),
	TO_ENUM(NEC850_STVC_SR, "Store contents of virtual machine context (SR)"),
	TO_ENUM(NEC850_LDTC_GR, "Load to thread context (GR)"),
	TO_ENUM(NEC850_STTC_GR, "Store contents of thread context (GR)"),
	TO_ENUM(NEC850_LDTC_PC, "Load to thread context (PC)"),
	TO_ENUM(NEC850_STTC_PC, "Store contents of thread context (PC)"),
	TO_ENUM(NEC850_LDTC_SR, "Load to thread context (SR)"),
	TO_ENUM(NEC850_STTC_SR, "Store contents of thread context (SR)"),
	TO_ENUM(NEC850_LDTC_VR, "Load to thread context (VR)"),
	TO_ENUM(NEC850_STTC_VR, "Store contents of thread context (VR)"),
	TO_ENUM(NEC850_TLBAI, "TLB ASID Invalidate"),
	TO_ENUM(NEC850_TLBR, "TLB Read"),
	TO_ENUM(NEC850_TLBS, "TLB Search"),
	TO_ENUM(NEC850_TLBVI, "TLB VA Invalidate"),
	TO_ENUM(NEC850_TLBW, "TLB Write"),
	TO_ENUM(NEC850_ROUNDF_DL, "Floating-point Convert Double to Long, round to nearest (Double)"),
	TO_ENUM(NEC850_ROUNDF_DW, "Floating-point Convert Double to Word, round to nearest (Double)"),
	TO_ENUM(NEC850_ROUNDF_DUL, "Floating-point Convert Double to Unsigned-Long, round to nearest (Double)"),
	TO_ENUM(NEC850_ROUNDF_DUW, "Floating-point Convert Double to Unsigned-Word, round to nearest (Double)"),
	TO_ENUM(NEC850_ROUNDF_SL, "Floating-point Convert Single to Long, round to nearest (Single)"),
	TO_ENUM(NEC850_ROUNDF_SW, "Floating-point Convert Single to Word, round to nearest (Single)"),
	TO_ENUM(NEC850_ROUNDF_SUL, "Floating-point Convert Single to Unsigned-Long, round to nearest (Single)"),
	TO_ENUM(NEC850_ROUNDF_SUW, "Floating-point Convert Single to Unsigned-Word, round to nearest (Single)"),
	TO_ENUM(NEC850_LDM_MP, "Load Multiple MPU entries from memory"),
	TO_ENUM(NEC850_STM_MP, "Store Multiple MPU entries to memory"),
	TO_ENUM(NEC850_CLIP_B, "Signed data conversion from word to byte with saturation"),
	TO_ENUM(NEC850_CLIP_BU, "Unsigned data conversion from word to byte with saturation"),
	TO_ENUM(NEC850_CLIP_H, "Signed data conversion from word to halfword with saturation"),
	TO_ENUM(NEC850_CLIP_HU, "Unsigned data conversion from word to halfword with saturation"),
	TO_ENUM(NEC850_LDL_BU, "Load to start atomic byte data manipulation"),
	TO_ENUM(NEC850_LDL_HU, "Load to start atomic halfword data manipulation"),
	TO_ENUM(NEC850_RESBANK, "Restore from register bank"),
	TO_ENUM(NEC850_STC_B, "Store conditional byte"),
	TO_ENUM(NEC850_STC_H, "Store conditional halfword"),
	TO_ENUM(NEC850_VAND, "Vector and"),
	TO_ENUM(NEC850_VOR, "Vector or"),
	TO_ENUM(NEC850_VXOR, "Vector xor"),
	TO_ENUM(NEC850_VNOT, "Vector not"),
	TO_ENUM(NEC850_VSAR_H, "Vector shift arithmetic right halfword"),
	TO_ENUM(NEC850_VSAR_W, "Vector shift arithmetic right word"),
	TO_ENUM(NEC850_VSAR_DW, "Vector shift arithmetic right double-word"),
	TO_ENUM(NEC850_VSHR_H, "Vector shift logical right halfword"),
	TO_ENUM(NEC850_VSHR_W, "Vector shift logical right word"),
	TO_ENUM(NEC850_VSHR_DW, "Vector shift logical right double-word"),
	TO_ENUM(NEC850_VSHL_H, "Vector shift logical left halfword"),
	TO_ENUM(NEC850_VSHL_W, "Vector shift logical left word"),
	TO_ENUM(NEC850_VSHL_DW, "Vector shift logical left double-word"),
	TO_ENUM(NEC850_VCONCAT_B, "Concatenate vector byte"),
	TO_ENUM(NEC850_VITLV_H, "Interleave halfword"),
	TO_ENUM(NEC850_VITLV_W, "Interleave word"),
	TO_ENUM(NEC850_VITLVHW_H, "Interleave halfword(halfword to word)"),
	TO_ENUM(NEC850_VITLVWH_H, "Interleave halfword(word to halfword)"),
	TO_ENUM(NEC850_VSHUFL_B, "Shuffle byte"),
	TO_ENUM(NEC850_VBSWAP_DW, "Swap double - word"),
	TO_ENUM(NEC850_VBSWAP_H, "Swap halfword"),
	TO_ENUM(NEC850_VBSWAP_W, "Swap word"),
	TO_ENUM(NEC850_DUP_H, "Duplicate halfword"),
	TO_ENUM(NEC850_DUP_W, "Duplicate word"),
	TO_ENUM(NEC850_MOV_H, "Move register (halfword)"),
	TO_ENUM(NEC850_MOV_W, "Move register (word)"),
	TO_ENUM(NEC850_MOV_DW, "Move register (double word)"),
	TO_ENUM(NEC850_VLD_B, "Vector Load byte"),
	TO_ENUM(NEC850_VLD_B_FMT3, "Vector Load byte (3rd instruction format)"),
	TO_ENUM(NEC850_VLD_B_FMT4, "Vector Load byte (4th instruction format)"),
	TO_ENUM(NEC850_VLD_H, "Vector Load halfword"),
	TO_ENUM(NEC850_VLD_H_FMT4, "Vector Load halfword (4th instruction format)"),
	TO_ENUM(NEC850_VLD_W, "Vector Load word"),
	TO_ENUM(NEC850_VLD_W_FMT4, "Vector Load word (4th instruction format)"),
	TO_ENUM(NEC850_VLD_DW, "Vector Load double - word"),
	TO_ENUM(NEC850_VLD_DW_FMT3, "Vector Load double - word (3rd instruction format)"),
	TO_ENUM(NEC850_VLD_DW_FMT4, "Vector Load double - word (4th instruction format)"),
	TO_ENUM(NEC850_VLD_DW_FMT5, "Vector Load double - word (5th instruction format)"),
	TO_ENUM(NEC850_VST_B, "Vector Store byte"),
	TO_ENUM(NEC850_VST_B_FMT4, "Vector Store byte (4th instruction format)"),
	TO_ENUM(NEC850_VST_H, "Vector Store halfword"),
	TO_ENUM(NEC850_VST_H_FMT_4_5, "Vector Store halfword (4th/5th instruction format)"),
	TO_ENUM(NEC850_VST_W, "Vector Store word"),
	TO_ENUM(NEC850_VST_W_FMT_4_5, "Vector Store word (4th/5th instruction format)"),
	TO_ENUM(NEC850_VST_DW, "Vector Store double - word"),
	TO_ENUM(NEC850_VST_DW_FMT_4_5, "Vector Store double - word (4th/5th instruction format)"),
	TO_ENUM(NEC850_VST_DW_FMT6, "Vector Store double - word (6th instruction format)"),
	TO_ENUM(NEC850_VCMOV, "Vector conditional move"),
	TO_ENUM(NEC850_MODADD, "Modulo Add"),
	TO_ENUM(NEC850_VADD_H, "Vector add halfword"),
	TO_ENUM(NEC850_VADD_W, "Vector add word"),
	TO_ENUM(NEC850_VADD_DW, "Vector add double - word"),
	TO_ENUM(NEC850_VSUB_H, "Vector subtract halfword"),
	TO_ENUM(NEC850_VSUB_W, "Vector subtract word"),
	TO_ENUM(NEC850_VSUB_DW, "Vector subtract double - word"),
	TO_ENUM(NEC850_VADDSAT_H, "Vector add halfword with saturation"),
	TO_ENUM(NEC850_VADDSAT_W, "Vector add word with saturation"),
	TO_ENUM(NEC850_VSUBSAT_H, "Vector subtract halfword with saturation"),
	TO_ENUM(NEC850_VSUBSAT_W, "Vector subtract word with saturation"),
	TO_ENUM(NEC850_VADDS_H, "Vector add halfword with scaling"),
	TO_ENUM(NEC850_VADDS_W, "Vector add word with scaling"),
	TO_ENUM(NEC850_VSUBS_H, "Vector subtract halfword with scaling"),
	TO_ENUM(NEC850_VSUBS_W, "Vector subtract word with scaling"),
	TO_ENUM(NEC850_VMUL_H, "Vector multiply halfword"),
	TO_ENUM(NEC850_VMUL_W, "Vector multiply word"),
	TO_ENUM(NEC850_VMULT_H, "Vector multiply halfword with truncation"),
	TO_ENUM(NEC850_VMULT_W, "Vector multiply word with truncation"),
	TO_ENUM(NEC850_VMULCX_H, "Vector multiply halfword with complex number"),
	TO_ENUM(NEC850_VMULCX_W, "Vector multiply word with complex number"),
	TO_ENUM(NEC850_VCMPEQ_H, "Vector compare equal halfword"),
	TO_ENUM(NEC850_VCMPEQ_W, "Vector compare equal word"),
	TO_ENUM(NEC850_VCMPLT_H, "Vector compare less-than halfword"),
	TO_ENUM(NEC850_VCMPLT_W, "Vector compare less-than word"),
	TO_ENUM(NEC850_VCMPLE_H, "Vector compare less-than-equal halfword"),
	TO_ENUM(NEC850_VCMPLE_W, "Vector compare less-than-equal word"),
	TO_ENUM(NEC850_VCMPNE_H, "Vector compare not-equal halfword"),
	TO_ENUM(NEC850_VCMPNE_W, "Vector compare not-equal word"),
	TO_ENUM(NEC850_VABS_H, "Vector absolute halfword"),
	TO_ENUM(NEC850_VABS_W, "Vector absolute word"),
	TO_ENUM(NEC850_VNEG_H, "Vector negate halfword"),
	TO_ENUM(NEC850_VNEG_W, "Vector negate word"),
	TO_ENUM(NEC850_VMAXGT_H, "Vector maximum greater-than halfword"),
	TO_ENUM(NEC850_VMAXGE_H, "Vector maximum greater-than-equal halfword"),
	TO_ENUM(NEC850_VMINLT_H, "Vector minimum less-than halfword"),
	TO_ENUM(NEC850_VMINLE_H, "Vector minimum less-than-equal halfword"),
	TO_ENUM(NEC850_VMAXGT_W, "Vector maximum greater-than word"),
	TO_ENUM(NEC850_VMAXGE_W, "Vector maximum greater-than-equal word"),
	TO_ENUM(NEC850_VMINLT_W, "Vector minimum less-than word"),
	TO_ENUM(NEC850_VMINLE_W, "Vector minimum less-than-equal word"),
	TO_ENUM(NEC850_VMADSAT_H, "Vector multiply halfword and add with saturation"),
	TO_ENUM(NEC850_VMADSAT_W, "Vector multiply word and add with saturation"),
	TO_ENUM(NEC850_VMADRN_H, "Vector multiply halfword and add with rounding"),
	TO_ENUM(NEC850_VMADRN_W, "Vector multiply word and add with rounding"),
	TO_ENUM(NEC850_VMSUM_H, "Vector multiply halfword and sum"),
	TO_ENUM(NEC850_VMSUM_W, "Vector multiply word and sum"),
	TO_ENUM(NEC850_VMSUMAD_H, "Vector multiply halfword and sum and add to vector register"),
	TO_ENUM(NEC850_VMSUMAD_W, "Vector multiply word and sum and add to vector register"),
	TO_ENUM(NEC850_VMSUMADRE_H, "Vector multiply halfword and sum and add to vector register for real part result of complex number calculation"),
	TO_ENUM(NEC850_VMSUMADRE_W, "Vector multiply word and sum and add to vector register for real part result of complex number calculation"),
	TO_ENUM(NEC850_VMSUMADIM_H, "Vector multiply halfword and sum and add to vector register for imaginary part result of complex number calculation"),
	TO_ENUM(NEC850_VMSUMADIM_W, "Vector multiply word and sum and add to vector register for imaginary part result of complex number calculation"),
	TO_ENUM(NEC850_VMSUMADRN_H, "Vector multiply halfword and sum and add to vector register with rounding"),
	TO_ENUM(NEC850_VBIQ_H, "Vector multiply halfword for biquad calculation"),
	TO_ENUM(NEC850_PKUI8I16, "Pack vector unsigned integer byte to vector signed integer halfword"),
	TO_ENUM(NEC850_PKI16I32, "Pack vector signed integer halfword to vector signed integer word"),
	TO_ENUM(NEC850_PKQ15Q31, "Pack vector Q15 fractional halfword to vector Q31 fractional word"),
	TO_ENUM(NEC850_PKI16UI8, "Pack vector signed integer halfword to vector unsigned integer byte"),
	TO_ENUM(NEC850_PKI32I16, "Pack vector signed integer word to vector signed integer halfword"),
	TO_ENUM(NEC850_PKQ31Q15, "Pack vector Q31 fractional word to vector Q15 fractional halfword"),
	TO_ENUM(NEC850_PKQ30Q31, "Pack Q31 fractional double-word to vector Q31 fractional halfword"),
	TO_ENUM(NEC850_PKI64I32, "Pack signed integer double-word to vector signed integer word"),
	TO_ENUM(NEC850_CNVQ15Q30, "Convert from Q15 fractional halfword to Q30 fractional double-word"),
	TO_ENUM(NEC850_CNVQ31Q62, "Convert from Q31 fractional word to Q62 fractional double-word"),
	TO_ENUM(NEC850_CNVQ30Q15, "Convert from Q30 fractional double-word to Q15 fractional halfword"),
	TO_ENUM(NEC850_CNVQ62Q31, "Convert from Q62 fractional double-word to Q31 fractional word"),
	TO_ENUM(NEC850_EXPQ31, "Extract exponent of Q31 fractional word"),
	TO_ENUM(NEC850_VCALCH, "Vector calculate with halfword"),
	TO_ENUM(NEC850_VCALCW, "Vector calculate with word"),
	TO_ENUM(NEC850_MOVV_W4, "Move vector register to vector register"),
	TO_ENUM(NEC850_FLPV_S4, "Floating-point SIMD Flip (single)"),
	TO_ENUM(NEC850_SHFLV_W4, "Vector Shuffle"),
	TO_ENUM(NEC850_LDV_DW, "Load Vector (Double-Word)"),
	TO_ENUM(NEC850_LDV_QW, "Load Vector (Quad-Word)"),
	TO_ENUM(NEC850_LDV_W, "Load Vector (Word)"),
	TO_ENUM(NEC850_LDVZ_H4, "Load Vector at Even Halfword field"),
	TO_ENUM(NEC850_STV_DW, "Store Vector (Double-Word)"),
	TO_ENUM(NEC850_STV_QW, "Store Vector (Quad-Word)"),
	TO_ENUM(NEC850_STV_W, "Store Vector (Word)"),
	TO_ENUM(NEC850_STVZ_H4, "Store Vector at Even Halfword field"),
	TO_ENUM(NEC850_CMOVF_W4, "Conditional move of vector register (Single precision)"),
	TO_ENUM(NEC850_TRFSRV_W4, "Transfers compare result to PSW"),
	TO_ENUM(NEC850_ABSF_S4, "Floating-point SIMD Absolute (single)"),
	TO_ENUM(NEC850_ADDF_S4, "Floating-point SIMD Add (single)"),
	TO_ENUM(NEC850_DIVF_S4, "Floating-point SIMD Divide (single)"),
	TO_ENUM(NEC850_MAXF_S4, "Floating-point SIMD Maximum (single)"),
	TO_ENUM(NEC850_MINF_S4, "Floating-point SIMD Minimum (single)"),
	TO_ENUM(NEC850_MULF_S4, "Floating-point SIMD Multiply (single)"),
	TO_ENUM(NEC850_NEGF_S4, "Floating-point SIMD Negative (single)"),
	TO_ENUM(NEC850_RECIPF_S4, "Floating-point SIMD Reciprocal (single)"),
	TO_ENUM(NEC850_RSQRTF_S4, "Floating-point SIMD Reciprocal Square-Root (single)"),
	TO_ENUM(NEC850_SQRTF_S4, "Floating-point SIMD Square-Root (single)"),
	TO_ENUM(NEC850_SUBF_S4, "Floating-point SIMD Subtract (single)"),
	TO_ENUM(NEC850_FMAF_S4, "Floating-point SIMD Fused-Multiply-Add (Single)"),
	TO_ENUM(NEC850_FMSF_S4, "Floating-point SIMD Fused-Multiply-Subtract (Single)"),
	TO_ENUM(NEC850_FNMAF_S4, "Floating-point SIMD Fused-Negative-Multiply-Add (Single)"),
	TO_ENUM(NEC850_FNMSF_S4, "Floating-point SIMD Fused-Negative-Multiply-Subtract (Single)"),
	TO_ENUM(NEC850_ADDSUBF_S4, "Floating-point SIMD Add/Subtract (single)"),
	TO_ENUM(NEC850_ADDSUBNF_S4, "Floating-point SIMD Add/Subtract Negative (single)"),
	TO_ENUM(NEC850_SUBADDF_S4, "Floating-point SIMD Subtract/Add (single)"),
	TO_ENUM(NEC850_SUBADDNF_S4, "Floating-point SIMD Subtract/Add Negative (single)"),
	TO_ENUM(NEC850_ADDXF_S4, "Floating-point SIMD Add Exchange (single)"),
	TO_ENUM(NEC850_MULXF_S4, "Floating-point SIMD Multiply Exchange (single)"),
	TO_ENUM(NEC850_SUBXF_S4, "Floating-point SIMD Subtract Exchange (single)"),
	TO_ENUM(NEC850_ADDSUBNXF_S4, "Floating-point SIMD Add/Subtract Negative Exchange (single)"),
	TO_ENUM(NEC850_ADDSUBXF_S4, "Floating-point SIMD Add/Subtract Exchange (single)"),
	TO_ENUM(NEC850_SUBADDNXF_S4, "Floating-point SIMD Subtract/Add Negative Exchange (single)"),
	TO_ENUM(NEC850_SUBADDXF_S4, "Floating-point SIMD Subtract/Add Exchange (single)"),
	TO_ENUM(NEC850_ADDRF_S4, "Floating-point SIMD Add Reduction (single)"),
	TO_ENUM(NEC850_MAXRF_S4, "Floating-point SIMD Maximum Reduction (single)"),
	TO_ENUM(NEC850_MINRF_S4, "Floating-point SIMD Minimum Reduction (single)"),
	TO_ENUM(NEC850_MULRF_S4, "Floating-point SIMD Multiply Reduction (single)"),
	TO_ENUM(NEC850_SUBRF_S4, "Floating-point SIMD Subtract Reduction (single)"),
	TO_ENUM(NEC850_CEILF_SUW4, "Floating-point SIMD Convert Single to Unsigned Word, round toward positive (single)"),
	TO_ENUM(NEC850_CEILF_SW4, "Floating-point SIMD Convert Single to Word, round toward positive (single)"),
	TO_ENUM(NEC850_CVTF_HS4, "Floating-point SIMD Convert Half to Single (single)"),
	TO_ENUM(NEC850_CVTF_SH4, "Floating-point SIMD Convert Single to Half (single)"),
	TO_ENUM(NEC850_CVTF_SUW4, "Floating-point SIMD Convert Single to Unsigned Word (single)"),
	TO_ENUM(NEC850_CVTF_SW4, "Floating-point SIMD Convert Single to Word (single)"),
	TO_ENUM(NEC850_CVTF_UWS4, "Floating-point SIMD Convert Unsigned Word to Single (single)"),
	TO_ENUM(NEC850_CVTF_WS4, "Floating-point SIMD Convert Word to Single (single)"),
	TO_ENUM(NEC850_FLOORF_SUW4, "Floating-point SIMD Convert Single to Unsigned Word, round toward negative (single)"),
	TO_ENUM(NEC850_FLOORF_SW4, "Floating-point SIMD Convert Single to Word, round toward negative (single)"),
	TO_ENUM(NEC850_ROUNDF_SUW4, "Floating-point SIMD Convert Single to Unsigned Word, round to nearest (single)"),
	TO_ENUM(NEC850_ROUNDF_SW4, "Floating-point SIMD Convert Single to Word, round to nearest (single)"),
	TO_ENUM(NEC850_TRNCF_SUW4, "Floating-point SIMD Convert Single to Unsigned Word, round toward zero (single)"),
	TO_ENUM(NEC850_TRNCF_SW4, "Floating-point SIMD Convert Single to Word, round toward zero (single)"),
	TO_ENUM(NEC850_CMPF_S4, "Floating-point SIMD Comparison (single)"),
	TO_ENUM(NEC850_LAST_INSTRUCTION, "Undocumented instruction NEC850_LAST_INSTRUCTION")
};
