auto instructions_PLFM_JAVA = flags_vector_t{
	TO_ENUM(j_nop, "Undocumented instruction j_nop"),
	TO_ENUM(j_aconst_null, "1 Push null object reference"),
	TO_ENUM(j_iconst_m1, "2 Push integer constant -1"),
	TO_ENUM(j_iconst_0, "3 Push the integer 0"),
	TO_ENUM(j_iconst_1, "4 Push the integer 1"),
	TO_ENUM(j_iconst_2, "5 Push the integer 2"),
	TO_ENUM(j_iconst_3, "6 Push the integer 3"),
	TO_ENUM(j_iconst_4, "7 Push the integer 4"),
	TO_ENUM(j_iconst_5, "8 Push the integer 5"),
	TO_ENUM(j_lconst_0, "9 Push the long integer 0"),
	TO_ENUM(j_lconst_1, "10 Push the long integer 1"),
	TO_ENUM(j_fconst_0, "11 Push the single-precision foating point 0.0"),
	TO_ENUM(j_fconst_1, "12 Push the single-precision foating point 1.0"),
	TO_ENUM(j_fconst_2, "13 Push the single-precision foating point 2.0"),
	TO_ENUM(j_dconst_0, "14 Push the double-precision foating point 2.0"),
	TO_ENUM(j_dconst_1, "15 Push the double-precision foating point 2.0"),
	TO_ENUM(j_bipush, "16 Push one byte signed integer"),
	TO_ENUM(j_sipush, "17 Push two-byte signed integer"),
	TO_ENUM(j_ldc, "18 Push item from constant pool (i1)"),
	TO_ENUM(j_ldcw, "19 Push item from constant pool (i2)"),
	TO_ENUM(j_ldc2w, "20 Push long or double from constant pool"),
	TO_ENUM(j_iload, "21 Push integer value of the local variable"),
	TO_ENUM(j_lload, "22 Push long value of the local variable"),
	TO_ENUM(j_fload, "23 Push single float value of the local variable"),
	TO_ENUM(j_dload, "24 Push double float value of the local variable"),
	TO_ENUM(j_aload, "25 Push object reference from the local variable"),
	TO_ENUM(j_iload_0, "26 Push integer value of the local variable #0"),
	TO_ENUM(j_iload_1, "27 Push integer value of the local variable #1"),
	TO_ENUM(j_iload_2, "28 Push integer value of the local variable #2"),
	TO_ENUM(j_iload_3, "29 Push integer value of the local variable #3"),
	TO_ENUM(j_lload_0, "30 Push long value of the local variable #0"),
	TO_ENUM(j_lload_1, "31 Push long value of the local variable #1"),
	TO_ENUM(j_lload_2, "32 Push long value of the local variable #2"),
	TO_ENUM(j_lload_3, "33 Push long value of the local variable #3"),
	TO_ENUM(j_fload_0, "34 Push single float value of the local variable #0"),
	TO_ENUM(j_fload_1, "35 Push single float value of the local variable #1"),
	TO_ENUM(j_fload_2, "36 Push single float value of the local variable #2"),
	TO_ENUM(j_fload_3, "37 Push single float value of the local variable #3"),
	TO_ENUM(j_dload_0, "38 Push double float value of the local variable #0"),
	TO_ENUM(j_dload_1, "39 Push double float value of the local variable #1"),
	TO_ENUM(j_dload_2, "40 Push double float value of the local variable #2"),
	TO_ENUM(j_dload_3, "41 Push double float value of the local variable #3"),
	TO_ENUM(j_aload_0, "42 Push object reference from the local variable #0"),
	TO_ENUM(j_aload_1, "43 Push object reference from the local variable #1"),
	TO_ENUM(j_aload_2, "44 Push object reference from the local variable #2"),
	TO_ENUM(j_aload_3, "45 Push object reference from the local variable #3"),
	TO_ENUM(j_iaload, "46 Push integer from array"),
	TO_ENUM(j_laload, "47 Push long from array"),
	TO_ENUM(j_faload, "48 Push single float from array"),
	TO_ENUM(j_daload, "49 Push double float from array"),
	TO_ENUM(j_aaload, "50 Push object refernce from array"),
	TO_ENUM(j_baload, "51 Push signed byte from array"),
	TO_ENUM(j_caload, "52 Push character from array"),
	TO_ENUM(j_saload, "53 Push short from array"),
	TO_ENUM(j_istore, "54 Pop integer value into local variable"),
	TO_ENUM(j_lstore, "55 Pop long value into local variable"),
	TO_ENUM(j_fstore, "56 Pop single float value into local variable"),
	TO_ENUM(j_dstore, "57 Pop double float value into local variable"),
	TO_ENUM(j_astore, "58 Pop object refernce into local variable"),
	TO_ENUM(j_istore_0, "59 Pop integer value into local variable #0"),
	TO_ENUM(j_istore_1, "60 Pop integer value into local variable #1"),
	TO_ENUM(j_istore_2, "61 Pop integer value into local variable #2"),
	TO_ENUM(j_istore_3, "62 Pop integer value into local variable #3"),
	TO_ENUM(j_lstore_0, "63 Pop long value into local variable #0"),
	TO_ENUM(j_lstore_1, "64 Pop long value into local variable #1"),
	TO_ENUM(j_lstore_2, "65 Pop long value into local variable #2"),
	TO_ENUM(j_lstore_3, "66 Pop long value into local variable #3"),
	TO_ENUM(j_fstore_0, "67 Pop single float value into local variable #0"),
	TO_ENUM(j_fstore_1, "68 Pop single float value into local variable #1"),
	TO_ENUM(j_fstore_2, "69 Pop single float value into local variable #2"),
	TO_ENUM(j_fstore_3, "70 Pop single float value into local variable #3"),
	TO_ENUM(j_dstore_0, "71 Pop double float value into local variable"),
	TO_ENUM(j_dstore_1, "72 Pop double float value into local variable #0"),
	TO_ENUM(j_dstore_2, "73 Pop double float value into local variable #1"),
	TO_ENUM(j_dstore_3, "74 Pop double float value into local variable #2"),
	TO_ENUM(j_astore_0, "75 Pop object refernce into local variable #0"),
	TO_ENUM(j_astore_1, "76 Pop object refernce into local variable #1"),
	TO_ENUM(j_astore_2, "77 Pop object refernce into local variable #2"),
	TO_ENUM(j_astore_3, "78 Pop object refernce into local variable #3"),
	TO_ENUM(j_iastore, "79 Pop integer from array"),
	TO_ENUM(j_lastore, "80 Pop long from array"),
	TO_ENUM(j_fastore, "81 Pop single float from array"),
	TO_ENUM(j_dastore, "82 Pop double float from array"),
	TO_ENUM(j_aastore, "83 Pop object refernce from array"),
	TO_ENUM(j_bastore, "84 Pop signed byte from array"),
	TO_ENUM(j_castore, "85 Pop character from array"),
	TO_ENUM(j_sastore, "86 Pop short from array"),
	TO_ENUM(j_pop, "87 Pop top stack word"),
	TO_ENUM(j_pop2, "88 Pop top two stack word"),
	TO_ENUM(j_dup, "89 Duplicate top stack word"),
	TO_ENUM(j_dup_x1, "90 Duplicate top stack word and put two down"),
	TO_ENUM(j_dup_x2, "91 Duplicate top stack word and put three down"),
	TO_ENUM(j_dup2, "92 Duplicate top two stack word"),
	TO_ENUM(j_dup2_x1, "93 Duplicate top two stack words and put two down"),
	TO_ENUM(j_dup2_x2, "94 Duplicate top two stack words and put three down"),
	TO_ENUM(j_swap, "95 Swap two top stack words"),
	TO_ENUM(j_iadd, "96 Integer add"),
	TO_ENUM(j_ladd, "97 Long add"),
	TO_ENUM(j_fadd, "98 Single float add"),
	TO_ENUM(j_dadd, "99 Double float add"),
	TO_ENUM(j_isub, "100 Integer subtract"),
	TO_ENUM(j_lsub, "101 Long subtract"),
	TO_ENUM(j_fsub, "102 Single float subtract"),
	TO_ENUM(j_dsub, "103 Double Float subtract"),
	TO_ENUM(j_imul, "104 Integer multiply"),
	TO_ENUM(j_lmul, "105 Long multiply"),
	TO_ENUM(j_fmul, "106 Single float multiply"),
	TO_ENUM(j_dmul, "107 Double Float multiply"),
	TO_ENUM(j_idiv, "108 Integer divide"),
	TO_ENUM(j_ldiv, "109 Long divide"),
	TO_ENUM(j_fdiv, "110 Single float divide"),
	TO_ENUM(j_ddiv, "111 Double Float divide"),
	TO_ENUM(j_irem, "112 Integer reminder"),
	TO_ENUM(j_lrem, "113 Long reminder"),
	TO_ENUM(j_frem, "114 Single float reminder"),
	TO_ENUM(j_drem, "115 Double Float reminder"),
	TO_ENUM(j_ineg, "116 Integer negate"),
	TO_ENUM(j_lneg, "117 Long negate"),
	TO_ENUM(j_fneg, "118 Single float negate"),
	TO_ENUM(j_dneg, "119 Double Float negate"),
	TO_ENUM(j_ishl, "120 Integer shift left"),
	TO_ENUM(j_lshl, "121 Long shift left"),
	TO_ENUM(j_ishr, "122 Integer logical shift right"),
	TO_ENUM(j_lshr, "123 Long logical shift right"),
	TO_ENUM(j_iushr, "124 Integer arithmetic shift right"),
	TO_ENUM(j_lushr, "125 Long arithmeticshift right"),
	TO_ENUM(j_iand, "126 Integer boolean AND"),
	TO_ENUM(j_land, "127 Long boolean AND"),
	TO_ENUM(j_ior, "128 Integer boolean OR"),
	TO_ENUM(j_lor, "129 Long boolean OR"),
	TO_ENUM(j_ixor, "130 Integer boolean XOR"),
	TO_ENUM(j_lxor, "131 Long boolean XOR"),
	TO_ENUM(j_iinc, "132 Add 8-bit signed const to local variable"),
	TO_ENUM(j_i2l, "133 Integer to Long conversion"),
	TO_ENUM(j_i2f, "134 Integer to single float conversion"),
	TO_ENUM(j_i2d, "135 Integer to double float conversion"),
	TO_ENUM(j_l2i, "136 Long to Integer conversion"),
	TO_ENUM(j_l2f, "137 Long to single float conversion"),
	TO_ENUM(j_l2d, "138 Long to double float conversion"),
	TO_ENUM(j_f2i, "139 Single float to Integer conversion"),
	TO_ENUM(j_f2l, "140 Single float to Long conversion"),
	TO_ENUM(j_f2d, "141 Single float to double float conversion"),
	TO_ENUM(j_d2i, "142 Double float to Integer conversion"),
	TO_ENUM(j_d2l, "143 Double float to Long conversion"),
	TO_ENUM(j_d2f, "144 Double float to double float conversion"),
	TO_ENUM(j_i2b, "145 Integer to signed byte conversion"),
	TO_ENUM(j_i2c, "146 Integer to unsigned short conversion"),
	TO_ENUM(j_i2s, "147 Integer to signed short conversion"),
	TO_ENUM(j_lcmp, "148 Long compare"),
	TO_ENUM(j_fcmpl, "149 Single float compare (-1 on NaN)"),
	TO_ENUM(j_fcmpg, "150 Single float compare (1 on NaN)"),
	TO_ENUM(j_dcmpl, "151 Double float compare (-1 on NaN)"),
	TO_ENUM(j_dcmpg, "152 Double float compare (1 on NaN)"),
	TO_ENUM(j_ifeq, "153 Branch if equal to 0"),
	TO_ENUM(j_ifne, "154 Branch if not equal to 0"),
	TO_ENUM(j_iflt, "155 Branch if less then 0"),
	TO_ENUM(j_ifge, "156 Branch if greater than or equal to 0"),
	TO_ENUM(j_ifgt, "157 Branch if greater than 0"),
	TO_ENUM(j_ifle, "158 Branch if less than or equal to 0"),
	TO_ENUM(j_if_icmpeq, "159 Branch if integers equal"),
	TO_ENUM(j_if_icmpne, "160 Branch if integers not equal"),
	TO_ENUM(j_if_icmplt, "161 Branch if integers less than"),
	TO_ENUM(j_if_icmpge, "162 Branch if integers grater than or equal to"),
	TO_ENUM(j_if_icmpgt, "163 Branch if integers grater than"),
	TO_ENUM(j_if_icmple, "164 Branch if integers less than or equal to"),
	TO_ENUM(j_if_acmpeq, "165 Branch if object references are equal"),
	TO_ENUM(j_if_acmpne, "166 Branch if object references not equal"),
	TO_ENUM(j_goto, "167 Branch always"),
	TO_ENUM(j_jsr, "168 Jump subroutine"),
	TO_ENUM(j_ret, "169 Return from subroutine"),
	TO_ENUM(j_tableswitch, "170 Access jump table by index and jump"),
	TO_ENUM(j_lookupswitch, "171 Access jump table by key match and jump"),
	TO_ENUM(j_ireturn, "172 Return integer from function"),
	TO_ENUM(j_lreturn, "173 Return long from function"),
	TO_ENUM(j_freturn, "174 Return single floatr from function"),
	TO_ENUM(j_dreturn, "175 Return double float from function"),
	TO_ENUM(j_areturn, "176 Return object reference from function"),
	TO_ENUM(j_return, "177 Return (void) from procedure"),
	TO_ENUM(j_getstatic, "178 Set static field from class"),
	TO_ENUM(j_putstatic, "179 Set static field in class"),
	TO_ENUM(j_getfield, "180 Fetch field from object"),
	TO_ENUM(j_putfield, "181 Set field in object"),
	TO_ENUM(j_invokevirtual, "182 invoke instance method"),
	TO_ENUM(j_invokespecial, "183 invoke instance method (superclass/init/...)"),
	TO_ENUM(j_invokestatic, "184 invoke a class (static) method"),
	TO_ENUM(j_invokeinterface, "185 invoke interface method"),
	TO_ENUM(j_invokedynamic, "186 invoke instance method (select by paraneter)"),
	TO_ENUM(j_new, "187 Create new object"),
	TO_ENUM(j_newarray, "188 Allocate new array"),
	TO_ENUM(j_anewarray, "189 Allocate new array of refernces to object"),
	TO_ENUM(j_arraylength, "190 Get length of array"),
	TO_ENUM(j_athrow, "191 Throw exception or error"),
	TO_ENUM(j_checkcast, "192 Make sure object is of given type"),
	TO_ENUM(j_instanceof, "193 Determine if an object is of given type"),
	TO_ENUM(j_monitorenter, "194 Enter monitored region of code"),
	TO_ENUM(j_monitorexit, "195 Exit monitored region of code"),
	TO_ENUM(j_wide, "196 wide (prefix of command)"),
	TO_ENUM(j_multianewarray, "197  Allocate new multi-dimensional array"),
	TO_ENUM(j_ifnull, "198 Branch if NULL-ptr"),
	TO_ENUM(j_ifnonnull, "199 Branch if not NULL-ptr"),
	TO_ENUM(j_goto_w, "200 Branch always (wide index)"),
	TO_ENUM(j_jsr_w, "201 Jump subroutine (wide index)"),
	TO_ENUM(j_breakpoint, "202 Stop and pass control to breakpoint handler"),
	TO_ENUM(j_lastnorm, "Undocumented instruction j_lastnorm"),
	TO_ENUM(j_a_invokesuper, "Undocumented instruction j_a_invokesuper"),
	TO_ENUM(j_a_invokevirtualobject, "Undocumented instruction j_a_invokevirtualobject"),
	TO_ENUM(j_a_invokeignored, "Undocumented instruction j_a_invokeignored"),
	TO_ENUM(j_a_software, "Undocumented instruction j_a_software"),
	TO_ENUM(j_a_hardware, "Undocumented instruction j_a_hardware"),
	TO_ENUM(j_last, "Undocumented instruction j_last"),
	TO_ENUM(j_ldc_quick, "Undocumented instruction j_ldc_quick"),
	TO_ENUM(j_ldcw_quick, "204     (19)"),
	TO_ENUM(j_ldc2w_quick, "205     (20)"),
	TO_ENUM(j_getfield_quick, "206     (180)"),
	TO_ENUM(j_putfield_quick, "207     (181)"),
	TO_ENUM(j_getfield2_quick, "208"),
	TO_ENUM(j_putfield2_quick, "209"),
	TO_ENUM(j_getstatic_quick, "210     (178)"),
	TO_ENUM(j_putstatic_quick, "211     (179)"),
	TO_ENUM(j_getstatic2_quick, "212"),
	TO_ENUM(j_putstatic2_quick, "213"),
	TO_ENUM(j_invokevirtual_quick, "214     (182)"),
	TO_ENUM(j_invokenonvirtual_quick, "215     (183)"),
	TO_ENUM(j_invokesuper_quick, "216"),
	TO_ENUM(j_invokestatic_quick, "217     (184)"),
	TO_ENUM(j_invokeinterface_quick, "218     (185)"),
	TO_ENUM(j_invokevirtualobject_quick, "219"),
	TO_ENUM(j_invokeignored_quick, "220"),
	TO_ENUM(j_new_quick, "221     (187)"),
	TO_ENUM(j_anewarray_quick, "222     (189)"),
	TO_ENUM(j_multianewarray_quick, "223     (197)"),
	TO_ENUM(j_checkcast_quick, "224     (192)"),
	TO_ENUM(j_instanceof_quick, "225     (193)"),
	TO_ENUM(j_invokevirtual_quick_w, "226"),
	TO_ENUM(j_getfield_quick_w, "227"),
	TO_ENUM(j_putfield_quick_w, "228"),
	TO_ENUM(j_quick_last, "Undocumented instruction j_quick_last")
};
