auto instructions_PLFM_MIPS = flags_vector_t{
	TO_ENUM(MIPS_null, "Undocumented instruction MIPS_null"),
	TO_ENUM(MIPS_add, "Add"),
	TO_ENUM(MIPS_addu, "Add Unsigned"),
	TO_ENUM(MIPS_and, "AND"),
	TO_ENUM(MIPS_dadd, "Doubleword Add"),
	TO_ENUM(MIPS_daddu, "Doubleword Add Unsigned"),
	TO_ENUM(MIPS_dsub, "Doubleword Subtract"),
	TO_ENUM(MIPS_dsubu, "Doubleword Subtract Unsigned"),
	TO_ENUM(MIPS_nor, "NOR"),
	TO_ENUM(MIPS_or, "OR"),
	TO_ENUM(MIPS_slt, "Set on Less Than"),
	TO_ENUM(MIPS_sltu, "Set on Less Than Unsigned"),
	TO_ENUM(MIPS_sub, "Subtract"),
	TO_ENUM(MIPS_subu, "Subtract Unsigned"),
	TO_ENUM(MIPS_xor, "Exclusive OR"),
	TO_ENUM(MIPS_dsll, "Doubleword Shift Left Logical"),
	TO_ENUM(MIPS_dsll32, "Doubleword Shift Left Logical + 32"),
	TO_ENUM(MIPS_dsra, "Doubleword Shift Right Arithmetic"),
	TO_ENUM(MIPS_dsra32, "Doubleword Shift Right Arithmetic + 32"),
	TO_ENUM(MIPS_dsrl, "Doubleword Shift Right Logical"),
	TO_ENUM(MIPS_dsrl32, "Doubleword Shift Right Logical + 32"),
	TO_ENUM(MIPS_sll, "Shift Left Logical"),
	TO_ENUM(MIPS_sra, "Shift Right Arithmetic"),
	TO_ENUM(MIPS_srl, "Shift Right Logical"),
	TO_ENUM(MIPS_dsllv, "Doubleword Shift Left Logical Variable"),
	TO_ENUM(MIPS_dsrav, "Doubleword Shift Right Arithmetic Variable"),
	TO_ENUM(MIPS_dsrlv, "Doubleword Shift Right Logical Variable"),
	TO_ENUM(MIPS_sllv, "Shift Left Logical Variable"),
	TO_ENUM(MIPS_srav, "Shift Right Arithmetic Variable"),
	TO_ENUM(MIPS_srlv, "Shift Right Logical Variable"),
	TO_ENUM(MIPS_addi, "Add Immediate"),
	TO_ENUM(MIPS_addiu, "Add Immediate Unsigned"),
	TO_ENUM(MIPS_daddi, "Doubleword Add Immediate"),
	TO_ENUM(MIPS_daddiu, "Doubleword Add Immediate Unsigned"),
	TO_ENUM(MIPS_slti, "Set on Less Than Immediate"),
	TO_ENUM(MIPS_sltiu, "Set on Less Than Immediate Unsigned"),
	TO_ENUM(MIPS_andi, "AND Immediate"),
	TO_ENUM(MIPS_ori, "OR Immediate"),
	TO_ENUM(MIPS_xori, "Exclusive OR Immediate"),
	TO_ENUM(MIPS_teq, "Trap if Equal"),
	TO_ENUM(MIPS_tge, "Trap if Greater Than or Equal"),
	TO_ENUM(MIPS_tgeu, "Trap if Greater Than or Equal Unsigned"),
	TO_ENUM(MIPS_tlt, "Trap if Less Than"),
	TO_ENUM(MIPS_tltu, "Trap if Less Than Unsigned"),
	TO_ENUM(MIPS_tne, "Trap if Not Equal"),
	TO_ENUM(MIPS_cfc1, "Move Control From FPU"),
	TO_ENUM(MIPS_cfc2, "Move Control From Coprocessor 2"),
	TO_ENUM(MIPS_ctc1, "Move Control to FPU"),
	TO_ENUM(MIPS_ctc2, "Move Control to Coprocessor 2"),
	TO_ENUM(MIPS_dmfc0, "Doubleword Move From CP0"),
	TO_ENUM(MIPS_qmfc2, "Quadword Move From CP2"),
	TO_ENUM(MIPS_dmtc0, "Doubleword Move To CP0"),
	TO_ENUM(MIPS_qmtc2, "Quadword Move To CP2"),
	TO_ENUM(MIPS_mfc0, "Move from CP0"),
	TO_ENUM(MIPS_mfc1, "Move from FPU"),
	TO_ENUM(MIPS_mfc2, "Move from CP2"),
	TO_ENUM(MIPS_mtc0, "Move to CP0"),
	TO_ENUM(MIPS_mtc1, "Move to FPU"),
	TO_ENUM(MIPS_mtc2, "Move to CP2"),
	TO_ENUM(MIPS_teqi, "Trap if Equal Immediate"),
	TO_ENUM(MIPS_tgei, "Trap if Greater Than or Equal Immediate"),
	TO_ENUM(MIPS_tgeiu, "Trap if Greater Than or Equal Immediate Unsigned"),
	TO_ENUM(MIPS_tlti, "Trap if Less Than Immediate"),
	TO_ENUM(MIPS_tltiu, "Trap if Less Than Immediate Unsigned"),
	TO_ENUM(MIPS_tnei, "Trap if Not Equal Immediate"),
	TO_ENUM(MIPS_ddiv, "Doubleword Divide"),
	TO_ENUM(MIPS_ddivu, "Doubleword Divide Unsigned"),
	TO_ENUM(MIPS_div, "Divide"),
	TO_ENUM(MIPS_divu, "Divide Unsigned"),
	TO_ENUM(MIPS_dmult, "Doubleword Multiply"),
	TO_ENUM(MIPS_dmultu, "Doubleword Multiply Unsigned"),
	TO_ENUM(MIPS_mult, "Multiply"),
	TO_ENUM(MIPS_multu, "Multiply Unsigned"),
	TO_ENUM(MIPS_mthi, "Move To HI"),
	TO_ENUM(MIPS_mtlo, "Move To LO"),
	TO_ENUM(MIPS_mfhi, "Move From HI"),
	TO_ENUM(MIPS_mflo, "Move From LO"),
	TO_ENUM(MIPS_cop0, "Coprocessor 0 Operation"),
	TO_ENUM(MIPS_cop1, "FPU Operation"),
	TO_ENUM(MIPS_cop2, "Coprocessor 2 Operation"),
	TO_ENUM(MIPS_break, "Break"),
	TO_ENUM(MIPS_syscall, "System Call"),
	TO_ENUM(MIPS_bc0f, "Branch on Coprocessor 0 False"),
	TO_ENUM(MIPS_bc1f, "Branch on FPU False"),
	TO_ENUM(MIPS_bc2f, "Branch on Coprocessor 2 False"),
	TO_ENUM(MIPS_bc3f, "Branch on Coprocessor 3 False"),
	TO_ENUM(MIPS_bc0fl, "Branch on Coprocessor 0 False Likely"),
	TO_ENUM(MIPS_bc1fl, "Branch on FPU False Likely"),
	TO_ENUM(MIPS_bc2fl, "Branch on Coprocessor 2 False Likely"),
	TO_ENUM(MIPS_bc3fl, "Branch on Coprocessor 3 False Likely"),
	TO_ENUM(MIPS_bc0t, "Branch on Coprocessor 0 True"),
	TO_ENUM(MIPS_bc1t, "Branch on FPU True"),
	TO_ENUM(MIPS_bc2t, "Branch on Coprocessor 2 True"),
	TO_ENUM(MIPS_bc3t, "Branch on Coprocessor 3 True"),
	TO_ENUM(MIPS_bc0tl, "Branch on Coprocessor 0 True Likely"),
	TO_ENUM(MIPS_bc1tl, "Branch on FPU True Likely"),
	TO_ENUM(MIPS_bc2tl, "Branch on Coprocessor 2 True Likely"),
	TO_ENUM(MIPS_bc3tl, "Branch on Coprocessor 3 True Likely"),
	TO_ENUM(MIPS_bgez, "Branch on Greater Than or Equal to Zero"),
	TO_ENUM(MIPS_bgezal, "Branch on Greater Than or Equal to Zero And Link"),
	TO_ENUM(MIPS_bgezall, "Branch on Greater Than or Equal to Zero And Link Likely"),
	TO_ENUM(MIPS_bgezl, "Branch on Greater Than or Equal to Zero Likely"),
	TO_ENUM(MIPS_bgtz, "Branch on Greater Than Zero"),
	TO_ENUM(MIPS_bgtzl, "Branch on Greater Than Zero Likely"),
	TO_ENUM(MIPS_blez, "Branch on Less Than or Equal to Zero"),
	TO_ENUM(MIPS_blezl, "Branch on Less Than or Equal to Zero Likely"),
	TO_ENUM(MIPS_bltz, "Branch on Less Than Zero"),
	TO_ENUM(MIPS_bltzal, "Branch on Less Than Zero And Link"),
	TO_ENUM(MIPS_bltzall, "Branch on Less Than Zero And Link Likely"),
	TO_ENUM(MIPS_bltzl, "Branch on Less Than Zero Likely"),
	TO_ENUM(MIPS_beq, "Branch on Equal"),
	TO_ENUM(MIPS_beql, "Branch on Equal Likely"),
	TO_ENUM(MIPS_bne, "Branch on Not Equal"),
	TO_ENUM(MIPS_bnel, "Branch on Not Equal Likely"),
	TO_ENUM(MIPS_jalr, "Jump And Link Register"),
	TO_ENUM(MIPS_j, "Jump"),
	TO_ENUM(MIPS_jr, "Jump Register"),
	TO_ENUM(MIPS_jal, "Jump And Link"),
	TO_ENUM(MIPS_jalx, "Jump And Link And Exchange"),
	TO_ENUM(MIPS_cache, "Cache Operation"),
	TO_ENUM(MIPS_lb, "Load Byte"),
	TO_ENUM(MIPS_lbu, "Load Byte Unsigned"),
	TO_ENUM(MIPS_ldl, "Load Doubleword Left"),
	TO_ENUM(MIPS_ldr, "Load Doubleword Right"),
	TO_ENUM(MIPS_lwl, "Load Word Left"),
	TO_ENUM(MIPS_lwr, "Load Word Right"),
	TO_ENUM(MIPS_ld, "Load Doubleword"),
	TO_ENUM(MIPS_lld, "Load Linked Doubleword"),
	TO_ENUM(MIPS_ldc1, "Load Double FPU"),
	TO_ENUM(MIPS_ldc2, "Load Double Coprocessor 2"),
	TO_ENUM(MIPS_ll, "Load Linked"),
	TO_ENUM(MIPS_lw, "Load Word"),
	TO_ENUM(MIPS_lwu, "Load Word Unsigned"),
	TO_ENUM(MIPS_lh, "Load Halfword"),
	TO_ENUM(MIPS_lhu, "Load Halfword Unsigned"),
	TO_ENUM(MIPS_lui, "Load Upper Immediate"),
	TO_ENUM(MIPS_lwc1, "Load Word to FPU"),
	TO_ENUM(MIPS_lwc2, "Load Word to Coprocessor 2"),
	TO_ENUM(MIPS_sb, "Store Byte"),
	TO_ENUM(MIPS_sdl, "Store Doubleword Left"),
	TO_ENUM(MIPS_sdr, "Store Doubleword Right"),
	TO_ENUM(MIPS_swl, "Store Word Left"),
	TO_ENUM(MIPS_swr, "Store Word Right"),
	TO_ENUM(MIPS_scd, "Store Conditional Doubleword"),
	TO_ENUM(MIPS_sd, "Store Doubleword"),
	TO_ENUM(MIPS_sdc1, "Store Double FPU"),
	TO_ENUM(MIPS_sdc2, "Store Double Coprocessor 2"),
	TO_ENUM(MIPS_sc, "Store Conditional"),
	TO_ENUM(MIPS_sw, "Store Word"),
	TO_ENUM(MIPS_sh, "Store Halfword"),
	TO_ENUM(MIPS_swc1, "Store Word from FPU"),
	TO_ENUM(MIPS_swc2, "Store Word from Coprocessor 2"),
	TO_ENUM(MIPS_sync, "Sync"),
	TO_ENUM(MIPS_eret, "Exception Return"),
	TO_ENUM(MIPS_tlbp, "Probe TLB for Matching Entry"),
	TO_ENUM(MIPS_tlbr, "Read Indexed TLB Entry"),
	TO_ENUM(MIPS_tlbwi, "Write Indexed TLB Entry"),
	TO_ENUM(MIPS_tlbwr, "Write Random TLB Entry"),
	TO_ENUM(MIPS_fadd, "Floating-point Add"),
	TO_ENUM(MIPS_fsub, "Floating-point Subtract"),
	TO_ENUM(MIPS_fmul, "Floating-point Multiply"),
	TO_ENUM(MIPS_fdiv, "Floating-point Divide"),
	TO_ENUM(MIPS_fabs, "Floating-point Absolute Value"),
	TO_ENUM(MIPS_fcvt_s, "Floating-point Convert to Single Fixed-Point Format"),
	TO_ENUM(MIPS_fcvt_d, "Floating-point Convert to Double Floating-Point Format"),
	TO_ENUM(MIPS_fcvt_w, "Floating-point Convert to Fixed-Point Format"),
	TO_ENUM(MIPS_fcvt_l, "Floating-point Convert to Long Fixed-Point Format"),
	TO_ENUM(MIPS_fround_l, "Floating-point Round to Long Fixed-Point Format"),
	TO_ENUM(MIPS_ftrunc_l, "Floating-point Truncate to Long Fixed-Point Format"),
	TO_ENUM(MIPS_fceil_l, "Floating-point Ceiling to Long Fixed-Point Format"),
	TO_ENUM(MIPS_ffloor_l, "Floating-point Floor to Long Fixed-Point Format"),
	TO_ENUM(MIPS_fround_w, "Floating-point Round to Single Fixed-Point Format"),
	TO_ENUM(MIPS_ftrunc_w, "Floating-point Truncate to Single Fixed-Point Format"),
	TO_ENUM(MIPS_fceil_w, "Floating-point Ceiling to Single Fixed-Point Format"),
	TO_ENUM(MIPS_ffloor_w, "Floating-point Floor to Single Fixed-Point Format"),
	TO_ENUM(MIPS_fmov, "Floating-point Move"),
	TO_ENUM(MIPS_fneg, "Floating-point Negate"),
	TO_ENUM(MIPS_fsqrt, "Floating-point Square Root"),
	TO_ENUM(MIPS_fc_f, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_un, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_eq, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ueq, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_olt, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ult, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ole, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ule, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_sf, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ngle, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_seq, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ngl, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_lt, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_nge, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_le, "Floating-point Compare"),
	TO_ENUM(MIPS_fc_ngt, "Floating-point Compare"),
	TO_ENUM(MIPS_nop, "No operation"),
	TO_ENUM(MIPS_mov, "Move register"),
	TO_ENUM(MIPS_neg, "Negate"),
	TO_ENUM(MIPS_negu, "Negate Unsigned"),
	TO_ENUM(MIPS_bnez, "Branch on Not Zero"),
	TO_ENUM(MIPS_bnezl, "Branch on Not Zero Likely"),
	TO_ENUM(MIPS_beqz, "Branch on Zero"),
	TO_ENUM(MIPS_beqzl, "Branch on Zero Likely"),
	TO_ENUM(MIPS_b, "Branch Always"),
	TO_ENUM(MIPS_bal, "Branch Always and Link"),
	TO_ENUM(MIPS_li, "Load Immediate"),
	TO_ENUM(MIPS_la, "Load Address"),
	TO_ENUM(MIPS_pref, "Prefetch"),
	TO_ENUM(MIPS_ldxc1, "Load Doubleword Indexed to Floating Point"),
	TO_ENUM(MIPS_lwxc1, "Load Word Indexed to Floating Point"),
	TO_ENUM(MIPS_sdxc1, "Store Doubleword Indexed from Floating Point"),
	TO_ENUM(MIPS_swxc1, "Store Word Indexed from Floating Point"),
	TO_ENUM(MIPS_madd_s, "Floating-Point Multiply Add"),
	TO_ENUM(MIPS_madd_d, "Floating-Point Multiply Add"),
	TO_ENUM(MIPS_msub_s, "Floating-Point Multiply Subtract"),
	TO_ENUM(MIPS_msub_d, "Floating-Point Multiply Subtract"),
	TO_ENUM(MIPS_movf, "Move Conditional on FP False"),
	TO_ENUM(MIPS_movt, "Move Conditional on FP True"),
	TO_ENUM(MIPS_movn, "Move Conditional on Not Zero"),
	TO_ENUM(MIPS_movz, "Move Conditional on Zero"),
	TO_ENUM(MIPS_fmovf, "Floating-Point Move Conditional on FP False"),
	TO_ENUM(MIPS_fmovt, "Floating-Point Move Conditional on FP True"),
	TO_ENUM(MIPS_fmovn, "Floating-Point Move Conditional on Not Zero"),
	TO_ENUM(MIPS_fmovz, "Floating-Point Move Conditional on Zero"),
	TO_ENUM(MIPS_nmadd_s, "Floating-Pont Negative Multiply Add"),
	TO_ENUM(MIPS_nmadd_d, "Floating-Pont Negative Multiply Add"),
	TO_ENUM(MIPS_nmsub_s, "Floating-Pont Negative Multiply Subtract"),
	TO_ENUM(MIPS_nmsub_d, "Floating-Pont Negative Multiply Subtract"),
	TO_ENUM(MIPS_prefx, "Prefetch Indexed"),
	TO_ENUM(MIPS_frecip, "Reciprocal Approximation"),
	TO_ENUM(MIPS_frsqrt, "Reciprocal Suare Root Approximation"),
	TO_ENUM(MIPS_lbv, "Load Byte into Vector"),
	TO_ENUM(MIPS_lsv, "Load Short into Vector"),
	TO_ENUM(MIPS_llv, "Load Word into Vector"),
	TO_ENUM(MIPS_ldv, "Load Doubleword into Vector"),
	TO_ENUM(MIPS_lqv, "Load Quadword into Vector"),
	TO_ENUM(MIPS_lrv, "Load Rest Vector"),
	TO_ENUM(MIPS_lpv, "Load Packed Vector"),
	TO_ENUM(MIPS_luv, "Load Unpack Vector"),
	TO_ENUM(MIPS_lhv, "Load Half Vector"),
	TO_ENUM(MIPS_lfv, "Load Fourth Vector"),
	TO_ENUM(MIPS_lwv, "Load Wrap Vector"),
	TO_ENUM(MIPS_ltv, "Load Transpose Vector"),
	TO_ENUM(MIPS_sbv, "Store Byte from Vector"),
	TO_ENUM(MIPS_ssv, "Store Short from Vector"),
	TO_ENUM(MIPS_slv, "Store Word from Vector"),
	TO_ENUM(MIPS_sdv, "Store Doubleword from Vector"),
	TO_ENUM(MIPS_sqv, "Store Quadword from Vector"),
	TO_ENUM(MIPS_srv, "Store Rest Vector"),
	TO_ENUM(MIPS_spv, "Store Packed Vector"),
	TO_ENUM(MIPS_suv, "Store Unpack Vector"),
	TO_ENUM(MIPS_shv, "Store Half Vector"),
	TO_ENUM(MIPS_sfv, "Store Fourth Vector"),
	TO_ENUM(MIPS_swv, "Store Wrap Vector"),
	TO_ENUM(MIPS_stv, "Store Transpose Vector"),
	TO_ENUM(MIPS_vmulf, "Vector (Frac) Multiply"),
	TO_ENUM(MIPS_vmacf, "Vector (Frac) Multiply Accumulate"),
	TO_ENUM(MIPS_vmulu, "Vector (Unsigned Frac) Multiply"),
	TO_ENUM(MIPS_vmacu, "Vector (Unsigned Frac) Multiply Accumulate"),
	TO_ENUM(MIPS_vrndp, "Vector DCT Round (+)"),
	TO_ENUM(MIPS_vrndn, "Vector DCT Round (-)"),
	TO_ENUM(MIPS_vmulq, "Vector (Integer) Multiply"),
	TO_ENUM(MIPS_vmacq, "Vector (Integer) Multiply Accumulate"),
	TO_ENUM(MIPS_vmudh, "Vector (High) Multiply"),
	TO_ENUM(MIPS_vmadh, "Vector (High) Multiply Accumulate"),
	TO_ENUM(MIPS_vmudm, "Vector (Mid-M) Multiply"),
	TO_ENUM(MIPS_vmadm, "Vector (Mid-M) Multiply Accumulate"),
	TO_ENUM(MIPS_vmudn, "Vector (Mid-N) Multiply"),
	TO_ENUM(MIPS_vmadn, "Vector (Mid-N) Multiply Accumulate"),
	TO_ENUM(MIPS_vmudl, "Vector (Low) Multiply"),
	TO_ENUM(MIPS_vmadl, "Vector (Low) Multiply Accumulate"),
	TO_ENUM(MIPS_vadd, "Vector Add"),
	TO_ENUM(MIPS_vsub, "Vector Subtract"),
	TO_ENUM(MIPS_vsut, "Vector SUT (vt - vs)"),
	TO_ENUM(MIPS_vabs, "Vector Absolute Value"),
	TO_ENUM(MIPS_vaddc, "Vector ADDC"),
	TO_ENUM(MIPS_vsubc, "Vector SUBC"),
	TO_ENUM(MIPS_vaddb, "Vector Add Byte"),
	TO_ENUM(MIPS_vsubb, "Vector Subtract Byte"),
	TO_ENUM(MIPS_vaccb, "Vector Add Byte/Add Accumulator"),
	TO_ENUM(MIPS_vsucb, "Vector Subtract Byte/Add Accumulator"),
	TO_ENUM(MIPS_vsad, "Vector SAD"),
	TO_ENUM(MIPS_vsac, "Vector SAC"),
	TO_ENUM(MIPS_vsum, "Vector SUM"),
	TO_ENUM(MIPS_vsaw, "Vector SAW"),
	TO_ENUM(MIPS_vlt, "Vector Less Than"),
	TO_ENUM(MIPS_veq, "Vector Equal To"),
	TO_ENUM(MIPS_vne, "Vector Not Equal To"),
	TO_ENUM(MIPS_vge, "Vector Greater Than or Equal To"),
	TO_ENUM(MIPS_vcl, "Vector Clip Low"),
	TO_ENUM(MIPS_vch, "Vector Clip High"),
	TO_ENUM(MIPS_vcr, "Vector 1's Complement Clip"),
	TO_ENUM(MIPS_vmrg, "Vector Merge"),
	TO_ENUM(MIPS_vand, "Vector Logical AND"),
	TO_ENUM(MIPS_vnand, "Vector Logical NAND"),
	TO_ENUM(MIPS_vor, "Vector Logical OR"),
	TO_ENUM(MIPS_vnor, "Vector Logical NOR"),
	TO_ENUM(MIPS_vxor, "Vector Logical Exclusive OR"),
	TO_ENUM(MIPS_vnxor, "Vector Logical NOT Exclusive OR"),
	TO_ENUM(MIPS_vnoop, "Vector No-Operation"),
	TO_ENUM(MIPS_vmov, "Vector Scalar-Element Move"),
	TO_ENUM(MIPS_vrcp, "Single Precision, Lookup Source, Write Result"),
	TO_ENUM(MIPS_vrsq, "Single Precision, Lookup Source, Write Result"),
	TO_ENUM(MIPS_vrcph, "Set Source, Write Previous Result"),
	TO_ENUM(MIPS_vrsqh, "Set Source, Write Previous Result"),
	TO_ENUM(MIPS_vrcpl, "Lookup Source and Previous, Write Result"),
	TO_ENUM(MIPS_vrsql, "Lookup Source and Previous, Write Result"),
	TO_ENUM(MIPS_vinst, "Vector Insert Triple (5/5/5/1)"),
	TO_ENUM(MIPS_vextt, "Vector Extract Triple (5/5/5/1)"),
	TO_ENUM(MIPS_vinsq, "Vector Insert Quad (4/4/4/4)"),
	TO_ENUM(MIPS_vextq, "Vector Extract Quad (4/4/4/4)"),
	TO_ENUM(MIPS_vinsn, "Vector Insert Nibble (4/4/4/4) Sign-Extended"),
	TO_ENUM(MIPS_vextn, "Vector Insert Nibble (4/4/4/4) Sign-Extended"),
	TO_ENUM(MIPS_cfc0, "Move Control From Coprocessor 0"),
	TO_ENUM(MIPS_ctc0, "Move Control to Coprocessor 0"),
	TO_ENUM(MIPS_mtsa, "Move To Shift Amount Register"),
	TO_ENUM(MIPS_R5900_first, "Undocumented instruction MIPS_R5900_first"),
	TO_ENUM(MIPS_mfsa, "Move From Shift Amount Register"),
	TO_ENUM(MIPS_mtsab, "Move Byte Count To Shift Amount Register"),
	TO_ENUM(MIPS_mtsah, "Move Halfword Count To Shift Amount Register"),
	TO_ENUM(MIPS_fadda, "Floating-point add to accumulator"),
	TO_ENUM(MIPS_fsuba, "Floating-point subtract to accumulator"),
	TO_ENUM(MIPS_fmula, "Floating-point multiply to accumulator"),
	TO_ENUM(MIPS_fmadda, "Floating-point multiply and add to accumulator"),
	TO_ENUM(MIPS_fmsuba, "Floating-point multiply and subtract from accumulator"),
	TO_ENUM(MIPS_fmadd, "Floating-point multiply and add"),
	TO_ENUM(MIPS_fmsub, "Floating-point multiply and subtract"),
	TO_ENUM(MIPS_fmax, "Floating-point maximum"),
	TO_ENUM(MIPS_fmin, "Floating-point minimum"),
	TO_ENUM(MIPS_plzcw, "Parallel Leading Zero or One Count Word"),
	TO_ENUM(MIPS_mthi1, "Move To HI1 Register"),
	TO_ENUM(MIPS_mtlo1, "Move To LO1 Register"),
	TO_ENUM(MIPS_pmthl_lw, "Parallel Move From HI/LO Register"),
	TO_ENUM(MIPS_pmthi, "Parallel Move To HI Register"),
	TO_ENUM(MIPS_pmtlo, "Parallel Move To LO Register"),
	TO_ENUM(MIPS_div1, "Divide Pipeline 1"),
	TO_ENUM(MIPS_divu1, "Divide Unsigned Pipeline 1"),
	TO_ENUM(MIPS_pdivw, "Parallel Divide Word"),
	TO_ENUM(MIPS_pdivuw, "Parallel Divide Unsigned Word"),
	TO_ENUM(MIPS_pdivbw, "Parallel Divide Broadcast Word"),
	TO_ENUM(MIPS_paddw, "Parallel Add Word"),
	TO_ENUM(MIPS_pmaddw, "Parallel Multiply-Add Word"),
	TO_ENUM(MIPS_mult1, "Multiply Pipeline 1"),
	TO_ENUM(MIPS_multu1, "Multiply Unsigned Pipeline 1"),
	TO_ENUM(MIPS_madd1, "Multiply-Add Pipeline 1"),
	TO_ENUM(MIPS_maddu1, "Multiply-Add Unsigned Pipeline 1"),
	TO_ENUM(MIPS_pmadduw, "Parallel Multiply-Add Unsigned Word"),
	TO_ENUM(MIPS_psubw, "Parallel Subtract HalfWord"),
	TO_ENUM(MIPS_pcgtw, "Parallel Compare for Greater Than Word"),
	TO_ENUM(MIPS_psllvw, "Parallel Shift Left Logical Variable Word"),
	TO_ENUM(MIPS_pceqw, "Parallel Compare for Equal Word"),
	TO_ENUM(MIPS_pmaxw, "Parallel Maximize Word"),
	TO_ENUM(MIPS_psrlvw, "Parallel Shift Right Logical Variable Word"),
	TO_ENUM(MIPS_pminw, "Parallel Minimize Word"),
	TO_ENUM(MIPS_psravw, "Parallel Shift Right Arithmetic Variable Word"),
	TO_ENUM(MIPS_paddh, "Parallel Add Halfword"),
	TO_ENUM(MIPS_pmsubw, "Parallel Multiply-Subtract Word"),
	TO_ENUM(MIPS_padsbh, "Parallel Add/Subtract Halfword"),
	TO_ENUM(MIPS_psubh, "Parallel Subtract Halfword"),
	TO_ENUM(MIPS_pcgth, "Parallel Compare for Greater Than Halfword"),
	TO_ENUM(MIPS_pceqh, "Parallel Compare for Equal Halfword"),
	TO_ENUM(MIPS_pmaxh, "Parallel Maximize Halfword"),
	TO_ENUM(MIPS_pminh, "Parallel Minimize Halfword"),
	TO_ENUM(MIPS_paddb, "Parallel Add Byte"),
	TO_ENUM(MIPS_psubb, "Parallel Subtract Byte"),
	TO_ENUM(MIPS_pcgtb, "Parallel Compare for Greater Than Byte"),
	TO_ENUM(MIPS_pinth, "Parallel Interleave Halfword"),
	TO_ENUM(MIPS_pceqb, "Parallel Compare for Equal Byte"),
	TO_ENUM(MIPS_pintoh, "Parallel Interleave Odd Halfword"),
	TO_ENUM(MIPS_pmultw, "Parallel Multiply Word"),
	TO_ENUM(MIPS_pmultuw, "Parallel Multiply Unsigned Word"),
	TO_ENUM(MIPS_pcpyld, "Parallel Copy Lower Doubleword"),
	TO_ENUM(MIPS_pcpyud, "Parallel Copy Upper Doubleword"),
	TO_ENUM(MIPS_paddsw, "Parallel Add with Signed Saturation Word"),
	TO_ENUM(MIPS_pmaddh, "Parallel Multiply-Add Halfword"),
	TO_ENUM(MIPS_padduw, "Parallel Add with Unsigned Saturation Word"),
	TO_ENUM(MIPS_psubsw, "Parallel Subtract with Signed Saturation Word"),
	TO_ENUM(MIPS_phmadh, "Parallel Horizontal Multiply-Add Halfword"),
	TO_ENUM(MIPS_psubuw, "Parallel Subtract with Unsigned Saturation Word"),
	TO_ENUM(MIPS_pextlw, "Parallel Extend Lower from Word"),
	TO_ENUM(MIPS_pand, "Parallel AND"),
	TO_ENUM(MIPS_pextuw, "Parallel Extend Upper from Word"),
	TO_ENUM(MIPS_por, "Parallel OR"),
	TO_ENUM(MIPS_ppacw, "Paralle Pack to Word"),
	TO_ENUM(MIPS_pxor, "Parallel XOR"),
	TO_ENUM(MIPS_pnor, "Parallel NOR"),
	TO_ENUM(MIPS_paddsh, "Parallel Add with Signed Saturation Halfword"),
	TO_ENUM(MIPS_pmsubh, "Parallel Multiply-Subtract Halfword"),
	TO_ENUM(MIPS_padduh, "Parallel Add with Unsigned Saturation Halfword"),
	TO_ENUM(MIPS_psubsh, "Parallel Subtract with Signed Saturation Halfword"),
	TO_ENUM(MIPS_phmsbh, "Parallel Horizontal Multiply-Subtract Halfword"),
	TO_ENUM(MIPS_psubuh, "Parallel Subtract with Unsigned Saturation Halfword"),
	TO_ENUM(MIPS_pextlh, "Parallel Extend Lower from Halfword"),
	TO_ENUM(MIPS_pextuh, "Parallel Extend Upper from Halfword"),
	TO_ENUM(MIPS_ppach, "Paralle Pack to Halfword"),
	TO_ENUM(MIPS_paddsb, "Parallel Add with Signed Saturation Byte"),
	TO_ENUM(MIPS_paddub, "Parallel Add with Unsigned Saturation Byte"),
	TO_ENUM(MIPS_psubsb, "Parallel Subtract with Signed Saturation Byte"),
	TO_ENUM(MIPS_psubub, "Parallel Subtract with Unsigned Saturation Byte"),
	TO_ENUM(MIPS_pextlb, "Parallel Extend Lower from Byte"),
	TO_ENUM(MIPS_pextub, "Parallel Extend Upper from Byte"),
	TO_ENUM(MIPS_ppacb, "Paralle Pack to Byte"),
	TO_ENUM(MIPS_qfsrv, "Quadword Funnel Shift Right Variable"),
	TO_ENUM(MIPS_pmulth, "Parallel Multiply Halfword"),
	TO_ENUM(MIPS_pabsw, "Parallel Absolute Word"),
	TO_ENUM(MIPS_pabsh, "Parallel Absolute Halfword"),
	TO_ENUM(MIPS_pexoh, "Parallel Exchange Odd Halfword"),
	TO_ENUM(MIPS_pexch, "Parallel Exchange Center Halfword"),
	TO_ENUM(MIPS_prevh, "Parallel Reverse Halfword"),
	TO_ENUM(MIPS_pcpyh, "Parallel Copy Halfword"),
	TO_ENUM(MIPS_pext5, "Parallel Extend Upper from 5 bits"),
	TO_ENUM(MIPS_pexow, "Parallel Exchange Odd Word"),
	TO_ENUM(MIPS_pexcw, "Parallel Exchange Center Word"),
	TO_ENUM(MIPS_ppac5, "Parallel Pack to 5 bits"),
	TO_ENUM(MIPS_prot3w, "Parallel Rotate 3 Words"),
	TO_ENUM(MIPS_psllh, "Parallel Shift Left Logical Halfword"),
	TO_ENUM(MIPS_psrlh, "Parallel Shift Right Logical Halfword"),
	TO_ENUM(MIPS_psrah, "Parallel Shift Right Arithmetic Halfword"),
	TO_ENUM(MIPS_psllw, "Parallel Shift Left Logical Word"),
	TO_ENUM(MIPS_psrlw, "Parallel Shift Right Logical Word"),
	TO_ENUM(MIPS_psraw, "Parallel Shift Right Arithmetic Word"),
	TO_ENUM(MIPS_mfhi1, "Move From HI1 Register"),
	TO_ENUM(MIPS_mflo1, "Move From LO1 Register"),
	TO_ENUM(MIPS_pmfhi, "Parallel Move From HI Register"),
	TO_ENUM(MIPS_pmflo, "Parallel Move From LO Register"),
	TO_ENUM(MIPS_pmfhl, "Parallel Move From HI/LO Register"),
	TO_ENUM(MIPS_lq, "Load Quadword"),
	TO_ENUM(MIPS_sq, "Store Quadword"),
	TO_ENUM(MIPS_lqc2, "Load Quadword Coprocessor 2"),
	TO_ENUM(MIPS_sqc2, "Store Quadword Coprocessor 2"),
	TO_ENUM(MIPS_madd_r5900, "Multiply/Add"),
	TO_ENUM(MIPS_maddu_r5900, "Multiply/Add Unsigned"),
	TO_ENUM(MIPS_R5900_last, "Undocumented instruction MIPS_R5900_last"),
	TO_ENUM(MIPS_mult3, "Multiply (3-operand)"),
	TO_ENUM(MIPS_multu3, "Multiply Unsigned (3-operand)"),
	TO_ENUM(MIPS_bteqz, "Branch on T Equal to Zero (same as 439)"),
	TO_ENUM(MIPS_btnez, "Branch on T Not Equal to Zero"),
	TO_ENUM(MIPS_cmp, "Compare"),
	TO_ENUM(MIPS_cmpi, "Compare Immediate"),
	TO_ENUM(MIPS_extend, "Extend (same as 458)"),
	TO_ENUM(MIPS_move, "Move (same as 473)"),
	TO_ENUM(MIPS_not, "Not (same as 477)"),
	TO_ENUM(MIPS_dla, "Load 64-bit address (same as 495)"),
	TO_ENUM(MIPS_clo, "Count Leading Ones in Word (same as 498)"),
	TO_ENUM(MIPS_clz, "Count Leading Zeros in Word"),
	TO_ENUM(MIPS_madd, "Multiply/Add"),
	TO_ENUM(MIPS_maddu, "Multiply/Add Unsigned"),
	TO_ENUM(MIPS_msub, "Multiply and Subtract Word to Hi,Lo"),
	TO_ENUM(MIPS_msubu, "Multiply and Subtract Word to Hi,Lo"),
	TO_ENUM(MIPS_mul, "Multiply Word to GPR"),
	TO_ENUM(MIPS_sdbbp, "Software Debug Breakpoint"),
	TO_ENUM(MIPS_wait, "Enter Standby Mode"),
	TO_ENUM(MIPS_alnv_ps, "Floating Point Align Variable"),
	TO_ENUM(MIPS_deret, "Debug Exception Return"),
	TO_ENUM(MIPS_di, "Disable interrupts"),
	TO_ENUM(MIPS_ehb, "Execution Hazard Barrier"),
	TO_ENUM(MIPS_ei, "Enable interrupts"),
	TO_ENUM(MIPS_ext, "Extract Bit Field"),
	TO_ENUM(MIPS_fcvt_ps, "Floating Point Convert Pair to Paired Single"),
	TO_ENUM(MIPS_fcvt_s_pl, "Floating Point Convert Pair Lower to Single Floating Point"),
	TO_ENUM(MIPS_fcvt_s_pu, "Floating Point Convert Pair Upper to Single Floating Point"),
	TO_ENUM(MIPS_ins, "Insert Bit Field"),
	TO_ENUM(MIPS_jalr_hb, "Jump and Link Register with Hazard Barrier"),
	TO_ENUM(MIPS_jr_hb, "Jump Register with Hazard Barrier"),
	TO_ENUM(MIPS_luxc1, "Load Doubleword Indexed Unaligned to Floating Point"),
	TO_ENUM(MIPS_madd_ps, "Floating Point Multiply Add"),
	TO_ENUM(MIPS_mfhc1, "Move Word from High Half of Floating Point Register"),
	TO_ENUM(MIPS_mfhc2, "Move Word from High Half of Coprocessor 2 Register"),
	TO_ENUM(MIPS_msub_ps, "Floating Point Multiply Subtract"),
	TO_ENUM(MIPS_mthc1, "Move Word to High Half of Floating Point Register"),
	TO_ENUM(MIPS_mthc2, "Move Word to High Half of Coprocessor 2 Register"),
	TO_ENUM(MIPS_nmadd_ps, "Floating Point Negative Multiply Add"),
	TO_ENUM(MIPS_nmsub_ps, "Floating Point Negative Multiply Subtract"),
	TO_ENUM(MIPS_pll, "Pair Lower Lower"),
	TO_ENUM(MIPS_plu, "Pair Lower Upper"),
	TO_ENUM(MIPS_pul, "Pair Upper Lower"),
	TO_ENUM(MIPS_puu, "Pair Upper Upper"),
	TO_ENUM(MIPS_rdhwr, "Read Hardware Register"),
	TO_ENUM(MIPS_rdpgpr, "Read GPR from Previous Shadow Set"),
	TO_ENUM(MIPS_rotr, "Rotate Word Right"),
	TO_ENUM(MIPS_rotrv, "Rotate Word Right Variable"),
	TO_ENUM(MIPS_seb, "Sign-Extend Byte"),
	TO_ENUM(MIPS_seh, "Sign-Extend Halfword"),
	TO_ENUM(MIPS_suxc1, "Store Doubleword Indexed Unaligned from Floating Point"),
	TO_ENUM(MIPS_synci, "Synchronize Caches to Make Instruction Writes Effective"),
	TO_ENUM(MIPS_wrpgpr, "Write GPR to Previous Shadow Set"),
	TO_ENUM(MIPS_wsbh, "Word Swap Bytes Within Halfwords"),
	TO_ENUM(MIPS_dmfc1, "Doubleword Move From CP1"),
	TO_ENUM(MIPS_dmtc1, "Doubleword Move To CP1"),
	TO_ENUM(MIPS_save, "Save Registers and Set Up Stack Frame"),
	TO_ENUM(MIPS_restore, "Restore Registers and Deallocate Stack Frame"),
	TO_ENUM(MIPS_jalrc, "Jump and Link Register, Compact"),
	TO_ENUM(MIPS_jrc, "Jump Register, Compact"),
	TO_ENUM(MIPS_sew, "Sign-Extend Word"),
	TO_ENUM(MIPS_zeb, "Zero-Extend Byte"),
	TO_ENUM(MIPS_zeh, "Zero-Extend Halfword"),
	TO_ENUM(MIPS_zew, "Zero-Extend Word"),
	TO_ENUM(MIPS_ssnop, "Superscalar No operation"),
	TO_ENUM(MIPS_li_s, "Load floating-point immediate"),
	TO_ENUM(MIPS_li_d, "Load floating-point immediate"),
	TO_ENUM(MIPS_dneg, "Negate"),
	TO_ENUM(MIPS_dnegu, "Negate Unsigned"),
	TO_ENUM(MIPS_pause, "Wait for the LLBit to clear"),
	TO_ENUM(MIPS_dclo, "Count Leading Ones in Doubleword"),
	TO_ENUM(MIPS_dclz, "Count Leading Zeros in Doubleword"),
	TO_ENUM(MIPS_dext, "Doubleword Extract Bit Field"),
	TO_ENUM(MIPS_dextm, "Doubleword Extract Bit Field Middle"),
	TO_ENUM(MIPS_dextu, "Doubleword Extract Bit Field Upper"),
	TO_ENUM(MIPS_dins, "Doubleword Insert Bit Field"),
	TO_ENUM(MIPS_dinsm, "Doubleword Insert Bit Field Middle"),
	TO_ENUM(MIPS_dinsu, "Doubleword Insert Bit Field Upper"),
	TO_ENUM(MIPS_dmfc2, "Doubleword Move From CP2"),
	TO_ENUM(MIPS_dmtc2, "Doubleword Move To CP2"),
	TO_ENUM(MIPS_drotr, "Doubleword Rotate Right"),
	TO_ENUM(MIPS_drotr32, "Doubleword Rotate Right Plus 32"),
	TO_ENUM(MIPS_drotrv, "Doubleword Rotate Right Variable"),
	TO_ENUM(MIPS_dsbh, "Doubleword Swap Bytes Within Halfwords"),
	TO_ENUM(MIPS_dshd, "Doubleword Swap Halfwords Within Doublewords"),
	TO_ENUM(MIPS_baddu, "Unsigned Byte Add"),
	TO_ENUM(MIPS_bbit0, "Branch on Bit Clear"),
	TO_ENUM(MIPS_bbit032, "Branch on Bit Clear Plus 32"),
	TO_ENUM(MIPS_bbit1, "Branch on Bit Set"),
	TO_ENUM(MIPS_bbit132, "Branch on Bit Set Plus 32"),
	TO_ENUM(MIPS_cins, "Clear and Insert a Bit Field"),
	TO_ENUM(MIPS_cins32, "Clear and Insert a Bit Field Plus 32"),
	TO_ENUM(MIPS_dmul, "Multiply Doubleword to GPR"),
	TO_ENUM(MIPS_dpop, "Count Ones in a Doubleword"),
	TO_ENUM(MIPS_exts, "Extract a Signed Bit Field"),
	TO_ENUM(MIPS_exts32, "Extract a Signed Bit Field Plus 32"),
	TO_ENUM(MIPS_mtm0, "Load Multiplier Register MPL0"),
	TO_ENUM(MIPS_mtm1, "Load Multiplier Register MPL1"),
	TO_ENUM(MIPS_mtm2, "Load Multiplier Register MPL2"),
	TO_ENUM(MIPS_mtp0, "Load Multiplier Register P0"),
	TO_ENUM(MIPS_mtp1, "Load Multiplier Register P1"),
	TO_ENUM(MIPS_mtp2, "Load Multiplier Register P2"),
	TO_ENUM(MIPS_pop, "Count Ones in a Word"),
	TO_ENUM(MIPS_saa, "Store Atomic Add Word"),
	TO_ENUM(MIPS_saad, "Store Atomic Add Double Word"),
	TO_ENUM(MIPS_seq, "Set on Equal"),
	TO_ENUM(MIPS_seqi, "Set on Equal Immediate"),
	TO_ENUM(MIPS_sne, "Set on Not Equal"),
	TO_ENUM(MIPS_snei, "Set on Not Equal Immediate"),
	TO_ENUM(MIPS_synciobdma, "Synchronize IOBDMAs"),
	TO_ENUM(MIPS_syncs, "Synchronize Special"),
	TO_ENUM(MIPS_syncw, "Synchronize Stores"),
	TO_ENUM(MIPS_syncws, "Synchronize Stores Special"),
	TO_ENUM(MIPS_uld, "Unaligned Load Doubleword"),
	TO_ENUM(MIPS_ulw, "Unaligned Load Word"),
	TO_ENUM(MIPS_usd, "Unaligned Store Doubleword"),
	TO_ENUM(MIPS_usw, "Unaligned Store Word"),
	TO_ENUM(MIPS_v3mulu, "192-bit x 64-bit Unsigned Multiply and Add"),
	TO_ENUM(MIPS_vmm0, "64-bit Unsigned Multiply and Add Move"),
	TO_ENUM(MIPS_vmulu_cn, "64-bit Unsigned Multiply and Add"),
	TO_ENUM(MIPS_dbreak, "Debug Break"),
	TO_ENUM(MIPS_dret, "Debug Return"),
	TO_ENUM(MIPS_mfdr, "Move from Debug Register"),
	TO_ENUM(MIPS_mtdr, "Move to Debug Register"),
	TO_ENUM(MIPS_ac0iu, "Add Coprocessor 0 Immediate Unsigned"),
	TO_ENUM(MIPS_bs1f, "Bit Search One Forward"),
	TO_ENUM(MIPS_bfins, "Bit field insert"),
	TO_ENUM(MIPS_addmiu, "Add Immediate to Memory Word"),
	TO_ENUM(MIPS_sadd, "Saturated Add"),
	TO_ENUM(MIPS_ssub, "Saturated Subtract"),
	TO_ENUM(MIPS_btst, "Bit Test"),
	TO_ENUM(MIPS_bclr, "Bit Clear"),
	TO_ENUM(MIPS_bset, "Bit Set"),
	TO_ENUM(MIPS_bins, "Bit Insert"),
	TO_ENUM(MIPS_bext, "Bit Extract"),
	TO_ENUM(MIPS_dive, "Divide, with Overflow Exception"),
	TO_ENUM(MIPS_diveu, "Divide unsigned, with Overflow Exception"),
	TO_ENUM(MIPS_min, "Minimum signed"),
	TO_ENUM(MIPS_max, "Maximum signed"),
	TO_ENUM(MIPS_madd3, "Multiply/Add (3-operand)"),
	TO_ENUM(MIPS_maddu3, "Multiply/Add Unsigned (3-operand)"),
	TO_ENUM(MIPS_msub3, "Multiply and Subtract Word to Hi,Lo (3-operand)"),
	TO_ENUM(MIPS_msubu3, "Multiply and Subtract Word to Hi,Lo (3-operand)"),
	TO_ENUM(MIPS_dvpe, "Disable Virtual Processor Execution"),
	TO_ENUM(MIPS_evpe, "Enable Virtual Processor Execution"),
	TO_ENUM(MIPS_dmt, "Disable Multi-Threaded Execution"),
	TO_ENUM(MIPS_emt, "Enable Multi-Threaded Execution"),
	TO_ENUM(MIPS_fork, "Allocate and Schedule a New Thread"),
	TO_ENUM(MIPS_yield, "Conditionally Deschedule or Deallocate the Current Thread"),
	TO_ENUM(MIPS_mftr, "Move From Thread Context"),
	TO_ENUM(MIPS_mftc0, "Move From Thread Context (CP0 register, low-order half)"),
	TO_ENUM(MIPS_mfthc0, "Move From Thread Context (CP0 register, high-order half)"),
	TO_ENUM(MIPS_mftlo, "Move From Thread Context (LO register)"),
	TO_ENUM(MIPS_mfthi, "Move From Thread Context (HI register)"),
	TO_ENUM(MIPS_mftacx, "Move From Thread Context (ACX register)"),
	TO_ENUM(MIPS_mftdsp, "Move From Thread Context (DSPControl register)"),
	TO_ENUM(MIPS_mfthc1, "Move From Thread Context (CP1 register, high-order half)"),
	TO_ENUM(MIPS_mftc1, "Move From Thread Context (CP1 register, low-order half)"),
	TO_ENUM(MIPS_cftc1, "Move From Thread Context (CP1 control register)"),
	TO_ENUM(MIPS_mfthc2, "Move From Thread Context (CP2 register, high-order half)"),
	TO_ENUM(MIPS_mftc2, "Move From Thread Context (CP2 register, low-order half)"),
	TO_ENUM(MIPS_cftc2, "Move From Thread Context (CP2 control register)"),
	TO_ENUM(MIPS_mftgpr, "Move From Thread Context (general-purpose register)"),
	TO_ENUM(MIPS_mttr, "Move To Thread Context"),
	TO_ENUM(MIPS_mttc0, "Move To Thread Context (CP0 register, low-order half)"),
	TO_ENUM(MIPS_mtthc0, "Move To Thread Context (CP0 register, high-order half)"),
	TO_ENUM(MIPS_mttlo, "Move To Thread Context (LO register)"),
	TO_ENUM(MIPS_mtthi, "Move To Thread Context (HI register)"),
	TO_ENUM(MIPS_mttacx, "Move To Thread Context (ACX register)"),
	TO_ENUM(MIPS_mttdsp, "Move To Thread Context (DSPControl register)"),
	TO_ENUM(MIPS_mtthc1, "Move To Thread Context (CP1 register, high-order half)"),
	TO_ENUM(MIPS_mttc1, "Move To Thread Context (CP1 register, low-order half)"),
	TO_ENUM(MIPS_cttc1, "Move To Thread Context (CP1 control register)"),
	TO_ENUM(MIPS_mtthc2, "Move To Thread Context (CP2 register, high-order half)"),
	TO_ENUM(MIPS_mttc2, "Move To Thread Context (CP2 register, low-order half)"),
	TO_ENUM(MIPS_cttc2, "Move To Thread Context (CP2 control register)"),
	TO_ENUM(MIPS_mttgpr, "Move To Thread Context (general-purpose register)"),
	TO_ENUM(MIPS_faddr, "Floating-point Reduction Addition"),
	TO_ENUM(MIPS_bc1any2f, "Branch on Any of Two Floating Point Condition Codes False"),
	TO_ENUM(MIPS_bc1any2t, "Branch on Any of Two Floating Point Condition Codes True"),
	TO_ENUM(MIPS_bc1any4f, "Branch on Any of Four Floating Point Condition Codes False"),
	TO_ENUM(MIPS_bc1any4t, "Branch on Any of Four Floating Point Condition Codes True"),
	TO_ENUM(MIPS_fcabs_f, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_un, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_eq, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ueq, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_olt, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ult, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ole, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ule, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_sf, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ngle, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_seq, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ngl, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_lt, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_nge, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_le, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcabs_ngt, "Floating-point Absolute Compare"),
	TO_ENUM(MIPS_fcvt_pw_ps, "Floating-point Convert Paired Single to Paired Word"),
	TO_ENUM(MIPS_fcvt_ps_pw, "Floating-point Convert Paired Word to Paired Single"),
	TO_ENUM(MIPS_fmulr, "Floating-point Reduction Multiply"),
	TO_ENUM(MIPS_frecip1, "Floating-point Reduced Precision Reciprocal (Step 1)"),
	TO_ENUM(MIPS_frecip2, "Floating-point Reduced Precision Reciprocal (Step 2)"),
	TO_ENUM(MIPS_frsqrt1, "Floating-point Reduced Precision Reciprocal Square Root (Step 1)"),
	TO_ENUM(MIPS_frsqrt2, "Floating-point Reduced Precision Reciprocal Square Root (Step 2)"),
	TO_ENUM(MIPS_lwxs, "Load Word Indexed, Scaled"),
	TO_ENUM(MIPS_maddp, "Multiply and Add Polynomial Basis Word to Hi,Lo"),
	TO_ENUM(MIPS_mflhxu, "Move from Extended Carry, Hi and Lo (Unsigned)"),
	TO_ENUM(MIPS_mtlhx, "Move to Lo, Hi, and Extended Carry"),
	TO_ENUM(MIPS_multp, "Multiply Binary Polynomial Basis Word"),
	TO_ENUM(MIPS_pperm, "Partial Permutation of Word Data into ACX-Hi-Lo Accumulator"),
	TO_ENUM(MIPS_jals, "Jump and Link, Short Delay Slot"),
	TO_ENUM(MIPS_lwp, "Load Word Pair"),
	TO_ENUM(MIPS_ldp, "Load Doubleword Pair"),
	TO_ENUM(MIPS_lwm, "Load Word Multiple"),
	TO_ENUM(MIPS_ldm, "Load Doubleword Multiple"),
	TO_ENUM(MIPS_swp, "Store Word Pair"),
	TO_ENUM(MIPS_sdp, "Store Doubleword Pair"),
	TO_ENUM(MIPS_swm, "Store Word Multiple"),
	TO_ENUM(MIPS_sdm, "Store Doubleword Multiple"),
	TO_ENUM(MIPS_bnezc, "Branch on Not Equal to Zero, Compact"),
	TO_ENUM(MIPS_bltzals, "Branch on Less Than Zero and Link, Short Delay-Slot"),
	TO_ENUM(MIPS_beqzc, "Branch on Equal to Zero, Compact"),
	TO_ENUM(MIPS_bgezals, "Branch on Greater Than or Equal to Zero and Link, Short Delay-Slot"),
	TO_ENUM(MIPS_jraddiusp, "Jump Register, Adjust Stack Pointer"),
	TO_ENUM(MIPS_jalrs, "Jump and Link Register, Short Delay Slot"),
	TO_ENUM(MIPS_jalrs_hb, "Jump and Link Register with Hazard Barrier, Short Delay-Slot"),
	TO_ENUM(MIPS_movep, "Move a Pair of Registers"),
	TO_ENUM(MIPS_dli, "Doubleword Load Immediate"),
	TO_ENUM(MIPS_insv, "Insert Bit Field Variable"),
	TO_ENUM(MIPS_dinsv, "Doubleword Insert Variable Bit Field"),
	TO_ENUM(MIPS_bposge32, "Branch on Greater Than or Equal To Value 32 in DSPControl Pos Field"),
	TO_ENUM(MIPS_bposge64, "Branch on Greater Than or Equal To Value 64 in DSPControl Pos Field"),
	TO_ENUM(MIPS_addu_qb, "Unsigned Add Quad Byte Vectors"),
	TO_ENUM(MIPS_addu_ph, "Unsigned Add Integer Halfwords"),
	TO_ENUM(MIPS_addsc, "Add Signed Word and Set Carry Bit"),
	TO_ENUM(MIPS_subu_qb, "Subtract Unsigned Quad Byte Vector"),
	TO_ENUM(MIPS_subu_ph, "Subtract Unsigned Integer Halfwords"),
	TO_ENUM(MIPS_addwc, "Add Word with Carry Bit"),
	TO_ENUM(MIPS_addq_ph, "Add Fractional Halfword Vectors"),
	TO_ENUM(MIPS_modsub, "Modular Subtraction on an Index Value"),
	TO_ENUM(MIPS_subq_ph, "Subtract Fractional Halfword Vector"),
	TO_ENUM(MIPS_addu_s_qb, "Unsigned Add Quad Byte Vectors"),
	TO_ENUM(MIPS_addu_s_ph, "Unsigned Add Integer Halfwords"),
	TO_ENUM(MIPS_raddu_w_qb, "Unsigned Reduction Add Vector Quad Bytes"),
	TO_ENUM(MIPS_muleq_s_w_phl, "Multiply Vector Fractional Left Halfwords to Expanded Width Products"),
	TO_ENUM(MIPS_subu_s_qb, "Subtract Unsigned Quad Byte Vector"),
	TO_ENUM(MIPS_subu_s_ph, "Subtract Unsigned Integer Halfwords"),
	TO_ENUM(MIPS_muleq_s_w_phr, "Multiply Vector Fractional Right Halfwords to Expanded Width Products"),
	TO_ENUM(MIPS_muleu_s_ph_qbl, "Multiply Unsigned Vector Left Bytes by Halfwords to Halfword Products"),
	TO_ENUM(MIPS_addq_s_ph, "Add Fractional Halfword Vectors"),
	TO_ENUM(MIPS_addq_s_w, "Add Fractional Words"),
	TO_ENUM(MIPS_mulq_s_ph, "Multiply Vector Fractional Half-Words to Same Size Products"),
	TO_ENUM(MIPS_muleu_s_ph_qbr, "Multiply Unsigned Vector Right Bytes with halfwords to Half Word Products"),
	TO_ENUM(MIPS_subq_s_ph, "Subtract Fractional Halfword Vector"),
	TO_ENUM(MIPS_subq_s_w, "Subtract Fractional Word"),
	TO_ENUM(MIPS_mulq_rs_ph, "Multiply Vector Fractional Halfwords to Fractional Halfword Products"),
	TO_ENUM(MIPS_addu_ob, "Unsigned Add Octal Byte Vectors"),
	TO_ENUM(MIPS_subu_ob, "Subtract Unsigned Octal Byte Vector"),
	TO_ENUM(MIPS_addq_qh, "Add Fractional Halfword Vectors"),
	TO_ENUM(MIPS_addq_pw, "Add Fractional Word Vectors"),
	TO_ENUM(MIPS_subq_qh, "Subtract Fractional Halfword Vector"),
	TO_ENUM(MIPS_subq_pw, "Subtract Fractional Word Vector"),
	TO_ENUM(MIPS_addu_s_ob, "Unsigned Add Octal Byte Vectors"),
	TO_ENUM(MIPS_raddu_l_ob, "Unsigned Reduction Add Vector Octal Bytes"),
	TO_ENUM(MIPS_muleq_s_pw_qhl, "Multiply Vector Fractional Left Halfwords to Expanded Width Products"),
	TO_ENUM(MIPS_subu_s_ob, "Subtract Unsigned Octal Byte Vector"),
	TO_ENUM(MIPS_muleq_s_pw_qhr, "Multiply Vector Fractional Right Halfwords to Expanded Width Products"),
	TO_ENUM(MIPS_muleu_s_qh_obl, "Multiply Unsigned Vector Left Bytes by Halfwords to Halfword Products"),
	TO_ENUM(MIPS_addq_s_qh, "Add Fractional Halfword Vectors"),
	TO_ENUM(MIPS_addq_s_pw, "Add Fractional Word Vectors"),
	TO_ENUM(MIPS_muleu_s_qh_obr, "Multiply Unsigned Vector Right Bytes by Halfwords to Halfword Products"),
	TO_ENUM(MIPS_subq_s_qh, "Subtract Fractional Halfword Vector"),
	TO_ENUM(MIPS_subq_s_pw, "Subtract Fractional Word Vector"),
	TO_ENUM(MIPS_mulq_rs_qh, "Multiply Vector Fractional Halfwords to Fractional Halfword Products"),
	TO_ENUM(MIPS_cmpu_eq_qb, "Compare Vectors of Unsigned Byte Values"),
	TO_ENUM(MIPS_cmp_eq_ph, "Compare Vectors of Signed Integer Halfword Values"),
	TO_ENUM(MIPS_cmpgdu_eq_qb, "Compare Unsigned Vector of Four Bytes and Write Result to GPR and DSPControl"),
	TO_ENUM(MIPS_cmpu_lt_qb, "Compare Vectors of Unsigned Byte Values"),
	TO_ENUM(MIPS_cmp_lt_ph, "Compare Vectors of Signed Integer Halfword Values"),
	TO_ENUM(MIPS_cmpgdu_lt_qb, "Compare Unsigned Vector of Four Bytes and Write Result to GPR and DSPControl"),
	TO_ENUM(MIPS_cmpu_le_qb, "Compare Vectors of Unsigned Byte Values"),
	TO_ENUM(MIPS_cmp_le_ph, "Compare Vectors of Signed Integer Halfword Values"),
	TO_ENUM(MIPS_cmpgdu_le_qb, "Compare Unsigned Vector of Four Bytes and Write Result to GPR and DSPControl"),
	TO_ENUM(MIPS_pick_qb, "Pick a Vector of Byte Values Based on Condition Code Bits"),
	TO_ENUM(MIPS_pick_ph, "Pick a Vector of Halfword Values Based on Condition Code Bits"),
	TO_ENUM(MIPS_cmpgu_eq_qb, "Compare Vectors of Unsigned Byte Values and Write Results to a GPR"),
	TO_ENUM(MIPS_precrq_qb_ph, "Precision Reduce Four Fractional Halfwords to Four Bytes"),
	TO_ENUM(MIPS_precrq_ph_w, "Precision Reduce Fractional Words to Fractional Halfwords"),
	TO_ENUM(MIPS_cmpgu_lt_qb, "Compare Vectors of Unsigned Byte Values and Write Results to a GPR"),
	TO_ENUM(MIPS_precr_qb_ph, "Precision Reduce Four Integer Halfwords to Four Bytes"),
	TO_ENUM(MIPS_precrq_rs_ph_w, "Precision Reduce Fractional Words to Halfwords With Rounding and Saturation"),
	TO_ENUM(MIPS_cmpgu_le_qb, "Compare Vectors of Unsigned Byte Values and Write Results to a GPR"),
	TO_ENUM(MIPS_packrl_ph, "Pack a Vector of Halfwords from Vector Halfword Sources"),
	TO_ENUM(MIPS_precr_sra_ph_w, "Precision Reduce Two Integer Words to Halfwords after a Right Shift"),
	TO_ENUM(MIPS_precrqu_s_qb_ph, "Precision Reduce Fractional Halfwords to Unsigned Bytes With Saturation"),
	TO_ENUM(MIPS_precr_sra_r_ph_w, "Precision Reduce Two Integer Words to Halfwords after a Right Shift"),
	TO_ENUM(MIPS_cmpu_eq_ob, "Compare Vectors of Unsigned Byte Values"),
	TO_ENUM(MIPS_cmp_eq_qh, "Compare Vectors of Signed Integer Halfword Values"),
	TO_ENUM(MIPS_cmp_eq_pw, "Compare Vectors of Signed Integer Word Values"),
	TO_ENUM(MIPS_cmpu_lt_ob, "Compare Vectors of Unsigned Byte Values"),
	TO_ENUM(MIPS_cmp_lt_qh, "Compare Vectors of Signed Integer Halfword Values"),
	TO_ENUM(MIPS_cmp_lt_pw, "Compare Vectors of Signed Integer Word Values"),
	TO_ENUM(MIPS_cmpu_le_ob, "Compare Vectors of Unsigned Byte Values"),
	TO_ENUM(MIPS_cmp_le_qh, "Compare Vectors of Signed Integer Halfword Values"),
	TO_ENUM(MIPS_cmp_le_pw, "Compare Vectors of Signed Integer Word Values"),
	TO_ENUM(MIPS_pick_ob, "Pick a Vector of Byte Values Based on Condition Code Bits"),
	TO_ENUM(MIPS_pick_qh, "Pick a Vector of Halfword Values Based on Condition Code Bits"),
	TO_ENUM(MIPS_pick_pw, "Pick a Vector of Word Values Based on Condition Code Bits"),
	TO_ENUM(MIPS_cmpgu_eq_ob, "Compare Vectors of Unsigned Byte Values and Write Results to a GPR"),
	TO_ENUM(MIPS_precrq_ob_qh, "Precision Reduce Fractional Halfwords to Fractional Bytes"),
	TO_ENUM(MIPS_precrq_qh_pw, "Precision Reduce Fractional Words to Fractional Halfwords"),
	TO_ENUM(MIPS_precrq_pw_l, "Precision Reduce Fractional Doublewords to Fractional Words"),
	TO_ENUM(MIPS_cmpgu_lt_ob, "Compare Vectors of Unsigned Byte Values and Write Results to a GPR"),
	TO_ENUM(MIPS_precrq_rs_qh_pw, "Precision Reduce Fractional Words to Halfwords With Rounding and Saturation"),
	TO_ENUM(MIPS_cmpgu_le_ob, "Compare Vectors of Unsigned Byte Values and Write Results to a GPR"),
	TO_ENUM(MIPS_packrl_pw, "Pack a Vector of Words from Vector Word Sources"),
	TO_ENUM(MIPS_precrqu_s_ob_qh, "Precision Reduce Fractional Halfwords to Unsigned Bytes With Saturation"),
	TO_ENUM(MIPS_absq_s_qb, "Find Absolute Value of Four Fractional Byte Values"),
	TO_ENUM(MIPS_absq_s_ph, "Find Absolute Value of Two Fractional Halfwords"),
	TO_ENUM(MIPS_absq_s_w, "Find Absolute Value of Fractional Word"),
	TO_ENUM(MIPS_repl_qb, "Replicate Immediate Integer into all Vector Element Positions"),
	TO_ENUM(MIPS_repl_ph, "Replicate Immediate Integer into all Vector Element Positions"),
	TO_ENUM(MIPS_replv_qb, "Replicate Byte into all Vector Element Positions"),
	TO_ENUM(MIPS_replv_ph, "Replicate a Halfword into all Vector Element Positions"),
	TO_ENUM(MIPS_bitrev, "Bit-Reverse Halfword"),
	TO_ENUM(MIPS_precequ_ph_qbl, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceq_w_phl, "Precision Expand Fractional Halfword to Fractional Word Value"),
	TO_ENUM(MIPS_preceu_ph_qbl, "Precision Expand Two Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_precequ_ph_qbr, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceq_w_phr, "Precision Expand Fractional Halfword to Fractional Word Value"),
	TO_ENUM(MIPS_preceu_ph_qbr, "Precision Expand two Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_precequ_ph_qbla, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceu_ph_qbla, "Precision Expand Two Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_precequ_ph_qbra, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceu_ph_qbra, "Precision Expand Two Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_absq_s_qh, "Find Absolute Value of Four Fractional Halfwords"),
	TO_ENUM(MIPS_absq_s_pw, "Find Absolute Value of Two Fractional Words"),
	TO_ENUM(MIPS_repl_ob, "Replicate Immediate Integer into all Vector Element Positions"),
	TO_ENUM(MIPS_repl_qh, "Replicate Immediate Integer into all Vector Element Positions"),
	TO_ENUM(MIPS_repl_pw, "Replicate Immediate Integer into all Vector Element Positions"),
	TO_ENUM(MIPS_replv_ob, "Replicate Byte into all Vector Element Positions"),
	TO_ENUM(MIPS_replv_qh, "Replicate a Halfword into all Vector Element Positions"),
	TO_ENUM(MIPS_replv_pw, "Replicate Word into all Vector Element Positions"),
	TO_ENUM(MIPS_precequ_pw_qhl, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceq_pw_qhl, "Precision Expand Two Fractional Halfwords to Fractional Word Values"),
	TO_ENUM(MIPS_preceq_s_l_pwl, "Precision Expand Fractional Word to Fractional Doubleword Value"),
	TO_ENUM(MIPS_preceu_qh_obl, "Precision Expand Four Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_precequ_pw_qhr, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceq_pw_qhr, "Precision Expand Two Fractional Halfwords to Fractional Word Values"),
	TO_ENUM(MIPS_preceq_s_l_pwr, "Precision Expand Fractional Word to Fractional Doubleword Value"),
	TO_ENUM(MIPS_preceu_qh_obr, "Precision Expand Four Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_precequ_pw_qhla, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceq_pw_qhla, "Precision Expand Two Fractional Halfwords to Fractional Word Values"),
	TO_ENUM(MIPS_preceu_qh_obla, "Precision Expand Four Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_precequ_pw_qhra, "Precision Expand two Unsigned Bytes to Fractional Halfword Values"),
	TO_ENUM(MIPS_preceq_pw_qhra, "Precision Expand Two Fractional Halfwords to Fractional Word Values"),
	TO_ENUM(MIPS_preceu_qh_obra, "Precision Expand Four Unsigned Bytes to Unsigned Halfword Values"),
	TO_ENUM(MIPS_shll_qb, "Shift Left Logical Vector Quad Bytes"),
	TO_ENUM(MIPS_shll_ph, "Shift Left Logical Vector Pair Halfwords"),
	TO_ENUM(MIPS_shrl_qb, "Shift Right Logical Vector Quad Bytes"),
	TO_ENUM(MIPS_shra_ph, "Shift Right Arithmetic Vector Pair Halfwords"),
	TO_ENUM(MIPS_shrl_ph, "Shift Right Logical Two Halfwords"),
	TO_ENUM(MIPS_shllv_qb, "Shift Left Logical Variable Vector Quad Bytes"),
	TO_ENUM(MIPS_shllv_ph, "Shift Left Logical Variable Vector Pair Halfwords"),
	TO_ENUM(MIPS_shrlv_qb, "Shift Right Logical Variable Vector Quad Bytes"),
	TO_ENUM(MIPS_shrav_ph, "Shift Right Arithmetic Variable Vector Pair Halfwords"),
	TO_ENUM(MIPS_shrlv_ph, "Shift Variable Right Logical Pair of Halfwords"),
	TO_ENUM(MIPS_shra_qb, "Shift Right Arithmetic Vector of Four Bytes"),
	TO_ENUM(MIPS_shll_s_ph, "Shift Left Logical Vector Pair Halfwords"),
	TO_ENUM(MIPS_shll_s_w, "Shift Left Logical Word with Saturation"),
	TO_ENUM(MIPS_shra_r_qb, "Shift Right Arithmetic Vector of Four Bytes"),
	TO_ENUM(MIPS_shra_r_ph, "Shift Right Arithmetic Vector Pair Halfwords"),
	TO_ENUM(MIPS_shra_r_w, "Shift Right Arithmetic Word with Rounding"),
	TO_ENUM(MIPS_shrav_qb, "Shift Right Arithmetic Variable Vector of Four Bytes"),
	TO_ENUM(MIPS_shllv_s_ph, "Shift Left Logical Variable Vector Pair Halfwords"),
	TO_ENUM(MIPS_shllv_s_w, "Shift Left Logical Variable Vector Word"),
	TO_ENUM(MIPS_shrav_r_qb, "Shift Right Arithmetic Variable Vector of Four Bytes"),
	TO_ENUM(MIPS_shrav_r_ph, "Shift Right Arithmetic Variable Vector Pair Halfwords"),
	TO_ENUM(MIPS_shrav_r_w, "Shift Right Arithmetic Variable Word with Rounding"),
	TO_ENUM(MIPS_shll_ob, "Shift Left Logical Vector Octal Bytes"),
	TO_ENUM(MIPS_shll_qh, "Shift Left Logical Vector Quad Halfwords"),
	TO_ENUM(MIPS_shll_pw, "Shift Left Logical Vector Pair Words"),
	TO_ENUM(MIPS_shrl_ob, "Shift Right Logical Vector Octal Bytes"),
	TO_ENUM(MIPS_shra_qh, "Shift Right Arithmetic Vector Quad Halfwords"),
	TO_ENUM(MIPS_shra_pw, "Shift Right Arithmetic Vector Pair Words"),
	TO_ENUM(MIPS_shllv_ob, "Shift Left Logical Variable Vector Octal Bytes"),
	TO_ENUM(MIPS_shllv_qh, "Shift Left Logical Variable Vector Quad Halfwords"),
	TO_ENUM(MIPS_shllv_pw, "Shift Left Logical Variable Vector Pair Words"),
	TO_ENUM(MIPS_shrlv_ob, "Shift Right Logical Variable Vector Octal Bytes"),
	TO_ENUM(MIPS_shrav_qh, "Shift Right Arithmetic Variable Vector Quad Halfwords"),
	TO_ENUM(MIPS_shrav_pw, "Shift Right Arithmetic Variable Vector Pair Words"),
	TO_ENUM(MIPS_shll_s_qh, "Shift Left Logical Vector Quad Halfwords"),
	TO_ENUM(MIPS_shll_s_pw, "Shift Left Logical Vector Pair Words"),
	TO_ENUM(MIPS_shra_r_qh, "Shift Right Arithmetic Vector Quad Halfwords"),
	TO_ENUM(MIPS_shra_r_pw, "Shift Right Arithmetic Vector Pair Words"),
	TO_ENUM(MIPS_shllv_s_qh, "Shift Left Logical Variable Vector Quad Halfwords"),
	TO_ENUM(MIPS_shllv_s_pw, "Shift Left Logical Variable Vector Pair Words"),
	TO_ENUM(MIPS_shrav_r_qh, "Shift Right Arithmetic Variable Vector Quad Halfwords"),
	TO_ENUM(MIPS_shrav_r_pw, "Shift Right Arithmetic Variable Vector Pair Words"),
	TO_ENUM(MIPS_lwx, "Load Word Indexed"),
	TO_ENUM(MIPS_ldx, "Load Doubleword Indexed"),
	TO_ENUM(MIPS_lhx, "Load Halfword Indexed"),
	TO_ENUM(MIPS_lbux, "Load Unsigned Byte Indexed"),
	TO_ENUM(MIPS_dpa_w_ph, "Dot Product with Accumulate on Vector Integer Halfword Elements"),
	TO_ENUM(MIPS_dpax_w_ph, "Cross Dot Product with Accumulate on Vector Integer Halfword Elements"),
	TO_ENUM(MIPS_maq_sa_w_phl, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dpaqx_s_w_ph, "Cross Dot Product with Accumulation on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dps_w_ph, "Dot Product with Subtract on Vector Integer Half-Word Elements"),
	TO_ENUM(MIPS_dpsx_w_ph, "Cross Dot Product with Subtract on Vector Integer Halfword Elements"),
	TO_ENUM(MIPS_dpsqx_s_w_ph, "Cross Dot Product with Subtraction on Fractional Halfword Elements"),
	TO_ENUM(MIPS_mulsa_w_ph, "Multiply and Subtract Vector Integer Halfword Elements and Accumulate"),
	TO_ENUM(MIPS_maq_sa_w_phr, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dpaqx_sa_w_ph, "Cross Dot Product with Accumulation on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dpau_h_qbl, "Dot Product with Accumulate on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_dpsu_h_qbl, "Dot Product with Subtraction on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_dpsqx_sa_w_ph, "Cross Dot Product with Subtraction on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dpaq_s_w_ph, "Dot Product with Accumulation on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dpaq_sa_l_w, "Dot Product with Accumulate on Fractional Word Element"),
	TO_ENUM(MIPS_maq_s_w_phl, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dpsq_s_w_ph, "Dot Product with Subtraction on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dpsq_sa_l_w, "Dot Product with Subtraction on Fractional Word Element"),
	TO_ENUM(MIPS_mulsaq_s_w_ph, "Multiply And Subtract Vector Fractional Halfwords And Accumulate"),
	TO_ENUM(MIPS_maq_s_w_phr, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dpau_h_qbr, "Dot Product with Accumulate on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_dpsu_h_qbr, "Dot Product with Subtraction on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_maq_sa_w_qhll, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_maq_sa_w_qhlr, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dmadd, "Multiply Vector Words And Accumulate"),
	TO_ENUM(MIPS_dmsub, "Multiply Vector Words And Subtract From Accumulator"),
	TO_ENUM(MIPS_maq_sa_w_qhrl, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dpau_h_obl, "Dot Product with Accumulate on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_dpsu_h_obl, "Dot Product with Subtract on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_maq_sa_w_qhrr, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dpaq_s_w_qh, "Dot Product with Accumulation on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dpaq_sa_l_pw, "Dot Product with Accumulate on Fractional Word Elements"),
	TO_ENUM(MIPS_maq_s_w_qhll, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_maq_s_l_pwl, "Multiply with Accumulate Single Vector Fractional Word Element"),
	TO_ENUM(MIPS_dpsq_s_w_qh, "Dot Product with Subtraction on Fractional Halfword Elements"),
	TO_ENUM(MIPS_dpsq_sa_l_pw, "Dot Product with Subtraction on Fractional Word Elements"),
	TO_ENUM(MIPS_maq_s_w_qhlr, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dmaddu, "Multiply Vector Unsigned Words And Accumulate"),
	TO_ENUM(MIPS_mulsaq_s_w_qh, "Multiply And Subtract Vector Fractional Halfwords And Accumulate"),
	TO_ENUM(MIPS_mulsaq_s_l_pw, "Multiply And Subtract Vector Fractional Words And Accumulate"),
	TO_ENUM(MIPS_maq_s_w_qhrl, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_maq_s_l_pwr, "Multiply with Accumulate Single Vector Fractional Word Element"),
	TO_ENUM(MIPS_dpau_h_obr, "Dot Product with Accumulate on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_dpsu_h_obr, "Dot Product with Subtract on Vector Unsigned Byte Elements"),
	TO_ENUM(MIPS_maq_s_w_qhrr, "Multiply with Accumulate Single Vector Fractional Halfword Element"),
	TO_ENUM(MIPS_dmsubu, "Multiply Vector Unsigned Words And Subtract From Accumulator"),
	TO_ENUM(MIPS_extr_w, "Extract Word Value With Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_extrv_w, "Extract Word Value With Variable Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_extp, "Extract Fixed Bitfield From Arbitrary Position in Accumulator to GPR"),
	TO_ENUM(MIPS_extpdp, "Extract Fixed Bitfield From Arbitrary Position in Accumulator to GPR and Decrement Pos"),
	TO_ENUM(MIPS_rddsp, "Read DSPControl Register Fields to a GPR"),
	TO_ENUM(MIPS_shilo, "Shift an Accumulator Value Leaving the Result in the Same Accumulator"),
	TO_ENUM(MIPS_extpv, "Extract Variable Bitfield From Arbitrary Position in Accumulator to GPR"),
	TO_ENUM(MIPS_extpdpv, "Extract Variable Bitfield From Arbitrary Position in Accumulator to GPR and Decrement Pos"),
	TO_ENUM(MIPS_wrdsp, "Write Fields to DSPControl Register from a GPR"),
	TO_ENUM(MIPS_shilov, "Variable Shift of Accumulator Value Leaving the Result in the Same Accumulator"),
	TO_ENUM(MIPS_extr_r_w, "Extract Word Value With Right Shift And Rounding From Accumulator to GPR"),
	TO_ENUM(MIPS_extrv_r_w, "Extract Word Value With Variable Right Shift And Rounding From Accumulator to GPR"),
	TO_ENUM(MIPS_extr_rs_w, "Extract Word Value With Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_extr_s_h, "Extract Halfword Value From Accumulator to GPR With Right Shift and Saturate"),
	TO_ENUM(MIPS_extrv_rs_w, "Extract Word Value With Variable Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_extrv_s_h, "Extract Halfword Value Variable From Accumulator to GPR With Right Shift and Saturate"),
	TO_ENUM(MIPS_mthlip, "Copy LO to HI and a GPR to LO and Increment Pos by 32"),
	TO_ENUM(MIPS_dextr_w, "Extract Word Value With Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextr_l, "Extract Doubleword Value With Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextrv_w, "Extract Word Value With Variable Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextrv_l, "Extract Doubleword Value With Variable Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextp, "Extract Fixed Bitfield From Arbitrary Position in Accumulator to GPR"),
	TO_ENUM(MIPS_dextpdp, "Extract Fixed Bitfield From Arbitrary Position in Accumulator to GPR and Decrement Pos"),
	TO_ENUM(MIPS_dshilo, "Shift an Accumulator Value Leaving the Result in the Same Accumulator"),
	TO_ENUM(MIPS_dextpv, "Extract Variable Bitfield From Arbitrary Position in Accumulator to GPR"),
	TO_ENUM(MIPS_dextpdpv, "Extract Variable Bitfield From Arbitrary Position in Accumulator to GPR and Decrement Pos"),
	TO_ENUM(MIPS_dshilov, "Variable Shift of Accumulator Value Leaving the Result in the Same Accumulator"),
	TO_ENUM(MIPS_dextr_r_w, "Extract Word Value With Right Shift And Rounding From Accumulator to GPR"),
	TO_ENUM(MIPS_dextr_r_l, "Extract Doubleword Value With Right Shift And Rounding From Accumulator to GPR"),
	TO_ENUM(MIPS_dextrv_r_w, "Extract Word Value With Variable Right Shift And Rounding From Accumulator to GPR"),
	TO_ENUM(MIPS_dextrv_r_l, "Extract Doubleword Value With Variable Right Shift And Rounding From Accumulator to GPR"),
	TO_ENUM(MIPS_dextr_rs_w, "Extract Word Value With Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextr_s_h, "Extract Halfword Value From Accumulator to GPR With Right Shift and Saturate"),
	TO_ENUM(MIPS_dextr_rs_l, "Extract Doubleword Value With Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextrv_rs_w, "Extract Word Value With Variable Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dextrv_s_h, "Extract Halfword Value Variable From Accumulator to GPR With Right Shift and Saturate"),
	TO_ENUM(MIPS_dextrv_rs_l, "Extract Doubleword Value With Variable Right Shift From Accumulator to GPR"),
	TO_ENUM(MIPS_dmthlip, "Copy LO to HI and a GPR to LO and Increment Pos by 64"),
	TO_ENUM(MIPS_adduh_qb, "Unsigned Add Vector Quad-Bytes And Right Shift to Halve Results"),
	TO_ENUM(MIPS_addqh_ph, "Add Fractional Halfword Vectors And Shift Right to Halve Results"),
	TO_ENUM(MIPS_addqh_w, "Add Fractional Words And Shift Right to Halve Results"),
	TO_ENUM(MIPS_subuh_qb, "Subtract Unsigned Bytes And Right Shift to Halve Results"),
	TO_ENUM(MIPS_subqh_ph, "Subtract Fractional Halfword Vectors And Shift Right to Halve Results"),
	TO_ENUM(MIPS_subqh_w, "Subtract Fractional Words And Shift Right to Halve Results"),
	TO_ENUM(MIPS_adduh_r_qb, "Unsigned Add Vector Quad-Bytes And Right Shift to Halve Results"),
	TO_ENUM(MIPS_addqh_r_ph, "Add Fractional Halfword Vectors And Shift Right to Halve Results"),
	TO_ENUM(MIPS_addqh_r_w, "Add Fractional Words And Shift Right to Halve Results"),
	TO_ENUM(MIPS_subuh_r_qb, "Subtract Unsigned Bytes And Right Shift to Halve Results"),
	TO_ENUM(MIPS_subqh_r_ph, "Subtract Fractional Halfword Vectors And Shift Right to Halve Results"),
	TO_ENUM(MIPS_subqh_r_w, "Subtract Fractional Words And Shift Right to Halve Results"),
	TO_ENUM(MIPS_mul_ph, "Multiply Vector Integer HalfWords to Same Size Products"),
	TO_ENUM(MIPS_mul_s_ph, "Multiply Vector Integer HalfWords to Same Size Products"),
	TO_ENUM(MIPS_mulq_s_w, "Multiply Fractional Words to Same Size Product with Saturation"),
	TO_ENUM(MIPS_mulq_rs_w, "Multiply Fractional Words to Same Size Product with Saturation and Rounding"),
	TO_ENUM(MIPS_append, "Left Shift and Append Bits to the LSB"),
	TO_ENUM(MIPS_balign, "Byte Align Contents from Two Registers"),
	TO_ENUM(MIPS_prepend, "Right Shift and Prepend Bits to the MSB"),
	TO_ENUM(MIPS_laa, "Load Atomic Add Word"),
	TO_ENUM(MIPS_laad, "Load Atomic Add Doubleword"),
	TO_ENUM(MIPS_lac, "Load Atomic Clear Word"),
	TO_ENUM(MIPS_lacd, "Load Atomic Clear Doubleword"),
	TO_ENUM(MIPS_lad, "Load Atomic Decrement Word"),
	TO_ENUM(MIPS_ladd, "Load Atomic Decrement Doubleword"),
	TO_ENUM(MIPS_lai, "Load Atomic Increment Word"),
	TO_ENUM(MIPS_laid, "Load Atomic Increment Doubleword"),
	TO_ENUM(MIPS_las, "Load Atomic Set Word"),
	TO_ENUM(MIPS_lasd, "Load Atomic Set Doubleword"),
	TO_ENUM(MIPS_law, "Load Atomic Swap Word"),
	TO_ENUM(MIPS_lawd, "Load Atomic Swap Doubleword"),
	TO_ENUM(MIPS_lbx, "Load Byte Indexed"),
	TO_ENUM(MIPS_lhux, "Load Halfword Unsigned Indexed"),
	TO_ENUM(MIPS_lwux, "Load Word Unsigned Indexed"),
	TO_ENUM(MIPS_qmac_00, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmac_01, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmac_02, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmac_03, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmacs_00, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmacs_01, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmacs_02, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_qmacs_03, "Q15 Multiply Accumulate"),
	TO_ENUM(MIPS_zcb, "Zero Cache Block"),
	TO_ENUM(MIPS_zcbt, "Zero Cache Block"),
	TO_ENUM(MIPS_msa_sll_b, "Vector Shift Left"),
	TO_ENUM(MIPS_msa_sll_h, "Vector Shift Left"),
	TO_ENUM(MIPS_msa_sll_w, "Vector Shift Left"),
	TO_ENUM(MIPS_msa_sll_d, "Vector Shift Left"),
	TO_ENUM(MIPS_msa_slli_b, "Immediate Shift Left"),
	TO_ENUM(MIPS_msa_slli_h, "Immediate Shift Left"),
	TO_ENUM(MIPS_msa_slli_w, "Immediate Shift Left"),
	TO_ENUM(MIPS_msa_slli_d, "Immediate Shift Left"),
	TO_ENUM(MIPS_msa_sra_b, "Vector Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_sra_h, "Vector Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_sra_w, "Vector Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_sra_d, "Vector Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_srai_b, "Immediate Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_srai_h, "Immediate Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_srai_w, "Immediate Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_srai_d, "Immediate Shift Right Arithmetic"),
	TO_ENUM(MIPS_msa_srl_b, "Vector Shift Right Logical"),
	TO_ENUM(MIPS_msa_srl_h, "Vector Shift Right Logical"),
	TO_ENUM(MIPS_msa_srl_w, "Vector Shift Right Logical"),
	TO_ENUM(MIPS_msa_srl_d, "Vector Shift Right Logical"),
	TO_ENUM(MIPS_msa_srli_b, "Immediate Shift Right Logical"),
	TO_ENUM(MIPS_msa_srli_h, "Immediate Shift Right Logical"),
	TO_ENUM(MIPS_msa_srli_w, "Immediate Shift Right Logical"),
	TO_ENUM(MIPS_msa_srli_d, "Immediate Shift Right Logical"),
	TO_ENUM(MIPS_msa_bclr_b, "Vector Bit Clear"),
	TO_ENUM(MIPS_msa_bclr_h, "Vector Bit Clear"),
	TO_ENUM(MIPS_msa_bclr_w, "Vector Bit Clear"),
	TO_ENUM(MIPS_msa_bclr_d, "Vector Bit Clear"),
	TO_ENUM(MIPS_msa_bclri_b, "Immediate Bit Clear"),
	TO_ENUM(MIPS_msa_bclri_h, "Immediate Bit Clear"),
	TO_ENUM(MIPS_msa_bclri_w, "Immediate Bit Clear"),
	TO_ENUM(MIPS_msa_bclri_d, "Immediate Bit Clear"),
	TO_ENUM(MIPS_msa_bset_b, "Vector Bit Set"),
	TO_ENUM(MIPS_msa_bset_h, "Vector Bit Set"),
	TO_ENUM(MIPS_msa_bset_w, "Vector Bit Set"),
	TO_ENUM(MIPS_msa_bset_d, "Vector Bit Set"),
	TO_ENUM(MIPS_msa_bseti_b, "Immediate Bit Set"),
	TO_ENUM(MIPS_msa_bseti_h, "Immediate Bit Set"),
	TO_ENUM(MIPS_msa_bseti_w, "Immediate Bit Set"),
	TO_ENUM(MIPS_msa_bseti_d, "Immediate Bit Set"),
	TO_ENUM(MIPS_msa_bneg_b, "Vector Bit Negate"),
	TO_ENUM(MIPS_msa_bneg_h, "Vector Bit Negate"),
	TO_ENUM(MIPS_msa_bneg_w, "Vector Bit Negate"),
	TO_ENUM(MIPS_msa_bneg_d, "Vector Bit Negate"),
	TO_ENUM(MIPS_msa_bnegi_b, "Immediate Bit Negate"),
	TO_ENUM(MIPS_msa_bnegi_h, "Immediate Bit Negate"),
	TO_ENUM(MIPS_msa_bnegi_w, "Immediate Bit Negate"),
	TO_ENUM(MIPS_msa_bnegi_d, "Immediate Bit Negate"),
	TO_ENUM(MIPS_msa_binsl_b, "Vector Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsl_h, "Vector Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsl_w, "Vector Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsl_d, "Vector Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsli_b, "Immediate Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsli_h, "Immediate Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsli_w, "Immediate Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsli_d, "Immediate Bit Insert Left"),
	TO_ENUM(MIPS_msa_binsr_b, "Vector Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsr_h, "Vector Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsr_w, "Vector Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsr_d, "Vector Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsri_b, "Immediate Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsri_h, "Immediate Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsri_w, "Immediate Bit Insert Right"),
	TO_ENUM(MIPS_msa_binsri_d, "Immediate Bit Insert Right"),
	TO_ENUM(MIPS_msa_addv_b, "Vector Add"),
	TO_ENUM(MIPS_msa_addv_h, "Vector Add"),
	TO_ENUM(MIPS_msa_addv_w, "Vector Add"),
	TO_ENUM(MIPS_msa_addv_d, "Vector Add"),
	TO_ENUM(MIPS_msa_addvi_b, "Immediate Add"),
	TO_ENUM(MIPS_msa_addvi_h, "Immediate Add"),
	TO_ENUM(MIPS_msa_addvi_w, "Immediate Add"),
	TO_ENUM(MIPS_msa_addvi_d, "Immediate Add"),
	TO_ENUM(MIPS_msa_subv_b, "Vector Subtract"),
	TO_ENUM(MIPS_msa_subv_h, "Vector Subtract"),
	TO_ENUM(MIPS_msa_subv_w, "Vector Subtract"),
	TO_ENUM(MIPS_msa_subv_d, "Vector Subtract"),
	TO_ENUM(MIPS_msa_subvi_b, "Immediate Subtract"),
	TO_ENUM(MIPS_msa_subvi_h, "Immediate Subtract"),
	TO_ENUM(MIPS_msa_subvi_w, "Immediate Subtract"),
	TO_ENUM(MIPS_msa_subvi_d, "Immediate Subtract"),
	TO_ENUM(MIPS_msa_max_s_b, "Vector Signed Maximum"),
	TO_ENUM(MIPS_msa_max_s_h, "Vector Signed Maximum"),
	TO_ENUM(MIPS_msa_max_s_w, "Vector Signed Maximum"),
	TO_ENUM(MIPS_msa_max_s_d, "Vector Signed Maximum"),
	TO_ENUM(MIPS_msa_maxi_s_b, "Immediate Signed Maximum"),
	TO_ENUM(MIPS_msa_maxi_s_h, "Immediate Signed Maximum"),
	TO_ENUM(MIPS_msa_maxi_s_w, "Immediate Signed Maximum"),
	TO_ENUM(MIPS_msa_maxi_s_d, "Immediate Signed Maximum"),
	TO_ENUM(MIPS_msa_max_u_b, "Vector Unsigned Maximum"),
	TO_ENUM(MIPS_msa_max_u_h, "Vector Unsigned Maximum"),
	TO_ENUM(MIPS_msa_max_u_w, "Vector Unsigned Maximum"),
	TO_ENUM(MIPS_msa_max_u_d, "Vector Unsigned Maximum"),
	TO_ENUM(MIPS_msa_maxi_u_b, "Immediate Unsigned Maximum"),
	TO_ENUM(MIPS_msa_maxi_u_h, "Immediate Unsigned Maximum"),
	TO_ENUM(MIPS_msa_maxi_u_w, "Immediate Unsigned Maximum"),
	TO_ENUM(MIPS_msa_maxi_u_d, "Immediate Unsigned Maximum"),
	TO_ENUM(MIPS_msa_min_s_b, "Vector Signed Minimum"),
	TO_ENUM(MIPS_msa_min_s_h, "Vector Signed Minimum"),
	TO_ENUM(MIPS_msa_min_s_w, "Vector Signed Minimum"),
	TO_ENUM(MIPS_msa_min_s_d, "Vector Signed Minimum"),
	TO_ENUM(MIPS_msa_mini_s_b, "Immediate Signed Minimum"),
	TO_ENUM(MIPS_msa_mini_s_h, "Immediate Signed Minimum"),
	TO_ENUM(MIPS_msa_mini_s_w, "Immediate Signed Minimum"),
	TO_ENUM(MIPS_msa_mini_s_d, "Immediate Signed Minimum"),
	TO_ENUM(MIPS_msa_min_u_b, "Vector Unsigned Minimum"),
	TO_ENUM(MIPS_msa_min_u_h, "Vector Unsigned Minimum"),
	TO_ENUM(MIPS_msa_min_u_w, "Vector Unsigned Minimum"),
	TO_ENUM(MIPS_msa_min_u_d, "Vector Unsigned Minimum"),
	TO_ENUM(MIPS_msa_mini_u_b, "Immediate Unsigned Minimum"),
	TO_ENUM(MIPS_msa_mini_u_h, "Immediate Unsigned Minimum"),
	TO_ENUM(MIPS_msa_mini_u_w, "Immediate Unsigned Minimum"),
	TO_ENUM(MIPS_msa_mini_u_d, "Immediate Unsigned Minimum"),
	TO_ENUM(MIPS_msa_max_a_b, "Vector Maximum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_max_a_h, "Vector Maximum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_max_a_w, "Vector Maximum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_max_a_d, "Vector Maximum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_min_a_b, "Vector Minimum Based on Absolute Value"),
	TO_ENUM(MIPS_msa_min_a_h, "Vector Minimum Based on Absolute Value"),
	TO_ENUM(MIPS_msa_min_a_w, "Vector Minimum Based on Absolute Value"),
	TO_ENUM(MIPS_msa_min_a_d, "Vector Minimum Based on Absolute Value"),
	TO_ENUM(MIPS_msa_ceq_b, "Vector Compare Equal"),
	TO_ENUM(MIPS_msa_ceq_h, "Vector Compare Equal"),
	TO_ENUM(MIPS_msa_ceq_w, "Vector Compare Equal"),
	TO_ENUM(MIPS_msa_ceq_d, "Vector Compare Equal"),
	TO_ENUM(MIPS_msa_ceqi_b, "Immediate Compare Equal"),
	TO_ENUM(MIPS_msa_ceqi_h, "Immediate Compare Equal"),
	TO_ENUM(MIPS_msa_ceqi_w, "Immediate Compare Equal"),
	TO_ENUM(MIPS_msa_ceqi_d, "Immediate Compare Equal"),
	TO_ENUM(MIPS_msa_clt_s_b, "Vector Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clt_s_h, "Vector Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clt_s_w, "Vector Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clt_s_d, "Vector Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clti_s_b, "Immediate Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clti_s_h, "Immediate Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clti_s_w, "Immediate Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clti_s_d, "Immediate Compare Signed Less Than"),
	TO_ENUM(MIPS_msa_clt_u_b, "Vector Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clt_u_h, "Vector Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clt_u_w, "Vector Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clt_u_d, "Vector Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clti_u_b, "Immediate Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clti_u_h, "Immediate Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clti_u_w, "Immediate Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_clti_u_d, "Immediate Compare Unsigned Less Than"),
	TO_ENUM(MIPS_msa_cle_s_b, "Vector Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_s_h, "Vector Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_s_w, "Vector Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_s_d, "Vector Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_s_b, "Immediate Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_s_h, "Immediate Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_s_w, "Immediate Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_s_d, "Immediate Compare Signed Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_u_b, "Vector Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_u_h, "Vector Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_u_w, "Vector Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_cle_u_d, "Vector Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_u_b, "Immediate Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_u_h, "Immediate Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_u_w, "Immediate Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_clei_u_d, "Immediate Compare Unsigned Less Than or Equal"),
	TO_ENUM(MIPS_msa_ld_b, "Vector Load"),
	TO_ENUM(MIPS_msa_ld_h, "Vector Load"),
	TO_ENUM(MIPS_msa_ld_w, "Vector Load"),
	TO_ENUM(MIPS_msa_ld_d, "Vector Load"),
	TO_ENUM(MIPS_msa_st_b, "Vector Store"),
	TO_ENUM(MIPS_msa_st_h, "Vector Store"),
	TO_ENUM(MIPS_msa_st_w, "Vector Store"),
	TO_ENUM(MIPS_msa_st_d, "Vector Store"),
	TO_ENUM(MIPS_msa_sat_s_b, "Immediate Signed Saturate"),
	TO_ENUM(MIPS_msa_sat_s_h, "Immediate Signed Saturate"),
	TO_ENUM(MIPS_msa_sat_s_w, "Immediate Signed Saturate"),
	TO_ENUM(MIPS_msa_sat_s_d, "Immediate Signed Saturate"),
	TO_ENUM(MIPS_msa_sat_u_b, "Immediate Unsigned Saturate"),
	TO_ENUM(MIPS_msa_sat_u_h, "Immediate Unsigned Saturate"),
	TO_ENUM(MIPS_msa_sat_u_w, "Immediate Unsigned Saturate"),
	TO_ENUM(MIPS_msa_sat_u_d, "Immediate Unsigned Saturate"),
	TO_ENUM(MIPS_msa_add_a_b, "Vector Add Absolute Values"),
	TO_ENUM(MIPS_msa_add_a_h, "Vector Add Absolute Values"),
	TO_ENUM(MIPS_msa_add_a_w, "Vector Add Absolute Values"),
	TO_ENUM(MIPS_msa_add_a_d, "Vector Add Absolute Values"),
	TO_ENUM(MIPS_msa_adds_a_b, "Vector Saturated Add of Absolute Values"),
	TO_ENUM(MIPS_msa_adds_a_h, "Vector Saturated Add of Absolute Values"),
	TO_ENUM(MIPS_msa_adds_a_w, "Vector Saturated Add of Absolute Values"),
	TO_ENUM(MIPS_msa_adds_a_d, "Vector Saturated Add of Absolute Values"),
	TO_ENUM(MIPS_msa_adds_s_b, "Vector Signed Saturated Add of Signed Values"),
	TO_ENUM(MIPS_msa_adds_s_h, "Vector Signed Saturated Add of Signed Values"),
	TO_ENUM(MIPS_msa_adds_s_w, "Vector Signed Saturated Add of Signed Values"),
	TO_ENUM(MIPS_msa_adds_s_d, "Vector Signed Saturated Add of Signed Values"),
	TO_ENUM(MIPS_msa_adds_u_b, "Vector Unsigned Saturated Add of Unsigned Values"),
	TO_ENUM(MIPS_msa_adds_u_h, "Vector Unsigned Saturated Add of Unsigned Values"),
	TO_ENUM(MIPS_msa_adds_u_w, "Vector Unsigned Saturated Add of Unsigned Values"),
	TO_ENUM(MIPS_msa_adds_u_d, "Vector Unsigned Saturated Add of Unsigned Values"),
	TO_ENUM(MIPS_msa_ave_s_b, "Vector Signed Average"),
	TO_ENUM(MIPS_msa_ave_s_h, "Vector Signed Average"),
	TO_ENUM(MIPS_msa_ave_s_w, "Vector Signed Average"),
	TO_ENUM(MIPS_msa_ave_s_d, "Vector Signed Average"),
	TO_ENUM(MIPS_msa_ave_u_b, "Vector Unsigned Average"),
	TO_ENUM(MIPS_msa_ave_u_h, "Vector Unsigned Average"),
	TO_ENUM(MIPS_msa_ave_u_w, "Vector Unsigned Average"),
	TO_ENUM(MIPS_msa_ave_u_d, "Vector Unsigned Average"),
	TO_ENUM(MIPS_msa_aver_s_b, "Vector Signed Average Rounded"),
	TO_ENUM(MIPS_msa_aver_s_h, "Vector Signed Average Rounded"),
	TO_ENUM(MIPS_msa_aver_s_w, "Vector Signed Average Rounded"),
	TO_ENUM(MIPS_msa_aver_s_d, "Vector Signed Average Rounded"),
	TO_ENUM(MIPS_msa_aver_u_b, "Vector Unsigned Average Rounded"),
	TO_ENUM(MIPS_msa_aver_u_h, "Vector Unsigned Average Rounded"),
	TO_ENUM(MIPS_msa_aver_u_w, "Vector Unsigned Average Rounded"),
	TO_ENUM(MIPS_msa_aver_u_d, "Vector Unsigned Average Rounded"),
	TO_ENUM(MIPS_msa_subs_s_b, "Vector Signed Saturated Subtract of Signed Values"),
	TO_ENUM(MIPS_msa_subs_s_h, "Vector Signed Saturated Subtract of Signed Values"),
	TO_ENUM(MIPS_msa_subs_s_w, "Vector Signed Saturated Subtract of Signed Values"),
	TO_ENUM(MIPS_msa_subs_s_d, "Vector Signed Saturated Subtract of Signed Values"),
	TO_ENUM(MIPS_msa_subs_u_b, "Vector Unsigned Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subs_u_h, "Vector Unsigned Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subs_u_w, "Vector Unsigned Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subs_u_d, "Vector Unsigned Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subsus_u_b, "Vector Unsigned Saturated Subtract of Signed from Unsigned"),
	TO_ENUM(MIPS_msa_subsus_u_h, "Vector Unsigned Saturated Subtract of Signed from Unsigned"),
	TO_ENUM(MIPS_msa_subsus_u_w, "Vector Unsigned Saturated Subtract of Signed from Unsigned"),
	TO_ENUM(MIPS_msa_subsus_u_d, "Vector Unsigned Saturated Subtract of Signed from Unsigned"),
	TO_ENUM(MIPS_msa_subsuu_s_b, "Vector Signed Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subsuu_s_h, "Vector Signed Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subsuu_s_w, "Vector Signed Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_subsuu_s_d, "Vector Signed Saturated Subtract of Unsigned Values"),
	TO_ENUM(MIPS_msa_asub_s_b, "Vector Absolute Values of Signed Subtract"),
	TO_ENUM(MIPS_msa_asub_s_h, "Vector Absolute Values of Signed Subtract"),
	TO_ENUM(MIPS_msa_asub_s_w, "Vector Absolute Values of Signed Subtract"),
	TO_ENUM(MIPS_msa_asub_s_d, "Vector Absolute Values of Signed Subtract"),
	TO_ENUM(MIPS_msa_asub_u_b, "Vector Absolute Values of Unsigned Subtract"),
	TO_ENUM(MIPS_msa_asub_u_h, "Vector Absolute Values of Unsigned Subtract"),
	TO_ENUM(MIPS_msa_asub_u_w, "Vector Absolute Values of Unsigned Subtract"),
	TO_ENUM(MIPS_msa_asub_u_d, "Vector Absolute Values of Unsigned Subtract"),
	TO_ENUM(MIPS_msa_mulv_b, "Vector Multiply"),
	TO_ENUM(MIPS_msa_mulv_h, "Vector Multiply"),
	TO_ENUM(MIPS_msa_mulv_w, "Vector Multiply"),
	TO_ENUM(MIPS_msa_mulv_d, "Vector Multiply"),
	TO_ENUM(MIPS_msa_maddv_b, "Vector Multiply and Add"),
	TO_ENUM(MIPS_msa_maddv_h, "Vector Multiply and Add"),
	TO_ENUM(MIPS_msa_maddv_w, "Vector Multiply and Add"),
	TO_ENUM(MIPS_msa_maddv_d, "Vector Multiply and Add"),
	TO_ENUM(MIPS_msa_msubv_b, "Vector Multiply and Subtract"),
	TO_ENUM(MIPS_msa_msubv_h, "Vector Multiply and Subtract"),
	TO_ENUM(MIPS_msa_msubv_w, "Vector Multiply and Subtract"),
	TO_ENUM(MIPS_msa_msubv_d, "Vector Multiply and Subtract"),
	TO_ENUM(MIPS_msa_div_s_b, "Vector Signed Divide"),
	TO_ENUM(MIPS_msa_div_s_h, "Vector Signed Divide"),
	TO_ENUM(MIPS_msa_div_s_w, "Vector Signed Divide"),
	TO_ENUM(MIPS_msa_div_s_d, "Vector Signed Divide"),
	TO_ENUM(MIPS_msa_div_u_b, "Vector Unsigned Divide"),
	TO_ENUM(MIPS_msa_div_u_h, "Vector Unsigned Divide"),
	TO_ENUM(MIPS_msa_div_u_w, "Vector Unsigned Divide"),
	TO_ENUM(MIPS_msa_div_u_d, "Vector Unsigned Divide"),
	TO_ENUM(MIPS_msa_mod_s_b, "Vector Signed Modulo"),
	TO_ENUM(MIPS_msa_mod_s_h, "Vector Signed Modulo"),
	TO_ENUM(MIPS_msa_mod_s_w, "Vector Signed Modulo"),
	TO_ENUM(MIPS_msa_mod_s_d, "Vector Signed Modulo"),
	TO_ENUM(MIPS_msa_mod_u_b, "Vector Unsigned Modulo"),
	TO_ENUM(MIPS_msa_mod_u_h, "Vector Unsigned Modulo"),
	TO_ENUM(MIPS_msa_mod_u_w, "Vector Unsigned Modulo"),
	TO_ENUM(MIPS_msa_mod_u_d, "Vector Unsigned Modulo"),
	TO_ENUM(MIPS_msa_dotp_s_h, "Vector Signed Dot Product"),
	TO_ENUM(MIPS_msa_dotp_s_w, "Vector Signed Dot Product"),
	TO_ENUM(MIPS_msa_dotp_s_d, "Vector Signed Dot Product"),
	TO_ENUM(MIPS_msa_dotp_u_h, "Vector Unsigned Dot Product"),
	TO_ENUM(MIPS_msa_dotp_u_w, "Vector Unsigned Dot Product"),
	TO_ENUM(MIPS_msa_dotp_u_d, "Vector Unsigned Dot Product"),
	TO_ENUM(MIPS_msa_dpadd_s_h, "Vector Signed Dot Product and Add"),
	TO_ENUM(MIPS_msa_dpadd_s_w, "Vector Signed Dot Product and Add"),
	TO_ENUM(MIPS_msa_dpadd_s_d, "Vector Signed Dot Product and Add"),
	TO_ENUM(MIPS_msa_dpadd_u_h, "Vector Unsigned Dot Product and Add"),
	TO_ENUM(MIPS_msa_dpadd_u_w, "Vector Unsigned Dot Product and Add"),
	TO_ENUM(MIPS_msa_dpadd_u_d, "Vector Unsigned Dot Product and Add"),
	TO_ENUM(MIPS_msa_dpsub_s_h, "Vector Signed Dot Product and Subtract"),
	TO_ENUM(MIPS_msa_dpsub_s_w, "Vector Signed Dot Product and Subtract"),
	TO_ENUM(MIPS_msa_dpsub_s_d, "Vector Signed Dot Product and Subtract"),
	TO_ENUM(MIPS_msa_dpsub_u_h, "Vector Unsigned Dot Product and Subtract"),
	TO_ENUM(MIPS_msa_dpsub_u_w, "Vector Unsigned Dot Product and Subtract"),
	TO_ENUM(MIPS_msa_dpsub_u_d, "Vector Unsigned Dot Product and Subtract"),
	TO_ENUM(MIPS_msa_sld_b, "GPR Columns Slide"),
	TO_ENUM(MIPS_msa_sld_h, "GPR Columns Slide"),
	TO_ENUM(MIPS_msa_sld_w, "GPR Columns Slide"),
	TO_ENUM(MIPS_msa_sld_d, "GPR Columns Slide"),
	TO_ENUM(MIPS_msa_sldi_b, "Immediate Columns Slide"),
	TO_ENUM(MIPS_msa_sldi_h, "Immediate Columns Slide"),
	TO_ENUM(MIPS_msa_sldi_w, "Immediate Columns Slide"),
	TO_ENUM(MIPS_msa_sldi_d, "Immediate Columns Slide"),
	TO_ENUM(MIPS_msa_splat_b, "GPR Element Splat"),
	TO_ENUM(MIPS_msa_splat_h, "GPR Element Splat"),
	TO_ENUM(MIPS_msa_splat_w, "GPR Element Splat"),
	TO_ENUM(MIPS_msa_splat_d, "GPR Element Splat"),
	TO_ENUM(MIPS_msa_splati_b, "Immediate Element Splat"),
	TO_ENUM(MIPS_msa_splati_h, "Immediate Element Splat"),
	TO_ENUM(MIPS_msa_splati_w, "Immediate Element Splat"),
	TO_ENUM(MIPS_msa_splati_d, "Immediate Element Splat"),
	TO_ENUM(MIPS_msa_pckev_b, "Vector Pack Even"),
	TO_ENUM(MIPS_msa_pckev_h, "Vector Pack Even"),
	TO_ENUM(MIPS_msa_pckev_w, "Vector Pack Even"),
	TO_ENUM(MIPS_msa_pckev_d, "Vector Pack Even"),
	TO_ENUM(MIPS_msa_pckod_b, "Vector Pack Odd"),
	TO_ENUM(MIPS_msa_pckod_h, "Vector Pack Odd"),
	TO_ENUM(MIPS_msa_pckod_w, "Vector Pack Odd"),
	TO_ENUM(MIPS_msa_pckod_d, "Vector Pack Odd"),
	TO_ENUM(MIPS_msa_ilvl_b, "Vector Interleave Left"),
	TO_ENUM(MIPS_msa_ilvl_h, "Vector Interleave Left"),
	TO_ENUM(MIPS_msa_ilvl_w, "Vector Interleave Left"),
	TO_ENUM(MIPS_msa_ilvl_d, "Vector Interleave Left"),
	TO_ENUM(MIPS_msa_ilvr_b, "Vector Interleave Right"),
	TO_ENUM(MIPS_msa_ilvr_h, "Vector Interleave Right"),
	TO_ENUM(MIPS_msa_ilvr_w, "Vector Interleave Right"),
	TO_ENUM(MIPS_msa_ilvr_d, "Vector Interleave Right"),
	TO_ENUM(MIPS_msa_ilvev_b, "Vector Interleave Even"),
	TO_ENUM(MIPS_msa_ilvev_h, "Vector Interleave Even"),
	TO_ENUM(MIPS_msa_ilvev_w, "Vector Interleave Even"),
	TO_ENUM(MIPS_msa_ilvev_d, "Vector Interleave Even"),
	TO_ENUM(MIPS_msa_ilvod_b, "Vector Interleave Odd"),
	TO_ENUM(MIPS_msa_ilvod_h, "Vector Interleave Odd"),
	TO_ENUM(MIPS_msa_ilvod_w, "Vector Interleave Odd"),
	TO_ENUM(MIPS_msa_ilvod_d, "Vector Interleave Odd"),
	TO_ENUM(MIPS_msa_vshf_b, "Vector Data Preserving Shuffle"),
	TO_ENUM(MIPS_msa_vshf_h, "Vector Data Preserving Shuffle"),
	TO_ENUM(MIPS_msa_vshf_w, "Vector Data Preserving Shuffle"),
	TO_ENUM(MIPS_msa_vshf_d, "Vector Data Preserving Shuffle"),
	TO_ENUM(MIPS_msa_srar_b, "Vector Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srar_h, "Vector Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srar_w, "Vector Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srar_d, "Vector Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srari_b, "Immediate Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srari_h, "Immediate Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srari_w, "Immediate Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srari_d, "Immediate Shift Right Arithmetic Rounded"),
	TO_ENUM(MIPS_msa_srlr_b, "Vector Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlr_h, "Vector Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlr_w, "Vector Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlr_d, "Vector Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlri_b, "Immediate Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlri_h, "Immediate Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlri_w, "Immediate Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_srlri_d, "Immediate Shift Right Logical Rounded"),
	TO_ENUM(MIPS_msa_hadd_s_h, "Vector Signed Horizontal Add"),
	TO_ENUM(MIPS_msa_hadd_s_w, "Vector Signed Horizontal Add"),
	TO_ENUM(MIPS_msa_hadd_s_d, "Vector Signed Horizontal Add"),
	TO_ENUM(MIPS_msa_hadd_u_h, "Vector Unsigned Horizontal Add"),
	TO_ENUM(MIPS_msa_hadd_u_w, "Vector Unsigned Horizontal Add"),
	TO_ENUM(MIPS_msa_hadd_u_d, "Vector Unsigned Horizontal Add"),
	TO_ENUM(MIPS_msa_hsub_s_h, "Vector Signed Horizontal Subtract"),
	TO_ENUM(MIPS_msa_hsub_s_w, "Vector Signed Horizontal Subtract"),
	TO_ENUM(MIPS_msa_hsub_s_d, "Vector Signed Horizontal Subtract"),
	TO_ENUM(MIPS_msa_hsub_u_h, "Vector Unsigned Horizontal Subtract"),
	TO_ENUM(MIPS_msa_hsub_u_w, "Vector Unsigned Horizontal Subtract"),
	TO_ENUM(MIPS_msa_hsub_u_d, "Vector Unsigned Horizontal Subtract"),
	TO_ENUM(MIPS_msa_and_v, "Vector Logical And"),
	TO_ENUM(MIPS_msa_andi_b, "Immediate Logical And"),
	TO_ENUM(MIPS_msa_or_v, "Vector Logical Or"),
	TO_ENUM(MIPS_msa_ori_b, "Immediate Logical Or"),
	TO_ENUM(MIPS_msa_nor_v, "Vector Logical Negated Or"),
	TO_ENUM(MIPS_msa_nori_b, "Immediate Logical Negated Or"),
	TO_ENUM(MIPS_msa_xor_v, "Vector Logical Exclusive Or"),
	TO_ENUM(MIPS_msa_xori_b, "Immediate Logical Exclusive Or"),
	TO_ENUM(MIPS_msa_bmnz_v, "Vector Bit Move If Not Zero"),
	TO_ENUM(MIPS_msa_bmnzi_b, "Immediate Bit Move If Not Zero"),
	TO_ENUM(MIPS_msa_bmz_v, "Vector Bit Move If Zero"),
	TO_ENUM(MIPS_msa_bmzi_b, "Immediate Bit Move If Zero"),
	TO_ENUM(MIPS_msa_bsel_v, "Vector Bit Select"),
	TO_ENUM(MIPS_msa_bseli_b, "Immediate Bit Select"),
	TO_ENUM(MIPS_msa_shf_b, "Immediate Set Shuffle Elements"),
	TO_ENUM(MIPS_msa_shf_h, "Immediate Set Shuffle Elements"),
	TO_ENUM(MIPS_msa_shf_w, "Immediate Set Shuffle Elements"),
	TO_ENUM(MIPS_msa_bnz_v, "Immediate Branch If Not Zero (At Least One Element of Any Format Is Not Zero)"),
	TO_ENUM(MIPS_msa_bz_v, "Immediate Branch If Zero (All Elements of Any Format Are Zero)"),
	TO_ENUM(MIPS_msa_fill_b, "Vector Fill from GPR"),
	TO_ENUM(MIPS_msa_fill_h, "Vector Fill from GPR"),
	TO_ENUM(MIPS_msa_fill_w, "Vector Fill from GPR"),
	TO_ENUM(MIPS_msa_fill_d, "Vector Fill from GPR"),
	TO_ENUM(MIPS_msa_pcnt_b, "Vector Population Count"),
	TO_ENUM(MIPS_msa_pcnt_h, "Vector Population Count"),
	TO_ENUM(MIPS_msa_pcnt_w, "Vector Population Count"),
	TO_ENUM(MIPS_msa_pcnt_d, "Vector Population Count"),
	TO_ENUM(MIPS_msa_nloc_b, "Vector Leading Ones Count"),
	TO_ENUM(MIPS_msa_nloc_h, "Vector Leading Ones Count"),
	TO_ENUM(MIPS_msa_nloc_w, "Vector Leading Ones Count"),
	TO_ENUM(MIPS_msa_nloc_d, "Vector Leading Ones Count"),
	TO_ENUM(MIPS_msa_nlzc_b, "Vector Leading Zeros Count"),
	TO_ENUM(MIPS_msa_nlzc_h, "Vector Leading Zeros Count"),
	TO_ENUM(MIPS_msa_nlzc_w, "Vector Leading Zeros Count"),
	TO_ENUM(MIPS_msa_nlzc_d, "Vector Leading Zeros Count"),
	TO_ENUM(MIPS_msa_copy_s_b, "Element Copy to GPR Signed"),
	TO_ENUM(MIPS_msa_copy_s_h, "Element Copy to GPR Signed"),
	TO_ENUM(MIPS_msa_copy_s_w, "Element Copy to GPR Signed"),
	TO_ENUM(MIPS_msa_copy_s_d, "Element Copy to GPR Signed"),
	TO_ENUM(MIPS_msa_copy_u_b, "Element Copy to GPR Unsigned"),
	TO_ENUM(MIPS_msa_copy_u_h, "Element Copy to GPR Unsigned"),
	TO_ENUM(MIPS_msa_copy_u_w, "Element Copy to GPR Unsigned"),
	TO_ENUM(MIPS_msa_copy_u_d, "Element Copy to GPR Unsigned"),
	TO_ENUM(MIPS_msa_insert_b, "GPR Insert Element"),
	TO_ENUM(MIPS_msa_insert_h, "GPR Insert Element"),
	TO_ENUM(MIPS_msa_insert_w, "GPR Insert Element"),
	TO_ENUM(MIPS_msa_insert_d, "GPR Insert Element"),
	TO_ENUM(MIPS_msa_insve_b, "Element Insert Element"),
	TO_ENUM(MIPS_msa_insve_h, "Element Insert Element"),
	TO_ENUM(MIPS_msa_insve_w, "Element Insert Element"),
	TO_ENUM(MIPS_msa_insve_d, "Element Insert Element"),
	TO_ENUM(MIPS_msa_bnz_b, "Immediate Branch If All Elements Are Not Zero"),
	TO_ENUM(MIPS_msa_bnz_h, "Immediate Branch If All Elements Are Not Zero"),
	TO_ENUM(MIPS_msa_bnz_w, "Immediate Branch If All Elements Are Not Zero"),
	TO_ENUM(MIPS_msa_bnz_d, "Immediate Branch If All Elements Are Not Zero"),
	TO_ENUM(MIPS_msa_bz_b, "Immediate Branch If At Least One Element Is Zero"),
	TO_ENUM(MIPS_msa_bz_h, "Immediate Branch If At Least One Element Is Zero"),
	TO_ENUM(MIPS_msa_bz_w, "Immediate Branch If At Least One Element Is Zero"),
	TO_ENUM(MIPS_msa_bz_d, "Immediate Branch If At Least One Element Is Zero"),
	TO_ENUM(MIPS_msa_ldi_b, "Immediate Load"),
	TO_ENUM(MIPS_msa_ldi_h, "Immediate Load"),
	TO_ENUM(MIPS_msa_ldi_w, "Immediate Load"),
	TO_ENUM(MIPS_msa_ldi_d, "Immediate Load"),
	TO_ENUM(MIPS_msa_fcaf_w, "Vector Floating-Point Quiet Compare Always False"),
	TO_ENUM(MIPS_msa_fcaf_d, "Vector Floating-Point Quiet Compare Always False"),
	TO_ENUM(MIPS_msa_fcun_w, "Vector Floating-Point Quiet Compare Unordered"),
	TO_ENUM(MIPS_msa_fcun_d, "Vector Floating-Point Quiet Compare Unordered"),
	TO_ENUM(MIPS_msa_fceq_w, "Vector Floating-Point Quiet Compare Equal"),
	TO_ENUM(MIPS_msa_fceq_d, "Vector Floating-Point Quiet Compare Equal"),
	TO_ENUM(MIPS_msa_fcueq_w, "Vector Floating-Point Quiet Compare Unordered or Equal"),
	TO_ENUM(MIPS_msa_fcueq_d, "Vector Floating-Point Quiet Compare Unordered or Equal"),
	TO_ENUM(MIPS_msa_fclt_w, "Vector Floating-Point Quiet Compare Less Than"),
	TO_ENUM(MIPS_msa_fclt_d, "Vector Floating-Point Quiet Compare Less Than"),
	TO_ENUM(MIPS_msa_fcult_w, "Vector Floating-Point Quiet Compare Unordered or Less Than"),
	TO_ENUM(MIPS_msa_fcult_d, "Vector Floating-Point Quiet Compare Unordered or Less Than"),
	TO_ENUM(MIPS_msa_fcle_w, "Vector Floating-Point Quiet Compare Less or Equal"),
	TO_ENUM(MIPS_msa_fcle_d, "Vector Floating-Point Quiet Compare Less or Equal"),
	TO_ENUM(MIPS_msa_fcule_w, "Vector Floating-Point Quiet Compare Unordered or Less or Equal"),
	TO_ENUM(MIPS_msa_fcule_d, "Vector Floating-Point Quiet Compare Unordered or Less or Equal"),
	TO_ENUM(MIPS_msa_fsaf_w, "Vector Floating-Point Signaling Compare Always False"),
	TO_ENUM(MIPS_msa_fsaf_d, "Vector Floating-Point Signaling Compare Always False"),
	TO_ENUM(MIPS_msa_fsun_w, "Vector Floating-Point Signaling Compare Unordered"),
	TO_ENUM(MIPS_msa_fsun_d, "Vector Floating-Point Signaling Compare Unordered"),
	TO_ENUM(MIPS_msa_fseq_w, "Vector Floating-Point Signaling Compare Equal"),
	TO_ENUM(MIPS_msa_fseq_d, "Vector Floating-Point Signaling Compare Equal"),
	TO_ENUM(MIPS_msa_fsueq_w, "Vector Floating-Point Signaling Compare Unordered or Equal"),
	TO_ENUM(MIPS_msa_fsueq_d, "Vector Floating-Point Signaling Compare Unordered or Equal"),
	TO_ENUM(MIPS_msa_fslt_w, "Vector Floating-Point Signaling Compare Less Than"),
	TO_ENUM(MIPS_msa_fslt_d, "Vector Floating-Point Signaling Compare Less Than"),
	TO_ENUM(MIPS_msa_fsult_w, "Vector Floating-Point Signaling Compare Unordered or Less Than"),
	TO_ENUM(MIPS_msa_fsult_d, "Vector Floating-Point Signaling Compare Unordered or Less Than"),
	TO_ENUM(MIPS_msa_fsle_w, "Vector Floating-Point Signaling Compare Less or Equal"),
	TO_ENUM(MIPS_msa_fsle_d, "Vector Floating-Point Signaling Compare Less or Equal"),
	TO_ENUM(MIPS_msa_fsule_w, "Vector Floating-Point Signaling Compare Unordered or Less or Equal"),
	TO_ENUM(MIPS_msa_fsule_d, "Vector Floating-Point Signaling Compare Unordered or Less or Equal"),
	TO_ENUM(MIPS_msa_fadd_w, "Vector Floating-Point Addition"),
	TO_ENUM(MIPS_msa_fadd_d, "Vector Floating-Point Addition"),
	TO_ENUM(MIPS_msa_fsub_w, "Vector Floating-Point Subtraction"),
	TO_ENUM(MIPS_msa_fsub_d, "Vector Floating-Point Subtraction"),
	TO_ENUM(MIPS_msa_fmul_w, "Vector Floating-Point Multiplication"),
	TO_ENUM(MIPS_msa_fmul_d, "Vector Floating-Point Multiplication"),
	TO_ENUM(MIPS_msa_fdiv_w, "Vector Floating-Point Division"),
	TO_ENUM(MIPS_msa_fdiv_d, "Vector Floating-Point Division"),
	TO_ENUM(MIPS_msa_fmadd_w, "Vector Floating-Point Multiply-Add"),
	TO_ENUM(MIPS_msa_fmadd_d, "Vector Floating-Point Multiply-Add"),
	TO_ENUM(MIPS_msa_fmsub_w, "Vector Floating-Point Multiply-Sub"),
	TO_ENUM(MIPS_msa_fmsub_d, "Vector Floating-Point Multiply-Sub"),
	TO_ENUM(MIPS_msa_fexp2_w, "Vector Floating-Point Base 2 Exponentiation"),
	TO_ENUM(MIPS_msa_fexp2_d, "Vector Floating-Point Base 2 Exponentiation"),
	TO_ENUM(MIPS_msa_fexdo_h, "Vector Floating-Point Down-Convert Interchange Format"),
	TO_ENUM(MIPS_msa_fexdo_w, "Vector Floating-Point Down-Convert Interchange Format"),
	TO_ENUM(MIPS_msa_ftq_h, "Vector Floating-Point Convert to Fixed-Point"),
	TO_ENUM(MIPS_msa_ftq_w, "Vector Floating-Point Convert to Fixed-Point"),
	TO_ENUM(MIPS_msa_fmin_w, "Vector Floating-Point Minimum"),
	TO_ENUM(MIPS_msa_fmin_d, "Vector Floating-Point Minimum"),
	TO_ENUM(MIPS_msa_fmin_a_w, "Vector Floating-Point Minimum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_fmin_a_d, "Vector Floating-Point Minimum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_fmax_w, "Vector Floating-Point Maximum"),
	TO_ENUM(MIPS_msa_fmax_d, "Vector Floating-Point Maximum"),
	TO_ENUM(MIPS_msa_fmax_a_w, "Vector Floating-Point Maximum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_fmax_a_d, "Vector Floating-Point Maximum Based on Absolute Values"),
	TO_ENUM(MIPS_msa_fcor_w, "Vector Floating-Point Quiet Compare Ordered"),
	TO_ENUM(MIPS_msa_fcor_d, "Vector Floating-Point Quiet Compare Ordered"),
	TO_ENUM(MIPS_msa_fcune_w, "Vector Floating-Point Quiet Compare Unordered or Not Equal"),
	TO_ENUM(MIPS_msa_fcune_d, "Vector Floating-Point Quiet Compare Unordered or Not Equal"),
	TO_ENUM(MIPS_msa_fcne_w, "Vector Floating-Point Quiet Compare Not Equal"),
	TO_ENUM(MIPS_msa_fcne_d, "Vector Floating-Point Quiet Compare Not Equal"),
	TO_ENUM(MIPS_msa_mul_q_h, "Vector Fixed-Point Multiply"),
	TO_ENUM(MIPS_msa_mul_q_w, "Vector Fixed-Point Multiply"),
	TO_ENUM(MIPS_msa_madd_q_h, "Vector Fixed-Point Multiply and Add"),
	TO_ENUM(MIPS_msa_madd_q_w, "Vector Fixed-Point Multiply and Add"),
	TO_ENUM(MIPS_msa_msub_q_h, "Vector Fixed-Point Multiply and Subtract"),
	TO_ENUM(MIPS_msa_msub_q_w, "Vector Fixed-Point Multiply and Subtract"),
	TO_ENUM(MIPS_msa_fsor_w, "Vector Floating-Point Signaling Compare Ordered"),
	TO_ENUM(MIPS_msa_fsor_d, "Vector Floating-Point Signaling Compare Ordered"),
	TO_ENUM(MIPS_msa_fsune_w, "Vector Floating-Point Signaling Compare Unordered or Not Equal"),
	TO_ENUM(MIPS_msa_fsune_d, "Vector Floating-Point Signaling Compare Unordered or Not Equal"),
	TO_ENUM(MIPS_msa_fsne_w, "Vector Floating-Point Signaling Compare Not Equal"),
	TO_ENUM(MIPS_msa_fsne_d, "Vector Floating-Point Signaling Compare Not Equal"),
	TO_ENUM(MIPS_msa_mulr_q_h, "Vector Fixed-Point Multiply Rounded"),
	TO_ENUM(MIPS_msa_mulr_q_w, "Vector Fixed-Point Multiply Rounded"),
	TO_ENUM(MIPS_msa_maddr_q_h, "Vector Fixed-Point Multiply and Add Rounded"),
	TO_ENUM(MIPS_msa_maddr_q_w, "Vector Fixed-Point Multiply and Add Rounded"),
	TO_ENUM(MIPS_msa_msubr_q_h, "Vector Fixed-Point Multiply and Subtract Rounded"),
	TO_ENUM(MIPS_msa_msubr_q_w, "Vector Fixed-Point Multiply and Subtract Rounded"),
	TO_ENUM(MIPS_msa_fclass_w, "Vector Floating-Point Class Mask"),
	TO_ENUM(MIPS_msa_fclass_d, "Vector Floating-Point Class Mask"),
	TO_ENUM(MIPS_msa_ftrunc_s_w, "Vector Floating-Point Truncate and Convert to Signed Integer"),
	TO_ENUM(MIPS_msa_ftrunc_s_d, "Vector Floating-Point Truncate and Convert to Signed Integer"),
	TO_ENUM(MIPS_msa_ftrunc_u_w, "Vector Floating-Point Truncate and Convert to Unsigned Integer"),
	TO_ENUM(MIPS_msa_ftrunc_u_d, "Vector Floating-Point Truncate and Convert to Unsigned Integer"),
	TO_ENUM(MIPS_msa_fsqrt_w, "Vector Floating-Point Square Root"),
	TO_ENUM(MIPS_msa_fsqrt_d, "Vector Floating-Point Square Root"),
	TO_ENUM(MIPS_msa_frsqrt_w, "Vector Approximate Floating-Point Reciprocal of Square Root"),
	TO_ENUM(MIPS_msa_frsqrt_d, "Vector Approximate Floating-Point Reciprocal of Square Root"),
	TO_ENUM(MIPS_msa_frcp_w, "Vector Approximate Floating-Point Reciprocal"),
	TO_ENUM(MIPS_msa_frcp_d, "Vector Approximate Floating-Point Reciprocal"),
	TO_ENUM(MIPS_msa_frint_w, "Vector Floating-Point Round to Integer"),
	TO_ENUM(MIPS_msa_frint_d, "Vector Floating-Point Round to Integer"),
	TO_ENUM(MIPS_msa_flog2_w, "Vector Floating-Point Base 2 Logarithm"),
	TO_ENUM(MIPS_msa_flog2_d, "Vector Floating-Point Base 2 Logarithm"),
	TO_ENUM(MIPS_msa_fexupl_w, "Vector Floating-Point Up-Convert Interchange Format Left"),
	TO_ENUM(MIPS_msa_fexupl_d, "Vector Floating-Point Up-Convert Interchange Format Left"),
	TO_ENUM(MIPS_msa_fexupr_w, "Vector Floating-Point Up-Convert Interchange Format Right"),
	TO_ENUM(MIPS_msa_fexupr_d, "Vector Floating-Point Up-Convert Interchange Format Right"),
	TO_ENUM(MIPS_msa_ffql_w, "Vector Floating-Point Convert from Fixed-Point Left"),
	TO_ENUM(MIPS_msa_ffql_d, "Vector Floating-Point Convert from Fixed-Point Left"),
	TO_ENUM(MIPS_msa_ffqr_w, "Vector Floating-Point Convert from Fixed-Point Right"),
	TO_ENUM(MIPS_msa_ffqr_d, "Vector Floating-Point Convert from Fixed-Point Right"),
	TO_ENUM(MIPS_msa_ftint_s_w, "Vector Floating-Point Convert to Signed Integer"),
	TO_ENUM(MIPS_msa_ftint_s_d, "Vector Floating-Point Convert to Signed Integer"),
	TO_ENUM(MIPS_msa_ftint_u_w, "Vector Floating-Point Round and Convert to Unsigned Integer"),
	TO_ENUM(MIPS_msa_ftint_u_d, "Vector Floating-Point Round and Convert to Unsigned Integer"),
	TO_ENUM(MIPS_msa_ffint_s_w, "Vector Floating-Point Round and Convert from Signed Integer"),
	TO_ENUM(MIPS_msa_ffint_s_d, "Vector Floating-Point Round and Convert from Signed Integer"),
	TO_ENUM(MIPS_msa_ffint_u_w, "Vector Floating-Point Convert from Unsigned Integer"),
	TO_ENUM(MIPS_msa_ffint_u_d, "Vector Floating-Point Convert from Unsigned Integer"),
	TO_ENUM(MIPS_msa_ctcmsa, "GPR Copy to MSA Control Register"),
	TO_ENUM(MIPS_msa_cfcmsa, "GPR Copy from MSA Control Register"),
	TO_ENUM(MIPS_msa_move_v, "Vector Move"),
	TO_ENUM(MIPS_lsa, "Left Shift Add"),
	TO_ENUM(MIPS_dlsa, "Doubleword Left Shift Add"),
	TO_ENUM(MIPS_lbe, "Load Byte EVA"),
	TO_ENUM(MIPS_lbue, "Load Byte Unsigned EVA"),
	TO_ENUM(MIPS_lhe, "Load Halfword EVA"),
	TO_ENUM(MIPS_lhue, "Load Halfword Unsigned EVA"),
	TO_ENUM(MIPS_lwe, "Load Word EVA"),
	TO_ENUM(MIPS_sbe, "Store Byte EVA"),
	TO_ENUM(MIPS_she, "Store Halfword EVA"),
	TO_ENUM(MIPS_swe, "Store Word EVA"),
	TO_ENUM(MIPS_lle, "Load Linked Word EVA"),
	TO_ENUM(MIPS_sce, "Store Conditional Word EVA"),
	TO_ENUM(MIPS_cachee, "Perform Cache Operation EVA"),
	TO_ENUM(MIPS_prefe, "Prefetch EVA"),
	TO_ENUM(MIPS_lwle, "Load Word Left EVA"),
	TO_ENUM(MIPS_lwre, "Load Word Right EVA"),
	TO_ENUM(MIPS_swle, "Store Word Left EVA"),
	TO_ENUM(MIPS_swre, "Store Word Right EVA"),
	TO_ENUM(MIPS_movtz, "Move Conditional on T Equal to Zero"),
	TO_ENUM(MIPS_movtn, "Move Zero Conditional on T Not Equal to Zero"),
	TO_ENUM(MIPS_copyw, "Copy Data to Aligned Memory Location"),
	TO_ENUM(MIPS_ucopyw, "Copy Data to Unaligned Memory Location"),
	TO_ENUM(MIPS_muh, "Multiply High"),
	TO_ENUM(MIPS_mulu, "Multiply Unsigned"),
	TO_ENUM(MIPS_muhu, "Multiply High Unsigned"),
	TO_ENUM(MIPS_mod, "Modulo"),
	TO_ENUM(MIPS_modu, "Modulo Unsigned"),
	TO_ENUM(MIPS_sov, "Set on Overflow"),
	TO_ENUM(MIPS_crc32b, "CRC32 Byte"),
	TO_ENUM(MIPS_crc32h, "CRC32 Half"),
	TO_ENUM(MIPS_crc32w, "CRC32 Word"),
	TO_ENUM(MIPS_crc32cb, "CRC32 Castagnoli Byte"),
	TO_ENUM(MIPS_crc32ch, "CRC32 Castagnoli Half"),
	TO_ENUM(MIPS_crc32cw, "CRC32 Castagnoli Word"),
	TO_ENUM(MIPS_sbx, "Store Byte indeXed"),
	TO_ENUM(MIPS_shx, "Store Half indeXed"),
	TO_ENUM(MIPS_shxs, "Store Half indeXed Scaled"),
	TO_ENUM(MIPS_swx, "Store Word indeXed"),
	TO_ENUM(MIPS_swxs, "Store Word indeXed Scaled"),
	TO_ENUM(MIPS_lhxs, "Load Half indeXed Scaled"),
	TO_ENUM(MIPS_lhuxs, "Load Half Unsigned indeXed Scaled"),
	TO_ENUM(MIPS_mfhc0, "Move From High Coprocessor 0"),
	TO_ENUM(MIPS_mthc0, "Move To High Coprocessor 0"),
	TO_ENUM(MIPS_extw, "Extend Word"),
	TO_ENUM(MIPS_tlbinv, "TLB Invalidate"),
	TO_ENUM(MIPS_tlbinvf, "TLB Invalidate Flush"),
	TO_ENUM(MIPS_ginvt, "Globally Invalidate TLBs"),
	TO_ENUM(MIPS_ginvi, "Globally Invalidate Instruction caches"),
	TO_ENUM(MIPS_eretnc, "Exception Return Not Clearing LLBit"),
	TO_ENUM(MIPS_lwpc, "Load Word PC relative"),
	TO_ENUM(MIPS_swpc, "Store Word PC relative"),
	TO_ENUM(MIPS_rotx, "Rotate and eXchange"),
	TO_ENUM(MIPS_llwp, "Load Linked Word Pair"),
	TO_ENUM(MIPS_llwpe, "Load Linked Word Pair using EVA addressing"),
	TO_ENUM(MIPS_scwp, "Load Linked Word Pair"),
	TO_ENUM(MIPS_scwpe, "Load Linked Word Pair using EVA addressing"),
	TO_ENUM(MIPS_ualwm, "Unaligned Load Word Multiple"),
	TO_ENUM(MIPS_uaswm, "Unaligned Store Word Multiple"),
	TO_ENUM(MIPS_ualh, "Unaligned Load Half"),
	TO_ENUM(MIPS_uash, "Unaligned Store Half"),
	TO_ENUM(MIPS_syncie, "SYNChronize Instruction cache using EVA addressing"),
	TO_ENUM(MIPS_dvp, "Disable Virtual Processor"),
	TO_ENUM(MIPS_evp, "Enable Virtual Processor"),
	TO_ENUM(MIPS_sigrie, "Signal Reserved Instruction Exception"),
	TO_ENUM(MIPS_bc, "Branch Always, Compact"),
	TO_ENUM(MIPS_balc, "Branch Always and Link, Compact"),
	TO_ENUM(MIPS_restore_jrc, "Restore callee saved registers and Jump to Return address, Compact"),
	TO_ENUM(MIPS_move_balc, "Move and Branch and Link, Compact"),
	TO_ENUM(MIPS_addiupc, "Add Immediate (Untrapped) to PC"),
	TO_ENUM(MIPS_jalrc_hb, "Jump And Link Register, Compact, with Hazard Barrier"),
	TO_ENUM(MIPS_aluipc, "Add aLigned Upper Immediate to PC"),
	TO_ENUM(MIPS_beqic, "Branch if Equal to Immediate, Compact"),
	TO_ENUM(MIPS_bbeqzc, "Branch if Bit Equals Zero, Compact"),
	TO_ENUM(MIPS_bgeic, "Branch if Greater than or Equal to Immediate, Compact"),
	TO_ENUM(MIPS_bgeiuc, "Branch if Greater than or Equal to Immediate Unsigned, Compact"),
	TO_ENUM(MIPS_bneic, "Branch if Not Equal to Immediate, Compact"),
	TO_ENUM(MIPS_bbnezc, "Branch if Bit Not Equal to Zero, Compact"),
	TO_ENUM(MIPS_bltic, "Branch if Less Than Immediate, Compact"),
	TO_ENUM(MIPS_bltiuc, "Branch if Less Than Immediate Unsigned Compact"),
	TO_ENUM(MIPS_bnec, "Branch Not Equal, Compact"),
	TO_ENUM(MIPS_bltc, "Branch if Less Than, Compact"),
	TO_ENUM(MIPS_bltuc, "Branch if Less Than Unsigned, Compact"),
	TO_ENUM(MIPS_beqc, "Branch if Equal, Compact"),
	TO_ENUM(MIPS_bgec, "Branch if Greater than or Equal, Compact"),
	TO_ENUM(MIPS_bgeuc, "Branch if Greater than or Equal to Unsigned, Compact"),
	TO_ENUM(MIPS_brsc, "Branch Register Scaled, Compact"),
	TO_ENUM(MIPS_balrsc, "Branch And Link Register Scaled, Compact"),
	TO_ENUM(MIPS_bitrevw, "Reverse all bits"),
	TO_ENUM(MIPS_bitrevh, "Reverse bits in halfs"),
	TO_ENUM(MIPS_bitrevb, "Reverse bits in bytes"),
	TO_ENUM(MIPS_byterevw, "Reverse all bytes"),
	TO_ENUM(MIPS_byterevh, "Reverse bytes in halfs"),
	TO_ENUM(MIPS_lwm2, "Load Word Multiple (w/o reglist)"),
	TO_ENUM(MIPS_swm2, "Store Word Multiple (w/o reglist)"),
	TO_ENUM(MIPS_last, "Undocumented instruction MIPS_last")
};
