auto instructions_PLFM_ST20 = flags_vector_t{
	TO_ENUM(ST20_null, "Undocumented instruction ST20_null"),
	TO_ENUM(ST20_adc, "add constant"),
	TO_ENUM(ST20_add, "add"),
	TO_ENUM(ST20_addc, "add with carry"),
	TO_ENUM(ST20_ajw, "adjust work space"),
	TO_ENUM(ST20_and, "and"),
	TO_ENUM(ST20_arot, "anti-rotate stack"),
	TO_ENUM(ST20_ashr, "arithmetic shift right"),
	TO_ENUM(ST20_biquad, "biquad IIR filter step"),
	TO_ENUM(ST20_bitld, "load bit"),
	TO_ENUM(ST20_bitmask, "create bit mask"),
	TO_ENUM(ST20_bitst, "store bit"),
	TO_ENUM(ST20_breakpoint, "breakpoint"),
	TO_ENUM(ST20_cj, "conditional jump"),
	TO_ENUM(ST20_dequeue, "dequeue a process"),
	TO_ENUM(ST20_divstep, "divide step"),
	TO_ENUM(ST20_dup, "duplicate"),
	TO_ENUM(ST20_ecall, "exception call"),
	TO_ENUM(ST20_enqueue, "enqueue a process"),
	TO_ENUM(ST20_eqc, "equals constant"),
	TO_ENUM(ST20_eret, "exception return"),
	TO_ENUM(ST20_fcall, "function call"),
	TO_ENUM(ST20_gajw, "general adjust workspace"),
	TO_ENUM(ST20_gt, "greater than"),
	TO_ENUM(ST20_gtu, "greater than unsigned"),
	TO_ENUM(ST20_io, "input/output"),
	TO_ENUM(ST20_j, "jump"),
	TO_ENUM(ST20_jab, "jump absolute"),
	TO_ENUM(ST20_lbinc, "load byte and increment"),
	TO_ENUM(ST20_ldc, "load constant"),
	TO_ENUM(ST20_ldl, "load local"),
	TO_ENUM(ST20_ldlp, "load local pointer"),
	TO_ENUM(ST20_ldnl, "load non-local"),
	TO_ENUM(ST20_ldnlp, "load non-local pointer"),
	TO_ENUM(ST20_ldpi, "load pointer to instruction"),
	TO_ENUM(ST20_ldprodid, "load product identity"),
	TO_ENUM(ST20_ldtdesc, "load task descriptor"),
	TO_ENUM(ST20_lsinc, "load sixteen and increment"),
	TO_ENUM(ST20_lsxinc, "load sixteen sign extended and increment"),
	TO_ENUM(ST20_lwinc, "load word and increment"),
	TO_ENUM(ST20_mac, "multiply accumulate"),
	TO_ENUM(ST20_mul, "multiply"),
	TO_ENUM(ST20_nfix, "negative prefix"),
	TO_ENUM(ST20_nop, "no operation"),
	TO_ENUM(ST20_not, "bitwise not"),
	TO_ENUM(ST20_opr, "operate"),
	TO_ENUM(ST20_or, "or"),
	TO_ENUM(ST20_order, "order"),
	TO_ENUM(ST20_orderu, "unsigned order"),
	TO_ENUM(ST20_pfix, "prefix"),
	TO_ENUM(ST20_rev, "reverse"),
	TO_ENUM(ST20_rmw, "read modify write"),
	TO_ENUM(ST20_rot, "rotate stack"),
	TO_ENUM(ST20_run, "run process"),
	TO_ENUM(ST20_saturate, "saturate"),
	TO_ENUM(ST20_sbinc, "store byte and increment"),
	TO_ENUM(ST20_shl, "shift left"),
	TO_ENUM(ST20_shr, "shift right"),
	TO_ENUM(ST20_signal, "signal"),
	TO_ENUM(ST20_smacinit, "initialize short multiply accumulate loop"),
	TO_ENUM(ST20_smacloop, "short multiply accumulate loop"),
	TO_ENUM(ST20_smul, "short multiply"),
	TO_ENUM(ST20_ssinc, "store sixteen and increment"),
	TO_ENUM(ST20_statusclr, "clear bits in status register"),
	TO_ENUM(ST20_statusset, "set bits in status register"),
	TO_ENUM(ST20_statustst, "test status register"),
	TO_ENUM(ST20_stl, "store local"),
	TO_ENUM(ST20_stnl, "store non-local"),
	TO_ENUM(ST20_stop, "stop process"),
	TO_ENUM(ST20_sub, "subtract"),
	TO_ENUM(ST20_subc, "subtract with carry"),
	TO_ENUM(ST20_swap32, "byte swap 32"),
	TO_ENUM(ST20_swinc, "store word and increment"),
	TO_ENUM(ST20_timeslice, "timeslice"),
	TO_ENUM(ST20_umac, "unsigned multiply accumulate"),
	TO_ENUM(ST20_unsign, "unsign argument"),
	TO_ENUM(ST20_wait, "wait"),
	TO_ENUM(ST20_wsub, "word subscript"),
	TO_ENUM(ST20_xbword, "sign extend byte to word"),
	TO_ENUM(ST20_xor, "exclusive or"),
	TO_ENUM(ST20_xsword, "sign extend sixteen to word"),
	TO_ENUM(ST20_alt, "alt start"),
	TO_ENUM(ST20_altend, "alt end"),
	TO_ENUM(ST20_altwt, "alt wait"),
	TO_ENUM(ST20_bcnt, "byte count"),
	TO_ENUM(ST20_bitcnt, "count bits set in word"),
	TO_ENUM(ST20_bitrevnbits, "reverse bottom n bits in word"),
	TO_ENUM(ST20_bitrevword, "reverse bits in word"),
	TO_ENUM(ST20_bsub, "byte subscript"),
	TO_ENUM(ST20_call, "call"),
	TO_ENUM(ST20_causeerror, "cause error"),
	TO_ENUM(ST20_cb, "check byte"),
	TO_ENUM(ST20_cbu, "check byte unsigned"),
	TO_ENUM(ST20_ccnt1, "check count from 1"),
	TO_ENUM(ST20_cflerr, "check floating point error"),
	TO_ENUM(ST20_cir, "check in range"),
	TO_ENUM(ST20_ciru, "check in range unsigned"),
	TO_ENUM(ST20_clockdis, "clock disable"),
	TO_ENUM(ST20_clockenb, "clock enable"),
	TO_ENUM(ST20_clrhalterr, "clear halt-on error flag"),
	TO_ENUM(ST20_crcbyte, "calculate CRC on byte"),
	TO_ENUM(ST20_crcword, "calculate CRC on word"),
	TO_ENUM(ST20_cs, "check sixteen"),
	TO_ENUM(ST20_csngl, "check single"),
	TO_ENUM(ST20_csu, "check sixteen unsigned"),
	TO_ENUM(ST20_csub0, "check subscript from 0"),
	TO_ENUM(ST20_cword, "check word"),
	TO_ENUM(ST20_devlb, "device load byte"),
	TO_ENUM(ST20_devls, "device load sixteen"),
	TO_ENUM(ST20_devlw, "device load word"),
	TO_ENUM(ST20_devmove, "device move"),
	TO_ENUM(ST20_devsb, "device store byte"),
	TO_ENUM(ST20_devss, "device store sixteen"),
	TO_ENUM(ST20_devsw, "device store word"),
	TO_ENUM(ST20_diff, "difference"),
	TO_ENUM(ST20_disc, "disable channel"),
	TO_ENUM(ST20_diss, "disable skip"),
	TO_ENUM(ST20_dist, "disable timer"),
	TO_ENUM(ST20_div, "divide"),
	TO_ENUM(ST20_enbc, "enable channel"),
	TO_ENUM(ST20_enbs, "enable skip"),
	TO_ENUM(ST20_enbt, "enable timer"),
	TO_ENUM(ST20_endp, "end process"),
	TO_ENUM(ST20_fmul, "fractional multiply"),
	TO_ENUM(ST20_fptesterr, "test for FPU error"),
	TO_ENUM(ST20_gcall, "general call"),
	TO_ENUM(ST20_gintdis, "general interrupt disable"),
	TO_ENUM(ST20_gintenb, "general interrupt enable"),
	TO_ENUM(ST20_in, "input message"),
	TO_ENUM(ST20_insertqueue, "insert at front of scheduler queue"),
	TO_ENUM(ST20_intdis, "(localised) interrupt disable"),
	TO_ENUM(ST20_intenb, "(localised) interrupt enable"),
	TO_ENUM(ST20_iret, "interrupt return"),
	TO_ENUM(ST20_ladd, "long add"),
	TO_ENUM(ST20_lb, "load byte"),
	TO_ENUM(ST20_lbx, "load byte and sign extend"),
	TO_ENUM(ST20_ldclock, "load clock"),
	TO_ENUM(ST20_lddevid, "load device identity"),
	TO_ENUM(ST20_ldiff, "long diff"),
	TO_ENUM(ST20_ldinf, "load infinity"),
	TO_ENUM(ST20_ldiv, "long divide"),
	TO_ENUM(ST20_ldmemstartval, "load value of MemStart address"),
	TO_ENUM(ST20_ldpri, "load current priority"),
	TO_ENUM(ST20_ldshadow, "load shadow registers"),
	TO_ENUM(ST20_ldtimer, "load timer"),
	TO_ENUM(ST20_ldtraph, "load trap handler"),
	TO_ENUM(ST20_ldtrapped, "load trapped process status"),
	TO_ENUM(ST20_lend, "loop end"),
	TO_ENUM(ST20_lmul, "long multiply"),
	TO_ENUM(ST20_ls, "load sixteen"),
	TO_ENUM(ST20_lshl, "long shift left"),
	TO_ENUM(ST20_lshr, "long shift right"),
	TO_ENUM(ST20_lsub, "long subtract"),
	TO_ENUM(ST20_lsum, "long sum"),
	TO_ENUM(ST20_lsx, "load sixteen and sign extend"),
	TO_ENUM(ST20_mint, "minimum integer"),
	TO_ENUM(ST20_move, "move message"),
	TO_ENUM(ST20_move2dall, "2D block copy"),
	TO_ENUM(ST20_move2dinit, "initialize data for 2D block move"),
	TO_ENUM(ST20_move2dnonzero, "2D block copy non-zero bytes"),
	TO_ENUM(ST20_move2dzero, "2D block copy zero bytes"),
	TO_ENUM(ST20_norm, "normalize"),
	TO_ENUM(ST20_out, "output message"),
	TO_ENUM(ST20_outbyte, "output byte"),
	TO_ENUM(ST20_outword, "output word"),
	TO_ENUM(ST20_pop, "pop processor stack"),
	TO_ENUM(ST20_postnormsn, "post-normalize correction of single length fp number"),
	TO_ENUM(ST20_prod, "product"),
	TO_ENUM(ST20_reboot, "reboot"),
	TO_ENUM(ST20_rem, "remainder"),
	TO_ENUM(ST20_resetch, "reset channel"),
	TO_ENUM(ST20_restart, "restart"),
	TO_ENUM(ST20_ret, "return"),
	TO_ENUM(ST20_roundsn, "round single length floating point number"),
	TO_ENUM(ST20_runp, "run process"),
	TO_ENUM(ST20_satadd, "saturating add"),
	TO_ENUM(ST20_satmul, "saturating multiply"),
	TO_ENUM(ST20_satsub, "saturating subtract"),
	TO_ENUM(ST20_saveh, "save high priority queue registers"),
	TO_ENUM(ST20_savel, "save low priority queue registers"),
	TO_ENUM(ST20_sb, "store byte"),
	TO_ENUM(ST20_seterr, "set error flags"),
	TO_ENUM(ST20_sethalterr, "set halt-on error flag"),
	TO_ENUM(ST20_settimeslice, "set timeslicing status"),
	TO_ENUM(ST20_slmul, "signed long multiply"),
	TO_ENUM(ST20_ss, "store sixteen"),
	TO_ENUM(ST20_ssub, "sixteen subscript"),
	TO_ENUM(ST20_startp, "start process"),
	TO_ENUM(ST20_stclock, "store clock register"),
	TO_ENUM(ST20_sthb, "store high priority back pointer"),
	TO_ENUM(ST20_sthf, "store high priority front pointer"),
	TO_ENUM(ST20_stlb, "store low priority back pointer"),
	TO_ENUM(ST20_stlf, "store low priority front pointer"),
	TO_ENUM(ST20_stoperr, "stop on error"),
	TO_ENUM(ST20_stopp, "stop process"),
	TO_ENUM(ST20_stshadow, "store shadow registers"),
	TO_ENUM(ST20_sttimer, "store timer"),
	TO_ENUM(ST20_sttraph, "store trap handler"),
	TO_ENUM(ST20_sttrapped, "store trapped process"),
	TO_ENUM(ST20_sulmul, "signed timer unsigned long multiply"),
	TO_ENUM(ST20_sum, "sum"),
	TO_ENUM(ST20_swapqueue, "swap scheduler queue"),
	TO_ENUM(ST20_swaptimer, "swap timer queue"),
	TO_ENUM(ST20_talt, "timer alt start"),
	TO_ENUM(ST20_taltwt, "timer alt wait"),
	TO_ENUM(ST20_testerr, "test error flag"),
	TO_ENUM(ST20_testhalterr, "test halt-on error flag"),
	TO_ENUM(ST20_testpranal, "test processor analysing"),
	TO_ENUM(ST20_tin, "timer input"),
	TO_ENUM(ST20_trapdis, "trap disable"),
	TO_ENUM(ST20_trapenb, "trap enable"),
	TO_ENUM(ST20_tret, "trap return"),
	TO_ENUM(ST20_unpacksn, "unpack single length fp number"),
	TO_ENUM(ST20_wcnt, "word count"),
	TO_ENUM(ST20_wsubdb, "form double word subscript"),
	TO_ENUM(ST20_xdble, "extend to double"),
	TO_ENUM(ST20_xword, "extend word"),
	TO_ENUM(ST20_last, "Undocumented instruction ST20_last")
};
