auto instructions_PLFM_FR = flags_vector_t{
	TO_ENUM(fr_null, "Undocumented instruction fr_null"),
	TO_ENUM(fr_add, "add word data of source register / 4-bit immediate data to destination register"),
	TO_ENUM(fr_add2, "add 4-bit immediate data to destination register"),
	TO_ENUM(fr_addc, "add word data of source register and carry bit to destination register"),
	TO_ENUM(fr_addn, "add word data of source register / immediate data to destination register"),
	TO_ENUM(fr_addn2, "add immediate data to destination register"),
	TO_ENUM(fr_sub, "subtract word data in source register from destination register"),
	TO_ENUM(fr_subc, "subtract word data in source register and carry bit from destination register"),
	TO_ENUM(fr_subn, "subtract word data in source register from destination register"),
	TO_ENUM(fr_cmp, "compare word / immediate data in source register and destination register"),
	TO_ENUM(fr_cmp2, "compare immediate data and destination register"),
	TO_ENUM(fr_and, "and word data of source register to destination register / data in memory"),
	TO_ENUM(fr_andh, "and half-word data of source register to data in memory"),
	TO_ENUM(fr_andb, "and byte data of source register to data in memory"),
	TO_ENUM(fr_or, "or word data of source register to destination register / data in memory"),
	TO_ENUM(fr_orh, "or half-word data of source register to data in memory"),
	TO_ENUM(fr_orb, "or byte data of source register to data in memory"),
	TO_ENUM(fr_eor, "exclusive or word data of source register to destination register / data in memory"),
	TO_ENUM(fr_eorh, "exclusive or half-word data of source register to data in memory"),
	TO_ENUM(fr_eorb, "exclusive or byte data of source register to data in memory"),
	TO_ENUM(fr_bandl, "and 4-bit immediate data to lower 4 bits of byte data in memory"),
	TO_ENUM(fr_bandh, "and 4-bit immediate data to higher 4 bits of byte data in memory"),
	TO_ENUM(fr_borl, "or 4-bit immediate data to lower 4 bits of byte data in memory"),
	TO_ENUM(fr_borh, "or 4-bit immediate data to higher 4 bits of byte data in memory"),
	TO_ENUM(fr_beorl, "eor 4-bit immediate data to lower 4 bits of byte data in memory"),
	TO_ENUM(fr_beorh, "eor 4-bit immediate data to higher 4 bits of byte data in memory"),
	TO_ENUM(fr_btstl, "test lower 4 bits of byte data in memory"),
	TO_ENUM(fr_btsth, "test higher 4 bits of byte data in memory"),
	TO_ENUM(fr_mul, "multiply word data"),
	TO_ENUM(fr_mulu, "multiply unsigned word data"),
	TO_ENUM(fr_mulh, "multiply half-word data"),
	TO_ENUM(fr_muluh, "multiply unsigned half-word data"),
	TO_ENUM(fr_div0s, "initial setting up for signed division"),
	TO_ENUM(fr_div0u, "initial setting up for unsigned division"),
	TO_ENUM(fr_div1, "main process of division"),
	TO_ENUM(fr_div2, "correction when remainder is 0"),
	TO_ENUM(fr_div3, "correction when remainder is 0"),
	TO_ENUM(fr_div4s, "correction answer for signed division"),
	TO_ENUM(fr_lsl, "logical shift to the left direction"),
	TO_ENUM(fr_lsl2, "logical shift to the left direction"),
	TO_ENUM(fr_lsr, "logical shift to the right direction"),
	TO_ENUM(fr_lsr2, "logical shift to the right direction"),
	TO_ENUM(fr_asr, "arithmetic shift to the right direction"),
	TO_ENUM(fr_asr2, "arithmetic shift to the right direction"),
	TO_ENUM(fr_ldi_32, "load immediate 32-bit data to destination register"),
	TO_ENUM(fr_ldi_20, "load immediate 20-bit data to destination register"),
	TO_ENUM(fr_ldi_8, "load immediate 8-bit data to destination register"),
	TO_ENUM(fr_ld, "load word data in memory to register / program status register"),
	TO_ENUM(fr_lduh, "load half-word data in memory to register"),
	TO_ENUM(fr_ldub, "load byte data in memory to register"),
	TO_ENUM(fr_st, "store word data in register / program status register to memory"),
	TO_ENUM(fr_sth, "store half-word data in register to memory"),
	TO_ENUM(fr_stb, "store byte data in register to memory"),
	TO_ENUM(fr_mov, "move word data in source register / program status register to destination register / program status register"),
	TO_ENUM(fr_jmp, "jump"),
	TO_ENUM(fr_call, "call subroutine"),
	TO_ENUM(fr_ret, "return from subroutine"),
	TO_ENUM(fr_int, "software interrupt"),
	TO_ENUM(fr_inte, "software interrupt for emulator"),
	TO_ENUM(fr_reti, "return from interrupt"),
	TO_ENUM(fr_bra, "branch relative if condition satisfied"),
	TO_ENUM(fr_bno, "branch relative if condition satisfied"),
	TO_ENUM(fr_beq, "branch relative if condition satisfied"),
	TO_ENUM(fr_bne, "branch relative if condition satisfied"),
	TO_ENUM(fr_bc, "branch relative if condition satisfied"),
	TO_ENUM(fr_bnc, "branch relative if condition satisfied"),
	TO_ENUM(fr_bn, "branch relative if condition satisfied"),
	TO_ENUM(fr_bp, "branch relative if condition satisfied"),
	TO_ENUM(fr_bv, "branch relative if condition satisfied"),
	TO_ENUM(fr_bnv, "branch relative if condition satisfied"),
	TO_ENUM(fr_blt, "branch relative if condition satisfied"),
	TO_ENUM(fr_bge, "branch relative if condition satisfied"),
	TO_ENUM(fr_ble, "branch relative if condition satisfied"),
	TO_ENUM(fr_bgt, "branch relative if condition satisfied"),
	TO_ENUM(fr_bls, "branch relative if condition satisfied"),
	TO_ENUM(fr_bhi, "branch relative if condition satisfied"),
	TO_ENUM(fr_dmov, "move word data from register / address to register / address"),
	TO_ENUM(fr_dmovh, "move half-word data from register / address to register / address"),
	TO_ENUM(fr_dmovb, "move byte data from register / address to register / address"),
	TO_ENUM(fr_ldres, "load word data in memory to resource"),
	TO_ENUM(fr_stres, "store word data in resource to memory"),
	TO_ENUM(fr_copop, "coprocessor operation"),
	TO_ENUM(fr_copld, "load 32-bit data from register to coprocessor register"),
	TO_ENUM(fr_copst, "store 32-bit data from coprocessor register to register"),
	TO_ENUM(fr_copsv, "save 32-bit data from coprocessor register to register"),
	TO_ENUM(fr_nop, "no operation"),
	TO_ENUM(fr_andccr, "and condition code register and immediate data"),
	TO_ENUM(fr_orccr, "or condition code register and immediate data"),
	TO_ENUM(fr_stilm, "set immediate data to interrupt level mask register"),
	TO_ENUM(fr_addsp, "add stack pointer and immediate data"),
	TO_ENUM(fr_extsb, "sign extend from byte data to word data"),
	TO_ENUM(fr_extub, "unsign extend from byte data to word data"),
	TO_ENUM(fr_extsh, "sign extend from byte data to word data"),
	TO_ENUM(fr_extuh, "unsigned extend from byte data to word data"),
	TO_ENUM(fr_ldm0, "load multiple registers"),
	TO_ENUM(fr_ldm1, "load multiple registers"),
	TO_ENUM(fr_stm0, "store multiple registers"),
	TO_ENUM(fr_stm1, "store multiple registers"),
	TO_ENUM(fr_enter, "enter function"),
	TO_ENUM(fr_leave, "leave function"),
	TO_ENUM(fr_xchb, "exchange byte data"),
	TO_ENUM(fr_last, "last instruction")
};
