auto instructions_PLFM_TRIMEDIA = flags_vector_t{
	TO_ENUM(TRIMEDIA_null, "Undocumented instruction TRIMEDIA_null"),
	TO_ENUM(TRIMEDIA_igtri, "signed compare greater with immediate"),
	TO_ENUM(TRIMEDIA_igeqi, "signed compare greater or equal with immediate"),
	TO_ENUM(TRIMEDIA_ilesi, "signed compare less with immediate"),
	TO_ENUM(TRIMEDIA_ineqi, "signed compare not equal with immediate"),
	TO_ENUM(TRIMEDIA_ieqli, "signed compare equal with immediate"),
	TO_ENUM(TRIMEDIA_iaddi, "add with immediate"),
	TO_ENUM(TRIMEDIA_ild16d, "signed 16-bit load with displacement"),
	TO_ENUM(TRIMEDIA_ld32d, "32-bit load with displacement"),
	TO_ENUM(TRIMEDIA_uld8d, "unsigned 8-bit load with displacement"),
	TO_ENUM(TRIMEDIA_lsri, "logical shift right immediate"),
	TO_ENUM(TRIMEDIA_asri, "arithmetic shift right immediate"),
	TO_ENUM(TRIMEDIA_asli, "arithmetic shift left immediate"),
	TO_ENUM(TRIMEDIA_iadd, "signed add"),
	TO_ENUM(TRIMEDIA_isub, "signed subtract"),
	TO_ENUM(TRIMEDIA_igeq, "signed compare greater or equal"),
	TO_ENUM(TRIMEDIA_igtr, "signed compare greater"),
	TO_ENUM(TRIMEDIA_bitand, "bitwise logical AND"),
	TO_ENUM(TRIMEDIA_bitor, "bitwise logical OR"),
	TO_ENUM(TRIMEDIA_asr, "arithmetic shift right"),
	TO_ENUM(TRIMEDIA_asl, "arithmetic shift left"),
	TO_ENUM(TRIMEDIA_ifloat, "convert signed integer to floating-point"),
	TO_ENUM(TRIMEDIA_ifixrz, "convert floating-point to integer with round toward zero"),
	TO_ENUM(TRIMEDIA_fadd, "floating-point add"),
	TO_ENUM(TRIMEDIA_imin, "signed minimum"),
	TO_ENUM(TRIMEDIA_imax, "signed maximum"),
	TO_ENUM(TRIMEDIA_iavgonep, "signed average"),
	TO_ENUM(TRIMEDIA_ume8uu, "sum of absolute values of unsigned 8-bit differences"),
	TO_ENUM(TRIMEDIA_imul, "signed multiply"),
	TO_ENUM(TRIMEDIA_fmul, "floating-point multiply"),
	TO_ENUM(TRIMEDIA_h_st8d, "hardware 8-bit store with displacement"),
	TO_ENUM(TRIMEDIA_h_st16d, "hardware 16-bit store with displacement"),
	TO_ENUM(TRIMEDIA_h_st32d, "hardware 32-bit store with displacement"),
	TO_ENUM(TRIMEDIA_isubi, "subtract with immediate"),
	TO_ENUM(TRIMEDIA_ugtr, "unsigned compare greater"),
	TO_ENUM(TRIMEDIA_ugtri, "unsigned compare greater with immediate"),
	TO_ENUM(TRIMEDIA_ugeq, "unsigned compare greater or equal"),
	TO_ENUM(TRIMEDIA_ugeqi, "unsigned compare greater or equal with immediate"),
	TO_ENUM(TRIMEDIA_ieql, "signed compare equal"),
	TO_ENUM(TRIMEDIA_ueqli, "unsigned compare equal with immediate"),
	TO_ENUM(TRIMEDIA_ineq, "signed compare not equal"),
	TO_ENUM(TRIMEDIA_uneqi, "unsigned compare not equal"),
	TO_ENUM(TRIMEDIA_ulesi, "unsigned compare less with immediate"),
	TO_ENUM(TRIMEDIA_ileqi, "signed compare less or equal with immediate"),
	TO_ENUM(TRIMEDIA_uleqi, "unsigned compare less or equal with immediate"),
	TO_ENUM(TRIMEDIA_h_iabs, "hardware absolute value"),
	TO_ENUM(TRIMEDIA_carry, "compute carry bit from unsigned add"),
	TO_ENUM(TRIMEDIA_izero, "if zero select zero"),
	TO_ENUM(TRIMEDIA_inonzero, "if nonzero select zero"),
	TO_ENUM(TRIMEDIA_bitxor, "bitwise logical exclusive OR"),
	TO_ENUM(TRIMEDIA_bitandinv, "bitwise logical AND NOT"),
	TO_ENUM(TRIMEDIA_bitinv, "bitwise logical NOT"),
	TO_ENUM(TRIMEDIA_sex16, "sign extend 16 bits"),
	TO_ENUM(TRIMEDIA_packbytes, "pack least-significant bytes"),
	TO_ENUM(TRIMEDIA_pack16lsb, "pack least-significant 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_pack16msb, "pack most-significant 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_ubytesel, "select unsigned byte"),
	TO_ENUM(TRIMEDIA_ibytesel, "signed select byte"),
	TO_ENUM(TRIMEDIA_mergelsb, "merge least-significant byte"),
	TO_ENUM(TRIMEDIA_mergemsb, "merge most-significant byte"),
	TO_ENUM(TRIMEDIA_ume8ii, "unsigned sum of absolute values of signed 8-bit differences"),
	TO_ENUM(TRIMEDIA_h_dspiabs, "clipped signed absolute value"),
	TO_ENUM(TRIMEDIA_dspiadd, "clipped signed add"),
	TO_ENUM(TRIMEDIA_dspuadd, "clipped unsigned add"),
	TO_ENUM(TRIMEDIA_dspisub, "clipped signed subtract"),
	TO_ENUM(TRIMEDIA_dspusub, "clipped unsigned subtract"),
	TO_ENUM(TRIMEDIA_dspidualadd, "dual clipped add of signed 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_dspidualsub, "dual clipped subtract of signed 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_h_dspidualabs, "dual clipped absolute value of signed 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_quadavg, "unsigned byte-wise quad average"),
	TO_ENUM(TRIMEDIA_iclipi, "clip signed to signed"),
	TO_ENUM(TRIMEDIA_uclipi, "clip signed to unsigned"),
	TO_ENUM(TRIMEDIA_uclipu, "clip unsigned to unsigned"),
	TO_ENUM(TRIMEDIA_iflip, "if non-zero negate"),
	TO_ENUM(TRIMEDIA_dspuquadaddui, "quad clipped add of unsigned/signed bytes"),
	TO_ENUM(TRIMEDIA_quadumin, "unsigned byte-wise quad minimum"),
	TO_ENUM(TRIMEDIA_quadumax, "unsigned byte-wise quad maximum"),
	TO_ENUM(TRIMEDIA_dualiclipi, "dual-16 clip signed to signed"),
	TO_ENUM(TRIMEDIA_dualuclipi, "dual-16 clip signed to unsigned"),
	TO_ENUM(TRIMEDIA_quadumulmsb, "unsigned quad 8-bit multiply most significant"),
	TO_ENUM(TRIMEDIA_ufir8uu, "unsigned sum of products of unsigned bytes"),
	TO_ENUM(TRIMEDIA_ifir8ui, "signed sum of products of unsigned/signed bytes"),
	TO_ENUM(TRIMEDIA_ifir8ii, "signed sum of products of signed bytes"),
	TO_ENUM(TRIMEDIA_ifir16, "sum of products of signed 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_ufir16, "sum of products of unsigned 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_dspidualmul, "dual clipped multiply of signed 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_lsr, "logical shift right"),
	TO_ENUM(TRIMEDIA_rol, "rotate left"),
	TO_ENUM(TRIMEDIA_roli, "rotate left by immediate"),
	TO_ENUM(TRIMEDIA_funshift1, "funnel-shift 1 byte"),
	TO_ENUM(TRIMEDIA_funshift2, "funnel-shift 2 bytes"),
	TO_ENUM(TRIMEDIA_funshift3, "funnel-shift 3 bytes"),
	TO_ENUM(TRIMEDIA_dualasr, "dual-16 arithmetic shift right"),
	TO_ENUM(TRIMEDIA_mergedual16lsb, "merge dual 16-bit lsb bytes"),
	TO_ENUM(TRIMEDIA_fdiv, "floating-point divide"),
	TO_ENUM(TRIMEDIA_fdivflags, "IEEE status flags from floating-point divide"),
	TO_ENUM(TRIMEDIA_fsqrt, "floating-point square root"),
	TO_ENUM(TRIMEDIA_fsqrtflags, "IEEE status flags from floating-point square root"),
	TO_ENUM(TRIMEDIA_faddflags, "IEEE status flags from floating-point add"),
	TO_ENUM(TRIMEDIA_fsub, "floating-point subtract"),
	TO_ENUM(TRIMEDIA_fsubflags, "IEEE status flags from floating-point subtract"),
	TO_ENUM(TRIMEDIA_fabsval, "floating-point absolute value"),
	TO_ENUM(TRIMEDIA_fabsvalflags, "IEEE status flags from floating-point absolute value"),
	TO_ENUM(TRIMEDIA_ifloatrz, "convert signed integer to floating-point with rounding toward zero"),
	TO_ENUM(TRIMEDIA_ifloatrzflags, "IEEE status flags from convert signed integer to floating-point with rounding toward zero"),
	TO_ENUM(TRIMEDIA_ufloatrz, "convert unsigned integer to floating-point with round toward zero"),
	TO_ENUM(TRIMEDIA_ufloatrzflags, "IEEE status flags from convert unsigned integer to floating-point with round toward zero"),
	TO_ENUM(TRIMEDIA_ifixieee, "convert floating-point to integer using PCSW rounding mode"),
	TO_ENUM(TRIMEDIA_ifixieeeflags, "IEEE status flags from convert floating-point to integer using PCSW rounding mode"),
	TO_ENUM(TRIMEDIA_ufixieee, "convert floating-point to unsigned integer using PCSW rounding mode"),
	TO_ENUM(TRIMEDIA_ufixieeeflags, "IEEE status flags from convert floating-point to unsigned integer using PCSW rounding mode"),
	TO_ENUM(TRIMEDIA_ufixrz, "convert floating-point to unsigned integer with round toward zero"),
	TO_ENUM(TRIMEDIA_ufixrzflags, "IEEE status flags from convert floating-point to unsigned integer with round toward zero"),
	TO_ENUM(TRIMEDIA_ufloat, "convert unsigned integer to floating-point"),
	TO_ENUM(TRIMEDIA_ufloatflags, "IEEE status flags from convert unsigned integer to floating-point"),
	TO_ENUM(TRIMEDIA_ifixrzflags, "IEEE status flags from convert floating-point to integer with round toward zero"),
	TO_ENUM(TRIMEDIA_ifloatflags, "IEEE status flags from convert signed integer to floating-point"),
	TO_ENUM(TRIMEDIA_umul, "unsigned multiply"),
	TO_ENUM(TRIMEDIA_imulm, "signed multiply, return most-significant 32 bits"),
	TO_ENUM(TRIMEDIA_umulm, "unsigned multiply, return most-significant 32 bits"),
	TO_ENUM(TRIMEDIA_dspimul, "clipped signed multiply"),
	TO_ENUM(TRIMEDIA_dspumul, "clipped unsigned multiply"),
	TO_ENUM(TRIMEDIA_fmulflags, "IEEE status flags from floating-point multiply"),
	TO_ENUM(TRIMEDIA_fgtr, "floating-point compare greater"),
	TO_ENUM(TRIMEDIA_fgtrflags, "IEEE status flags from floating-point compare greater"),
	TO_ENUM(TRIMEDIA_fgeq, "floating-point compare greater or equal"),
	TO_ENUM(TRIMEDIA_fgeqflags, "IEEE status flags from floating-point compare greater or equal"),
	TO_ENUM(TRIMEDIA_feql, "floating-point compare equal"),
	TO_ENUM(TRIMEDIA_feqlflags, "IEEE status flags from floating-point compare equal"),
	TO_ENUM(TRIMEDIA_fneq, "floating-point compare not equal"),
	TO_ENUM(TRIMEDIA_fneqflags, "IEEE status flags from floating-point compare not equal"),
	TO_ENUM(TRIMEDIA_fsign, "sign of floating-point value"),
	TO_ENUM(TRIMEDIA_fsignflags, "IEEE status flags from floating-point sign"),
	TO_ENUM(TRIMEDIA_cycles, "read clock cycle counter, least-significant word"),
	TO_ENUM(TRIMEDIA_hicycles, "read clock cycle counter, most-significant word"),
	TO_ENUM(TRIMEDIA_readdpc, "read destination program counter"),
	TO_ENUM(TRIMEDIA_readspc, "read source program counter"),
	TO_ENUM(TRIMEDIA_readpcsw, "read program control and status word"),
	TO_ENUM(TRIMEDIA_writespc, "write source program counter"),
	TO_ENUM(TRIMEDIA_writedpc, "write destination program counter"),
	TO_ENUM(TRIMEDIA_writepcsw, "write program control and status word"),
	TO_ENUM(TRIMEDIA_curcycles, "read current clock cycle, least-significant word"),
	TO_ENUM(TRIMEDIA_jmpt, "indirect jump on true"),
	TO_ENUM(TRIMEDIA_ijmpt, "interruptible indirect jump on true"),
	TO_ENUM(TRIMEDIA_jmpi, "jump immediate"),
	TO_ENUM(TRIMEDIA_ijmpi, "interruptible jump immediate"),
	TO_ENUM(TRIMEDIA_jmpf, "indirect jump on false"),
	TO_ENUM(TRIMEDIA_ijmpf, "interruptible indirect jump on false"),
	TO_ENUM(TRIMEDIA_iclr, "invalidate all instruction cache blocks"),
	TO_ENUM(TRIMEDIA_uimm, "unsigned immediate"),
	TO_ENUM(TRIMEDIA_ild8d, "signed 8-bit load with displacement"),
	TO_ENUM(TRIMEDIA_ild8r, "signed 8-bit load with index"),
	TO_ENUM(TRIMEDIA_uld8r, "unsigned 8-bit load with index"),
	TO_ENUM(TRIMEDIA_ild16r, "signed 16-bit load with index"),
	TO_ENUM(TRIMEDIA_ild16x, "signed 16-bit load with scaled index"),
	TO_ENUM(TRIMEDIA_uld16d, "unsigned 16-bit load with displacement"),
	TO_ENUM(TRIMEDIA_uld16r, "unsigned 16-bit load with index"),
	TO_ENUM(TRIMEDIA_uld16x, "unsigned 16-bit load with scaled index"),
	TO_ENUM(TRIMEDIA_ld32r, "32-bit load with index"),
	TO_ENUM(TRIMEDIA_ld32x, "32-bit load with scaled index"),
	TO_ENUM(TRIMEDIA_rdtag, "read data cache address tag"),
	TO_ENUM(TRIMEDIA_rdstatus, "read data cache status bits"),
	TO_ENUM(TRIMEDIA_dcb, "data cache copy back"),
	TO_ENUM(TRIMEDIA_dinvalid, "invalidate data cache block"),
	TO_ENUM(TRIMEDIA_prefd, "prefetch with displacement"),
	TO_ENUM(TRIMEDIA_prefr, "prefetch with index"),
	TO_ENUM(TRIMEDIA_pref16x, "prefetch with 16-bit scaled index"),
	TO_ENUM(TRIMEDIA_pref32x, "prefetch with 32-bit scaled index"),
	TO_ENUM(TRIMEDIA_allocd, "allocate a cache block with displacement"),
	TO_ENUM(TRIMEDIA_allocr, "allocate a cache block with index"),
	TO_ENUM(TRIMEDIA_allocx, "allocate a cache block with scaled index"),
	TO_ENUM(TRIMEDIA_nop, "Undocumented instruction TRIMEDIA_nop"),
	TO_ENUM(TRIMEDIA_alloc, "allocate a cache block"),
	TO_ENUM(TRIMEDIA_dspiabs, "clipped signed absolute value"),
	TO_ENUM(TRIMEDIA_dspidualabs, "dual clipped absolute value of signed 16-bit halfwords"),
	TO_ENUM(TRIMEDIA_iabs, "absolute value"),
	TO_ENUM(TRIMEDIA_ild16, "signed 16-bit load"),
	TO_ENUM(TRIMEDIA_ild8, "signed 8-bit load"),
	TO_ENUM(TRIMEDIA_ineg, "signed negate"),
	TO_ENUM(TRIMEDIA_ld32, "32-bit load"),
	TO_ENUM(TRIMEDIA_pref, "prefetch"),
	TO_ENUM(TRIMEDIA_sex8, "sign extend 8 bits"),
	TO_ENUM(TRIMEDIA_st16, "16-bit store"),
	TO_ENUM(TRIMEDIA_st16d, "16-bit store with displacement"),
	TO_ENUM(TRIMEDIA_st32, "32-bit store"),
	TO_ENUM(TRIMEDIA_st32d, "32-bit store with displacement"),
	TO_ENUM(TRIMEDIA_st8, "8-bit store"),
	TO_ENUM(TRIMEDIA_st8d, "8-bit store with displacement"),
	TO_ENUM(TRIMEDIA_uld16, "unsigned 16-bit load"),
	TO_ENUM(TRIMEDIA_uld8, "unsigned 8-bit load"),
	TO_ENUM(TRIMEDIA_zex16, "zero extend 16 bits"),
	TO_ENUM(TRIMEDIA_zex8, "zero extend 8 bits"),
	TO_ENUM(TRIMEDIA_ident, "identity"),
	TO_ENUM(TRIMEDIA_iles, "Undocumented instruction TRIMEDIA_iles"),
	TO_ENUM(TRIMEDIA_ileq, "Undocumented instruction TRIMEDIA_ileq"),
	TO_ENUM(TRIMEDIA_ules, "Undocumented instruction TRIMEDIA_ules"),
	TO_ENUM(TRIMEDIA_uleq, "Undocumented instruction TRIMEDIA_uleq"),
	TO_ENUM(TRIMEDIA_fles, "Undocumented instruction TRIMEDIA_fles"),
	TO_ENUM(TRIMEDIA_fleq, "Undocumented instruction TRIMEDIA_fleq"),
	TO_ENUM(TRIMEDIA_ueql, "Undocumented instruction TRIMEDIA_ueql"),
	TO_ENUM(TRIMEDIA_uneq, "Undocumented instruction TRIMEDIA_uneq"),
	TO_ENUM(TRIMEDIA_flesflags, "Undocumented instruction TRIMEDIA_flesflags"),
	TO_ENUM(TRIMEDIA_fleqflags, "Undocumented instruction TRIMEDIA_fleqflags"),
	TO_ENUM(TRIMEDIA_borrow, "Undocumented instruction TRIMEDIA_borrow"),
	TO_ENUM(TRIMEDIA_umin, "Undocumented instruction TRIMEDIA_umin"),
	TO_ENUM(TRIMEDIA_lsl, "Undocumented instruction TRIMEDIA_lsl"),
	TO_ENUM(TRIMEDIA_lsli, "Undocumented instruction TRIMEDIA_lsli"),
	TO_ENUM(TRIMEDIA_last, "Undocumented instruction TRIMEDIA_last")
};
