auto instructions_PLFM_DSP56K = flags_vector_t{
	TO_ENUM(DSP56_null, "Undocumented instruction DSP56_null"),
	TO_ENUM(DSP56_abs, "Absolute Value"),
	TO_ENUM(DSP56_adc, "Add Long with Carry"),
	TO_ENUM(DSP56_add, "Addition"),
	TO_ENUM(DSP56_addl, "Shift Left and Add"),
	TO_ENUM(DSP56_addr, "Shift Right and Add"),
	TO_ENUM(DSP56_and, "Logical AND"),
	TO_ENUM(DSP56_andi, "AND Immediate to Control Register"),
	TO_ENUM(DSP56_asl, "Arithmetic Shift Left"),
	TO_ENUM(DSP56_asl4, "Arithmetic Shift Left 4"),
	TO_ENUM(DSP56_asr, "Arithmetic Shift Right"),
	TO_ENUM(DSP56_asr4, "Arithmetic Shift Right 4"),
	TO_ENUM(DSP56_asr16, "Arithmetic Shift Right 16"),
	TO_ENUM(DSP56_bfchg, "Test Bit Field and Change"),
	TO_ENUM(DSP56_bfclr, "Clear Bit Field"),
	TO_ENUM(DSP56_bfset, "Set Bit Field"),
	TO_ENUM(DSP56_bftsth, "Test Bit Field High"),
	TO_ENUM(DSP56_bftstl, "Test Bit Field Low"),
	TO_ENUM(DSP56_bcc, "Branch Conditionaly"),
	TO_ENUM(DSP56_bchg, "Bit Test and Change"),
	TO_ENUM(DSP56_bclr, "Bit Test and Clear"),
	TO_ENUM(DSP56_bra, "Branch Always"),
	TO_ENUM(DSP56_brclr, "Branch if Bit Clear"),
	TO_ENUM(DSP56_brkcc, "Exit Current DO Loop Conditionally"),
	TO_ENUM(DSP56_brset, "Branch if Bit Set"),
	TO_ENUM(DSP56_bscc, "Branch to Subroutine Conditionaly"),
	TO_ENUM(DSP56_bsclr, "Branch to Subroutine if Bit Clear"),
	TO_ENUM(DSP56_bset, "Bit Test and Set"),
	TO_ENUM(DSP56_bsr, "Branch to Subroutine"),
	TO_ENUM(DSP56_bsset, "Branch to Subroutine if Bit Set"),
	TO_ENUM(DSP56_btst, "Bit Test on Memory and Registers"),
	TO_ENUM(DSP56_chkaau, "Check address ALU result"),
	TO_ENUM(DSP56_clb, "Count Leading Bits"),
	TO_ENUM(DSP56_clr, "Clear an Operand"),
	TO_ENUM(DSP56_clr24, "Clear 24 MS-bits of Accumulator"),
	TO_ENUM(DSP56_cmp, "Compare"),
	TO_ENUM(DSP56_cmpm, "Compare Magnitude"),
	TO_ENUM(DSP56_cmpu, "Compare Unsigned"),
	TO_ENUM(DSP56_debug, "Enter Debug Mode"),
	TO_ENUM(DSP56_debugcc, "Enter Debug Mode Conditionally"),
	TO_ENUM(DSP56_dec, "Decrement by One"),
	TO_ENUM(DSP56_dec24, "Decrement 24 MS-bit of Accumulator"),
	TO_ENUM(DSP56_div, "Divide Iteration"),
	TO_ENUM(DSP56_dmac, "Double-Precision Multiply-Accumulate With Right Shift"),
	TO_ENUM(DSP56_do, "Start Hardware Loop"),
	TO_ENUM(DSP56_do_f, "Start Infinite Loop"),
	TO_ENUM(DSP56_dor, "Start PC-Relative Hardware Loop"),
	TO_ENUM(DSP56_dor_f, "Start PC-Relative Infinite Loop"),
	TO_ENUM(DSP56_enddo, "Exit from Hardware Loop"),
	TO_ENUM(DSP56_eor, "Logical Exclusive OR"),
	TO_ENUM(DSP56_extract, "Extract Bit Field"),
	TO_ENUM(DSP56_extractu, "Extract Unsigned Bit Field"),
	TO_ENUM(DSP56_ext, "Sign Extend Accumulator"),
	TO_ENUM(DSP56_ill, "Illegal Instruction"),
	TO_ENUM(DSP56_imac, "Integer Multiply-Accumulate"),
	TO_ENUM(DSP56_impy, "Integer Multiply"),
	TO_ENUM(DSP56_inc, "Increment by One"),
	TO_ENUM(DSP56_inc24, "Increment 24 MS-bit of Accumulator"),
	TO_ENUM(DSP56_insert, "Insert Bit Field"),
	TO_ENUM(DSP56_jcc, "Jump Conditionally"),
	TO_ENUM(DSP56_jclr, "Jump if Bit Clear"),
	TO_ENUM(DSP56_jmp, "Jump"),
	TO_ENUM(DSP56_jscc, "Jump to Subroutine Conditionally"),
	TO_ENUM(DSP56_jsclr, "Jump to Subroutine if Bit Clear"),
	TO_ENUM(DSP56_jset, "Jump if Bit Set"),
	TO_ENUM(DSP56_jsr, "Jump to Subroutine"),
	TO_ENUM(DSP56_jsset, "Jump to Subroutine if Bit Set"),
	TO_ENUM(DSP56_lra, "Load PC-Reliative Address"),
	TO_ENUM(DSP56_lsl, "Logical Shift Left"),
	TO_ENUM(DSP56_lsr, "Logical Shift Right"),
	TO_ENUM(DSP56_lua, "Load Updated Address"),
	TO_ENUM(DSP56_lea, "Load Updated Address"),
	TO_ENUM(DSP56_mac, "Signed Multiply-Accumulate"),
	TO_ENUM(DSP56_maci, "Signed Multiply-Accumulate With Immediate Operand"),
	TO_ENUM(DSP56_mac_s_u, "Mixed Multiply-Accumulate"),
	TO_ENUM(DSP56_macr, "Signed Multiply-Accumulate and Round"),
	TO_ENUM(DSP56_macri, "Signed Multiply-Accumulate and Round With Immediate Operand"),
	TO_ENUM(DSP56_max, "Transfer by Signed Value"),
	TO_ENUM(DSP56_maxm, "Transfer by Magnitude"),
	TO_ENUM(DSP56_merge, "Merge Two Half Words"),
	TO_ENUM(DSP56_move, "Move Data"),
	TO_ENUM(DSP56_movec, "Move Control Register"),
	TO_ENUM(DSP56_movei, "Move Immediate Short"),
	TO_ENUM(DSP56_movem, "Move Program Memory"),
	TO_ENUM(DSP56_movep, "Move Peripheral Data"),
	TO_ENUM(DSP56_moves, "Move Absolute Short"),
	TO_ENUM(DSP56_mpy, "Signed Multiply"),
	TO_ENUM(DSP56_mpyi, "Signed Multiply With Immediate Operand"),
	TO_ENUM(DSP56_mpy_s_u, "Mixed Multiply"),
	TO_ENUM(DSP56_mpyr, "Signed Multiply and Round"),
	TO_ENUM(DSP56_mpyri, "Signed Multiply and Round With Immediate Operand"),
	TO_ENUM(DSP56_neg, "Negate Accumulator"),
	TO_ENUM(DSP56_negc, "Negate Accumulator"),
	TO_ENUM(DSP56_nop, "No Operation"),
	TO_ENUM(DSP56_norm, "Norm Accumulator Iteration"),
	TO_ENUM(DSP56_normf, "Fast Accumulator Normalization"),
	TO_ENUM(DSP56_not, "Logical Complement"),
	TO_ENUM(DSP56_or, "Logical Inclusive OR"),
	TO_ENUM(DSP56_ori, "OR Immediate to Control Register"),
	TO_ENUM(DSP56_pflush, "Program Cache Flush"),
	TO_ENUM(DSP56_pflushun, "Program Cache Flush Unlocked Sectors"),
	TO_ENUM(DSP56_pfree, "Program Cache Global Unlock"),
	TO_ENUM(DSP56_plock, "Lock Instruction Cache Sector"),
	TO_ENUM(DSP56_plockr, "Lock Instruction Cache Relative Sector"),
	TO_ENUM(DSP56_punlock, "Unlock Instruction Cache Sector"),
	TO_ENUM(DSP56_punlockr, "Unlock Instruction Cache Relative Sector"),
	TO_ENUM(DSP56_rep, "Repeat Next Instruction"),
	TO_ENUM(DSP56_repcc, "Repeat Next Instruction"),
	TO_ENUM(DSP56_reset, "Reset On-Chip Peripheral Devices"),
	TO_ENUM(DSP56_rnd, "Round Accumulator"),
	TO_ENUM(DSP56_rol, "Rotate Left"),
	TO_ENUM(DSP56_ror, "Rotate Right"),
	TO_ENUM(DSP56_rti, "Return from Interrupt"),
	TO_ENUM(DSP56_rts, "Return from Subroutine"),
	TO_ENUM(DSP56_sbc, "Subtract Long with Carry"),
	TO_ENUM(DSP56_stop, "Stop Processing (Low-Power Standby)"),
	TO_ENUM(DSP56_sub, "Subtract"),
	TO_ENUM(DSP56_subl, "Shift Left and Subtract"),
	TO_ENUM(DSP56_subr, "Shift Right and Subtract"),
	TO_ENUM(DSP56_swap, "Swap Accumulator Words"),
	TO_ENUM(DSP56_tcc, "Transfer Conditionally"),
	TO_ENUM(DSP56_tfr, "Transfer Data ALU Register"),
	TO_ENUM(DSP56_tfr2, "Transfer Data ALU Register"),
	TO_ENUM(DSP56_tfr3, "Transfer Data ALU Register"),
	TO_ENUM(DSP56_trap, "Software Interrupt"),
	TO_ENUM(DSP56_trapcc, "Software Interrupt Conditionally"),
	TO_ENUM(DSP56_tst, "Test an Operand"),
	TO_ENUM(DSP56_tst2, "Test an Operand"),
	TO_ENUM(DSP56_vsl, "Viterbi Shift Left"),
	TO_ENUM(DSP56_wait, "Wait for Interrupt or DMA Request (Low-Power Standby)"),
	TO_ENUM(DSP56_zero, "Zero Extend Accumulator"),
	TO_ENUM(DSP56_swi, "Software Interrupt (only for 56000)"),
	TO_ENUM(DSP56_pmov, "Pseudo insn"),
	TO_ENUM(DSP56_last, "Undocumented instruction DSP56_last")
};
