auto instructions_PLFM_PIC16 = flags_vector_t{
	TO_ENUM(PIC16_null, "Undocumented instruction PIC16_null"),
	TO_ENUM(PIC16_EXCH, "Exchange Wns and Wnd"),
	TO_ENUM(PIC16_MOV, "Move"),
	TO_ENUM(PIC16_SWAP, "Byte or Nibble Swap Wn"),
	TO_ENUM(PIC16_TBLRDH, "Table Read High"),
	TO_ENUM(PIC16_TBLRDL, "Table Read Low"),
	TO_ENUM(PIC16_TBLWTH, "Table Write High"),
	TO_ENUM(PIC16_TBLWTL, "Table Write Low"),
	TO_ENUM(PIC16_MOVPAG, "Move to Page Register"),
	TO_ENUM(PIC16_ADD, "Add"),
	TO_ENUM(PIC16_ADDC, "Add with carry"),
	TO_ENUM(PIC16_DAWB, "Decimal Adjust Wn"),
	TO_ENUM(PIC16_DEC, "Decrement"),
	TO_ENUM(PIC16_DEC2, "Decrement by 2"),
	TO_ENUM(PIC16_DIV, "Signed/Unsigned Integer Divide"),
	TO_ENUM(PIC16_INC, "Increment"),
	TO_ENUM(PIC16_INC2, "Increment by 2"),
	TO_ENUM(PIC16_MUL, "Integer Multiply"),
	TO_ENUM(PIC16_SE, "Sign-Extend Ws"),
	TO_ENUM(PIC16_SUB, "Subtract"),
	TO_ENUM(PIC16_SUBB, "Subtract with Borrow"),
	TO_ENUM(PIC16_SUBBR, "Subtract with Borrow"),
	TO_ENUM(PIC16_SUBR, "Subtract"),
	TO_ENUM(PIC16_ZE, "Zero - Extend Ws"),
	TO_ENUM(PIC16_MULW, "Integer Multiply with 16-bit Result"),
	TO_ENUM(PIC16_DIVF, "Fractional Divide"),
	TO_ENUM(PIC16_AND, "AND"),
	TO_ENUM(PIC16_CLR, "Clear f or WREG | Clear Wd"),
	TO_ENUM(PIC16_COM, "Complement f | Complement Ws"),
	TO_ENUM(PIC16_IOR, "Inclusive OR"),
	TO_ENUM(PIC16_NEG, "Negate f | Negate Ws"),
	TO_ENUM(PIC16_SETM, "Set f or WREG | Set Ws"),
	TO_ENUM(PIC16_XOR, "Exclusive OR"),
	TO_ENUM(PIC16_ASR, "Arithmetic Shift Right"),
	TO_ENUM(PIC16_LSR, "Logical Shift Right"),
	TO_ENUM(PIC16_RLC, "Rotate Left through Carry"),
	TO_ENUM(PIC16_RLNC, "Rotate Left without Carry"),
	TO_ENUM(PIC16_RRC, "Rotate Right through Carry"),
	TO_ENUM(PIC16_RRNC, "Rotate Right without Carry"),
	TO_ENUM(PIC16_SL, "Shift Left"),
	TO_ENUM(PIC16_BCLR, "Bit Clear f | Bit Clear in Ws"),
	TO_ENUM(PIC16_BSET, "Bit Set f | Bit Set in Ws"),
	TO_ENUM(PIC16_BSW, "Bit Write in Ws"),
	TO_ENUM(PIC16_BTG, "Bit Toggle f | Bit Toggle in Ws"),
	TO_ENUM(PIC16_BTST, "Bit Test f | Bit Test in Ws"),
	TO_ENUM(PIC16_BTSTS, "Bit Test/Set f | Bit Test/Set in Ws"),
	TO_ENUM(PIC16_FBCL, "Find First Bit Change from Left"),
	TO_ENUM(PIC16_FF1L, "Find First One from Left"),
	TO_ENUM(PIC16_FF1R, "Find First One from Right"),
	TO_ENUM(PIC16_BTSC, "Bit Test, Skip if Clear"),
	TO_ENUM(PIC16_BTSS, "Bit Test, Skip if Set"),
	TO_ENUM(PIC16_CP, "Compare, Set Status Flags"),
	TO_ENUM(PIC16_CP0, "Compare, Set Status Flags"),
	TO_ENUM(PIC16_CPB, "Compare using Borrow, set Status Flags"),
	TO_ENUM(PIC16_CPSEQ, "Compare Wb with Wn, Skip if Equal (Wb = Wn)"),
	TO_ENUM(PIC16_CPSGT, "Signed Compare Wb with Wn, Skip if Greater Than (Wb > Wn)"),
	TO_ENUM(PIC16_CPSLT, "Signed Compare Wb with Wn, Skip if Less Than (Wb < Wn)"),
	TO_ENUM(PIC16_CPSNE, "Signed Compare Wb with Wn, Skip if Not Equal (Wb != Wn)"),
	TO_ENUM(PIC16_CPBEQ, "Compare Wb with Wn, branch if ="),
	TO_ENUM(PIC16_CPBNE, "Compare Wb with Wn, Branch if Not Equal (Wb != Wn)"),
	TO_ENUM(PIC16_CPBGT, "Signed Compare Wb with Wn, Branch if Greater Than (Wb > Wn)"),
	TO_ENUM(PIC16_CPBLT, "Signed Compare Wb with Wn, Branch if Less Than (Wb < Wn)"),
	TO_ENUM(PIC16_BRA, "Branch unconditionally/conditionally"),
	TO_ENUM(PIC16_CALL, "Call Subroutine | Call Indirect Subroutine"),
	TO_ENUM(PIC16_GOTO, "Unconditional Jump"),
	TO_ENUM(PIC16_RCALL, "Relative Call | Relative Call"),
	TO_ENUM(PIC16_REPEAT, "Repeat next instruction"),
	TO_ENUM(PIC16_RETFIE, "Return from Interrupt"),
	TO_ENUM(PIC16_RETLW, "Return with Literal in Wn"),
	TO_ENUM(PIC16_RETURN, "Return"),
	TO_ENUM(PIC16_DO, "Initialize Hardware Loop"),
	TO_ENUM(PIC16_LNK, "Allocate Stack Frame"),
	TO_ENUM(PIC16_POP, "Pop TOS | Pop Shadow Registers"),
	TO_ENUM(PIC16_PUSH, "Push to TOS | Push Shadow Registers"),
	TO_ENUM(PIC16_ULNK, "De-allocate Stack Frame"),
	TO_ENUM(PIC16_CLRWDT, "Clear Watchdog Timer"),
	TO_ENUM(PIC16_DISI, "Disable Interrupts Temporarily"),
	TO_ENUM(PIC16_NOP, "No operation"),
	TO_ENUM(PIC16_NOPR, "No operation"),
	TO_ENUM(PIC16_PWRSAV, "Enter Power Saving Mode"),
	TO_ENUM(PIC16_RESET, "Reset"),
	TO_ENUM(PIC16_LAC, "Load Accumulator"),
	TO_ENUM(PIC16_SAC, "Store Accumulator"),
	TO_ENUM(PIC16_SFTAC, "Arithmetic Shift Accumulator"),
	TO_ENUM(PIC16_CLR1, "Clear Accumulator, Prefetch Operands"),
	TO_ENUM(PIC16_ED, "Euclidean Distance (No Accumulate)"),
	TO_ENUM(PIC16_EDAC, "Euclidean Distance"),
	TO_ENUM(PIC16_MAC, "Multiply and Accumulate"),
	TO_ENUM(PIC16_MOVSAC, "Prefetch Operands and Store Accumulator"),
	TO_ENUM(PIC16_MPY, "Multiply to Accumulator"),
	TO_ENUM(PIC16_MSC, "Multiply and Subtract from Accumulator"),
	TO_ENUM(PIC16_BREAK, "ICD Break"),
	TO_ENUM(PIC16_URUN, "ICD Run"),
	TO_ENUM(PIC16_SSTEP, "ICD Single Step"),
	TO_ENUM(PIC16_FEX, "ICD Execute"),
	TO_ENUM(PIC16_last, "Undocumented instruction PIC16_last")
};
