auto instructions_PLFM_Z8 = flags_vector_t{
	TO_ENUM(Z8_null, "Undocumented instruction Z8_null"),
	TO_ENUM(Z8_adc, "Add with carry"),
	TO_ENUM(Z8_add, "Add"),
	TO_ENUM(Z8_and, "Logical AND"),
	TO_ENUM(Z8_call, "Call procedure"),
	TO_ENUM(Z8_ccf, "Complement carry flag"),
	TO_ENUM(Z8_clr, "Clear"),
	TO_ENUM(Z8_com, "Complement"),
	TO_ENUM(Z8_cp, "Compare"),
	TO_ENUM(Z8_da, "Decimal adjust"),
	TO_ENUM(Z8_dec, "Decrement"),
	TO_ENUM(Z8_decw, "Decrement word"),
	TO_ENUM(Z8_di, "Disable interrupts"),
	TO_ENUM(Z8_djnz, "Decrement and jump if non-zero"),
	TO_ENUM(Z8_ei, "Enable interrupts"),
	TO_ENUM(Z8_halt, "Enter HALT mode"),
	TO_ENUM(Z8_inc, "Increment"),
	TO_ENUM(Z8_incw, "Increment word"),
	TO_ENUM(Z8_iret, "Return from interrupt"),
	TO_ENUM(Z8_jp, "Unconditional jump"),
	TO_ENUM(Z8_jpcond, "Conditional jump"),
	TO_ENUM(Z8_jr, "Relative jump"),
	TO_ENUM(Z8_jrcond, "Conditional relative jump"),
	TO_ENUM(Z8_ld, "Load data"),
	TO_ENUM(Z8_ldc, "Load constant"),
	TO_ENUM(Z8_ldci, "Load constant with auto-increment"),
	TO_ENUM(Z8_lde, "Load external data"),
	TO_ENUM(Z8_ldei, "Load external data with auto-increment"),
	TO_ENUM(Z8_nop, "NOP"),
	TO_ENUM(Z8_or, "Logical OR"),
	TO_ENUM(Z8_pop, "Pop"),
	TO_ENUM(Z8_push, "Push"),
	TO_ENUM(Z8_rcf, "Reset carry flag"),
	TO_ENUM(Z8_ret, "Return"),
	TO_ENUM(Z8_rl, "Rotate left"),
	TO_ENUM(Z8_rlc, "Rotate left through carry"),
	TO_ENUM(Z8_rr, "Rotate right"),
	TO_ENUM(Z8_rrc, "Rotate right through carry"),
	TO_ENUM(Z8_sbc, "Subtract with carry"),
	TO_ENUM(Z8_scf, "Set carry flag"),
	TO_ENUM(Z8_sra, "Shift right arithmetic"),
	TO_ENUM(Z8_srp, "Set register pointer"),
	TO_ENUM(Z8_stop, "Enter STOP mode"),
	TO_ENUM(Z8_sub, "Subtract"),
	TO_ENUM(Z8_swap, "Swap nibbles"),
	TO_ENUM(Z8_tm, "Test under mask"),
	TO_ENUM(Z8_tcm, "Test complement under mask"),
	TO_ENUM(Z8_xor, "Logical EXCLUSIVE OR"),
	TO_ENUM(Z8_wdh, "Enable WATCH-DOG in HALT mode"),
	TO_ENUM(Z8_wdt, "Clear WATCH-DOG timer"),
	TO_ENUM(Z8_last, "Undocumented instruction Z8_last")
};
