auto instructions_PLFM_UNSP = flags_vector_t{
	TO_ENUM(UNSP_null, "Undocumented instruction UNSP_null"),
	TO_ENUM(UNSP_add, "Add"),
	TO_ENUM(UNSP_adc, "Add with Carry"),
	TO_ENUM(UNSP_sub, "Subtract"),
	TO_ENUM(UNSP_sbc, "Subtract with Carry"),
	TO_ENUM(UNSP_cmp, "Compare"),
	TO_ENUM(UNSP_cmpc, "Compare with Carry?"),
	TO_ENUM(UNSP_neg, "Negate"),
	TO_ENUM(UNSP_negc, "Negate with Carry?"),
	TO_ENUM(UNSP_xor, "Exclusive-OR"),
	TO_ENUM(UNSP_load, "Load"),
	TO_ENUM(UNSP_or, "OR"),
	TO_ENUM(UNSP_and, "AND"),
	TO_ENUM(UNSP_test, "Test"),
	TO_ENUM(UNSP_store, "Store"),
	TO_ENUM(UNSP_add_s, "Add (Simple)"),
	TO_ENUM(UNSP_adc_s, "Add with Carry (Simple)"),
	TO_ENUM(UNSP_sub_s, "Subtract (Simple)"),
	TO_ENUM(UNSP_sbc_s, "Subtract with Carry (Simple)"),
	TO_ENUM(UNSP_cmp_s, "Compare (Simple)"),
	TO_ENUM(UNSP_cmpc_s, "Compare with Carry? (Simple)"),
	TO_ENUM(UNSP_neg_s, "Negate (Simple)"),
	TO_ENUM(UNSP_negc_s, "Negate with Carry? (Simple)"),
	TO_ENUM(UNSP_xor_s, "Exclusive-OR (Simple)"),
	TO_ENUM(UNSP_load_s, "Load (Simple)"),
	TO_ENUM(UNSP_or_s, "OR (Simple)"),
	TO_ENUM(UNSP_and_s, "AND (Simple)"),
	TO_ENUM(UNSP_test_s, "Test (Simple)"),
	TO_ENUM(UNSP_store_s, "Store (Simple)"),
	TO_ENUM(UNSP_retf, "Return Function"),
	TO_ENUM(UNSP_reti, "Return Interrupt"),
	TO_ENUM(UNSP_pop, "Pop from Stack"),
	TO_ENUM(UNSP_push, "Push to Stack"),
	TO_ENUM(UNSP_call, "Call"),
	TO_ENUM(UNSP_goto, "Goto (far jump)"),
	TO_ENUM(UNSP_nop, "NOP"),
	TO_ENUM(UNSP_exp, "Effective Exponent"),
	TO_ENUM(UNSP_jb, "Jump if Below (unsigned) [jcc, jnae]"),
	TO_ENUM(UNSP_jae, "Jump if Above or Equal (unsigned) [jcs, jnb]"),
	TO_ENUM(UNSP_jge, "Jump if Greater or Equal (signed) [jsc, jnl]"),
	TO_ENUM(UNSP_jl, "Jump if Less (signed) [jss, jnge]"),
	TO_ENUM(UNSP_jne, "Jump if Not Equal [jnz]"),
	TO_ENUM(UNSP_je, "Jump if Equal [jz]"),
	TO_ENUM(UNSP_jpl, "Jump if Positive"),
	TO_ENUM(UNSP_jmi, "Jump if Negative"),
	TO_ENUM(UNSP_jbe, "Jump if Below or Equal (unsigned) [jna]"),
	TO_ENUM(UNSP_ja, "Jump if Above (unsigned) [jnbe]"),
	TO_ENUM(UNSP_jle, "Jump if Less or Equal (signed) [jng]"),
	TO_ENUM(UNSP_jg, "Jump if Greater (signed) [jnle]"),
	TO_ENUM(UNSP_jvc, "Jump if Not Overflow"),
	TO_ENUM(UNSP_jvs, "Jump if Overflow"),
	TO_ENUM(UNSP_jmp, "Jump"),
	TO_ENUM(UNSP_mulss, "Multiply Signed * Signed"),
	TO_ENUM(UNSP_mulus, "Multiply Unsigned * Signed"),
	TO_ENUM(UNSP_muluu, "Multiply Unsigned * Unsigned"),
	TO_ENUM(UNSP_divs, "Divide (Sign)"),
	TO_ENUM(UNSP_divq, "Divide (Quotient)"),
	TO_ENUM(UNSP_int1, "Interrupt flags"),
	TO_ENUM(UNSP_int2, "Interrupt flags"),
	TO_ENUM(UNSP_fir_mov, "FIR_MOV setting"),
	TO_ENUM(UNSP_fraction, "FRACTION setting"),
	TO_ENUM(UNSP_irq, "IRQ setting"),
	TO_ENUM(UNSP_secbank, "SECBANK setting"),
	TO_ENUM(UNSP_fiq, "FIQ setting"),
	TO_ENUM(UNSP_irqnest, "IRQNEST setting"),
	TO_ENUM(UNSP_break, "BREAK"),
	TO_ENUM(UNSP_asr, "Arithmetic shift right"),
	TO_ENUM(UNSP_asror, "Arithmetic shift right OR"),
	TO_ENUM(UNSP_lsl, "Logical shift left"),
	TO_ENUM(UNSP_lslor, "Logical shift left OR"),
	TO_ENUM(UNSP_lsr, "Logical shift right"),
	TO_ENUM(UNSP_lsror, "Logical shift right OR"),
	TO_ENUM(UNSP_rol, "Rotate left"),
	TO_ENUM(UNSP_ror, "Rotate right"),
	TO_ENUM(UNSP_tstb, "Test bit"),
	TO_ENUM(UNSP_setb, "Set bit"),
	TO_ENUM(UNSP_clrb, "Clear bit"),
	TO_ENUM(UNSP_invb, "Invert bit"),
	TO_ENUM(UNSP_last, "Undocumented instruction UNSP_last")
};
