auto instructions_PLFM_PIC = flags_vector_t{
	TO_ENUM(PIC_null, "Undocumented instruction PIC_null"),
	TO_ENUM(PIC_addwf, "Add W and f"),
	TO_ENUM(PIC_andwf, "AND W with f"),
	TO_ENUM(PIC_clrf, "Clear f"),
	TO_ENUM(PIC_clrw, "Clear W"),
	TO_ENUM(PIC_comf, "Complement f"),
	TO_ENUM(PIC_decf, "Decrement f"),
	TO_ENUM(PIC_decfsz, "Decrement f, Skip if 0"),
	TO_ENUM(PIC_incf, "Increment f"),
	TO_ENUM(PIC_incfsz, "Increment f, Skip if 0"),
	TO_ENUM(PIC_iorwf, "Inclusive OR W with f"),
	TO_ENUM(PIC_movf, "Move f"),
	TO_ENUM(PIC_movwf, "Move W to f"),
	TO_ENUM(PIC_nop, "No Operation"),
	TO_ENUM(PIC_rlf, "Rotate Left f through Carry"),
	TO_ENUM(PIC_rrf, "Rotate Right f through Carry"),
	TO_ENUM(PIC_subwf, "Subtract W from f"),
	TO_ENUM(PIC_swapf, "Swap nibbles in f"),
	TO_ENUM(PIC_xorwf, "Exclusive OR W with f"),
	TO_ENUM(PIC_bcf, "Bit Clear f"),
	TO_ENUM(PIC_bsf, "Bit Set f"),
	TO_ENUM(PIC_btfsc, "Bit Test f, Skip if Clear"),
	TO_ENUM(PIC_btfss, "Bit Test f, Skip if Set"),
	TO_ENUM(PIC_addlw, "Add literal and W"),
	TO_ENUM(PIC_andlw, "AND literal with W"),
	TO_ENUM(PIC_call, "Call subroutine"),
	TO_ENUM(PIC_clrwdt, "Clear Watchdog Timer"),
	TO_ENUM(PIC_goto, "Go to address"),
	TO_ENUM(PIC_iorlw, "Inclusive OR literal with W"),
	TO_ENUM(PIC_movlw, "Move literal to W"),
	TO_ENUM(PIC_retfie, "Return from interrupt"),
	TO_ENUM(PIC_retlw, "Return with literal in W"),
	TO_ENUM(PIC_return, "Return from Subroutine"),
	TO_ENUM(PIC_sleep, "Go into standby mode"),
	TO_ENUM(PIC_sublw, "Subtract W from literal"),
	TO_ENUM(PIC_xorlw, "Exclusive OR literal with W"),
	TO_ENUM(PIC_option, "Load OPTION register"),
	TO_ENUM(PIC_tris, "Load TRIS Register"),
	TO_ENUM(PIC_movfw, "Move Contents of File Reg to W"),
	TO_ENUM(PIC_tstf, "Test Contents of File Register"),
	TO_ENUM(PIC_negf, "Negate File Register Contents"),
	TO_ENUM(PIC_b, "Branch to Address"),
	TO_ENUM(PIC_clrc, "Clear Carry"),
	TO_ENUM(PIC_clrdc, "Clear Digit Carry"),
	TO_ENUM(PIC_clrz, "Clear Zero"),
	TO_ENUM(PIC_setc, "Set Carry"),
	TO_ENUM(PIC_setdc, "Set Digit Carry"),
	TO_ENUM(PIC_setz, "Set Zero"),
	TO_ENUM(PIC_skpc, "Skip on Carry"),
	TO_ENUM(PIC_skpdc, "Skip on Digit Carry"),
	TO_ENUM(PIC_skpnc, "Skip on No Carry"),
	TO_ENUM(PIC_skpndc, "Skip on No Digit Carry"),
	TO_ENUM(PIC_skpnz, "Skip on No Zero"),
	TO_ENUM(PIC_skpz, "Skip on Zero"),
	TO_ENUM(PIC_bc, "Branch on Carry to Address k"),
	TO_ENUM(PIC_bdc, "Branch on Digit Carry to k"),
	TO_ENUM(PIC_bnc, "Branch on No Carry to k"),
	TO_ENUM(PIC_bndc, "Branch on No Digit Carry to k"),
	TO_ENUM(PIC_bnz, "Branch on No Zero to Address"),
	TO_ENUM(PIC_bz, "Branch on Zero to Address k"),
	TO_ENUM(PIC_addcf, "Add Carry to File Register"),
	TO_ENUM(PIC_adddcf, "Add Digit to File Register"),
	TO_ENUM(PIC_subcf, "Subtract Carry from File Reg"),
	TO_ENUM(PIC_addwf3, "Add W and f"),
	TO_ENUM(PIC_addwfc3, "Add W and Carry to f"),
	TO_ENUM(PIC_andwf3, "AND W with f"),
	TO_ENUM(PIC_clrf2, "Clear f"),
	TO_ENUM(PIC_comf3, "Complement f"),
	TO_ENUM(PIC_cpfseq2, "Compare f with W, Skip if =="),
	TO_ENUM(PIC_cpfsgt2, "Compare f with W, Skip if >"),
	TO_ENUM(PIC_cpfslt2, "Compare f with W, Skip if <"),
	TO_ENUM(PIC_decf3, "Decrement f"),
	TO_ENUM(PIC_decfsz3, "Decrement f, Skip if 0"),
	TO_ENUM(PIC_dcfsnz3, "Decrement f, Skip if not 0"),
	TO_ENUM(PIC_incf3, "Increment f"),
	TO_ENUM(PIC_incfsz3, "Increment f, Skip if 0"),
	TO_ENUM(PIC_infsnz3, "Increment f, Skip if not 0"),
	TO_ENUM(PIC_iorwf3, "Inclusive OR W with f"),
	TO_ENUM(PIC_movf3, "Move f"),
	TO_ENUM(PIC_movff2, "Move fs to fd"),
	TO_ENUM(PIC_movwf2, "Move W to f"),
	TO_ENUM(PIC_mulwf2, "Multiply W with f"),
	TO_ENUM(PIC_negf2, "Negate f"),
	TO_ENUM(PIC_rlcf3, "Rotate Left f through Carry"),
	TO_ENUM(PIC_rlncf3, "Rotate Left f"),
	TO_ENUM(PIC_rrcf3, "Rotate Right f through Carry"),
	TO_ENUM(PIC_rrncf3, "Rotate Right f"),
	TO_ENUM(PIC_setf2, "Set f"),
	TO_ENUM(PIC_subfwb3, "Substract f from W with borrow"),
	TO_ENUM(PIC_subwf3, "Substract W from f"),
	TO_ENUM(PIC_subwfb3, "Substract W from f with borrow"),
	TO_ENUM(PIC_swapf3, "Swap nibbles in f"),
	TO_ENUM(PIC_tstfsz2, "Test f, Skip if 0"),
	TO_ENUM(PIC_xorwf3, "Exclusive OR W with f"),
	TO_ENUM(PIC_bcf3, "Bit Clear f"),
	TO_ENUM(PIC_bsf3, "Bit Set f"),
	TO_ENUM(PIC_btfsc3, "Bit Test f, Skip if Clear"),
	TO_ENUM(PIC_btfss3, "Bit Test f, Skip if Set"),
	TO_ENUM(PIC_btg3, "Bit Toggle f"),
	TO_ENUM(PIC_bc1, "Branch if Carry"),
	TO_ENUM(PIC_bn1, "Branch if Negative"),
	TO_ENUM(PIC_bnc1, "Branch if not Carry"),
	TO_ENUM(PIC_bnn1, "Branch if not Negative"),
	TO_ENUM(PIC_bnov1, "Branch if not Overflow"),
	TO_ENUM(PIC_bnz1, "Branch if not Zero"),
	TO_ENUM(PIC_bov1, "Branch if Overflow"),
	TO_ENUM(PIC_bra1, "Branch unconditionally"),
	TO_ENUM(PIC_bz1, "Branch if Zero"),
	TO_ENUM(PIC_call2, "Call subroutine"),
	TO_ENUM(PIC_daw0, "Decimal Adjust W"),
	TO_ENUM(PIC_pop0, "Pop top of return stack"),
	TO_ENUM(PIC_push0, "Push top of return stack"),
	TO_ENUM(PIC_rcall1, "Relative Call subroutine"),
	TO_ENUM(PIC_reset0, "Software device Reset"),
	TO_ENUM(PIC_retfie1, "Return from interrupt enable"),
	TO_ENUM(PIC_return1, "Return from Subroutine"),
	TO_ENUM(PIC_lfsr2, "Move literal to FSR"),
	TO_ENUM(PIC_movlb1, "Move literal to BSR"),
	TO_ENUM(PIC_mullw1, "Multiply literal with W"),
	TO_ENUM(PIC_tblrd0, "Table Read"),
	TO_ENUM(PIC_tblrd0p, "Table Read with post-increment"),
	TO_ENUM(PIC_tblrd0m, "Table Read with post-decrement"),
	TO_ENUM(PIC_tblrdp0, "Table Read with pre-increment"),
	TO_ENUM(PIC_tblwt0, "Table Write"),
	TO_ENUM(PIC_tblwt0p, "Table Write with post-increment"),
	TO_ENUM(PIC_tblwt0m, "Table Write with post-decrement"),
	TO_ENUM(PIC_tblwtp0, "Table Write with pre-increment"),
	TO_ENUM(PIC_addwfc, "Add W and Carry to f"),
	TO_ENUM(PIC_movlp, "Move literal to PCLATH"),
	TO_ENUM(PIC_movlb, "Move literal to BSR"),
	TO_ENUM(PIC_addfsr, "Add Literal to FSRn"),
	TO_ENUM(PIC_asrf, "Arithmetic Right Shift"),
	TO_ENUM(PIC_lslf, "Logical Left Shift"),
	TO_ENUM(PIC_lsrf, "Logical Right Shift"),
	TO_ENUM(PIC_subwfb, "Subtract with Borrow W from f"),
	TO_ENUM(PIC_bra, "Relative Branch"),
	TO_ENUM(PIC_brw, "Relative Branch with W"),
	TO_ENUM(PIC_callw, "Call Subroutine with W"),
	TO_ENUM(PIC_reset, "Software device Reset"),
	TO_ENUM(PIC_moviw, "Move INDFn to W"),
	TO_ENUM(PIC_movwi, "Move W to INDFn"),
	TO_ENUM(PIC_last, "Undocumented instruction PIC_last")
};
