auto instructions_PLFM_ST9 = flags_vector_t{
	TO_ENUM(st9_null, "Undocumented instruction st9_null"),
	TO_ENUM(st9_ld, "Load."),
	TO_ENUM(st9_ldw, "Load word."),
	TO_ENUM(st9_ldpp, "Load (using CSR) => (using CSR)."),
	TO_ENUM(st9_ldpd, "Load (using DPRx) => (using CSR)."),
	TO_ENUM(st9_lddp, "Load (using CSR) => (using DPRx)."),
	TO_ENUM(st9_lddd, "Load (using DPRx) => (using DPRx)."),
	TO_ENUM(st9_add, "Add."),
	TO_ENUM(st9_addw, "Add Word."),
	TO_ENUM(st9_adc, "Add with Carry."),
	TO_ENUM(st9_adcw, "Add Word with Carry."),
	TO_ENUM(st9_sub, "Substract."),
	TO_ENUM(st9_subw, "Substract Word."),
	TO_ENUM(st9_sbc, "Substract with Carry."),
	TO_ENUM(st9_sbcw, "Substract Word with Carry."),
	TO_ENUM(st9_and, "Logical AND."),
	TO_ENUM(st9_andw, "Logical Word AND."),
	TO_ENUM(st9_or, "Logical OR."),
	TO_ENUM(st9_orw, "Logical Word OR."),
	TO_ENUM(st9_xor, "Logical Exclusive OR."),
	TO_ENUM(st9_xorw, "Logical Word Exclusive OR."),
	TO_ENUM(st9_cp, "Compare."),
	TO_ENUM(st9_cpw, "Compare Word."),
	TO_ENUM(st9_tm, "Test under Mask."),
	TO_ENUM(st9_tmw, "Test Word under Mask."),
	TO_ENUM(st9_tcm, "Test Complement under Mask."),
	TO_ENUM(st9_tcmw, "Test Word Complement under Mask."),
	TO_ENUM(st9_inc, "Increment."),
	TO_ENUM(st9_incw, "Increment Word."),
	TO_ENUM(st9_dec, "Decrement."),
	TO_ENUM(st9_decw, "Decrement Word."),
	TO_ENUM(st9_sla, "Shift Left Arithmetic."),
	TO_ENUM(st9_slaw, "Shift Word Left Arithmetic."),
	TO_ENUM(st9_sra, "Shift Right Arithmetic."),
	TO_ENUM(st9_sraw, "Shift Word Right Arithmetic."),
	TO_ENUM(st9_rrc, "Rotate Right through Carry."),
	TO_ENUM(st9_rrcw, "Rotate Word Right through Carry."),
	TO_ENUM(st9_rlc, "Rotate Left through Carry."),
	TO_ENUM(st9_rlcw, "Rotate Word Left through Carry."),
	TO_ENUM(st9_ror, "Rotate Right."),
	TO_ENUM(st9_rol, "Rotate Left."),
	TO_ENUM(st9_clr, "Clear Register."),
	TO_ENUM(st9_cpl, "Complement Register."),
	TO_ENUM(st9_swap, "Swap Nibbles."),
	TO_ENUM(st9_da, "Decimal ajust."),
	TO_ENUM(st9_push, "Push on System Stack."),
	TO_ENUM(st9_pushw, "Push Word on System Stack."),
	TO_ENUM(st9_pea, "Push Effective Address on System Stack."),
	TO_ENUM(st9_pop, "Pop from System Stack."),
	TO_ENUM(st9_popw, "Pop Word from System Stack."),
	TO_ENUM(st9_pushu, "Push on User Stack."),
	TO_ENUM(st9_pushuw, "Push Word on User Stack."),
	TO_ENUM(st9_peau, "Push Effective Address on User Stack."),
	TO_ENUM(st9_popu, "Pop from User Stack."),
	TO_ENUM(st9_popuw, "Pop Word from User Stack."),
	TO_ENUM(st9_link, "Move System Stack Pointer upward; support for high-level language."),
	TO_ENUM(st9_unlink, "Move System Stack Pointer backward; support for high-level language."),
	TO_ENUM(st9_linku, "Move User Stack Pointer upward; support for high-level language."),
	TO_ENUM(st9_unlinku, "Move User Stack Pointer backward; support for high-level language."),
	TO_ENUM(st9_mul, "Multiply 8x8."),
	TO_ENUM(st9_div, "Divide 8x8."),
	TO_ENUM(st9_divws, "Divide Word Stepped 32/16."),
	TO_ENUM(st9_bset, "Bit Set."),
	TO_ENUM(st9_bres, "Bit Reset    ."),
	TO_ENUM(st9_bcpl, "Bit Complement."),
	TO_ENUM(st9_btset, "Bit Test and Set."),
	TO_ENUM(st9_bld, "Bit Load."),
	TO_ENUM(st9_band, "Bit AND."),
	TO_ENUM(st9_bor, "Bit OR."),
	TO_ENUM(st9_bxor, "Bit XOR."),
	TO_ENUM(st9_ret, "Return from Subroutine."),
	TO_ENUM(st9_rets, "Inter-segment Return to Subroutine."),
	TO_ENUM(st9_iret, "Return from Interrupt."),
	TO_ENUM(st9_jrcc, "Jump Relative if Condition ``cc'' is Met."),
	TO_ENUM(st9_jpcc, "Jump if Condition ``cc'' is Met."),
	TO_ENUM(st9_jp, "Unconditional Jump."),
	TO_ENUM(st9_jps, "Unconditional Inter-segment Jump."),
	TO_ENUM(st9_call, "Unconditional Call."),
	TO_ENUM(st9_calls, "Inter-segment Call to Subroutine."),
	TO_ENUM(st9_btjf, "Bit Test and Jump if False."),
	TO_ENUM(st9_btjt, "Bit Test and Jump if True."),
	TO_ENUM(st9_djnz, "Decrement a Working Register and Jump if Non Zero."),
	TO_ENUM(st9_dwjnz, "Decrement a Register Pair and Jump if Non Zero."),
	TO_ENUM(st9_cpjfi, "Compare and Jump on False.  Otherwise Post Increment."),
	TO_ENUM(st9_cpjti, "Compare and Jump on True.  Otherwise Post Increment."),
	TO_ENUM(st9_xch, "Exchange Registers."),
	TO_ENUM(st9_srp, "Set Register Pointer Long (16 working registers)."),
	TO_ENUM(st9_srp0, "Set Register Pointer 0 (8 LSB working registers)."),
	TO_ENUM(st9_srp1, "Set Register Pointer 1 (8 MSB working registers)."),
	TO_ENUM(st9_spp, "Set Page Pointer."),
	TO_ENUM(st9_ext, "Sign Extend."),
	TO_ENUM(st9_ei, "Enable Interrupts."),
	TO_ENUM(st9_di, "Disable Interrupts."),
	TO_ENUM(st9_scf, "Set Carry Flag."),
	TO_ENUM(st9_rcf, "Reset Carry Flag."),
	TO_ENUM(st9_ccf, "Complement Carry Flag."),
	TO_ENUM(st9_spm, "Select Extended Memory addressing scheme through CSR Register."),
	TO_ENUM(st9_sdm, "Select Extended Memory addressing scheme through DPR Registers."),
	TO_ENUM(st9_nop, "No Operation."),
	TO_ENUM(st9_wfi, "Stop Program Execution and Wait for the next Enable Interrupt."),
	TO_ENUM(st9_halt, "Stop Program Execution until System Reset."),
	TO_ENUM(st9_etrap, "Undocumented instruction."),
	TO_ENUM(st9_eret, "Undocumented instruction."),
	TO_ENUM(st9_ald, "PSEUDO INSTRUCTION.  SHOULD NEVER BE USED."),
	TO_ENUM(st9_aldw, "PSEUDO INSTRUCTION.  SHOULD NEVER BE USED."),
	TO_ENUM(st9_last, "Undocumented instruction st9_last")
};
