auto instructions_PLFM_PDP = flags_vector_t{
	TO_ENUM(pdp_null, "Undocumented instruction pdp_null"),
	TO_ENUM(pdp_halt, "Stop CPU"),
	TO_ENUM(pdp_wait, "Wait interrupt"),
	TO_ENUM(pdp_rti, "Interrupt return"),
	TO_ENUM(pdp_bpt, "Trap to Debbuger"),
	TO_ENUM(pdp_iot, "Trap to 20 (i/o)"),
	TO_ENUM(pdp_reset, "Reset CPU and device"),
	TO_ENUM(pdp_rtt, "Interrupt return and ignore dbg-flag"),
	TO_ENUM(pdp_mfpt, "Load Processor Type          (* hi model)"),
	TO_ENUM(pdp_jmp, "Absolute jmp"),
	TO_ENUM(pdp_rts, "Return into subroutine"),
	TO_ENUM(pdp_spl, "Set Prior."),
	TO_ENUM(pdp_nop, "Not operation"),
	TO_ENUM(pdp_clc, "Clear C bit in PSW"),
	TO_ENUM(pdp_clv, "Clear V bit in PSW"),
	TO_ENUM(pdp_clz, "Clear Z bit in PSW"),
	TO_ENUM(pdp_cln, "Clear N bit in PSW"),
	TO_ENUM(pdp_ccc, "Clear All Condition bits in PSW"),
	TO_ENUM(pdp_sec, "Set C bit in PSW"),
	TO_ENUM(pdp_sev, "Set V bit in PSW"),
	TO_ENUM(pdp_sez, "Set Z bit in PSW"),
	TO_ENUM(pdp_sen, "Set N bit in PSW"),
	TO_ENUM(pdp_scc, "Set All Condition bits bit in PSW"),
	TO_ENUM(pdp_swab, "Exchange byte in word"),
	TO_ENUM(pdp_br, "Relative jmp"),
	TO_ENUM(pdp_bne, "Jump if Z=0"),
	TO_ENUM(pdp_beq, "Jump if Z=1"),
	TO_ENUM(pdp_bge, "Jump if N^V=0"),
	TO_ENUM(pdp_blt, "Jump if N^V=1"),
	TO_ENUM(pdp_bgt, "Jump if Z|(N^V)=0"),
	TO_ENUM(pdp_ble, "Jump if Z|(N^V)=1"),
	TO_ENUM(pdp_jsr, "Call procedure"),
	TO_ENUM(pdp_clr, "Clear operand"),
	TO_ENUM(pdp_com, "Inverse operand"),
	TO_ENUM(pdp_inc, "Increment operand"),
	TO_ENUM(pdp_dec, "Decrement operand"),
	TO_ENUM(pdp_neg, "op = -op"),
	TO_ENUM(pdp_adc, "Add with Carry"),
	TO_ENUM(pdp_sbc, "Substract with Carry"),
	TO_ENUM(pdp_tst, "Test operand"),
	TO_ENUM(pdp_ror, "Cyclic shift rignt"),
	TO_ENUM(pdp_rol, "Cyclic shift left"),
	TO_ENUM(pdp_asr, "Arifmetic shift rignt"),
	TO_ENUM(pdp_asl, "Arifmetic shift left"),
	TO_ENUM(pdp_mark, "Return and empty stack"),
	TO_ENUM(pdp_mfpi, "Load from previous instruction space (*hi model)"),
	TO_ENUM(pdp_mtpi, "Store to previous instruction space  (*hi model)"),
	TO_ENUM(pdp_sxt, "N=>op"),
	TO_ENUM(pdp_mov, "Move operand"),
	TO_ENUM(pdp_cmp, "Compare operands"),
	TO_ENUM(pdp_bit, "Check Bit's"),
	TO_ENUM(pdp_bic, "Clear Bit's"),
	TO_ENUM(pdp_bis, "Set Bit's"),
	TO_ENUM(pdp_add, "Add operands"),
	TO_ENUM(pdp_sub, "Substract operands"),
	TO_ENUM(pdp_mul, "Multiple Reg          (*eis)"),
	TO_ENUM(pdp_div, "Divide Reg            (*eis)"),
	TO_ENUM(pdp_ash, "Multistep shift       (*eis)"),
	TO_ENUM(pdp_ashc, "Multistep shift 2 reg (*eis)"),
	TO_ENUM(pdp_xor, "Exclusive or          (*eis)"),
	TO_ENUM(pdp_fadd, "Floating Add         (*fis)"),
	TO_ENUM(pdp_fsub, "Floating Subtract    (*fis)"),
	TO_ENUM(pdp_fmul, "Floating Multiple    (*fis)"),
	TO_ENUM(pdp_fdiv, "Floating Divide      (*fis)"),
	TO_ENUM(pdp_sob, "Undocumented instruction pdp_sob"),
	TO_ENUM(pdp_bpl, "Jump if N=0"),
	TO_ENUM(pdp_bmi, "Jump if N=1"),
	TO_ENUM(pdp_bhi, "Jump if (!C)&(!Z)=0"),
	TO_ENUM(pdp_blos, "Jump if C|Z=1"),
	TO_ENUM(pdp_bvc, "Jump if V=0"),
	TO_ENUM(pdp_bvs, "Jump if V=1"),
	TO_ENUM(pdp_bcc, "Jump if C=0"),
	TO_ENUM(pdp_bcs, "Jump if C=1"),
	TO_ENUM(pdp_emt, "Trap to System"),
	TO_ENUM(pdp_trap, "Trap to user/compiler"),
	TO_ENUM(pdp_mtps, "Store PSW            (*lsi11 only)"),
	TO_ENUM(pdp_mfpd, "Load from previous data space (*hi model)"),
	TO_ENUM(pdp_mtpd, "Store to previous data space  (*hi model)"),
	TO_ENUM(pdp_mfps, "Load  PSW            (*lsi11 only)"),
	TO_ENUM(pdp_cfcc, "Copy cond.codes into FPS to PSW"),
	TO_ENUM(pdp_setf, "Set Float"),
	TO_ENUM(pdp_seti, "Set Integer"),
	TO_ENUM(pdp_setd, "Set Double"),
	TO_ENUM(pdp_setl, "Set Long Integer"),
	TO_ENUM(pdp_ldfps, "Load FPS"),
	TO_ENUM(pdp_stfps, "Store FPS"),
	TO_ENUM(pdp_stst, "Load interrupt status"),
	TO_ENUM(pdp_clrd, "Clear"),
	TO_ENUM(pdp_tstd, "Test"),
	TO_ENUM(pdp_absd, "op = mod(op)"),
	TO_ENUM(pdp_negd, "op = -op"),
	TO_ENUM(pdp_muld, "Multiple"),
	TO_ENUM(pdp_modd, "Get int. part"),
	TO_ENUM(pdp_addd, "Add"),
	TO_ENUM(pdp_ldd, "Load in Acc"),
	TO_ENUM(pdp_subd, "Substract"),
	TO_ENUM(pdp_cmpd, "Compare"),
	TO_ENUM(pdp_std, "Store into Acc"),
	TO_ENUM(pdp_divd, "Divide"),
	TO_ENUM(pdp_stexp, "Store exponent"),
	TO_ENUM(pdp_stcdi, "Store and convert double/float to integer/long"),
	TO_ENUM(pdp_stcdf, "Store and convert double/float to float/double"),
	TO_ENUM(pdp_ldexp, "Load exponent"),
	TO_ENUM(pdp_ldcif, "Load and convert integer/long to double/float"),
	TO_ENUM(pdp_ldcfd, "Load and convert float/double to double/float"),
	TO_ENUM(pdp_call, "Jsr PC,"),
	TO_ENUM(pdp_return, "RTS PC"),
	TO_ENUM(pdp_compcc, "Complex Condition Codes"),
	TO_ENUM(pdp_last, "Undocumented instruction pdp_last")
};
