auto instructions_PLFM_68K = flags_vector_t{
	TO_ENUM(mc_null, "Undocumented instruction mc_null"),
	TO_ENUM(mc_abcd, "summa with BCD correction"),
	TO_ENUM(mc_add, "summa with Dn"),
	TO_ENUM(mc_adda, "summa with An"),
	TO_ENUM(mc_addi, "summa with immediate"),
	TO_ENUM(mc_addq, "-\"-"),
	TO_ENUM(mc_addx, "summa 2 reg and const"),
	TO_ENUM(mc_and, "logical and"),
	TO_ENUM(mc_andi, "logical and with immediate"),
	TO_ENUM(mc_asl, "shift by count"),
	TO_ENUM(mc_asr, "-\"-"),
	TO_ENUM(mc_b, "branch if cond code"),
	TO_ENUM(mc_bchg, "bit chang"),
	TO_ENUM(mc_bclr, "bit clear"),
	TO_ENUM(mc_bftst, "bit field test"),
	TO_ENUM(mc_bfchg, "bit field change"),
	TO_ENUM(mc_bfclr, "bit field set in 0"),
	TO_ENUM(mc_bfset, "bit field set in 1"),
	TO_ENUM(mc_bfextu, "bit field extract (unsigned)"),
	TO_ENUM(mc_bfexts, "bit field extract (signed)"),
	TO_ENUM(mc_bfffo, "bit field offset"),
	TO_ENUM(mc_bfins, "bit field include"),
	TO_ENUM(mc_bgnd, "CPU32- enter backgound mode"),
	TO_ENUM(mc_bkpt, "disable TRAP at any cycles"),
	TO_ENUM(mc_bra, "branch"),
	TO_ENUM(mc_bset, "bit set"),
	TO_ENUM(mc_bsr, "relative call"),
	TO_ENUM(mc_btst, "bit test"),
	TO_ENUM(mc_callm, "call module [descrtiptor] (020)"),
	TO_ENUM(mc_cas, "compare and swap"),
	TO_ENUM(mc_cas2, "-\"-"),
	TO_ENUM(mc_chk, "compare and trap"),
	TO_ENUM(mc_chk2, "-\"-"),
	TO_ENUM(mc_cinv, "invalidate cache"),
	TO_ENUM(mc_clr, "clear data"),
	TO_ENUM(mc_cmp, "compare data"),
	TO_ENUM(mc_cmp2, "-\"-"),
	TO_ENUM(mc_cmpa, "compare address"),
	TO_ENUM(mc_cmpi, "compare immediate"),
	TO_ENUM(mc_cmpm, "compare memory"),
	TO_ENUM(mc_cpush, "invalidate cache"),
	TO_ENUM(mc_db, "(djnz) if cond code"),
	TO_ENUM(mc_divs, "sign divide"),
	TO_ENUM(mc_divsl, "-\"-"),
	TO_ENUM(mc_divu, "unsign didide"),
	TO_ENUM(mc_divul, "-\"-"),
	TO_ENUM(mc_eor, "logical xor"),
	TO_ENUM(mc_eori, "logical xor with immediate"),
	TO_ENUM(mc_exg, "exchange registers"),
	TO_ENUM(mc_ext, "analog cwd"),
	TO_ENUM(mc_extb, "analog cwq"),
	TO_ENUM(mc_fabs, "FP abs"),
	TO_ENUM(mc_facos, "FP acos"),
	TO_ENUM(mc_fadd, "FP add"),
	TO_ENUM(mc_fasin, "FP asin"),
	TO_ENUM(mc_fatan, "FP atan"),
	TO_ENUM(mc_fatanh, "FP atanh"),
	TO_ENUM(mc_fb, "fBcc"),
	TO_ENUM(mc_fcmp, "FP cmp"),
	TO_ENUM(mc_fcos, "FP cos"),
	TO_ENUM(mc_fcosh, "FP cosh"),
	TO_ENUM(mc_fdabs, "FP abs double rounded"),
	TO_ENUM(mc_fdadd, "FP add"),
	TO_ENUM(mc_fdb, "fDBcc"),
	TO_ENUM(mc_fddiv, "FP div double rounded"),
	TO_ENUM(mc_fdiv, "FP div"),
	TO_ENUM(mc_fdmove, "FP mov double rounded"),
	TO_ENUM(mc_fdmul, "FP mul double rounded"),
	TO_ENUM(mc_fdneg, "FP neg double rounded"),
	TO_ENUM(mc_fdsqrt, "FP sqrt double rounded"),
	TO_ENUM(mc_fdsub, "FP sub double rounded"),
	TO_ENUM(mc_fetox, "FP e**x"),
	TO_ENUM(mc_fetoxm1, "FP e**x-1"),
	TO_ENUM(mc_fgetexp, "FP extract exponent"),
	TO_ENUM(mc_fgetman, "FP extract mantissa"),
	TO_ENUM(mc_fint, "FP get integer part"),
	TO_ENUM(mc_fintrz, "FP get integer part by round"),
	TO_ENUM(mc_flog2, "FP log[2]"),
	TO_ENUM(mc_flog10, "FP log[10]"),
	TO_ENUM(mc_flogn, "FP log[e]"),
	TO_ENUM(mc_flognp1, "FP log[e] x+1"),
	TO_ENUM(mc_fmod, "FP mod"),
	TO_ENUM(mc_fmove, "move float"),
	TO_ENUM(mc_fmovecr, "move floating const"),
	TO_ENUM(mc_fmovem, "move float register list"),
	TO_ENUM(mc_fmul, "FM mul"),
	TO_ENUM(mc_fneg, "FP neg"),
	TO_ENUM(mc_fnop, "float nop"),
	TO_ENUM(mc_frem, "FP rem"),
	TO_ENUM(mc_frestore, "restore status"),
	TO_ENUM(mc_fs, "fScc"),
	TO_ENUM(mc_fsabs, "FP abs single rounded"),
	TO_ENUM(mc_fsadd, "FP add single rounded"),
	TO_ENUM(mc_fsave, "Fsave status"),
	TO_ENUM(mc_fscale, "FP *2**x"),
	TO_ENUM(mc_fsdiv, "FP div single rounded"),
	TO_ENUM(mc_fsgldiv, "FP single div"),
	TO_ENUM(mc_fsglmul, "FP single mul"),
	TO_ENUM(mc_fsin, "FP sin"),
	TO_ENUM(mc_fsincos, "FP sin & cos"),
	TO_ENUM(mc_fsinh, "FP sinh"),
	TO_ENUM(mc_fsmove, "FP mov single rounded"),
	TO_ENUM(mc_fsmul, "FP mul single rounded"),
	TO_ENUM(mc_fsneg, "FP neg single rounded"),
	TO_ENUM(mc_fsqrt, "FP sqrt"),
	TO_ENUM(mc_fssqrt, "FP sqrt single rounded"),
	TO_ENUM(mc_fssub, "FP sub single rounded"),
	TO_ENUM(mc_fsub, "FP sub"),
	TO_ENUM(mc_ftan, "FP tan"),
	TO_ENUM(mc_ftanh, "FP tanh"),
	TO_ENUM(mc_ftentox, "FP 10**x"),
	TO_ENUM(mc_ftrap, "fTRAPcc"),
	TO_ENUM(mc_ftst, "FP tst"),
	TO_ENUM(mc_ftwotox, "FP 2**x"),
	TO_ENUM(mc_halt, "(coldfire) Halt the processor"),
	TO_ENUM(mc_illegal, "trap to vector"),
	TO_ENUM(mc_jmp, "absolute Jmp"),
	TO_ENUM(mc_jsr, "absolute jsr"),
	TO_ENUM(mc_lea, "load effective address"),
	TO_ENUM(mc_link, "change sp context"),
	TO_ENUM(mc_lpstop, "cpu32 - stop"),
	TO_ENUM(mc_lsl, "logical shift"),
	TO_ENUM(mc_lsr, "-\"-"),
	TO_ENUM(mc_mac, "multiple and accumulate"),
	TO_ENUM(mc_macl, "multiple and accumulate with register load"),
	TO_ENUM(mc_move, "move memory"),
	TO_ENUM(mc_move16, "move 16 byte"),
	TO_ENUM(mc_movea, "move move with address reg"),
	TO_ENUM(mc_movec, "move from/to control register"),
	TO_ENUM(mc_movem, "move register list"),
	TO_ENUM(mc_movep, "move with data register"),
	TO_ENUM(mc_moveq, "move with immediate"),
	TO_ENUM(mc_moves, "mtpd/mfpd"),
	TO_ENUM(mc_msac, "multiple and subtract"),
	TO_ENUM(mc_msacl, "multiple and subtract with register load"),
	TO_ENUM(mc_muls, "sign multiplication"),
	TO_ENUM(mc_mulu, "unsign multiplication"),
	TO_ENUM(mc_nbcd, "negative with BCD correct"),
	TO_ENUM(mc_neg, "negative"),
	TO_ENUM(mc_negx, "negative with immediate"),
	TO_ENUM(mc_nop, "null operation"),
	TO_ENUM(mc_not, "logical not"),
	TO_ENUM(mc_or, "logical or"),
	TO_ENUM(mc_ori, "logical or with immediate"),
	TO_ENUM(mc_pack, "UNP(bcd)+adj -> PACK(bcd)"),
	TO_ENUM(mc_pea, "lea into stack"),
	TO_ENUM(mc_pb, "68851 pbcc"),
	TO_ENUM(mc_pdb, "68851 pdbcc"),
	TO_ENUM(mc_pflush, "invalidate cache"),
	TO_ENUM(mc_pflushr, "68851 load root entry"),
	TO_ENUM(mc_ploadr, "68851"),
	TO_ENUM(mc_ploadw, "68851"),
	TO_ENUM(mc_pmove, "move MMU register"),
	TO_ENUM(mc_prestore, "68851"),
	TO_ENUM(mc_psave, "68851"),
	TO_ENUM(mc_ps, "68851 pscc"),
	TO_ENUM(mc_ptestr, "test a logical address"),
	TO_ENUM(mc_ptestw, "-\"-"),
	TO_ENUM(mc_ptrap, "68851 ptrapcc"),
	TO_ENUM(mc_pulse, "(coldfire) generate unique PST value"),
	TO_ENUM(mc_pvalid, "68851 move AL bit"),
	TO_ENUM(mc_rol, "cycl. shift"),
	TO_ENUM(mc_ror, "-\"-"),
	TO_ENUM(mc_roxl, "two op cycl shift"),
	TO_ENUM(mc_roxr, "-\"-"),
	TO_ENUM(mc_reset, "reset"),
	TO_ENUM(mc_rtd, "mark"),
	TO_ENUM(mc_rte, "return with SR"),
	TO_ENUM(mc_rtm, "reload save module state"),
	TO_ENUM(mc_rtr, "return with CCR"),
	TO_ENUM(mc_rts, "return"),
	TO_ENUM(mc_sbcd, "substract with BCD correction"),
	TO_ENUM(mc_s, "1 if cond code else 0"),
	TO_ENUM(mc_stop, "halt"),
	TO_ENUM(mc_sub, "substract"),
	TO_ENUM(mc_suba, "substract address"),
	TO_ENUM(mc_subi, "substract immediate"),
	TO_ENUM(mc_subq, "-\"-"),
	TO_ENUM(mc_subx, "substract memory"),
	TO_ENUM(mc_swap, "hi and low word in register"),
	TO_ENUM(mc_tas, "test byte sign"),
	TO_ENUM(mc_tbl, "CPU32-tblu/tblun/tbls/tblsn"),
	TO_ENUM(mc_trap, "analog int(86) (or trap if cond code)"),
	TO_ENUM(mc_trapv, "if V then trap"),
	TO_ENUM(mc_tst, "test destination"),
	TO_ENUM(mc_unlk, "destroy address ?"),
	TO_ENUM(mc_unpk, "PACK(bcd)+adj -> UNPACK(bcd)"),
	TO_ENUM(mc_wddata, "(coldfire) load WDDATA port (pins)"),
	TO_ENUM(mc_wdebug, "(coldfire) load debug register"),
	TO_ENUM(mc_atrap, "MacOS atrap"),
	TO_ENUM(mc_bitrev, "bit reverse"),
	TO_ENUM(mc_byterev, "byte reverse"),
	TO_ENUM(mc_ff1, "find first one"),
	TO_ENUM(mc_intouch, "instruction fetch touch"),
	TO_ENUM(mc_mov3q, "move 3-bit data quick"),
	TO_ENUM(mc_mvs, "move with sign extend"),
	TO_ENUM(mc_mvz, "move with zero-fill"),
	TO_ENUM(mc_sats, "signed saturate"),
	TO_ENUM(mc_movclr, "move from accumulator and clear"),
	TO_ENUM(mc_maaac, "Multiply and Add to 1st Accumulator, Add to 2nd Accumulator"),
	TO_ENUM(mc_masac, "Multiply and Add to 1st Accumulator, Subtract from 2nd Accumulator"),
	TO_ENUM(mc_msaac, "Multiply and Subtract to 1st Accumulator, Add to 2nd Accumulator"),
	TO_ENUM(mc_mssac, "Multiply and Subtract to 1st Accumulator, Subtract to 2nd Accumulator"),
	TO_ENUM(mc_remsl, "Signed Divide Remainder"),
	TO_ENUM(mc_remul, "Unsigned Divide Remainder"),
	TO_ENUM(mc_last, "Undocumented instruction mc_last")
};
