auto instructions_PLFM_SPARC = flags_vector_t{
	TO_ENUM(SPARC_null, "Undocumented instruction SPARC_null"),
	TO_ENUM(SPARC_add, "Add"),
	TO_ENUM(SPARC_addcc, "Add and modify condition codes"),
	TO_ENUM(SPARC_addc, "Add with carry"),
	TO_ENUM(SPARC_addccc, "Add with carry and modify condition codes"),
	TO_ENUM(SPARC_and, "And"),
	TO_ENUM(SPARC_andcc, "And and modify condition codes"),
	TO_ENUM(SPARC_andn, "And not"),
	TO_ENUM(SPARC_andncc, "And not (and modify condition codes)"),
	TO_ENUM(SPARC_b, "Branch on integer condition codes"),
	TO_ENUM(SPARC_bp, "Branch on integer condition codes with prediction"),
	TO_ENUM(SPARC_bpr, "Branch on contents of integer register with prediction"),
	TO_ENUM(SPARC_call, "Call and link"),
	TO_ENUM(SPARC_casa, "Compare and swap word in alternate space"),
	TO_ENUM(SPARC_casxa, "Compare and swap doubleword in alternate space"),
	TO_ENUM(SPARC_done, "Return from trap"),
	TO_ENUM(SPARC_fabs, "Floating-point absolute value"),
	TO_ENUM(SPARC_fadd, "Floating-point add"),
	TO_ENUM(SPARC_fbp, "Branch on floating-point condition codes with prediction"),
	TO_ENUM(SPARC_fb, "Branch on floating-point condition codes"),
	TO_ENUM(SPARC_fcmp, "Floating-point compare"),
	TO_ENUM(SPARC_fcmpe, "Floating-point compare (exception if unordered)"),
	TO_ENUM(SPARC_fdiv, "Floating-point divide"),
	TO_ENUM(SPARC_fdmulq, "Floating-point multiply double to quad"),
	TO_ENUM(SPARC_flush, "Flush instruction memory"),
	TO_ENUM(SPARC_flushw, "Flush register windows"),
	TO_ENUM(SPARC_fmov, "Floating-point move"),
	TO_ENUM(SPARC_fmovcc, "Conditional floating-point move"),
	TO_ENUM(SPARC_fmovr, "Move floating-point register if integer register contents satisfy condition"),
	TO_ENUM(SPARC_fmul, "Floating-point multiply"),
	TO_ENUM(SPARC_fneg, "Floating-point negate"),
	TO_ENUM(SPARC_fsmuld, "Floating-point multiply single to double"),
	TO_ENUM(SPARC_fsqrt, "Floating-point square root"),
	TO_ENUM(SPARC_fsub, "Floating-point subtract"),
	TO_ENUM(SPARC_fstox, "Convert single floating point to 64-bit integer"),
	TO_ENUM(SPARC_fdtox, "Convert doublee floating point to 64-bit integer"),
	TO_ENUM(SPARC_fqtox, "Convert quad floating point to 64-bit integer"),
	TO_ENUM(SPARC_fxtos, "Convert 64-bit integer to single floating point"),
	TO_ENUM(SPARC_fxtod, "Convert 64-bit integer to double floating point"),
	TO_ENUM(SPARC_fxtoq, "Convert 64-bit integer to quad floating point"),
	TO_ENUM(SPARC_fitos, "Convert 32-bit integer to single floating point"),
	TO_ENUM(SPARC_fdtos, "Convert single floating point to single floating point"),
	TO_ENUM(SPARC_fqtos, "Convert quade floating point to single floating point"),
	TO_ENUM(SPARC_fitod, "Convert 32-bit integer to double floating point"),
	TO_ENUM(SPARC_fstod, "Convert single floating point to double floating point"),
	TO_ENUM(SPARC_fqtod, "Convert quade floating point to double floating point"),
	TO_ENUM(SPARC_fitoq, "Convert 32-bit integer to quad floating point"),
	TO_ENUM(SPARC_fstoq, "Convert single floating point to quad floating point"),
	TO_ENUM(SPARC_fdtoq, "Convert quade floating point to quad floating point"),
	TO_ENUM(SPARC_fstoi, "Convert single floating point to 32-bit integer"),
	TO_ENUM(SPARC_fdtoi, "Convert doublee floating point to 32-bit integer"),
	TO_ENUM(SPARC_fqtoi, "Convert quad floating point to 32-bit integer"),
	TO_ENUM(SPARC_illtrap, "Illegal instruction"),
	TO_ENUM(SPARC_impdep1, "Implementation-dependent instruction"),
	TO_ENUM(SPARC_impdep2, "Implementation-dependent instruction"),
	TO_ENUM(SPARC_jmpl, "Jump and link"),
	TO_ENUM(SPARC_ldd, "Load doubleword"),
	TO_ENUM(SPARC_ldda, "Load doubleword from alternate space"),
	TO_ENUM(SPARC_lddf, "Load double floating-point"),
	TO_ENUM(SPARC_lddfa, "Load double floating-point from alternate space"),
	TO_ENUM(SPARC_ldf, "Load floating-point"),
	TO_ENUM(SPARC_ldfa, "Load floating-point from alternate space"),
	TO_ENUM(SPARC_ldfsr, "Load floating-point state register lower"),
	TO_ENUM(SPARC_ldqf, "Load quad floating-point"),
	TO_ENUM(SPARC_ldqfa, "Load quad floating-point from alternate space"),
	TO_ENUM(SPARC_ldsb, "Load signed byte"),
	TO_ENUM(SPARC_ldsba, "Load signed byte from alternate space"),
	TO_ENUM(SPARC_ldsh, "Load signed halfword"),
	TO_ENUM(SPARC_ldsha, "Load signed halfword from alternate space"),
	TO_ENUM(SPARC_ldstub, "Load-store unsigned byte"),
	TO_ENUM(SPARC_ldstuba, "Load-store unsigned byte in alternate space"),
	TO_ENUM(SPARC_ldsw, "Load signed word"),
	TO_ENUM(SPARC_ldswa, "Load signed word from alternate space"),
	TO_ENUM(SPARC_ldub, "Load unsigned byte"),
	TO_ENUM(SPARC_lduba, "Load unsigned byte from alternate space"),
	TO_ENUM(SPARC_lduh, "Load unsigned halfword"),
	TO_ENUM(SPARC_lduha, "Load unsigned halfword from alternate space"),
	TO_ENUM(SPARC_lduw, "Load unsigned word"),
	TO_ENUM(SPARC_lduwa, "Load unsigned word from alternate space"),
	TO_ENUM(SPARC_ldx, "Load extended"),
	TO_ENUM(SPARC_ldxa, "Load extended from alternate space"),
	TO_ENUM(SPARC_ldxfsr, "Load extended floating-point state register"),
	TO_ENUM(SPARC_membar, "Memory barrier"),
	TO_ENUM(SPARC_mov, "Move integer register if condition is satisfied"),
	TO_ENUM(SPARC_movr, "Move integer register on contents of integer register"),
	TO_ENUM(SPARC_mulscc, "Multiply step and modify condition codes"),
	TO_ENUM(SPARC_mulx, "Multiply 64-bit integers"),
	TO_ENUM(SPARC_nop, "No operation"),
	TO_ENUM(SPARC_or, "Inclusive-or"),
	TO_ENUM(SPARC_orcc, "Inclusive-or (and modify condition codes)"),
	TO_ENUM(SPARC_orn, "Inclusive-or not"),
	TO_ENUM(SPARC_orncc, "Inclusive-or not (and modify condition codes)"),
	TO_ENUM(SPARC_popc, "Population count"),
	TO_ENUM(SPARC_prefetch, "Prefetch data"),
	TO_ENUM(SPARC_prefetcha, "Prefetch data from alternate space"),
	TO_ENUM(SPARC_rd, "Read state register"),
	TO_ENUM(SPARC_rdpr, "Read privileged register"),
	TO_ENUM(SPARC_restore, "Restore caller's window"),
	TO_ENUM(SPARC_restored, "Window has been restored"),
	TO_ENUM(SPARC_retry, "Return from trap and retry"),
	TO_ENUM(SPARC_return, "Return"),
	TO_ENUM(SPARC_save, "Save caller's window"),
	TO_ENUM(SPARC_saved, "Window has been saved"),
	TO_ENUM(SPARC_sdiv, "32-bit signed integer divide"),
	TO_ENUM(SPARC_sdivcc, "32-bit signed integer divide and modify condition codes"),
	TO_ENUM(SPARC_sdivx, "64-bit signed integer divide"),
	TO_ENUM(SPARC_sethi, "Set high 22 bits of low word of integer register"),
	TO_ENUM(SPARC_sir, "Software-initiated reset"),
	TO_ENUM(SPARC_sll, "Shift left logical"),
	TO_ENUM(SPARC_sllx, "Shift left logical, extended"),
	TO_ENUM(SPARC_smul, "Signed integer multiply"),
	TO_ENUM(SPARC_smulcc, "Signed integer multiply (and modify condition codes)"),
	TO_ENUM(SPARC_sra, "Shift right arithmetic"),
	TO_ENUM(SPARC_srax, "Shift right arithmetic, extended"),
	TO_ENUM(SPARC_srl, "Shift right logical"),
	TO_ENUM(SPARC_srlx, "Shift right logical, extended"),
	TO_ENUM(SPARC_stb, "Store byte"),
	TO_ENUM(SPARC_stba, "Store byte into alternate space"),
	TO_ENUM(SPARC_stbar, "Store barrier"),
	TO_ENUM(SPARC_std, "Store doubleword"),
	TO_ENUM(SPARC_stda, "Store doubleword into alternate space"),
	TO_ENUM(SPARC_stdf, "Store double floating-point"),
	TO_ENUM(SPARC_stdfa, "Store double floating-point into alternate space"),
	TO_ENUM(SPARC_stf, "Store floating-point"),
	TO_ENUM(SPARC_stfa, "Store floating-point into alternate space"),
	TO_ENUM(SPARC_stfsr, "Store floating-point state register"),
	TO_ENUM(SPARC_sth, "Store halfword"),
	TO_ENUM(SPARC_stha, "Store halfword into alternate space"),
	TO_ENUM(SPARC_stqf, "Store quad floating-point"),
	TO_ENUM(SPARC_stqfa, "Store quad floating-point into alternate space"),
	TO_ENUM(SPARC_stw, "Store word"),
	TO_ENUM(SPARC_stwa, "Store word into alternate space"),
	TO_ENUM(SPARC_stx, "Store extended"),
	TO_ENUM(SPARC_stxa, "Store extended into alternate space"),
	TO_ENUM(SPARC_stxfsr, "Store extended floating-point state register"),
	TO_ENUM(SPARC_sub, "Subtract"),
	TO_ENUM(SPARC_subcc, "Subtract and modify condition codes"),
	TO_ENUM(SPARC_subc, "Subtract with carry"),
	TO_ENUM(SPARC_subccc, "Subtract with carry and modify condition codes"),
	TO_ENUM(SPARC_swap, "Swap integer register with memory"),
	TO_ENUM(SPARC_swapa, "Swap integer register with memory in alternate space"),
	TO_ENUM(SPARC_taddcc, "Tagged add and modify condition codes"),
	TO_ENUM(SPARC_taddcctv, "Tagged add and modify condition codes (trap on overflow)"),
	TO_ENUM(SPARC_tsubcc, "Tagged subtract and modify condition codes"),
	TO_ENUM(SPARC_tsubcctv, "Tagged subtract and modify condition codes (trap on overflow)"),
	TO_ENUM(SPARC_t, "Trap on integer condition codes"),
	TO_ENUM(SPARC_udiv, "Unsigned integer divide"),
	TO_ENUM(SPARC_udivcc, "Unsigned integer divide and modify condition codes"),
	TO_ENUM(SPARC_udivx, "64-bit unsigned integer divide"),
	TO_ENUM(SPARC_umul, "Unsigned integer multiply"),
	TO_ENUM(SPARC_umulcc, "Unsigned integer multiply and modify condition codes"),
	TO_ENUM(SPARC_wr, "Write Y register"),
	TO_ENUM(SPARC_wrpr, "Write privileged register"),
	TO_ENUM(SPARC_xnor, "Exclusive-nor"),
	TO_ENUM(SPARC_xnorcc, "Exclusive-nor (and modify condition codes)"),
	TO_ENUM(SPARC_xor, "Exclusive-or"),
	TO_ENUM(SPARC_xorcc, "Exclusive-or (and modify condition codes)"),
	TO_ENUM(SPARC_cmp, "Compare"),
	TO_ENUM(SPARC_jmp, "Jump"),
	TO_ENUM(SPARC_iprefetch, "Instruction prefetch"),
	TO_ENUM(SPARC_tst, "Test"),
	TO_ENUM(SPARC_ret, "Return from subroutine"),
	TO_ENUM(SPARC_retl, "Return from leaf subroutine"),
	TO_ENUM(SPARC_setuw, "Load unsigned constant"),
	TO_ENUM(SPARC_setsw, "Load signed constant"),
	TO_ENUM(SPARC_setx, "Load 64-bit constant"),
	TO_ENUM(SPARC_signx, "Sign-extend 32-bit value to 64 bits"),
	TO_ENUM(SPARC_not, "One's complement"),
	TO_ENUM(SPARC_neg, "Two's complement"),
	TO_ENUM(SPARC_cas, "Compare and swap"),
	TO_ENUM(SPARC_casl, "Compare and swap, little endian"),
	TO_ENUM(SPARC_casx, "Compare and swap extended"),
	TO_ENUM(SPARC_casxl, "Compare and swap extended, little endian"),
	TO_ENUM(SPARC_inc, "Increment"),
	TO_ENUM(SPARC_inccc, "Increment and modify condition codes"),
	TO_ENUM(SPARC_dec, "Deccrement"),
	TO_ENUM(SPARC_deccc, "Decrement and modify condition codes"),
	TO_ENUM(SPARC_btst, "Bit test"),
	TO_ENUM(SPARC_bset, "Bit set"),
	TO_ENUM(SPARC_bclr, "Bit clear"),
	TO_ENUM(SPARC_btog, "Bit toggle"),
	TO_ENUM(SPARC_clr, "Clear"),
	TO_ENUM(SPARC_clrb, "Clear byte"),
	TO_ENUM(SPARC_clrh, "Clear halfword"),
	TO_ENUM(SPARC_clrx, "Clear extended word"),
	TO_ENUM(SPARC_clruw, "Clear upper word"),
	TO_ENUM(SPARC_pseudo_mov, "Move register"),
	TO_ENUM(SPARC_alignaddress, "Calculate address for misaligned data access"),
	TO_ENUM(SPARC_array, "3-D address to blocked byte address conversion"),
	TO_ENUM(SPARC_edge, "Edge boundary processing {little-endian}"),
	TO_ENUM(SPARC_faligndata, "Perform data alignment for misaligned data"),
	TO_ENUM(SPARC_fandnot1, "Negated src1 AND src2 (single precision)"),
	TO_ENUM(SPARC_fandnot2, "src1 AND negated src2 (single precision)"),
	TO_ENUM(SPARC_fand, "Logical AND (single precision)"),
	TO_ENUM(SPARC_fcmpeq, "Four 16-bit/two 32-bit compare; set integer dest if src1 = src2"),
	TO_ENUM(SPARC_fcmpgt, "Four 16-bit/two 32-bit compare; set integer dest if src1 > src2"),
	TO_ENUM(SPARC_fcmple, "Four 16-bit/two 32-bit compare; set integer dest if src1 <= src2"),
	TO_ENUM(SPARC_fcmpne, "Four 16-bit/two 32-bit compare; set integer dest if src1 != src2"),
	TO_ENUM(SPARC_fexpand, "Four 8-bit to 16-bit expands"),
	TO_ENUM(SPARC_fmul8sux16, "Signed upper 8/16-bit partitioned product of corresponding components"),
	TO_ENUM(SPARC_fmul8ulx16, "Unsigned lower 8/16-bit partitioned product of corresponding components"),
	TO_ENUM(SPARC_fmul8x16, "8/16-bit partitioned product of corresponding components"),
	TO_ENUM(SPARC_fmul8x16al, "8/16-bit lower a partitioned product of 4 components"),
	TO_ENUM(SPARC_fmul8x16au, "8/16-bit upper a partitioned product of 4 components"),
	TO_ENUM(SPARC_fmuld8sux16, "Signed upper 8/16-bit multiply 32-bit partitioned product of components"),
	TO_ENUM(SPARC_fmuld8ulx16, "Unsigned lower 8/16-bit multiply 32-bit partitioned product of components"),
	TO_ENUM(SPARC_fnand, "Logical NAND (single precision)"),
	TO_ENUM(SPARC_fnor, "Logical NOR (single precision)"),
	TO_ENUM(SPARC_fnot1, "Negate (1's complement) src1 (single precision)"),
	TO_ENUM(SPARC_fnot2, "Negate (1's complement) src2 (single precision)"),
	TO_ENUM(SPARC_fone, "One fill (single precision)"),
	TO_ENUM(SPARC_fornot1, "Negated src1 OR src2 (single precision)"),
	TO_ENUM(SPARC_fornot2, "src1 OR negated src2 (single precision)"),
	TO_ENUM(SPARC_for, "Logical OR (single precision)"),
	TO_ENUM(SPARC_fpackfix, "Two 32-bit to 16-bit fixed pack"),
	TO_ENUM(SPARC_fpack, "Four 16-bit/two 32-bit pixel pack"),
	TO_ENUM(SPARC_fpadd, "Four 16-bit/two 32-bit partitioned add (single precision)"),
	TO_ENUM(SPARC_fpmerge, "Two 32-bit pixel to 64-bit pixel merge"),
	TO_ENUM(SPARC_fpsub, "Four 16-bit/two 32-bit partitioned subtract (single precision)"),
	TO_ENUM(SPARC_fsrc1, "Copy src1 (single precision)"),
	TO_ENUM(SPARC_fsrc2, "Copy src2 (single precision)"),
	TO_ENUM(SPARC_fxnor, "Logical XNOR (single precision)"),
	TO_ENUM(SPARC_fxor, "Logical XOR (single precision)"),
	TO_ENUM(SPARC_fzero, "Zero fill (single precision)"),
	TO_ENUM(SPARC_pdist, "Distance between 8 8-bit components"),
	TO_ENUM(SPARC_shutdown, "Power-down support"),
	TO_ENUM(SPARC_rett, "Return from trap"),
	TO_ENUM(SPARC_bmask, "Byte Mask"),
	TO_ENUM(SPARC_bshuffle, "Byte Shuffle"),
	TO_ENUM(SPARC_edgen, "Edge boundary processing (no CC) {little-endian}"),
	TO_ENUM(SPARC_rdhpr, "Read Hyperprivileged Register"),
	TO_ENUM(SPARC_wrhpr, "Write Hyperprivileged Register"),
	TO_ENUM(SPARC_siam, "Set Interval Arithmetic Mode"),
	TO_ENUM(SPARC_last, "Undocumented instruction SPARC_last")
};
