auto instructions_PLFM_RISCV = flags_vector_t{
	TO_ENUM(RISCV_null, "Undocumented instruction RISCV_null"),
	TO_ENUM(RISCV_lui, "Load Upper Immediate"),
	TO_ENUM(RISCV_auipc, "Add Upper Immediate to pc"),
	TO_ENUM(RISCV_jal, "Jump and link"),
	TO_ENUM(RISCV_jalr, "Jump register rs1 & write pc +2 in rs1"),
	TO_ENUM(RISCV_beq, "Branch on equal"),
	TO_ENUM(RISCV_bne, "Branch not equal"),
	TO_ENUM(RISCV_blt, "Branch less than"),
	TO_ENUM(RISCV_bge, "Branch greater or equal"),
	TO_ENUM(RISCV_bltu, "Branch less than unsigned"),
	TO_ENUM(RISCV_bgeu, "Branch greater or equal unsigned"),
	TO_ENUM(RISCV_lb, "Load byte"),
	TO_ENUM(RISCV_lh, "Load halfword"),
	TO_ENUM(RISCV_lw, "Load word"),
	TO_ENUM(RISCV_lbu, "Load byte unsigned"),
	TO_ENUM(RISCV_lhu, "Load halfword unsigned"),
	TO_ENUM(RISCV_sb, "Store byte"),
	TO_ENUM(RISCV_sh, "Store halfword"),
	TO_ENUM(RISCV_sw, "Store word"),
	TO_ENUM(RISCV_addi, "Add immediate"),
	TO_ENUM(RISCV_slti, "Set less than immediate"),
	TO_ENUM(RISCV_sltiu, "Set less than immediate unsigned"),
	TO_ENUM(RISCV_xori, "Xor immediate"),
	TO_ENUM(RISCV_ori, "Or immediate"),
	TO_ENUM(RISCV_andi, "And Immediate"),
	TO_ENUM(RISCV_slli, "Shift left logical immediate"),
	TO_ENUM(RISCV_srli, "Shift right logical immediate"),
	TO_ENUM(RISCV_srai, "Shift right arithmetical immediate"),
	TO_ENUM(RISCV_add, "Add integer"),
	TO_ENUM(RISCV_sub, "Substract integer"),
	TO_ENUM(RISCV_sll, "Shift left logical"),
	TO_ENUM(RISCV_slt, "Set Less Than"),
	TO_ENUM(RISCV_sltu, "Set Less Than unsigned"),
	TO_ENUM(RISCV_xor, "eXclusive Or"),
	TO_ENUM(RISCV_srl, "Shift right logical"),
	TO_ENUM(RISCV_sra, "Shift right arithmetical"),
	TO_ENUM(RISCV_or, "Or"),
	TO_ENUM(RISCV_and, "And"),
	TO_ENUM(RISCV_fence, "Fence"),
	TO_ENUM(RISCV_ecall, "Ecall"),
	TO_ENUM(RISCV_ebreak, "Ebreak"),
	TO_ENUM(RISCV_uret, "User lvl return"),
	TO_ENUM(RISCV_sret, "Supervisor lvl return"),
	TO_ENUM(RISCV_mret, "Machine lvl return"),
	TO_ENUM(RISCV_wfi, "Wait for interrupt"),
	TO_ENUM(RISCV_sfence, "Supervisor fence"),
	TO_ENUM(RISCV_hfenceb, "Hypervisor fence b"),
	TO_ENUM(RISCV_hfenceg, "Hypervisor fence g"),
	TO_ENUM(RISCV_lwu, "Load word unsigned"),
	TO_ENUM(RISCV_ld, "Load double"),
	TO_ENUM(RISCV_sd, "Store double"),
	TO_ENUM(RISCV_addiw, "Add immediate word"),
	TO_ENUM(RISCV_slliw, "Shift left logical immediate word"),
	TO_ENUM(RISCV_srliw, "Shift right logical immediate word"),
	TO_ENUM(RISCV_sraiw, "Shift right arithmetical immediate word"),
	TO_ENUM(RISCV_addw, "Add integer word"),
	TO_ENUM(RISCV_subw, "Substract integer word"),
	TO_ENUM(RISCV_sllw, "Shift left logical word"),
	TO_ENUM(RISCV_sltw, "Set Less Than word"),
	TO_ENUM(RISCV_srlw, "Shift right logical word"),
	TO_ENUM(RISCV_sraw, "Shift right arithmetical word"),
	TO_ENUM(RISCV_fencei, "Fence immediate"),
	TO_ENUM(RISCV_csrrw, "Atomic Read Write CSR"),
	TO_ENUM(RISCV_csrrs, "Atomic Read and Set bit CSR"),
	TO_ENUM(RISCV_csrrc, "Atomic Read and clear bit CSR"),
	TO_ENUM(RISCV_csrrwi, "Atomic Read Write CSR immediate"),
	TO_ENUM(RISCV_csrrsi, "Atomic Read and Set bit CSR immediate"),
	TO_ENUM(RISCV_csrrci, "Atomic Read and clear bit CSR immediate"),
	TO_ENUM(RISCV_mul, "Multiplication"),
	TO_ENUM(RISCV_mulh, "Multiplication half (signed signed)"),
	TO_ENUM(RISCV_mulhsu, "Multiplication half (signed unsigned)"),
	TO_ENUM(RISCV_mulhu, "Multiplication half (unsigned unsigned)"),
	TO_ENUM(RISCV_div, "Division"),
	TO_ENUM(RISCV_divu, "Division unsigned"),
	TO_ENUM(RISCV_rem, "Remainder of div"),
	TO_ENUM(RISCV_remu, "Remainder of div unsigned"),
	TO_ENUM(RISCV_mulw, "Multiplication word"),
	TO_ENUM(RISCV_divw, "Division word"),
	TO_ENUM(RISCV_divuw, "Division unsigned word"),
	TO_ENUM(RISCV_remw, "Remainder of div word"),
	TO_ENUM(RISCV_remuw, "Remainder of div unsigned word"),
	TO_ENUM(RISCV_lr, "Load reserved"),
	TO_ENUM(RISCV_sc, "Store conditional"),
	TO_ENUM(RISCV_amoswap, "Atomic memory operation swap"),
	TO_ENUM(RISCV_amoadd, "Atomic memory operation add"),
	TO_ENUM(RISCV_amoxor, "Atomic memory operation xop"),
	TO_ENUM(RISCV_amoand, "Atomic memory operation and"),
	TO_ENUM(RISCV_amoor, "Atomic memory operation or"),
	TO_ENUM(RISCV_amomin, "Atomic memory operation min"),
	TO_ENUM(RISCV_amomax, "Atomic memory operation max"),
	TO_ENUM(RISCV_amominu, "Atomic memory operation min unsigned"),
	TO_ENUM(RISCV_amomaxu, "Atomic memory operation max unsigned"),
	TO_ENUM(RISCV_amocas, "Atomic compare and swap"),
	TO_ENUM(RISCV_flw, "Load word (32b)"),
	TO_ENUM(RISCV_fsw, "Store word (32b)"),
	TO_ENUM(RISCV_fmadd, "Multiply then add"),
	TO_ENUM(RISCV_fmsub, "Multiply then substract"),
	TO_ENUM(RISCV_fnmsub, "Multiply then negate then substract"),
	TO_ENUM(RISCV_fnmadd, "Multiply then negate then add"),
	TO_ENUM(RISCV_fadd, "Float addition"),
	TO_ENUM(RISCV_fsub, "Float substraction"),
	TO_ENUM(RISCV_fmul, "Float multiplication"),
	TO_ENUM(RISCV_fdiv, "Float division"),
	TO_ENUM(RISCV_fsqrt, "Float square root"),
	TO_ENUM(RISCV_fsgnj, "Float sign injection"),
	TO_ENUM(RISCV_fsgnjn, "Float sign injection negate"),
	TO_ENUM(RISCV_fsgnjx, "Float sign injection xor between operands"),
	TO_ENUM(RISCV_fmin, "Float minimum"),
	TO_ENUM(RISCV_fmax, "Float maximum"),
	TO_ENUM(RISCV_fcvtf2f, "F2F conve"),
	TO_ENUM(RISCV_fcvtf2i, "F2I conve"),
	TO_ENUM(RISCV_fcvti2f, "I2F conve"),
	TO_ENUM(RISCV_fmv, "Mv"),
	TO_ENUM(RISCV_feq, "Float equal"),
	TO_ENUM(RISCV_flt, "Float less than"),
	TO_ENUM(RISCV_fle, "Float less or equal than"),
	TO_ENUM(RISCV_fclass, "Classify the float"),
	TO_ENUM(RISCV_fld, "Load double (64b)"),
	TO_ENUM(RISCV_fsd, "Store double (64b)"),
	TO_ENUM(RISCV_flq, "Load quadruple (128b)"),
	TO_ENUM(RISCV_fsq, "Store quadruple (128b)"),
	TO_ENUM(RISCV_nop, "No operation"),
	TO_ENUM(RISCV_li, "Load Immediate"),
	TO_ENUM(RISCV_mv, "Copy register"),
	TO_ENUM(RISCV_not, "One's complement"),
	TO_ENUM(RISCV_neg, "Two's complement"),
	TO_ENUM(RISCV_negw, "Two's complement word"),
	TO_ENUM(RISCV_sext, "Sign extend word"),
	TO_ENUM(RISCV_seqz, "Set if = zero"),
	TO_ENUM(RISCV_snez, "Set if != zero"),
	TO_ENUM(RISCV_sltz, "Set if < zero"),
	TO_ENUM(RISCV_sgtz, "Set if > zero"),
	TO_ENUM(RISCV_fabs, "Float absolute value"),
	TO_ENUM(RISCV_fneg, "Float negate"),
	TO_ENUM(RISCV_beqz, "Branch == 0"),
	TO_ENUM(RISCV_bnez, "Branch != 0"),
	TO_ENUM(RISCV_blez, "Branch <= 0"),
	TO_ENUM(RISCV_bgez, "Branch >= 0"),
	TO_ENUM(RISCV_bltz, "Branch < 0"),
	TO_ENUM(RISCV_bgtz, "Branch > 0"),
	TO_ENUM(RISCV_j, "Jump"),
	TO_ENUM(RISCV_jr, "Jump register"),
	TO_ENUM(RISCV_ret, "Return"),
	TO_ENUM(RISCV_rdinstret, "Read instructions-retired counter"),
	TO_ENUM(RISCV_rdcycle, "Read cycle counter"),
	TO_ENUM(RISCV_rdtime, "Read real-time clock"),
	TO_ENUM(RISCV_rdinstreth, "Read instructions-retired counter Upper 32 bits"),
	TO_ENUM(RISCV_rdcycleh, "Read cycle counter Upper 32 bits"),
	TO_ENUM(RISCV_rdtimeh, "Read real-time clock Upper 32 bits"),
	TO_ENUM(RISCV_csrr, "Read CSR"),
	TO_ENUM(RISCV_csrw, "Write CSR"),
	TO_ENUM(RISCV_csrs, "Set bit CSR"),
	TO_ENUM(RISCV_csrc, "Clear bit"),
	TO_ENUM(RISCV_csrwi, "Write CSR immediate"),
	TO_ENUM(RISCV_csrsi, "Set bit CSR immediate"),
	TO_ENUM(RISCV_csrci, "Clear bit CSR immediate"),
	TO_ENUM(RISCV_frcsr, "Read FP control/status register"),
	TO_ENUM(RISCV_fscsr, "Write/Swap FP control/status register"),
	TO_ENUM(RISCV_frrm, "Read FP rounding mode"),
	TO_ENUM(RISCV_fsrm, "Write/Swap FP rounding mode"),
	TO_ENUM(RISCV_frflags, "Read FP exception flags"),
	TO_ENUM(RISCV_fsflags, "Write/Swap FP exception flags"),
	TO_ENUM(RISCV_la, "Load Address macro"),
	TO_ENUM(RISCV_call, "Call macro"),
	TO_ENUM(RISCV_tail, "Tail macro"),
	TO_ENUM(RISCV_jump, "Jump macro"),
	TO_ENUM(RISCV_vsetvl, "Set vector length rd = new vl, rs1 = AVL, rs2 = new vtype value"),
	TO_ENUM(RISCV_vsetvli, "Set vector length vtype immediate"),
	TO_ENUM(RISCV_vsetivli, "Set vector length avl immediate and vtype immediate"),
	TO_ENUM(RISCV_vl, "Vector load"),
	TO_ENUM(RISCV_vs, "Vector store"),
	TO_ENUM(RISCV_vadd, "Vector add"),
	TO_ENUM(RISCV_vsub, "Vector sub"),
	TO_ENUM(RISCV_vrsub, "Vector reverse substract"),
	TO_ENUM(RISCV_vminu, "Vector unsigned minimum"),
	TO_ENUM(RISCV_vmin, "Vector signed minimum"),
	TO_ENUM(RISCV_vmaxu, "Vector unsigned maximum"),
	TO_ENUM(RISCV_vmax, "Vector signed maximum"),
	TO_ENUM(RISCV_vand, "Vector bitwise logical and"),
	TO_ENUM(RISCV_vor, "Vector bitwise logical or"),
	TO_ENUM(RISCV_vxor, "Vector bitwise logical xor"),
	TO_ENUM(RISCV_vrgather, "Vector register gather"),
	TO_ENUM(RISCV_vslideup, "Vector slide up"),
	TO_ENUM(RISCV_vrgatherei16, "Vector register gather"),
	TO_ENUM(RISCV_vslidedown, "Vector slide down"),
	TO_ENUM(RISCV_vadc, "Vector produce sum with carry"),
	TO_ENUM(RISCV_vmadc, "Vector produce carry out in mask register format"),
	TO_ENUM(RISCV_vsbc, "Vector produce difference with borrow"),
	TO_ENUM(RISCV_vmsbc, "Vector produce borrow out in mask register format"),
	TO_ENUM(RISCV_vmerge, "Vector integer merge"),
	TO_ENUM(RISCV_vmv, "Vector integer move"),
	TO_ENUM(RISCV_vmseq, "Vector set if equal"),
	TO_ENUM(RISCV_vmsne, "Vector set if not equal"),
	TO_ENUM(RISCV_vmsltu, "Vector set if less than, unsigned"),
	TO_ENUM(RISCV_vmslt, "Vector set if less than, signed"),
	TO_ENUM(RISCV_vmsleu, "Vector set if less than or equal, unsigned"),
	TO_ENUM(RISCV_vmsle, "Vector set if less than or equal, signed"),
	TO_ENUM(RISCV_vmsgtu, "Vector set if greater than, unsigned"),
	TO_ENUM(RISCV_vmsgt, "Vector set if greater than, signed"),
	TO_ENUM(RISCV_vsaddu, "Vector saturating adds of unsigned integers"),
	TO_ENUM(RISCV_vsadd, "Vector saturating adds of signed integers"),
	TO_ENUM(RISCV_vssubu, "Vector saturating subtract of unsigned integers"),
	TO_ENUM(RISCV_vssub, "Vector saturating subtract of signed integers"),
	TO_ENUM(RISCV_vsll, "Vector bit shift left logical"),
	TO_ENUM(RISCV_vsmul, "Vector signed saturating and rounding fractional multiply"),
	TO_ENUM(RISCV_vmvr, "Vector whole register move <nbr> reg"),
	TO_ENUM(RISCV_vsrl, "Vector bit shift right logical"),
	TO_ENUM(RISCV_vsra, "Vector bit shift right arithmetic"),
	TO_ENUM(RISCV_vssrl, "Vector scaling shift right logical"),
	TO_ENUM(RISCV_vssra, "Vector scaling shift right arithmetic"),
	TO_ENUM(RISCV_vnsrl, "Vector narrowing shift right logical, SEW = (2*SEW) >> SEW"),
	TO_ENUM(RISCV_vnsra, "Vector narrowing shift right arithmetic, SEW = (2*SEW) >> SEW"),
	TO_ENUM(RISCV_vnclipu, "Vector narrowing unsigned clip"),
	TO_ENUM(RISCV_vnclip, "Vector narrowing signed clip"),
	TO_ENUM(RISCV_vwredsumu, "Vector unsigned sum reduction into double-width accumulator"),
	TO_ENUM(RISCV_vwredsum, "Vector signed sum reduction into double-width accumulator"),
	TO_ENUM(RISCV_vredsum, "Vector single-width reduction sum"),
	TO_ENUM(RISCV_vredand, "Vector single-width reduction and"),
	TO_ENUM(RISCV_vredor, "Vector single-width reduction or"),
	TO_ENUM(RISCV_vredxor, "Vector single-width reduction xor"),
	TO_ENUM(RISCV_vredminu, "Vector single-width reduction min unsigned"),
	TO_ENUM(RISCV_vredmin, "Vector single-width reduction min"),
	TO_ENUM(RISCV_vredmaxu, "Vector single-width reduction max unsigned"),
	TO_ENUM(RISCV_vredmax, "Vector single-width reduction max"),
	TO_ENUM(RISCV_vaaddu, "Vector averaging adds of unsigned integers"),
	TO_ENUM(RISCV_vaadd, "Vector averaging adds of signed integers"),
	TO_ENUM(RISCV_vasubu, "Vector averaging subtract of unsigned integers"),
	TO_ENUM(RISCV_vasub, "Vector averaging subtract of signed integers"),
	TO_ENUM(RISCV_vslide1up, "Vector integer slide one element up"),
	TO_ENUM(RISCV_vslide1down, "Vector integer slide one element down"),
	TO_ENUM(RISCV_vcpop, "Vector count population in mask"),
	TO_ENUM(RISCV_vfirst, "Vector find-first-set mask bit"),
	TO_ENUM(RISCV_vmvi, "Vector integer scalar move"),
	TO_ENUM(RISCV_vzext, "Vector zero extend"),
	TO_ENUM(RISCV_vsext, "Vector sign extend"),
	TO_ENUM(RISCV_vmsbf, "Vector Vector set-before-first mask bit"),
	TO_ENUM(RISCV_vmsof, "Vector Vector set-only-first mask bit"),
	TO_ENUM(RISCV_vmsif, "Vector Vector set-including-first mask bit"),
	TO_ENUM(RISCV_viota, "Vector Vector iota"),
	TO_ENUM(RISCV_vid, "Vector Vector element index"),
	TO_ENUM(RISCV_vcompress, "Vector compress"),
	TO_ENUM(RISCV_vmandn, "Vector mask-register not(vs2.mask[i] and vs1.mask[i])"),
	TO_ENUM(RISCV_vmand, "Vector mask-register (vs2.mask[i] and vs1.mask[i])"),
	TO_ENUM(RISCV_vmor, "Vector mask-register (vs2.mask[i] or vs1.mask[i])"),
	TO_ENUM(RISCV_vmxor, "Vector mask-register (vs2.mask[i] xor vs1.mask[i])"),
	TO_ENUM(RISCV_vmorn, "Vector mask-register not(vs2.mask[i] or vs1.mask[i])"),
	TO_ENUM(RISCV_vmnand, "Vector mask-register not(vs2.mask[i] and vs1.mask[i])"),
	TO_ENUM(RISCV_vmnor, "Vector mask-register not(vs2.mask[i] or vs1.mask[i])"),
	TO_ENUM(RISCV_vmxnor, "Vector mask-register not(vs2.mask[i] xor vs1.mask[i])"),
	TO_ENUM(RISCV_vdivu, "Vector unsigned divide"),
	TO_ENUM(RISCV_vdiv, "Vector signed divide"),
	TO_ENUM(RISCV_vremu, "Vector unsigned remainder"),
	TO_ENUM(RISCV_vrem, "Vector signed remainder"),
	TO_ENUM(RISCV_vmulhu, "Vector unsigned multiply, returning high bits of product"),
	TO_ENUM(RISCV_vmul, "Vector signed multiply, returning low bits of product"),
	TO_ENUM(RISCV_vmulhsu, "Vector signed-unsigned multiply, returning high bits of product"),
	TO_ENUM(RISCV_vmulh, "Vector signed multiply, returning high bits of product"),
	TO_ENUM(RISCV_vmadd, "Vector integer multiply-add, overwrite multiplicand"),
	TO_ENUM(RISCV_vnmsub, "Vector integer multiply-sub, overwrite multiplicand"),
	TO_ENUM(RISCV_vmacc, "Vector integer multiply-add, overwrite addend"),
	TO_ENUM(RISCV_vnmsac, "Vector integer multiply-sub, overwrite minuend"),
	TO_ENUM(RISCV_vwaddu, "Vector widening unsigned integer add , 2*SEW = SEW +/- SEW"),
	TO_ENUM(RISCV_vwadd, "Vector widening signed integer add , 2*SEW = SEW +/- SEW"),
	TO_ENUM(RISCV_vwsubu, "Vector widening unsigned integer substract , 2*SEW = SEW +/- SEW"),
	TO_ENUM(RISCV_vwsub, "Vector widening signed integer substract , 2*SEW = SEW +/- SEW"),
	TO_ENUM(RISCV_vwadduw, "Vector widening unsigned integer add , 2*SEW = 2*SEW +/- SEW"),
	TO_ENUM(RISCV_vwaddw, "Vector widening signed integer add , 2*SEW = 2*SEW +/- SEW"),
	TO_ENUM(RISCV_vwsubuw, "Vector widening unsigned integer substract , 2*SEW = 2*SEW +/- SEW"),
	TO_ENUM(RISCV_vwsubw, "Vector widening signed integer substract , 2*SEW = 2*SEW +/- SEW"),
	TO_ENUM(RISCV_vwmulu, "Vector widening unsigned-integer multiply"),
	TO_ENUM(RISCV_vwmulsu, "Vector widening signed(vs2)-unsigned integer multiply"),
	TO_ENUM(RISCV_vwmul, "Vector widening signed-integer multiply"),
	TO_ENUM(RISCV_vwmaccu, "Vector widening unsigned-integer multiply-add, overwrite addend"),
	TO_ENUM(RISCV_vwmacc, "Vector widening signed-integer multiply-add, overwrite addend"),
	TO_ENUM(RISCV_vwmaccus, "Vector widening unsigned-signed-integer multiply-add, overwrite addend"),
	TO_ENUM(RISCV_vwmaccsu, "Vector widening signed-unsigned-integer multiply-add, overwrite addend"),
	TO_ENUM(RISCV_vfadd, "Vector floating-point add"),
	TO_ENUM(RISCV_vfredusum, "Vector fp simple-width reductions unordered sum"),
	TO_ENUM(RISCV_vfsub, "Vector floating-point subtract"),
	TO_ENUM(RISCV_vfredosum, "Vector fp simple-width reductions ordered sum"),
	TO_ENUM(RISCV_vfmin, "Vector floating-point minimum"),
	TO_ENUM(RISCV_vfredmin, "Vector fp simple-width reductions minimum value"),
	TO_ENUM(RISCV_vfmax, "Vector floating-point maximum"),
	TO_ENUM(RISCV_vfredmax, "Vector fp simple-width reductions maximum value"),
	TO_ENUM(RISCV_vfsgnj, "Vector sign injection"),
	TO_ENUM(RISCV_vfsgnjn, "Vector sign injection negated"),
	TO_ENUM(RISCV_vfsgnjx, "Vector sign injection xor"),
	TO_ENUM(RISCV_vfslide1up, "Vector fp slide one element up"),
	TO_ENUM(RISCV_vfslide1down, "Vector fp slide one element down"),
	TO_ENUM(RISCV_vfmov, "Vector floating-point scalar move"),
	TO_ENUM(RISCV_vfcvt, "Vector convert float to integer / integer to float"),
	TO_ENUM(RISCV_vfwcvt, "Vector convert single width float/integer to double-width integer/float"),
	TO_ENUM(RISCV_vfncvt, "Vector convert double-width float/integer to single width float/integer"),
	TO_ENUM(RISCV_vfsqrt, "Vector floating-point square root"),
	TO_ENUM(RISCV_vfrsqrt7, "Vector floating-point reciprocal square-root estimate to 7 bits"),
	TO_ENUM(RISCV_vfrec7, "Vector floating-point reciprocal estimate to 7 bits"),
	TO_ENUM(RISCV_vfclass, "Vector classification of float"),
	TO_ENUM(RISCV_vfmerge, "Vector floating-point merge"),
	TO_ENUM(RISCV_vfmv, "Vector floating-point move"),
	TO_ENUM(RISCV_vmfeq, "Vector fp compare equal"),
	TO_ENUM(RISCV_vmfle, "Vector fp compare less than or equal"),
	TO_ENUM(RISCV_vmflt, "Vector fp compare less than"),
	TO_ENUM(RISCV_vmfne, "Vector fp compare not equal"),
	TO_ENUM(RISCV_vmfgt, "Vector fp compare greater than"),
	TO_ENUM(RISCV_vmfge, "Vector fp compare greater than or equal"),
	TO_ENUM(RISCV_vfdiv, "Vector floating-point divide"),
	TO_ENUM(RISCV_vfrdiv, "Vector floating-point reverse divide"),
	TO_ENUM(RISCV_vfmul, "Vector floating-point multiply"),
	TO_ENUM(RISCV_vfrsub, "Vector floating-point reverse subtract"),
	TO_ENUM(RISCV_vfmadd, "Vector fp multiply-add, overwrites multiplicand"),
	TO_ENUM(RISCV_vfnmadd, "Vector fp negate-(multiply-add), overwrites multiplicand"),
	TO_ENUM(RISCV_vfmsub, "Vector fp multiply-sub, overwrites multiplicand"),
	TO_ENUM(RISCV_vfnmsub, "Vector fp negate-(multiply-sub), overwrites multiplicand"),
	TO_ENUM(RISCV_vfmacc, "Vector fp multiply-accumulate, overwrites addend"),
	TO_ENUM(RISCV_vfnmacc, "Vector fp negate-(multiply-accumulate), overwrites subtrahend"),
	TO_ENUM(RISCV_vfmsac, "Vector fp multiply-subtract-accumulator, overwrites subtrahend"),
	TO_ENUM(RISCV_vfnmsac, "Vector fp negate-(multiply-subtract-accumulator), overwrites minuend"),
	TO_ENUM(RISCV_vfwadd, "Vector widening fp add 2*SEW = SEW +/- SEW"),
	TO_ENUM(RISCV_vfwredusum, "Vector fp widened reduction unordered sum"),
	TO_ENUM(RISCV_vfwsub, "Vector widening fp substract 2*SEW = SEW +/- SEW"),
	TO_ENUM(RISCV_vfwredosum, "Vector fp widened reduction ordered sum"),
	TO_ENUM(RISCV_vfwaddw, "Vector widening fp add 2*SEW = 2*SEW +/- SEW"),
	TO_ENUM(RISCV_vfwsubw, "Vector widening fp substract 2*SEW = 2*SEW +/- SEW"),
	TO_ENUM(RISCV_vfwmul, "Vector widening floating-point multiply"),
	TO_ENUM(RISCV_vfwmacc, "Vector fp widening multiply-accumulate, overwrites addend"),
	TO_ENUM(RISCV_vfwnmacc, "Vector fp widening negate-(multiply-accumulate), overwrites addend"),
	TO_ENUM(RISCV_vfwmsac, "Vector fp widening multiply-subtract-accumulator, overwrites addend"),
	TO_ENUM(RISCV_vfwnmsac, "Vector fp widening negate-(multiply-subtract-accumulator), overwrites addend"),
	TO_ENUM(RISCV_vneg, "Vector negate"),
	TO_ENUM(RISCV_vwcvt, "Vector double width signed"),
	TO_ENUM(RISCV_vwcvtu, "Vector double width unsigned"),
	TO_ENUM(RISCV_vnot, "Vector not"),
	TO_ENUM(RISCV_vncvt, "Vector half width"),
	TO_ENUM(RISCV_vfneg, "Vector floating point negate"),
	TO_ENUM(RISCV_vfabs, "Vector floating point absolute"),
	TO_ENUM(RISCV_vmmv, "Vector copy mask register"),
	TO_ENUM(RISCV_vmclr, "Vector clear mask register"),
	TO_ENUM(RISCV_vmset, "Vector set mask register"),
	TO_ENUM(RISCV_vmnot, "Vector invert bits"),
	TO_ENUM(RISCV_andn, "And with inverted operand rs2"),
	TO_ENUM(RISCV_bclr, "Single-bit clear (register)"),
	TO_ENUM(RISCV_bclri, "Single-bit clear (immediate)"),
	TO_ENUM(RISCV_bext, "Single-bit extract (register)"),
	TO_ENUM(RISCV_bexti, "Single-bit extract (immediate)"),
	TO_ENUM(RISCV_binv, "Single-bit invert (register)"),
	TO_ENUM(RISCV_binvi, "Single-bit invert (immediate)"),
	TO_ENUM(RISCV_bset, "Single-bit set (register)"),
	TO_ENUM(RISCV_bseti, "Single-bit set (immediate)"),
	TO_ENUM(RISCV_clmul, "Carry-less multiply (low-part)"),
	TO_ENUM(RISCV_clmulh, "Carry-less multiply (high-part)"),
	TO_ENUM(RISCV_clmulr, "Carry-less multiply (reversed)"),
	TO_ENUM(RISCV_clz, "Count leading zero bits"),
	TO_ENUM(RISCV_clzw, "Count leading zero bits in word"),
	TO_ENUM(RISCV_cpop, "Count set bits"),
	TO_ENUM(RISCV_cpopw, "Count set bits in word"),
	TO_ENUM(RISCV_ctz, "Count trailing zeros"),
	TO_ENUM(RISCV_ctzw, "Count trainling zeros ni word"),
	TO_ENUM(RISCV_max, "Maximum signed"),
	TO_ENUM(RISCV_maxu, "Maximum unsigned"),
	TO_ENUM(RISCV_min, "Minimum signed"),
	TO_ENUM(RISCV_minu, "Minimum unsigned"),
	TO_ENUM(RISCV_orc, "Bitwise OR-Combine"),
	TO_ENUM(RISCV_orn, "Or with inverted operand rs2"),
	TO_ENUM(RISCV_rev8, "Byte-reverse register"),
	TO_ENUM(RISCV_rol, "Rotate left (Register)"),
	TO_ENUM(RISCV_rolw, "Rotate Left Word (Register)"),
	TO_ENUM(RISCV_ror, "Rotate right"),
	TO_ENUM(RISCV_rori, "Rotate right immediate"),
	TO_ENUM(RISCV_roriw, "Rotate Right Word by Immediate"),
	TO_ENUM(RISCV_rorw, "Rotate Right Word (Register)"),
	TO_ENUM(RISCV_sh1add, "Shift left by 1 and add"),
	TO_ENUM(RISCV_sh2add, "Shift left by 2 and add"),
	TO_ENUM(RISCV_sh3add, "Shift left by 3 and add"),
	TO_ENUM(RISCV_xnor, "Exclusive nor"),
	TO_ENUM(RISCV_zext, "Zero-extend halfword"),
	TO_ENUM(RISCV_flh, "Load floating point half-precision (16 bits)"),
	TO_ENUM(RISCV_fsh, "Store floating point half-precision (16 bits)"),
	TO_ENUM(RISCV_hl, "Load hypervisor mode"),
	TO_ENUM(RISCV_hs, "Store hypervisor mode"),
	TO_ENUM(RISCV_sinval, "invalidates address-translation cache"),
	TO_ENUM(RISCV_sfencefg, "fine grained supervisor fence"),
	TO_ENUM(RISCV_hinval, "invalidates address-translation cache in hypervisor mode"),
	TO_ENUM(RISCV_pause, "Pause"),
	TO_ENUM(RISCV_cbo, "cache base operation"),
	TO_ENUM(RISCV_prefetch, "prefetch address hint"),
	TO_ENUM(RISCV_sfencevm, "Supervisor memory-management fence (spec 1.9.1, 2016)"),
	TO_ENUM(RISCV_aes, "AES encryption decryption"),
	TO_ENUM(RISCV_aes64im, "inverse MixColumns step of the AES Block Cipher"),
	TO_ENUM(RISCV_aes64ks1i, "KeySchedule operation for the AES Block cipher involving the SBox operation"),
	TO_ENUM(RISCV_aes64ks2, "KeySchedule operation for the AES Block cipher"),
	TO_ENUM(RISCV_brev8, "Reverse the bits in each byte of a source register"),
	TO_ENUM(RISCV_pack, "Pack the low halves of rs1 and rs2 into rd"),
	TO_ENUM(RISCV_packh, "Pack the low bytes of rs1 and rs2 into rd"),
	TO_ENUM(RISCV_packw, "Pack the low bytes of rs1 and rs2 into rd"),
	TO_ENUM(RISCV_sha256, "transformation for SHA2-256 hash function"),
	TO_ENUM(RISCV_sha512, "transformation for SHA2-512 hash function"),
	TO_ENUM(RISCV_sm3, "transformation for SM3 hash function"),
	TO_ENUM(RISCV_sm4, "Acceleration operations for the SM4 block cipher"),
	TO_ENUM(RISCV_unzip, "Place odd and even bits of the source word into upper/lower halves of the destination"),
	TO_ENUM(RISCV_xperm4, "Nibble-wise lookup of indicies into a vector"),
	TO_ENUM(RISCV_xperm8, "Byte-wise lookup of indicies into a vector in registers"),
	TO_ENUM(RISCV_zip, "Place upper/lower halves of the source register into odd/even bits of the destination respectivley"),
	TO_ENUM(RISCV_wrsnto, "Wait on reservation with no timeout"),
	TO_ENUM(RISCV_wrssto, "Wait on reservation with short timeout"),
	TO_ENUM(RISCV_thdcachecall, "Clean all D-cache"),
	TO_ENUM(RISCV_thdcacheciall, "Clean & invalidate all D-cache"),
	TO_ENUM(RISCV_thdcacheiall, "Invalidate all D-cache"),
	TO_ENUM(RISCV_thdcachecpa, "Clean D-cache at PA"),
	TO_ENUM(RISCV_thdcachecipa, "Clean and invalidate D-cache at PA"),
	TO_ENUM(RISCV_thdcacheipa, "Invalidate D-cache at PA"),
	TO_ENUM(RISCV_thdcachecva, "Clean D-cache at VA"),
	TO_ENUM(RISCV_thdcacheciva, "Clean and invalidate D-cache at VA"),
	TO_ENUM(RISCV_thdcacheiva, "Invalidate D-cache at VA"),
	TO_ENUM(RISCV_thdcachecsw, "Clean D-cache by set/way"),
	TO_ENUM(RISCV_thdcachecisw, "Clean & invalidate D-cache by set/way"),
	TO_ENUM(RISCV_thdcacheisw, "Invalidate D-cache by set/way"),
	TO_ENUM(RISCV_thdcachecpal1, "Clean L1 D-cache at PA"),
	TO_ENUM(RISCV_thdcachecval1, "Clean L1 D-cache at VA"),
	TO_ENUM(RISCV_thicacheiall, "Invalidate all I-cache"),
	TO_ENUM(RISCV_thicacheialls, "Invalidate all I-cache on all harts"),
	TO_ENUM(RISCV_thicacheipa, "Invalidate I-cache at PA"),
	TO_ENUM(RISCV_thicacheiva, "Invalidate I-cache at VA"),
	TO_ENUM(RISCV_thl2cachecall, "Clean all L2 cache"),
	TO_ENUM(RISCV_thl2cacheciall, "Clean & invalidate all L2 cache"),
	TO_ENUM(RISCV_thl2cacheiall, "Invalidate all L2 cache"),
	TO_ENUM(RISCV_thsfencevmas, "Invalidate TLB (page table cache) on all harts via broadcasting"),
	TO_ENUM(RISCV_thsync, "Ensures that preceding instructions retire earlier and subsequent instructions retire later"),
	TO_ENUM(RISCV_thsyncs, "Ensures that preceding instructions retire earlier and subsequent instructions retire later"),
	TO_ENUM(RISCV_thsynci, "Ensures that preceding instructions retire earlier and subsequent instructions retire later"),
	TO_ENUM(RISCV_thsyncis, "Ensures that preceding instructions retire earlier and subsequent instructions retire later"),
	TO_ENUM(RISCV_thaddsl, "Add a shifted operand to a second operand"),
	TO_ENUM(RISCV_thsrri, "Rotate Right (by Immediate)"),
	TO_ENUM(RISCV_thsrriw, "Rotate Right Word (by Immediate)"),
	TO_ENUM(RISCV_thext, "Extract and sign-extend bits"),
	TO_ENUM(RISCV_thextu, "Extract and zero-extend bits"),
	TO_ENUM(RISCV_thff0, "Find first '0'-bit"),
	TO_ENUM(RISCV_thff1, "Find first '1'-bit"),
	TO_ENUM(RISCV_threv, "Reverse the byte order"),
	TO_ENUM(RISCV_threvw, "Reverse the byte order of a word operand"),
	TO_ENUM(RISCV_thtstnbz, "Test for NUL bytes"),
	TO_ENUM(RISCV_thtst, "Tests if a single bit is set"),
	TO_ENUM(RISCV_thmveqz, "Move if equal zero"),
	TO_ENUM(RISCV_thmvnez, "Move if not equal zero"),
	TO_ENUM(RISCV_thlbia, "Load indexed byte, increment address after loading"),
	TO_ENUM(RISCV_thlbib, "Load indexed byte, increment address before loading"),
	TO_ENUM(RISCV_thlbuia, "Load indexed unsigned byte, increment address after loading"),
	TO_ENUM(RISCV_thlbuib, "Load indexed unsigned byte, increment address before loading"),
	TO_ENUM(RISCV_thlhia, "Load indexed half-word, increment address after loading"),
	TO_ENUM(RISCV_thlhib, "Load indexed half-word, increment address before loading"),
	TO_ENUM(RISCV_thlhuia, "Load indexed unsigned half-word, increment address after loading"),
	TO_ENUM(RISCV_thlhuib, "Load indexed unsigned half-word, increment address before loading"),
	TO_ENUM(RISCV_thlwia, "Load indexed word, increment address after loading"),
	TO_ENUM(RISCV_thlwib, "Load indexed word, increment address before loading"),
	TO_ENUM(RISCV_thlwuia, "Load indexed unsigned word, increment address after loading"),
	TO_ENUM(RISCV_thlwuib, "Load indexed unsigned word, increment address before loading"),
	TO_ENUM(RISCV_thldia, "Load indexed double-word, increment address after loading"),
	TO_ENUM(RISCV_thldib, "Load indexed double-word, increment address before loading"),
	TO_ENUM(RISCV_thsbia, "Store indexed byte, increment address after loading"),
	TO_ENUM(RISCV_thsbib, "Store indexed byte, increment address before loading"),
	TO_ENUM(RISCV_thshia, "Store indexed half-word, increment address after loading"),
	TO_ENUM(RISCV_thshib, "Store indexed half-word, increment address before loading"),
	TO_ENUM(RISCV_thswia, "Store indexed word, increment address after loading"),
	TO_ENUM(RISCV_thswib, "Store indexed word, increment address before loading"),
	TO_ENUM(RISCV_thsdia, "Store indexed double-word, increment address after loading"),
	TO_ENUM(RISCV_thsdib, "Store indexed double-word, increment address before loading"),
	TO_ENUM(RISCV_thlrb, "Load indexed byte"),
	TO_ENUM(RISCV_thlrbu, "Load indexed unsigned byte"),
	TO_ENUM(RISCV_thlrh, "Load indexed half-word"),
	TO_ENUM(RISCV_thlrhu, "Load indexed unsigned half-word"),
	TO_ENUM(RISCV_thlrw, "Load indexed word"),
	TO_ENUM(RISCV_thlrwu, "Load indexed unsigned word"),
	TO_ENUM(RISCV_thlrd, "Load indexed word"),
	TO_ENUM(RISCV_thsrb, "Store indexed byte"),
	TO_ENUM(RISCV_thsrh, "Store indexed half-word"),
	TO_ENUM(RISCV_thsrw, "Store indexed word"),
	TO_ENUM(RISCV_thsrd, "Store indexed double-word"),
	TO_ENUM(RISCV_thlurb, "Load unsigned indexed byte"),
	TO_ENUM(RISCV_thlurbu, "Load unsigned indexed unsigned byte"),
	TO_ENUM(RISCV_thlurh, "Load unsigned indexed half-word"),
	TO_ENUM(RISCV_thlurhu, "Load unsigned indexed unsigned half-word"),
	TO_ENUM(RISCV_thlurw, "Load unsigned indexed word"),
	TO_ENUM(RISCV_thlurwu, "Load unsigned indexed unsigned word"),
	TO_ENUM(RISCV_thlurd, "Load unsigned indexed double-word"),
	TO_ENUM(RISCV_thsurb, "Store unsigned indexed byte"),
	TO_ENUM(RISCV_thsurh, "Store unsigned indexed half-word"),
	TO_ENUM(RISCV_thsurw, "Store unsigned indexed word"),
	TO_ENUM(RISCV_thsurd, "Store unsigned indexed double-word"),
	TO_ENUM(RISCV_thldd, "Load two 64-bit values from memory into two GPRs"),
	TO_ENUM(RISCV_thlwd, "Load two signed 32-bit values from memory into two GPRs"),
	TO_ENUM(RISCV_thlwud, "Load two unsigned 32-bit values from memory into two GPRs"),
	TO_ENUM(RISCV_thsdd, "Store two 64-bit values to memory from two GPRs"),
	TO_ENUM(RISCV_thswd, "Store two 32-bit values to memory from two GPRs"),
	TO_ENUM(RISCV_thflrd, "Load indexed double-precision floating point value"),
	TO_ENUM(RISCV_thflrw, "Load indexed single-precision floating point value"),
	TO_ENUM(RISCV_thflurd, "Load unsigned indexed double-precision floating point value"),
	TO_ENUM(RISCV_thflurw, "Load unsigned indexed single-precision floating point value"),
	TO_ENUM(RISCV_thfsrd, "Store indexed double-precision floating point value"),
	TO_ENUM(RISCV_thfsrw, "Store indexed single-precision floating point value"),
	TO_ENUM(RISCV_thfsurd, "Store unsigned indexed double-precision floating point value"),
	TO_ENUM(RISCV_thfsurw, "Store unsigned indexed single-precision floating point value"),
	TO_ENUM(RISCV_thmula, "Compute multiply-add result of double-word operands"),
	TO_ENUM(RISCV_thmulah, "Compute multiply-add result of half-word operands"),
	TO_ENUM(RISCV_thmulaw, "Compute multiply-add result of word operands"),
	TO_ENUM(RISCV_thmuls, "Compute multiply-subtract result of double-word operands"),
	TO_ENUM(RISCV_thmulsh, "Compute multiply-subtract result of half-word operands"),
	TO_ENUM(RISCV_thmulsw, "Compute multiply-subtract result of word operands"),
	TO_ENUM(RISCV_thfmv, "R/W double-precision floating-point high-bit data"),
	TO_ENUM(RISCV_thipush, "Pushes register context on the interrupt stack"),
	TO_ENUM(RISCV_thipop, "Pop register context from the interrupt stack"),
	TO_ENUM(RISCV_thandn, "And with inverted operand rs2 (undocumented)"),
	TO_ENUM(RISCV_thorn, "Or with inverted operand rs2 (undocumented)"),
	TO_ENUM(RISCV_thxorn, "Exclusive nor (undocumented)"),
	TO_ENUM(RISCV_thpackl, "Pack some bytes of rs1 and rs2 into rd (undocumented)"),
	TO_ENUM(RISCV_thpackh, "Pack the low bytes of rs1 and rs2 into rd (undocumented)"),
	TO_ENUM(RISCV_thpackhl, "Pack some bytes of rs1 and rs2 into rd (undocumented)"),
	TO_ENUM(RISCV_thvmaqa, "Four signed 8-bit multiply with 32-bit add"),
	TO_ENUM(RISCV_thvmaqau, "Four unsigned 8-bit multiply with 32-bit add"),
	TO_ENUM(RISCV_thvmaqasu, "Four signed-unsigned 8-bit multiply with 32-bit add"),
	TO_ENUM(RISCV_thvmaqaus, "Four unsigned-signed 8-bit multiply with 32-bit add"),
	TO_ENUM(RISCV_thvpmaqa, "Similar to vmaqa, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpmaqau, "Similar to vmaqau, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpmaqaus, "Similar to vmaqaus, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpmaqasu, "Similar to vmaqasu, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpnclip, "Similar to vnclip, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpnclipu, "Similar to vnclipu, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpwadd, "Similar to vadd, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_thvpwaddu, "Similar to vaddu, presumably involving packed values (undocumented)"),
	TO_ENUM(RISCV_unk, "Unsupported instruction"),
	TO_ENUM(RISCV_last, "Undocumented instruction RISCV_last")
};
