auto instructions_PLFM_AD218X = flags_vector_t{
	TO_ENUM(AD218X_null, "Undocumented instruction AD218X_null"),
	TO_ENUM(AD218X_amf_01, "op = op * op (rnd)"),
	TO_ENUM(AD218X_amf_03, "op = mr + op * op (rnd)"),
	TO_ENUM(AD218X_amf_02, "op = mr - op * op (rnd)"),
	TO_ENUM(AD218X_amf_04, "op = op * op (ss)"),
	TO_ENUM(AD218X_amf_05, "op = op * op (su)"),
	TO_ENUM(AD218X_amf_06, "op = op * op (us)"),
	TO_ENUM(AD218X_amf_07, "op = op * op (uu)"),
	TO_ENUM(AD218X_amf_08, "op = mr + op * op"),
	TO_ENUM(AD218X_amf_09, "op = mr + op * op"),
	TO_ENUM(AD218X_amf_0a, "op = mr + op * op"),
	TO_ENUM(AD218X_amf_0b, "op = mr + op * op"),
	TO_ENUM(AD218X_amf_0c, "op = mr - op * op"),
	TO_ENUM(AD218X_amf_0d, "op = mr - op * op"),
	TO_ENUM(AD218X_amf_0e, "op = mr - op * op"),
	TO_ENUM(AD218X_amf_0f, "op = mr - op * op"),
	TO_ENUM(AD218X_amf_10, "op = op"),
	TO_ENUM(AD218X_amf_11, "op = op + 1"),
	TO_ENUM(AD218X_amf_12, "op = op + op + C"),
	TO_ENUM(AD218X_amf_13, "op = op + op"),
	TO_ENUM(AD218X_amf_14, "op = not op"),
	TO_ENUM(AD218X_amf_15, "op = - op"),
	TO_ENUM(AD218X_amf_16, "op = op - op + C - 1"),
	TO_ENUM(AD218X_amf_17, "op = op - op"),
	TO_ENUM(AD218X_amf_18, "op = op - 1"),
	TO_ENUM(AD218X_amf_19, "op = op - op"),
	TO_ENUM(AD218X_amf_1a, "op = op - op + C - 1"),
	TO_ENUM(AD218X_amf_1b, "op = not op"),
	TO_ENUM(AD218X_amf_1c, "op = op and op"),
	TO_ENUM(AD218X_amf_1d, "op = op or op"),
	TO_ENUM(AD218X_amf_1e, "op = op xor op"),
	TO_ENUM(AD218X_amf_1f, "op = abs op"),
	TO_ENUM(AD218X_shft_0, "sr = lshift op (hi)"),
	TO_ENUM(AD218X_shft_1, "sr = sr or lshift op (hi)"),
	TO_ENUM(AD218X_shft_2, "sr = lshift op (lo)"),
	TO_ENUM(AD218X_shft_3, "sr = sr or lshift op (lo)"),
	TO_ENUM(AD218X_shft_4, "sr = ashift op (hi)"),
	TO_ENUM(AD218X_shft_5, "sr = sr or ashift op (hi)"),
	TO_ENUM(AD218X_shft_6, "sr = ashift op (lo)"),
	TO_ENUM(AD218X_shft_7, "sr = sr or ashift op (lo)"),
	TO_ENUM(AD218X_shft_8, "sr = norm op (hi)"),
	TO_ENUM(AD218X_shft_9, "sr = sr or norm op (hi)"),
	TO_ENUM(AD218X_shft_a, "sr = norm op (lo)"),
	TO_ENUM(AD218X_shft_b, "sr = sr or norm op (lo)"),
	TO_ENUM(AD218X_shft_c, "sr = exp op (hi)"),
	TO_ENUM(AD218X_shft_d, "sr = exp op (hix)"),
	TO_ENUM(AD218X_shft_e, "sr = exp op (lo)"),
	TO_ENUM(AD218X_shft_f, "sr = expadj op"),
	TO_ENUM(AD218X_alu_00, "op = op + op + C                     [IF  COND] X + Const"),
	TO_ENUM(AD218X_alu_01, "op = op + op"),
	TO_ENUM(AD218X_alu_02, "op = op - op + C - 1                 [IF  COND] X - Const"),
	TO_ENUM(AD218X_alu_03, "op = op - op"),
	TO_ENUM(AD218X_alu_04, "op = op - op + C - 1                 [IF  COND] Const - X"),
	TO_ENUM(AD218X_alu_05, "op = op - op"),
	TO_ENUM(AD218X_alu_06, "op = op and op                       [IF  COND] X and,or,xor Const"),
	TO_ENUM(AD218X_alu_07, "op = op or op"),
	TO_ENUM(AD218X_alu_08, "op = op xor op"),
	TO_ENUM(AD218X_alu_09, "op = op                              [IF  COND] PASS constant; constant <> 0,1, -1"),
	TO_ENUM(AD218X_alu_0a, "op = op + 1"),
	TO_ENUM(AD218X_alu_0b, "op = op - 1"),
	TO_ENUM(AD218X_alu_0c, "divq op                              ALU Type 23"),
	TO_ENUM(AD218X_alu_0d, "divs op, op                          ALU Type 24"),
	TO_ENUM(AD218X_alu_0e, "none = op                            ALU Type 9, with no result"),
	TO_ENUM(AD218X_alu_0f, "none = op + 1"),
	TO_ENUM(AD218X_alu_10, "none = op + op + C"),
	TO_ENUM(AD218X_alu_11, "none = op + op"),
	TO_ENUM(AD218X_alu_12, "none = not op"),
	TO_ENUM(AD218X_alu_13, "none = - op"),
	TO_ENUM(AD218X_alu_14, "none = op - op + C - 1"),
	TO_ENUM(AD218X_alu_15, "none = op - op"),
	TO_ENUM(AD218X_alu_16, "none = op - 1"),
	TO_ENUM(AD218X_alu_17, "none = op - op + C - 1"),
	TO_ENUM(AD218X_alu_18, "none = op - op"),
	TO_ENUM(AD218X_alu_19, "none = not op"),
	TO_ENUM(AD218X_alu_1a, "none = op and op"),
	TO_ENUM(AD218X_alu_1b, "none = op or op"),
	TO_ENUM(AD218X_alu_1c, "none = op xor op"),
	TO_ENUM(AD218X_alu_1d, "none = abs op"),
	TO_ENUM(AD218X_mac_0, "op = 0                               [IF  COND] MAC CLEAR"),
	TO_ENUM(AD218X_mac_1, "op = mr (rnd)                        [IF  COND] MAC TRANSFER"),
	TO_ENUM(AD218X_mac_2, "op = op * op (ss)                    [IF  COND] X * X"),
	TO_ENUM(AD218X_mac_3, "op = op * op (uu)"),
	TO_ENUM(AD218X_mac_4, "op = op * op (rnd)"),
	TO_ENUM(AD218X_mac_5, "op = mr + op * op (ss)               [IF  COND] MR + X * X"),
	TO_ENUM(AD218X_mac_6, "op = mr + op * op (uu)"),
	TO_ENUM(AD218X_mac_7, "op = mr + op * op (rnd)"),
	TO_ENUM(AD218X_mac_8, "op = mr - op * op (ss)               [IF  COND] MR - X * X"),
	TO_ENUM(AD218X_mac_9, "op = mr - op * op (uu)"),
	TO_ENUM(AD218X_mac_a, "op = mr - op * op (rnd)"),
	TO_ENUM(AD218X_mac_b, "if mv sat mr                         ALU/MAC Type 25"),
	TO_ENUM(AD218X_amf, "[IF  COND] AMF"),
	TO_ENUM(AD218X_shft, "[IF  COND] Shifter"),
	TO_ENUM(AD218X_shifter_0, "sr = ashift op by op (hi)"),
	TO_ENUM(AD218X_shifter_1, "sr = sr or ashift op by op (hi)"),
	TO_ENUM(AD218X_shifter_2, "sr = ashift op by op (lo)"),
	TO_ENUM(AD218X_shifter_3, "sr = sr or ashift op by op (lo)"),
	TO_ENUM(AD218X_shifter_4, "sr = lshift op by op (hi)"),
	TO_ENUM(AD218X_shifter_5, "sr = sr or lshift op by op (hi)"),
	TO_ENUM(AD218X_shifter_6, "sr = lshift op by op (lo)"),
	TO_ENUM(AD218X_shifter_7, "sr = sr or lshift op by op (lo)"),
	TO_ENUM(AD218X_move_0, "op = op                              Internal Data Move, Instruction Type 17:"),
	TO_ENUM(AD218X_move_1, "op = op                              Load Register Immediate, Instruction Type 6:"),
	TO_ENUM(AD218X_move_2, "op = op                              Load Non-Data Register Immediate, Instruction Type 7:"),
	TO_ENUM(AD218X_move_3, "op = dm(op)                          Data Memory Read (Direct Address), Instruction Type 3:"),
	TO_ENUM(AD218X_move_4, "op = dm(op, op)                      Data Memory Read, Instruction Type 4:"),
	TO_ENUM(AD218X_move_5, "op = pm(op, op)                      Program Memory Read"),
	TO_ENUM(AD218X_move_6, "dm(op) = op                          Data Memory Write (Direct Address)"),
	TO_ENUM(AD218X_move_7, "dm(op, op) = op                      Data Memory Write, Instruction Type 4:"),
	TO_ENUM(AD218X_move_8, "dm(op, op) = op                      Data Memory Write, Immediate Data, Instruction Type 2:"),
	TO_ENUM(AD218X_move_9, "pm(op, op) = op                      Program Memory Write, Instruction Type 5"),
	TO_ENUM(AD218X_move_a, "op = io(op)                          I/O Memory Space Read/Write, Instruction Type 29:"),
	TO_ENUM(AD218X_move_b, "io(op) = op"),
	TO_ENUM(AD218X_jump, "Unconditional JUMP Direct, Instruction Type 10:"),
	TO_ENUM(AD218X_jump_1, "Conditional JUMP Direct, Instruction Type 10:"),
	TO_ENUM(AD218X_jump_2, "Unconditional JUMP Indirect, Instruction Type 19:"),
	TO_ENUM(AD218X_jump_3, "Conditional JUMP Indirect, Instruction Type 19:"),
	TO_ENUM(AD218X_jump_4, "Conditional JUMP on Flag In Direct Instruction Type 27:"),
	TO_ENUM(AD218X_call, "Conditional CALL Direct, Instruction Type 10:"),
	TO_ENUM(AD218X_call_1, "Conditional CALL Indirect, Instruction Type 19:"),
	TO_ENUM(AD218X_call_2, "Conditional CALL on Flag In Direct Instruction Type 27:"),
	TO_ENUM(AD218X_rts, "Unconditional Return, Instruction Type 20:"),
	TO_ENUM(AD218X_rts_cond, "Conditional Return, Instruction Type 20:"),
	TO_ENUM(AD218X_rti, "Unconditional Return, Instruction Type 20:"),
	TO_ENUM(AD218X_rti_cond, "Conditional Return, Instruction Type 20:"),
	TO_ENUM(AD218X_nop, "No operation, Instruction Type 30"),
	TO_ENUM(AD218X_do, "Do Until, Instruction Type 11:"),
	TO_ENUM(AD218X_idle, "Idle, Instruction Type 31:"),
	TO_ENUM(AD218X_idle_1, "Undocumented instruction AD218X_idle_1"),
	TO_ENUM(AD218X_flag_out, "Flag Out Mode Control Instruction Type 28:"),
	TO_ENUM(AD218X_stack_ctl, "Stack Control, Instruction Type 26:"),
	TO_ENUM(AD218X_mode_ctl, "Mode Control, Instruction Type 18:"),
	TO_ENUM(AD218X_tops_w, "toppcstack = op                      Internal Data Move, Instruction Type 17:"),
	TO_ENUM(AD218X_tops_r, "op = toppcstack"),
	TO_ENUM(AD218X_ints_dis, "dis ints"),
	TO_ENUM(AD218X_ints_ena, "ena ints"),
	TO_ENUM(AD218X_modify, "modify(op, op)                       Modify Address Register, Instruction Type 21:"),
	TO_ENUM(AD218X_double_move, "op = dm(op, op), op = pm(op, op)     Data & Program Memory Read, Instruction Type 1:"),
	TO_ENUM(AD218X_amf_move_0, "amf_cmd, op = dm(op, op)             ALU/MAC operation with Data Memory Read, Instruction Type 4:"),
	TO_ENUM(AD218X_amf_move_1, "amf_cmd, op = pm(op, op)             ALU/MAC operation with Program Memory Read, Instruction Type 5:"),
	TO_ENUM(AD218X_amf_move_2, "amf_cmd, op = dm(op, op)             Shift operation with Data Memory Read, Instruction Type 12:"),
	TO_ENUM(AD218X_amf_move_3, "amf_cmd, op = pm(op, op)             Shift operation with Program Memory Read, Instruction Type 13:"),
	TO_ENUM(AD218X_amf_move_4, "amf_cmd, op = op                     ALU/MAC operation with Data Register Move, Instruction Type 8:"),
	TO_ENUM(AD218X_amf_move_5, "amf_cmd, op = op                     Shift operation with Data Register Move, Instruction Type 14:"),
	TO_ENUM(AD218X_amf_move_6, "dm(op, op) = op, amf_cmd             ALU/MAC operation with Data Memory Write, Instruction Type 4:"),
	TO_ENUM(AD218X_amf_move_7, "pm(op, op) = op, amf_cmd             ALU/MAC operation with Program Memory Write, Instruction Type 5:"),
	TO_ENUM(AD218X_amf_move_8, "dm(op, op) = op, amf_cmd             Shift operation with Data Memory Write, Instruction Type 12:"),
	TO_ENUM(AD218X_amf_move_9, "pm(op, op) = op, amf_cmd             Shift operation with Program Memory Write, Instruction Type 13:"),
	TO_ENUM(AD218X_amf_move_a, "amf_cmd, op = dm(op, op), op = pm(op, op)    ALU/MAC with Data and Program Memory Read, Instruction Type 1:"),
	TO_ENUM(AD218X_last, "Undocumented instruction AD218X_last")
};
