const auto instructions_PLFM_ARM = flags_vector_t{
	TO_ENUM(ARM_null, "Undocumented instruction ARM_null"),
	TO_ENUM(ARM_ret, "Return from Subroutine"),
	TO_ENUM(ARM_nop, "No Operation"),
	TO_ENUM(ARM_b, "Branch"),
	TO_ENUM(ARM_bl, "Branch with Link"),
	TO_ENUM(ARM_asr, "Arithmetic Shift Right"),
	TO_ENUM(ARM_lsl, "Logical Shift Left"),
	TO_ENUM(ARM_lsr, "Logical Shift Right"),
	TO_ENUM(ARM_ror, "Rotate Right"),
	TO_ENUM(ARM_neg, "Negate"),
	TO_ENUM(ARM_and, "0 Rd = Op1 & Op2"),
	TO_ENUM(ARM_eor, "1 Rd = Op1 ^ Op2"),
	TO_ENUM(ARM_sub, "2 Rd = Op1 - Op2"),
	TO_ENUM(ARM_rsb, "3 Rd = Op2 - Op1"),
	TO_ENUM(ARM_add, "4 Rd = Op1 + Op2"),
	TO_ENUM(ARM_adc, "5 Rd = Op1 + Op2 + C"),
	TO_ENUM(ARM_sbc, "6 Rd = Op1 - Op2 + C - 1"),
	TO_ENUM(ARM_rsc, "7 Rd = Op2 - Op1 + C - 1"),
	TO_ENUM(ARM_tst, "8 Set cond. codes on Op1 & Op2"),
	TO_ENUM(ARM_teq, "9 Set cond. codes on Op1 ^ Op2"),
	TO_ENUM(ARM_cmp, "A Set cond. codes on Op1 - Op2"),
	TO_ENUM(ARM_cmn, "B Set cond. codes on Op1 + Op2"),
	TO_ENUM(ARM_orr, "C Rd = Op1 | Op2"),
	TO_ENUM(ARM_mov, "D Rd = Op2"),
	TO_ENUM(ARM_bic, "E Rd = Op1 & ~Op2"),
	TO_ENUM(ARM_mvn, "F Rd = ~Op2"),
	TO_ENUM(ARM_mrs, "Transfer PSR to Register"),
	TO_ENUM(ARM_msr, "Transfer Register to PSR"),
	TO_ENUM(ARM_mul, "Multiply"),
	TO_ENUM(ARM_mla, "Multiply-Accumulate"),
	TO_ENUM(ARM_ldr, "Load from Memory"),
	TO_ENUM(ARM_ldrpc, "Indirect Jump"),
	TO_ENUM(ARM_str, "Store to Memory"),
	TO_ENUM(ARM_ldm, "Load Block from Memory"),
	TO_ENUM(ARM_stm, "Store Block to Memory"),
	TO_ENUM(ARM_swp, "Single Data Swap"),
	TO_ENUM(ARM_svc, "Supervisor call"),
	TO_ENUM(ARM_smull, "Signed Multiply long"),
	TO_ENUM(ARM_smlal, "Signed Multiply-Accumulate long"),
	TO_ENUM(ARM_umull, "Unsigned Multiply long"),
	TO_ENUM(ARM_umlal, "Unsigned Multiply-Accumulate long"),
	TO_ENUM(ARM_bx, "Branch to/from Thumb mode"),
	TO_ENUM(ARM_pop, "Pop registers"),
	TO_ENUM(ARM_push, "Push registers"),
	TO_ENUM(ARM_adr, "Load address"),
	TO_ENUM(ARM_bkpt, "Breakpoint"),
	TO_ENUM(ARM_blx1, "Branch with Link and Exchange (immediate address)"),
	TO_ENUM(ARM_blx2, "Branch with Link and Exchange (register indirect)"),
	TO_ENUM(ARM_clz, "Count Leading Zeros"),
	TO_ENUM(ARM_ldrd, "Load pair of registers"),
	TO_ENUM(ARM_pld, "Prepare to load data"),
	TO_ENUM(ARM_qadd, "Saturated addition"),
	TO_ENUM(ARM_qdadd, "Saturated addition with doubling"),
	TO_ENUM(ARM_qdsub, "Saturated subtraction with doubling"),
	TO_ENUM(ARM_qsub, "Saturated subtraction"),
	TO_ENUM(ARM_smlabb, "Signed multiply-accumulate (bottom*bottom)"),
	TO_ENUM(ARM_smlatb, "Signed multiply-accumulate (top*bottom)"),
	TO_ENUM(ARM_smlabt, "Signed multiply-accumulate (bottom*top)"),
	TO_ENUM(ARM_smlatt, "Signed multiply-accumulate (top*top)"),
	TO_ENUM(ARM_smlalbb, "Long signed multiply-accumulate (bottom*bottom)"),
	TO_ENUM(ARM_smlaltb, "Long signed multiply-accumulate (top*bottom)"),
	TO_ENUM(ARM_smlalbt, "Long signed multiply-accumulate (bottom*top)"),
	TO_ENUM(ARM_smlaltt, "Long signed multiply-accumulate (top*top)"),
	TO_ENUM(ARM_smlawb, "Wide signed multiply-accumulate (bottom)"),
	TO_ENUM(ARM_smulwb, "Wide signed multiply (bottom)"),
	TO_ENUM(ARM_smlawt, "Wide signed multiply-accumulate (top)"),
	TO_ENUM(ARM_smulwt, "Wide signed multiply (top)"),
	TO_ENUM(ARM_smulbb, "Signed multiply (bottom*bottom)"),
	TO_ENUM(ARM_smultb, "Signed multiply (top*bottom)"),
	TO_ENUM(ARM_smulbt, "Signed multiply (bottom*top)"),
	TO_ENUM(ARM_smultt, "Signed multiply (top*top)"),
	TO_ENUM(ARM_strd, "Store pair of registers"),
	TO_ENUM(ARM_movl, "Move immediate to register"),
	TO_ENUM(ARM_adrl, "Load address"),
	TO_ENUM(ARM_swbkpt, "WinCE Debugger break"),
	TO_ENUM(ARM_cdp, "Coprocessor Data Processing"),
	TO_ENUM(ARM_cdp2, "Coprocessor Data Processing"),
	TO_ENUM(ARM_ldc, "Load Coprocessor Register"),
	TO_ENUM(ARM_ldc2, "Load Coprocessor Register"),
	TO_ENUM(ARM_stc, "Store Coprocessor Register"),
	TO_ENUM(ARM_stc2, "Store Coprocessor Register"),
	TO_ENUM(ARM_mrc, "Move from Coprocessor to ARM Register"),
	TO_ENUM(ARM_mrc2, "Move from Coprocessor to ARM Register"),
	TO_ENUM(ARM_mcr, "Move from ARM to Coprocessor Register"),
	TO_ENUM(ARM_mcr2, "Move from ARM to Coprocessor Register"),
	TO_ENUM(ARM_mcrr, "Copy pair of registers to coprocessor (5E)"),
	TO_ENUM(ARM_mrrc, "Copy pair of registers from coprocessor (5E)"),
	TO_ENUM(ARM_fabsd, "Floating point Absolute Value, Double precision"),
	TO_ENUM(ARM_fabss, "Floating point Absolute Value, Single precision"),
	TO_ENUM(ARM_faddd, "Floating point Addition, Double precision"),
	TO_ENUM(ARM_fadds, "Floating point Addition, Single precision"),
	TO_ENUM(ARM_fcmpd, "Floating point Compare, Double precision"),
	TO_ENUM(ARM_fcmps, "Floating point Compare, Single precision"),
	TO_ENUM(ARM_fcmped, "Floating point Compare (NaN Exceptions), Double precision"),
	TO_ENUM(ARM_fcmpes, "Floating point Compare (NaN Exceptions), Single precision"),
	TO_ENUM(ARM_fcmpezd, "Floating point Compare (NaN Exceptions) with Zero, Double precision"),
	TO_ENUM(ARM_fcmpezs, "Floating point Compare (NaN Exceptions) with Zero, Single precision"),
	TO_ENUM(ARM_fcmpzd, "Floating point Compare with Zero, Double precision"),
	TO_ENUM(ARM_fcmpzs, "Floating point Compare with Zero, Single precision"),
	TO_ENUM(ARM_fcpyd, "Floating point Copy, Double precision"),
	TO_ENUM(ARM_fcpys, "Floating point Copy, Single precision"),
	TO_ENUM(ARM_fcvtsd, "Floating point Convert to Single precision from Double precision"),
	TO_ENUM(ARM_fcvtds, "Floating point Convert to Double precision from Single precision"),
	TO_ENUM(ARM_fdivd, "Floating point Divide, Double precision"),
	TO_ENUM(ARM_fdivs, "Floating point Divide, Single precision"),
	TO_ENUM(ARM_fldd, "Floating point Load, Double precision"),
	TO_ENUM(ARM_flds, "Floating point Load, Single precision"),
	TO_ENUM(ARM_fldmd, "Floating point Load Multiple, Double precision"),
	TO_ENUM(ARM_fldms, "Floating point Load Multiple, Single precision"),
	TO_ENUM(ARM_fldmx, "Floating point Load Multiple, Unknown precision"),
	TO_ENUM(ARM_fmacd, "Floating point Multiply and Accumulate, Double precision"),
	TO_ENUM(ARM_fmacs, "Floating point Multiply and Accumulate, Single precision"),
	TO_ENUM(ARM_fmscd, "Floating point Multiply and Subtract, Double precision"),
	TO_ENUM(ARM_fmscs, "Floating point Multiply and Subtract, Single precision"),
	TO_ENUM(ARM_fmstat, "Floating point Move Status"),
	TO_ENUM(ARM_fmuld, "Floating point Multiply, Double precision"),
	TO_ENUM(ARM_fmuls, "Floating point Multiply, Single precision"),
	TO_ENUM(ARM_fnegd, "Floating point Negate, Double precision"),
	TO_ENUM(ARM_fnegs, "Floating point Negate, Single precision"),
	TO_ENUM(ARM_fnmacd, "Floating point Negated Multiply and Accumulate, Double precision"),
	TO_ENUM(ARM_fnmacs, "Floating point Negated Multiply and Accumulate, Single precision"),
	TO_ENUM(ARM_fnmscd, "Floating point Negated Multiply and Subtract, Double precision"),
	TO_ENUM(ARM_fnmscs, "Floating point Negated Multiply and Subtract, Single precision"),
	TO_ENUM(ARM_fnmuld, "Floating point Negated Multiply, Double precision"),
	TO_ENUM(ARM_fnmuls, "Floating point Negated Multiply, Single precision"),
	TO_ENUM(ARM_fsitod, "Floating point Convert Signed Integer to Double precision"),
	TO_ENUM(ARM_fsitos, "Floating point Convert Signed Integer to Single precision"),
	TO_ENUM(ARM_fsqrtd, "Floating point Square Root, Double precision"),
	TO_ENUM(ARM_fsqrts, "Floating point Square Root, Single precision"),
	TO_ENUM(ARM_fstd, "Floating point Store, Double precision"),
	TO_ENUM(ARM_fsts, "Floating point Store, Single precision"),
	TO_ENUM(ARM_fstmd, "Floating point Store Multiple, Double precision"),
	TO_ENUM(ARM_fstms, "Floating point Store Multiple, Single precision"),
	TO_ENUM(ARM_fstmx, "Floating point Store Multiple, Unknown precision"),
	TO_ENUM(ARM_fsubd, "Floating point Subtract, Double precision"),
	TO_ENUM(ARM_fsubs, "Floating point Subtract, Single precision"),
	TO_ENUM(ARM_ftosid, "Floating point Convert to Signed Integer from Double precision"),
	TO_ENUM(ARM_ftosis, "Floating point Convert to Signed Integer from Single precision"),
	TO_ENUM(ARM_ftosizd, "Floating point Convert to Signed Integer from Double precision, RZ mode"),
	TO_ENUM(ARM_ftosizs, "Floating point Convert to Signed Integer from Single precision, RZ mode"),
	TO_ENUM(ARM_ftouid, "Floating point Convert to Unsigned Integer from Double precision"),
	TO_ENUM(ARM_ftouis, "Floating point Convert to Unsigned Integer from Single precision"),
	TO_ENUM(ARM_ftouizd, "Floating point Convert to Unsigned Integer from Double precision, RZ mode"),
	TO_ENUM(ARM_ftouizs, "Floating point Convert to Unsigned Integer from Single precision, RZ mode"),
	TO_ENUM(ARM_fuitod, "Floating point Convert Unsigned Integer to Double precision"),
	TO_ENUM(ARM_fuitos, "Floating point Convert Unsigned Integer to Single precision"),
	TO_ENUM(ARM_fmdhr, "Floating point Move to Double precision High from Register"),
	TO_ENUM(ARM_fmrdh, "Floating point Move to Register from Double precision High"),
	TO_ENUM(ARM_fmdlr, "Floating point Move to Double precision Low from Register"),
	TO_ENUM(ARM_fmrdl, "Floating point Move to Register from Double precision Low"),
	TO_ENUM(ARM_fmxr, "Floating point Move to System Register from Register"),
	TO_ENUM(ARM_fmrx, "Floating point Move to Register from System Register"),
	TO_ENUM(ARM_fmsr, "Floating point Move to Single precision from Register"),
	TO_ENUM(ARM_fmrs, "Floating point Move to Register from Single precision"),
	TO_ENUM(ARM_fmdrr, "Floating point Move to Double precision from two Registers"),
	TO_ENUM(ARM_fmrrd, "Floating point Move to two Registers from Double precision"),
	TO_ENUM(ARM_fmsrr, "Floating point Move to two Single precision from two Registers"),
	TO_ENUM(ARM_fmrrs, "Floating point Move to two Registers from two Single precision"),
	TO_ENUM(ARM_bxj, "Branch to Jazelle"),
	TO_ENUM(ARM_mcrr2, "Move to Coprocessor from two ARM Registers"),
	TO_ENUM(ARM_mrrc2, "Move to two ARM Registers from Coprocessor"),
	TO_ENUM(ARM_cps, "Change Processor State"),
	TO_ENUM(ARM_cpsid, "Disable Interrupts"),
	TO_ENUM(ARM_cpsie, "Enable Interrupts"),
	TO_ENUM(ARM_ldrex, "Load Register Exclusive"),
	TO_ENUM(ARM_pkhbt, "Pack halfword bottom + top"),
	TO_ENUM(ARM_pkhtb, "Pack halfword top + bottom"),
	TO_ENUM(ARM_qadd16, "Signed saturating arithmetic hafword-wise addition"),
	TO_ENUM(ARM_qadd8, "Signed saturating arithmetic byte-wise addition"),
	TO_ENUM(ARM_qasx, "Saturating Add and Subtract with Exchange"),
	TO_ENUM(ARM_qaddsubx, "Signed saturating arithmetic exchange, add, substract (old name) (same as ARM_qasx)"),
	TO_ENUM(ARM_qsub16, "Signed saturating arithmetic hafword-wise substraction"),
	TO_ENUM(ARM_qsub8, "Signed saturating arithmetic byte-wise substraction"),
	TO_ENUM(ARM_qsax, "Saturating Subtract and Add with Exchange"),
	TO_ENUM(ARM_qsubaddx, "Signed saturating arithmetic exchange, substract, add (old name) (same as ARM_qsax)"),
	TO_ENUM(ARM_rev, "Byte Reverse Word"),
	TO_ENUM(ARM_rev16, "Byte Reverse Packed Halfword"),
	TO_ENUM(ARM_revsh, "Byte Reverse Signed Halfword"),
	TO_ENUM(ARM_rfe, "Return from exception"),
	TO_ENUM(ARM_sadd16, "Signed arithmetic modulo hafword-wise addition"),
	TO_ENUM(ARM_sadd8, "Signed arithmetic modulo byte-wise addition"),
	TO_ENUM(ARM_sasx, "Signed Add and Subtract with Exchange"),
	TO_ENUM(ARM_saddsubx, "Signed arithmetic modulo exchange, add, substract (old name) (same as ARM_sasx)"),
	TO_ENUM(ARM_sel, "Select bytes"),
	TO_ENUM(ARM_setend, "Set Byte Endianness"),
	TO_ENUM(ARM_shadd16, "Signed arithmetic hafword-wise addition, halving results"),
	TO_ENUM(ARM_shadd8, "Signed arithmetic byte-wise addition, halving results"),
	TO_ENUM(ARM_shasx, "Signed Halving Add and Subtract with Exchange"),
	TO_ENUM(ARM_shaddsubx, "Signed arithmetic exchange, add, substract, halving results (old name) (same as ARM_shasx)"),
	TO_ENUM(ARM_shsub16, "Signed arithmetic hafword-wise substraction, halving results"),
	TO_ENUM(ARM_shsub8, "Signed arithmetic byte-wise substraction, halving results"),
	TO_ENUM(ARM_shsax, "Signed Halving Subtract and Add with Exchange"),
	TO_ENUM(ARM_shsubaddx, "Signed arithmetic exchange, substract, add, halving results (old name) (same as ARM_shsax)"),
	TO_ENUM(ARM_smlad, "Dual signed multiply, add and accumulate"),
	TO_ENUM(ARM_smladx, "Dual signed multiply, add and accumulate crossed"),
	TO_ENUM(ARM_smuad, "Dual signed multiply and add"),
	TO_ENUM(ARM_smuadx, "Dual signed multiply and add crossed"),
	TO_ENUM(ARM_smlald, "Dual signed multiply, add and accumulate long"),
	TO_ENUM(ARM_smlaldx, "Dual signed multiply, add and accumulate long crossed"),
	TO_ENUM(ARM_smlsd, "Dual signed multiply, substract and accumulate"),
	TO_ENUM(ARM_smlsdx, "Dual signed multiply, substract and accumulate crossed"),
	TO_ENUM(ARM_smusd, "Dual signed multiply and substract"),
	TO_ENUM(ARM_smusdx, "Dual signed multiply and substract crossed"),
	TO_ENUM(ARM_smlsld, "Dual signed multiply, substract and accumulate long"),
	TO_ENUM(ARM_smlsldx, "Dual signed multiply, substract and accumulate long crossed"),
	TO_ENUM(ARM_smmla, "Signed most significant word multiply and accumulate truncated"),
	TO_ENUM(ARM_smmlar, "Signed most significant word multiply and accumulate rounded"),
	TO_ENUM(ARM_smmul, "Signed most significant word multiply truncated"),
	TO_ENUM(ARM_smmulr, "Signed most significant word multiply rounded"),
	TO_ENUM(ARM_smmls, "Signed most significant word multiply and substract truncated"),
	TO_ENUM(ARM_smmlsr, "Signed most significant word multiply and substract rounded"),
	TO_ENUM(ARM_srs, "Store Return State"),
	TO_ENUM(ARM_ssat, "Signed Saturate"),
	TO_ENUM(ARM_ssat16, "Signed saturate two halfwords"),
	TO_ENUM(ARM_ssub16, "Signed arithmetic hafword-wise substraction"),
	TO_ENUM(ARM_ssub8, "Signed arithmetic byte-wise substraction"),
	TO_ENUM(ARM_ssax, "Signed Subtract and Add with Exchange"),
	TO_ENUM(ARM_ssubaddx, "Signed arithmetic exchange, substract, add (old name) (same as ARM_ssax)"),
	TO_ENUM(ARM_strex, "Store Register Exclusive"),
	TO_ENUM(ARM_sxtab, "Signed extend byte to word, add"),
	TO_ENUM(ARM_sxtb, "Signed extend byte to word"),
	TO_ENUM(ARM_sxtab16, "Signed extend two bytes to halfwords, add"),
	TO_ENUM(ARM_sxtb16, "Signed extend two bytes to halfwords"),
	TO_ENUM(ARM_sxtah, "Signed extend halfword to word, add"),
	TO_ENUM(ARM_sxth, "Signed extend halfword to word"),
	TO_ENUM(ARM_uadd16, "Unsigned arithmetic modulo hafword-wise addition"),
	TO_ENUM(ARM_uadd8, "Unsigned arithmetic modulo byte-wise addition"),
	TO_ENUM(ARM_uasx, "Unsigned Add and Subtract with Exchange"),
	TO_ENUM(ARM_uaddsubx, "Unsigned arithmetic modulo exchange, add, substract (old name) (same as ARM_uasx)"),
	TO_ENUM(ARM_uhadd16, "Unsigned arithmetic hafword-wise addition, halving results"),
	TO_ENUM(ARM_uhadd8, "Unsigned arithmetic byte-wise addition, halving results"),
	TO_ENUM(ARM_uhasx, "Unsigned Halving Add and Subtract with Exchange"),
	TO_ENUM(ARM_uhaddsubx, "Unsigned arithmetic exchange, add, substract, halving results (old name) (same as ARM_uhasx)"),
	TO_ENUM(ARM_uhsub16, "Unsigned arithmetic hafword-wise substraction, halving results"),
	TO_ENUM(ARM_uhsub8, "Unsigned arithmetic byte-wise substraction, halving results"),
	TO_ENUM(ARM_uhsax, "Unsigned Halving Subtract and Add with Exchange"),
	TO_ENUM(ARM_uhsubaddx, "Unsigned arithmetic exchange, substract, add, halving results (old name) (same as ARM_uhsax)"),
	TO_ENUM(ARM_umaal, "Multiply unsigned double accumulate long"),
	TO_ENUM(ARM_uqadd16, "Unsigned saturating arithmetic hafword-wise addition"),
	TO_ENUM(ARM_uqadd8, "Unsigned saturating arithmetic byte-wise addition"),
	TO_ENUM(ARM_uqasx, "Unsigned Saturating Add and Subtract with Exchange"),
	TO_ENUM(ARM_uqaddsubx, "Unsigned saturating arithmetic exchange, add, substract (old name) (same as ARM_uqasx)"),
	TO_ENUM(ARM_uqsub16, "Unsigned saturating arithmetic hafword-wise substraction"),
	TO_ENUM(ARM_uqsub8, "Unsigned saturating arithmetic byte-wise substraction"),
	TO_ENUM(ARM_uqsax, "Unsigned Saturating Subtract and Add with Exchange"),
	TO_ENUM(ARM_uqsubaddx, "Unsigned saturating arithmetic exchange, substract, add (old name) (same as ARM_uqsax)"),
	TO_ENUM(ARM_usada8, "Unsigned sum of absolute differences and accumulate"),
	TO_ENUM(ARM_usad8, "Unsigned sum of absolute differences"),
	TO_ENUM(ARM_usat, "Unsigned saturate word"),
	TO_ENUM(ARM_usat16, "Unsigned saturate two halfwords"),
	TO_ENUM(ARM_usub16, "Unsigned arithmetic hafword-wise substraction"),
	TO_ENUM(ARM_usub8, "Unsigned arithmetic byte-wise substraction"),
	TO_ENUM(ARM_usax, "Unsigned Subtract and Add with Exchange"),
	TO_ENUM(ARM_usubaddx, "Unsigned arithmetic exchange, substract, add (old name) (same as ARM_usax)"),
	TO_ENUM(ARM_uxtab, "Unsigned extend byte to word, add"),
	TO_ENUM(ARM_uxtb, "Unsigned extend byte to word"),
	TO_ENUM(ARM_uxtab16, "Unsigned extend two bytes to halfwords, add"),
	TO_ENUM(ARM_uxtb16, "Unsigned extend two bytes to halfwords"),
	TO_ENUM(ARM_uxtah, "Unsigned extend halfword to word, add"),
	TO_ENUM(ARM_uxth, "Unsigned extend halfword to word"),
	TO_ENUM(ARM_clrex, "Clear Exclusive"),
	TO_ENUM(ARM_ldrexb, "Load Byte Exclusive"),
	TO_ENUM(ARM_ldrexd, "Load DoubleWord Exclusive"),
	TO_ENUM(ARM_ldrexh, "Load Halfword Exclusive"),
	TO_ENUM(ARM_strexb, "Store Byte Exclusive"),
	TO_ENUM(ARM_strexd, "Store DoubleWord Exclusive"),
	TO_ENUM(ARM_strexh, "Store Halfword Exclusive"),
	TO_ENUM(ARM_yield, "Yield (hint)"),
	TO_ENUM(ARM_sev, "Send Event (hint)"),
	TO_ENUM(ARM_wfe, "Wait For Event (hint)"),
	TO_ENUM(ARM_wfi, "Wait For Interrupt (hint)"),
	TO_ENUM(ARM_smc, "Secure Monitor Call"),
	TO_ENUM(ARM_orn, "Rd = Op1 | ~Op2"),
	TO_ENUM(ARM_movt, "Move Top"),
	TO_ENUM(ARM_sbfx, "Signed Bit Field Extract"),
	TO_ENUM(ARM_ubfx, "Unsigned Bit Field Extract"),
	TO_ENUM(ARM_bfi, "Bit Field Insert"),
	TO_ENUM(ARM_bfc, "Bit Field Clear"),
	TO_ENUM(ARM_tbb, "Table Branch Byte"),
	TO_ENUM(ARM_tbh, "Table Branch Halfword"),
	TO_ENUM(ARM_pli, "Prepare to load code"),
	TO_ENUM(ARM_rbit, "Reverse Bits"),
	TO_ENUM(ARM_it, "If Then"),
	TO_ENUM(ARM_mls, "Multiply and Subtract"),
	TO_ENUM(ARM_sdiv, "Signed Divide"),
	TO_ENUM(ARM_udiv, "Unsigned Divide"),
	TO_ENUM(ARM_cbz, "Compare and Branch on Zero"),
	TO_ENUM(ARM_cbnz, "Compare and Branch on Non-Zero"),
	TO_ENUM(ARM_dsb, "Data Synchronization Barrier"),
	TO_ENUM(ARM_dmb, "Data Memory Barrier"),
	TO_ENUM(ARM_isb, "Instruction Synchronization Barrier"),
	TO_ENUM(ARM_dbg, "Debug Hint"),
	TO_ENUM(ARM_und, "Architecturally undefined instruction"),
	TO_ENUM(ARM_rrx, "Rotate Right with Extend"),
	TO_ENUM(ARM_enterx, "Enter ThumbEE state"),
	TO_ENUM(ARM_leavex, "Leave ThumbEE state"),
	TO_ENUM(ARM_chka, "Check Array"),
	TO_ENUM(ARM_hb, "Handler Branch"),
	TO_ENUM(ARM_hbl, "Handler Branch with Link"),
	TO_ENUM(ARM_hblp, "Handler Branch with Link and Parameter"),
	TO_ENUM(ARM_hbp, "Handler Branch with Parameter"),
	TO_ENUM(ARM_vaba, "Vector Absolute Difference and Accumulate"),
	TO_ENUM(ARM_vabal, "Vector Absolute Difference and Accumulate Long"),
	TO_ENUM(ARM_vabd, "Vector Absolute Difference"),
	TO_ENUM(ARM_vabdl, "Vector Absolute Difference Long"),
	TO_ENUM(ARM_vabs, "Vector Absolute"),
	TO_ENUM(ARM_vacge, "Vector Absolute Compare Greater Than or Equal"),
	TO_ENUM(ARM_vacgt, "Vector Absolute Compare Greater Than"),
	TO_ENUM(ARM_vacle, "Vector Absolute Compare Less Than or Equal"),
	TO_ENUM(ARM_vaclt, "Vector Absolute Compare Less Than"),
	TO_ENUM(ARM_vadd, "Vector Add"),
	TO_ENUM(ARM_vaddhn, "Vector Add and Narrow, returning High Half"),
	TO_ENUM(ARM_vaddl, "Vector Add Long"),
	TO_ENUM(ARM_vaddw, "Vector Add Wide"),
	TO_ENUM(ARM_vand, "Vector Bitwise AND"),
	TO_ENUM(ARM_vbic, "Vector Bitwise Bit Clear"),
	TO_ENUM(ARM_vbif, "Vector Bitwise Insert if False"),
	TO_ENUM(ARM_vbit, "Vector Bitwise Insert if True"),
	TO_ENUM(ARM_vbsl, "Vector Bitwise Select"),
	TO_ENUM(ARM_vceq, "Vector Compare Equal"),
	TO_ENUM(ARM_vcge, "Vector Compare Greater Than or Equal"),
	TO_ENUM(ARM_vcgt, "Vector Compare Greater Than"),
	TO_ENUM(ARM_vcle, "Vector Compare Less Than or Equal"),
	TO_ENUM(ARM_vcls, "Vector Count Leading Sign Bits"),
	TO_ENUM(ARM_vclt, "Vector Compare Less Than"),
	TO_ENUM(ARM_vclz, "Vector Count Leading Zeros"),
	TO_ENUM(ARM_vcmp, "Vector Compare"),
	TO_ENUM(ARM_vcmpe, "Vector Compare (Quiet NaNs trigger Exception)"),
	TO_ENUM(ARM_vcnt, "Vector Count Number of Bits"),
	TO_ENUM(ARM_vcvt, "Vector Convert"),
	TO_ENUM(ARM_vcvtr, "Vector Convert Rounding"),
	TO_ENUM(ARM_vcvtb, "Vector Convert Half-Precision Bottom"),
	TO_ENUM(ARM_vcvtt, "Vector Convert Half-Precision Top"),
	TO_ENUM(ARM_vdiv, "Vector Divide"),
	TO_ENUM(ARM_vdup, "Vector Duplicate"),
	TO_ENUM(ARM_veor, "Vector Bitwise Exclusive OR"),
	TO_ENUM(ARM_vext, "Vector Extract"),
	TO_ENUM(ARM_vfma, "Vector Fused Multiply Accumulate"),
	TO_ENUM(ARM_vfms, "Vector Fused Multiply Substract"),
	TO_ENUM(ARM_vfnma, "Vector Fused Negated Multiply Accumulate"),
	TO_ENUM(ARM_vfnms, "Vector Fused Negated Multiply Substract"),
	TO_ENUM(ARM_vhadd, "Vector Halving Add"),
	TO_ENUM(ARM_vhsub, "Vector Halving Sub"),
	TO_ENUM(ARM_vld1, "Vector Load Single Element"),
	TO_ENUM(ARM_vld2, "Vector Load Two-Element Structures"),
	TO_ENUM(ARM_vld3, "Vector Load Three-Element Structures"),
	TO_ENUM(ARM_vld4, "Vector Load Four-Element Structures"),
	TO_ENUM(ARM_vldm, "Vector Load Multiple"),
	TO_ENUM(ARM_vldr, "Vector Load Register"),
	TO_ENUM(ARM_vmax, "Vector Maximum"),
	TO_ENUM(ARM_vmin, "Vector Minimum"),
	TO_ENUM(ARM_vmla, "Vector Multiply Accumulate"),
	TO_ENUM(ARM_vmlal, "Vector Multiply Accumulate Long"),
	TO_ENUM(ARM_vmls, "Vector Multiply Subtract"),
	TO_ENUM(ARM_vmlsl, "Vector Multiply Subtract Long"),
	TO_ENUM(ARM_vmov, "Vector Move"),
	TO_ENUM(ARM_vmovl, "Vector Move Long"),
	TO_ENUM(ARM_vmovn, "Vector Move and Narrow"),
	TO_ENUM(ARM_vmrs, "Move FPSCR to ARM Register"),
	TO_ENUM(ARM_vmsr, "Move to FPSCR from ARM Register"),
	TO_ENUM(ARM_vmul, "Vector Multiply"),
	TO_ENUM(ARM_vmull, "Vector Multiply Long"),
	TO_ENUM(ARM_vmvn, "Vector Bitwise NOT"),
	TO_ENUM(ARM_vneg, "Vector Negate"),
	TO_ENUM(ARM_vnmla, "Vector Multiply Add Negated"),
	TO_ENUM(ARM_vnmls, "Vector Multiply Substract Negated"),
	TO_ENUM(ARM_vnmul, "Vector Multiply Negated"),
	TO_ENUM(ARM_vorn, "Vector Bitwise OR NOT"),
	TO_ENUM(ARM_vorr, "Vector Bitwise OR"),
	TO_ENUM(ARM_vpadal, "Vector Pairwise Add and Accumulate Long"),
	TO_ENUM(ARM_vpadd, "Vector Pairwise Add"),
	TO_ENUM(ARM_vpaddl, "Vector Pairwise Add Long"),
	TO_ENUM(ARM_vpmax, "Vector Pairwise Maximum"),
	TO_ENUM(ARM_vpmin, "Vector Pairwise Minimum"),
	TO_ENUM(ARM_vpop, "Vector Pop"),
	TO_ENUM(ARM_vpush, "Vector Push"),
	TO_ENUM(ARM_vqabs, "Vector Saturating Absolute"),
	TO_ENUM(ARM_vqadd, "Vector Saturating Add"),
	TO_ENUM(ARM_vqdmlal, "Vector Saturating Doubling Multiply Accumulate Long"),
	TO_ENUM(ARM_vqdmlsl, "Vector Saturating Doubling Multiply Subtract Long"),
	TO_ENUM(ARM_vqdmulh, "Vector Saturating Doubling Multiply Returning High Half"),
	TO_ENUM(ARM_vqdmull, "Vector Saturating Doubling Multiply Long"),
	TO_ENUM(ARM_vqmovn, "Vector Saturating Move and Narrow"),
	TO_ENUM(ARM_vqmovun, "Vector Saturating Move and Narrow, Unsigned result"),
	TO_ENUM(ARM_vqneg, "Vector Saturating Negate"),
	TO_ENUM(ARM_vqrdmulh, "Vector Saturating Rounding Doubling Multiply Returning High Half"),
	TO_ENUM(ARM_vqrshl, "Vector Saturating Rounding Shift Left"),
	TO_ENUM(ARM_vqrshrn, "Vector Saturating Rounding Shift Right, Narrow"),
	TO_ENUM(ARM_vqrshrun, "Vector Saturating Rounding Shift Right, Narrow, Unsigned result"),
	TO_ENUM(ARM_vqshl, "Vector Saturating Shift Left"),
	TO_ENUM(ARM_vqshlu, "Vector Saturating Shift Left, Unsigned result"),
	TO_ENUM(ARM_vqshrn, "Vector Saturating Shift Right, Narrow"),
	TO_ENUM(ARM_vqshrun, "Vector Saturating Shift Right, Narrow, Unsigned result"),
	TO_ENUM(ARM_vqsub, "Vector Saturating Subtract"),
	TO_ENUM(ARM_vraddhn, "Vector Rounding Add and Narrow, returning High Half"),
	TO_ENUM(ARM_vrecpe, "Vector Reciprocal Estimate"),
	TO_ENUM(ARM_vrecps, "Vector Reciprocal Step"),
	TO_ENUM(ARM_vrev16, "Vector Reverse in halfwords"),
	TO_ENUM(ARM_vrev32, "Vector Reverse in words"),
	TO_ENUM(ARM_vrev64, "Vector Reverse in doublewords"),
	TO_ENUM(ARM_vrhadd, "Vector Rounding Halving Add"),
	TO_ENUM(ARM_vrshl, "Vector Rounding Shift Left"),
	TO_ENUM(ARM_vrshr, "Vector Rounding Shift Right"),
	TO_ENUM(ARM_vrshrn, "Vector Rounding Shift Right and Narrow"),
	TO_ENUM(ARM_vrsqrte, "Vector Reciprocal Square Root Estimate"),
	TO_ENUM(ARM_vrsqrts, "Vector Reciprocal Square Root Step"),
	TO_ENUM(ARM_vrsra, "Vector Rounding Shift Right and Accumulate"),
	TO_ENUM(ARM_vrsubhn, "Vector Rounding Subtract and Narrow, returning High Half"),
	TO_ENUM(ARM_vshl, "Vector Shift Left"),
	TO_ENUM(ARM_vshll, "Vector Shift Left Long"),
	TO_ENUM(ARM_vshr, "Vector Shift Right"),
	TO_ENUM(ARM_vshrn, "Vector Shift Right Narrow"),
	TO_ENUM(ARM_vsli, "Vector Shift Left and Insert"),
	TO_ENUM(ARM_vsqrt, "Vector Square Root"),
	TO_ENUM(ARM_vsra, "Vector Shift Right and Accumulate"),
	TO_ENUM(ARM_vsri, "Vector Shift Right and Insert"),
	TO_ENUM(ARM_vst1, "Vector Store Single Element"),
	TO_ENUM(ARM_vst2, "Vector Store Two-Element Structures"),
	TO_ENUM(ARM_vst3, "Vector Store Three-Element Structures"),
	TO_ENUM(ARM_vst4, "Vector Store Four-Element Structures"),
	TO_ENUM(ARM_vstm, "Vector Store Multiple"),
	TO_ENUM(ARM_vstr, "Vector Store Register"),
	TO_ENUM(ARM_vsub, "Vector Subtract"),
	TO_ENUM(ARM_vsubhn, "Vector Subtract and Narrow, returning High Half"),
	TO_ENUM(ARM_vsubl, "Vector Subtract Long"),
	TO_ENUM(ARM_vsubw, "Vector Subtract Wide"),
	TO_ENUM(ARM_vswp, "Vector Swap"),
	TO_ENUM(ARM_vtbl, "Vector Table Lookup"),
	TO_ENUM(ARM_vtbx, "Vector Table Extension"),
	TO_ENUM(ARM_vtrn, "Vector Transpose"),
	TO_ENUM(ARM_vtst, "Vector Test Bits"),
	TO_ENUM(ARM_vuzp, "Vector Unzip"),
	TO_ENUM(ARM_vzip, "Vector Zip"),
	TO_ENUM(ARM_eret, "Exception Return"),
	TO_ENUM(ARM_hvc, "Hypervisor Call"),
	TO_ENUM(ARM_lda, "Load-Acquire Word/Byte/Halfword"),
	TO_ENUM(ARM_stl, "Store-Release Word/Byte/Halfword"),
	TO_ENUM(ARM_ldaex, "Load-Acquire Exclusive Word/Byte/Halfword"),
	TO_ENUM(ARM_stlex, "Store-Release Exclusive Word/Byte/Halfword"),
	TO_ENUM(ARM_vsel, "Floating-point Conditional Select"),
	TO_ENUM(ARM_vmaxnm, "Vector Maximum Numeric"),
	TO_ENUM(ARM_vminnm, "Vector Minimum Numeric"),
	TO_ENUM(ARM_vcvta, "Vector Convert Round to Nearest with Ties to Away"),
	TO_ENUM(ARM_vcvtn, "Vector Convert Round to Nearest with Ties to Even"),
	TO_ENUM(ARM_vcvtp, "Vector Convert Round towards +Infinity"),
	TO_ENUM(ARM_vcvtm, "Vector Convert Round towards -Infinity"),
	TO_ENUM(ARM_vrintx, "Vector Round to Integral, FPSCR rounding mode and signaling inexactness"),
	TO_ENUM(ARM_vrintr, "Vector Round to Integral, FPSCR rounding mode"),
	TO_ENUM(ARM_vrintz, "Vector Round to Integral, Round toward Zero"),
	TO_ENUM(ARM_vrinta, "Vector Round to Integral, Round to Nearest with Ties to Away"),
	TO_ENUM(ARM_vrintn, "Vector Round to Integral, Round to Nearest with Ties to Even"),
	TO_ENUM(ARM_vrintp, "Vector Round to Integral, Round towards +Infinity"),
	TO_ENUM(ARM_vrintm, "Vector Round to Integral, Round towards -Infinity"),
	TO_ENUM(ARM_aesd, "AES single round decryption"),
	TO_ENUM(ARM_aese, "AES single round encryption"),
	TO_ENUM(ARM_aesimc, "AES inverse mix columns"),
	TO_ENUM(ARM_aesmc, "AES mix columns"),
	TO_ENUM(ARM_sha1c, "SHA1 hash update accelerator, choose"),
	TO_ENUM(ARM_sha1m, "SHA1 hash update accelerator, majority"),
	TO_ENUM(ARM_sha1p, "SHA1 hash update accelerator, parity"),
	TO_ENUM(ARM_sha1h, "SHA1 hash update accelerator, rotate left by 30"),
	TO_ENUM(ARM_sha1su0, "SHA1 schedule update accelerator, first part"),
	TO_ENUM(ARM_sha1su1, "SHA1 schedule update accelerator, second part"),
	TO_ENUM(ARM_sha256h, "SHA256 hash update accelerator"),
	TO_ENUM(ARM_sha256h2, "SHA256 hash update accelerator upper part"),
	TO_ENUM(ARM_sha256su0, "SHA256 schedule update accelerator, first part"),
	TO_ENUM(ARM_sha256su1, "SHA256 schedule update accelerator, second part"),
	TO_ENUM(ARM_dcps1, "Debug Change Processor State to EL1"),
	TO_ENUM(ARM_dcps2, "Debug Change Processor State to EL2"),
	TO_ENUM(ARM_dcps3, "Debug Change Processor State to EL3"),
	TO_ENUM(ARM_hlt, "Halting mode software breakpoint"),
	TO_ENUM(ARM_sevl, "Send Event Locally"),
	TO_ENUM(ARM_tbz, "Test and Branch Zero"),
	TO_ENUM(ARM_tbnz, "Test and Branch Non-Zero"),
	TO_ENUM(ARM_br, "Branch To Register"),
	TO_ENUM(ARM_blr, "Branch and Link Register"),
	TO_ENUM(ARM_ldur, "Load Single Register (unscaled offset)"),
	TO_ENUM(ARM_stur, "Store Single Register (unscaled offset)"),
	TO_ENUM(ARM_ldp, "Load Pair"),
	TO_ENUM(ARM_stp, "Store Pair"),
	TO_ENUM(ARM_ldnp, "Load Non-temporal Pair"),
	TO_ENUM(ARM_stnp, "Store Non-temporal Pair"),
	TO_ENUM(ARM_ldtr, "Load Unprivileged Register"),
	TO_ENUM(ARM_sttr, "Store Unprivileged Register"),
	TO_ENUM(ARM_ldxr, "Load Exclusive Register"),
	TO_ENUM(ARM_stxr, "Store Exclusive Register"),
	TO_ENUM(ARM_ldxp, "Load Exclusive Pair"),
	TO_ENUM(ARM_stxp, "Store Exclusive Pair"),
	TO_ENUM(ARM_ldar, "Load-Acquire Register"),
	TO_ENUM(ARM_stlr, "Store-Release Register"),
	TO_ENUM(ARM_ldaxr, "Load-Acquire Exclusive Register"),
	TO_ENUM(ARM_stlxr, "Store-Release Exclusive Register"),
	TO_ENUM(ARM_ldaxp, "Load-Acquire Exclusive Pair"),
	TO_ENUM(ARM_stlxp, "Store Exclusive Pair"),
	TO_ENUM(ARM_prfm, "Prefetch Memory"),
	TO_ENUM(ARM_prfum, "Prefetch Memory (unscaled offset)"),
	TO_ENUM(ARM_movi, "Move Immediate"),
	TO_ENUM(ARM_mvni, "Move Inverted Immediate"),
	TO_ENUM(ARM_movz, "Move with Zero"),
	TO_ENUM(ARM_movn, "Move with Not"),
	TO_ENUM(ARM_movk, "Move with Keep"),
	TO_ENUM(ARM_adrp, "Address of Page"),
	TO_ENUM(ARM_bfm, "Bitfield Move"),
	TO_ENUM(ARM_sbfm, "Signed Bitfield Move"),
	TO_ENUM(ARM_ubfm, "Unsigned Bitfield Move"),
	TO_ENUM(ARM_bfxil, "Bitfield Extract and Insert Low"),
	TO_ENUM(ARM_sbfiz, "Signed Bitfield Insert in Zero"),
	TO_ENUM(ARM_ubfiz, "Signed Bitfield Insert in Zero"),
	TO_ENUM(ARM_extr, "Extract"),
	TO_ENUM(ARM_sxtw, "Signed Extend Word"),
	TO_ENUM(ARM_uxtw, "Unsigned Extend Word (non-existing insn)"),
	TO_ENUM(ARM_eon, "Bitwise exclusive OR NOT"),
	TO_ENUM(ARM_not, "Bitwise NOT"),
	TO_ENUM(ARM_cls, "Count Leading Sign Bits"),
	TO_ENUM(ARM_rev32, "Reverse Bytes in Words"),
	TO_ENUM(ARM_csel, "Conditional Select"),
	TO_ENUM(ARM_csinc, "Conditional Select Increment"),
	TO_ENUM(ARM_csinv, "Conditional Select Invert"),
	TO_ENUM(ARM_csneg, "Conditional Select Negate"),
	TO_ENUM(ARM_cset, "Conditional Set"),
	TO_ENUM(ARM_csetm, "Conditional Set Mask"),
	TO_ENUM(ARM_cinc, "Conditional Increment"),
	TO_ENUM(ARM_cinv, "Conditional Invert"),
	TO_ENUM(ARM_cneg, "Conditional Negate"),
	TO_ENUM(ARM_ngc, "Negate with Carry"),
	TO_ENUM(ARM_ccmn, "Conditional Compare Negative"),
	TO_ENUM(ARM_ccmp, "Conditional Compare"),
	TO_ENUM(ARM_madd, "Multiply-Add"),
	TO_ENUM(ARM_msub, "Multiply-Subtract"),
	TO_ENUM(ARM_mneg, "Multiply-Negate"),
	TO_ENUM(ARM_smaddl, "Signed Multiply-Add Long"),
	TO_ENUM(ARM_smsubl, "Signed Multiply-Subtract Long"),
	TO_ENUM(ARM_smnegl, "Signed Multiply-Negate Long"),
	TO_ENUM(ARM_smulh, "Signed Multiply High"),
	TO_ENUM(ARM_umaddl, "Unsigned Multiply-Add Long"),
	TO_ENUM(ARM_umsubl, "Unsigned Multiply-Subtract Long"),
	TO_ENUM(ARM_umnegl, "Unsigned Multiply-Negate Long"),
	TO_ENUM(ARM_umulh, "Unsigned Multiply High"),
	TO_ENUM(ARM_drps, "Debug Restore Processor State"),
	TO_ENUM(ARM_sys, "System Maintenance Operation"),
	TO_ENUM(ARM_sysl, "System Maintenance Operation With Result"),
	TO_ENUM(ARM_ic, "Instruction Cache Maintenance"),
	TO_ENUM(ARM_dc, "Data Cache Maintenance"),
	TO_ENUM(ARM_at, "Address Translation"),
	TO_ENUM(ARM_tlbi, "TLB Invalidation"),
	TO_ENUM(ARM_hint, "Hint instruction"),
	TO_ENUM(ARM_brk, "Monitor debug-mode breakpoint"),
	TO_ENUM(ARM_uaba, "Unsigned Integer Absolute Difference and Accumulate"),
	TO_ENUM(ARM_saba, "Signed Integer Absolute Difference and Accumulate"),
	TO_ENUM(ARM_uabal, "Unsigned Integer Absolute Difference and Accumulate Long"),
	TO_ENUM(ARM_uabal2, "Unsigned Integer Absolute Difference and Accumulate Long (Second Part)"),
	TO_ENUM(ARM_sabal, "Signed Integer Absolute Difference and Accumulate Long"),
	TO_ENUM(ARM_sabal2, "Signed Integer Absolute Difference and Accumulate Long (Second Part)"),
	TO_ENUM(ARM_uabd, "Unsigned Integer Absolute Difference"),
	TO_ENUM(ARM_sabd, "Signed Integer Absolute Difference"),
	TO_ENUM(ARM_fabd, "Floating-point Absolute Difference"),
	TO_ENUM(ARM_uabdl, "Unsigned Integer Absolute Difference Long"),
	TO_ENUM(ARM_uabdl2, "Unsigned Integer Absolute Difference Long (Second Part)"),
	TO_ENUM(ARM_sabdl, "Signed Integer Absolute Difference Long"),
	TO_ENUM(ARM_sabdl2, "Signed Integer Absolute Difference Long (Second Part)"),
	TO_ENUM(ARM_abs, "Integer Absolute Value"),
	TO_ENUM(ARM_fabs, "Floating-point Absolute Value"),
	TO_ENUM(ARM_facge, "Floating-point Absolute Compare Greater Than or Equal"),
	TO_ENUM(ARM_facgt, "Floating-point Absolute Compare Greater Than"),
	TO_ENUM(ARM_facle, "Floating-point Absolute Compare Less Than or Equal"),
	TO_ENUM(ARM_faclt, "Floating-point Absolute Compare Less Than"),
	TO_ENUM(ARM_fadd, "Floating-point Add"),
	TO_ENUM(ARM_addhn, "Integer Vector Add and Narrow High Half"),
	TO_ENUM(ARM_addhn2, "Integer Vector Add and Narrow High Half (second part)"),
	TO_ENUM(ARM_uaddl, "Unsigned Integer Add Long"),
	TO_ENUM(ARM_uaddl2, "Unsigned Integer Add Long (second part)"),
	TO_ENUM(ARM_saddl, "Signed Integer Add Long"),
	TO_ENUM(ARM_saddl2, "Signed Integer Add Long (second part)"),
	TO_ENUM(ARM_uaddw, "Unsigned Integer Add Wide"),
	TO_ENUM(ARM_uaddw2, "Unsigned Integer Add Wide (second part)"),
	TO_ENUM(ARM_saddw, "Signed Integer Add Wide"),
	TO_ENUM(ARM_saddw2, "Signed Integer Add Wide (second part)"),
	TO_ENUM(ARM_bif, "Bitwise Vector Insert if False"),
	TO_ENUM(ARM_bit, "Bitwise Vector Insert if True"),
	TO_ENUM(ARM_bsl, "Bitwise Vector Select"),
	TO_ENUM(ARM_cmeq, "Ingeger Vector Compare Equal"),
	TO_ENUM(ARM_fcmeq, "Floating-point Vector Compare Equal"),
	TO_ENUM(ARM_cmhs, "Unsigned Compare Greater Than or Equal"),
	TO_ENUM(ARM_cmge, "Signed Compare Greater Than or Equal"),
	TO_ENUM(ARM_fcmge, "Floating-point Compare Greater Than or Equal"),
	TO_ENUM(ARM_cmhi, "Unsigned Compare Greater Than"),
	TO_ENUM(ARM_cmgt, "Signed Compare Greater Than"),
	TO_ENUM(ARM_fcmgt, "Floating-point Compare Greater Than"),
	TO_ENUM(ARM_cmls, "Unsigned Compare Less Than or Equal"),
	TO_ENUM(ARM_cmle, "Signed Compare Less Than or Equal"),
	TO_ENUM(ARM_fcmle, "Floating-point Compare Less Than or Equal"),
	TO_ENUM(ARM_cmlo, "Unsigned Compare Less Than"),
	TO_ENUM(ARM_cmlt, "Signed Compare Less Than"),
	TO_ENUM(ARM_fcmlt, "Floating-point Compare Less Than"),
	TO_ENUM(ARM_fcmp, "Floating-point Compare"),
	TO_ENUM(ARM_fcmpe, "Floating-point Signaling Compare"),
	TO_ENUM(ARM_fccmp, "Floating-point Conditional Quiet Compare"),
	TO_ENUM(ARM_fccmpe, "Floating-point Conditional Signaling Compare"),
	TO_ENUM(ARM_fcsel, "Floating-point Conditional Select"),
	TO_ENUM(ARM_cnt, "Vector Count Non-zero Bits"),
	TO_ENUM(ARM_fcvt, "Floating-point convert precision (scalar)"),
	TO_ENUM(ARM_fcvtzs, "Convert Floating-point to Signed Integer (Round to Zero)"),
	TO_ENUM(ARM_fcvtas, "Convert Floating-point to Signed Integer (Round to Nearest, Ties to Away)"),
	TO_ENUM(ARM_fcvtns, "Convert Floating-point to Signed Integer (Round to Nearest, Ties to Even)"),
	TO_ENUM(ARM_fcvtps, "Convert Floating-point to Signed Integer (Round towards +Infinity)"),
	TO_ENUM(ARM_fcvtms, "Convert Floating-point to Signed Integer (Round towards -Infinity)"),
	TO_ENUM(ARM_fcvtzu, "Convert Floating-point to Unsigned Integer (Round to Zero)"),
	TO_ENUM(ARM_fcvtau, "Convert Floating-point to Unsigned Integer (Round to Nearest, Ties to Away)"),
	TO_ENUM(ARM_fcvtnu, "Convert Floating-point to Unsigned Integer (Round to Nearest, Ties to Even)"),
	TO_ENUM(ARM_fcvtpu, "Convert Floating-point to Unsigned Integer (Round towards +Infinity)"),
	TO_ENUM(ARM_fcvtmu, "Convert Floating-point to Unsigned Integer (Round towards -Infinity)"),
	TO_ENUM(ARM_ucvtf, "Convert Unsigned Integer to Floating-point"),
	TO_ENUM(ARM_scvtf, "Convert Signed Integer to Floating-point"),
	TO_ENUM(ARM_fcvtn, "Floating-point Convert Precision, Narrow"),
	TO_ENUM(ARM_fcvtn2, "Floating-point Convert Precision, Narrow (second part)"),
	TO_ENUM(ARM_fcvtl, "Floating-point Convert Precision, Long"),
	TO_ENUM(ARM_fcvtl2, "Floating-point Convert Precision, Long (second part)"),
	TO_ENUM(ARM_fcvtxn, "Floating-point Convert Precision, Narrow (Round to Odd)"),
	TO_ENUM(ARM_fcvtxn2, "Floating-point Convert Precision, Narrow (Round to Odd) (second part)"),
	TO_ENUM(ARM_frinta, "Floating-point Round to Integral (Round to Nearest, Ties to Away)"),
	TO_ENUM(ARM_frinti, "Floating-point Round to Integral (using FPCR rounding mode)"),
	TO_ENUM(ARM_frintm, "Floating-point Round to Integral (Round towards -Infinity)"),
	TO_ENUM(ARM_frintn, "Floating-point Round to Integral (Round to Nearest, Ties to Even)"),
	TO_ENUM(ARM_frintp, "Floating-point Round to Integral (Round towards +Infinity)"),
	TO_ENUM(ARM_frintx, "Floating-point Round to Integral (using FPCR rounding mode, with exactness test)"),
	TO_ENUM(ARM_frintz, "Floating-point Round to Integral (Round towards Zero)"),
	TO_ENUM(ARM_fmadd, "Floating-point scalar fused multiply-add"),
	TO_ENUM(ARM_fmsub, "Floating-point scalar fused multiply-subtract"),
	TO_ENUM(ARM_fnmadd, "Floating-point scalar negated fused multiply-add"),
	TO_ENUM(ARM_fnmsub, "Floating-point scalar negated fused multiply-subtract"),
	TO_ENUM(ARM_fdiv, "Floating-point Divide"),
	TO_ENUM(ARM_dup, "Duplicate Single Element to All Elements"),
	TO_ENUM(ARM_ins, "Insert Single Element in Another Element"),
	TO_ENUM(ARM_ext, "Bitwise Extract"),
	TO_ENUM(ARM_uhadd, "Unsigned Integer Halving Add"),
	TO_ENUM(ARM_shadd, "Signed Integer Halving Add"),
	TO_ENUM(ARM_uhsub, "Unsigned Integer Halving Subtract"),
	TO_ENUM(ARM_shsub, "Signed Integer Halving Subtract"),
	TO_ENUM(ARM_ld1, "Vector Load Single Element"),
	TO_ENUM(ARM_ld2, "Vector Load Two-Element Structures"),
	TO_ENUM(ARM_ld3, "Vector Load Three-Element Structures"),
	TO_ENUM(ARM_ld4, "Vector Load Four-Element Structures"),
	TO_ENUM(ARM_ld1r, "Vector Load Single Element and Replicate"),
	TO_ENUM(ARM_ld2r, "Vector Load Two-Element Structures and Replicate"),
	TO_ENUM(ARM_ld3r, "Vector Load Three-Element Structures and Replicate"),
	TO_ENUM(ARM_ld4r, "Vector Load Four-Element Structures and Replicate"),
	TO_ENUM(ARM_umax, "Unsigned Integer Maximum"),
	TO_ENUM(ARM_smax, "Signed Integer Maximum"),
	TO_ENUM(ARM_fmax, "Floating-point Maximum"),
	TO_ENUM(ARM_fmaxnm, "Floating-point maxNum()"),
	TO_ENUM(ARM_umin, "Unsigned Integer Minimum"),
	TO_ENUM(ARM_smin, "Signed Integer Minimum"),
	TO_ENUM(ARM_fmin, "Floating-point Minimum"),
	TO_ENUM(ARM_fminnm, "Floating-point minNum()"),
	TO_ENUM(ARM_fmla, "Fused Multiply-Add"),
	TO_ENUM(ARM_umlal2, "Unsigned Integer Multiply-Add Long (second part)"),
	TO_ENUM(ARM_smlal2, "Signed Integer Multiply-Add Long (second part)"),
	TO_ENUM(ARM_fmls, "Fused Multiply-Subtract"),
	TO_ENUM(ARM_umlsl, "Unsigned Integer Multiply-Subtract Long"),
	TO_ENUM(ARM_umlsl2, "Unsigned Integer Multiply-Subtract Long (second part)"),
	TO_ENUM(ARM_smlsl, "Signed Integer Multiply-Subtract Long"),
	TO_ENUM(ARM_smlsl2, "Signed Integer Multiply-Subtract Long (second part)"),
	TO_ENUM(ARM_umov, "Unsigned Integer Move"),
	TO_ENUM(ARM_smov, "Signed Integer Move"),
	TO_ENUM(ARM_fmov, "Floating-point Move"),
	TO_ENUM(ARM_uxtl, "Unsigned Integer Vector Lengthen"),
	TO_ENUM(ARM_uxtl2, "Unsigned Integer Vector Lengthen (second part)"),
	TO_ENUM(ARM_sxtl, "Signed Integer Vector Lengthen"),
	TO_ENUM(ARM_sxtl2, "Signed Integer Vector Lengthen (second part)"),
	TO_ENUM(ARM_xtn, "Integer Vector Narrow"),
	TO_ENUM(ARM_xtn2, "Integer Vector Narrow (second part)"),
	TO_ENUM(ARM_fmul, "Floating-point Vector Multiply"),
	TO_ENUM(ARM_pmul, "Polynomial Vector Multiply"),
	TO_ENUM(ARM_fmulx, "Floating-point Multiply Extended"),
	TO_ENUM(ARM_fnmul, "Floating-point Multiply-Negate"),
	TO_ENUM(ARM_umull2, "Unsigned Integer Vector Multiply Long (second part)"),
	TO_ENUM(ARM_smull2, "Signed Integer Vector Multiply Long (second part)"),
	TO_ENUM(ARM_pmull, "Polynomial Vector Multiply Long"),
	TO_ENUM(ARM_pmull2, "Polynomial Vector Multiply Long (second part)"),
	TO_ENUM(ARM_fneg, "Floating-point Negate"),
	TO_ENUM(ARM_uadalp, "Unsigned Integer Vector Add and Accumulate Long Pair"),
	TO_ENUM(ARM_sadalp, "Signed Integer Vector Add and Accumulate Long Pair"),
	TO_ENUM(ARM_addp, "Integer Vector Add Pair"),
	TO_ENUM(ARM_faddp, "Floating-point Vector Add Pair"),
	TO_ENUM(ARM_uaddlp, "Unsigned Integer Vector Add Long Pair"),
	TO_ENUM(ARM_saddlp, "Signed Integer Vector Add Long Pair"),
	TO_ENUM(ARM_umaxp, "Unsigned Integer Maximum Pair"),
	TO_ENUM(ARM_smaxp, "Signed Integer Maximum Pair"),
	TO_ENUM(ARM_fmaxp, "Floating-point Maximum Pair"),
	TO_ENUM(ARM_fmaxnmp, "Floating-point maxNum Pair"),
	TO_ENUM(ARM_uminp, "Unsigned Integer Minimum Pair"),
	TO_ENUM(ARM_sminp, "Signed Integer Minimum Pair"),
	TO_ENUM(ARM_fminp, "Floating-point Minimum Pair"),
	TO_ENUM(ARM_fminnmp, "Floating-point minNum Pair"),
	TO_ENUM(ARM_sqabs, "Signed Integer Saturating Absolute"),
	TO_ENUM(ARM_uqadd, "Unsigned Integer Saturating Add"),
	TO_ENUM(ARM_sqadd, "Signed Integer Saturating Add"),
	TO_ENUM(ARM_suqadd, "Signed Integer Saturating Accumulate of Unsigned Values"),
	TO_ENUM(ARM_usqadd, "Unsigned Integer Saturating Accumulate of Signed Values"),
	TO_ENUM(ARM_sqdmlal, "Signed Integer Saturating Doubling Multiply Add Long"),
	TO_ENUM(ARM_sqdmlal2, "Signed Integer Saturating Doubling Multiply Add Long (second part)"),
	TO_ENUM(ARM_sqdmlsl, "Signed Integer Saturating Doubling Multiply Subtract Long"),
	TO_ENUM(ARM_sqdmlsl2, "Signed Integer Saturating Doubling Multiply Subtract Long (second part)"),
	TO_ENUM(ARM_sqdmulh, "Signed Integer Saturating Doubling Multiply Returning High Half"),
	TO_ENUM(ARM_sqdmull, "Signed Integer Saturating Doubling Multiply Long"),
	TO_ENUM(ARM_sqdmull2, "Signed Integer Saturating Doubling Multiply Long (second part)"),
	TO_ENUM(ARM_uqxtn, "Unsigned Integer Saturating Vector Narrow"),
	TO_ENUM(ARM_uqxtn2, "Unsigned Integer Saturating Vector Narrow (second part)"),
	TO_ENUM(ARM_sqxtn, "Signed Integer Saturating Vector Narrow"),
	TO_ENUM(ARM_sqxtn2, "Signed Integer Saturating Vector Narrow (second part)"),
	TO_ENUM(ARM_sqxtun, "Signed Integer Saturating Vector and Unsigned Narrow"),
	TO_ENUM(ARM_sqxtun2, "Signed Integer Saturating Vector and Unsigned Narrow (second part)"),
	TO_ENUM(ARM_sqneg, "Signed Integer Saturating Negate"),
	TO_ENUM(ARM_sqrdmulh, "Signed Integer Saturating Rounding Doubling Multiply Returning High Half"),
	TO_ENUM(ARM_uqrshl, "Unsigned Integer Saturating Rounding Shift Left"),
	TO_ENUM(ARM_sqrshl, "Signed Integer Saturating Rounding Shift Left"),
	TO_ENUM(ARM_uqrshrn, "Unsigned Integer Saturating Rounding Shift Right, Narrow"),
	TO_ENUM(ARM_uqrshrn2, "Unsigned Integer Saturating Rounding Shift Right, Narrow (second part)"),
	TO_ENUM(ARM_sqrshrn, "Signed Integer Saturating Rounding Shift Right, Narrow"),
	TO_ENUM(ARM_sqrshrn2, "Signed Integer Saturating Rounding Shift Right, Narrow (second part)"),
	TO_ENUM(ARM_sqrshrun, "Signed Integer Saturating Rounding Shift Right, Narrow, Unsigned result"),
	TO_ENUM(ARM_sqrshrun2, "Signed Integer Saturating Rounding Shift Right, Narrow, Unsigned result (second part)"),
	TO_ENUM(ARM_uqshl, "Unsigned Integer Saturating Shift Left"),
	TO_ENUM(ARM_sqshl, "Signed Integer Saturating Shift Left"),
	TO_ENUM(ARM_sqshlu, "Signed Integer Saturating Shift Left, Unsigned result"),
	TO_ENUM(ARM_uqshrn, "Unsigned Integer Saturating Shift Right, Narrow"),
	TO_ENUM(ARM_uqshrn2, "Unsigned Integer Saturating Shift Right, Narrow (second part)"),
	TO_ENUM(ARM_sqshrn, "Signed Integer Saturating Shift Right, Narrow"),
	TO_ENUM(ARM_sqshrn2, "Signed Integer Saturating Shift Right, Narrow (second part)"),
	TO_ENUM(ARM_sqshrun, "Signed Integer Saturating Shift Right, Narrow, Unsigned result"),
	TO_ENUM(ARM_sqshrun2, "Signed Integer Saturating Shift Right, Narrow, Unsigned result (second part)"),
	TO_ENUM(ARM_uqsub, "Unsigned Integer Saturating Subtract"),
	TO_ENUM(ARM_sqsub, "Signed Integer Saturating Subtract"),
	TO_ENUM(ARM_raddhn, "Integer Rounding Add and Narrow, returning High Half"),
	TO_ENUM(ARM_raddhn2, "Integer Rounding Add and Narrow, returning High Half (second part)"),
	TO_ENUM(ARM_urecpe, "Unsigned Integer Reciprocal Estimate"),
	TO_ENUM(ARM_frecpe, "Floating-point Reciprocal Estimate"),
	TO_ENUM(ARM_frecps, "Floating-point Reciprocal Step"),
	TO_ENUM(ARM_frecpx, "Floating-point Reciprocal Exponent"),
	TO_ENUM(ARM_rev64, "Reverse doublewords"),
	TO_ENUM(ARM_urhadd, "Unsigned Integer Rounding Halving Add"),
	TO_ENUM(ARM_srhadd, "Signed Integer Rounding Halving Add"),
	TO_ENUM(ARM_urshl, "Unsigned Integer Rounding Shift Left"),
	TO_ENUM(ARM_srshl, "Signed Integer Rounding Shift Left"),
	TO_ENUM(ARM_urshr, "Unsigned Integer Rounding Shift Right"),
	TO_ENUM(ARM_srshr, "Signed Integer Rounding Shift Right"),
	TO_ENUM(ARM_rshrn, "Integer Rounding Shift Right and Narrow"),
	TO_ENUM(ARM_rshrn2, "Integer Rounding Shift Right and Narrow (second part)"),
	TO_ENUM(ARM_ursqrte, "Unsigned Integer Reciprocal Square Root Estimate"),
	TO_ENUM(ARM_frsqrte, "Floating-point Reciprocal Square Root Estimate"),
	TO_ENUM(ARM_frsqrts, "Floating-point Reciprocal Square Root Step"),
	TO_ENUM(ARM_ursra, "Unsigned Integer Rounding Shift Right and Accumulate"),
	TO_ENUM(ARM_srsra, "Signed Integer Rounding Shift Right and Accumulate"),
	TO_ENUM(ARM_rsubhn, "Integer Subtract and Narrow, returning High Half"),
	TO_ENUM(ARM_rsubhn2, "Integer Subtract and Narrow, returning High Half (second part)"),
	TO_ENUM(ARM_ushl, "Unsigned Integer Shift Left"),
	TO_ENUM(ARM_sshl, "Signed Integer Shift Left"),
	TO_ENUM(ARM_ushll, "Unsigned Integer Shift Left Long"),
	TO_ENUM(ARM_ushll2, "Unsigned Integer Shift Left Long (second part)"),
	TO_ENUM(ARM_sshll, "Signed Integer Shift Left Long"),
	TO_ENUM(ARM_sshll2, "Signed Integer Shift Left Long (second part)"),
	TO_ENUM(ARM_ushr, "Unsigned Integer Shift Right"),
	TO_ENUM(ARM_sshr, "Signed Integer Shift Right"),
	TO_ENUM(ARM_shrn, "Integer Shift Right Narrow"),
	TO_ENUM(ARM_shrn2, "Integer Shift Right Narrow (second part)"),
	TO_ENUM(ARM_shl, "Shift Left"),
	TO_ENUM(ARM_shll, "Shift Left Long"),
	TO_ENUM(ARM_shll2, "Shift Left Long (second part)"),
	TO_ENUM(ARM_sli, "Integer Vector Shift Left and Insert"),
	TO_ENUM(ARM_fsqrt, "Floating-point Square Root"),
	TO_ENUM(ARM_usra, "Unsigned Integer Shift Right and Accumulate"),
	TO_ENUM(ARM_ssra, "Signed Integer Shift Right and Accumulate"),
	TO_ENUM(ARM_sri, "Integer Shift Right and Insert"),
	TO_ENUM(ARM_st1, "Vector Store Single Element"),
	TO_ENUM(ARM_st2, "Vector Store Two-Element Structures"),
	TO_ENUM(ARM_st3, "Vector Store Three-Element Structures"),
	TO_ENUM(ARM_st4, "Vector Store Four-Element Structures"),
	TO_ENUM(ARM_fsub, "Floating-point Subtract"),
	TO_ENUM(ARM_subhn, "Integer Subtract and Narrow, returning High Half"),
	TO_ENUM(ARM_subhn2, "Integer Subtract and Narrow, returning High Half (second part)"),
	TO_ENUM(ARM_usubl, "Unsigned Integer Subtract Long"),
	TO_ENUM(ARM_usubl2, "Unsigned Integer Subtract Long (second part)"),
	TO_ENUM(ARM_ssubl, "Signed Integer Subtract Long"),
	TO_ENUM(ARM_ssubl2, "Signed Integer Subtract Long (second part)"),
	TO_ENUM(ARM_usubw, "Unsigned Integer Subtract Wide"),
	TO_ENUM(ARM_usubw2, "Unsigned Integer Subtract Wide (second part)"),
	TO_ENUM(ARM_ssubw, "Signed Integer Subtract Wide"),
	TO_ENUM(ARM_ssubw2, "Signed Integer Subtract Wide (second part)"),
	TO_ENUM(ARM_tbl, "Vector Table Lookup"),
	TO_ENUM(ARM_tbx, "Vector Table Extension"),
	TO_ENUM(ARM_trn1, "Vector Element Transpose (primary)"),
	TO_ENUM(ARM_trn2, "Vector Element Transpose (secondary)"),
	TO_ENUM(ARM_cmtst, "Integer Compare Mask Bitwise Test"),
	TO_ENUM(ARM_uzp1, "Vector Element Unzip (primary)"),
	TO_ENUM(ARM_uzp2, "Vector Element Unzip (secondary)"),
	TO_ENUM(ARM_zip1, "Vector Element Zip (primary)"),
	TO_ENUM(ARM_zip2, "Vector Element Zip (secondary)"),
	TO_ENUM(ARM_addv, "Integer Sum Elements in Vector"),
	TO_ENUM(ARM_uaddlv, "Unsigned Integer Sum Elements in Vector Long"),
	TO_ENUM(ARM_saddlv, "Signed Integer Sum Elements in Vector Long"),
	TO_ENUM(ARM_umaxv, "Unsigned Integer Max Element in Vector"),
	TO_ENUM(ARM_smaxv, "Signed Integer Max Element in Vector"),
	TO_ENUM(ARM_fmaxv, "Floating-point Max Element in Vector"),
	TO_ENUM(ARM_fmaxnmv, "Floating-point maxNum Element in Vector"),
	TO_ENUM(ARM_uminv, "Unsigned Integer Min Element in Vector"),
	TO_ENUM(ARM_sminv, "Signed Integer Min Element in Vector"),
	TO_ENUM(ARM_fminv, "Floating-point Min Element in Vector"),
	TO_ENUM(ARM_fminnmv, "Floating-point minNum Element in Vector"),
	TO_ENUM(ARM_swpl, "Swap value with memory, Release"),
	TO_ENUM(ARM_swpa, "Swap value with memory, Acquire"),
	TO_ENUM(ARM_swpal, "Swap value with memory, Acquire and release"),
	TO_ENUM(ARM_ldapr, "Load-Acquire RCpc Register"),
	TO_ENUM(ARM_ldadd, "Atomic add on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldaddl, "Atomic add on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldadda, "Atomic add on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldaddal, "Atomic add on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stadd, "Atomic add on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_staddl, "Atomic add on value in memory (no return), Release"),
	TO_ENUM(ARM_ldclr, "Atomic bit clear on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldclrl, "Atomic bit clear on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldclra, "Atomic bit clear on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldclral, "Atomic bit clear on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stclr, "Atomic bit clear on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_stclrl, "Atomic bit clear on value in memory (no return), Release"),
	TO_ENUM(ARM_ldeor, "Atomic exclusive OR on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldeorl, "Atomic exclusive OR on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldeora, "Atomic exclusive OR on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldeoral, "Atomic exclusive OR on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_steor, "Atomic exclusive OR on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_steorl, "Atomic exclusive OR on value in memory (no return), Release"),
	TO_ENUM(ARM_ldset, "Atomic bit set on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldsetl, "Atomic bit set on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldseta, "Atomic bit set on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldsetal, "Atomic bit set on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stset, "Atomic bit set on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_stsetl, "Atomic bit set on value in memory (no return), Release"),
	TO_ENUM(ARM_ldsmax, "Atomic signed maximum  on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldsmaxl, "Atomic signed maximum  on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldsmaxa, "Atomic signed maximum  on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldsmaxal, "Atomic signed maximum  on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stsmax, "Atomic signed maximum  on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_stsmaxl, "Atomic signed maximum  on value in memory (no return), Release"),
	TO_ENUM(ARM_ldsmin, "Atomic signed minimum  on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldsminl, "Atomic signed minimum  on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldsmina, "Atomic signed minimum  on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldsminal, "Atomic signed minimum  on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stsmin, "Atomic signed minimum  on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_stsminl, "Atomic signed minimum  on value in memory (no return), Release"),
	TO_ENUM(ARM_ldumax, "Atomic unsigned maximum  on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_ldumaxl, "Atomic unsigned maximum  on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldumaxa, "Atomic unsigned maximum  on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_ldumaxal, "Atomic unsigned maximum  on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stumax, "Atomic unsigned maximum  on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_stumaxl, "Atomic unsigned maximum  on value in memory (no return), Release"),
	TO_ENUM(ARM_ldumin, "Atomic unsigned minimum  on value in memory (return initial value), No memory ordering"),
	TO_ENUM(ARM_lduminl, "Atomic unsigned minimum  on value in memory (return initial value), Release"),
	TO_ENUM(ARM_ldumina, "Atomic unsigned minimum  on value in memory (return initial value), Acquire"),
	TO_ENUM(ARM_lduminal, "Atomic unsigned minimum  on value in memory (return initial value), Acquire and release"),
	TO_ENUM(ARM_stumin, "Atomic unsigned minimum  on value in memory (no return), No memory ordering"),
	TO_ENUM(ARM_stuminl, "Atomic unsigned minimum  on value in memory (no return), Release"),
	TO_ENUM(ARM_cas, "Compare and Swap , No memory ordering"),
	TO_ENUM(ARM_casl, "Compare and Swap, Release"),
	TO_ENUM(ARM_casa, "Compare and Swap, Acquire"),
	TO_ENUM(ARM_casal, "Compare and Swap, Acquire and release"),
	TO_ENUM(ARM_casp, "Compare and Swap Pair, No memory ordering"),
	TO_ENUM(ARM_caspl, "Compare and Swap Pair, Release"),
	TO_ENUM(ARM_caspa, "Compare and Swap Pair, Acquire"),
	TO_ENUM(ARM_caspal, "Compare and Swap Pair, Acquire and release"),
	TO_ENUM(ARM_ldlar, "Load LOAcquire Register"),
	TO_ENUM(ARM_stllr, "Store LORelease Register"),
	TO_ENUM(ARM_sqrdmlah, "Signed Saturating Rounding Doubling Multiply Accumulate"),
	TO_ENUM(ARM_sqrdmlsh, "Signed Saturating Rounding Doubling Multiply Subtract"),
	TO_ENUM(ARM_pac, "Pointer Authentication Code for Data/Instruction address/generic"),
	TO_ENUM(ARM_aut, "Authenticate Data/Instruction address"),
	TO_ENUM(ARM_xpac, "Strip Pointer Authentication Code"),
	TO_ENUM(ARM_ldrd2, "Load pair of registers"),
	TO_ENUM(ARM_strd2, "Store pair of registers"),
	TO_ENUM(ARM_crc32, "CRC32 using polynomial 0x04C11DB7"),
	TO_ENUM(ARM_crc32c, "CRC32 using polynomial 0x1EDC6F41"),
	TO_ENUM(ARM_tt, "Test Target (query the Security state and access permissions of a memory location)"),
	TO_ENUM(ARM_tta, "Test Target Alternate Domain (query the Security state and access permissions of a memory location for a Non-secure access)"),
	TO_ENUM(ARM_sg, "Secure Gateway"),
	TO_ENUM(ARM_vlldm, "Floating-point Lazy Load Multiple"),
	TO_ENUM(ARM_vlstm, "Floating-point Lazy Store Multiple"),
	TO_ENUM(ARM_pldw, "Preload Data for write"),
	TO_ENUM(ARM_vqrdmlah, "Vector Saturating Rounding Doubling Multiply Accumulate Returning High Half."),
	TO_ENUM(ARM_vqrdmlsh, "Vector Saturating Rounding Doubling Multiply Subtract Returning High Half"),
	TO_ENUM(ARM_vmovx, "Vector Move extraction"),
	TO_ENUM(ARM_vins, "Vector move Insertion."),
	TO_ENUM(ARM_vjcvt, "Javascript Convert to signed fixed-point, rounding toward Zero"),
	TO_ENUM(ARM_fjcvtzs, "Javascript Convert to signed fixed-point, rounding toward Zero"),
	TO_ENUM(ARM_ldapur, "Load-Acquire RCpc Register (unscaled offset)"),
	TO_ENUM(ARM_stlur, "Store-Release Register (unscaled offset)"),
	TO_ENUM(ARM_cfinv, "Invert Carry Flag"),
	TO_ENUM(ARM_rmif, "Rotate value and mask into flags"),
	TO_ENUM(ARM_setf8, "set flags from value (8-bit)"),
	TO_ENUM(ARM_setf16, "set flags from value (16-bit)"),
	TO_ENUM(ARM_xaflag, "Convert floating-point condition flags to ARM format"),
	TO_ENUM(ARM_axflag, "Convert floating-point condition flags from ARM to external format."),
	TO_ENUM(ARM_addg, "Add with Tag"),
	TO_ENUM(ARM_subg, "Subtract with Tag"),
	TO_ENUM(ARM_subp, "Subtract Pointer"),
	TO_ENUM(ARM_cmpp, "Compare with Tag"),
	TO_ENUM(ARM_irg, "Insert Random Tag"),
	TO_ENUM(ARM_gmi, "Tag Mask Insert"),
	TO_ENUM(ARM_stg, "Store Allocation Tag"),
	TO_ENUM(ARM_stzg, "Store Allocation Tag, Zeroing"),
	TO_ENUM(ARM_stzgm, "Store Tag and Zero Multiple"),
	TO_ENUM(ARM_st2g, "Store Allocation Tags"),
	TO_ENUM(ARM_stz2g, "Store Allocation Tags, Zeroing"),
	TO_ENUM(ARM_stgm, "Store Tag Multiple"),
	TO_ENUM(ARM_stgp, "Store Allocation Tag and Pair of registers"),
	TO_ENUM(ARM_ldg, "Load Allocation Tag"),
	TO_ENUM(ARM_ldgm, "Load Tag Multiple"),
	TO_ENUM(ARM_bti, "Branch Target Identification"),
	TO_ENUM(ARM_sb, "Speculation Barrier"),
	TO_ENUM(ARM_ssbb, "Speculative Store Bypass Barrier"),
	TO_ENUM(ARM_pssbb, "Physical Speculative Store Bypass Barrier"),
	TO_ENUM(ARM_frint32x, "Floating-point Round to 32-bit Integer, using current rounding mode"),
	TO_ENUM(ARM_frint32z, "Floating-point Round to 32-bit Integer toward Zero"),
	TO_ENUM(ARM_frint64x, "Floating-point Round to 32-bit Integer, using current rounding mode"),
	TO_ENUM(ARM_frint64z, "Floating-point Round to 32-bit Integer toward Zero"),
	TO_ENUM(ARM_bcax, "Bit Clear and exclusive-OR"),
	TO_ENUM(ARM_eor3, "Three-way Exclusive-OR"),
	TO_ENUM(ARM_rax1, "Rotate and Exclusive-OR"),
	TO_ENUM(ARM_xar, "Exclusive-OR and Rotate"),
	TO_ENUM(ARM_sha512h, "SHA512 Hash update part 1"),
	TO_ENUM(ARM_sha512h2, "SHA512 Hash update part 2"),
	TO_ENUM(ARM_sha512su0, "SHA512 Schedule Update 0"),
	TO_ENUM(ARM_sha512su1, "SHA512 Schedule Update 1"),
	TO_ENUM(ARM_sm3partw1, "Undocumented instruction ARM_sm3partw1"),
	TO_ENUM(ARM_sm3partw2, "Undocumented instruction ARM_sm3partw2"),
	TO_ENUM(ARM_sm3ss1, "Undocumented instruction ARM_sm3ss1"),
	TO_ENUM(ARM_sm3tt1a, "Undocumented instruction ARM_sm3tt1a"),
	TO_ENUM(ARM_sm3tt1b, "Undocumented instruction ARM_sm3tt1b"),
	TO_ENUM(ARM_sm3tt2a, "Undocumented instruction ARM_sm3tt2a"),
	TO_ENUM(ARM_sm3tt2b, "Undocumented instruction ARM_sm3tt2b"),
	TO_ENUM(ARM_sm4e, "Undocumented instruction ARM_sm4e"),
	TO_ENUM(ARM_sm4ekey, "Undocumented instruction ARM_sm4ekey"),
	TO_ENUM(ARM_sudot, "Undocumented instruction ARM_sudot"),
	TO_ENUM(ARM_ummla, "Undocumented instruction ARM_ummla"),
	TO_ENUM(ARM_usdot, "Undocumented instruction ARM_usdot"),
	TO_ENUM(ARM_usmmla, "Undocumented instruction ARM_usmmla"),
	TO_ENUM(ARM_sdot, "Undocumented instruction ARM_sdot"),
	TO_ENUM(ARM_udot, "Undocumented instruction ARM_udot"),
	TO_ENUM(ARM_fmlal, "Undocumented instruction ARM_fmlal"),
	TO_ENUM(ARM_fmlal2, "Undocumented instruction ARM_fmlal2"),
	TO_ENUM(ARM_fmlsl, "Undocumented instruction ARM_fmlsl"),
	TO_ENUM(ARM_fmlsl2, "Undocumented instruction ARM_fmlsl2"),
	TO_ENUM(ARM_bfmmla, "Undocumented instruction ARM_bfmmla"),
	TO_ENUM(ARM_bfmlalb, "Undocumented instruction ARM_bfmlalb"),
	TO_ENUM(ARM_bfmlalt, "Undocumented instruction ARM_bfmlalt"),
	TO_ENUM(ARM_bfdot, "Undocumented instruction ARM_bfdot"),
	TO_ENUM(ARM_bfcvtn, "Undocumented instruction ARM_bfcvtn"),
	TO_ENUM(ARM_bfcvtn2, "Undocumented instruction ARM_bfcvtn2"),
	TO_ENUM(ARM_bfcvt, "Undocumented instruction ARM_bfcvt"),
	TO_ENUM(ARM_trap, "Undefined opcode used for debugging"),
	TO_ENUM(ARM_trap2, "Undefined opcode used for debugging"),
	TO_ENUM(ARM_genter, "Enter guarded execution mode"),
	TO_ENUM(ARM_gexit, "Exit guarded execution mode"),
	TO_ENUM(ARM_wkdmc, "Compress memory page"),
	TO_ENUM(ARM_wkdmd, "Decompress memory page"),
	TO_ENUM(ARM_sdsb, "Strong data synchronization barrier"),
	TO_ENUM(ARM_amx, "AMX instruction"),
	TO_ENUM(ARM_mul53lo, "Multiply 2 53-bit pairs and store low 53 bits"),
	TO_ENUM(ARM_mul53hi, "Multiply 2 53-bit pairs and store high 53 bits"),
	TO_ENUM(ARM_vbrsr, "Vector Bit Reverse and Shift Right"),
	TO_ENUM(ARM_vcmul, "Vector Complex Multiply"),
	TO_ENUM(ARM_vfmas, "Vector Fused Multiply Accumulate Scalar"),
	TO_ENUM(ARM_vmaxa, "Vector Maximum Absolute"),
	TO_ENUM(ARM_vmaxnma, "Vector Maximum Absolute (floating-point)"),
	TO_ENUM(ARM_vmina, "Vector Minimum Absolute"),
	TO_ENUM(ARM_vminnma, "Vector Minimum Absolute (floating-point)"),
	TO_ENUM(ARM_vmlas, "Vector Multiply Accumulate Scalar"),
	TO_ENUM(ARM_vmovnb, "Vector Move and Narrow Bottom"),
	TO_ENUM(ARM_vmovnt, "Vector Move and Narrow Top"),
	TO_ENUM(ARM_vmulh, "Vector Multiply Returning High Half"),
	TO_ENUM(ARM_vrmulh, "Vector Rounding Multiply Returning High Half"),
	TO_ENUM(ARM_vmullb, "Vector Multiply Long Bottom"),
	TO_ENUM(ARM_vmullt, "Vector Multiply Long Top"),
	TO_ENUM(ARM_vqdmladh, "Vector Saturating Doubling Multiply Add Dual Returning High Half"),
	TO_ENUM(ARM_vqdmladhX, "Vector Saturating Doubling Multiply Add Dual Returning High Half (exchange)"),
	TO_ENUM(ARM_vqrdmladh, "Vector Saturating Rounding Doubling Multiply Add Dual Returning High Half"),
	TO_ENUM(ARM_vqrdmladhX, "Vector Saturating Rounding Doubling Multiply Add Dual Returning High Half (exchange)"),
	TO_ENUM(ARM_vqdmlah, "Vector Saturating Doubling Multiply Accumulate"),
	TO_ENUM(ARM_vqdmlash, "Vector Saturating Doubling Multiply Accumulate Scalar High Half"),
	TO_ENUM(ARM_vqrdmlash, "Vector Saturating Rounding Doubling Multiply Accumulate Scalar High Half"),
	TO_ENUM(ARM_vqdmlsdh, "Vector Saturating Doubling Multiply Subtract Dual Returning High Half"),
	TO_ENUM(ARM_vqdmlsdhX, "Vector Saturating Doubling Multiply Subtract Dual Returning High Half (exchange)"),
	TO_ENUM(ARM_vqrdmlsdh, "Vector Saturating Rounding Doubling Multiply Subtract Dual Returning High Half"),
	TO_ENUM(ARM_vqrdmlsdhX, "Vector Saturating Rounding Doubling Multiply Subtract Dual Returning High Half (exchange)"),
	TO_ENUM(ARM_vqmovnb, "Vector Saturating Move and Narrow Bottom"),
	TO_ENUM(ARM_vqmovnt, "Vector Saturating Move and Narrow Top"),
	TO_ENUM(ARM_vqmovunb, "Vector Saturating Move Unsigned and Narrow Bottom"),
	TO_ENUM(ARM_vqmovunt, "Vector Saturating Move Unsigned and Narrow Top"),
	TO_ENUM(ARM_vshllb, "Vector Shift Left Long Bottom"),
	TO_ENUM(ARM_vshllt, "Vector Shift Left Long Top"),
	TO_ENUM(ARM_vmladav, "Vector Multiply Add Dual Accumulate Across Vector"),
	TO_ENUM(ARM_vmladavX, "Vector Multiply Add Dual Accumulate Across Vector (exchange)"),
	TO_ENUM(ARM_vmladavA, "Vector Multiply Add Dual Accumulate Across Vector (accumulate)"),
	TO_ENUM(ARM_vmladavAX, "Vector Multiply Add Dual Accumulate Across Vector (accumulate, exchange)"),
	TO_ENUM(ARM_vmlsdav, "Vector Multiply Subtract Dual Accumulate Across Vector"),
	TO_ENUM(ARM_vmlsdavX, "Vector Multiply Subtract Dual Accumulate Across Vector (exchange)"),
	TO_ENUM(ARM_vmlsdavA, "Vector Multiply Subtract Dual Accumulate Across Vector (accumulate)"),
	TO_ENUM(ARM_vmlsdavAX, "Vector Multiply Subtract Dual Accumulate Across Vector (accumulate, exchange)"),
	TO_ENUM(ARM_vmlaldav, "Vector Multiply Add Long Dual Accumulate Across Vector"),
	TO_ENUM(ARM_vmlaldavX, "Vector Multiply Add Long Dual Accumulate Across Vector (exchange)"),
	TO_ENUM(ARM_vmlaldavA, "Vector Multiply Add Long Dual Accumulate Across Vector (accumulate)"),
	TO_ENUM(ARM_vmlaldavAX, "Vector Multiply Add Long Dual Accumulate Across Vector (accumulate, exchange)"),
	TO_ENUM(ARM_vmlsldav, "Vector Multiply Subtract Long Dual Accumulate Across Vector"),
	TO_ENUM(ARM_vmlsldavX, "Vector Multiply Subtract Long Dual Accumulate Across Vector (exchange)"),
	TO_ENUM(ARM_vmlsldavA, "Vector Multiply Subtract Long Dual Accumulate Across Vector (accumulate)"),
	TO_ENUM(ARM_vmlsldavAX, "Vector Multiply Subtract Long Dual Accumulate Across Vector (accumulate, exchange)"),
	TO_ENUM(ARM_vrmlsldavh, "Vector Rounding Multiply Subtract Long Dual Accumulate Across Vector Returning High 64 bits"),
	TO_ENUM(ARM_vrmlsldavhX, "Vector Rounding Multiply Subtract Long Dual Accumulate Across Vector Returning High 64 bits (exchange)"),
	TO_ENUM(ARM_vrmlsldavhA, "Vector Rounding Multiply Subtract Long Dual Accumulate Across Vector Returning High 64 bits (accumulate)"),
	TO_ENUM(ARM_vrmlsldavhAX, "Vector Rounding Multiply Subtract Long Dual Accumulate Across Vector Returning High 64 bits (accumulate, exchange)"),
	TO_ENUM(ARM_vidup, "Vector Increment and Duplicate"),
	TO_ENUM(ARM_vddup, "Vector Decrement and Duplicate"),
	TO_ENUM(ARM_viwdup, "Vector Increment with Wrap and Duplicate"),
	TO_ENUM(ARM_vdwdup, "Vector Decrement with Wrap and Duplicate"),
	TO_ENUM(ARM_vhcadd, "Vector Halving Complex Add with Rotate"),
	TO_ENUM(ARM_vcadd, "Vector Complex Add with Rotate"),
	TO_ENUM(ARM_vadc, "Whole Vector Add With Carry"),
	TO_ENUM(ARM_vadcI, "Whole Vector Add With Carry (initial carry is 1)"),
	TO_ENUM(ARM_sbdc, "Whole Vector Subtract With Carry"),
	TO_ENUM(ARM_vsbcI, "Whole Vector Subtract With Carry (initial carry is 1)"),
	TO_ENUM(ARM_vqdmullb, "Vector Multiply Long Bottom"),
	TO_ENUM(ARM_vqdmullt, "Vector Multiply Long Top"),
	TO_ENUM(ARM_vpsel, "Vector Predicated Select"),
	TO_ENUM(ARM_vcmpv, "Vector Compare (vector)"),
	TO_ENUM(ARM_vpt, "Vector Predicate Then"),
	TO_ENUM(ARM_vpnot, "Vector Predicate NOT"),
	TO_ENUM(ARM_vpst, "Vector Predicate Set Then"),
	TO_ENUM(ARM_vmaxv, "Vector Maximum Across Vector"),
	TO_ENUM(ARM_vmaxav, "Vector Maximum Absolute Across Vector"),
	TO_ENUM(ARM_vminv, "Vector Minimum Across Vector"),
	TO_ENUM(ARM_vminav, "Vector Minimum Absolute Across Vector"),
	TO_ENUM(ARM_vmaxnmv, "Vector Maximum Across Vector (floating-point)"),
	TO_ENUM(ARM_vmaxnmav, "Vector Maximum Absolute Across Vector (floating-point)"),
	TO_ENUM(ARM_vminnmv, "Vector Minimum Across Vector (floating-point)"),
	TO_ENUM(ARM_vminnmav, "Vector Minimum Absolute Across Vector (floating-point)"),
	TO_ENUM(ARM_vqshrnb, "Vector Saturating Shift Right and Narrow Bottom"),
	TO_ENUM(ARM_vqshrnt, "Vector Saturating Shift Right and Narrow Top"),
	TO_ENUM(ARM_vqrshrnb, "Vector Saturating Rounding Shift Right and Narrow Bottom"),
	TO_ENUM(ARM_vqrshrnt, "Vector Saturating Rounding Shift Right and Narrow Top"),
	TO_ENUM(ARM_vqshrunb, "Vector Saturating Shift Right Unsigned and Narrow Bottom"),
	TO_ENUM(ARM_vqshrunt, "Vector Saturating Shift Right Unsigned and Narrow Top"),
	TO_ENUM(ARM_vqrshrunb, "Vector Saturating Rounding Shift Right Unsigned and Narrow Bottom"),
	TO_ENUM(ARM_vqrshrunt, "Vector Saturating Rounding Shift Right Unsigned and Narrow Top"),
	TO_ENUM(ARM_vshrnb, "Vector Shift Right and Narrow Bottom"),
	TO_ENUM(ARM_vshrnt, "Vector Shift Right and Narrow Top"),
	TO_ENUM(ARM_vrshrnb, "Vector Rounding Shift Right and Narrow Bottom"),
	TO_ENUM(ARM_vrshrnt, "Vector Rounding Shift Right and Narrow Top"),
	TO_ENUM(ARM_vrmlaldavh, "Vector Rounding Multiply Add Long Dual Accumulate Across Vector Returning High 64 bits"),
	TO_ENUM(ARM_vrmlaldavhX, "Vector Rounding Multiply Add Long Dual Accumulate Across Vector Returning High 64 bits (exchange)"),
	TO_ENUM(ARM_vrmlaldavhA, "Vector Rounding Multiply Add Long Dual Accumulate Across Vector Returning High 64 bits (accumulate)"),
	TO_ENUM(ARM_vrmlaldavhAX, "Vector Rounding Multiply Add Long Dual Accumulate Across Vector Returning High 64 bits (accumulate, exchange)"),
	TO_ENUM(ARM_vabav, "Vector Absolute Difference and Accumulate Across Vector"),
	TO_ENUM(ARM_vaddlv, "Vector Add Long Across Vector"),
	TO_ENUM(ARM_vaddlvA, "Vector Add Long Across Vector (accumulate)"),
	TO_ENUM(ARM_vaddv, "Vector Add Across Vector"),
	TO_ENUM(ARM_vaddvA, "Vector Add Across Vector (accumulate)"),
	TO_ENUM(ARM_vshlc, "Whole Vector Left Shift with Carry"),
	TO_ENUM(ARM_vmovlb, "Vector Move Long Bottom"),
	TO_ENUM(ARM_vmovlt, "Vector Move Long Top"),
	TO_ENUM(ARM_vcmla, "Vector Complex Multiply Accumulate"),
	TO_ENUM(ARM_vscclrm, "Floating-point Secure Context Clear Multiple"),
	TO_ENUM(ARM_vld20, "Vector Deinterleaving Load - Stride 2 (pattern=0)"),
	TO_ENUM(ARM_vld21, "Vector Deinterleaving Load - Stride 2 (pattern=1)"),
	TO_ENUM(ARM_vld40, "Vector Deinterleaving Load - Stride 4 (pattern=0)"),
	TO_ENUM(ARM_vld41, "Vector Deinterleaving Load - Stride 4 (pattern=1)"),
	TO_ENUM(ARM_vld42, "Vector Deinterleaving Load - Stride 4 (pattern=2)"),
	TO_ENUM(ARM_vld43, "Vector Deinterleaving Load - Stride 4 (pattern=3)"),
	TO_ENUM(ARM_vst20, "Vector Interleaving Store - Stride 2 (pattern=0)"),
	TO_ENUM(ARM_vst21, "Vector Interleaving Store - Stride 2 (pattern=1)"),
	TO_ENUM(ARM_vst40, "Vector Interleaving Store - Stride 4 (pattern=0)"),
	TO_ENUM(ARM_vst41, "Vector Interleaving Store - Stride 4 (pattern=1)"),
	TO_ENUM(ARM_vst42, "Vector Interleaving Store - Stride 4 (pattern=2)"),
	TO_ENUM(ARM_vst43, "Vector Interleaving Store - Stride 4 (pattern=3)"),
	TO_ENUM(ARM_vldrb, "Vector Load Register/Vector Gather Load (byte)"),
	TO_ENUM(ARM_vldrh, "Vector Load Register/Vector Gather Load (halfword)"),
	TO_ENUM(ARM_vldrw, "Vector Load Register/Vector Gather Load (word)"),
	TO_ENUM(ARM_vldrd, "Vector Load Register/Vector Gather Load (doubleword)"),
	TO_ENUM(ARM_vstrb, "Vector Store Register/Vector Scatter Store (byte)"),
	TO_ENUM(ARM_vstrh, "Vector Store Register/Vector Scatter Store (halfword)"),
	TO_ENUM(ARM_vstrw, "Vector Store Register/Vector Scatter Store (word)"),
	TO_ENUM(ARM_vstrd, "Vector Store Register/Vector Scatter Store (doubleword)"),
	TO_ENUM(ARM_vmov2, "Vector Move (two general-purpose registers to two 32-bit vector lanes)"),
	TO_ENUM(ARM_lsll, "Logical Shift Left Long"),
	TO_ENUM(ARM_lsrl, "Logical Shift Right Long"),
	TO_ENUM(ARM_asrl, "Arithmetic Shift Right Long"),
	TO_ENUM(ARM_sqshll, "Signed Saturating Shift Left Long"),
	TO_ENUM(ARM_uqshll, "Unsigned Saturating Shift Left Long"),
	TO_ENUM(ARM_urshrl, "Unsigned Rounding Shift Right Long"),
	TO_ENUM(ARM_srshrl, "Signed Rounding Shift Right Long"),
	TO_ENUM(ARM_uqrshll, "Unsigned Saturating Rounding Shift Left Long"),
	TO_ENUM(ARM_sqrshrl, "Signed Saturating Rounding Shift Right Long"),
	TO_ENUM(ARM_sqrshr, "Signed Saturating Rounding Shift Right"),
	TO_ENUM(ARM_lctp, "Loop Clear with Tail Predication"),
	TO_ENUM(ARM_vctp, "Create Vector Tail Predicate"),
	TO_ENUM(ARM_pacbti, "Pointer Authentication Code for the link register with BTI clearing, using key"),
	TO_ENUM(ARM_autg, "Authenticate general value, using key"),
	TO_ENUM(ARM_bxaut, "Branch Exchange after Authenticating the address, using key"),
	TO_ENUM(ARM_pacg, "Pointer Authentication Code for a general value, using key"),
	TO_ENUM(ARM_esb, "Error Synchronization Barrier"),
	TO_ENUM(ARM_wls, "While Loop Start"),
	TO_ENUM(ARM_dls, "Do Loop Start"),
	TO_ENUM(ARM_wlstp, "While Loop Start with Tail Predication"),
	TO_ENUM(ARM_dlstp, "Do Loop Start with Tail Predication"),
	TO_ENUM(ARM_le1, "Loop End (count)"),
	TO_ENUM(ARM_le2, "Loop End (forever)"),
	TO_ENUM(ARM_letp, "Loop End with Tail Prediction"),
	TO_ENUM(ARM_bf, "Branch Future"),
	TO_ENUM(ARM_bfx, "Branch Future and Exchange"),
	TO_ENUM(ARM_bfl, "Branch Future with Link"),
	TO_ENUM(ARM_bflx, "Branch Future with Link and Exchange"),
	TO_ENUM(ARM_bfcsel, "Branch Future Conditional Select"),
	TO_ENUM(ARM_cx1, "Custom Instruction Class 1"),
	TO_ENUM(ARM_cx1A, "Custom Instruction Class 1 (accumulator)"),
	TO_ENUM(ARM_cx1d, "Custom Instruction Class 1 (pair)"),
	TO_ENUM(ARM_cx1dA, "Custom Instruction Class 1 (pair, accumulator)"),
	TO_ENUM(ARM_cx2, "Custom Instruction Class 2"),
	TO_ENUM(ARM_cx2A, "Custom Instruction Class 2 (accumulator)"),
	TO_ENUM(ARM_cx2d, "Custom Instruction Class 2 (pair)"),
	TO_ENUM(ARM_cx2dA, "Custom Instruction Class 2 (pair, accumulator)"),
	TO_ENUM(ARM_cx3, "Custom Instruction Class 3"),
	TO_ENUM(ARM_cx3A, "Custom Instruction Class 3 (accumulator)"),
	TO_ENUM(ARM_cx3d, "Custom Instruction Class 3 (pair)"),
	TO_ENUM(ARM_cx3dA, "Custom Instruction Class 3 (pair, accumulator)"),
	TO_ENUM(ARM_vcx1, "Custom Extension Instruction Class 1"),
	TO_ENUM(ARM_vcx1A, "Custom Extension Instruction Class 1 (accumulator)"),
	TO_ENUM(ARM_vcx2, "Custom Extension Instruction Class 2"),
	TO_ENUM(ARM_vcx2A, "Custom Extension Instruction Class 2 (accumulator)"),
	TO_ENUM(ARM_vcx3, "Custom Extension Instruction Class 3"),
	TO_ENUM(ARM_vcx3A, "Custom Extension Instruction Class 3 (accumulator)"),
	TO_ENUM(ARM_wfet, "Wait For Event with Timeout"),
	TO_ENUM(ARM_wfit, "Wait For Interrupt with Timeout"),
	TO_ENUM(ARM_last, "Undocumented instruction ARM_last")
};
