auto instructions_PLFM_TMS320C54 = flags_vector_t{
	TO_ENUM(TMS320C54_null, "Undocumented instruction TMS320C54_null"),
	TO_ENUM(TMS320C54_add1, "Add to Accumulator"),
	TO_ENUM(TMS320C54_add2, "Add to Accumulator"),
	TO_ENUM(TMS320C54_add3, "Add to Accumulator"),
	TO_ENUM(TMS320C54_addc, "Add to Accumulator With Carry"),
	TO_ENUM(TMS320C54_addm, "Add Long-Immediate Value to Memory"),
	TO_ENUM(TMS320C54_adds, "Add to Accumulator With Sign-Extension Suppressed"),
	TO_ENUM(TMS320C54_sub1, "Sub From Accumulator"),
	TO_ENUM(TMS320C54_sub2, "Sub From Accumulator"),
	TO_ENUM(TMS320C54_sub3, "Sub From Accumulator"),
	TO_ENUM(TMS320C54_subb, "Sub From Accumulator With Borrow"),
	TO_ENUM(TMS320C54_subc, "Subtract Conditionally"),
	TO_ENUM(TMS320C54_subs, "Subtract From Accumulator With Sign Extension Suppressed"),
	TO_ENUM(TMS320C54_mpy2, "Multiply Without Rounding"),
	TO_ENUM(TMS320C54_mpy3, "Multiply Without Rounding"),
	TO_ENUM(TMS320C54_mpyr2, "Multiply With Rounding"),
	TO_ENUM(TMS320C54_mpya, "Multiply by Accumulator A"),
	TO_ENUM(TMS320C54_mpyu, "Multiply Unsigned"),
	TO_ENUM(TMS320C54_squr, "Square"),
	TO_ENUM(TMS320C54_mac2, "Multiply Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_mac3, "Multiply Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_macr2, "Multiply Accumulate With Rounding"),
	TO_ENUM(TMS320C54_macr3, "Multiply Accumulate With Rounding"),
	TO_ENUM(TMS320C54_maca1, "Multiply by Accumulator A and Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_maca2, "Multiply by Accumulator A and Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_maca3, "Multiply by Accumulator A and Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_macar1, "Multiply by Accumulator A and Accumulate With Rounding"),
	TO_ENUM(TMS320C54_macar2, "Multiply by Accumulator A and Accumulate With Rounding"),
	TO_ENUM(TMS320C54_macar3, "Multiply by Accumulator A and Accumulate With Rounding"),
	TO_ENUM(TMS320C54_macd, "Multiply by Program Memory and Accumulate With Delay"),
	TO_ENUM(TMS320C54_macp, "Multiply by Program Memory and Accumulate"),
	TO_ENUM(TMS320C54_macsu, "Multiply Signed by Unsigned and Accumulate"),
	TO_ENUM(TMS320C54_mas2, "Multiply and Subtract Without Rounding"),
	TO_ENUM(TMS320C54_mas3, "Multiply and Subtract Without Rounding"),
	TO_ENUM(TMS320C54_masr2, "Multiply and Subtract With Rounding"),
	TO_ENUM(TMS320C54_masr3, "Multiply and Subtract With Rounding"),
	TO_ENUM(TMS320C54_masa1, "Multiply by Accumulator A and Subtract Without Rounding"),
	TO_ENUM(TMS320C54_masa2, "Multiply by Accumulator A and Subtract Without Rounding"),
	TO_ENUM(TMS320C54_masa3, "Multiply by Accumulator A and Subtract Without Rounding"),
	TO_ENUM(TMS320C54_masar1, "Multiply by Accumulator A and Subtract With Rounding"),
	TO_ENUM(TMS320C54_masar2, "Multiply by Accumulator A and Subtract With Rounding"),
	TO_ENUM(TMS320C54_masar3, "Multiply by Accumulator A and Subtract With Rounding"),
	TO_ENUM(TMS320C54_squra, "Square and Accumulate"),
	TO_ENUM(TMS320C54_squrs, "Square and Subtract"),
	TO_ENUM(TMS320C54_dadd2, "Double-Precision/Dual 16-Bit Add to Accumulator"),
	TO_ENUM(TMS320C54_dadd3, "Double-Precision/Dual 16-Bit Add to Accumulator"),
	TO_ENUM(TMS320C54_dadst, "Double-Precision Load With T Add/Dual 16-Bit Load With T Add/Subtract"),
	TO_ENUM(TMS320C54_drsub, "Double-Precision/Dual 16-Bit Subtract From Long Word"),
	TO_ENUM(TMS320C54_dsadt, "Long-Word Load With T Add/Dual 16-Bit Load With T Subtract/Add"),
	TO_ENUM(TMS320C54_dsub, "Double-Precision/Dual 16-Bit Subtract From Accumulator"),
	TO_ENUM(TMS320C54_dsubt, "Long-Word Load With T Subtract/Dual 16-Bit Load With T Subtract"),
	TO_ENUM(TMS320C54_abdst, "Absolute distance"),
	TO_ENUM(TMS320C54_abs1, "Absolute Value of Accumulator"),
	TO_ENUM(TMS320C54_abs2, "Absolute Value of Accumulator"),
	TO_ENUM(TMS320C54_cmpl1, "Complement Accumulator"),
	TO_ENUM(TMS320C54_cmpl2, "Complement Accumulator"),
	TO_ENUM(TMS320C54_delay, "Memory Delay"),
	TO_ENUM(TMS320C54_exp, "Accumulator Exponent"),
	TO_ENUM(TMS320C54_firs, "Symmetrical Finite Impulse Response Filter"),
	TO_ENUM(TMS320C54_lms, "Least Mean Square"),
	TO_ENUM(TMS320C54_max, "Accumulator Maximum"),
	TO_ENUM(TMS320C54_min, "Accumulator Minimum"),
	TO_ENUM(TMS320C54_neg1, "Negate Accumulator"),
	TO_ENUM(TMS320C54_neg2, "Negate Accumulator"),
	TO_ENUM(TMS320C54_norm1, "Normalization"),
	TO_ENUM(TMS320C54_norm2, "Normalization"),
	TO_ENUM(TMS320C54_poly, "Polynominal Evaluation"),
	TO_ENUM(TMS320C54_rnd1, "Round Accumulator"),
	TO_ENUM(TMS320C54_rnd2, "Round Accumulator"),
	TO_ENUM(TMS320C54_sat, "Saturate Accumulator"),
	TO_ENUM(TMS320C54_sqdst, "Square Distance"),
	TO_ENUM(TMS320C54_and1, "AND With Accumulator"),
	TO_ENUM(TMS320C54_and2, "AND With Accumulator"),
	TO_ENUM(TMS320C54_and3, "AND With Accumulator"),
	TO_ENUM(TMS320C54_andm, "AND Memory With Long Immediate"),
	TO_ENUM(TMS320C54_or1, "OR With Accumulator"),
	TO_ENUM(TMS320C54_or2, "OR With Accumulator"),
	TO_ENUM(TMS320C54_or3, "OR With Accumulator"),
	TO_ENUM(TMS320C54_orm, "OR Memory With Constant"),
	TO_ENUM(TMS320C54_xor1, "Exclusive OR With Accumulator"),
	TO_ENUM(TMS320C54_xor2, "Exclusive OR With Accumulator"),
	TO_ENUM(TMS320C54_xor3, "Exclusive OR With Accumulator"),
	TO_ENUM(TMS320C54_xorm, "Exclusive OR Memory With Constant"),
	TO_ENUM(TMS320C54_rol, "Rotate Accumulator"),
	TO_ENUM(TMS320C54_roltc, "Rotate Accumulator Left Using TC"),
	TO_ENUM(TMS320C54_ror, "Rotate Accumulator Right"),
	TO_ENUM(TMS320C54_sfta2, "Shift Accumulator Arithmetically"),
	TO_ENUM(TMS320C54_sfta3, "Shift Accumulator Arithmetically"),
	TO_ENUM(TMS320C54_sftc, "Shift Accumulator Conditionally"),
	TO_ENUM(TMS320C54_sftl2, "Shift Accumulator Logically"),
	TO_ENUM(TMS320C54_sftl3, "Shift Accumulator Logically"),
	TO_ENUM(TMS320C54_bit, "Test Bit"),
	TO_ENUM(TMS320C54_bitf, "Test Bit Field Specified by Immediate Value"),
	TO_ENUM(TMS320C54_bitt, "Test Bit Specified by T"),
	TO_ENUM(TMS320C54_cmpm, "Compare Memory With Long Immediate"),
	TO_ENUM(TMS320C54_cmpr, "Compare Auxiliary Register with AR0"),
	TO_ENUM(TMS320C54_b, "Branch Unconditionally"),
	TO_ENUM(TMS320C54_bd, "Branch Unconditionally"),
	TO_ENUM(TMS320C54_bacc, "Branch to Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_baccd, "Branch to Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_banz, "Branch on Auxiliary Register Not Zero"),
	TO_ENUM(TMS320C54_banzd, "Branch on Auxiliary Register Not Zero"),
	TO_ENUM(TMS320C54_bc2, "Branch Conditionally"),
	TO_ENUM(TMS320C54_bc3, "Branch Conditionally"),
	TO_ENUM(TMS320C54_bcd2, "Branch Conditionally"),
	TO_ENUM(TMS320C54_bcd3, "Branch Conditionally"),
	TO_ENUM(TMS320C54_fb, "Far Branch Unconditionally"),
	TO_ENUM(TMS320C54_fbd, "Far Branch Unconditionally"),
	TO_ENUM(TMS320C54_fbacc, "Far Branch to Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_fbaccd, "Far Branch to Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_cala, "Call Subroutine at Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_calad, "Call Subroutine at Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_call, "Call Unconditionally"),
	TO_ENUM(TMS320C54_calld, "Call Unconditionally"),
	TO_ENUM(TMS320C54_cc2, "Call Conditionally"),
	TO_ENUM(TMS320C54_cc3, "Call Conditionally"),
	TO_ENUM(TMS320C54_ccd2, "Call Conditionally"),
	TO_ENUM(TMS320C54_ccd3, "Call Conditionally"),
	TO_ENUM(TMS320C54_fcala, "Far Call Subroutine at Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_fcalad, "Far Call Subroutine at Location Specified by Accumulator"),
	TO_ENUM(TMS320C54_fcall, "Far Call Unconditionally"),
	TO_ENUM(TMS320C54_fcalld, "Far Call Unconditionally"),
	TO_ENUM(TMS320C54_intr, "Software Interrupt"),
	TO_ENUM(TMS320C54_trap, "Software Interrupt"),
	TO_ENUM(TMS320C54_fret, "Far Return"),
	TO_ENUM(TMS320C54_fretd, "Far Return"),
	TO_ENUM(TMS320C54_frete, "Enable Interrupts and Far Return From Interrupt"),
	TO_ENUM(TMS320C54_freted, "Enable Interrupts and Far Return From Interrupt"),
	TO_ENUM(TMS320C54_rc1, "Return Conditionally"),
	TO_ENUM(TMS320C54_rc2, "Return Conditionally"),
	TO_ENUM(TMS320C54_rc3, "Return Conditionally"),
	TO_ENUM(TMS320C54_rcd1, "Return Conditionally"),
	TO_ENUM(TMS320C54_rcd2, "Return Conditionally"),
	TO_ENUM(TMS320C54_rcd3, "Return Conditionally"),
	TO_ENUM(TMS320C54_ret, "Return"),
	TO_ENUM(TMS320C54_retd, "Return"),
	TO_ENUM(TMS320C54_rete, "Enable Interrupts and Return From Interrupt"),
	TO_ENUM(TMS320C54_reted, "Enable Interrupts and Return From Interrupt"),
	TO_ENUM(TMS320C54_retf, "Enable Interrupts and Fast Return From Interrupt"),
	TO_ENUM(TMS320C54_retfd, "Enable Interrupts and Fast Return From Interrupt"),
	TO_ENUM(TMS320C54_rpt, "Repeat Next Instruction"),
	TO_ENUM(TMS320C54_rptb, "Block Repeat"),
	TO_ENUM(TMS320C54_rptbd, "Block Repeat"),
	TO_ENUM(TMS320C54_rptz, "Repeat Next Instruction And Clear Accumulator"),
	TO_ENUM(TMS320C54_frame, "Stack Pointer Immediate Offset"),
	TO_ENUM(TMS320C54_popd, "Pop Top of Stack to Data Memory"),
	TO_ENUM(TMS320C54_popm, "Pop Top of Stack to Memory-Mapped Register"),
	TO_ENUM(TMS320C54_pshd, "Push Data-Memory Value Onto Stack"),
	TO_ENUM(TMS320C54_pshm, "Push Memory-Mapped Register Onto Stack"),
	TO_ENUM(TMS320C54_idle, "Idle Until Interrupt"),
	TO_ENUM(TMS320C54_mar, "Modify Auxiliary Register"),
	TO_ENUM(TMS320C54_nop, "No Operation"),
	TO_ENUM(TMS320C54_reset, "Software Reset"),
	TO_ENUM(TMS320C54_rsbx1, "Reset Status Register Bit"),
	TO_ENUM(TMS320C54_rsbx2, "Reset Status Register Bit"),
	TO_ENUM(TMS320C54_ssbx1, "Set Status Register Bit"),
	TO_ENUM(TMS320C54_ssbx2, "Set Status Register Bit"),
	TO_ENUM(TMS320C54_xc2, "Execute Conditionally"),
	TO_ENUM(TMS320C54_xc3, "Execute Conditionally"),
	TO_ENUM(TMS320C54_dld, "Double-Precision/Dual 16-Bit Long-Word Load to Accumulator"),
	TO_ENUM(TMS320C54_ld1, "Load Accumulator With Shift"),
	TO_ENUM(TMS320C54_ld2, "Load Accumulator With Shift"),
	TO_ENUM(TMS320C54_ld3, "Load Accumulator With Shift"),
	TO_ENUM(TMS320C54_ldm, "Load Memory-Mapped Register"),
	TO_ENUM(TMS320C54_ldr, "Load Memory Value in Accumulator High With Rounding"),
	TO_ENUM(TMS320C54_ldu, "Load Unsigned Memory Value"),
	TO_ENUM(TMS320C54_ltd, "Load T and insert Delay"),
	TO_ENUM(TMS320C54_dst, "Store Accumulator in Long Word"),
	TO_ENUM(TMS320C54_st, "Store T, TRN, or Immediate Value into Memory"),
	TO_ENUM(TMS320C54_sth2, "Store Accumulator High Into Memory"),
	TO_ENUM(TMS320C54_sth3, "Store Accumulator High Into Memory"),
	TO_ENUM(TMS320C54_stl2, "Store Accumulator Low Into Memory"),
	TO_ENUM(TMS320C54_stl3, "Store Accumulator Low Into Memory"),
	TO_ENUM(TMS320C54_stlm, "Store Accumulator Low Into Memory-Mapped Register"),
	TO_ENUM(TMS320C54_stm, "Store Immediate Value Into Memory-Mapped Register"),
	TO_ENUM(TMS320C54_cmps, "Compare, Select and Store Maximum"),
	TO_ENUM(TMS320C54_saccd, "Store Accumulator Conditionally"),
	TO_ENUM(TMS320C54_srccd, "Store Block Repeat Counter Conditionally"),
	TO_ENUM(TMS320C54_strcd, "Store T Conditionally"),
	TO_ENUM(TMS320C54_st_ld, "Store Accumulator With Parallel Load"),
	TO_ENUM(TMS320C54_ld_mac, "Load Accumulator With Parallel Multiply Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_ld_macr, "Load Accumulator With Parallel Multiply Accumulate With Rounding"),
	TO_ENUM(TMS320C54_ld_mas, "Load Accumulator With Parallel Multiply Subtract Without Rounding"),
	TO_ENUM(TMS320C54_ld_masr, "Load Accumulator With Parallel Multiply Subtract With Rounding"),
	TO_ENUM(TMS320C54_st_add, "Store Accumulator With Parallel Add"),
	TO_ENUM(TMS320C54_st_sub, "Store Accumulator With Parallel Subtract"),
	TO_ENUM(TMS320C54_st_mac, "Store Accumulator With Parallel Multiply Accumulate Without Rounding"),
	TO_ENUM(TMS320C54_st_macr, "Store Accumulator With Parallel Multiply Accumulate With Rounding"),
	TO_ENUM(TMS320C54_st_mas, "Store Accumulator With Parallel Multiply Subtract Without Rounding"),
	TO_ENUM(TMS320C54_st_masr, "Store Accumulator With Parallel Multiply Subtract With Rounding"),
	TO_ENUM(TMS320C54_st_mpy, "Store Accumulator With Parallel Multiply"),
	TO_ENUM(TMS320C54_mvdd, "Move Data From Data Memory to Data Memory With X,Y Addressing"),
	TO_ENUM(TMS320C54_mvdk, "Move Data From Data Memory to Data Memory With Destination Addressing"),
	TO_ENUM(TMS320C54_mvdm, "Move Data From Data Memory to Memory-Mapped Register"),
	TO_ENUM(TMS320C54_mvdp, "Move Data From Data Memory to Program Memory"),
	TO_ENUM(TMS320C54_mvkd, "Move Data From Data Memory to Data Memory With Source Addressing"),
	TO_ENUM(TMS320C54_mvmd, "Move Data From Memory-Mapped Register to Data Memory"),
	TO_ENUM(TMS320C54_mvmm, "Move Data From Memory-Mapped Register to Memory-Mapped Register"),
	TO_ENUM(TMS320C54_mvpd, "Move Data From Program Memory to Data Memory"),
	TO_ENUM(TMS320C54_portr, "Read Data From Port"),
	TO_ENUM(TMS320C54_portw, "Write Data to Port"),
	TO_ENUM(TMS320C54_reada, "Read Program Memory Addressed by Accumulator A and Store in Data Memory"),
	TO_ENUM(TMS320C54_writa, "Write Data to Program Memory Addressed by Accumulator A"),
	TO_ENUM(TMS320C54_last, "Undocumented instruction TMS320C54_last")
};
