auto instructions_PLFM_M16C = flags_vector_t{
	TO_ENUM(M16C_null, "Unknown Operation (same as 0)"),
	TO_ENUM(M16C_abs, "Absolute value"),
	TO_ENUM(M16C_adc, "Add with carry"),
	TO_ENUM(M16C_adcf, "Add carry flag"),
	TO_ENUM(M16C_add, "Add without carry"),
	TO_ENUM(M16C_adjnz, "Add & conditional jump"),
	TO_ENUM(M16C_and, "Logically AND"),
	TO_ENUM(M16C_band, "Logically AND bits"),
	TO_ENUM(M16C_bclr, "Clear bit"),
	TO_ENUM(M16C_bmcnd, "Conditional bit transfer"),
	TO_ENUM(M16C_bmgeu, "Conditional bit transfer: Equal to or greater than; C == 1"),
	TO_ENUM(M16C_bmgtu, "Conditional bit transfer: Greater than"),
	TO_ENUM(M16C_bmeq, "Conditional bit transfer: Equal to; Z == 1"),
	TO_ENUM(M16C_bmn, "Conditional bit transfer: Negative"),
	TO_ENUM(M16C_bmle, "Conditional bit transfer: Equal to or smaller than (signed)"),
	TO_ENUM(M16C_bmo, "Conditional bit transfer: Overflow; O == 1"),
	TO_ENUM(M16C_bmge, "Conditional bit transfer: Equal to or greater than (signed)"),
	TO_ENUM(M16C_bmltu, "Conditional bit transfer: Smaller than; C == 0"),
	TO_ENUM(M16C_bmleu, "Conditional bit transfer: Equal to or smaller than"),
	TO_ENUM(M16C_bmne, "Conditional bit transfer: Not equal; Z == 0"),
	TO_ENUM(M16C_bmpz, "Conditional bit transfer: Positive or zero"),
	TO_ENUM(M16C_bmgt, "Conditional bit transfer: Greater than (signed)"),
	TO_ENUM(M16C_bmno, "Conditional bit transfer: No overflow; O == 0"),
	TO_ENUM(M16C_bmlt, "Conditional bit transfer: Smaller than (signed)"),
	TO_ENUM(M16C_bnand, "Logically AND inverted bits"),
	TO_ENUM(M16C_bnor, "Logically OR inverted bits"),
	TO_ENUM(M16C_bnot, "Invert bit"),
	TO_ENUM(M16C_bntst, "Test inverted bit"),
	TO_ENUM(M16C_bnxor, "Exclusive OR inverted bits"),
	TO_ENUM(M16C_bor, "Logically OR bits"),
	TO_ENUM(M16C_brk, "Debug interrupt"),
	TO_ENUM(M16C_bset, "Set bit"),
	TO_ENUM(M16C_btst, "Test bit"),
	TO_ENUM(M16C_btstc, "Test bit & clear"),
	TO_ENUM(M16C_btsts, "Test bit & set"),
	TO_ENUM(M16C_bxor, "Exclusive OR bits"),
	TO_ENUM(M16C_cmp, "Compare"),
	TO_ENUM(M16C_dadc, "Decimal add with carry"),
	TO_ENUM(M16C_dadd, "Decimal add without carry"),
	TO_ENUM(M16C_dec, "Decrement"),
	TO_ENUM(M16C_div, "Signed divide"),
	TO_ENUM(M16C_divu, "Unsigned divide"),
	TO_ENUM(M16C_divx, "Signed divide (extension)"),
	TO_ENUM(M16C_dsbb, "Decimal subtract with borrow"),
	TO_ENUM(M16C_dsub, "Decimal subtract without borrow"),
	TO_ENUM(M16C_enter, "Build stack frame"),
	TO_ENUM(M16C_exitd, "Deallocate stack frame"),
	TO_ENUM(M16C_exts, "Extend sign"),
	TO_ENUM(M16C_fclr, "Clear flag register bit"),
	TO_ENUM(M16C_fset, "Set flag register bit"),
	TO_ENUM(M16C_inc, "Increment"),
	TO_ENUM(M16C_int, "Interrupt by INT instruction"),
	TO_ENUM(M16C_into, "Interrupt on overflow"),
	TO_ENUM(M16C_jcnd, "Jump on condition"),
	TO_ENUM(M16C_jgeu, "Conditional jump: Equal to or greater than; C == 1"),
	TO_ENUM(M16C_jgtu, "Conditional jump: Greater than"),
	TO_ENUM(M16C_jeq, "Conditional jump: Equal to; Z == 1"),
	TO_ENUM(M16C_jn, "Conditional jump: Negative"),
	TO_ENUM(M16C_jle, "Conditional jump: Equal to or smaller than (signed)"),
	TO_ENUM(M16C_jo, "Conditional jump: Overflow; O == 1"),
	TO_ENUM(M16C_jge, "Conditional jump: Equal to or greater than (signed)"),
	TO_ENUM(M16C_jltu, "Conditional jump: Smaller than; C == 0"),
	TO_ENUM(M16C_jleu, "Conditional jump: Equal to or smaller than"),
	TO_ENUM(M16C_jne, "Conditional jump: Not equal; Z == 0"),
	TO_ENUM(M16C_jpz, "Conditional jump: Positive or zero"),
	TO_ENUM(M16C_jgt, "Conditional jump: Greater than (signed)"),
	TO_ENUM(M16C_jno, "Conditional jump: No overflow; O == 0"),
	TO_ENUM(M16C_jlt, "Conditional jump: Smaller than (signed)"),
	TO_ENUM(M16C_jmp, "Unconditional jump"),
	TO_ENUM(M16C_jmpi, "Jump indirect"),
	TO_ENUM(M16C_jmps, "Jump to special page"),
	TO_ENUM(M16C_jsr, "Subroutine call"),
	TO_ENUM(M16C_jsri, "Indirect subroutine call"),
	TO_ENUM(M16C_jsrs, "Special page subroutine call"),
	TO_ENUM(M16C_ldc, "Transfer to control register"),
	TO_ENUM(M16C_ldctx, "Restore context"),
	TO_ENUM(M16C_lde, "Transfer from extended data area"),
	TO_ENUM(M16C_ldintb, "Load to INTB register"),
	TO_ENUM(M16C_ldipl, "Set interrupt enable level"),
	TO_ENUM(M16C_mov, "Transfer"),
	TO_ENUM(M16C_mova, "Transfer effective address"),
	TO_ENUM(M16C_movhh, "Xfer 4-bit data: src(8-bits)'s 4 hi bits -> dest(8-bits)'s 4 hi bits."),
	TO_ENUM(M16C_movhl, "Xfer 4-bit data: src(8-bits)'s 4 hi bits -> dest(8-bits)'s 4 lo bits."),
	TO_ENUM(M16C_movlh, "Xfer 4-bit data: src(8-bits)'s 4 lo bits -> dest(8-bits)'s 4 hi bits."),
	TO_ENUM(M16C_movll, "Xfer 4-bit data: src(8-bits)'s 4 lo bits -> dest(8-bits)'s 4 lo bits."),
	TO_ENUM(M16C_mul, "Signed multiply"),
	TO_ENUM(M16C_mulu, "Unsigned multiply"),
	TO_ENUM(M16C_neg, "Two's complement"),
	TO_ENUM(M16C_nop, "No operation"),
	TO_ENUM(M16C_not, "Invert all bits"),
	TO_ENUM(M16C_or, "Logically OR"),
	TO_ENUM(M16C_pop, "Restore register/memory"),
	TO_ENUM(M16C_popc, "Restore control register"),
	TO_ENUM(M16C_popm, "Restore multiple registers"),
	TO_ENUM(M16C_push, "Save register/memory/immediate data"),
	TO_ENUM(M16C_pusha, "Save effective address"),
	TO_ENUM(M16C_pushc, "Save control register"),
	TO_ENUM(M16C_pushm, "Save multiple registers"),
	TO_ENUM(M16C_reit, "Return from interrupt"),
	TO_ENUM(M16C_rmpa, "Calculate sum-of-products"),
	TO_ENUM(M16C_rolc, "Rotate left with carry"),
	TO_ENUM(M16C_rorc, "Rotate right with carry"),
	TO_ENUM(M16C_rot, "Rotate"),
	TO_ENUM(M16C_rts, "Return from subroutine"),
	TO_ENUM(M16C_sbb, "Subtract with borrow"),
	TO_ENUM(M16C_sbjnz, "Subtract & conditional jump"),
	TO_ENUM(M16C_sha, "Shift arithmetic"),
	TO_ENUM(M16C_shl, "Shift logical"),
	TO_ENUM(M16C_smovb, "Transfer string backward"),
	TO_ENUM(M16C_smovf, "Transfer string forward"),
	TO_ENUM(M16C_sstr, "Store string"),
	TO_ENUM(M16C_stc, "Transfer from control register"),
	TO_ENUM(M16C_stctx, "Save context"),
	TO_ENUM(M16C_ste, "Store to extended data area"),
	TO_ENUM(M16C_stnz, "Conditional transfer: store on not zero"),
	TO_ENUM(M16C_stz, "Conditional transfer: store on zero"),
	TO_ENUM(M16C_stzx, "Conditional transfer: store on zero extension"),
	TO_ENUM(M16C_sub, "Subtract without borrow"),
	TO_ENUM(M16C_tst, "Test"),
	TO_ENUM(M16C_und, "Interrupt for undefined instruction"),
	TO_ENUM(M16C_wait, "Wait"),
	TO_ENUM(M16C_xchg, "Exchange"),
	TO_ENUM(M16C_xor, "Exclusive OR"),
	TO_ENUM(M16C_addx, "Undocumented instruction M16C_addx"),
	TO_ENUM(M16C_bitindex, "Undocumented instruction M16C_bitindex"),
	TO_ENUM(M16C_brk2, "Debugger-only interrupt"),
	TO_ENUM(M16C_clip, "Undocumented instruction M16C_clip"),
	TO_ENUM(M16C_cmpx, "Undocumented instruction M16C_cmpx"),
	TO_ENUM(M16C_extz, "Undocumented instruction M16C_extz"),
	TO_ENUM(M16C_freit, "Fast return from interrupt"),
	TO_ENUM(M16C_indexb, "Undocumented instruction M16C_indexb"),
	TO_ENUM(M16C_indexbd, "Undocumented instruction M16C_indexbd"),
	TO_ENUM(M16C_indexbs, "Undocumented instruction M16C_indexbs"),
	TO_ENUM(M16C_indexl, "Undocumented instruction M16C_indexl"),
	TO_ENUM(M16C_indexld, "Undocumented instruction M16C_indexld"),
	TO_ENUM(M16C_indexls, "Undocumented instruction M16C_indexls"),
	TO_ENUM(M16C_indexw, "Undocumented instruction M16C_indexw"),
	TO_ENUM(M16C_indexwd, "Undocumented instruction M16C_indexwd"),
	TO_ENUM(M16C_indexws, "Undocumented instruction M16C_indexws"),
	TO_ENUM(M16C_max, "Undocumented instruction M16C_max"),
	TO_ENUM(M16C_min, "Undocumented instruction M16C_min"),
	TO_ENUM(M16C_movx, "Undocumented instruction M16C_movx"),
	TO_ENUM(M16C_mulex, "Undocumented instruction M16C_mulex"),
	TO_ENUM(M16C_sccnd, "Undocumented instruction M16C_sccnd"),
	TO_ENUM(M16C_scgeu, "Conditional store: Equal to or greater than; C == 1"),
	TO_ENUM(M16C_scgtu, "Conditional store: Greater than"),
	TO_ENUM(M16C_sceq, "Conditional store: Equal to; Z == 1"),
	TO_ENUM(M16C_scn, "Conditional store: Negative"),
	TO_ENUM(M16C_scle, "Conditional store: Equal to or smaller than (signed)"),
	TO_ENUM(M16C_sco, "Conditional store: Overflow; O == 1"),
	TO_ENUM(M16C_scge, "Conditional store: Equal to or greater than (signed)"),
	TO_ENUM(M16C_scltu, "Conditional store: Smaller than; C == 0"),
	TO_ENUM(M16C_scleu, "Conditional store: Equal to or smaller than"),
	TO_ENUM(M16C_scne, "Conditional store: Not equal; Z == 0"),
	TO_ENUM(M16C_scpz, "Conditional store: Positive or zero"),
	TO_ENUM(M16C_scgt, "Conditional store: Greater than (signed)"),
	TO_ENUM(M16C_scno, "Conditional store: No overflow; O == 0"),
	TO_ENUM(M16C_sclt, "Conditional store: Smaller than (signed)"),
	TO_ENUM(M16C_scmpu, "Undocumented instruction M16C_scmpu"),
	TO_ENUM(M16C_sin, "Undocumented instruction M16C_sin"),
	TO_ENUM(M16C_smovu, "Undocumented instruction M16C_smovu"),
	TO_ENUM(M16C_sout, "Undocumented instruction M16C_sout"),
	TO_ENUM(M16C_subx, "Undocumented instruction M16C_subx"),
	TO_ENUM(M16C_shanc, "Shift arithmetic no carry"),
	TO_ENUM(M16C_shlnc, "Shift logical no carry"),
	TO_ENUM(M16C_addf, "Undocumented instruction M16C_addf"),
	TO_ENUM(M16C_adsf, "Undocumented instruction M16C_adsf"),
	TO_ENUM(M16C_cmpf, "Undocumented instruction M16C_cmpf"),
	TO_ENUM(M16C_cnvif, "Undocumented instruction M16C_cnvif"),
	TO_ENUM(M16C_divf, "Undocumented instruction M16C_divf"),
	TO_ENUM(M16C_ediv, "Undocumented instruction M16C_ediv"),
	TO_ENUM(M16C_edivu, "Undocumented instruction M16C_edivu"),
	TO_ENUM(M16C_edivx, "Undocumented instruction M16C_edivx"),
	TO_ENUM(M16C_emul, "Undocumented instruction M16C_emul"),
	TO_ENUM(M16C_emulu, "Undocumented instruction M16C_emulu"),
	TO_ENUM(M16C_exiti, "Undocumented instruction M16C_exiti"),
	TO_ENUM(M16C_index1, "Undocumented instruction M16C_index1"),
	TO_ENUM(M16C_index2, "Undocumented instruction M16C_index2"),
	TO_ENUM(M16C_mulf, "Undocumented instruction M16C_mulf"),
	TO_ENUM(M16C_mulx, "Undocumented instruction M16C_mulx"),
	TO_ENUM(M16C_round, "Undocumented instruction M16C_round"),
	TO_ENUM(M16C_stop, "Undocumented instruction M16C_stop"),
	TO_ENUM(M16C_subf, "Undocumented instruction M16C_subf"),
	TO_ENUM(M16C_suntil, "Undocumented instruction M16C_suntil"),
	TO_ENUM(M16C_swhile, "Undocumented instruction M16C_swhile"),
	TO_ENUM(M16C_last, "Undocumented instruction M16C_last")
};
