auto instructions_PLFM_ARC = flags_vector_t{
	TO_ENUM(ARC_null, "Undocumented instruction ARC_null"),
	TO_ENUM(ARC_ld, "Load"),
	TO_ENUM(ARC_lr, "Load from auxiliary register"),
	TO_ENUM(ARC_st, "Store"),
	TO_ENUM(ARC_sr, "Store to auxiliary register"),
	TO_ENUM(ARC_store_instructions, "Undocumented instruction ARC_store_instructions"),
	TO_ENUM(ARC_flag, "Set flags"),
	TO_ENUM(ARC_asr, "Arithmetic shift right"),
	TO_ENUM(ARC_lsr, "Logical shift right"),
	TO_ENUM(ARC_sexb, "Sign extend byte"),
	TO_ENUM(ARC_sexw, "Sign extend word"),
	TO_ENUM(ARC_sexh, "Undocumented instruction ARC_sexh"),
	TO_ENUM(ARC_extb, "Zero extend byte"),
	TO_ENUM(ARC_extw, "Zero extend word"),
	TO_ENUM(ARC_exth, "Undocumented instruction ARC_exth"),
	TO_ENUM(ARC_ror, "Rotate right"),
	TO_ENUM(ARC_rrc, "Rotate right through carry"),
	TO_ENUM(ARC_b, "Branch"),
	TO_ENUM(ARC_bl, "Branch and link"),
	TO_ENUM(ARC_lp, "Zero-overhead loop setup"),
	TO_ENUM(ARC_j, "Jump"),
	TO_ENUM(ARC_jl, "Jump and link"),
	TO_ENUM(ARC_add, "Add"),
	TO_ENUM(ARC_adc, "Add with carry"),
	TO_ENUM(ARC_sub, "Subtract"),
	TO_ENUM(ARC_sbc, "Subtract with carry"),
	TO_ENUM(ARC_and, "Logical bitwise AND"),
	TO_ENUM(ARC_or, "Logical bitwise OR"),
	TO_ENUM(ARC_bic, "Logical bitwise AND with invert"),
	TO_ENUM(ARC_xor, "Logical bitwise exclusive-OR"),
	TO_ENUM(ARC_mov, "Move"),
	TO_ENUM(ARC_nop, "No operation"),
	TO_ENUM(ARC_lsl, "Logical shift left"),
	TO_ENUM(ARC_rlc, "Rotate left through carry"),
	TO_ENUM(ARC_brk, "Breakpoint"),
	TO_ENUM(ARC_sleep, "Sleep until interrupt or restart"),
	TO_ENUM(ARC_swi, "Software interrupt"),
	TO_ENUM(ARC_asl, "Arithmetic shift left"),
	TO_ENUM(ARC_mul64, "Signed 32x32 multiply"),
	TO_ENUM(ARC_mulu64, "Unsigned 32x32 multiply"),
	TO_ENUM(ARC_max, "Maximum of two signed integers"),
	TO_ENUM(ARC_min, "Minimum of two signed integers"),
	TO_ENUM(ARC_swap, "Exchange upper and lower 16 bits"),
	TO_ENUM(ARC_norm, "Normalize (find-first-bit)"),
	TO_ENUM(ARC_bbit0, "Branch if bit cleared to 0"),
	TO_ENUM(ARC_bbit1, "Branch if bit set to 1"),
	TO_ENUM(ARC_br, "Branch on compare"),
	TO_ENUM(ARC_pop, "Restore register value from stack"),
	TO_ENUM(ARC_push, "Store register value on stack"),
	TO_ENUM(ARC_abs, "Absolute value"),
	TO_ENUM(ARC_add1, "Add with left shift by 1 bit"),
	TO_ENUM(ARC_add2, "Add with left shift by 2 bits"),
	TO_ENUM(ARC_add3, "Add with left shift by 3 bits"),
	TO_ENUM(ARC_bclr, "Clear specified bit (to 0)"),
	TO_ENUM(ARC_bmsk, "Bit Mask"),
	TO_ENUM(ARC_bset, "Set specified bit (to 1)"),
	TO_ENUM(ARC_btst, "Test value of specified bit"),
	TO_ENUM(ARC_bxor, "Bit XOR"),
	TO_ENUM(ARC_cmp, "Compare"),
	TO_ENUM(ARC_ex, "Atomic Exchange"),
	TO_ENUM(ARC_mpy, "Signed 32x32 multiply (low)"),
	TO_ENUM(ARC_mpyh, "Signed 32x32 multiply (high)"),
	TO_ENUM(ARC_mpym, "Undocumented instruction ARC_mpym"),
	TO_ENUM(ARC_mpyhu, "Unsigned 32x32 multiply (high)"),
	TO_ENUM(ARC_mpyhm, "Undocumented instruction ARC_mpyhm"),
	TO_ENUM(ARC_mpyu, "Unsigned 32x32 multiply (low)"),
	TO_ENUM(ARC_neg, "Negate"),
	TO_ENUM(ARC_not, "Logical bit inversion"),
	TO_ENUM(ARC_rcmp, "Reverse Compare"),
	TO_ENUM(ARC_rsub, "Reverse Subtraction"),
	TO_ENUM(ARC_rtie, "Return from Interrupt/Exception"),
	TO_ENUM(ARC_sub1, "Subtract with left shift by 1 bit"),
	TO_ENUM(ARC_sub2, "Subtract with left shift by 2 bits"),
	TO_ENUM(ARC_sub3, "Subtract with left shift by 3 bits"),
	TO_ENUM(ARC_sync, "Synchronize"),
	TO_ENUM(ARC_trap, "Raise an exception"),
	TO_ENUM(ARC_tst, "Test"),
	TO_ENUM(ARC_unimp, "Unimplemented instruction"),
	TO_ENUM(ARC_abss, "Absolute and saturate"),
	TO_ENUM(ARC_abssw, "Absolute and saturate of word"),
	TO_ENUM(ARC_abssh, "Undocumented instruction ARC_abssh"),
	TO_ENUM(ARC_adds, "Add and saturate"),
	TO_ENUM(ARC_addsdw, "Add and saturate dual word"),
	TO_ENUM(ARC_asls, "Arithmetic shift left and saturate"),
	TO_ENUM(ARC_asrs, "Arithmetic shift right and saturate"),
	TO_ENUM(ARC_divaw, "Division assist"),
	TO_ENUM(ARC_negs, "Negate and saturate"),
	TO_ENUM(ARC_negsw, "Negate and saturate of word"),
	TO_ENUM(ARC_negsh, "Undocumented instruction ARC_negsh"),
	TO_ENUM(ARC_normw, "Normalize to 16 bits"),
	TO_ENUM(ARC_normh, "Undocumented instruction ARC_normh"),
	TO_ENUM(ARC_rnd16, "Round to word"),
	TO_ENUM(ARC_rndh, "Undocumented instruction ARC_rndh"),
	TO_ENUM(ARC_sat16, "Saturate to word"),
	TO_ENUM(ARC_sath, "Undocumented instruction ARC_sath"),
	TO_ENUM(ARC_subs, "Subtract and saturate"),
	TO_ENUM(ARC_subsdw, "Subtract and saturate dual word"),
	TO_ENUM(ARC_muldw, "Undocumented instruction ARC_muldw"),
	TO_ENUM(ARC_muludw, "Undocumented instruction ARC_muludw"),
	TO_ENUM(ARC_mulrdw, "Undocumented instruction ARC_mulrdw"),
	TO_ENUM(ARC_macdw, "Undocumented instruction ARC_macdw"),
	TO_ENUM(ARC_macudw, "Undocumented instruction ARC_macudw"),
	TO_ENUM(ARC_macrdw, "Undocumented instruction ARC_macrdw"),
	TO_ENUM(ARC_msubdw, "Undocumented instruction ARC_msubdw"),
	TO_ENUM(ARC_mululw, "Undocumented instruction ARC_mululw"),
	TO_ENUM(ARC_mullw, "Undocumented instruction ARC_mullw"),
	TO_ENUM(ARC_mulflw, "Undocumented instruction ARC_mulflw"),
	TO_ENUM(ARC_maclw, "Undocumented instruction ARC_maclw"),
	TO_ENUM(ARC_macflw, "Undocumented instruction ARC_macflw"),
	TO_ENUM(ARC_machulw, "Undocumented instruction ARC_machulw"),
	TO_ENUM(ARC_machlw, "Undocumented instruction ARC_machlw"),
	TO_ENUM(ARC_machflw, "Undocumented instruction ARC_machflw"),
	TO_ENUM(ARC_mulhlw, "Undocumented instruction ARC_mulhlw"),
	TO_ENUM(ARC_mulhflw, "Undocumented instruction ARC_mulhflw"),
	TO_ENUM(ARC_acm, "Undocumented instruction ARC_acm"),
	TO_ENUM(ARC_addqbs, "Undocumented instruction ARC_addqbs"),
	TO_ENUM(ARC_avgqb, "Undocumented instruction ARC_avgqb"),
	TO_ENUM(ARC_clamp, "Undocumented instruction ARC_clamp"),
	TO_ENUM(ARC_daddh11, "Undocumented instruction ARC_daddh11"),
	TO_ENUM(ARC_daddh12, "Undocumented instruction ARC_daddh12"),
	TO_ENUM(ARC_daddh21, "Undocumented instruction ARC_daddh21"),
	TO_ENUM(ARC_daddh22, "Undocumented instruction ARC_daddh22"),
	TO_ENUM(ARC_dexcl1, "Undocumented instruction ARC_dexcl1"),
	TO_ENUM(ARC_dexcl2, "Undocumented instruction ARC_dexcl2"),
	TO_ENUM(ARC_dmulh11, "Undocumented instruction ARC_dmulh11"),
	TO_ENUM(ARC_dmulh12, "Undocumented instruction ARC_dmulh12"),
	TO_ENUM(ARC_dmulh21, "Undocumented instruction ARC_dmulh21"),
	TO_ENUM(ARC_dmulh22, "Undocumented instruction ARC_dmulh22"),
	TO_ENUM(ARC_dsubh11, "Undocumented instruction ARC_dsubh11"),
	TO_ENUM(ARC_dsubh12, "Undocumented instruction ARC_dsubh12"),
	TO_ENUM(ARC_dsubh21, "Undocumented instruction ARC_dsubh21"),
	TO_ENUM(ARC_dsubh22, "Undocumented instruction ARC_dsubh22"),
	TO_ENUM(ARC_drsubh11, "Undocumented instruction ARC_drsubh11"),
	TO_ENUM(ARC_drsubh12, "Undocumented instruction ARC_drsubh12"),
	TO_ENUM(ARC_drsubh21, "Undocumented instruction ARC_drsubh21"),
	TO_ENUM(ARC_drsubh22, "Undocumented instruction ARC_drsubh22"),
	TO_ENUM(ARC_fadd, "Undocumented instruction ARC_fadd"),
	TO_ENUM(ARC_fsadd, "Undocumented instruction ARC_fsadd"),
	TO_ENUM(ARC_fmul, "Undocumented instruction ARC_fmul"),
	TO_ENUM(ARC_fsmul, "Undocumented instruction ARC_fsmul"),
	TO_ENUM(ARC_fsub, "Undocumented instruction ARC_fsub"),
	TO_ENUM(ARC_fssub, "Undocumented instruction ARC_fssub"),
	TO_ENUM(ARC_fxtr, "Undocumented instruction ARC_fxtr"),
	TO_ENUM(ARC_iaddr, "Undocumented instruction ARC_iaddr"),
	TO_ENUM(ARC_mpyqb, "Undocumented instruction ARC_mpyqb"),
	TO_ENUM(ARC_sfxtr, "Undocumented instruction ARC_sfxtr"),
	TO_ENUM(ARC_pkqb, "Undocumented instruction ARC_pkqb"),
	TO_ENUM(ARC_upkqb, "Undocumented instruction ARC_upkqb"),
	TO_ENUM(ARC_xpkqb, "Undocumented instruction ARC_xpkqb"),
	TO_ENUM(ARC_mpyw, "Signed 16x16 multiply"),
	TO_ENUM(ARC_mpyuw, "Unsigned 16x16 multiply"),
	TO_ENUM(ARC_bi, "Branch indexed"),
	TO_ENUM(ARC_bih, "Branch indexed half-word"),
	TO_ENUM(ARC_ldi, "Load indexed"),
	TO_ENUM(ARC_aex, "Exchange with auxiliary register"),
	TO_ENUM(ARC_bmskn, "Bit mask negated"),
	TO_ENUM(ARC_seteq, "Set if equal"),
	TO_ENUM(ARC_setne, "Set if not equal"),
	TO_ENUM(ARC_setlt, "Set if less than"),
	TO_ENUM(ARC_setge, "Set if greater or equal"),
	TO_ENUM(ARC_setlo, "Set if lower than"),
	TO_ENUM(ARC_seths, "Set if higher or same"),
	TO_ENUM(ARC_setle, "Set if less than or equal"),
	TO_ENUM(ARC_setgt, "Set if greater than"),
	TO_ENUM(ARC_rol, "Rotate left"),
	TO_ENUM(ARC_llock, "Load locked"),
	TO_ENUM(ARC_scond, "Store conditional"),
	TO_ENUM(ARC_seti, "Set interrupt enable and priority level"),
	TO_ENUM(ARC_clri, "Cler and get interrupt enable and priority level"),
	TO_ENUM(ARC_enter, "Function prologue sequence"),
	TO_ENUM(ARC_leave, "Function epilogue sequence"),
	TO_ENUM(ARC_div, "Signed integer divsion"),
	TO_ENUM(ARC_divu, "Unsigned integer divsion"),
	TO_ENUM(ARC_rem, "Signed integer remainder"),
	TO_ENUM(ARC_remu, "Unsigned integer remainder"),
	TO_ENUM(ARC_asrsr, "Shift right rounding and saturating"),
	TO_ENUM(ARC_valgn2h, "Two-way 16-bit vector align"),
	TO_ENUM(ARC_setacc, "Set the accumulator"),
	TO_ENUM(ARC_mac, "Signed 32x32 multiply accumulate"),
	TO_ENUM(ARC_macu, "Unsigned 32x32 multiply accumulate"),
	TO_ENUM(ARC_dmpyh, "Sum of dual signed 16x16 multiplication"),
	TO_ENUM(ARC_dmpyhu, "Sum of dual unsigned 16x16 multiplication"),
	TO_ENUM(ARC_dmach, "Dual signed 16x16 multiply accumulate"),
	TO_ENUM(ARC_dmachu, "Dual unsigned 16x16 multiply accumulate"),
	TO_ENUM(ARC_vadd2h, "Dual 16-bit addition"),
	TO_ENUM(ARC_vadds2h, "Dual 16-bit saturating addition"),
	TO_ENUM(ARC_vsub2h, "Dual 16-bit subtraction"),
	TO_ENUM(ARC_vsubs2h, "Dual 16-bit saturating subtraction"),
	TO_ENUM(ARC_vaddsub2h, "Dual 16-bit addition/subtraction"),
	TO_ENUM(ARC_vaddsubs2h, "Dual 16-bit saturating addition/subtraction"),
	TO_ENUM(ARC_vsubadd2h, "Dual 16-bit subtraction/addition"),
	TO_ENUM(ARC_vsubadds2h, "Dual 16-bit saturating subtraction/addition"),
	TO_ENUM(ARC_mpyd, "Signed 32x32 multiply (wide)"),
	TO_ENUM(ARC_mpydu, "Unsigned 32x32 multiply (wide)"),
	TO_ENUM(ARC_macd, "Signed 32x32 multiply accumulate (wide)"),
	TO_ENUM(ARC_macdu, "Unsigned 32x32 multiply accumulate (wide)"),
	TO_ENUM(ARC_vmpy2h, "Dual signed 16x16 multiply (wide)"),
	TO_ENUM(ARC_vmpy2hf, "Dual 16x16 saturating fractional multiply"),
	TO_ENUM(ARC_vmpy2hu, "Dual unsigned 16x16 multiply (wide)"),
	TO_ENUM(ARC_vmpy2hfr, "Dual 16x16 saturating rounded fractional multiply"),
	TO_ENUM(ARC_vmac2h, "Dual signed 16x16 multiply (wide)"),
	TO_ENUM(ARC_vmac2hf, "Dual 16x16 saturating fractional multiply"),
	TO_ENUM(ARC_vmac2hu, "Dual unsigned 16x16 multiply (wide)"),
	TO_ENUM(ARC_vmac2hfr, "Dual 16x16 saturating rounded fractional multiply"),
	TO_ENUM(ARC_vmpy2hwf, "Dual 16x16 saturating fractional multiply (wide)"),
	TO_ENUM(ARC_vasl2h, "Dual 16-bit arithmetic shift left"),
	TO_ENUM(ARC_vasls2h, "Dual 16-bit saturating arithmetic shift left"),
	TO_ENUM(ARC_vasr2h, "Dual 16-bit arithmetic shift right"),
	TO_ENUM(ARC_vasrs2h, "Dual 16-bit saturating arithmetic shift right"),
	TO_ENUM(ARC_vlsr2h, "Dual 16-bit logical shift right"),
	TO_ENUM(ARC_vasrsr2h, "Dual 16-bit saturating rounded arithmetic shift right"),
	TO_ENUM(ARC_vadd4b, "Quad 8-bit addition"),
	TO_ENUM(ARC_vmax2h, "Dual 16-bit maximum"),
	TO_ENUM(ARC_vsub4b, "Quad 8-bit subtraction"),
	TO_ENUM(ARC_vmin2h, "Dual 16-bit minimum"),
	TO_ENUM(ARC_adcs, "Signed saturating addition with carry in"),
	TO_ENUM(ARC_sbcs, "Signed saturating subtraction with carry in"),
	TO_ENUM(ARC_dmpyhwf, "Fractional saturating sum of dual 16x16 signed fractional multiply"),
	TO_ENUM(ARC_vpack2hl, "Compose lower 16-bits"),
	TO_ENUM(ARC_vpack2hm, "Compose upper 16-bits"),
	TO_ENUM(ARC_dmpyhf, "Saturating sum of dual 16x16 signed fractional multiply"),
	TO_ENUM(ARC_dmpyhfr, "Saturating rounded sum of dual 16x16 signed fractional multiply"),
	TO_ENUM(ARC_dmachf, "Saturating sum of dual 16x16 signed fractional multiply accumulate"),
	TO_ENUM(ARC_dmachfr, "Saturating rounded sum of dual 16x16 signed fractional multiply accumulate"),
	TO_ENUM(ARC_vperm, "Byte permutation with zero or sign extension"),
	TO_ENUM(ARC_bspush, "Bitstream push"),
	TO_ENUM(ARC_swape, "Swap byte ordering"),
	TO_ENUM(ARC_lsl16, "Logical shift left by 16 bits"),
	TO_ENUM(ARC_lsr16, "Logical shift right by 16 bits"),
	TO_ENUM(ARC_asr16, "Arithmetic shift right by 16 bits"),
	TO_ENUM(ARC_asr8, "Arithmetic shift right by 8 bits"),
	TO_ENUM(ARC_lsr8, "Logical shift right by 8 bits"),
	TO_ENUM(ARC_lsl8, "Logical shift left by 8 bits"),
	TO_ENUM(ARC_rol8, "Rotate left by 8 bits"),
	TO_ENUM(ARC_ror8, "Rotate right by 8 bits"),
	TO_ENUM(ARC_ffs, "Find first set bit"),
	TO_ENUM(ARC_fls, "Find last set bit"),
	TO_ENUM(ARC_getacc, "Get accumulator"),
	TO_ENUM(ARC_normacc, "Normalize accumulator"),
	TO_ENUM(ARC_satf, "Saturate according to flags"),
	TO_ENUM(ARC_vpack2hbl, "Pack lower bytes into lower 16 bits"),
	TO_ENUM(ARC_vpack2hbm, "Pack upper bytes into upper 16 bits"),
	TO_ENUM(ARC_vpack2hblf, "Pack upper bytes into lower 16 bits"),
	TO_ENUM(ARC_vpack2hbmf, "Pack lower bytes into upper 16 bits"),
	TO_ENUM(ARC_vext2bhlf, "Pack lower 2 bytes into upper byte of 16 bits each"),
	TO_ENUM(ARC_vext2bhmf, "Pack upper 2 bytes into upper byte of 16 bits each"),
	TO_ENUM(ARC_vrep2hl, "Repeat lower 16 bits"),
	TO_ENUM(ARC_vrep2hm, "Repeat upper 16 bits"),
	TO_ENUM(ARC_vext2bhl, "Pack lower 2 bytes into zero extended 16 bits"),
	TO_ENUM(ARC_vext2bhm, "Pack upper 2 bytes into zero extended 16 bits"),
	TO_ENUM(ARC_vsext2bhl, "Pack lower 2 bytes into sign extended 16 bits"),
	TO_ENUM(ARC_vsext2bhm, "Pack upper 2 bytes into sign extended 16 bits"),
	TO_ENUM(ARC_vabs2h, "Dual 16-bit absolute value"),
	TO_ENUM(ARC_vabss2h, "Dual saturating 16-bit absolute value"),
	TO_ENUM(ARC_vneg2h, "Dual 16-bit negation"),
	TO_ENUM(ARC_vnegs2h, "Dual saturating 16-bit negation"),
	TO_ENUM(ARC_vnorm2h, "Dual 16-bit normalization"),
	TO_ENUM(ARC_bspeek, "Bitstream peek"),
	TO_ENUM(ARC_bspop, "Bitstream pop"),
	TO_ENUM(ARC_sqrt, "Integer square root"),
	TO_ENUM(ARC_sqrtf, "Fractional square root"),
	TO_ENUM(ARC_aslacc, "Arithmetic shift of accumulator"),
	TO_ENUM(ARC_aslsacc, "Saturating arithmetic shift of accumulator"),
	TO_ENUM(ARC_flagacc, "Copy accumulator flags to status32 register"),
	TO_ENUM(ARC_modif, "Update address pointer"),
	TO_ENUM(ARC_cmpyhnfr, "Fractional 16+16 bit complex saturating rounded unshifted multiply"),
	TO_ENUM(ARC_cmpyhfr, "Fractional 16+16 bit complex saturating rounded multiply"),
	TO_ENUM(ARC_cmpychfr, "Fractional 16+16 bit complex saturating rounded conjugated multiply"),
	TO_ENUM(ARC_vmsub2hf, "Dual 16x16 saturating fractional multiply subtract"),
	TO_ENUM(ARC_vmsub2hfr, "Dual 16x16 saturating rounded fractional multiply subtract"),
	TO_ENUM(ARC_cmpychnfr, "Fractional 16+16 bit complex saturating rounded unshifted conjugated multiply"),
	TO_ENUM(ARC_cmachnfr, "Fractional 16+16 bit complex saturating rounded unshifted multiply accumulate"),
	TO_ENUM(ARC_cmachfr, "Fractional 16+16 bit complex saturating rounded unshifted accumulate"),
	TO_ENUM(ARC_cmacchnfr, "Fractional 16+16 bit complex saturating rounded conjugated multiply accumulate"),
	TO_ENUM(ARC_cmacchfr, "Fractional 16+16 bit complex saturating rounded unshifted conjugated multiply accumulate"),
	TO_ENUM(ARC_mpyf, "Signed 32-bit fractional saturating multiply"),
	TO_ENUM(ARC_mpyfr, "Signed 32-bit fractional saturating rounded multiply"),
	TO_ENUM(ARC_macf, "Signed 32-bit fractional saturating multiply accumulate"),
	TO_ENUM(ARC_macfr, "Signed 32-bit fractional saturating rounded multiply accumulate"),
	TO_ENUM(ARC_msubf, "Signed 32-bit fractional saturating multiply subtract"),
	TO_ENUM(ARC_msubfr, "Signed 32-bit fractional saturating rounded multiply subtract"),
	TO_ENUM(ARC_divf, "Signed 32-bit fractional division"),
	TO_ENUM(ARC_vmac2hnfr, "Dual signed 16-bit fractional saturating rounded multiply accumulate"),
	TO_ENUM(ARC_vmsub2hnfr, "Dual signed 16-bit fractional saturating rounded multiply subtract"),
	TO_ENUM(ARC_mpydf, "Signed 32-bit fractional multiply (wide)"),
	TO_ENUM(ARC_macdf, "Signed 32-bit fractional multiply accumulate (wide)"),
	TO_ENUM(ARC_msubwhfl, "Signed 32 x 16 (lower) fractional saturating multiply subtract"),
	TO_ENUM(ARC_msubdf, "Signed 32-bit fractional multiply subtract (wide)"),
	TO_ENUM(ARC_dmpyhbl, "Dual 16x8 signed multiply with lower two bytes"),
	TO_ENUM(ARC_dmpyhbm, "Dual 16x8 signed multiply with upper two bytes"),
	TO_ENUM(ARC_dmachbl, "Dual 16x8 signed multiply accumulate with lower two bytes"),
	TO_ENUM(ARC_dmachbm, "Dual 16x8 signed multiply accumulate with upper two bytes"),
	TO_ENUM(ARC_msubwhflr, "Signed 32 x 16 (lower) fractional saturating rounded multiply subtract"),
	TO_ENUM(ARC_cmpyhfmr, "Fractional 16+16 bit complex x 16bit real (upper) saturating rounded multiply"),
	TO_ENUM(ARC_cbflyhf0r, "Fractional 16+16 bit complex FFT butterfly, first half"),
	TO_ENUM(ARC_mpywhl, "Signed 32 x 16 (lower) multiply"),
	TO_ENUM(ARC_macwhl, "Signed 32 x 16 (lower) multiply accumulate"),
	TO_ENUM(ARC_mpywhul, "Unsigned 32 x 16 (lower) multiply"),
	TO_ENUM(ARC_macwhul, "Unsigned 32 x 16 (lower) multiply accumulate"),
	TO_ENUM(ARC_mpywhfm, "Signed 32 x 16 (upper) fractional saturating multiply"),
	TO_ENUM(ARC_mpywhfmr, "Signed 32 x 16 (upper) fractional saturating rounded multiply"),
	TO_ENUM(ARC_macwhfm, "Signed 32 x 16 (upper) fractional saturating multiply accumulate"),
	TO_ENUM(ARC_macwhfmr, "Signed 32 x 16 (upper) fractional saturating rounded multiply accumulate"),
	TO_ENUM(ARC_mpywhfl, "Signed 32 x 16 (lower) fractional saturating multiply"),
	TO_ENUM(ARC_mpywhflr, "Signed 32 x 16 (lower) fractional saturating rounded multiply"),
	TO_ENUM(ARC_macwhfl, "Signed 32 x 16 (lower) fractional saturating multiply accumulate"),
	TO_ENUM(ARC_macwhflr, "Signed 32 x 16 (lower) fractional saturating rounded multiply accumulate"),
	TO_ENUM(ARC_macwhkl, "Signed 32 x 16 (lower) 16-bit shifted multiply accumulate"),
	TO_ENUM(ARC_macwhkul, "Unsigned 32 x 16 (lower) 16-bit shifted multiply accumulate"),
	TO_ENUM(ARC_mpywhkl, "Signed 32 x 16 (lower) 16-bit shifted multiply"),
	TO_ENUM(ARC_mpywhkul, "Unsigned 32 x 16 (lower) 16-bit shifted multiply"),
	TO_ENUM(ARC_msubwhfm, "Signed 32 x 16 (upper) fractional saturating multiply subtract"),
	TO_ENUM(ARC_msubwhfmr, "Signed 32 x 16 (upper) fractional saturating rounded multiply subtract"),
	TO_ENUM(ARC_cbflyhf1r, "Fractional 16+16 bit complex FFT butterfly, second half"),
	TO_ENUM(ARC_fscmp, "Single precision floating point compare"),
	TO_ENUM(ARC_fscmpf, "Single precision floating point compare (IEEE 754 flag generation)"),
	TO_ENUM(ARC_fsmadd, "Single precision floating point fused multiply add"),
	TO_ENUM(ARC_fsmsub, "Single precision floating point fused multiply subtract"),
	TO_ENUM(ARC_fsdiv, "Single precision floating point division"),
	TO_ENUM(ARC_fcvt32, "Single precision floating point / integer conversion"),
	TO_ENUM(ARC_fssqrt, "Single precision floating point square root"),
	TO_ENUM(ARC_jli, "Jump and link indexed"),
	TO_ENUM(ARC_ei, "Execute indexed"),
	TO_ENUM(ARC_kflag, "Set kernel flags"),
	TO_ENUM(ARC_wevt, "Enter sleep state"),
	TO_ENUM(ARC_last, "Undocumented instruction ARC_last")
};
