auto instructions_PLFM_RL78 = flags_vector_t{
	TO_ENUM(RL78_null, "Undocumented instruction RL78_null"),
	TO_ENUM(RL78_subw, "Subtract Word - Word Data Subtraction"),
	TO_ENUM(RL78_movw, "Move Word - Word Data Transfer"),
	TO_ENUM(RL78_call, "Call - Subroutine Call"),
	TO_ENUM(RL78_clrw, "Clear Word - Word Data Clear"),
	TO_ENUM(RL78_addw, "Add Word - Word Data Addition"),
	TO_ENUM(RL78_ret, "Return - Return from Subroutine"),
	TO_ENUM(RL78_sel, "Select Register Bank"),
	TO_ENUM(RL78_push, "Push"),
	TO_ENUM(RL78_onew, "One Word - Word Data 0001 Set"),
	TO_ENUM(RL78_incw, "Increment Word - Word Data Increment"),
	TO_ENUM(RL78_cmpw, "Compare Word - Word Data Comparison"),
	TO_ENUM(RL78_bnz, "Branch if Not Zero"),
	TO_ENUM(RL78_clrb, "Clear byte - Byte Data Clear"),
	TO_ENUM(RL78_and, "And - Logical Product of Byte Data"),
	TO_ENUM(RL78_or, "Or - Logical Sum of Byte Data"),
	TO_ENUM(RL78_br, "Branch - Unconditional Branch"),
	TO_ENUM(RL78_pop, "Pop"),
	TO_ENUM(RL78_cmp, "Compare - Byte Data Comparison"),
	TO_ENUM(RL78_decw, "Decrement Word - Word Data Decrement"),
	TO_ENUM(RL78_inc, "Increment - Byte Data Increment"),
	TO_ENUM(RL78_bz, "Branch if Zero"),
	TO_ENUM(RL78_sknz, "Skip if not Z - Skip with Zero Flag (Z = 0)"),
	TO_ENUM(RL78_sknh, "Skip if not Higher than - Skip with numeric value comparison ((Z \/ CY) = 1)"),
	TO_ENUM(RL78_skh, "Skip if Higher than - Skip with numeric value comparison ((Z \/ CY) = 0)"),
	TO_ENUM(RL78_xor1, "Exclusive Or Single Bit - 1 Bit Data Exclusive Logical Sum"),
	TO_ENUM(RL78_or1, "Or Single Bit - 1 Bit Data Logical Sum"),
	TO_ENUM(RL78_and1, "And Single Bit - 1 Bit Data Logical Product"),
	TO_ENUM(RL78_mov1, "Move Single Bit - 1 Bit Data Transfer"),
	TO_ENUM(RL78_clr1, "Clear Single Bit (Carry Flag) - 1 Bit Data Clear"),
	TO_ENUM(RL78_set1, "Set Single Bit (Carry Flag) - 1 Bit Data Set"),
	TO_ENUM(RL78_not1, "Not Single Bit (Carry Flag) - 1 Bit Data Logical Negation"),
	TO_ENUM(RL78_skc, "Skip if CY - Skip with Carry Flag (CY = 1)"),
	TO_ENUM(RL78_sknc, "Skip if not CY - Skip with Carry Flag (CY = 0)"),
	TO_ENUM(RL78_skz, "Skip if Z - Skip with Zero Flag (Z = 1)"),
	TO_ENUM(RL78_mov, "Move - Byte Data Transfer"),
	TO_ENUM(RL78_btclr, "Branch if True and Clear - Conditional Branch and Clear by Bit Test (Byte Data Bit =1)"),
	TO_ENUM(RL78_bt, "Branch if True - Conditional Branch by Bit Test (Byte Data Bit = 1)"),
	TO_ENUM(RL78_bf, "Branch if False - Conditional Branch by Bit Test (Byte Data Bit = 0)"),
	TO_ENUM(RL78_shl, "Shift Left - Logical Shift to the Left"),
	TO_ENUM(RL78_shr, "Shift Right - Logical Shift to the Right"),
	TO_ENUM(RL78_sar, "Shift Arithmetic Right - Arithmetic Shift to the Right"),
	TO_ENUM(RL78_shlw, "Shift Left Word - Logical Shift to the Left"),
	TO_ENUM(RL78_shrw, "Shift Right Word - Logical Shift to the Right"),
	TO_ENUM(RL78_sarw, "Shift Arithmetic Right Word - Arithmetic Shift to the Right"),
	TO_ENUM(RL78_bc, "Branch if Carry - Conditional Branch with Carry Flag (CY = 1)"),
	TO_ENUM(RL78_bnc, "Branch if Not Carry - Conditional Branch with Carry Flag (CY = 0)"),
	TO_ENUM(RL78_bh, "Branch if Higher than - Conditional branch by numeric value comparison ((Z \/ CY) = 0)"),
	TO_ENUM(RL78_bnh, "Branch if Not Higher than - Conditional branch by numeric value comparison ((Z \/ CY) = 1)"),
	TO_ENUM(RL78_add, "Add - Byte Data Addition"),
	TO_ENUM(RL78_addc, "Add with Carry - Addition of Byte Data with Carry"),
	TO_ENUM(RL78_sub, "Subtract - Byte Data Subtraction"),
	TO_ENUM(RL78_subc, "Subtract with Carry -Subtraction of Byte Data with Carry"),
	TO_ENUM(RL78_xor, "Exclusive Or - Exclusive Logical Sum of Byte Data"),
	TO_ENUM(RL78_xch, "Exchange - Byte Data Transfer"),
	TO_ENUM(RL78_dec, "Decrement - Byte Data Decrement"),
	TO_ENUM(RL78_rolwc, "Rotate Left word with Carry - Word Data Rotation to the Left with Carry"),
	TO_ENUM(RL78_xchw, "Exchange Word - Word Data Transfer"),
	TO_ENUM(RL78_cmps, "Compare - Byte Data Comparison"),
	TO_ENUM(RL78_movs, "Move and change PSW - Byte Data Transfer and PSW Change"),
	TO_ENUM(RL78_halt, "Halt - HALT Mode Set"),
	TO_ENUM(RL78_cmp0, "Compare 00H - Byte Data Zero Comparison"),
	TO_ENUM(RL78_mulu, "Multiply Unsigned - Unsigned Multiplication of Data"),
	TO_ENUM(RL78_oneb, "One byte - Byte Data 01H Set"),
	TO_ENUM(RL78_ror, "Rotate Right - Byte Data Rotation to the Right"),
	TO_ENUM(RL78_rol, "Rotate Left - Byte Data Rotation to the Left"),
	TO_ENUM(RL78_rorc, "Rotate Right with Carry - Byte Data Rotation to the Right with Carry"),
	TO_ENUM(RL78_rolc, "Rotate Left with Carry - Byte Data Rotation to the Left with Carry"),
	TO_ENUM(RL78_brk, "Break - Software Vectored Interrupt"),
	TO_ENUM(RL78_retb, "Return from Break - Return from Software Vectored Interrupt"),
	TO_ENUM(RL78_reti, "Return from Interrupt - Return from Interrupt Vectored Interrupt"),
	TO_ENUM(RL78_stop, "Stop - Stop Mode Set"),
	TO_ENUM(RL78_nop, "No Operation"),
	TO_ENUM(RL78_callt, "Call Table - Subroutine Call (Refer to the Call Table)"),
	TO_ENUM(RL78_mulhu, "Multiply Unsigned - Unsigned Multiplication of Data"),
	TO_ENUM(RL78_mulh, "Multiply Signed - Signed Multiplication of Data"),
	TO_ENUM(RL78_divhu, "16-bit Divide Unsigned - Unsigned Division of Data"),
	TO_ENUM(RL78_divwu, "32-bit Divide Unsigned - Unsigned Division of Data"),
	TO_ENUM(RL78_machu, "Multiply and Accumulate Unsigned - Unsigned Multiplication and Accumulation of Data"),
	TO_ENUM(RL78_mach, "Multiply and Accumulate Signed - Signed Multiplication and Accumulation of Data"),
	TO_ENUM(RL78_last, "Undocumented instruction RL78_last")
};
