auto instructions_PLFM_HPPA = flags_vector_t{
	TO_ENUM(HPPA_null, "Undocumented instruction HPPA_null"),
	TO_ENUM(HPPA_add, "Add"),
	TO_ENUM(HPPA_addb, "Add and Branch"),
	TO_ENUM(HPPA_addi, "Add to Immediate"),
	TO_ENUM(HPPA_addib, "Add Immediate and Branch"),
	TO_ENUM(HPPA_addil, "Add to Immediate Left"),
	TO_ENUM(HPPA_and, "AND"),
	TO_ENUM(HPPA_andcm, "AND complement"),
	TO_ENUM(HPPA_b, "Branch"),
	TO_ENUM(HPPA_bb, "Branch on Bit"),
	TO_ENUM(HPPA_be, "Branch External"),
	TO_ENUM(HPPA_blr, "Branch and Link Register"),
	TO_ENUM(HPPA_break, "Break"),
	TO_ENUM(HPPA_bv, "Branch Vectored"),
	TO_ENUM(HPPA_bve, "Branch Vectored External"),
	TO_ENUM(HPPA_cldd, "Coprocessor Load Doubleword"),
	TO_ENUM(HPPA_cldw, "Coprocessor Load Word"),
	TO_ENUM(HPPA_clrbts, "Clear Branch Target Stack"),
	TO_ENUM(HPPA_cmpb, "Compare and Branch"),
	TO_ENUM(HPPA_cmpclr, "Compare and Clear"),
	TO_ENUM(HPPA_cmpib, "Compare Immediate and Branch"),
	TO_ENUM(HPPA_cmpiclr, "Compare Immediate and Clear"),
	TO_ENUM(HPPA_copr, "Coprocessor Operation"),
	TO_ENUM(HPPA_cstd, "Coprocessor Store Doubleword"),
	TO_ENUM(HPPA_cstw, "Coprocessor Store Word"),
	TO_ENUM(HPPA_dcor, "Decimal Correct"),
	TO_ENUM(HPPA_depd, "Deposit Doubleword"),
	TO_ENUM(HPPA_depdi, "Deposit Doubleword Immediate"),
	TO_ENUM(HPPA_depw, "Deposit Word"),
	TO_ENUM(HPPA_depwi, "Deposit Word Immediate"),
	TO_ENUM(HPPA_diag, "Diagnose"),
	TO_ENUM(HPPA_ds, "Divide Step"),
	TO_ENUM(HPPA_extrd, "Extract Doubleword"),
	TO_ENUM(HPPA_extrw, "Extract Word"),
	TO_ENUM(HPPA_fdc, "Flush Data Cache"),
	TO_ENUM(HPPA_fdce, "Flush Data Cache Entry"),
	TO_ENUM(HPPA_fic, "Flush Instruction Cache"),
	TO_ENUM(HPPA_fice, "Flush Instruction Cache Entry"),
	TO_ENUM(HPPA_hadd, "Halfword Parallel Add"),
	TO_ENUM(HPPA_havg, "Halfword Parallel Average"),
	TO_ENUM(HPPA_hshl, "Halfword Parallel Shift Left"),
	TO_ENUM(HPPA_hshladd, "Halfword Parallel Shift Left and Add"),
	TO_ENUM(HPPA_hshr, "Halfword Parallel Shift Right"),
	TO_ENUM(HPPA_hshradd, "Halfword Parallel Shift Right and Add"),
	TO_ENUM(HPPA_hsub, "Halfword Parallel Subtract"),
	TO_ENUM(HPPA_idtlbt, "Insert Data TLB Translation"),
	TO_ENUM(HPPA_iitlbt, "Insert Instruction TLB Translation"),
	TO_ENUM(HPPA_lci, "Load Coherence Index"),
	TO_ENUM(HPPA_ldb, "Load Byte"),
	TO_ENUM(HPPA_ldcd, "Load and Clear Doubleword"),
	TO_ENUM(HPPA_ldcw, "Load and Clear Word"),
	TO_ENUM(HPPA_ldd, "Load Doubleword"),
	TO_ENUM(HPPA_ldda, "Load Doubleword Absolute"),
	TO_ENUM(HPPA_ldh, "Load Halfword"),
	TO_ENUM(HPPA_ldil, "Load Immediate Left"),
	TO_ENUM(HPPA_ldo, "Load Offset"),
	TO_ENUM(HPPA_ldsid, "Load Space Identifier"),
	TO_ENUM(HPPA_ldw, "Load Word"),
	TO_ENUM(HPPA_ldwa, "Load Word Absolute"),
	TO_ENUM(HPPA_lpa, "Load Physical Address"),
	TO_ENUM(HPPA_mfctl, "Move From Control Register"),
	TO_ENUM(HPPA_mfia, "Move From Instruction Address"),
	TO_ENUM(HPPA_mfsp, "Move From Space Register"),
	TO_ENUM(HPPA_mixh, "Mix Halfwords"),
	TO_ENUM(HPPA_mixw, "Mix Words"),
	TO_ENUM(HPPA_movb, "Move and Branch"),
	TO_ENUM(HPPA_movib, "Move Immediate and Branch"),
	TO_ENUM(HPPA_mtctl, "Move To Control Register"),
	TO_ENUM(HPPA_mtsarcm, "Move To Shift Amount Register Complement"),
	TO_ENUM(HPPA_mtsm, "Move To System Mask"),
	TO_ENUM(HPPA_mtsp, "Move To Space Register"),
	TO_ENUM(HPPA_or, "Inclusive OR"),
	TO_ENUM(HPPA_pdc, "Purge Data Cache"),
	TO_ENUM(HPPA_pdtlb, "Purge Data TLB"),
	TO_ENUM(HPPA_pdtlbe, "Purge Data TLB Entry"),
	TO_ENUM(HPPA_permh, "Permute Halfwords"),
	TO_ENUM(HPPA_pitlb, "Purge Instruction TLB"),
	TO_ENUM(HPPA_pitlbe, "Purge Instruction TLB Entry"),
	TO_ENUM(HPPA_popbts, "Pop Branch Target Stack"),
	TO_ENUM(HPPA_probe, "Probe Access"),
	TO_ENUM(HPPA_probei, "Probe Access Immediate"),
	TO_ENUM(HPPA_pushbts, "Push Branch Target Stack"),
	TO_ENUM(HPPA_pushnom, "Push Nominated"),
	TO_ENUM(HPPA_rfi, "Return From Interruption"),
	TO_ENUM(HPPA_rsm, "Reset System Mask"),
	TO_ENUM(HPPA_shladd, "Shift Left and Add"),
	TO_ENUM(HPPA_shrpd, "Sihft Right Pair Doubleword"),
	TO_ENUM(HPPA_shrpw, "Sihft Right Pair Word"),
	TO_ENUM(HPPA_spop0, "Special Operation Zero"),
	TO_ENUM(HPPA_spop1, "Special Operation One"),
	TO_ENUM(HPPA_spop2, "Special Operation Two"),
	TO_ENUM(HPPA_spop3, "Special Operation Three"),
	TO_ENUM(HPPA_ssm, "Set System Mask"),
	TO_ENUM(HPPA_stb, "Store Byte"),
	TO_ENUM(HPPA_stby, "Store Bytes"),
	TO_ENUM(HPPA_std, "Store Doubleword"),
	TO_ENUM(HPPA_stda, "Store Doubleword Absolute"),
	TO_ENUM(HPPA_stdby, "Store Doubleword Bytes"),
	TO_ENUM(HPPA_sth, "Store Halfword"),
	TO_ENUM(HPPA_stw, "Store Word"),
	TO_ENUM(HPPA_stwa, "Store Word Absolute"),
	TO_ENUM(HPPA_sub, "Subtract"),
	TO_ENUM(HPPA_subi, "Subtract from Immediate"),
	TO_ENUM(HPPA_sync, "Synchronize Caches"),
	TO_ENUM(HPPA_syncdma, "Synchronize DMA"),
	TO_ENUM(HPPA_uaddcm, "Unit Add Complement"),
	TO_ENUM(HPPA_uxor, "Unit XOR"),
	TO_ENUM(HPPA_xor, "Exclusive OR"),
	TO_ENUM(HPPA_fabs, "Floating-Point Absolute Value"),
	TO_ENUM(HPPA_fadd, "Floating-Point Add"),
	TO_ENUM(HPPA_fcmp, "Floating-Point Compare"),
	TO_ENUM(HPPA_fcnv, "Floating-Point Convert"),
	TO_ENUM(HPPA_fcpy, "Floating-Point Copy"),
	TO_ENUM(HPPA_fdiv, "Floating-Point Divide"),
	TO_ENUM(HPPA_fid, "Floating-Point Identity"),
	TO_ENUM(HPPA_fldd, "Floating-Point Load Doubleword"),
	TO_ENUM(HPPA_fldw, "Floating-Point Load Word"),
	TO_ENUM(HPPA_fmpy, "Floating-Point Multiply"),
	TO_ENUM(HPPA_fmpyadd, "Floating-Point Multiply/Add"),
	TO_ENUM(HPPA_fmpyfadd, "Floating-Point Multiply Fused Add"),
	TO_ENUM(HPPA_fmpynfadd, "Floating-Point Multiply Negate Fused Add"),
	TO_ENUM(HPPA_fmpysub, "Floating-Point Multiply/Subtract"),
	TO_ENUM(HPPA_fneg, "Floating-Point Negate"),
	TO_ENUM(HPPA_fnegabs, "Floating-Point Negate Absolute Value"),
	TO_ENUM(HPPA_frem, "Floating-Point Remainder"),
	TO_ENUM(HPPA_frnd, "Floating-Point Round to Integer"),
	TO_ENUM(HPPA_fsqrt, "Floating-Point Square Root"),
	TO_ENUM(HPPA_fstd, "Floating-Point Store Doubleword"),
	TO_ENUM(HPPA_fstw, "Floating-Point Store Word"),
	TO_ENUM(HPPA_fsub, "Floating-Point Subtract"),
	TO_ENUM(HPPA_ftest, "Floating-Point Test"),
	TO_ENUM(HPPA_xmpyu, "Fixed-Point Multiply Unsigned"),
	TO_ENUM(HPPA_pmdis, "Performance Monitor Disable"),
	TO_ENUM(HPPA_pmenb, "Performance Monitor Enable"),
	TO_ENUM(HPPA_call, "Call Subroutine"),
	TO_ENUM(HPPA_ret, "Return From Subroutine"),
	TO_ENUM(HPPA_shld, "Shift Left Doubleword"),
	TO_ENUM(HPPA_shlw, "Shift Left Word"),
	TO_ENUM(HPPA_shrd, "Shift Right Doubleword"),
	TO_ENUM(HPPA_shrw, "Shift Right Word"),
	TO_ENUM(HPPA_ldi, "Load Immediate"),
	TO_ENUM(HPPA_copy, "Copy Register"),
	TO_ENUM(HPPA_mtsar, "Move To %SAR"),
	TO_ENUM(HPPA_nop, "No Operation"),
	TO_ENUM(HPPA_last, "Undocumented instruction HPPA_last")
};
