auto instructions_PLFM_RX = flags_vector_t{
	TO_ENUM(RX_null, "Undocumented instruction RX_null"),
	TO_ENUM(RX_abs, "Absolute value"),
	TO_ENUM(RX_adc, "Addition with carry"),
	TO_ENUM(RX_add, "Addition without carry"),
	TO_ENUM(RX_and, "Logical AND"),
	TO_ENUM(RX_bra, "Unconditional relative branch"),
	TO_ENUM(RX_brk, "Unconditional trap"),
	TO_ENUM(RX_bclr, "Clearing a bit"),
	TO_ENUM(RX_bfmov, "Transferring bit-fields"),
	TO_ENUM(RX_bfmovz, "Transferring a bit-field and setting the other bits at the destination to zero"),
	TO_ENUM(RX_beq, "Relative conditional branch, Equal to"),
	TO_ENUM(RX_bne, "Relative conditional branch, Not equal to"),
	TO_ENUM(RX_bgeu, "Relative conditional branch, Equal to or greater than"),
	TO_ENUM(RX_bltu, "Relative conditional branch, Less than"),
	TO_ENUM(RX_bgtu, "Relative conditional branch, Greater than"),
	TO_ENUM(RX_bleu, "Relative conditional branch, Equal to or less than"),
	TO_ENUM(RX_bpz, "Relative conditional branch, Positive or zero"),
	TO_ENUM(RX_bn, "Relative conditional branch, Negative"),
	TO_ENUM(RX_bge, "Relative conditional branch, Equal to or greater than as signed integer"),
	TO_ENUM(RX_blt, "Relative conditional branch, Less than as signed integer"),
	TO_ENUM(RX_bgt, "Relative conditional branch, Greater than as signed integer"),
	TO_ENUM(RX_ble, "Relative conditional branch, Equal to or less than as signed integer"),
	TO_ENUM(RX_bo, "Relative conditional branch, O flag is 1"),
	TO_ENUM(RX_bno, "Relative conditional branch, O flag is 0"),
	TO_ENUM(RX_bmeq, "Conditional bit transfer, Equal to"),
	TO_ENUM(RX_bmne, "Conditional bit transfer, Not equal to"),
	TO_ENUM(RX_bmgeu, "Conditional bit transfer, Equal to or greater than"),
	TO_ENUM(RX_bmltu, "Conditional bit transfer, Less than"),
	TO_ENUM(RX_bmgtu, "Conditional bit transfer, Greater than"),
	TO_ENUM(RX_bmleu, "Conditional bit transfer, Equal to or less than"),
	TO_ENUM(RX_bmpz, "Conditional bit transfer, Positive or zero"),
	TO_ENUM(RX_bmn, "Conditional bit transfer, Negative"),
	TO_ENUM(RX_bmge, "Conditional bit transfer, Equal to or greater than as signed integer"),
	TO_ENUM(RX_bmlt, "Conditional bit transfer, Less than as signed integer"),
	TO_ENUM(RX_bmgt, "Conditional bit transfer, Greater than as signed integer"),
	TO_ENUM(RX_bmle, "Conditional bit transfer, Equal to or less than as signed integer"),
	TO_ENUM(RX_bmo, "Conditional bit transfer, O flag is 1"),
	TO_ENUM(RX_bmno, "Conditional bit transfer, O flag is 0"),
	TO_ENUM(RX_bnot, "Inverting a bit"),
	TO_ENUM(RX_bset, "Setting a bit"),
	TO_ENUM(RX_bsr, "Relative subroutine branch"),
	TO_ENUM(RX_btst, "Testing a bit"),
	TO_ENUM(RX_clrpsw, "Clear a flag or bit in the PSW"),
	TO_ENUM(RX_cmp, "Comparison"),
	TO_ENUM(RX_div, "Signed division"),
	TO_ENUM(RX_divu, "Unsigned division"),
	TO_ENUM(RX_emaca, "Extend multiply-accumulate to the accumulator"),
	TO_ENUM(RX_emsba, "Extended multiply-subtract to the accumulator"),
	TO_ENUM(RX_emula, "Extended multiply to the accumulator"),
	TO_ENUM(RX_emul, "Signed multiplication"),
	TO_ENUM(RX_emulu, "Unsigned multiplication"),
	TO_ENUM(RX_fadd, "Single-precision floating-point addition"),
	TO_ENUM(RX_fcmp, "Single-precision floating-point comparison"),
	TO_ENUM(RX_fdiv, "Single-precision floating-point division"),
	TO_ENUM(RX_fmul, "Single-precision floating-point multiplication"),
	TO_ENUM(RX_fsqrt, "Single-precision floating-point square root"),
	TO_ENUM(RX_fsub, "Single-precision floating-point subtraction"),
	TO_ENUM(RX_ftoi, "Single-precision floating-point number to signed integer conversion"),
	TO_ENUM(RX_ftou, "Single-precision floating-point number to unsigned integer conversion"),
	TO_ENUM(RX_int, "Software interrupt"),
	TO_ENUM(RX_itof, "Signed integer to single-precision floating-point number conversion"),
	TO_ENUM(RX_jmp, "Unconditional jump"),
	TO_ENUM(RX_jsr, "Jump to a subroutine"),
	TO_ENUM(RX_machi, "Multiply-Accumulate the upper word"),
	TO_ENUM(RX_maclo, "Multiply-Accumulate the lower word"),
	TO_ENUM(RX_maclh, "Multiply-Accumulate the lower word and upper word"),
	TO_ENUM(RX_max, "Selecting the highest value"),
	TO_ENUM(RX_min, "Selecting the lowest value"),
	TO_ENUM(RX_mov, "Transferring data"),
	TO_ENUM(RX_movco, "Storing with LI flag clear"),
	TO_ENUM(RX_movli, "Loading with LI flag set"),
	TO_ENUM(RX_movu, "Transfer unsigned data"),
	TO_ENUM(RX_msbhi, "Multiply-Subtract the upper word"),
	TO_ENUM(RX_msblo, "Multiply-Subtract the lower word"),
	TO_ENUM(RX_msblh, "Multiply-Subtract the lower word and upper word"),
	TO_ENUM(RX_mul, "Multiplication"),
	TO_ENUM(RX_mulhi, "Multiply the upper word"),
	TO_ENUM(RX_mullo, "Multiply the lower word"),
	TO_ENUM(RX_mullh, "Multiply the lower word and upper word"),
	TO_ENUM(RX_mvfachi, "Move the upper longword from accumulator"),
	TO_ENUM(RX_mvfaclo, "Move the lower longword from the accumulator"),
	TO_ENUM(RX_mvfacmi, "Move the middle-order longword from the accumulator"),
	TO_ENUM(RX_mvfacgu, "Move the guard longword from the accumulator"),
	TO_ENUM(RX_mvfc, "Transfer from a control register"),
	TO_ENUM(RX_mvtacgu, "Move the guard longword to the accumulator"),
	TO_ENUM(RX_mvtachi, "Move the upper longword to the accumulator"),
	TO_ENUM(RX_mvtaclo, "Move the lower longword to the accumulator"),
	TO_ENUM(RX_mvtc, "Transfer to a control register"),
	TO_ENUM(RX_mvtipl, "Interrupt priority level setting"),
	TO_ENUM(RX_neg, "Negation"),
	TO_ENUM(RX_nop, "No operation"),
	TO_ENUM(RX_not, "Bitwise negation"),
	TO_ENUM(RX_or, "Logical OR"),
	TO_ENUM(RX_pop, "Restoring data from stack to register"),
	TO_ENUM(RX_popc, "Restoring a control register"),
	TO_ENUM(RX_popm, "Restoring multiple registers from the stack"),
	TO_ENUM(RX_push, "Saving data on the stack"),
	TO_ENUM(RX_pushc, "Saving a control register"),
	TO_ENUM(RX_pushm, "Saving multiple registers"),
	TO_ENUM(RX_racl, "Round the accumulator longword"),
	TO_ENUM(RX_rdacl, "Round the accumulator longword"),
	TO_ENUM(RX_racw, "Round the accumulator word"),
	TO_ENUM(RX_rdacw, "Round the accumulator word"),
	TO_ENUM(RX_revl, "Endian conversion"),
	TO_ENUM(RX_revw, "Endian conversion"),
	TO_ENUM(RX_rmpa, "Multiply-and-accumulate operation"),
	TO_ENUM(RX_rolc, "Rotation with carry to left"),
	TO_ENUM(RX_rorc, "Rotation with carry to right"),
	TO_ENUM(RX_rotl, "Rotation to left"),
	TO_ENUM(RX_rotr, "Rotation to right"),
	TO_ENUM(RX_round, "Conversion from single-precision floating-point number to signed integer"),
	TO_ENUM(RX_rstr, "Collective restoration of register values"),
	TO_ENUM(RX_rte, "Return from the exception"),
	TO_ENUM(RX_rtfi, "Return from the fast interrupt"),
	TO_ENUM(RX_rts, "Returning from a subroutine"),
	TO_ENUM(RX_rtsd, "Releasing stack frame and returning from subroutine"),
	TO_ENUM(RX_sat, "Saturation of signed 32-bit data"),
	TO_ENUM(RX_satr, "Saturation of signed 64-bit data for RMPA"),
	TO_ENUM(RX_save, "Collective saving of register values"),
	TO_ENUM(RX_sbb, "Subtraction with borrow"),
	TO_ENUM(RX_sceq, "Condition setting, Equal to"),
	TO_ENUM(RX_scne, "Condition setting, Not equal to"),
	TO_ENUM(RX_scgeu, "Condition setting, Equal to or greater than"),
	TO_ENUM(RX_scltu, "Condition setting, Less than"),
	TO_ENUM(RX_scgtu, "Condition setting, Greater than"),
	TO_ENUM(RX_scleu, "Condition setting, Equal to or less than"),
	TO_ENUM(RX_scpz, "Condition setting, Positive or zero"),
	TO_ENUM(RX_scn, "Condition setting, Negative"),
	TO_ENUM(RX_scge, "Condition setting, Equal to or greater than as signed integer"),
	TO_ENUM(RX_sclt, "Condition setting, Less than as signed integer"),
	TO_ENUM(RX_scgt, "Condition setting, Greater than as signed integer"),
	TO_ENUM(RX_scle, "Condition setting, Equal to or less than as signed integer"),
	TO_ENUM(RX_sco, "Condition setting, O flag is 1"),
	TO_ENUM(RX_scno, "Condition setting, O flag is 0"),
	TO_ENUM(RX_scmpu, "String comparison"),
	TO_ENUM(RX_setpsw, "Setting a flag or bit in the PSW"),
	TO_ENUM(RX_shar, "Arithmetic shift to the right"),
	TO_ENUM(RX_shll, "Logical and arithmetic shift to the left"),
	TO_ENUM(RX_shlr, "Logical shift to the right"),
	TO_ENUM(RX_smovb, "Transferring a string backward"),
	TO_ENUM(RX_smovf, "Transferring a string forward"),
	TO_ENUM(RX_smovu, "Transferring a string"),
	TO_ENUM(RX_sstr, "Storing a string"),
	TO_ENUM(RX_stnz, "Transfer with condition (Z == 0)"),
	TO_ENUM(RX_stz, "Transfer with condition (Z == 1)"),
	TO_ENUM(RX_sub, "Subtraction without borrow"),
	TO_ENUM(RX_suntil, "Searching for a string"),
	TO_ENUM(RX_swhile, "Searching for a string"),
	TO_ENUM(RX_tst, "Logical test"),
	TO_ENUM(RX_utof, "Unsigned integer to single-precision floating-point number conversion"),
	TO_ENUM(RX_wait, "Waiting"),
	TO_ENUM(RX_xchg, "Exchanging values"),
	TO_ENUM(RX_xor, "Logical Exclusive OR"),
	TO_ENUM(RX_dabs, "Double-precision floating-point absolute value"),
	TO_ENUM(RX_dadd, "Double-precision floating-point addition without carry"),
	TO_ENUM(RX_dcmpun, "Double-precision floating-point comparison, This condition is for detecting cases where classification of order based on the comparison is impossible."),
	TO_ENUM(RX_dcmpeq, "Double-precision floating-point comparison, This condition is for detecting that src2 is equal to src."),
	TO_ENUM(RX_dcmplt, "Double-precision floating-point comparison, This condition is for detecting that src2 is less than src."),
	TO_ENUM(RX_dcmple, "Double-precision floating-point comparison, This condition is for detecting that src2 is less than or equal to src."),
	TO_ENUM(RX_ddiv, "Double-precision floating-point division"),
	TO_ENUM(RX_dmov, "Double-precision floating-point transferring data"),
	TO_ENUM(RX_dmul, "Double-precision floating-point multiplication"),
	TO_ENUM(RX_dneg, "Double-precision floating-point negate"),
	TO_ENUM(RX_dpopm, "Restoring multiple double-precision floating-point registers"),
	TO_ENUM(RX_dpushm, "Saving multiple double-precision floating-point registers"),
	TO_ENUM(RX_dround, "Conversion from double-precision floating-point number to signed integer"),
	TO_ENUM(RX_dsqrt, "Double-precision floating-point square root"),
	TO_ENUM(RX_dsub, "Double-precision floating-point subtraction"),
	TO_ENUM(RX_dtof, "Double-precision floating-point number to single-precision floating-point number conversion"),
	TO_ENUM(RX_dtoi, "Double-precision floating-point number to signed integer conversion"),
	TO_ENUM(RX_dtou, "Double-precision floating-point number to unsigned integer conversion"),
	TO_ENUM(RX_ftod, "Single-precision floating-point number to double-precision floating-point number conversion"),
	TO_ENUM(RX_itod, "Signed integer to double-precision floating-point number conversion"),
	TO_ENUM(RX_mvfdc, "Transfer from double-precision floating-point control register"),
	TO_ENUM(RX_mvfdr, "Transfer from double-precision floating-point comparison result register"),
	TO_ENUM(RX_mvtdc, "Transfer to double-precision floating-point control register"),
	TO_ENUM(RX_utod, "Unsigned integer to double-precision floating-point number conversion"),
	TO_ENUM(RX_last, "Undocumented instruction RX_last")
};
