auto instructions_PLFM_F2MC = flags_vector_t{
	TO_ENUM(F2MC_null, "Undocumented instruction F2MC_null"),
	TO_ENUM(F2MC_mov, "Move  byte data from source to destination"),
	TO_ENUM(F2MC_movn, "Move immediate nibble data to A"),
	TO_ENUM(F2MC_movx, "Move byte data with sign extension from source to A"),
	TO_ENUM(F2MC_xch, "Exchange byte data of source to destination"),
	TO_ENUM(F2MC_movw, "Move word data from source to destination"),
	TO_ENUM(F2MC_xchw, "Exchange word data of source to destination"),
	TO_ENUM(F2MC_movl, "Move long word data from source to destination"),
	TO_ENUM(F2MC_add, "Add byte data of destination and source to destination"),
	TO_ENUM(F2MC_addc1, "Add byte data of AL and AH with Carry to AL"),
	TO_ENUM(F2MC_addc2, "Add byte data of A and effective address with Carry to A"),
	TO_ENUM(F2MC_adddc, "Add decimal data of AL and AH with Carry to AL"),
	TO_ENUM(F2MC_sub, "Subtract byte data of source from festination to destination"),
	TO_ENUM(F2MC_subc1, "Subtract byte data of AL from AH with Carry to AL"),
	TO_ENUM(F2MC_subc2, "Subtract byte data of effective address from A with Carry to A"),
	TO_ENUM(F2MC_subdc, "Subtract decimal data of AL from AH with Carry to AL"),
	TO_ENUM(F2MC_addw1, "Add word data of AH and AL to AL"),
	TO_ENUM(F2MC_addw2, "Add word data of destination and source to destination"),
	TO_ENUM(F2MC_addcw, "Add word data of A and effective address from A with Carry to A"),
	TO_ENUM(F2MC_subw1, "Subtract word data of AL from AH to AL"),
	TO_ENUM(F2MC_subw2, "Subtract word data of source from festination to destination"),
	TO_ENUM(F2MC_subcw, "Subtract word data of A and effective address from A with carry to A"),
	TO_ENUM(F2MC_addl, "Add long word data of destination and source to destination"),
	TO_ENUM(F2MC_subl, "Subtract long word data of source from festination to destination"),
	TO_ENUM(F2MC_inc, "Increment byte data"),
	TO_ENUM(F2MC_dec, "Decrement byte data"),
	TO_ENUM(F2MC_incw, "Increment word data"),
	TO_ENUM(F2MC_decw, "Decrement word data"),
	TO_ENUM(F2MC_incl, "Increment long word data"),
	TO_ENUM(F2MC_decl, "Decrement long word data"),
	TO_ENUM(F2MC_cmp1, "Compare byte data of AH and AL"),
	TO_ENUM(F2MC_cmp2, "Compare byte data of destination and source"),
	TO_ENUM(F2MC_cmpw1, "Compare word data of AH and AL"),
	TO_ENUM(F2MC_cmpw2, "Compare word data of destination and source"),
	TO_ENUM(F2MC_cmpl, "Compare long word data of destination and source"),
	TO_ENUM(F2MC_divu1, "Divide unsigned AH by AL"),
	TO_ENUM(F2MC_divu2, "Divide unsigned word data by unsigned byte data"),
	TO_ENUM(F2MC_divuw, "Divide unsigned long word data by unsigned word data"),
	TO_ENUM(F2MC_mulu1, "Multiply unsigned byte AH by AL"),
	TO_ENUM(F2MC_mulu2, "Multiply unsigned byte data"),
	TO_ENUM(F2MC_muluw1, "Multiply unsigned word AH by AL"),
	TO_ENUM(F2MC_muluw2, "Multiply unsigned word data"),
	TO_ENUM(F2MC_div1, "Divide AH by AL"),
	TO_ENUM(F2MC_div2, "Divide word data by byte data"),
	TO_ENUM(F2MC_divw, "Divide long word data by word data"),
	TO_ENUM(F2MC_mul1, "Multiply byte AH by AL"),
	TO_ENUM(F2MC_mul2, "Multiply byte data"),
	TO_ENUM(F2MC_mulw1, "Multiply word AH by AL"),
	TO_ENUM(F2MC_mulw2, "Multiply word data"),
	TO_ENUM(F2MC_and, "And byte data of destination and source to destination"),
	TO_ENUM(F2MC_or, "Or byte data of destination and source to destination"),
	TO_ENUM(F2MC_xor, "Exclusive or byte data of destination and source to destination"),
	TO_ENUM(F2MC_not, "Not byte data of destination"),
	TO_ENUM(F2MC_andw1, "And word data of AH and AL to AL"),
	TO_ENUM(F2MC_andw2, "And word data of destination and source to destination"),
	TO_ENUM(F2MC_orw1, "Or word data of AH and AL to AL"),
	TO_ENUM(F2MC_orw2, "Or word data of destination and source to destination"),
	TO_ENUM(F2MC_xorw1, "Exclusive or word data of AH and AL to AL"),
	TO_ENUM(F2MC_xorw2, "Exclusive or word data of destination and source to destination"),
	TO_ENUM(F2MC_notw, "Not word data of destination"),
	TO_ENUM(F2MC_andl, "And long word data of destination and source to destination"),
	TO_ENUM(F2MC_orl, "Or long word data of destination and source to destination"),
	TO_ENUM(F2MC_xorl, "Exclusive or long word data of destination and source to destination"),
	TO_ENUM(F2MC_neg, "Negate byte data of destination"),
	TO_ENUM(F2MC_negw, "Negate word data of destination"),
	TO_ENUM(F2MC_nrml, "Normalize long word"),
	TO_ENUM(F2MC_rorc, "Rotate byte data of A with Carry to right"),
	TO_ENUM(F2MC_rolc, "Rotate byte data of A with Carry to left"),
	TO_ENUM(F2MC_asr, "Arithmetic shift byte data of A to right"),
	TO_ENUM(F2MC_lsr, "Logical shift byte data of A to right"),
	TO_ENUM(F2MC_lsl, "Logical shift byte data of A to left"),
	TO_ENUM(F2MC_asrw1, "Arithmetic shift word data of A to right"),
	TO_ENUM(F2MC_asrw2, "Arithmetic shift word data of A to right"),
	TO_ENUM(F2MC_lsrw1, "Logical shift word data of A to right"),
	TO_ENUM(F2MC_lsrw2, "Logical shift word data of A to right"),
	TO_ENUM(F2MC_lslw1, "Logical shift word data of A to left"),
	TO_ENUM(F2MC_lslw2, "Logical shift word data of A to left"),
	TO_ENUM(F2MC_asrl, "Arithmetic shift long word data of A to right"),
	TO_ENUM(F2MC_lsrl, "Logical shift long word data of A to right"),
	TO_ENUM(F2MC_lsll, "Logical shift long word data of A to left"),
	TO_ENUM(F2MC_bz, "Branch if Zero"),
	TO_ENUM(F2MC_bnz, "Branch if Not Zero"),
	TO_ENUM(F2MC_bc, "Branch if Carry"),
	TO_ENUM(F2MC_bnc, "Branch if Not Carry"),
	TO_ENUM(F2MC_bn, "Branch if Negative"),
	TO_ENUM(F2MC_bp, "Branch if Not Negative"),
	TO_ENUM(F2MC_bv, "Branch if Overflow"),
	TO_ENUM(F2MC_bnv, "Branch if Not Overflow"),
	TO_ENUM(F2MC_bt, "Branch if Sticky"),
	TO_ENUM(F2MC_bnt, "Branch if Not Sticky"),
	TO_ENUM(F2MC_blt, "Branch if Overflow or Negative"),
	TO_ENUM(F2MC_bge, "Branch if Not (Overflow or Negative)"),
	TO_ENUM(F2MC_ble, "Branch if (Overflow xor Negative) or Zero"),
	TO_ENUM(F2MC_bgt, "Branch if Not ((Overflow xor Negative) or Zero)"),
	TO_ENUM(F2MC_bls, "Branch if Carry or Zero"),
	TO_ENUM(F2MC_bhi, "Branch if Not (Carry or Zero)"),
	TO_ENUM(F2MC_bra, "Branch unconditionally"),
	TO_ENUM(F2MC_jmp, "Jump destination address"),
	TO_ENUM(F2MC_jmpp, "Jump destination physical address"),
	TO_ENUM(F2MC_call, "Call subroutine"),
	TO_ENUM(F2MC_callv, "Call vectored subroutine"),
	TO_ENUM(F2MC_callp, "Call physical address"),
	TO_ENUM(F2MC_cbne, "Compare byte data and branch if not Equal"),
	TO_ENUM(F2MC_cwbne, "Compare word data and branch if not Equal"),
	TO_ENUM(F2MC_dbnz, "Decrement byte data and branch if not Zero"),
	TO_ENUM(F2MC_dwbnz, "Decrement word data and branch if not Zero"),
	TO_ENUM(F2MC_int, "Software interrupt"),
	TO_ENUM(F2MC_intp, "Software interrupt"),
	TO_ENUM(F2MC_int9, "Software interrupt"),
	TO_ENUM(F2MC_reti, "Return from interrupt"),
	TO_ENUM(F2MC_link, "Link and create new stack frame"),
	TO_ENUM(F2MC_unlink, "Unlink and create new stack frame"),
	TO_ENUM(F2MC_ret, "Return from subroutine"),
	TO_ENUM(F2MC_retp, "Return from physical address"),
	TO_ENUM(F2MC_pushw, "Push to stack memory"),
	TO_ENUM(F2MC_popw, "Pop from stack memory"),
	TO_ENUM(F2MC_jctx, "Jump context"),
	TO_ENUM(F2MC_movea, "Move effective address to destination"),
	TO_ENUM(F2MC_addsp, "Add word data of SP and immediate data to SP"),
	TO_ENUM(F2MC_nop, "No operation"),
	TO_ENUM(F2MC_adb, "ADB register"),
	TO_ENUM(F2MC_dtb, "DTB register"),
	TO_ENUM(F2MC_pcb, "PCB register"),
	TO_ENUM(F2MC_spb, "SPB register"),
	TO_ENUM(F2MC_ncc, "Flag change inhibit"),
	TO_ENUM(F2MC_cmr, "Common register bank"),
	TO_ENUM(F2MC_movb, "Move bit data"),
	TO_ENUM(F2MC_setb, "Set bit"),
	TO_ENUM(F2MC_clrb, "Clear bit"),
	TO_ENUM(F2MC_bbc, "Branch if bit condition satisfied"),
	TO_ENUM(F2MC_bbs, "Branch if bit condition satisfied"),
	TO_ENUM(F2MC_sbbs, "Set bit and branch if bit set"),
	TO_ENUM(F2MC_wbts, "Wait until bit condition satisfied"),
	TO_ENUM(F2MC_wbtc, "Wait until bit condition satisfied"),
	TO_ENUM(F2MC_swap, "Swap byte data of A"),
	TO_ENUM(F2MC_swapw, "Swap word data of A"),
	TO_ENUM(F2MC_ext, "Sign extend from byte data to word data"),
	TO_ENUM(F2MC_extw, "Sign extend from word data to long word data"),
	TO_ENUM(F2MC_zext, "Zero extendfrom byte data to word data"),
	TO_ENUM(F2MC_zextw, "Zero extendfrom word data to long word data"),
	TO_ENUM(F2MC_movsi, "Move string byte with addresses incremented"),
	TO_ENUM(F2MC_movsd, "Move string byte with addresses decremented"),
	TO_ENUM(F2MC_sceqi, "Scan string byte until Equal with address incremented"),
	TO_ENUM(F2MC_sceqd, "Scan string byte until Equal with address decremented"),
	TO_ENUM(F2MC_filsi, "Fill string byte"),
	TO_ENUM(F2MC_movswi, "Move string word with address incremented"),
	TO_ENUM(F2MC_movswd, "Move string word with address decremented"),
	TO_ENUM(F2MC_scweqi, "Scan string word until Equal with address incremented"),
	TO_ENUM(F2MC_scweqd, "Scan string word until Equal with address decremented"),
	TO_ENUM(F2MC_filswi, "Fill string word"),
	TO_ENUM(F2MC_bz16, "Branch if Zero"),
	TO_ENUM(F2MC_bnz16, "Branch if Not Zero"),
	TO_ENUM(F2MC_bc16, "Branch if Carry"),
	TO_ENUM(F2MC_bnc16, "Branch if Not Carry"),
	TO_ENUM(F2MC_bn16, "Branch if Negative"),
	TO_ENUM(F2MC_bp16, "Branch if Not Negative"),
	TO_ENUM(F2MC_bv16, "Branch if Overflow"),
	TO_ENUM(F2MC_bnv16, "Branch if Not Overflow"),
	TO_ENUM(F2MC_bt16, "Branch if Sticky"),
	TO_ENUM(F2MC_bnt16, "Branch if Not Sticky"),
	TO_ENUM(F2MC_blt16, "Branch if Overflow or Negative"),
	TO_ENUM(F2MC_bge16, "Branch if Not (Overflow or Negative)"),
	TO_ENUM(F2MC_ble16, "Branch if (Overflow xor Negative) or Zero"),
	TO_ENUM(F2MC_bgt16, "Branch if Not ((Overflow xor Negative) or Zero)"),
	TO_ENUM(F2MC_bls16, "Branch if Carry or Zero"),
	TO_ENUM(F2MC_bhi16, "Branch if Not (Carry or Zero)"),
	TO_ENUM(F2MC_cbne16, "Compare byte data and branch if not Equal"),
	TO_ENUM(F2MC_cwbne16, "Compare word data and branch if not Equal"),
	TO_ENUM(F2MC_dbnz16, "Decrement byte data and branch if not Zero"),
	TO_ENUM(F2MC_dwbnz16, "Decrement word data and branch if not Zero"),
	TO_ENUM(F2MC_bbc16, "Branch if bit condition satisfied"),
	TO_ENUM(F2MC_bbs16, "Branch if bit condition satisfied"),
	TO_ENUM(F2MC_sbbs16, "Set bit and branch if bit set"),
	TO_ENUM(F2MC_last, "Undocumented instruction F2MC_last")
};
