auto instructions_PLFM_6502 = flags_vector_t{
	TO_ENUM(M65_null, "Undocumented instruction M65_null"),
	TO_ENUM(M65_adc, "A <- (A) + M + C"),
	TO_ENUM(M65_anc, "A <- A /\ M, C <- ~A7"),
	TO_ENUM(M65_and, "A <- (A) /\ M"),
	TO_ENUM(M65_ane, "M <-[(A)\/$EE] /\ (X)/\(M)"),
	TO_ENUM(M65_arr, "A <- [(A /\ M) >> 1]"),
	TO_ENUM(M65_asl, "C <- A7, A <- (A) << 1"),
	TO_ENUM(M65_asr, "A <- [(A /\ M) >> 1]"),
	TO_ENUM(M65_bcc, "if C=0, PC = PC + offset"),
	TO_ENUM(M65_bcs, "if C=1, PC = PC + offset"),
	TO_ENUM(M65_beq, "if Z=1, PC = PC + offset"),
	TO_ENUM(M65_bit, "Z <- ~(A /\ M) N<-M7 V<-M6"),
	TO_ENUM(M65_bmi, "if N=1, PC = PC + offset"),
	TO_ENUM(M65_bne, "if Z=0, PC = PC + offset"),
	TO_ENUM(M65_bpl, "if N=0, PC = PC + offset"),
	TO_ENUM(M65_brk, "Stack <- PC, PC <- ($fffe)"),
	TO_ENUM(M65_bvc, "if V=0, PC = PC + offset"),
	TO_ENUM(M65_bvs, "if V=1, PC = PC + offset"),
	TO_ENUM(M65_clc, "C <- 0"),
	TO_ENUM(M65_cld, "D <- 0"),
	TO_ENUM(M65_cli, "I <- 0"),
	TO_ENUM(M65_clv, "V <- 0"),
	TO_ENUM(M65_cmp, "(A - M) -> NZC"),
	TO_ENUM(M65_cpx, "(X - M) -> NZC"),
	TO_ENUM(M65_cpy, "(Y - M) -> NZC"),
	TO_ENUM(M65_dcp, "M <- (M)-1, (A-M) -> NZC"),
	TO_ENUM(M65_dec, "M <- (M) - 1"),
	TO_ENUM(M65_dex, "X <- (X) - 1"),
	TO_ENUM(M65_dey, "Y <- (Y) - 1"),
	TO_ENUM(M65_eor, "A <- (A) \-/ M"),
	TO_ENUM(M65_inc, "M <- (M) + 1"),
	TO_ENUM(M65_inx, "X <- (X) +1"),
	TO_ENUM(M65_iny, "Y <- (Y) + 1"),
	TO_ENUM(M65_isb, "M <- (M) - 1,A <- (A)-M-~C"),
	TO_ENUM(M65_jmp, "PC <- Address"),
	TO_ENUM(M65_jmpi, "(PC <- Address)"),
	TO_ENUM(M65_jsr, "Stack <- PC, PC <- Address"),
	TO_ENUM(M65_lae, "X,S,A <- (S /\ M)"),
	TO_ENUM(M65_lax, "A <- M, X <- M"),
	TO_ENUM(M65_lda, "A <- M"),
	TO_ENUM(M65_ldx, "X <- M"),
	TO_ENUM(M65_ldy, "Y <- M"),
	TO_ENUM(M65_lsr, "C <- A0, A <- (A) >> 1"),
	TO_ENUM(M65_lxa, "X04 <- (X04) /\ M04, A04 <- (A04) /\ M04"),
	TO_ENUM(M65_nop, "[no operation]"),
	TO_ENUM(M65_ora, "A <- (A) V M"),
	TO_ENUM(M65_pha, "Stack <- (A)"),
	TO_ENUM(M65_php, "Stack <- (P)"),
	TO_ENUM(M65_pla, "A <- (Stack)"),
	TO_ENUM(M65_plp, "A <- (Stack)"),
	TO_ENUM(M65_rla, "M <- (M << 1) /\ (A)"),
	TO_ENUM(M65_rol, "C <- A7 & A <- A << 1 + C"),
	TO_ENUM(M65_ror, "C<-A0 & A<- (A7=C + A>>1)"),
	TO_ENUM(M65_rra, "M <- (M >> 1) + (A) + C"),
	TO_ENUM(M65_rti, "P <- (Stack), PC <-(Stack)"),
	TO_ENUM(M65_rts, "PC <- (Stack)"),
	TO_ENUM(M65_sax, "M <- (A) /\ (X)"),
	TO_ENUM(M65_sbc, "A <- (A) - M - ~C"),
	TO_ENUM(M65_sbx, "X <- (X)/\(A) - M"),
	TO_ENUM(M65_sec, "C <- 1"),
	TO_ENUM(M65_sed, "D <- 1"),
	TO_ENUM(M65_sei, "I <- 1"),
	TO_ENUM(M65_sha, "M <- (A) /\ (X) /\ (PCH+1)"),
	TO_ENUM(M65_shs, "X <- (A) /\ (X), S <- (X), M <- (X) /\ (PCH+1)"),
	TO_ENUM(M65_shx, "M <- (X) /\ (PCH+1)"),
	TO_ENUM(M65_shy, "M <- (Y) /\ (PCH+1)"),
	TO_ENUM(M65_slo, "M <- (M >> 1) + A + C"),
	TO_ENUM(M65_sre, "M <- (M >> 1) \-/ A"),
	TO_ENUM(M65_sta, "M <- (A)"),
	TO_ENUM(M65_stx, "M <- (X)"),
	TO_ENUM(M65_sty, "M <- (Y)"),
	TO_ENUM(M65_tax, "X <- (A)"),
	TO_ENUM(M65_tay, "Y <- (A)"),
	TO_ENUM(M65_tsx, "X <- (S)"),
	TO_ENUM(M65_txa, "A <- (X)"),
	TO_ENUM(M65_txs, "S <- (X)"),
	TO_ENUM(M65_tya, "A <- (Y)"),
	TO_ENUM(M65_bbr0, "Branch if bit 0 reset"),
	TO_ENUM(M65_bbr1, "Branch if bit 1 reset"),
	TO_ENUM(M65_bbr2, "Branch if bit 2 reset"),
	TO_ENUM(M65_bbr3, "Branch if bit 3 reset"),
	TO_ENUM(M65_bbr4, "Branch if bit 4 reset"),
	TO_ENUM(M65_bbr5, "Branch if bit 5 reset"),
	TO_ENUM(M65_bbr6, "Branch if bit 6 reset"),
	TO_ENUM(M65_bbr7, "Branch if bit 7 reset"),
	TO_ENUM(M65_bbs0, "Branch if bit 0 set"),
	TO_ENUM(M65_bbs1, "Branch if bit 1 set"),
	TO_ENUM(M65_bbs2, "Branch if bit 2 set"),
	TO_ENUM(M65_bbs3, "Branch if bit 3 set"),
	TO_ENUM(M65_bbs4, "Branch if bit 4 set"),
	TO_ENUM(M65_bbs5, "Branch if bit 5 set"),
	TO_ENUM(M65_bbs6, "Branch if bit 6 set"),
	TO_ENUM(M65_bbs7, "Branch if bit 7 set"),
	TO_ENUM(M65_rmb0, "Reset memory bit 0"),
	TO_ENUM(M65_rmb1, "Reset memory bit 1"),
	TO_ENUM(M65_rmb2, "Reset memory bit 2"),
	TO_ENUM(M65_rmb3, "Reset memory bit 3"),
	TO_ENUM(M65_rmb4, "Reset memory bit 4"),
	TO_ENUM(M65_rmb5, "Reset memory bit 5"),
	TO_ENUM(M65_rmb6, "Reset memory bit 6"),
	TO_ENUM(M65_rmb7, "Reset memory bit 7"),
	TO_ENUM(M65_smb0, "Set memory bit 0"),
	TO_ENUM(M65_smb1, "Set memory bit 1"),
	TO_ENUM(M65_smb2, "Set memory bit 2"),
	TO_ENUM(M65_smb3, "Set memory bit 3"),
	TO_ENUM(M65_smb4, "Set memory bit 4"),
	TO_ENUM(M65_smb5, "Set memory bit 5"),
	TO_ENUM(M65_smb6, "Set memory bit 6"),
	TO_ENUM(M65_smb7, "Set memory bit 7"),
	TO_ENUM(M65_stz, "Store zero"),
	TO_ENUM(M65_tsb, "Test and set bits"),
	TO_ENUM(M65_trb, "Test and reset bits"),
	TO_ENUM(M65_phy, "Push Y register"),
	TO_ENUM(M65_ply, "Pull Y register"),
	TO_ENUM(M65_phx, "Push X register"),
	TO_ENUM(M65_plx, "Pull X register"),
	TO_ENUM(M65_bra, "Branch always"),
	TO_ENUM(M65_wai, "Wait for interrupt"),
	TO_ENUM(M65_stp, "Stop processor"),
	TO_ENUM(M65_last, "Undocumented instruction M65_last")
};
