auto instructions_PLFM_TMS = flags_vector_t{
	TO_ENUM(TMS_null, "Undocumented instruction TMS_null"),
	TO_ENUM(TMS_abs, "Absolute value of Acc"),
	TO_ENUM(TMS_adcb, "Add ACCB to Acc With Carry"),
	TO_ENUM(TMS_add, "Add to Acc"),
	TO_ENUM(TMS_addb, "Add ACCB to Acc"),
	TO_ENUM(TMS_addc, "Add to Acc With Carry"),
	TO_ENUM(TMS_adds, "Add to Acc With Sign-Extension Suppressed"),
	TO_ENUM(TMS_addt, "Add to Acc With Shift Specified by TREG1"),
	TO_ENUM(TMS_adrk, "Add to Aux Register With Short Immediate"),
	TO_ENUM(TMS_and, "AND With Acc"),
	TO_ENUM(TMS_andb, "AND ACCD With Acc"),
	TO_ENUM(TMS_apac, "Add P Register to Acc"),
	TO_ENUM(TMS_apl, "AND Data Memory Value With DBMR"),
	TO_ENUM(TMS_apl2, "AND Data Memory Value With Long Constant"),
	TO_ENUM(TMS_b, "Branch Unconditionally"),
	TO_ENUM(TMS_bacc, "Branch to Location (Acc)"),
	TO_ENUM(TMS_baccd, "Branch to Location (Acc) Delayed"),
	TO_ENUM(TMS_banz, "Branch on Aux Register Not Zero"),
	TO_ENUM(TMS_banzd, "Branch on Aux Register Not Zero Delayed"),
	TO_ENUM(TMS_bcnd, "Branch Conditionally"),
	TO_ENUM(TMS_bcndd, "Branch Conditionally Delayed"),
	TO_ENUM(TMS_bd, "Branch Unconditionally Delayed"),
	TO_ENUM(TMS_bit, "Test Bit"),
	TO_ENUM(TMS_bitt, "Test Bit Specified by TREG2"),
	TO_ENUM(TMS_bldd, "Block Move From Data Memory to Data Memory"),
	TO_ENUM(TMS_bldp, "Block Move From Data Memory to Program Memory"),
	TO_ENUM(TMS_blpd, "Block Move From Program Memory to Data Memory"),
	TO_ENUM(TMS_bsar, "Barrel Shift"),
	TO_ENUM(TMS_cala, "Call Subroutine at (Acc)"),
	TO_ENUM(TMS_calad, "Call Subroutine at (Acc) Delayed"),
	TO_ENUM(TMS_call, "Call Unconditionally"),
	TO_ENUM(TMS_calld, "Call Unconditionally Delayed"),
	TO_ENUM(TMS_cc, "Call Conditionally"),
	TO_ENUM(TMS_ccd, "Call Conditionally Delayed"),
	TO_ENUM(TMS_clrc, "Clear Control Bit"),
	TO_ENUM(TMS_cmpl, "Complement Acc"),
	TO_ENUM(TMS_cmpr, "Compare Aux Register With ARCR"),
	TO_ENUM(TMS_cpl, "Compare DBMR With Data Value"),
	TO_ENUM(TMS_cpl2, "Compare Long Immediate With Data Value"),
	TO_ENUM(TMS_crgt, "Test for Acc Greater Than ACCB"),
	TO_ENUM(TMS_crlt, "Test for Acc Smaller Than ACCB"),
	TO_ENUM(TMS_dmov, "Data Move in Data Memory"),
	TO_ENUM(TMS_estop, "Emulator Stop"),
	TO_ENUM(TMS_exar, "Exchange ACCB With Acc"),
	TO_ENUM(TMS_idle, "Idle Until Interrupt"),
	TO_ENUM(TMS_idle2, "Idle Until Interrupt - Low Power Mode"),
	TO_ENUM(TMS_in, "Input Data From Port"),
	TO_ENUM(TMS_intr, "Soft Interrupt"),
	TO_ENUM(TMS_lacb, "Load Acc With ACCB"),
	TO_ENUM(TMS_lacc, "Load Acc With Shift"),
	TO_ENUM(TMS_lacl, "Load Low Acc and Clear High Acc"),
	TO_ENUM(TMS_lact, "Load Acc With Shift Specified by TREG1"),
	TO_ENUM(TMS_lamm, "Load Acc With Memory-Mapped Register"),
	TO_ENUM(TMS_lar, "Load Aux Register"),
	TO_ENUM(TMS_ldp, "Load Data Memory Pointer"),
	TO_ENUM(TMS_lmmr, "Load Memory-Mapped Register"),
	TO_ENUM(TMS_lph, "Load Product High Register"),
	TO_ENUM(TMS_lst, "Load Status Register"),
	TO_ENUM(TMS_lt, "Load TREG0"),
	TO_ENUM(TMS_lta, "Load TREG0 and Accumulate Previous Product"),
	TO_ENUM(TMS_ltd, "Load TREG0,Accumulate Previous Product and Move Data"),
	TO_ENUM(TMS_ltp, "Load TREG0 and Store P -> Acc"),
	TO_ENUM(TMS_lts, "Load TREG0 and Subtract Previous Product"),
	TO_ENUM(TMS_mac, "Multiply and Accumulate"),
	TO_ENUM(TMS_macd, "Multiply and Accumulate With Data Move"),
	TO_ENUM(TMS_madd, "Multiply and Accumulate With Data Move and Dynamic Addressing"),
	TO_ENUM(TMS_mads, "Multiply and Accumulate With Dynamic Addressing"),
	TO_ENUM(TMS_mar, "Modify Aux Register"),
	TO_ENUM(TMS_mpy, "Multiply"),
	TO_ENUM(TMS_mpya, "Multiply and Accumulate Previous Product"),
	TO_ENUM(TMS_mpys, "Multiply and Subtract Previous Product"),
	TO_ENUM(TMS_mpyu, "Multiply Unsigned"),
	TO_ENUM(TMS_neg, "Negate Acc"),
	TO_ENUM(TMS_nmi, "Nonmaskable Interrupt"),
	TO_ENUM(TMS_nop, "No Operation"),
	TO_ENUM(TMS_norm, "Normalize Contents of Acc"),
	TO_ENUM(TMS_opl, "OR With DBMS"),
	TO_ENUM(TMS_opl2, "OR With Long Immediate"),
	TO_ENUM(TMS_or, "OR With Acc"),
	TO_ENUM(TMS_orb, "OR ACCB With Accumulator"),
	TO_ENUM(TMS_out, "Out Data to Port"),
	TO_ENUM(TMS_pac, "Load Acc <- P"),
	TO_ENUM(TMS_pop, "Pop Top of Stack to Low Acc"),
	TO_ENUM(TMS_popd, "Pop Top of Stack to Data Memory"),
	TO_ENUM(TMS_pshd, "Push Data Memory Value Onto Stack"),
	TO_ENUM(TMS_push, "Push Low Acc Onto Stack"),
	TO_ENUM(TMS_ret, "Return From Subroutine"),
	TO_ENUM(TMS_retc, "Return Conditionally"),
	TO_ENUM(TMS_retcd, "Return Conditionally Delayed"),
	TO_ENUM(TMS_retd, "Return From Subroutine Delayed"),
	TO_ENUM(TMS_rete, "Enable Interrupts and Return From Interrupt"),
	TO_ENUM(TMS_reti, "Return From Interrupt"),
	TO_ENUM(TMS_rol, "Rotate Acc Left"),
	TO_ENUM(TMS_rolb, "Rotate ACCB and Acc Left"),
	TO_ENUM(TMS_ror, "Rotate Acc Right"),
	TO_ENUM(TMS_rorb, "Rotate ACCB and Acc Right"),
	TO_ENUM(TMS_rpt, "Repeat Next Instruction"),
	TO_ENUM(TMS_rptb, "Repeat Block"),
	TO_ENUM(TMS_rptz, "Repeat Preceded by Clearing Acc and P"),
	TO_ENUM(TMS_sacb, "Store Acc in ACCB"),
	TO_ENUM(TMS_sach, "Store High Acc With Shift"),
	TO_ENUM(TMS_sacl, "Store Low Acc With Shift"),
	TO_ENUM(TMS_samm, "Store Acc in Memory-Mapped Register"),
	TO_ENUM(TMS_sar, "Store Aux Register"),
	TO_ENUM(TMS_sath, "Barrel Shift Acc as Specified by TREG1(4)"),
	TO_ENUM(TMS_satl, "Barrel Shift Acc as Specified by TREG1(3-0)"),
	TO_ENUM(TMS_sbb, "Subtract ACCB From Acc"),
	TO_ENUM(TMS_sbbb, "Subtract ACCB From Acc With Borrow"),
	TO_ENUM(TMS_sbrk, "Subtract From Aux Register Short Immediate"),
	TO_ENUM(TMS_setc, "Set Control Bit"),
	TO_ENUM(TMS_sfl, "Shift Acc Left"),
	TO_ENUM(TMS_sflb, "Shift ACCB and Acc Left"),
	TO_ENUM(TMS_sfr, "Shift Acc Right"),
	TO_ENUM(TMS_sfrb, "Shift ACCB and Acc Right"),
	TO_ENUM(TMS_smmr, "Store Memory-Mapped Register"),
	TO_ENUM(TMS_spac, "Subtract P From Acc"),
	TO_ENUM(TMS_sph, "Store High P Register"),
	TO_ENUM(TMS_spl, "Store Low P Register"),
	TO_ENUM(TMS_splk, "Store Parallel Long Immediate"),
	TO_ENUM(TMS_spm, "Store ACCB and Acc Right"),
	TO_ENUM(TMS_sqra, "Square and Accumulate Previous Product"),
	TO_ENUM(TMS_sqrs, "Square and Subtract Previous Product"),
	TO_ENUM(TMS_sst, "Store Status Register"),
	TO_ENUM(TMS_sub, "Subtract From Acc"),
	TO_ENUM(TMS_subb, "Subtract From Acc With Borrow"),
	TO_ENUM(TMS_subc, "Conditional Subtract"),
	TO_ENUM(TMS_subs, "Subtract From Acc With Sign-Extension Suppressed"),
	TO_ENUM(TMS_subt, "Subtract From Acc With Shift Specified by TREG1"),
	TO_ENUM(TMS_tblr, "Table Read"),
	TO_ENUM(TMS_tblw, "Table Write"),
	TO_ENUM(TMS_trap, "Software Interrupt"),
	TO_ENUM(TMS_xc, "Execute Conditionally"),
	TO_ENUM(TMS_xor, "Exclusive-OR With Acc"),
	TO_ENUM(TMS_xorb, "Exclusive-OR of ACCB With Acc"),
	TO_ENUM(TMS_xpl, "Exclusive-OR Data Memory Value"),
	TO_ENUM(TMS_xpl2, "Exclusive-OR Data Memory Value"),
	TO_ENUM(TMS_zalr, "Zero Low Acc Load High Acc With Rounding"),
	TO_ENUM(TMS_zap, "Zero Acc and P"),
	TO_ENUM(TMS_zpr, "Zero P Register"),
	TO_ENUM(TMS_last, "Undocumented instruction TMS_last")
};
