auto instructions_PLFM_M740 = flags_vector_t{
	TO_ENUM(m740_null, "Undocumented instruction m740_null"),
	TO_ENUM(m740_adc, "add with carry"),
	TO_ENUM(m740_and, "logical and"),
	TO_ENUM(m740_asl, "arithmetic shift left"),
	TO_ENUM(m740_bbc, "branch on bit clear"),
	TO_ENUM(m740_bbs, "branch on bit set"),
	TO_ENUM(m740_bcc, "branch on carry clear"),
	TO_ENUM(m740_bcs, "branch on carry set"),
	TO_ENUM(m740_beq, "branch on equal"),
	TO_ENUM(m740_bit, "test bit in memory with accumulator"),
	TO_ENUM(m740_bmi, "branch on result minus"),
	TO_ENUM(m740_bne, "branch on not equal"),
	TO_ENUM(m740_bpl, "branch on result plus"),
	TO_ENUM(m740_bra, "branch always"),
	TO_ENUM(m740_brk, "force break"),
	TO_ENUM(m740_bvc, "branch on overflow clear"),
	TO_ENUM(m740_bvs, "branch on overflow set"),
	TO_ENUM(m740_clb, "clear bit"),
	TO_ENUM(m740_clc, "clear carry flag"),
	TO_ENUM(m740_cld, "clear decimal mode"),
	TO_ENUM(m740_cli, "clear interrupt disable status"),
	TO_ENUM(m740_clt, "clear transfer flag"),
	TO_ENUM(m740_clv, "clear overflow flag"),
	TO_ENUM(m740_cmp, "compare"),
	TO_ENUM(m740_com, "complement"),
	TO_ENUM(m740_cpx, "compare memory and index register X"),
	TO_ENUM(m740_cpy, "compare memory and index register Y"),
	TO_ENUM(m740_dec, "decrement by one"),
	TO_ENUM(m740_dex, "decrement index register X by one"),
	TO_ENUM(m740_dey, "decrement index register Y by one"),
	TO_ENUM(m740_div, "divide memory by accumulator"),
	TO_ENUM(m740_eor, "exclusive or memory with accumulator"),
	TO_ENUM(m740_inc, "increment by one"),
	TO_ENUM(m740_inx, "increment index register X by one"),
	TO_ENUM(m740_iny, "increment index register Y by one"),
	TO_ENUM(m740_jmp, "jump"),
	TO_ENUM(m740_jsr, "jump to subroutine"),
	TO_ENUM(m740_lda, "load accumulator with memory"),
	TO_ENUM(m740_ldm, "load immediate data to memory"),
	TO_ENUM(m740_ldx, "load index register X from memory"),
	TO_ENUM(m740_ldy, "load index register Y from memory"),
	TO_ENUM(m740_lsr, "logical shift right"),
	TO_ENUM(m740_mul, "multiply accumulator and memory"),
	TO_ENUM(m740_nop, "no operation"),
	TO_ENUM(m740_ora, "or memory with accumulator"),
	TO_ENUM(m740_pha, "push accumulator on stack"),
	TO_ENUM(m740_php, "push processor status on stack"),
	TO_ENUM(m740_pla, "pull accumulator from stack"),
	TO_ENUM(m740_plp, "pull processor status from stack"),
	TO_ENUM(m740_rol, "rotate one bit left"),
	TO_ENUM(m740_ror, "rotate one bit right"),
	TO_ENUM(m740_rrf, "rotate right of four bits"),
	TO_ENUM(m740_rti, "return from interrupt"),
	TO_ENUM(m740_rts, "return from subroutine"),
	TO_ENUM(m740_sbc, "subtract with carry"),
	TO_ENUM(m740_seb, "set bit"),
	TO_ENUM(m740_sec, "set carry flag"),
	TO_ENUM(m740_sed, "set decimal mode"),
	TO_ENUM(m740_sei, "set interrupt disable flag"),
	TO_ENUM(m740_set, "set transfert flag"),
	TO_ENUM(m740_sta, "store accumulator in memory"),
	TO_ENUM(m740_stp, "stop"),
	TO_ENUM(m740_stx, "store index register X in memory"),
	TO_ENUM(m740_sty, "store index register Y in memory"),
	TO_ENUM(m740_tax, "transfert accumulator to index register X"),
	TO_ENUM(m740_tay, "transfert accumulator to index register Y"),
	TO_ENUM(m740_tst, "test for negative or zero"),
	TO_ENUM(m740_tsx, "transfert stack pointer to index register X"),
	TO_ENUM(m740_txa, "transfert index register X to accumulator"),
	TO_ENUM(m740_txs, "transfert index register X to stack pointer"),
	TO_ENUM(m740_tya, "transfert index register Y to accumulator"),
	TO_ENUM(m740_wit, "wait"),
	TO_ENUM(m740_last, "Undocumented instruction m740_last")
};
