auto instructions_PLFM_C166 = flags_vector_t{
	TO_ENUM(C166_null, "Undocumented instruction C166_null"),
	TO_ENUM(C166_add, "Integer Addition"),
	TO_ENUM(C166_addb, "Integer Addition Byte"),
	TO_ENUM(C166_addc, "Integer Addition with Carry"),
	TO_ENUM(C166_addcb, "Integer Addition with Carry Byte"),
	TO_ENUM(C166_and, "Logical AND"),
	TO_ENUM(C166_andb, "Logical AND Byte"),
	TO_ENUM(C166_ashr, "Arithmetic Shift Right"),
	TO_ENUM(C166_atomic, "Begin ATOMIC Sequence"),
	TO_ENUM(C166_band, "Bit Logical AND"),
	TO_ENUM(C166_bclr, "Bit Clear"),
	TO_ENUM(C166_bcmp, "Bit to Bit Compare"),
	TO_ENUM(C166_bfldh, "Bit Field High Byte"),
	TO_ENUM(C166_bfldl, "Bit Field Low Byte"),
	TO_ENUM(C166_bmov, "Bit to Bit Move"),
	TO_ENUM(C166_bmovn, "Bit to Bit Move and Negate"),
	TO_ENUM(C166_bor, "Bit Logical OR"),
	TO_ENUM(C166_bset, "Bit Set"),
	TO_ENUM(C166_bxor, "Bit Logical XOR"),
	TO_ENUM(C166_calla, "Call Subroutine Absolute"),
	TO_ENUM(C166_calli, "Call Subroutine Indirect"),
	TO_ENUM(C166_callr, "Call Subroutine Relative"),
	TO_ENUM(C166_calls, "Call Inter-Segment Subroutine"),
	TO_ENUM(C166_cmp, "Integer Compare"),
	TO_ENUM(C166_cmpb, "Integer Compare Byte"),
	TO_ENUM(C166_cmpd1, "Integer Compare and Decrement by 1"),
	TO_ENUM(C166_cmpd2, "Integer Compare and Decrement by 2"),
	TO_ENUM(C166_cmpi1, "Integer Compare and Increment by 1"),
	TO_ENUM(C166_cmpi2, "Integer Compare and Increment by 2"),
	TO_ENUM(C166_cpl, "Integer One's Complement"),
	TO_ENUM(C166_cplb, "Integer One's Complement Byte"),
	TO_ENUM(C166_diswdt, "Disable Watchdog Timer"),
	TO_ENUM(C166_div, "16-by-16 Signed Division"),
	TO_ENUM(C166_divl, "32-by-16 Signed Division"),
	TO_ENUM(C166_divlu, "32-by-16 Unsigned Division"),
	TO_ENUM(C166_divu, "16-by-16 Unsigned Division"),
	TO_ENUM(C166_einit, "End of Intialization"),
	TO_ENUM(C166_extr, "Begin Extended Register Sequence"),
	TO_ENUM(C166_extp, "Begin Extended Page Sequence"),
	TO_ENUM(C166_extpr, "Begin Extended Page and Register Sequence"),
	TO_ENUM(C166_exts, "Begin Extended Segment Sequence"),
	TO_ENUM(C166_extsr, "Begin Extended Segment and Register Sequence"),
	TO_ENUM(C166_idle, "Enter Idle Mode"),
	TO_ENUM(C166_jb, "Relative Jump if Bit Set"),
	TO_ENUM(C166_jbc, "Relative Jump if Bit Set and Clear Bit"),
	TO_ENUM(C166_jmpa, "Absolute Conditional Jump"),
	TO_ENUM(C166_jmpi, "Indirect Conditional Jump"),
	TO_ENUM(C166_jmpr, "Relative Conditional Jump"),
	TO_ENUM(C166_jmps, "Absolute Inter-Segment Jump"),
	TO_ENUM(C166_jnb, "Relative Jump if Bit Clear"),
	TO_ENUM(C166_jnbs, "Relative Jump if Bit Clear and Set Bit"),
	TO_ENUM(C166_mov, "Move Word"),
	TO_ENUM(C166_movb, "Move Byte"),
	TO_ENUM(C166_movbs, "Move Byte Sign Extend"),
	TO_ENUM(C166_movbz, "Move Byte Zero Extend"),
	TO_ENUM(C166_mul, "Signed Multiplication"),
	TO_ENUM(C166_mulu, "Unsigned Multiplication"),
	TO_ENUM(C166_neg, "Integer Two's Complement"),
	TO_ENUM(C166_negb, "Integer Two's Complement Byte"),
	TO_ENUM(C166_nop, "No Operation"),
	TO_ENUM(C166_or, "Logical OR"),
	TO_ENUM(C166_orb, "Logical OR Byte"),
	TO_ENUM(C166_pcall, "Push Word and Call Subroutine Absolute"),
	TO_ENUM(C166_pop, "Pop Word from System Stack"),
	TO_ENUM(C166_prior, "Prioritize Register"),
	TO_ENUM(C166_push, "Push Word on System Stack"),
	TO_ENUM(C166_pwrdn, "Enter Power Down Mode"),
	TO_ENUM(C166_ret, "Return from Subroutine"),
	TO_ENUM(C166_reti, "Return from Interrupt Routine"),
	TO_ENUM(C166_retp, "Return from Subroutine and Pop Word"),
	TO_ENUM(C166_rets, "Return from Inter-Segment Subroutine"),
	TO_ENUM(C166_rol, "Rotate Left"),
	TO_ENUM(C166_ror, "Rotate Right"),
	TO_ENUM(C166_scxt, "Switch Context"),
	TO_ENUM(C166_shl, "Shift Left"),
	TO_ENUM(C166_shr, "Shift Rightt"),
	TO_ENUM(C166_srst, "Software Reset"),
	TO_ENUM(C166_srvwdt, "Service Watchdog Timer"),
	TO_ENUM(C166_sub, "Integer Subtraction"),
	TO_ENUM(C166_subb, "Integer Subtraction Byte"),
	TO_ENUM(C166_subc, "Integer Subtraction with Carry"),
	TO_ENUM(C166_subcb, "Integer Subtraction with Carry Byte"),
	TO_ENUM(C166_trap, "Software Trap"),
	TO_ENUM(C166_xor, "Logical Exclusive OR"),
	TO_ENUM(C166_xorb, "Logical Exclusive OR Byte"),
	TO_ENUM(C166_enwdt, "Enable Watchdog Timer"),
	TO_ENUM(C166_sbrk, "Software Break"),
	TO_ENUM(C166_last, "Undocumented instruction C166_last")
};
