auto instructions_PLFM_NEC_78K0S = flags_vector_t{
	TO_ENUM(NEC_78K_0S_null, "Undocumented instruction NEC_78K_0S_null"),
	TO_ENUM(NEC_78K_0S_cmp, "Compare Byte Data Comparison"),
	TO_ENUM(NEC_78K_0S_xor, "Exclusive Or Exclusive Logical Sum of Byte Data"),
	TO_ENUM(NEC_78K_0S_and, "AND Logical Product of Byte Data"),
	TO_ENUM(NEC_78K_0S_or, "OR Logical Sum of Byte Data"),
	TO_ENUM(NEC_78K_0S_add, "ADD Byte Data Addition"),
	TO_ENUM(NEC_78K_0S_sub, "Subtract Byte Data Subtraction"),
	TO_ENUM(NEC_78K_0S_addc, "Add with Carry Addition of Byte Data with Carry"),
	TO_ENUM(NEC_78K_0S_subc, "Subtract with Carry Subtraction of Byte Data with Carry"),
	TO_ENUM(NEC_78K_0S_subw, "Subtract Word Data Subtraction"),
	TO_ENUM(NEC_78K_0S_addw, "Add Word Data Addition"),
	TO_ENUM(NEC_78K_0S_cmpw, "Compare Word Data Comparison"),
	TO_ENUM(NEC_78K_0S_inc, "Increment Byte Data Increment"),
	TO_ENUM(NEC_78K_0S_dec, "Decrement Byte Data Decrement"),
	TO_ENUM(NEC_78K_0S_incw, "Increment Word Data Increment"),
	TO_ENUM(NEC_78K_0S_decw, "Decrement Word Data Decrement"),
	TO_ENUM(NEC_78K_0S_ror, "Rotate Right Byte Data Rotation to the Right"),
	TO_ENUM(NEC_78K_0S_rol, "Rotate Left Byte Data Rotation to the Left"),
	TO_ENUM(NEC_78K_0S_rorc, "Rotate Right with Carry Byte Data Rotation to the Right with Carry"),
	TO_ENUM(NEC_78K_0S_rolc, "Rotate Left with Carry Byte Data Rotation to the Left with Carry"),
	TO_ENUM(NEC_78K_0S_call, "CALL Subroutine Call (16 Bit Direct)"),
	TO_ENUM(NEC_78K_0S_callt, "Call Table Subroutine Call (Call Table Reference)"),
	TO_ENUM(NEC_78K_0S_ret, "Return from Subroutine"),
	TO_ENUM(NEC_78K_0S_reti, "Return from Interrupt / Return from Hardware Vectored Interrupt"),
	TO_ENUM(NEC_78K_0S_mov, "Move Byte Data Transfer"),
	TO_ENUM(NEC_78K_0S_xch, "Exchange Byte Data Exchange"),
	TO_ENUM(NEC_78K_0S_xchw, "Exchange Word Data Exchange"),
	TO_ENUM(NEC_78K_0S_set1, "Set Single Bit (Carry Flag) 1 Bit Data Set"),
	TO_ENUM(NEC_78K_0S_clr1, "Clear Single Bit (Carry Flag) 1 Bit Data Clear"),
	TO_ENUM(NEC_78K_0S_not1, "Not Single Bit (Carry Flag) 1 Bit Data Logical Negation"),
	TO_ENUM(NEC_78K_0S_push, "Push"),
	TO_ENUM(NEC_78K_0S_pop, "Pop"),
	TO_ENUM(NEC_78K_0S_movw, "Move Word Data Transfer / Word Data Transfer with Stack Pointer"),
	TO_ENUM(NEC_78K_0S_br, "Unconditional Branch"),
	TO_ENUM(NEC_78K_0S_bc, "Branch if Carry Conditional Branch with Carry Flag (CY = 1)"),
	TO_ENUM(NEC_78K_0S_bnc, "Branch if Not Carry Conditional Branch with Carry Flag (CY = 0)"),
	TO_ENUM(NEC_78K_0S_bz, "Branch if Zero Conditional Branch with Zero Flag (Z = 1)"),
	TO_ENUM(NEC_78K_0S_bnz, "Branch if Not Zero Conditional Branch with Zero Flag (Z = 0)"),
	TO_ENUM(NEC_78K_0S_bt, "Branch if True Conditional Branch by Bit Test (Byte Data Bit = 1)"),
	TO_ENUM(NEC_78K_0S_bf, "Branch if False Conditional Branch by Bit Test (Byte Data Bit = 0)"),
	TO_ENUM(NEC_78K_0S_dbnz, "Decrement and Branch if Not Zero Conditional Loop (R1 != 0)"),
	TO_ENUM(NEC_78K_0S_nop, "No Operation"),
	TO_ENUM(NEC_78K_0S_EI, "Enable Interrupt"),
	TO_ENUM(NEC_78K_0S_DI, "Disable Interrupt"),
	TO_ENUM(NEC_78K_0S_HALT, "HALT Mode Set"),
	TO_ENUM(NEC_78K_0S_STOP, "Stop Mode Set"),
	TO_ENUM(NEC_78K_0S_last, "Undocumented instruction NEC_78K_0S_last")
};
