auto instructions_PLFM_I960 = flags_vector_t{
	TO_ENUM(I960_null, "Undocumented instruction I960_null"),
	TO_ENUM(I960_addc, "Add ordinal with carry"),
	TO_ENUM(I960_addi, "Add integer"),
	TO_ENUM(I960_addo, "Add ordinal"),
	TO_ENUM(I960_alterbit, "Alter bit"),
	TO_ENUM(I960_and, "Src2 AND src1"),
	TO_ENUM(I960_andnot, "Src2 AND (NOT src1)"),
	TO_ENUM(I960_atadd, "Atomic add"),
	TO_ENUM(I960_atmod, "Atomic modify"),
	TO_ENUM(I960_b, "Branch"),
	TO_ENUM(I960_bal, "Branch and Link"),
	TO_ENUM(I960_balx, "Branch and Link Extended"),
	TO_ENUM(I960_bbc, "Check bit and branch if clear"),
	TO_ENUM(I960_bbs, "Check bit and branch if set"),
	TO_ENUM(I960_bno, "Branch if unordered/false"),
	TO_ENUM(I960_bg, "Branch if greater"),
	TO_ENUM(I960_be, "Branch if equal/true"),
	TO_ENUM(I960_bge, "Branch if greater or equal"),
	TO_ENUM(I960_bl, "Branch if less"),
	TO_ENUM(I960_bne, "Branch if not equal"),
	TO_ENUM(I960_ble, "Branch if less or equal"),
	TO_ENUM(I960_bo, "Branch if ordered"),
	TO_ENUM(I960_bx, "Branch Extended"),
	TO_ENUM(I960_call, "Call"),
	TO_ENUM(I960_calls, "Call system"),
	TO_ENUM(I960_callx, "Call extended"),
	TO_ENUM(I960_chkbit, "Check bit"),
	TO_ENUM(I960_clrbit, "Clear bit"),
	TO_ENUM(I960_cmpdeci, "Compare and decrement integer"),
	TO_ENUM(I960_cmpdeco, "Compare and decrement ordinal"),
	TO_ENUM(I960_cmpi, "Compare integer"),
	TO_ENUM(I960_cmpibno, "Compare integer and branch if unordered"),
	TO_ENUM(I960_cmpibg, "Compare integer and branch if greater"),
	TO_ENUM(I960_cmpibe, "Compare integer and branch if equal"),
	TO_ENUM(I960_cmpibge, "Compare integer and branch if greater or equal"),
	TO_ENUM(I960_cmpibl, "Compare integer and branch if less"),
	TO_ENUM(I960_cmpibne, "Compare integer and branch if not equal"),
	TO_ENUM(I960_cmpible, "Compare integer and branch if less or equal"),
	TO_ENUM(I960_cmpibo, "Compare integer and branch if ordered"),
	TO_ENUM(I960_cmpinci, "Compare and increment integer"),
	TO_ENUM(I960_cmpinco, "Compare and increment ordinal"),
	TO_ENUM(I960_cmpo, "Compare ordinal"),
	TO_ENUM(I960_cmpobg, "Compare ordinal and branch if greater"),
	TO_ENUM(I960_cmpobe, "Compare ordinal and branch if equal"),
	TO_ENUM(I960_cmpobge, "Compare ordinal and branch if greater or equal"),
	TO_ENUM(I960_cmpobl, "Compare ordinal and branch if less"),
	TO_ENUM(I960_cmpobne, "Compare ordinal and branch if not equal"),
	TO_ENUM(I960_cmpoble, "Compare ordinal and branch if less or equal"),
	TO_ENUM(I960_concmpi, "Conditional compare integer"),
	TO_ENUM(I960_concmpo, "Conditional compare ordinal"),
	TO_ENUM(I960_divi, "Divide integer"),
	TO_ENUM(I960_divo, "Divide ordinal"),
	TO_ENUM(I960_ediv, "Extended divide"),
	TO_ENUM(I960_emul, "Extended multiply"),
	TO_ENUM(I960_eshro, "Extended shift right ordinal"),
	TO_ENUM(I960_extract, "Extract"),
	TO_ENUM(I960_faultno, "Fault if unordered"),
	TO_ENUM(I960_faultg, "Fault if greater"),
	TO_ENUM(I960_faulte, "Fault if equal"),
	TO_ENUM(I960_faultge, "Fault if greater or equal"),
	TO_ENUM(I960_faultl, "Fault if less"),
	TO_ENUM(I960_faultne, "Fault if not equal"),
	TO_ENUM(I960_faultle, "Fault if less or equal"),
	TO_ENUM(I960_faulto, "Fault if ordered"),
	TO_ENUM(I960_flushreg, "Flush cached local register sets to memory"),
	TO_ENUM(I960_fmark, "Force mark"),
	TO_ENUM(I960_ld, "Load word"),
	TO_ENUM(I960_lda, "Load address"),
	TO_ENUM(I960_ldib, "Load integer byte"),
	TO_ENUM(I960_ldis, "Load integer short"),
	TO_ENUM(I960_ldl, "Load long"),
	TO_ENUM(I960_ldob, "Load ordinal byte"),
	TO_ENUM(I960_ldos, "Load ordinal short"),
	TO_ENUM(I960_ldq, "Load quad"),
	TO_ENUM(I960_ldt, "Load triple"),
	TO_ENUM(I960_mark, "Mark"),
	TO_ENUM(I960_modac, "Modify the AC register"),
	TO_ENUM(I960_modi, "Modulo integer"),
	TO_ENUM(I960_modify, "Modify"),
	TO_ENUM(I960_modpc, "Modify the process controls register"),
	TO_ENUM(I960_modtc, "Modify trace controls"),
	TO_ENUM(I960_mov, "Move word"),
	TO_ENUM(I960_movl, "Move long word"),
	TO_ENUM(I960_movq, "Move quad word"),
	TO_ENUM(I960_movt, "Move triple word"),
	TO_ENUM(I960_muli, "Multiply integer"),
	TO_ENUM(I960_mulo, "Multiply ordinal"),
	TO_ENUM(I960_nand, "NOT (src2 AND src1)"),
	TO_ENUM(I960_nor, "NOT (src2 OR src1)"),
	TO_ENUM(I960_not, "NOT src1"),
	TO_ENUM(I960_notand, "(NOT src2) AND src1"),
	TO_ENUM(I960_notbit, "Not bit"),
	TO_ENUM(I960_notor, "(NOT src2) or src1"),
	TO_ENUM(I960_or, "Src2 OR src1"),
	TO_ENUM(I960_ornot, "Src2 or (NOT src1)"),
	TO_ENUM(I960_remi, "Remainder integer"),
	TO_ENUM(I960_remo, "Remainder ordinal"),
	TO_ENUM(I960_ret, "Return"),
	TO_ENUM(I960_rotate, "Rotate left"),
	TO_ENUM(I960_scanbit, "Scan for bit"),
	TO_ENUM(I960_scanbyte, "Scan byte equal"),
	TO_ENUM(I960_setbit, "Set bit"),
	TO_ENUM(I960_shli, "Shift left integer"),
	TO_ENUM(I960_shlo, "Shift left ordinal"),
	TO_ENUM(I960_shrdi, "Shift right dividing integer"),
	TO_ENUM(I960_shri, "Shift right integer"),
	TO_ENUM(I960_shro, "Shift right ordinal"),
	TO_ENUM(I960_spanbit, "Span over bit"),
	TO_ENUM(I960_st, "Store word"),
	TO_ENUM(I960_stib, "Store integer byte"),
	TO_ENUM(I960_stis, "Store integer short"),
	TO_ENUM(I960_stl, "Store long"),
	TO_ENUM(I960_stob, "Store ordinal byte"),
	TO_ENUM(I960_stos, "Store ordinal short"),
	TO_ENUM(I960_stq, "Store quad"),
	TO_ENUM(I960_stt, "Store triple"),
	TO_ENUM(I960_subc, "Subtract ordinal with carry"),
	TO_ENUM(I960_subi, "Subtract integer"),
	TO_ENUM(I960_subo, "Subtract ordinal"),
	TO_ENUM(I960_syncf, "Synchronize faults"),
	TO_ENUM(I960_testno, "Test for unordered"),
	TO_ENUM(I960_testg, "Test for greater"),
	TO_ENUM(I960_teste, "Test for equal"),
	TO_ENUM(I960_testge, "Test for greater or equal"),
	TO_ENUM(I960_testl, "Test for less"),
	TO_ENUM(I960_testne, "Test for not equal"),
	TO_ENUM(I960_testle, "Test for less or equal"),
	TO_ENUM(I960_testo, "Test for ordered"),
	TO_ENUM(I960_xnor, "Src2 XNOR src1"),
	TO_ENUM(I960_xor, "Src2 XOR src1"),
	TO_ENUM(I960_sdma, "Set up a DMA controller channel"),
	TO_ENUM(I960_sysctl, "Perform system control function"),
	TO_ENUM(I960_udma, "Copy current DMA pointers to internal data RAM"),
	TO_ENUM(I960_dcinva, "Undocumented instruction I960_dcinva"),
	TO_ENUM(I960_cmpob, "Undocumented instruction I960_cmpob"),
	TO_ENUM(I960_cmpib, "Undocumented instruction I960_cmpib"),
	TO_ENUM(I960_cmpos, "Undocumented instruction I960_cmpos"),
	TO_ENUM(I960_cmpis, "Undocumented instruction I960_cmpis"),
	TO_ENUM(I960_bswap, "Undocumented instruction I960_bswap"),
	TO_ENUM(I960_intdis, "Undocumented instruction I960_intdis"),
	TO_ENUM(I960_inten, "Undocumented instruction I960_inten"),
	TO_ENUM(I960_synmov, "Undocumented instruction I960_synmov"),
	TO_ENUM(I960_synmovl, "Undocumented instruction I960_synmovl"),
	TO_ENUM(I960_synmovq, "Undocumented instruction I960_synmovq"),
	TO_ENUM(I960_cmpstr, "Undocumented instruction I960_cmpstr"),
	TO_ENUM(I960_movqstr, "Undocumented instruction I960_movqstr"),
	TO_ENUM(I960_movstr, "Undocumented instruction I960_movstr"),
	TO_ENUM(I960_inspacc, "Undocumented instruction I960_inspacc"),
	TO_ENUM(I960_ldphy, "Undocumented instruction I960_ldphy"),
	TO_ENUM(I960_synld, "Undocumented instruction I960_synld"),
	TO_ENUM(I960_fill, "Undocumented instruction I960_fill"),
	TO_ENUM(I960_daddc, "Undocumented instruction I960_daddc"),
	TO_ENUM(I960_dsubc, "Undocumented instruction I960_dsubc"),
	TO_ENUM(I960_dmovt, "Undocumented instruction I960_dmovt"),
	TO_ENUM(I960_condrec, "Undocumented instruction I960_condrec"),
	TO_ENUM(I960_receive, "Undocumented instruction I960_receive"),
	TO_ENUM(I960_intctl, "Undocumented instruction I960_intctl"),
	TO_ENUM(I960_icctl, "Undocumented instruction I960_icctl"),
	TO_ENUM(I960_dcctl, "Undocumented instruction I960_dcctl"),
	TO_ENUM(I960_halt, "Undocumented instruction I960_halt"),
	TO_ENUM(I960_send, "Undocumented instruction I960_send"),
	TO_ENUM(I960_sendserv, "Undocumented instruction I960_sendserv"),
	TO_ENUM(I960_resumprcs, "Undocumented instruction I960_resumprcs"),
	TO_ENUM(I960_schedprcs, "Undocumented instruction I960_schedprcs"),
	TO_ENUM(I960_saveprcs, "Undocumented instruction I960_saveprcs"),
	TO_ENUM(I960_condwait, "Undocumented instruction I960_condwait"),
	TO_ENUM(I960_wait, "Undocumented instruction I960_wait"),
	TO_ENUM(I960_signal, "Undocumented instruction I960_signal"),
	TO_ENUM(I960_ldtime, "Undocumented instruction I960_ldtime"),
	TO_ENUM(I960_addono, "Undocumented instruction I960_addono"),
	TO_ENUM(I960_addino, "Undocumented instruction I960_addino"),
	TO_ENUM(I960_subono, "Undocumented instruction I960_subono"),
	TO_ENUM(I960_subino, "Undocumented instruction I960_subino"),
	TO_ENUM(I960_selno, "Undocumented instruction I960_selno"),
	TO_ENUM(I960_addog, "Undocumented instruction I960_addog"),
	TO_ENUM(I960_addig, "Undocumented instruction I960_addig"),
	TO_ENUM(I960_subog, "Undocumented instruction I960_subog"),
	TO_ENUM(I960_subig, "Undocumented instruction I960_subig"),
	TO_ENUM(I960_selg, "Undocumented instruction I960_selg"),
	TO_ENUM(I960_addoe, "Undocumented instruction I960_addoe"),
	TO_ENUM(I960_addie, "Undocumented instruction I960_addie"),
	TO_ENUM(I960_suboe, "Undocumented instruction I960_suboe"),
	TO_ENUM(I960_subie, "Undocumented instruction I960_subie"),
	TO_ENUM(I960_sele, "Undocumented instruction I960_sele"),
	TO_ENUM(I960_addoge, "Undocumented instruction I960_addoge"),
	TO_ENUM(I960_addige, "Undocumented instruction I960_addige"),
	TO_ENUM(I960_suboge, "Undocumented instruction I960_suboge"),
	TO_ENUM(I960_subige, "Undocumented instruction I960_subige"),
	TO_ENUM(I960_selge, "Undocumented instruction I960_selge"),
	TO_ENUM(I960_addol, "Undocumented instruction I960_addol"),
	TO_ENUM(I960_addil, "Undocumented instruction I960_addil"),
	TO_ENUM(I960_subol, "Undocumented instruction I960_subol"),
	TO_ENUM(I960_subil, "Undocumented instruction I960_subil"),
	TO_ENUM(I960_sell, "Undocumented instruction I960_sell"),
	TO_ENUM(I960_addone, "Undocumented instruction I960_addone"),
	TO_ENUM(I960_addine, "Undocumented instruction I960_addine"),
	TO_ENUM(I960_subone, "Undocumented instruction I960_subone"),
	TO_ENUM(I960_subine, "Undocumented instruction I960_subine"),
	TO_ENUM(I960_selne, "Undocumented instruction I960_selne"),
	TO_ENUM(I960_addole, "Undocumented instruction I960_addole"),
	TO_ENUM(I960_addile, "Undocumented instruction I960_addile"),
	TO_ENUM(I960_subole, "Undocumented instruction I960_subole"),
	TO_ENUM(I960_subile, "Undocumented instruction I960_subile"),
	TO_ENUM(I960_selle, "Undocumented instruction I960_selle"),
	TO_ENUM(I960_addoo, "Undocumented instruction I960_addoo"),
	TO_ENUM(I960_addio, "Undocumented instruction I960_addio"),
	TO_ENUM(I960_suboo, "Undocumented instruction I960_suboo"),
	TO_ENUM(I960_subio, "Undocumented instruction I960_subio"),
	TO_ENUM(I960_selo, "Undocumented instruction I960_selo"),
	TO_ENUM(I960_faddr, "Undocumented instruction I960_faddr"),
	TO_ENUM(I960_faddrl, "Undocumented instruction I960_faddrl"),
	TO_ENUM(I960_fatanr, "Undocumented instruction I960_fatanr"),
	TO_ENUM(I960_fatanrl, "Undocumented instruction I960_fatanrl"),
	TO_ENUM(I960_fclassr, "Undocumented instruction I960_fclassr"),
	TO_ENUM(I960_fclassrl, "Undocumented instruction I960_fclassrl"),
	TO_ENUM(I960_fcmpor, "Undocumented instruction I960_fcmpor"),
	TO_ENUM(I960_fcmporl, "Undocumented instruction I960_fcmporl"),
	TO_ENUM(I960_fcmpr, "Undocumented instruction I960_fcmpr"),
	TO_ENUM(I960_fcmprl, "Undocumented instruction I960_fcmprl"),
	TO_ENUM(I960_fcosr, "Undocumented instruction I960_fcosr"),
	TO_ENUM(I960_fcosrl, "Undocumented instruction I960_fcosrl"),
	TO_ENUM(I960_fcpyrsre, "Undocumented instruction I960_fcpyrsre"),
	TO_ENUM(I960_fcpysre, "Undocumented instruction I960_fcpysre"),
	TO_ENUM(I960_fcvtilr, "Undocumented instruction I960_fcvtilr"),
	TO_ENUM(I960_fcvtir, "Undocumented instruction I960_fcvtir"),
	TO_ENUM(I960_fcvtri, "Undocumented instruction I960_fcvtri"),
	TO_ENUM(I960_fcvtril, "Undocumented instruction I960_fcvtril"),
	TO_ENUM(I960_fcvtzri, "Undocumented instruction I960_fcvtzri"),
	TO_ENUM(I960_fcvtzril, "Undocumented instruction I960_fcvtzril"),
	TO_ENUM(I960_fdivr, "Undocumented instruction I960_fdivr"),
	TO_ENUM(I960_fdivrl, "Undocumented instruction I960_fdivrl"),
	TO_ENUM(I960_fexpr, "Undocumented instruction I960_fexpr"),
	TO_ENUM(I960_fexprl, "Undocumented instruction I960_fexprl"),
	TO_ENUM(I960_flogbnr, "Undocumented instruction I960_flogbnr"),
	TO_ENUM(I960_flogbnrl, "Undocumented instruction I960_flogbnrl"),
	TO_ENUM(I960_flogepr, "Undocumented instruction I960_flogepr"),
	TO_ENUM(I960_flogeprl, "Undocumented instruction I960_flogeprl"),
	TO_ENUM(I960_flogr, "Undocumented instruction I960_flogr"),
	TO_ENUM(I960_flogrl, "Undocumented instruction I960_flogrl"),
	TO_ENUM(I960_fmovr, "Undocumented instruction I960_fmovr"),
	TO_ENUM(I960_fmovre, "Undocumented instruction I960_fmovre"),
	TO_ENUM(I960_fmovrl, "Undocumented instruction I960_fmovrl"),
	TO_ENUM(I960_fmulr, "Undocumented instruction I960_fmulr"),
	TO_ENUM(I960_fmulrl, "Undocumented instruction I960_fmulrl"),
	TO_ENUM(I960_fremr, "Undocumented instruction I960_fremr"),
	TO_ENUM(I960_fremrl, "Undocumented instruction I960_fremrl"),
	TO_ENUM(I960_froundr, "Undocumented instruction I960_froundr"),
	TO_ENUM(I960_froundrl, "Undocumented instruction I960_froundrl"),
	TO_ENUM(I960_fscaler, "Undocumented instruction I960_fscaler"),
	TO_ENUM(I960_fscalerl, "Undocumented instruction I960_fscalerl"),
	TO_ENUM(I960_fsinr, "Undocumented instruction I960_fsinr"),
	TO_ENUM(I960_fsinrl, "Undocumented instruction I960_fsinrl"),
	TO_ENUM(I960_fsqrtr, "Undocumented instruction I960_fsqrtr"),
	TO_ENUM(I960_fsqrtrl, "Undocumented instruction I960_fsqrtrl"),
	TO_ENUM(I960_fsubr, "Undocumented instruction I960_fsubr"),
	TO_ENUM(I960_fsubrl, "Undocumented instruction I960_fsubrl"),
	TO_ENUM(I960_ftanr, "Undocumented instruction I960_ftanr"),
	TO_ENUM(I960_ftanrl, "Undocumented instruction I960_ftanrl"),
	TO_ENUM(I960_last, "Undocumented instruction I960_last")
};
