auto instructions_PLFM_DSP96K = flags_vector_t{
	TO_ENUM(DSP96_null, "Undocumented instruction DSP96_null"),
	TO_ENUM(DSP96_abs, "Absolute Value"),
	TO_ENUM(DSP96_add, "Addition"),
	TO_ENUM(DSP96_addc, "Add with Carry"),
	TO_ENUM(DSP96_and, "Logical AND"),
	TO_ENUM(DSP96_andc, "AND Immediate with Complement"),
	TO_ENUM(DSP96_andi, "AND Immediate to Control Register"),
	TO_ENUM(DSP96_asl, "Arithmetic Shift Left"),
	TO_ENUM(DSP96_asr, "Arithmetic Shift Right"),
	TO_ENUM(DSP96_bcc, "Branch Conditionally (indirect)"),
	TO_ENUM(DSP96_bccd, "Branch Conditionally (direct)"),
	TO_ENUM(DSP96_bchg, "Bit Test and Change"),
	TO_ENUM(DSP96_bclr, "Bit Test and Clear"),
	TO_ENUM(DSP96_bfind, "Find Leading One"),
	TO_ENUM(DSP96_bra, "Branch Always"),
	TO_ENUM(DSP96_brclr, "Branch if Bit Clear"),
	TO_ENUM(DSP96_brset, "Branch if Bit Set"),
	TO_ENUM(DSP96_bscc, "Branch to Subroutine Conditionally (indirect)"),
	TO_ENUM(DSP96_bsccd, "Branch to Subroutine Conditionally (direct)"),
	TO_ENUM(DSP96_bsclr, "Branch to Subroutine if Bit Clear"),
	TO_ENUM(DSP96_bset, "Bit Test and Set"),
	TO_ENUM(DSP96_bsr, "Branch to Subroutine (indirect)"),
	TO_ENUM(DSP96_bsrd, "Branch to Subroutine (direct)"),
	TO_ENUM(DSP96_bsset, "Branch to Subroutine if Bit Set"),
	TO_ENUM(DSP96_btst, "Bit Test on Memory and Registers"),
	TO_ENUM(DSP96_clr, "Clear an Operand"),
	TO_ENUM(DSP96_cmp, "Compare"),
	TO_ENUM(DSP96_cmpg, "Graphics Compare with Trivial Accept.Reject Flags"),
	TO_ENUM(DSP96_debugcc, "Enter Debug Mode Conditionally"),
	TO_ENUM(DSP96_dec, "Decrement by One"),
	TO_ENUM(DSP96_do, "Start Hardware Loop"),
	TO_ENUM(DSP96_dor, "Start PC-Relative Hardware Loop"),
	TO_ENUM(DSP96_enddo, "Exit from Hardware Loop"),
	TO_ENUM(DSP96_eor, "Logical Exclusive OR"),
	TO_ENUM(DSP96_ext, "Sign Extend 16-Bit To 32-Bit"),
	TO_ENUM(DSP96_extb, "Sign Extend 8-Bit to 32-Bit"),
	TO_ENUM(DSP96_fabs, "Absolute Value"),
	TO_ENUM(DSP96_fadd, "Add"),
	TO_ENUM(DSP96_faddsub, "Add and Subtract"),
	TO_ENUM(DSP96_fbcc, "Branch Conditionally (Floating-Point Condition) (indirect)"),
	TO_ENUM(DSP96_fbccd, "Branch Conditionally (Floating-Point Condition) (direct)"),
	TO_ENUM(DSP96_fbscc, "Branch to Subroutine Conditionally (Floating-Point Condition) (indirect)"),
	TO_ENUM(DSP96_fbsccd, "Branch to Subroutine Conditionally (Floating-Point Condition) (direct)"),
	TO_ENUM(DSP96_fclr, "Clear a Floating-Point Operand"),
	TO_ENUM(DSP96_fcmp, "Compare"),
	TO_ENUM(DSP96_fcmpg, "Graphics Compare with Trivial Accept.Reject Flags"),
	TO_ENUM(DSP96_fcmpm, "Compare Magnitude"),
	TO_ENUM(DSP96_fcopys, "Copy Sign"),
	TO_ENUM(DSP96_fdebugcc, "Enter Debug Mode Conditionally"),
	TO_ENUM(DSP96_fgetman, "Get Mantissa"),
	TO_ENUM(DSP96_fint, "Convert to Floating-Point Integer"),
	TO_ENUM(DSP96_fjcc, "Jump Conditionally (indirect)"),
	TO_ENUM(DSP96_fjccd, "Jump Conditionally (direct)"),
	TO_ENUM(DSP96_fjscc, "Jump to Subroutine Conditionally (indirect)"),
	TO_ENUM(DSP96_fjsccd, "Jump to Subroutine Conditionally (direct)"),
	TO_ENUM(DSP96_float, "Integer to Floating-Point Conversion"),
	TO_ENUM(DSP96_floatu, "Unsigned Integer to SP Floating-Point Conversion"),
	TO_ENUM(DSP96_floor, "Convert to Floating-Point Integer round to -Infinity"),
	TO_ENUM(DSP96_fmove, "Move FP Data Register(s)"),
	TO_ENUM(DSP96_fmpyfadd, "Multiply and Add"),
	TO_ENUM(DSP96_fmpyfaddsub, "Multiply, Add and Subtract"),
	TO_ENUM(DSP96_fmpyfsub, "Multiply and Subtract"),
	TO_ENUM(DSP96_fmpy, "Multiply"),
	TO_ENUM(DSP96_fneg, "Change sign"),
	TO_ENUM(DSP96_fscale, "Scale a Floating-Point Operand"),
	TO_ENUM(DSP96_fseedd, "Reciprocal Approximation"),
	TO_ENUM(DSP96_fseedr, "Square-Root Reciprocal Approximation"),
	TO_ENUM(DSP96_fsub, "Subtract"),
	TO_ENUM(DSP96_ftfr, "Transfer Floating-Point Register"),
	TO_ENUM(DSP96_ftrapcc, "Conditional Software Interrupt"),
	TO_ENUM(DSP96_ftst, "Test a floating-Point Operand"),
	TO_ENUM(DSP96_getexp, "Get Exponent"),
	TO_ENUM(DSP96_illegal, "Illegal Instruction"),
	TO_ENUM(DSP96_inc, "Increment by One"),
	TO_ENUM(DSP96_int, "Floating-Point to Integer Conversion"),
	TO_ENUM(DSP96_intrz, "Floating-Point to Integer Conversion Round to Zero"),
	TO_ENUM(DSP96_intu, "Floating-Point to Unsigned Integer Conversion"),
	TO_ENUM(DSP96_inturz, "Floating-Point to Unsigned Integer Conversion Round to Zero"),
	TO_ENUM(DSP96_jcc, "Jump Conditionally (indirect)"),
	TO_ENUM(DSP96_jccd, "Jump Conditionally (direct)"),
	TO_ENUM(DSP96_jclr, "Jump if Bit Clear"),
	TO_ENUM(DSP96_join, "Join two 16-Bit Integers"),
	TO_ENUM(DSP96_joinb, "Join two 8-Bit Integers"),
	TO_ENUM(DSP96_jscc, "Jump to Subroutine Conditionally"),
	TO_ENUM(DSP96_jsccd, "Jump to Subroutine Conditionally"),
	TO_ENUM(DSP96_jsclr, "Jump to Subroutine if Bit Clear"),
	TO_ENUM(DSP96_jset, "Jump if Bit Set"),
	TO_ENUM(DSP96_jsset, "Jump to Subroutine if Bit Set"),
	TO_ENUM(DSP96_lea, "Load Effective Address"),
	TO_ENUM(DSP96_lra, "Load PC Relative Address"),
	TO_ENUM(DSP96_lsl, "Logical Shift Left"),
	TO_ENUM(DSP96_lsr, "Logical Shift Right"),
	TO_ENUM(DSP96_move, "Move Data Register(s)"),
	TO_ENUM(DSP96_movec, "Move Control Register"),
	TO_ENUM(DSP96_movei, "Move Immediate"),
	TO_ENUM(DSP96_movem, "Move Program Memory"),
	TO_ENUM(DSP96_movep, "Move Peripheral Data"),
	TO_ENUM(DSP96_moves, "Move Absolute Short"),
	TO_ENUM(DSP96_moveta, "Move Data Register(s) and Test Address"),
	TO_ENUM(DSP96_mpys, "Signed Multiply"),
	TO_ENUM(DSP96_mpyu, "Unsigned Multiply"),
	TO_ENUM(DSP96_neg, "Negate Accumulator"),
	TO_ENUM(DSP96_negc, "Negate with Carry"),
	TO_ENUM(DSP96_nop, "No Operation"),
	TO_ENUM(DSP96_not, "Logical Complement"),
	TO_ENUM(DSP96_or, "Logical Inclusive OR"),
	TO_ENUM(DSP96_orc, "OR With Compliment"),
	TO_ENUM(DSP96_ori, "OR Immediate to Control Register"),
	TO_ENUM(DSP96_rep, "Repeat Next Instruction"),
	TO_ENUM(DSP96_reset, "Reset On-Chip Peripheral Devices"),
	TO_ENUM(DSP96_rol, "Rotate Left"),
	TO_ENUM(DSP96_ror, "Rotate Right"),
	TO_ENUM(DSP96_rti, "Return from Interrupt"),
	TO_ENUM(DSP96_rtr, "Return from Subroutine and Restore Status Register"),
	TO_ENUM(DSP96_rts, "Return from Subroutine"),
	TO_ENUM(DSP96_setw, "Set an Operand"),
	TO_ENUM(DSP96_split, "Extract 16-Bit Integer"),
	TO_ENUM(DSP96_splitb, "Extract 8-Bit Integer"),
	TO_ENUM(DSP96_stop, "Stop Processing (Low Power Stand-by)"),
	TO_ENUM(DSP96_sub, "Subtract"),
	TO_ENUM(DSP96_subc, "Subtract with Carry"),
	TO_ENUM(DSP96_tfr, "Transfer Data ALU Register"),
	TO_ENUM(DSP96_trapcc, "Software Interrupt Conditionally"),
	TO_ENUM(DSP96_tst, "Test an Operand"),
	TO_ENUM(DSP96_wait, "Wait for Interrupt or DMA Request (Low Power Stand-by)"),
	TO_ENUM(DSP96_last, "Undocumented instruction DSP96_last")
};
