auto instructions_PLFM_MC6816 = flags_vector_t{
	TO_ENUM(MC6816_null, "Undocumented instruction MC6816_null"),
	TO_ENUM(MC6816_ldaa, "Load A"),
	TO_ENUM(MC6816_ldab, "Load B"),
	TO_ENUM(MC6816_ldd, "Load D"),
	TO_ENUM(MC6816_lde, "Load E"),
	TO_ENUM(MC6816_lded, "Load Concatenated D and E"),
	TO_ENUM(MC6816_movb, "Move Byte"),
	TO_ENUM(MC6816_movw, "Move Word"),
	TO_ENUM(MC6816_staa, "Store A"),
	TO_ENUM(MC6816_stab, "Store B"),
	TO_ENUM(MC6816_std, "Store D"),
	TO_ENUM(MC6816_ste, "Store E"),
	TO_ENUM(MC6816_sted, "Store Concatenated D and E"),
	TO_ENUM(MC6816_tab, "Transfer A to B"),
	TO_ENUM(MC6816_tba, "Transfer B to A"),
	TO_ENUM(MC6816_tde, "Transfer D to E"),
	TO_ENUM(MC6816_ted, "Transfer E to D"),
	TO_ENUM(MC6816_xgab, "Exchange A with B"),
	TO_ENUM(MC6816_xgde, "Exchange D with E"),
	TO_ENUM(MC6816_aba, "Add B to A"),
	TO_ENUM(MC6816_adca, "Add with Carry to A"),
	TO_ENUM(MC6816_adcb, "Add with Carry to B"),
	TO_ENUM(MC6816_adcd, "Add with Carry to D"),
	TO_ENUM(MC6816_adce, "Add with Carry to E"),
	TO_ENUM(MC6816_adda, "Add to A"),
	TO_ENUM(MC6816_addb, "Add to B"),
	TO_ENUM(MC6816_addd, "Add to D"),
	TO_ENUM(MC6816_adde, "Add to E"),
	TO_ENUM(MC6816_ade, "Add D to E"),
	TO_ENUM(MC6816_sba, "Subtract B from A"),
	TO_ENUM(MC6816_sbca, "Subtract with Carry from A"),
	TO_ENUM(MC6816_sbcb, "Subtract with Carry from B"),
	TO_ENUM(MC6816_sbcd, "Subtract with Carry from D"),
	TO_ENUM(MC6816_sbce, "Subtract with Carry from E"),
	TO_ENUM(MC6816_sde, "Subtract D from E"),
	TO_ENUM(MC6816_suba, "Subtract from A"),
	TO_ENUM(MC6816_subb, "Subtract from B"),
	TO_ENUM(MC6816_subd, "Subtract from D"),
	TO_ENUM(MC6816_sube, "Subtract from E"),
	TO_ENUM(MC6816_daa, "Decimal Adjust A"),
	TO_ENUM(MC6816_sxt, "Sign Extend B into A"),
	TO_ENUM(MC6816_cba, "Compare A to B"),
	TO_ENUM(MC6816_cmpa, "Compare A to Memory"),
	TO_ENUM(MC6816_cmpb, "Compare B to Memory"),
	TO_ENUM(MC6816_cpd, "Compare D to Memory"),
	TO_ENUM(MC6816_cpe, "Compare E to Memory"),
	TO_ENUM(MC6816_tst, "Test for Zero or Minus"),
	TO_ENUM(MC6816_tsta, "Test A for Zero or Minus"),
	TO_ENUM(MC6816_tstb, "Test B for Zero or Minus"),
	TO_ENUM(MC6816_tstd, "Test D for Zero or Minus"),
	TO_ENUM(MC6816_tste, "Test E for Zero or Minus"),
	TO_ENUM(MC6816_tstw, "Test for Zero or Minus Word"),
	TO_ENUM(MC6816_ediv, "Extended Unsigned Divide"),
	TO_ENUM(MC6816_edivs, "Extended Signed Divide"),
	TO_ENUM(MC6816_emul, "Extended Unsigned Multiply"),
	TO_ENUM(MC6816_emuls, "Extended Signed Multiply"),
	TO_ENUM(MC6816_fdiv, "Unsigned Fractional Divide"),
	TO_ENUM(MC6816_fmuls, "Signed Fractional Multiply"),
	TO_ENUM(MC6816_idiv, "Integer Divide"),
	TO_ENUM(MC6816_mul, "Multiply"),
	TO_ENUM(MC6816_dec, "Decrement Memory"),
	TO_ENUM(MC6816_deca, "Decrement A"),
	TO_ENUM(MC6816_decb, "Decrement B"),
	TO_ENUM(MC6816_decw, "Decrement Memory Word"),
	TO_ENUM(MC6816_inc, "Increment Memory"),
	TO_ENUM(MC6816_inca, "Increment A"),
	TO_ENUM(MC6816_incb, "Increment B"),
	TO_ENUM(MC6816_incw, "Increment Memory Word"),
	TO_ENUM(MC6816_clr, "Clear Memory"),
	TO_ENUM(MC6816_clra, "Clear A"),
	TO_ENUM(MC6816_clrb, "Clear B"),
	TO_ENUM(MC6816_clrd, "Clear D"),
	TO_ENUM(MC6816_clre, "Clear E"),
	TO_ENUM(MC6816_clrw, "Clear Memory Word"),
	TO_ENUM(MC6816_com, "One's Complement Byte"),
	TO_ENUM(MC6816_coma, "One's Complement A"),
	TO_ENUM(MC6816_comb, "One's Complement B"),
	TO_ENUM(MC6816_comd, "One's Complement D"),
	TO_ENUM(MC6816_come, "One's Complement E"),
	TO_ENUM(MC6816_comw, "One's Complement Word"),
	TO_ENUM(MC6816_neg, "Two's Complement Byte"),
	TO_ENUM(MC6816_nega, "Two's Complement A"),
	TO_ENUM(MC6816_negb, "Two's Complement B"),
	TO_ENUM(MC6816_negd, "Two's Complement D"),
	TO_ENUM(MC6816_nege, "Two's Complement E"),
	TO_ENUM(MC6816_negw, "Two's Complement Word"),
	TO_ENUM(MC6816_anda, "AND A"),
	TO_ENUM(MC6816_andb, "AND B"),
	TO_ENUM(MC6816_andd, "AND D"),
	TO_ENUM(MC6816_ande, "AND E"),
	TO_ENUM(MC6816_eora, "Exclusive OR A"),
	TO_ENUM(MC6816_eorb, "Exclusive OR B"),
	TO_ENUM(MC6816_eord, "Exclusive OR D"),
	TO_ENUM(MC6816_eore, "Exclusive OR E"),
	TO_ENUM(MC6816_oraa, "OR A"),
	TO_ENUM(MC6816_orab, "OR B"),
	TO_ENUM(MC6816_ord, "OR D"),
	TO_ENUM(MC6816_ore, "OR E"),
	TO_ENUM(MC6816_bita, "Bit Test A"),
	TO_ENUM(MC6816_bitb, "Bit Test B"),
	TO_ENUM(MC6816_bclr, "Clear Bit(s)"),
	TO_ENUM(MC6816_bclrw, "Clear Bit(s) Word"),
	TO_ENUM(MC6816_bset, "Set Bit(s)"),
	TO_ENUM(MC6816_bsetw, "Set Bit(s) Word"),
	TO_ENUM(MC6816_lsr, "Logic Shift Right"),
	TO_ENUM(MC6816_lsra, "Logic Shift Right A"),
	TO_ENUM(MC6816_lsrb, "Logic Shift Right B"),
	TO_ENUM(MC6816_lsrd, "Logic Shift Right D"),
	TO_ENUM(MC6816_lsre, "Logic Shift Right E"),
	TO_ENUM(MC6816_lsrw, "Logic Shift Right Word"),
	TO_ENUM(MC6816_asl, "Arithmetic Shift Left"),
	TO_ENUM(MC6816_asla, "Arithmetic Shift Left A"),
	TO_ENUM(MC6816_aslb, "Arithmetic Shift Left B"),
	TO_ENUM(MC6816_asld, "Arithmetic Shift Left D"),
	TO_ENUM(MC6816_asle, "Arithmetic Shift Left E"),
	TO_ENUM(MC6816_aslw, "Arithmetic Shift Left Word"),
	TO_ENUM(MC6816_asr, "Arithmetic Shift Right"),
	TO_ENUM(MC6816_asra, "Arithmetic Shift Right A"),
	TO_ENUM(MC6816_asrb, "Arithmetic Shift Right B"),
	TO_ENUM(MC6816_asrd, "Arithmetic Shift Right D"),
	TO_ENUM(MC6816_asre, "Arithmetic Shift Right E"),
	TO_ENUM(MC6816_asrw, "Arithmetic Shift Right Word"),
	TO_ENUM(MC6816_rol, "Rotate Left"),
	TO_ENUM(MC6816_rola, "Rotate Left A"),
	TO_ENUM(MC6816_rolb, "Rotate Left B"),
	TO_ENUM(MC6816_rold, "Rotate Left D"),
	TO_ENUM(MC6816_role, "Rotate Left E"),
	TO_ENUM(MC6816_rolw, "Rotate Left Word"),
	TO_ENUM(MC6816_ror, "Rotate Right"),
	TO_ENUM(MC6816_rora, "Rotate Right A"),
	TO_ENUM(MC6816_rorb, "Rotate Right B"),
	TO_ENUM(MC6816_rord, "Rotate Right D"),
	TO_ENUM(MC6816_rore, "Rotate Right E"),
	TO_ENUM(MC6816_rorw, "Rotate Right Word"),
	TO_ENUM(MC6816_bra, "Branch Always"),
	TO_ENUM(MC6816_brn, "Branch Never"),
	TO_ENUM(MC6816_bcc, "Branch If Carry Clear"),
	TO_ENUM(MC6816_bcs, "Branch If Carry Set"),
	TO_ENUM(MC6816_beq, "Branch If Equal to Zero"),
	TO_ENUM(MC6816_bmi, "Branch If Minus"),
	TO_ENUM(MC6816_bne, "Branch If Not Equal to Zero"),
	TO_ENUM(MC6816_bpl, "Branch If Plus"),
	TO_ENUM(MC6816_bvc, "Branch If Overflow Clear"),
	TO_ENUM(MC6816_bvs, "Branch If Overflow Set"),
	TO_ENUM(MC6816_bhi, "Branch If Higher"),
	TO_ENUM(MC6816_bls, "Branch If Lower or Same"),
	TO_ENUM(MC6816_bge, "Branch If Greater than or Equal to Zero"),
	TO_ENUM(MC6816_bgt, "Branch If Greater than Zero"),
	TO_ENUM(MC6816_ble, "Branch If Less than or Equal to Zero"),
	TO_ENUM(MC6816_blt, "Branch If Less than Zero"),
	TO_ENUM(MC6816_lbra, "Long Branch Always"),
	TO_ENUM(MC6816_lbrn, "Long Branch Never"),
	TO_ENUM(MC6816_lbcc, "Long Branch If Carry Clear"),
	TO_ENUM(MC6816_lbcs, "Long Branch If Carry Set"),
	TO_ENUM(MC6816_lbeq, "Long Branch If Equal to Zero"),
	TO_ENUM(MC6816_lbev, "Long Branch If EV Set"),
	TO_ENUM(MC6816_lbmi, "Long Branch If Minus"),
	TO_ENUM(MC6816_lbmv, "Long Branch If MV Set"),
	TO_ENUM(MC6816_lbne, "Long Branch If Not Equal to Zero"),
	TO_ENUM(MC6816_lbpl, "Long Branch If Plus"),
	TO_ENUM(MC6816_lbvc, "Long Branch If Overflow Clear"),
	TO_ENUM(MC6816_lbvs, "Long Branch If Overflow Set"),
	TO_ENUM(MC6816_lbhi, "Long Branch If Higher"),
	TO_ENUM(MC6816_lbls, "Long Branch If Lower or Same"),
	TO_ENUM(MC6816_lbge, "Long Branch If Greater than or Equal to Zero"),
	TO_ENUM(MC6816_lbgt, "Long Branch If Greater than Zero"),
	TO_ENUM(MC6816_lble, "Long Branch If Less than or Equal to Zero"),
	TO_ENUM(MC6816_lblt, "Long Branch If Less than Zero"),
	TO_ENUM(MC6816_brclr, "Branch if Bits Clear"),
	TO_ENUM(MC6816_brset, "Branch if Bits Set"),
	TO_ENUM(MC6816_jmp, "Jump"),
	TO_ENUM(MC6816_bsr, "Branch to Subroutine"),
	TO_ENUM(MC6816_jsr, "Jump to Subroutine"),
	TO_ENUM(MC6816_lbsr, "Long Branch to Subroutine"),
	TO_ENUM(MC6816_rts, "Return From Subroutine"),
	TO_ENUM(MC6816_rti, "Return from Interrupt"),
	TO_ENUM(MC6816_swi, "Software Interrupt"),
	TO_ENUM(MC6816_abx, "Add B to IX"),
	TO_ENUM(MC6816_aby, "Add B to IY"),
	TO_ENUM(MC6816_abz, "Add B to IZ"),
	TO_ENUM(MC6816_adx, "Add D to IX"),
	TO_ENUM(MC6816_ady, "Add D to IY"),
	TO_ENUM(MC6816_adz, "Add D to IZ"),
	TO_ENUM(MC6816_aex, "Add E to IX"),
	TO_ENUM(MC6816_aey, "Add E to IY"),
	TO_ENUM(MC6816_aez, "Add E to IZ"),
	TO_ENUM(MC6816_aix, "Add Immediate Value to IX"),
	TO_ENUM(MC6816_aiy, "Add Immediate Value to IY"),
	TO_ENUM(MC6816_aiz, "Add Immediate Value to IZ"),
	TO_ENUM(MC6816_cpx, "Compare IX to Memory"),
	TO_ENUM(MC6816_cpy, "Compare IY to Memory"),
	TO_ENUM(MC6816_cpz, "Compare IZ to Memory"),
	TO_ENUM(MC6816_ldx, "Load IX"),
	TO_ENUM(MC6816_ldy, "Load IY"),
	TO_ENUM(MC6816_ldz, "Load IZ"),
	TO_ENUM(MC6816_stx, "Store IX"),
	TO_ENUM(MC6816_sty, "Store IY"),
	TO_ENUM(MC6816_stz, "Store IZ"),
	TO_ENUM(MC6816_tsx, "Transfer SP to IX"),
	TO_ENUM(MC6816_tsy, "Transfer SP to IY"),
	TO_ENUM(MC6816_tsz, "Transfer SP to IZ"),
	TO_ENUM(MC6816_txs, "Transfer IX to SP"),
	TO_ENUM(MC6816_txy, "Transfer IX to IY"),
	TO_ENUM(MC6816_txz, "Transfer IX to IZ"),
	TO_ENUM(MC6816_tys, "Transfer IY to SP"),
	TO_ENUM(MC6816_tyx, "Transfer IY to IX"),
	TO_ENUM(MC6816_tyz, "Transfer IY to IZ"),
	TO_ENUM(MC6816_tzs, "Transfer IZ to SP"),
	TO_ENUM(MC6816_tzx, "Transfer IZ to IX"),
	TO_ENUM(MC6816_tzy, "Transfer IZ to IY"),
	TO_ENUM(MC6816_xgdx, "Exchange D with IX"),
	TO_ENUM(MC6816_xgdy, "Exchange D with IY"),
	TO_ENUM(MC6816_xgdz, "Exchange D with IZ"),
	TO_ENUM(MC6816_xgex, "Exchange E with IX"),
	TO_ENUM(MC6816_xgey, "Exchange E with IY"),
	TO_ENUM(MC6816_xgez, "Exchange E with IZ"),
	TO_ENUM(MC6816_tbek, "Transfer B to EK"),
	TO_ENUM(MC6816_tbsk, "Transfer B to SK"),
	TO_ENUM(MC6816_tbxk, "Transfer B to XK"),
	TO_ENUM(MC6816_tbyk, "Transfer B to YK"),
	TO_ENUM(MC6816_tbzk, "Transfer B to ZK"),
	TO_ENUM(MC6816_tekb, "Transfer EK to B"),
	TO_ENUM(MC6816_tskb, "Transfer SK to B"),
	TO_ENUM(MC6816_txkb, "Transfer XK to B"),
	TO_ENUM(MC6816_tykb, "Transfer YK to B"),
	TO_ENUM(MC6816_tzkb, "Transfer ZK to B"),
	TO_ENUM(MC6816_ais, "Add Immediate Data to SP"),
	TO_ENUM(MC6816_cps, "Compare SP to Memory"),
	TO_ENUM(MC6816_lds, "Load SP"),
	TO_ENUM(MC6816_sts, "Store SP"),
	TO_ENUM(MC6816_psha, "Push A"),
	TO_ENUM(MC6816_pshb, "Push B"),
	TO_ENUM(MC6816_pshm, "Push Multiple Registers"),
	TO_ENUM(MC6816_pula, "Pull A"),
	TO_ENUM(MC6816_pulb, "Pull B"),
	TO_ENUM(MC6816_pulm, "Pull Multiple Registers"),
	TO_ENUM(MC6816_andp, "AND CCR"),
	TO_ENUM(MC6816_orp, "OR CCR"),
	TO_ENUM(MC6816_tap, "Transfer A to CCR"),
	TO_ENUM(MC6816_tdp, "Transfer D to CCR"),
	TO_ENUM(MC6816_tpa, "Transfer CCR MSB to A"),
	TO_ENUM(MC6816_tpd, "Transfer CCR to D"),
	TO_ENUM(MC6816_ace, "Add E to AM[31:15]"),
	TO_ENUM(MC6816_aced, "Add concatenated E and D to AM"),
	TO_ENUM(MC6816_aslm, "Arithmetic Shift Left AM"),
	TO_ENUM(MC6816_asrm, "Arithmetic Shift Right AM"),
	TO_ENUM(MC6816_clrm, "Clear AM"),
	TO_ENUM(MC6816_ldhi, "Initialize HR and IR"),
	TO_ENUM(MC6816_mac, "Multiply and Accumulate"),
	TO_ENUM(MC6816_pshmac, "Push MAC State"),
	TO_ENUM(MC6816_pulmac, "Pull MAC State"),
	TO_ENUM(MC6816_rmac, "Repeating Multiply and Accumulate"),
	TO_ENUM(MC6816_tdmsk, "Transfer D to XMSK:YMSK"),
	TO_ENUM(MC6816_tedm, "Transfer E and T to AM[31:0]"),
	TO_ENUM(MC6816_tem, "Transfer E to AM[31:16]"),
	TO_ENUM(MC6816_tmer, "Transfer AM to E Rounded"),
	TO_ENUM(MC6816_tmet, "Transfer AM to E Truncated"),
	TO_ENUM(MC6816_tmxed, "Transfer AM t IX:E:D"),
	TO_ENUM(MC6816_lpstop, "Low Power Stop"),
	TO_ENUM(MC6816_wai, "Wait for Interrupt"),
	TO_ENUM(MC6816_bgnd, "Enter Background Debugging Mode"),
	TO_ENUM(MC6816_nop, "Null operation"),
	TO_ENUM(MC6816_last, "Undocumented instruction MC6816_last")
};
