auto instructions_PLFM_80196 = flags_vector_t{
	TO_ENUM(I196_null, "Undocumented instruction I196_null"),
	TO_ENUM(I196_add2, "Add words (2 operands)"),
	TO_ENUM(I196_add3, "Add words (3 operands)"),
	TO_ENUM(I196_addb2, "Add bytes (2 operands)"),
	TO_ENUM(I196_addb3, "Add bytes (3 operands)"),
	TO_ENUM(I196_addc, "Add words with carry"),
	TO_ENUM(I196_addcb, "Add bytes with carry"),
	TO_ENUM(I196_and2, "Logical AND words (2 operands)"),
	TO_ENUM(I196_and3, "Logical AND words (3 operands)"),
	TO_ENUM(I196_andb2, "Logical AND bytes (2 operands)"),
	TO_ENUM(I196_andb3, "Logical AND bytes (3 operands)"),
	TO_ENUM(I196_bmov, "Block move"),
	TO_ENUM(I196_bmovi, "Interruptable block move"),
	TO_ENUM(I196_br, "Branch indirect"),
	TO_ENUM(I196_clr, "Clear word"),
	TO_ENUM(I196_clrb, "Clear byte"),
	TO_ENUM(I196_clrc, "Clear carry flag"),
	TO_ENUM(I196_clrvt, "Clear overflow-trap flag"),
	TO_ENUM(I196_cmp, "Compare words"),
	TO_ENUM(I196_cmpb, "Compare bytes"),
	TO_ENUM(I196_cmpl, "Compare long"),
	TO_ENUM(I196_dec, "Decrement word"),
	TO_ENUM(I196_decb, "Decrement byte"),
	TO_ENUM(I196_di, "Disable interrupts"),
	TO_ENUM(I196_div, "Divide integers"),
	TO_ENUM(I196_divb, "Divide short-integers"),
	TO_ENUM(I196_divu, "Divide words, unsigned"),
	TO_ENUM(I196_divub, "Divide bytes, unsigned"),
	TO_ENUM(I196_djnz, "Decrement and jump if not zero"),
	TO_ENUM(I196_djnzw, "Decrement and jump if not zero word"),
	TO_ENUM(I196_dpts, "Disable peripheral transaction server"),
	TO_ENUM(I196_ei, "Enable interrupts"),
	TO_ENUM(I196_epts, "Enable peripheral transaction server"),
	TO_ENUM(I196_ext, "Sign-extend integer into long-integer"),
	TO_ENUM(I196_extb, "Sign-extend short-integer into integer"),
	TO_ENUM(I196_idlpd, "Idle/powerdown"),
	TO_ENUM(I196_inc, "Increment word"),
	TO_ENUM(I196_incb, "Increment byte"),
	TO_ENUM(I196_jbc, "Jump if bit is clear"),
	TO_ENUM(I196_jbs, "Jump if bit is set"),
	TO_ENUM(I196_jc, "Jump if carry flag is set"),
	TO_ENUM(I196_je, "Jump if equal"),
	TO_ENUM(I196_jge, "Jump if signed greater than or equal"),
	TO_ENUM(I196_jgt, "Jump if signed greater than"),
	TO_ENUM(I196_jh, "Jump if higher (unsigned)"),
	TO_ENUM(I196_jle, "Jump if signed less than or equal"),
	TO_ENUM(I196_jlt, "Jump if signed less than"),
	TO_ENUM(I196_jnc, "Jump if carry flag is clear"),
	TO_ENUM(I196_jne, "Jump if not equal"),
	TO_ENUM(I196_jnh, "Jump if not higher (unsigned)"),
	TO_ENUM(I196_jnst, "Jump if sticky bit flag is clear"),
	TO_ENUM(I196_jnv, "Jump if overflow flag is clear"),
	TO_ENUM(I196_jnvt, "Jump if overflow-trap flag is clear"),
	TO_ENUM(I196_jst, "Jump if sticky bit flag is set"),
	TO_ENUM(I196_jv, "Jump if overflow flag is set"),
	TO_ENUM(I196_jvt, "Jump if overflow-trap flag is set"),
	TO_ENUM(I196_lcall, "Long call"),
	TO_ENUM(I196_ld, "Load word"),
	TO_ENUM(I196_ldb, "Load byte"),
	TO_ENUM(I196_ldbse, "Load byte sign-extended"),
	TO_ENUM(I196_ldbze, "Load byte zero-extended"),
	TO_ENUM(I196_ljmp, "Long jump"),
	TO_ENUM(I196_mul2, "Multiply integers (2 operands)"),
	TO_ENUM(I196_mul3, "Multiply integers (3 operands)"),
	TO_ENUM(I196_mulb2, "Multiply short-integers (2 operands)"),
	TO_ENUM(I196_mulb3, "Multiply short-integers (3 operands)"),
	TO_ENUM(I196_mulu2, "Multiply words, unsigned (2 operands)"),
	TO_ENUM(I196_mulu3, "Multiply words, unsigned (3 operands)"),
	TO_ENUM(I196_mulub2, "Multiply bytes, unsigned (2 operands)"),
	TO_ENUM(I196_mulub3, "Multiply bytes, unsigned (3 operands)"),
	TO_ENUM(I196_neg, "Negate integer"),
	TO_ENUM(I196_negb, "Negate short-integer"),
	TO_ENUM(I196_nop, "No operation"),
	TO_ENUM(I196_norml, "Normalize long-integer"),
	TO_ENUM(I196_not, "Complement word"),
	TO_ENUM(I196_notb, "Complement byte"),
	TO_ENUM(I196_or, "Logical OR words"),
	TO_ENUM(I196_orb, "Logical OR bytes"),
	TO_ENUM(I196_pop, "Pop word"),
	TO_ENUM(I196_popa, "Pop all"),
	TO_ENUM(I196_popf, "Pop flags"),
	TO_ENUM(I196_push, "Push word"),
	TO_ENUM(I196_pusha, "Push all"),
	TO_ENUM(I196_pushf, "Push flags"),
	TO_ENUM(I196_ret, "Return from subroutine"),
	TO_ENUM(I196_rst, "Reset system"),
	TO_ENUM(I196_scall, "Short call"),
	TO_ENUM(I196_setc, "Set carry flag"),
	TO_ENUM(I196_shl, "Shift word left"),
	TO_ENUM(I196_shlb, "Shift byte left"),
	TO_ENUM(I196_shll, "Shift double-word left"),
	TO_ENUM(I196_shr, "Logical right shift word"),
	TO_ENUM(I196_shra, "Arithmetic right shift word"),
	TO_ENUM(I196_shrab, "Arithmetic right shift byte"),
	TO_ENUM(I196_shral, "Arithmetic right shift double-word"),
	TO_ENUM(I196_shrb, "Logical right shift byte"),
	TO_ENUM(I196_shrl, "Logical right shift double-word"),
	TO_ENUM(I196_sjmp, "Short jump"),
	TO_ENUM(I196_skip, "Two byte no-operation"),
	TO_ENUM(I196_st, "Store word"),
	TO_ENUM(I196_stb, "Store byte"),
	TO_ENUM(I196_sub2, "Subtract words (2 operands)"),
	TO_ENUM(I196_sub3, "Subtract words (3 operands)"),
	TO_ENUM(I196_subb2, "Subtract bytes (2 operands)"),
	TO_ENUM(I196_subb3, "subtract bytes (3 operands)"),
	TO_ENUM(I196_subc, "Subtract words with borrow"),
	TO_ENUM(I196_subcb, "Subtract bytes with borrow"),
	TO_ENUM(I196_tijmp, "Table indirect jump"),
	TO_ENUM(I196_trap, "Software trap"),
	TO_ENUM(I196_xch, "Exchange word"),
	TO_ENUM(I196_xchb, "Exchange byte"),
	TO_ENUM(I196_xor, "Logical exclusive-or words"),
	TO_ENUM(I196_xorb, "Logical exclusive-or bytes"),
	TO_ENUM(I196_ebmovi, "Extended interruptable block move"),
	TO_ENUM(I196_ebr, "Extended branch indirect"),
	TO_ENUM(I196_ecall, "Extended call"),
	TO_ENUM(I196_ejmp, "Extended jump"),
	TO_ENUM(I196_eld, "Extended load word"),
	TO_ENUM(I196_eldb, "Extended load byte"),
	TO_ENUM(I196_est, "Extended store word"),
	TO_ENUM(I196_estb, "Extended store byte"),
	TO_ENUM(I196_last, "Undocumented instruction I196_last")
};
