auto instructions_PLFM_SH = flags_vector_t{
	TO_ENUM(SH4_fabs, "Floating-point absolute value"),
	TO_ENUM(SH4_fadd, "Floating-point add"),
	TO_ENUM(SH4_fcmp_eq, "Floating-point compare eqaul"),
	TO_ENUM(SH4_fcmp_gt, "Floating-point compare greater than"),
	TO_ENUM(SH4_fcnvds, "Floating-point convert double to single precision"),
	TO_ENUM(SH4_fcnvsd, "Floating-point convert single to double precision"),
	TO_ENUM(SH4_fdiv, "Floating-point divide"),
	TO_ENUM(SH4_fipr, "Floating-point inner product"),
	TO_ENUM(SH4_fldi0, "Floating-point Load Immediate 0.0"),
	TO_ENUM(SH4_fldi1, "Floating-point Load Immediate 1.0"),
	TO_ENUM(SH4_flds, "Floating-point Load to system register"),
	TO_ENUM(SH4_float, "Floating-point convert from integer"),
	TO_ENUM(SH4_fmac, "Floating-point multiply and accumulate"),
	TO_ENUM(SH4_fmov, "Floating-point move"),
	TO_ENUM(SH4_fmov_s, "Floating-point move single precision"),
	TO_ENUM(SH4_fmovex, "Floating-point move extension"),
	TO_ENUM(SH4_fmul, "Floating-point multiply"),
	TO_ENUM(SH4_fneg, "Floating-Point sign inversion"),
	TO_ENUM(SH4_frchg, "FR-bit change"),
	TO_ENUM(SH4_fschg, "SZ-bit change"),
	TO_ENUM(SH4_fsqrt, "Floating-point square root"),
	TO_ENUM(SH4_fsts, "Floating-point store system register"),
	TO_ENUM(SH4_fsub, "Floating-point subtract"),
	TO_ENUM(SH4_ftrc, "Floating-point truncate and convert to integer"),
	TO_ENUM(SH4_ftrv, "Floating-point transform vector"),
	TO_ENUM(SH4_ftstn, "Floating point square root reciprocal approximate"),
	TO_ENUM(SH4_movca_l, "Move with cache block allocation"),
	TO_ENUM(SH4_ocbi, "Operand Cache Block Invalidate"),
	TO_ENUM(SH4_ocbp, "Operand Cache Block Purge"),
	TO_ENUM(SH4_ocbwb, "Operand Cache Block Write Back"),
	TO_ENUM(SH4_fsca, "Floating point sine and cosine approximate"),
	TO_ENUM(SH4_last, "Undocumented instruction SH4_last")
};
