auto instructions_PLFM_XTENSA = flags_vector_t{
	TO_ENUM(XTENSA_null, "Undocumented instruction XTENSA_null"),
	TO_ENUM(XTENSA_abs, "Absolute value"),
	TO_ENUM(XTENSA_add, "Add two registers"),
	TO_ENUM(XTENSA_addi, "Add signed constant to register"),
	TO_ENUM(XTENSA_addmi, "Add a register and a shifted 8-bit immediate"),
	TO_ENUM(XTENSA_addx2, "Add register to register shifted by 1"),
	TO_ENUM(XTENSA_addx4, "Add register to register shifted by 2"),
	TO_ENUM(XTENSA_addx8, "Add register to register shifted by 3"),
	TO_ENUM(XTENSA_and, "Bitwise logical AND"),
	TO_ENUM(XTENSA_ball, "Branch if all of masked bits set"),
	TO_ENUM(XTENSA_bany, "Branch if any of masked bits set"),
	TO_ENUM(XTENSA_bbc, "Branch if bit clear"),
	TO_ENUM(XTENSA_bbs, "Branch if bit set"),
	TO_ENUM(XTENSA_bbci, "Branch if bit clear immediate"),
	TO_ENUM(XTENSA_bbsi, "Branch if bit set immediate"),
	TO_ENUM(XTENSA_beq, "Branch if equal"),
	TO_ENUM(XTENSA_beqi, "Branch if equal immediate"),
	TO_ENUM(XTENSA_beqz, "Branch if equal to zero"),
	TO_ENUM(XTENSA_bge, "Branch if greater than or equal"),
	TO_ENUM(XTENSA_bgei, "Branch if one register is greater than or equal to an encoded constant"),
	TO_ENUM(XTENSA_bgeu, "Branch if greater than or equal unsigned"),
	TO_ENUM(XTENSA_bgeui, "Branch if greater than or equal unsigned immediate"),
	TO_ENUM(XTENSA_bgez, "Branch if greater than or equal to zero"),
	TO_ENUM(XTENSA_blt, "Branch if less than"),
	TO_ENUM(XTENSA_blti, "Branch if less than immediate"),
	TO_ENUM(XTENSA_bltu, "Branch if less than Unsigned"),
	TO_ENUM(XTENSA_bltui, "Branch if less than unsigned immediate"),
	TO_ENUM(XTENSA_bltz, "Branch if less than zero"),
	TO_ENUM(XTENSA_bnall, "Branch if not all of masked bits set"),
	TO_ENUM(XTENSA_bnone, "Branch if none of masked bits set (All Clear)"),
	TO_ENUM(XTENSA_bne, "Branch if not equal"),
	TO_ENUM(XTENSA_bnei, "Branch if not equal immediate"),
	TO_ENUM(XTENSA_bnez, "Branch if not equal to zero"),
	TO_ENUM(XTENSA_break, "Breakpoint"),
	TO_ENUM(XTENSA_call0, "Call subroutine, PC-relative"),
	TO_ENUM(XTENSA_call4, "Call subroutine, PC-relative, rotate window by 4"),
	TO_ENUM(XTENSA_call8, "Call subroutine, PC-relative, rotate window by 8"),
	TO_ENUM(XTENSA_call12, "Call subroutine, PC-relative, rotate window by 12"),
	TO_ENUM(XTENSA_callx0, "Call subroutine register specified location"),
	TO_ENUM(XTENSA_callx4, "Call Register, Rotate Window by 4"),
	TO_ENUM(XTENSA_callx8, "Call Register, Rotate Window by 8"),
	TO_ENUM(XTENSA_callx12, "Call Register, Rotate Window by 12"),
	TO_ENUM(XTENSA_dsync, "Load/store synchronize"),
	TO_ENUM(XTENSA_entry, "Subroutine entry"),
	TO_ENUM(XTENSA_esync, "Register value synchronize"),
	TO_ENUM(XTENSA_excw, "Exception Wait"),
	TO_ENUM(XTENSA_extui, "Extract field specified by immediates from a register"),
	TO_ENUM(XTENSA_extw, "Wait for any possible external ordering requirement"),
	TO_ENUM(XTENSA_isync, "Instruction fetch synchronize"),
	TO_ENUM(XTENSA_j, "Jump to PC plus offset"),
	TO_ENUM(XTENSA_jx, "Jump to register specified location"),
	TO_ENUM(XTENSA_loop, "Loop"),
	TO_ENUM(XTENSA_loopgtz, "Loop if Greater Than Zero"),
	TO_ENUM(XTENSA_loopnez, "Loop if Not-Equal Zero"),
	TO_ENUM(XTENSA_lsi, "Load single-precision immediate"),
	TO_ENUM(XTENSA_lsx, "Load single-precision indexed"),
	TO_ENUM(XTENSA_l8ui, "Load zero extended byte"),
	TO_ENUM(XTENSA_l16si, "16-bit signed load (8-bit shifted offset)"),
	TO_ENUM(XTENSA_l16ui, "16-bit unsigned load (8-bit shifted offset)"),
	TO_ENUM(XTENSA_l32i, "32-bit load (8-bit shifted offset)"),
	TO_ENUM(XTENSA_l32r, "32-bit load PC-relative (16-bit negative word offset)"),
	TO_ENUM(XTENSA_max, "Maximum Value Signed"),
	TO_ENUM(XTENSA_maxu, "Maximum Value Unsigned"),
	TO_ENUM(XTENSA_memw, "Wait for any possible memory ordering requirement"),
	TO_ENUM(XTENSA_min, "Minimum Value Signed"),
	TO_ENUM(XTENSA_minu, "Minimum Value Unsigned"),
	TO_ENUM(XTENSA_mov, "Move a 32-bit register to a register"),
	TO_ENUM(XTENSA_moveqz, "Conditional move if zero"),
	TO_ENUM(XTENSA_movgez, "Conditional move if greater than or equal to zero"),
	TO_ENUM(XTENSA_movi, "Move a 12-bit immediate to a register"),
	TO_ENUM(XTENSA_movltz, "Conditional move if less than zero"),
	TO_ENUM(XTENSA_movnez, "Conditional move if non-zero"),
	TO_ENUM(XTENSA_mul16s, "Signed 16-bit multiplication"),
	TO_ENUM(XTENSA_mul16u, "Unsigned 16-bit multiplication"),
	TO_ENUM(XTENSA_mull, "Multiply low"),
	TO_ENUM(XTENSA_neg, "Negate"),
	TO_ENUM(XTENSA_nsa, "Normalization shift amount signed"),
	TO_ENUM(XTENSA_nsau, "Normalization shift amount unsigned"),
	TO_ENUM(XTENSA_nop, "No operation"),
	TO_ENUM(XTENSA_or, "Bitwise logical OR"),
	TO_ENUM(XTENSA_ret, "Return"),
	TO_ENUM(XTENSA_retw, "Windowed Return"),
	TO_ENUM(XTENSA_rfe, "Returns from the KernelExceptionVector exception"),
	TO_ENUM(XTENSA_rfi, "Return from high-priority interrupt"),
	TO_ENUM(XTENSA_rsil, "Read and set interrupt level"),
	TO_ENUM(XTENSA_rsr, "Read Special Register"),
	TO_ENUM(XTENSA_rsync, "Wait for dispatch related changes to resolve"),
	TO_ENUM(XTENSA_s8i, "8-bit store (8-bit offset)"),
	TO_ENUM(XTENSA_s16i, "16-bit store (8-bit shifted offset)"),
	TO_ENUM(XTENSA_s32i, "Store 32-bit quantity"),
	TO_ENUM(XTENSA_s32ri, "Store 32-bit release"),
	TO_ENUM(XTENSA_sext, "Sign Extend"),
	TO_ENUM(XTENSA_sll, "Shift left logical"),
	TO_ENUM(XTENSA_slli, "Shift left logical by SAR/immediate"),
	TO_ENUM(XTENSA_sra, "Shift right arithmetic"),
	TO_ENUM(XTENSA_srai, "Shift right arithmetic immediate by 0..31 bit positions"),
	TO_ENUM(XTENSA_src, "Shift right combined"),
	TO_ENUM(XTENSA_srl, "Shift right logical"),
	TO_ENUM(XTENSA_srli, "Shift right logical immediate by 0..15 bit positions"),
	TO_ENUM(XTENSA_ssa8b, "Set shift amount register (SAR) for big-endian byte align"),
	TO_ENUM(XTENSA_ssa8l, "Set shift amount register (SAR) for little-endian byte align"),
	TO_ENUM(XTENSA_ssai, "Set shift amount register (SAR) immediate"),
	TO_ENUM(XTENSA_ssl, "Set shift amount register (SAR) for shift left logica"),
	TO_ENUM(XTENSA_ssr, "Set shift amount register (SAR) for shift right logical"),
	TO_ENUM(XTENSA_sub, "Subtract two registers"),
	TO_ENUM(XTENSA_subx2, "Subtract register from register shifted by 1"),
	TO_ENUM(XTENSA_subx4, "Subtract register from register shifted by 2"),
	TO_ENUM(XTENSA_subx8, "Subtract register from register shifted by 3"),
	TO_ENUM(XTENSA_waiti, "Wait for interrupt"),
	TO_ENUM(XTENSA_wdtlb, "Write data TLB"),
	TO_ENUM(XTENSA_witlb, "Write instruction TLB"),
	TO_ENUM(XTENSA_wsr, "Write Special Register"),
	TO_ENUM(XTENSA_xor, "Bitwise logical exclusive OR"),
	TO_ENUM(XTENSA_xsr, "Exchange Special Register"),
	TO_ENUM(XTENSA_ill, "Illegal instruction executed"),
	TO_ENUM(XTENSA_andi, "Bitwise logical AND with immediate"),
	TO_ENUM(XTENSA_ori, "Bitwise logical OR with immediate"),
	TO_ENUM(XTENSA_rur, "Read User Register"),
	TO_ENUM(XTENSA_wur, "Write User Register"),
	TO_ENUM(XTENSA_fsync, "Fetch Synchronize"),
	TO_ENUM(XTENSA_rer, "Read External Register"),
	TO_ENUM(XTENSA_s32nb, "Store 32-bit Non-Buffered"),
	TO_ENUM(XTENSA_salt, "Set AR if Less Than"),
	TO_ENUM(XTENSA_saltu, "Set AR if Less Than Unsigned"),
	TO_ENUM(XTENSA_wer, "Write External Register"),
	TO_ENUM(XTENSA_dhi_b, "Block Data Cache Hit Invalidate"),
	TO_ENUM(XTENSA_dhwb_b, "Block Data Cache Hit Writeback"),
	TO_ENUM(XTENSA_dhwbi_b, "Block Data Cache Hit Writeback Inv"),
	TO_ENUM(XTENSA_dpfm_b, "Block Data Cache Prefetch and Modify"),
	TO_ENUM(XTENSA_dpfm_bf, "Block Data Cache Prefetch/Modify First"),
	TO_ENUM(XTENSA_dpfr_b, "Block Data Cache Prefetch for Read"),
	TO_ENUM(XTENSA_dpfr_bf, "Block Data Cache Prefetch for Read First"),
	TO_ENUM(XTENSA_dpfw_b, "Block Data Cache Prefetch for Write"),
	TO_ENUM(XTENSA_dpfw_bf, "Block Data Cache Prefetch for Write First"),
	TO_ENUM(XTENSA_all4, "All 4 Booleans True"),
	TO_ENUM(XTENSA_all8, "All 8 Booleans True"),
	TO_ENUM(XTENSA_andb, "Boolean And"),
	TO_ENUM(XTENSA_andbc, "Boolean And with Complement"),
	TO_ENUM(XTENSA_any4, "Any 4 Booleans True"),
	TO_ENUM(XTENSA_any8, "Any 8 Booleans True"),
	TO_ENUM(XTENSA_bf, "Branch if False"),
	TO_ENUM(XTENSA_bt, "Branch if True"),
	TO_ENUM(XTENSA_movf, "Move if False"),
	TO_ENUM(XTENSA_movt, "Move if True"),
	TO_ENUM(XTENSA_orb, "Boolean Or"),
	TO_ENUM(XTENSA_orbc, "Boolean Or with Complement"),
	TO_ENUM(XTENSA_xorb, "Boolean Exclusive Or"),
	TO_ENUM(XTENSA_s32c1i, "Store 32-bit Compare Conditional"),
	TO_ENUM(XTENSA_dci, "Data Cache Coherent Hit Invalidate"),
	TO_ENUM(XTENSA_dcwb, "Data Cache Coherent Hit Writeback"),
	TO_ENUM(XTENSA_dcwbi, "Data Cache Coherent Hit WB Invalidate"),
	TO_ENUM(XTENSA_dhi, "Data Cache Hit Invalidate"),
	TO_ENUM(XTENSA_dhu, "Data Cache Hit Unlock"),
	TO_ENUM(XTENSA_dhwb, "Data Cache Hit Writeback"),
	TO_ENUM(XTENSA_dhwbi, "Data Cache Hit Writeback Invalidate"),
	TO_ENUM(XTENSA_dii, "Data Cache Index Invalidate"),
	TO_ENUM(XTENSA_diu, "Data Cache Index Unlock"),
	TO_ENUM(XTENSA_diwb, "Data Cache Index Write Back"),
	TO_ENUM(XTENSA_diwbi, "Data Cache Index Write Back Invalidate"),
	TO_ENUM(XTENSA_diwbui_p, "Data Cache Empty"),
	TO_ENUM(XTENSA_dpfl, "Data Cache Prefetch and Lock"),
	TO_ENUM(XTENSA_dpfr, "Data Cache Prefetch for Read"),
	TO_ENUM(XTENSA_dpfro, "Data Cache Prefetch for Read Once"),
	TO_ENUM(XTENSA_dpfw, "Data Cache Prefetch for Write"),
	TO_ENUM(XTENSA_dpfwo, "Data Cache Prefetch for Write Once"),
	TO_ENUM(XTENSA_ldct, "Load Data Cache Tag"),
	TO_ENUM(XTENSA_ldcw, "Load Data Cache Word"),
	TO_ENUM(XTENSA_sdct, "Store Data Cache Tag"),
	TO_ENUM(XTENSA_sdcw, "Store Data Cache Word"),
	TO_ENUM(XTENSA_lddr32_p, "Load to DDR Register"),
	TO_ENUM(XTENSA_rfdd, "Return from Debug and Dispatch"),
	TO_ENUM(XTENSA_rfdo, "Return from Debug Operation"),
	TO_ENUM(XTENSA_sddr32_p, "Store from DDR Register"),
	TO_ENUM(XTENSA_depbits, "Deposit Bits                           - same encoding as \"add.s\""),
	TO_ENUM(XTENSA_rfde, "Return from Double Exception"),
	TO_ENUM(XTENSA_rfue, "Return from User-Mode Exception"),
	TO_ENUM(XTENSA_syscall, "System Call"),
	TO_ENUM(XTENSA_clrex, "Clear Exclusive"),
	TO_ENUM(XTENSA_getex, "Get Exclusive Result"),
	TO_ENUM(XTENSA_l32ex, "Load 32-bit Exclusive"),
	TO_ENUM(XTENSA_s32ex, "Store 32-bit Exclusive"),
	TO_ENUM(XTENSA_abs_d, "Absolute Value Double"),
	TO_ENUM(XTENSA_abs_s, "Absolute Value Single"),
	TO_ENUM(XTENSA_add_d, "Add Double"),
	TO_ENUM(XTENSA_add_s, "Add Single                             - same encoding as \"depbits\""),
	TO_ENUM(XTENSA_addexp_d, "Add Exponent Double"),
	TO_ENUM(XTENSA_addexp_s, "Add Exponent Single"),
	TO_ENUM(XTENSA_addexpm_d, "Add Exponent from Mantissa Double"),
	TO_ENUM(XTENSA_addexpm_s, "Add Exponent from Mantissa Single"),
	TO_ENUM(XTENSA_ceil_d, "Ceiling Double to Fixed"),
	TO_ENUM(XTENSA_ceil_s, "Ceiling Single to Fixed"),
	TO_ENUM(XTENSA_const_d, "Constant Double"),
	TO_ENUM(XTENSA_const_s, "Constant Single"),
	TO_ENUM(XTENSA_cvtd_s, "Convert Single to Double"),
	TO_ENUM(XTENSA_cvts_d, "Convert Double to Single"),
	TO_ENUM(XTENSA_div0_d, "Divide Begin Double"),
	TO_ENUM(XTENSA_div0_s, "Divide Begin Single"),
	TO_ENUM(XTENSA_divn_d, "Divide Final Double"),
	TO_ENUM(XTENSA_divn_s, "Divide Final Single"),
	TO_ENUM(XTENSA_float_d, "Convert Fixed to Double"),
	TO_ENUM(XTENSA_float_s, "Convert Fixed to Single"),
	TO_ENUM(XTENSA_floor_d, "Floor Double to Fixed"),
	TO_ENUM(XTENSA_floor_s, "Floor Single to Fixed"),
	TO_ENUM(XTENSA_ldi, "Load Double Immediate"),
	TO_ENUM(XTENSA_ldip, "Load Double Immediate Post-Increment"),
	TO_ENUM(XTENSA_ldx, "Load Double Indexed"),
	TO_ENUM(XTENSA_ldxp, "Load Double Indexed Post-Increment"),
	TO_ENUM(XTENSA_lsip, "Load Single Immediate Post-Increment   - newer  version of lsiu"),
	TO_ENUM(XTENSA_lsiu, "Load Single Immediate with Update      - fp2000 version of lsip"),
	TO_ENUM(XTENSA_lsxp, "Load Single Indexed Post-Increment     - newer  version of lsxu"),
	TO_ENUM(XTENSA_lsxu, "Load Single Indexed with Update        - fp2000 version of lsxp"),
	TO_ENUM(XTENSA_madd_d, "Multiply and Add Double"),
	TO_ENUM(XTENSA_madd_s, "Multiply and Add Single"),
	TO_ENUM(XTENSA_maddn_d, "Multiply and Add Double Round Nearest"),
	TO_ENUM(XTENSA_maddn_s, "Multiply and Add Single Round Nearest"),
	TO_ENUM(XTENSA_mkdadj_d, "Make Divide Adjust Double"),
	TO_ENUM(XTENSA_mkdadj_s, "Make Divide Adjust Single"),
	TO_ENUM(XTENSA_mksadj_d, "Make Square Root Adjust Double"),
	TO_ENUM(XTENSA_mksadj_s, "Make Square Root Adjust Single"),
	TO_ENUM(XTENSA_mov_d, "Move Double"),
	TO_ENUM(XTENSA_mov_s, "Move Single"),
	TO_ENUM(XTENSA_moveqz_s, "Move Single if Equal to Zero"),
	TO_ENUM(XTENSA_movf_s, "Move Single if False"),
	TO_ENUM(XTENSA_movgez_s, "Move Single if Greater Than or Equal to Zero"),
	TO_ENUM(XTENSA_movltz_s, "Move Single if Less Than Zero"),
	TO_ENUM(XTENSA_movnez_s, "Move Single if Not Equal to Zero"),
	TO_ENUM(XTENSA_movt_s, "Move Single if True"),
	TO_ENUM(XTENSA_msub_d, "Multiply and Subtract Double"),
	TO_ENUM(XTENSA_msub_s, "Multiply and Subtract Single"),
	TO_ENUM(XTENSA_mul_d, "Multiply Double"),
	TO_ENUM(XTENSA_mul_s, "Multiply Single"),
	TO_ENUM(XTENSA_neg_d, "Negate Double"),
	TO_ENUM(XTENSA_neg_s, "Negate Single"),
	TO_ENUM(XTENSA_nexp01_d, "Narrow Exponent Range Double"),
	TO_ENUM(XTENSA_nexp01_s, "Narrow Exponent Range Single"),
	TO_ENUM(XTENSA_oeq_d, "Compare Double Equal"),
	TO_ENUM(XTENSA_oeq_s, "Compare Single Equal"),
	TO_ENUM(XTENSA_ole_d, "Compare Double Ordered and Less Than or Equal"),
	TO_ENUM(XTENSA_ole_s, "Compare Single Ordered and Less Than or Equal"),
	TO_ENUM(XTENSA_olt_d, "Compare Double Ordered and Less Than"),
	TO_ENUM(XTENSA_olt_s, "Compare Single Ordered and Less Than"),
	TO_ENUM(XTENSA_recip0_d, "Reciprocal Begin Double"),
	TO_ENUM(XTENSA_recip0_s, "Reciprocal Begin Single"),
	TO_ENUM(XTENSA_rfr, "Move FR to AR"),
	TO_ENUM(XTENSA_rfrd, "Move FR to AR Upper"),
	TO_ENUM(XTENSA_round_d, "Round Double to Fixed"),
	TO_ENUM(XTENSA_round_s, "Round Single to Fixed"),
	TO_ENUM(XTENSA_rsqrt0_d, "Reciprocal Sqrt Begin Double"),
	TO_ENUM(XTENSA_rsqrt0_s, "Reciprocal Sqrt Begin Single"),
	TO_ENUM(XTENSA_sdi, "Store Double Immediate"),
	TO_ENUM(XTENSA_sdip, "Store Double Immediate Post-Increment"),
	TO_ENUM(XTENSA_sdx, "Store Double Indexed"),
	TO_ENUM(XTENSA_sdxp, "Store Double Indexed Post-Increment"),
	TO_ENUM(XTENSA_sqrt0_d, "Sqrt Begin Double"),
	TO_ENUM(XTENSA_sqrt0_s, "Sqrt Begin Single"),
	TO_ENUM(XTENSA_ssi, "Store Single Immediate"),
	TO_ENUM(XTENSA_ssip, "Store Single Immediate Post-Increment  - newer  version of ssiu"),
	TO_ENUM(XTENSA_ssiu, "Store Single Immediate with Update     - fp2000 version of ssip"),
	TO_ENUM(XTENSA_ssx, "Store Single Indexed"),
	TO_ENUM(XTENSA_ssxp, "Store Single Indexed Post-Increment    - newer  version of ssxu"),
	TO_ENUM(XTENSA_ssxu, "Store Single Indexed with Update       - fp2000 version of ssxp"),
	TO_ENUM(XTENSA_sub_d, "Subtract Double"),
	TO_ENUM(XTENSA_sub_s, "Subtract Single"),
	TO_ENUM(XTENSA_trunc_d, "Truncate Double to Fixed"),
	TO_ENUM(XTENSA_trunc_s, "Truncate Single to Fixed"),
	TO_ENUM(XTENSA_ueq_d, "Compare Double Unordered or Equal"),
	TO_ENUM(XTENSA_ueq_s, "Compare Single Unordered or Equal"),
	TO_ENUM(XTENSA_ufloat_d, "Convert Unsigned Fixed to Double"),
	TO_ENUM(XTENSA_ufloat_s, "Convert Unsigned Fixed to Single"),
	TO_ENUM(XTENSA_ule_d, "Compare Double Unord or Less Than or Equal"),
	TO_ENUM(XTENSA_ule_s, "Compare Single Unord or Less Than or Equal"),
	TO_ENUM(XTENSA_ult_d, "Compare Double Unordered or Less Than"),
	TO_ENUM(XTENSA_ult_s, "Compare Single Unordered or Less Than"),
	TO_ENUM(XTENSA_un_d, "Compare Double Unordered"),
	TO_ENUM(XTENSA_un_s, "Compare Single Unordered"),
	TO_ENUM(XTENSA_utrunc_d, "Truncate Double to Fixed Unsigned"),
	TO_ENUM(XTENSA_utrunc_s, "Truncate Single to Fixed Unsigned"),
	TO_ENUM(XTENSA_wfr, "Move AR to FR"),
	TO_ENUM(XTENSA_wfrd, "Move AR to FR Double"),
	TO_ENUM(XTENSA_ihi, "Instruction Cache Hit Invalidate"),
	TO_ENUM(XTENSA_ihu, "Instruction Cache Hit Unlock"),
	TO_ENUM(XTENSA_iii, "Instruction Cache Index Invalidate"),
	TO_ENUM(XTENSA_iiu, "Instruction Cache Index Unlock"),
	TO_ENUM(XTENSA_ipf, "Instruction Cache Prefetch"),
	TO_ENUM(XTENSA_ipfl, "Instruction Cache Prefetch and Lock"),
	TO_ENUM(XTENSA_lict, "Load Instruction Cache Tag"),
	TO_ENUM(XTENSA_licw, "Load Instruction Cache Word"),
	TO_ENUM(XTENSA_sict, "Store Instruction Cache Tag"),
	TO_ENUM(XTENSA_sicw, "Store Instruction Cache Word"),
	TO_ENUM(XTENSA_mulsh, "Multiply Signed High"),
	TO_ENUM(XTENSA_muluh, "Multiply Unsigned High"),
	TO_ENUM(XTENSA_quos, "Quotient Signed"),
	TO_ENUM(XTENSA_quou, "Quotient Unsigned"),
	TO_ENUM(XTENSA_rems, "Remainder Signed"),
	TO_ENUM(XTENSA_remu, "Remainder Unsigned"),
	TO_ENUM(XTENSA_lddec, "Load with Autodecrement"),
	TO_ENUM(XTENSA_ldinc, "Load with Autoincrement"),
	TO_ENUM(XTENSA_mul_aa, "Signed Multiply"),
	TO_ENUM(XTENSA_mul_ad, "Signed Multiply"),
	TO_ENUM(XTENSA_mul_da, "Signed Multiply"),
	TO_ENUM(XTENSA_mul_dd, "Signed Multiply"),
	TO_ENUM(XTENSA_mula_aa, "Signed Multiply/Accumulate"),
	TO_ENUM(XTENSA_mula_ad, "Signed Multiply/Accumulate"),
	TO_ENUM(XTENSA_mula_da, "Signed Multiply/Accumulate"),
	TO_ENUM(XTENSA_mula_da_lddec, "Signed Multiply/Accumulate, Ld/Autodec"),
	TO_ENUM(XTENSA_mula_da_ldinc, "Signed Multiply/Accumulate, Ld/Autoinc"),
	TO_ENUM(XTENSA_mula_dd, "Signed Multiply/Accumulate"),
	TO_ENUM(XTENSA_mula_dd_lddec, "Signed Multiply/Accumulate, Ld/Autodec"),
	TO_ENUM(XTENSA_mula_dd_ldinc, "Signed Multiply/Accumulate, Ld/Autoinc"),
	TO_ENUM(XTENSA_muls_aa, "Signed Multiply/Subtract"),
	TO_ENUM(XTENSA_muls_ad, "Signed Multiply/Subtract"),
	TO_ENUM(XTENSA_muls_da, "Signed Multiply/Subtract"),
	TO_ENUM(XTENSA_muls_dd, "Signed Multiply/Subtract"),
	TO_ENUM(XTENSA_umul_aa, "Unsigned Multiply"),
	TO_ENUM(XTENSA_rfme, "Return from Memory Error"),
	TO_ENUM(XTENSA_clamps, "Signed Clamp"),
	TO_ENUM(XTENSA_l32ai, "Load 32-bit Aquire"),
	TO_ENUM(XTENSA_idtlb, "Invalidate Data TLB Entry"),
	TO_ENUM(XTENSA_iitlb, "Invalidate Instruction TLB Entry"),
	TO_ENUM(XTENSA_pdtlb, "Probe Data TLB"),
	TO_ENUM(XTENSA_pitlb, "Probe Intruction TLB"),
	TO_ENUM(XTENSA_pptlb, "Probe Protection TLB                   - same encoding as \"pdtlb\""),
	TO_ENUM(XTENSA_rdtlb0, "Read Data TLB Entry Virtual"),
	TO_ENUM(XTENSA_rdtlb1, "Read Data TLB Entry Translation"),
	TO_ENUM(XTENSA_ritlb0, "Read Instruction TLB Entry Virtual"),
	TO_ENUM(XTENSA_ritlb1, "Read Instruction TLB Entry Translation"),
	TO_ENUM(XTENSA_rptlb0, "Read Protection TLB Entry Address      - same encoding as \"rdtlb0\""),
	TO_ENUM(XTENSA_rptlb1, "Read Protection TLB Entry Info         - same encoding as \"rdtlb1\""),
	TO_ENUM(XTENSA_wptlb, "Write Protection TLB Entry             - same encoding as \"wdtlb\""),
	TO_ENUM(XTENSA_simcall, "Simulator Call"),
	TO_ENUM(XTENSA_l32e, "Load 32-bit for Window Exceptions"),
	TO_ENUM(XTENSA_movsp, "Move to Stack Pointer"),
	TO_ENUM(XTENSA_rfwo, "Return from Window Overflow"),
	TO_ENUM(XTENSA_rfwu, "Return from Window Underflow"),
	TO_ENUM(XTENSA_rotw, "Rotate Window"),
	TO_ENUM(XTENSA_s32e, "Store 32-bit for Window Exceptions"),
	TO_ENUM(XTENSA_clrb_expstate, "?"),
	TO_ENUM(XTENSA_hwwdtlba, "?"),
	TO_ENUM(XTENSA_hwwitlba, "?"),
	TO_ENUM(XTENSA_ldpte, "?"),
	TO_ENUM(XTENSA_read_impwire, "?"),
	TO_ENUM(XTENSA_setb_expstate, "?"),
	TO_ENUM(XTENSA_wrmsk_expstate, "?"),
	TO_ENUM(XTENSA_ae2_rur, "Read User Register (AE2 version)"),
	TO_ENUM(XTENSA_ae2_wur, "Write User Register (AE2 version)"),
	TO_ENUM(XTENSA_ae_rur, "Read User Register (AE version)"),
	TO_ENUM(XTENSA_ae_wur, "Write User Register (AE version)"),
	TO_ENUM(XTENSA_last, "Undocumented instruction XTENSA_last")
};
