auto instructions_PLFM_M7700 = flags_vector_t{
	TO_ENUM(m7700_null, "Undocumented instruction m7700_null"),
	TO_ENUM(m7700_adc, "addition with carry"),
	TO_ENUM(m7700_and, "logical AND"),
	TO_ENUM(m7700_asl, "arithmetic shift left"),
	TO_ENUM(m7700_bbc, "branch on bit clear"),
	TO_ENUM(m7700_bbs, "branch on bit set"),
	TO_ENUM(m7700_bcc, "branch on carry clear"),
	TO_ENUM(m7700_bcs, "branch on carry set"),
	TO_ENUM(m7700_beq, "branch on equal"),
	TO_ENUM(m7700_bmi, "branch on result minus"),
	TO_ENUM(m7700_bne, "branch on not equal"),
	TO_ENUM(m7700_bpl, "branch on result plus"),
	TO_ENUM(m7700_bra, "branch always"),
	TO_ENUM(m7700_brk, "force break"),
	TO_ENUM(m7700_bvc, "branch on overflow clear"),
	TO_ENUM(m7700_bvs, "branch on overflow set"),
	TO_ENUM(m7700_clb, "clear bit"),
	TO_ENUM(m7700_clc, "clear carry flag"),
	TO_ENUM(m7700_cli, "clear interrupt disable status"),
	TO_ENUM(m7700_clm, "clear m flag"),
	TO_ENUM(m7700_clp, "clear processor status"),
	TO_ENUM(m7700_clv, "clear overflow flag"),
	TO_ENUM(m7700_cmp, "compare"),
	TO_ENUM(m7700_cpx, "compare memory and index register X"),
	TO_ENUM(m7700_cpy, "compare memory and index register Y"),
	TO_ENUM(m7700_dec, "decrement by one"),
	TO_ENUM(m7700_dex, "decrement index register X by one"),
	TO_ENUM(m7700_dey, "decrement index register Y by one"),
	TO_ENUM(m7700_div, "divide"),
	TO_ENUM(m7700_eor, "exclusive OR memory with accumulator"),
	TO_ENUM(m7700_inc, "increment by one"),
	TO_ENUM(m7700_inx, "increment index register X by one"),
	TO_ENUM(m7700_iny, "increment index register Y by one"),
	TO_ENUM(m7700_jmp, "jump"),
	TO_ENUM(m7700_jsr, "jump to subroutine"),
	TO_ENUM(m7700_lda, "load accumulator from memory"),
	TO_ENUM(m7700_ldm, "load immediate to memory"),
	TO_ENUM(m7700_ldt, "load immediate to data bank register"),
	TO_ENUM(m7700_ldx, "load index register X from memory"),
	TO_ENUM(m7700_ldy, "load index register Y from memory"),
	TO_ENUM(m7700_lsr, "logical shift right"),
	TO_ENUM(m7700_mpy, "multiply"),
	TO_ENUM(m7700_mvn, "move negative"),
	TO_ENUM(m7700_mvp, "move positive"),
	TO_ENUM(m7700_nop, "no operation"),
	TO_ENUM(m7700_ora, "OR memory with accumulator"),
	TO_ENUM(m7700_pea, "push effective address"),
	TO_ENUM(m7700_pei, "push effective indirect address"),
	TO_ENUM(m7700_per, "push effective program counter relative address"),
	TO_ENUM(m7700_pha, "push accumulator A on stack"),
	TO_ENUM(m7700_phb, "push accumulator B on stack"),
	TO_ENUM(m7700_phd, "push direct page register on stack"),
	TO_ENUM(m7700_phg, "push program bank register on stack"),
	TO_ENUM(m7700_php, "push processor status on stack"),
	TO_ENUM(m7700_pht, "push data bank register on stack"),
	TO_ENUM(m7700_phx, "push index register X on stack"),
	TO_ENUM(m7700_phy, "push index register Y on stack"),
	TO_ENUM(m7700_pla, "pull accumulator A from stack"),
	TO_ENUM(m7700_plb, "pull accumulator B from stack"),
	TO_ENUM(m7700_pld, "pull direct page register from stack"),
	TO_ENUM(m7700_plp, "pull processor status from stack"),
	TO_ENUM(m7700_plt, "pull data bank register from stack"),
	TO_ENUM(m7700_plx, "pull index register X from stack"),
	TO_ENUM(m7700_ply, "pull index register Y from stack"),
	TO_ENUM(m7700_psh, "push"),
	TO_ENUM(m7700_pul, "pull"),
	TO_ENUM(m7700_rla, "rotate left accumulator A"),
	TO_ENUM(m7700_rol, "rotate one bit left"),
	TO_ENUM(m7700_ror, "rotate one bit right"),
	TO_ENUM(m7700_rti, "return from interrupt"),
	TO_ENUM(m7700_rtl, "return from subroutine long"),
	TO_ENUM(m7700_rts, "return from subroutine"),
	TO_ENUM(m7700_sbc, "subtract with carry"),
	TO_ENUM(m7700_seb, "set bit"),
	TO_ENUM(m7700_sec, "set carry flag"),
	TO_ENUM(m7700_sei, "set interrupt disable status"),
	TO_ENUM(m7700_sem, "set m flag"),
	TO_ENUM(m7700_sep, "set processor status"),
	TO_ENUM(m7700_sta, "store accumulator in memory"),
	TO_ENUM(m7700_stp, "stop"),
	TO_ENUM(m7700_stx, "store index register X in memory"),
	TO_ENUM(m7700_sty, "store index register Y in memory"),
	TO_ENUM(m7700_tad, "transfer accumulator A to direct page register"),
	TO_ENUM(m7700_tas, "transfer accumulator A to stack pointer"),
	TO_ENUM(m7700_tax, "transfer accumulator A to index register X"),
	TO_ENUM(m7700_tay, "transfer accumulator A to index register Y"),
	TO_ENUM(m7700_tbd, "transfer accumulator B to direct page register"),
	TO_ENUM(m7700_tbs, "transfer accumulator B to stack pointer"),
	TO_ENUM(m7700_tbx, "transfer accumulator B to index register X"),
	TO_ENUM(m7700_tby, "transfer accumulator B to index register Y"),
	TO_ENUM(m7700_tda, "transfer direct page register to accumulator A"),
	TO_ENUM(m7700_tdb, "transfer direct page register to accumulator B"),
	TO_ENUM(m7700_tsa, "transfer stack pointer to accumulator A"),
	TO_ENUM(m7700_tsb, "transfer stack pointer to accumulator B"),
	TO_ENUM(m7700_tsx, "transfer stack pointer to index register X"),
	TO_ENUM(m7700_txa, "transfer index register X to accumulator A"),
	TO_ENUM(m7700_txb, "transfer index register X to accumulator B"),
	TO_ENUM(m7700_txs, "transfer index register X to stack pointer"),
	TO_ENUM(m7700_txy, "transfer index register X to Y"),
	TO_ENUM(m7700_tya, "transfer index register Y to accumulator A"),
	TO_ENUM(m7700_tyb, "transfer index register Y to accumulator B"),
	TO_ENUM(m7700_tyx, "transfer index register Y to X"),
	TO_ENUM(m7700_wit, "wait"),
	TO_ENUM(m7700_xab, "exchange accumulator A and B"),
	TO_ENUM(m7700_last, "Undocumented instruction m7700_last")
};
