auto instructions_PLFM_6800 = flags_vector_t{
	TO_ENUM(mc8_null, "Undocumented instruction mc8_null"),
	TO_ENUM(mc8_aba, "Add b to a                                  (11)"),
	TO_ENUM(mc8_ab, "Add b to index register"),
	TO_ENUM(mc8_adc, "Add with carry"),
	TO_ENUM(mc8_add, "Add without carry"),
	TO_ENUM(mc8_addd, "Add 16-bit to D                             (11)"),
	TO_ENUM(mc8_ais, "Add immediate value to stack pointer        (8)"),
	TO_ENUM(mc8_aix, "Add immediate value to index register (H:X) (8)"),
	TO_ENUM(mc8_and, "Logical AND"),
	TO_ENUM(mc8_andcc, "Logical AND immdiate with CCR (9)"),
	TO_ENUM(mc8_asr, "Ariphmetic shift right"),
	TO_ENUM(mc8_bcc, "Branch if carry bit clear"),
	TO_ENUM(mc8_bclr, "Clear bit in memory"),
	TO_ENUM(mc8_bcs, "Branch if carry bit set"),
	TO_ENUM(mc8_beq, "Branch if equal"),
	TO_ENUM(mc8_bge, "Branch if >= (signed)"),
	TO_ENUM(mc8_bgt, "Branch if > (signed)"),
	TO_ENUM(mc8_bhcc, "Branch if half carry bit clear (8)"),
	TO_ENUM(mc8_bhcs, "Branch if half carry bit set   (8)"),
	TO_ENUM(mc8_bhi, "Branch if > (unsigned)"),
	TO_ENUM(mc8_bhs, "Branch if >= (unsigned)        (11)"),
	TO_ENUM(mc8_bih, "Branch if IRQ pin high         (8)"),
	TO_ENUM(mc8_bil, "Branch if IRQ pin low          (8)"),
	TO_ENUM(mc8_bit, "Bit test                       (8)"),
	TO_ENUM(mc8_ble, "Branch if <= (signed)          (8)"),
	TO_ENUM(mc8_blo, "Branch if <  (unsigned)        (11)"),
	TO_ENUM(mc8_bls, "Branch if <= (unsigned)        (8)"),
	TO_ENUM(mc8_blt, "Branch if < (signed)           (8)"),
	TO_ENUM(mc8_bmc, "Branch if interrupt mask clear (8)"),
	TO_ENUM(mc8_bmi, "Branch if minus"),
	TO_ENUM(mc8_bms, "Branch if interrupt mask set   (8)"),
	TO_ENUM(mc8_bne, "Branch if not equal"),
	TO_ENUM(mc8_bpl, "Branch if not plus"),
	TO_ENUM(mc8_bra, "Branch always"),
	TO_ENUM(mc8_brclr, "Branch if bit (n) in memory clear"),
	TO_ENUM(mc8_brn, "Branch never"),
	TO_ENUM(mc8_brset, "Branch if bit (n) in memory set"),
	TO_ENUM(mc8_bset, "Set bit in memory"),
	TO_ENUM(mc8_bsr, "Branch to subroutine"),
	TO_ENUM(mc8_bvc, "Branch if overflow cleared     (11)"),
	TO_ENUM(mc8_bvs, "Branch if overflow set         (11)"),
	TO_ENUM(mc8_cba, "Compare A to B                 (11)"),
	TO_ENUM(mc8_cbeq, "Compare and branch if equal    (8)"),
	TO_ENUM(mc8_clc, "Clear carry bit"),
	TO_ENUM(mc8_cli, "Clear interrupt mask"),
	TO_ENUM(mc8_clr, "Clear"),
	TO_ENUM(mc8_clv, "Clear overflow flag            (11)"),
	TO_ENUM(mc8_cmp, "Compare accumulator with memory"),
	TO_ENUM(mc8_com, "Complement"),
	TO_ENUM(mc8_cp, "Compare index register 16 bit  (11)"),
	TO_ENUM(mc8_cpd, "Compare D 16 bit               (11)"),
	TO_ENUM(mc8_cphx, "Compare index register with memory          (8)"),
	TO_ENUM(mc8_cpx, "Compare X (index register low) with memory  (8)"),
	TO_ENUM(mc8_cwai, "Clear CC bits & wait for interrupt          (9)"),
	TO_ENUM(mc8_daa, "Decimal adjust accumulator"),
	TO_ENUM(mc8_dbnz, "Decrement and branch if not equal   (8)"),
	TO_ENUM(mc8_de, "Decrement index register            (11)"),
	TO_ENUM(mc8_dec, "Decrement"),
	TO_ENUM(mc8_des, "Decrement stack pointer             (11)"),
	TO_ENUM(mc8_div, "Divide                              (8)"),
	TO_ENUM(mc8_eor, "Excusive OR memory with accumulator"),
	TO_ENUM(mc8_exg, "Exchange register                   (9)"),
	TO_ENUM(mc8_fdiv, "Fractional divide 16 by 16          (11)"),
	TO_ENUM(mc8_idiv, "Integer divide 16 by 16             (11)"),
	TO_ENUM(mc8_in, "Increment index register            (11)"),
	TO_ENUM(mc8_inc, "Increment"),
	TO_ENUM(mc8_ins, "Increment stack pointer             (11)"),
	TO_ENUM(mc8_jmp, "Jump"),
	TO_ENUM(mc8_jsr, "Jump to subroutine"),
	TO_ENUM(mc8_ld, "Load index register                     (11)"),
	TO_ENUM(mc8_lda, "Load accumulator from memory"),
	TO_ENUM(mc8_ldd, "Load double accumulator                 (11)"),
	TO_ENUM(mc8_ldhx, "Load index register from memory         (8)"),
	TO_ENUM(mc8_lds, "Load stack pointer                      (11)"),
	TO_ENUM(mc8_ldx, "Load X (index register low) from memory (8)"),
	TO_ENUM(mc8_lea, "Load register from memory               (9)"),
	TO_ENUM(mc8_lsl, "Logical (or Ariphmetic) shift left"),
	TO_ENUM(mc8_lsld, "Logical (or Ariphmetic) shift left double (11)"),
	TO_ENUM(mc8_lsr, "Logical shift right"),
	TO_ENUM(mc8_lsrd, "Logical shift right double                (11)"),
	TO_ENUM(mc8_mov, "Move                          (8)"),
	TO_ENUM(mc8_mul, "Unsigned multiply"),
	TO_ENUM(mc8_neg, "Negate"),
	TO_ENUM(mc8_nop, "No Operation"),
	TO_ENUM(mc8_nsa, "Nibble swap accumulator       (8)"),
	TO_ENUM(mc8_ora, "Inclusive OR memory with accumulator"),
	TO_ENUM(mc8_orcc, "Inclusive OR immediate with CCR            (9)"),
	TO_ENUM(mc8_psh, "Push index register into stack (low first) (11)"),
	TO_ENUM(mc8_psha, "Push accumulator A into stack"),
	TO_ENUM(mc8_pshb, "Push accumulator B into stack              (11)"),
	TO_ENUM(mc8_pshh, "Push H (index register high) into stack    (8)"),
	TO_ENUM(mc8_pshx, "Push X (index register low) into stack     (8)"),
	TO_ENUM(mc8_pul, "Pull index register from stack (hi first)  (11)"),
	TO_ENUM(mc8_pula, "Pull accumulator A from stack"),
	TO_ENUM(mc8_pulb, "Pull accumulator B from stack              (11)"),
	TO_ENUM(mc8_pulh, "Pull H (index register high) from stack    (8)"),
	TO_ENUM(mc8_pulx, "Pull X (index register low) from stack     (8)"),
	TO_ENUM(mc8_rol, "Rotate left trough carry"),
	TO_ENUM(mc8_ror, "Rotate right trough carry"),
	TO_ENUM(mc8_rsp, "Reset stack pointer               (8)"),
	TO_ENUM(mc8_rti, "Reset from interrupt"),
	TO_ENUM(mc8_rts, "Reset from subroutine"),
	TO_ENUM(mc8_sba, "Subtract B from A                       (11)"),
	TO_ENUM(mc8_sbc, "Subtract with carry"),
	TO_ENUM(mc8_sec, "Set carry bit"),
	TO_ENUM(mc8_sei, "Set interrupt mask bit"),
	TO_ENUM(mc8_sev, "Set Overflow Flag                       (11)"),
	TO_ENUM(mc8_sex, "Sign extended                           (9)"),
	TO_ENUM(mc8_slp, "Sleep    (HD63701 extention)            (11)"),
	TO_ENUM(mc8_st, "Store index register in memory          (11)"),
	TO_ENUM(mc8_sta, "Store accumulator in memory"),
	TO_ENUM(mc8_std, "Store accumulators in memory            (11)"),
	TO_ENUM(mc8_sthx, "Store H:X (index reg)                   (8)"),
	TO_ENUM(mc8_stop, "Enable IRQ pin. Stop oscillator"),
	TO_ENUM(mc8_sts, "Store stack pointer                     (11)"),
	TO_ENUM(mc8_stx, "Store X (index register low) in memory  (8)"),
	TO_ENUM(mc8_sub, "Subtract"),
	TO_ENUM(mc8_subd, "Subtract 16-bit                         (11)"),
	TO_ENUM(mc8_swi, "Software interrupt"),
	TO_ENUM(mc8_sync, "Syncronisation with interrupt           (9)"),
	TO_ENUM(mc8_tab, "Transfer A to B                                (11)"),
	TO_ENUM(mc8_tap, "Transfer A to CCR"),
	TO_ENUM(mc8_tax, "Transfer accumulator to X (index register low) (8)"),
	TO_ENUM(mc8_tba, "Transfer B to A                                (11)"),
	TO_ENUM(mc8_test, "Address Bus Counts (in test mode)              (11)"),
	TO_ENUM(mc8_tfr, "Transfer register to register                  (9)"),
	TO_ENUM(mc8_tpa, "Transfer CCR to A"),
	TO_ENUM(mc8_ts, "Transfer SP to index reg                       (11)"),
	TO_ENUM(mc8_tst, "Test for negative or zero"),
	TO_ENUM(mc8_tsx, "Transfer SP to index reg                       (8)"),
	TO_ENUM(mc8_txa, "Transfer X (index reg low) to accumulator      (8)"),
	TO_ENUM(mc8_txs, "Transfer index reg X to SP"),
	TO_ENUM(mc8_tys, "Transfer index reg Y to SP                     (11)"),
	TO_ENUM(mc8_wai, "Wait for interrupt                   (11)"),
	TO_ENUM(mc8_wait, "Enable interrupt. Stop processor     (8)"),
	TO_ENUM(mc8_xgd, "Exchange D with index register       (11)"),
	TO_ENUM(mc8_1, "Special testing command              (11)"),
	TO_ENUM(mc8_2, "Special testing command              (11)"),
	TO_ENUM(mc8_os9, "OS9 system call                      (9)"),
	TO_ENUM(mc8_aim, "Undocumented instruction mc8_aim"),
	TO_ENUM(mc8_oim, "Undocumented instruction mc8_oim"),
	TO_ENUM(mc8_eim, "Undocumented instruction mc8_eim"),
	TO_ENUM(mc8_tim, "Undocumented instruction mc8_tim"),
	TO_ENUM(mc8_bgnd, "Background                                     (8)"),
	TO_ENUM(mc8_call, "Call Subroutine                                (8)"),
	TO_ENUM(mc8_rtc, "Return fom Call                                (8)"),
	TO_ENUM(mc8_skip1, "Skip one byte"),
	TO_ENUM(mc8_skip2, "Skip two bytes"),
	TO_ENUM(mc8_last, "Undocumented instruction mc8_last")
};
