auto instructions_PLFM_TMS320C3 = flags_vector_t{
	TO_ENUM(TMS320C3X_null, "Undocumented instruction TMS320C3X_null"),
	TO_ENUM(TMS320C3X_ABSF, "Absolute value of a floating-point number"),
	TO_ENUM(TMS320C3X_ABSI, "Absolute value of an integer"),
	TO_ENUM(TMS320C3X_ADDC, "Add integers with carry"),
	TO_ENUM(TMS320C3X_ADDF, "Add Floating-Point Values"),
	TO_ENUM(TMS320C3X_ADDI, "Add Integer"),
	TO_ENUM(TMS320C3X_AND, "Bitwise-Logical AND"),
	TO_ENUM(TMS320C3X_ANDN, "Bitwise-Logical AND With Complement"),
	TO_ENUM(TMS320C3X_ASH, "Arithmetic Shift"),
	TO_ENUM(TMS320C3X_CMPF, "Compare Floating-Point Value"),
	TO_ENUM(TMS320C3X_CMPI, "Compare Integer"),
	TO_ENUM(TMS320C3X_FIX, "Floating-Point-to-Integer Conversion"),
	TO_ENUM(TMS320C3X_FLOAT, "Integer-to-Floating-Point Conversion"),
	TO_ENUM(TMS320C3X_IDLE, "Idle Until Interrupt"),
	TO_ENUM(TMS320C3X_IDLE2, "Low-Power Idle"),
	TO_ENUM(TMS320C3X_LDE, "Load Floating-Point Exponent"),
	TO_ENUM(TMS320C3X_LDF, "Load Floating-Point Value"),
	TO_ENUM(TMS320C3X_LDFI, "Load Floating-Point Value, Interlocked"),
	TO_ENUM(TMS320C3X_LDI, "Load Integer"),
	TO_ENUM(TMS320C3X_LDII, "Load Integer, Interlocked"),
	TO_ENUM(TMS320C3X_LDM, "Load Floating-Point Mantissa"),
	TO_ENUM(TMS320C3X_LSH, "Logical Shift"),
	TO_ENUM(TMS320C3X_MPYF, "Multiply Floating-Point Value"),
	TO_ENUM(TMS320C3X_MPYI, "Multiply Integer"),
	TO_ENUM(TMS320C3X_NEGB, "Negative Integer With Borrow"),
	TO_ENUM(TMS320C3X_NEGF, "Negate Floating-Point Value"),
	TO_ENUM(TMS320C3X_NEGI, "Negate Integer"),
	TO_ENUM(TMS320C3X_NOP, "No Operation"),
	TO_ENUM(TMS320C3X_NORM, "Normalize"),
	TO_ENUM(TMS320C3X_NOT, "Bitwise-Logical Complement"),
	TO_ENUM(TMS320C3X_POP, "Pop Integer"),
	TO_ENUM(TMS320C3X_POPF, "Pop Floating-Point Value"),
	TO_ENUM(TMS320C3X_PUSH, "PUSH Integer"),
	TO_ENUM(TMS320C3X_PUSHF, "PUSH Floating-Point Value"),
	TO_ENUM(TMS320C3X_OR, "Bitwise-Logical OR"),
	TO_ENUM(TMS320C3X_LOPOWER, "Divide Clock by 16"),
	TO_ENUM(TMS320C3X_MAXSPEED, "Restore Clock to Regular Speed"),
	TO_ENUM(TMS320C3X_RND, "Round Floating-Point Value"),
	TO_ENUM(TMS320C3X_ROL, "Rotate Left"),
	TO_ENUM(TMS320C3X_ROLC, "Rotate Left Through Carry"),
	TO_ENUM(TMS320C3X_ROR, "Rotate Right"),
	TO_ENUM(TMS320C3X_RORC, "Rotate Right Through Carry"),
	TO_ENUM(TMS320C3X_RPTS, "Repeat Single Instruction"),
	TO_ENUM(TMS320C3X_STF, "Store Floating-Point Value"),
	TO_ENUM(TMS320C3X_STFI, "Store Floating-Point Value, Interlocked"),
	TO_ENUM(TMS320C3X_STI, "Store Integer"),
	TO_ENUM(TMS320C3X_STII, "Store Integer, Interlocked"),
	TO_ENUM(TMS320C3X_SIGI, "Signal, Interlocked"),
	TO_ENUM(TMS320C3X_SUBB, "Subtract Integer With Borrow"),
	TO_ENUM(TMS320C3X_SUBC, "Subtract Integer Conditionally"),
	TO_ENUM(TMS320C3X_SUBF, "Subtract Floating-Point Value"),
	TO_ENUM(TMS320C3X_SUBI, "Subtract Integer"),
	TO_ENUM(TMS320C3X_SUBRB, "Subtract Reverse Integer With Borrow"),
	TO_ENUM(TMS320C3X_SUBRF, "Subtract Reverse Floating-Point Value"),
	TO_ENUM(TMS320C3X_SUBRI, "Subtract Reverse Integer"),
	TO_ENUM(TMS320C3X_TSTB, "Test Bit Fields"),
	TO_ENUM(TMS320C3X_XOR, "Bitwise-Exclusive OR"),
	TO_ENUM(TMS320C3X_IACK, "Interrupt acknowledge"),
	TO_ENUM(TMS320C3X_ADDC3, "Add integers with carry (3-operand)"),
	TO_ENUM(TMS320C3X_ADDF3, "Add floating-point values (3-operand)"),
	TO_ENUM(TMS320C3X_ADDI3, "Add integers (3 operand)"),
	TO_ENUM(TMS320C3X_AND3, "Bitwise-logical AND (3-operand)"),
	TO_ENUM(TMS320C3X_ANDN3, "Bitwise-logical ANDN (3-operand)"),
	TO_ENUM(TMS320C3X_ASH3, "Arithmetic shift (3-operand)"),
	TO_ENUM(TMS320C3X_CMPF3, "Compare floating-point values (3-operand)"),
	TO_ENUM(TMS320C3X_CMPI3, "Compare integers (3-operand)"),
	TO_ENUM(TMS320C3X_LSH3, "Logical shift (3-operand)"),
	TO_ENUM(TMS320C3X_MPYF3, "Multiply floating-point value (3-operand)"),
	TO_ENUM(TMS320C3X_MPYI3, "Multiply integers (3-operand)"),
	TO_ENUM(TMS320C3X_OR3, "Bitwise-logical OR (3-operand)"),
	TO_ENUM(TMS320C3X_SUBB3, "Subtract integers with borrow (3-operand)"),
	TO_ENUM(TMS320C3X_SUBF3, "Subtract floating-point values (3-operand)"),
	TO_ENUM(TMS320C3X_SUBI3, "Subtract integers (3-operand)"),
	TO_ENUM(TMS320C3X_TSTB3, "Test Bit Fields, 3-Operand"),
	TO_ENUM(TMS320C3X_XOR3, "Bitwise-Exclusive OR, 3-Operand"),
	TO_ENUM(TMS320C3X_LDFcond, "Load floating-point value conditionally"),
	TO_ENUM(TMS320C3X_LDIcond, "Load integer conditionally"),
	TO_ENUM(TMS320C3X_BR, "Branch unconditionally (standard)"),
	TO_ENUM(TMS320C3X_BRD, "Branch unconditionally (delayed)"),
	TO_ENUM(TMS320C3X_CALL, "Call subroutine"),
	TO_ENUM(TMS320C3X_RPTB, "Repeat block of instructions"),
	TO_ENUM(TMS320C3X_SWI, "Software Interrupt"),
	TO_ENUM(TMS320C3X_Bcond, "Branch conditionally"),
	TO_ENUM(TMS320C3X_DBcond, "Decrement and branch conditionally"),
	TO_ENUM(TMS320C3X_CALLcond, "Call subroutine conditionally"),
	TO_ENUM(TMS320C3X_TRAPcond, "Trap Conditionally"),
	TO_ENUM(TMS320C3X_RETIcond, "Return from interrupt conditionally"),
	TO_ENUM(TMS320C3X_RETScond, "Return from subroutine conditionally"),
	TO_ENUM(TMS320C3X_RETIU, "Return from interrupt unconditionally"),
	TO_ENUM(TMS320C3X_RETSU, "Return from subroutine unconditionally"),
	TO_ENUM(TMS320C3X_NONE, "Pseudo insn (more accurate definition need)"),
	TO_ENUM(TMS320C3X_MV_IDX, "Pseudo insn (move to next index need)"),
	TO_ENUM(TMS320C3X_last, "last ID")
};
