auto instructions_PLFM_ST7 = flags_vector_t{
	TO_ENUM(ST7_null, "Undocumented instruction ST7_null"),
	TO_ENUM(ST7_adc, "Add with Carry"),
	TO_ENUM(ST7_add, "Addition"),
	TO_ENUM(ST7_and, "Logical And"),
	TO_ENUM(ST7_bcp, "Bit compare"),
	TO_ENUM(ST7_bres, "Bit Reset"),
	TO_ENUM(ST7_bset, "Bit Set"),
	TO_ENUM(ST7_btjf, "Jump if bit is false"),
	TO_ENUM(ST7_btjt, "Jump if bit is true"),
	TO_ENUM(ST7_call, "Call subroutine"),
	TO_ENUM(ST7_callr, "Call subroutine relative"),
	TO_ENUM(ST7_clr, "Clear"),
	TO_ENUM(ST7_cp, "Arithmetic Compare"),
	TO_ENUM(ST7_cpl, "One Complement"),
	TO_ENUM(ST7_dec, "Decrement"),
	TO_ENUM(ST7_halt, "Halt"),
	TO_ENUM(ST7_iret, "Interrupt routine return"),
	TO_ENUM(ST7_inc, "Increment"),
	TO_ENUM(ST7_jp, "Absolute Jump"),
	TO_ENUM(ST7_jra, "Jump relative always"),
	TO_ENUM(ST7_jrt, "Jump relative"),
	TO_ENUM(ST7_jrf, "Never jump"),
	TO_ENUM(ST7_jrih, "Jump if Port INT pin = 1"),
	TO_ENUM(ST7_jril, "Jump if Port INT pin = 0"),
	TO_ENUM(ST7_jrh, "Jump if H = 1"),
	TO_ENUM(ST7_jrnh, "Jump if H = 0"),
	TO_ENUM(ST7_jrm, "Jump if I = 1"),
	TO_ENUM(ST7_jrnm, "Jump if I = 0"),
	TO_ENUM(ST7_jrmi, "Jump if N = 1 (minus)"),
	TO_ENUM(ST7_jrpl, "Jump if N = 0 (plus)"),
	TO_ENUM(ST7_jreq, "Jump if Z = 1 (equal)"),
	TO_ENUM(ST7_jrne, "Jump if Z = 0 (not equal)"),
	TO_ENUM(ST7_jrc, "Jump if C = 1"),
	TO_ENUM(ST7_jrnc, "Jump if C = 0"),
	TO_ENUM(ST7_jrult, "Jump if C = 1"),
	TO_ENUM(ST7_jruge, "Jump if C = 0"),
	TO_ENUM(ST7_jrugt, "Jump if (C + Z = 0)"),
	TO_ENUM(ST7_jrule, "Jump if (C + Z = 1)"),
	TO_ENUM(ST7_ld, "Load"),
	TO_ENUM(ST7_mul, "Multiply"),
	TO_ENUM(ST7_neg, "Negate"),
	TO_ENUM(ST7_nop, "No Operation"),
	TO_ENUM(ST7_or, "OR Operation"),
	TO_ENUM(ST7_pop, "Pop from the Stack"),
	TO_ENUM(ST7_push, "Push onto the Stack"),
	TO_ENUM(ST7_rcf, "Reset carry flag"),
	TO_ENUM(ST7_ret, "Subroutine Return"),
	TO_ENUM(ST7_rim, "Enable Interrupts"),
	TO_ENUM(ST7_rlc, "Rotate left true"),
	TO_ENUM(ST7_rrc, "Rotate right true"),
	TO_ENUM(ST7_rsp, "Reset Stack Pointer"),
	TO_ENUM(ST7_sbc, "Subtract with Carry"),
	TO_ENUM(ST7_scf, "Set carry flag"),
	TO_ENUM(ST7_sim, "Disable Interrupts"),
	TO_ENUM(ST7_sla, "Shift left Arithmetic"),
	TO_ENUM(ST7_sll, "Shift left Logic"),
	TO_ENUM(ST7_srl, "Shift right Logic"),
	TO_ENUM(ST7_sra, "Shift right Arithmetic"),
	TO_ENUM(ST7_sub, "Substraction"),
	TO_ENUM(ST7_swap, "SWAP nibbles"),
	TO_ENUM(ST7_tnz, "Test for Neg & Zero"),
	TO_ENUM(ST7_trap, "S/W trap"),
	TO_ENUM(ST7_wfi, "Wait for Interrupt"),
	TO_ENUM(ST7_xor, "Exclusive OR"),
	TO_ENUM(ST7_last, "Undocumented instruction ST7_last")
};
