auto instructions_PLFM_NEC_78K0 = flags_vector_t{
	TO_ENUM(NEC_78K_0_null, "Undocumented instruction NEC_78K_0_null"),
	TO_ENUM(NEC_78K_0_mov, "Move Byte Data Transfer"),
	TO_ENUM(NEC_78K_0_xch, "Exchange Byte Data"),
	TO_ENUM(NEC_78K_0_movw, "Move Word Data Transfer / Word Data Transfer with Stack Pointer"),
	TO_ENUM(NEC_78K_0_xchw, "Exchange Word Data"),
	TO_ENUM(NEC_78K_0_add, "Add Byte Data Addition"),
	TO_ENUM(NEC_78K_0_addc, "Add with Carry Addition of Byte Data with Carry"),
	TO_ENUM(NEC_78K_0_sub, "Subtract Byte Data Subtraction"),
	TO_ENUM(NEC_78K_0_subc, "Subtract with Carry Subtraction of Byte Data with Carry"),
	TO_ENUM(NEC_78K_0_and, "And Logical Product of Byte Data"),
	TO_ENUM(NEC_78K_0_or, "Or Logical Sum of Byte Data"),
	TO_ENUM(NEC_78K_0_xor, "Exclusive Or Exclusive Logical Sum of Byte Data"),
	TO_ENUM(NEC_78K_0_cmp, "Compare Byte Data Comparison"),
	TO_ENUM(NEC_78K_0_addw, "Add Word Data Addition"),
	TO_ENUM(NEC_78K_0_subw, "Subtract Word Data Subtraction"),
	TO_ENUM(NEC_78K_0_cmpw, "Compare Word Data Comparison"),
	TO_ENUM(NEC_78K_0_mulu, "Multiply Unsigned Multiplication of Data"),
	TO_ENUM(NEC_78K_0_divuw, "Divide Unsigned Word Unsigned Division of Word Data"),
	TO_ENUM(NEC_78K_0_inc, "Increment Byte Data Increment"),
	TO_ENUM(NEC_78K_0_dec, "Decrement Byte Data Decrement"),
	TO_ENUM(NEC_78K_0_incw, "Increment Word Data Increment"),
	TO_ENUM(NEC_78K_0_decw, "Decrement Word Data Decrement"),
	TO_ENUM(NEC_78K_0_ror, "Rotate Right Byte Data Rotation to the Right"),
	TO_ENUM(NEC_78K_0_rol, "Rotate Left Byte Data Rotation to the Left"),
	TO_ENUM(NEC_78K_0_rorc, "Rotate Right with Carry Byte Data Rotation to the Right with Carry"),
	TO_ENUM(NEC_78K_0_rolc, "Rotate Left with Carry Byte Data Rotation to the Left with Carry"),
	TO_ENUM(NEC_78K_0_ror4, "Rotate Right Digit Digit Rotation to the Right"),
	TO_ENUM(NEC_78K_0_rol4, "Rotate Left Digit Digit Rotation to the Left"),
	TO_ENUM(NEC_78K_0_adjba, "Decimal Adjust Register for Addition Decimal Adjustment of Addition Result"),
	TO_ENUM(NEC_78K_0_adjbs, "Decimal Adjust Register for Subtraction Decimal Adjustment of Subtraction Result"),
	TO_ENUM(NEC_78K_0_mov1, "Move Single Bit 1 Bit Data Transfer"),
	TO_ENUM(NEC_78K_0_and1, "And Single Bit 1 Bit Data Logical Product"),
	TO_ENUM(NEC_78K_0_or1, "Or Single Bit 1 Bit Data Logical Sum"),
	TO_ENUM(NEC_78K_0_xor1, "Exclusive Or Single Bit 1 Bit Data Exclusive Logical Sum"),
	TO_ENUM(NEC_78K_0_set1, "Set Single Bit (Carry Flag) 1 Bit Data Set"),
	TO_ENUM(NEC_78K_0_clr1, "Clear Single Bit (Carry Flag) 1 Bit Data Clear"),
	TO_ENUM(NEC_78K_0_not1, "Not Single Bit (Carry Flag) 1 Bit Data Logical Negation"),
	TO_ENUM(NEC_78K_0_call, "Call Subroutine Call (16 Bit Direct)"),
	TO_ENUM(NEC_78K_0_callf, "Call Flag Subroutine Call (11 Bit Direct Specification)"),
	TO_ENUM(NEC_78K_0_callt, "Call Table Subroutine Call (Refer to the Call Table)"),
	TO_ENUM(NEC_78K_0_brk, "Break Software Vectored Interrupt"),
	TO_ENUM(NEC_78K_0_ret, "Return Return from Subroutine"),
	TO_ENUM(NEC_78K_0_retb, "Return from Interrupt Return from Hardware Vectored Interrupt"),
	TO_ENUM(NEC_78K_0_reti, "Return from Break Return from Software Vectored Interrupt"),
	TO_ENUM(NEC_78K_0_push, "Push"),
	TO_ENUM(NEC_78K_0_pop, "Pop"),
	TO_ENUM(NEC_78K_0_br, "Branch Unconditional Branch"),
	TO_ENUM(NEC_78K_0_bc, "Branch if Carry Conditional Branch with Carry Flag (CY = 1)"),
	TO_ENUM(NEC_78K_0_bnc, "Branch if Not Carry Conditional Branch with Carry Flag (CY = 0)"),
	TO_ENUM(NEC_78K_0_bz, "Branch if Zero Conditional Branch with Zero Flag (Z = 1)"),
	TO_ENUM(NEC_78K_0_bnz, "Branch if Not Zero Conditional Branch with Zero Flag (Z = 0)"),
	TO_ENUM(NEC_78K_0_bt, "Branch if True Conditional Branch by Bit Test (Byte Data Bit = 1)"),
	TO_ENUM(NEC_78K_0_bf, "Branch if False Conditional Branch by Bit Test (Byte Data Bit = 0)"),
	TO_ENUM(NEC_78K_0_btclr, "Branch if True and Clear Conditional Branch and Clear by Bit Test (Byte Data Bit = 1)"),
	TO_ENUM(NEC_78K_0_dbnz, "Decrement and Branch if Not Zero Conditional Loop (R1!= 0)"),
	TO_ENUM(NEC_78K_0_sel, "Select Register Bank Register Bank Selection"),
	TO_ENUM(NEC_78K_0_nop, "No Operation"),
	TO_ENUM(NEC_78K_0_EI, "Enable Interrupt"),
	TO_ENUM(NEC_78K_0_DI, "Disable Interrupt"),
	TO_ENUM(NEC_78K_0_HALT, "HALT Mode Set"),
	TO_ENUM(NEC_78K_0_STOP, "Stop Mode Set"),
	TO_ENUM(NEC_78K_0_last, "Undocumented instruction NEC_78K_0_last")
};
