auto instructions_PLFM_M32R = flags_vector_t{
	TO_ENUM(m32r_null, "Undocumented instruction m32r_null"),
	TO_ENUM(m32r_add, "Add"),
	TO_ENUM(m32r_add3, "Add 3-operand"),
	TO_ENUM(m32r_addi, "Add immediate"),
	TO_ENUM(m32r_addv, "Add with overflow checking"),
	TO_ENUM(m32r_addv3, "Add 3-operand with overflow checking"),
	TO_ENUM(m32r_addx, "Add with carry"),
	TO_ENUM(m32r_and, "AND"),
	TO_ENUM(m32r_and3, "AND 3-operand"),
	TO_ENUM(m32r_bc, "Branch on C-bit"),
	TO_ENUM(m32r_beq, "Branch on equal"),
	TO_ENUM(m32r_beqz, "Branch on equal zero"),
	TO_ENUM(m32r_bgez, "Branch on greater than or equal zero"),
	TO_ENUM(m32r_bgtz, "Branch on greater than zero"),
	TO_ENUM(m32r_bl, "Branch and link"),
	TO_ENUM(m32r_blez, "Branch on less than or equal zero"),
	TO_ENUM(m32r_bltz, "Branch on less than zero"),
	TO_ENUM(m32r_bnc, "Branch on not C-bit"),
	TO_ENUM(m32r_bne, "Branch on not equal"),
	TO_ENUM(m32r_bnez, "Branch on not equal zero"),
	TO_ENUM(m32r_bra, "Branch"),
	TO_ENUM(m32r_cmp, "Compare"),
	TO_ENUM(m32r_cmpi, "Compare immediate"),
	TO_ENUM(m32r_cmpu, "Compare unsigned"),
	TO_ENUM(m32r_cmpui, "Compare unsigned immediate"),
	TO_ENUM(m32r_div, "Divide"),
	TO_ENUM(m32r_divu, "Divide unsigned"),
	TO_ENUM(m32r_jl, "Jump and link"),
	TO_ENUM(m32r_jmp, "Jump"),
	TO_ENUM(m32r_ld, "Load"),
	TO_ENUM(m32r_ld24, "Load 24-bit immediate"),
	TO_ENUM(m32r_ldb, "Load byte"),
	TO_ENUM(m32r_ldh, "Load halfword"),
	TO_ENUM(m32r_ldi, "Load immediate"),
	TO_ENUM(m32r_ldub, "Load unsigned byte"),
	TO_ENUM(m32r_lduh, "Load unsigned halfword"),
	TO_ENUM(m32r_lock, "Load locked"),
	TO_ENUM(m32r_machi, "Multiply-accumulate high-order halfwords"),
	TO_ENUM(m32r_maclo, "Multiply-accumulate low-order halfwords"),
	TO_ENUM(m32r_macwhi, "Multiply-accumulate word and high-order halfword"),
	TO_ENUM(m32r_macwlo, "Multiply-accumulate word and low-order halfword"),
	TO_ENUM(m32r_mul, "Multiply"),
	TO_ENUM(m32r_mulhi, "Multiply high-order halfwords"),
	TO_ENUM(m32r_mullo, "Multiply low-order halfwords"),
	TO_ENUM(m32r_mulwhi, "Multiply word high-order halfwords"),
	TO_ENUM(m32r_mulwlo, "Multiply word low-order halfwords"),
	TO_ENUM(m32r_mv, "Move register"),
	TO_ENUM(m32r_mvfachi, "Move from accumulator high-order word"),
	TO_ENUM(m32r_mvfaclo, "Move from accumulator low-order word"),
	TO_ENUM(m32r_mvfacmi, "Move from accumulator middle-order word"),
	TO_ENUM(m32r_mvfc, "Move from control register"),
	TO_ENUM(m32r_mvtachi, "Move to accumulator high-order word"),
	TO_ENUM(m32r_mvtaclo, "Move to accumulator low-order word"),
	TO_ENUM(m32r_mvtc, "Move to control register"),
	TO_ENUM(m32r_neg, "Negate"),
	TO_ENUM(m32r_nop, "No operation"),
	TO_ENUM(m32r_not, "Logical NOT"),
	TO_ENUM(m32r_or, "OR"),
	TO_ENUM(m32r_or3, "OR 3-operand"),
	TO_ENUM(m32r_push, "Push, mnem for st reg, @-sp"),
	TO_ENUM(m32r_pop, "Pop, mnem for ld reg, @sp+"),
	TO_ENUM(m32r_rac, "Round accumulator"),
	TO_ENUM(m32r_rach, "Round accumulator halfword"),
	TO_ENUM(m32r_rem, "Remainder"),
	TO_ENUM(m32r_remu, "Remainder unsigned"),
	TO_ENUM(m32r_rte, "Return from EIT"),
	TO_ENUM(m32r_seth, "Set high-order 16-bit"),
	TO_ENUM(m32r_sll, "Shift left logical"),
	TO_ENUM(m32r_sll3, "Shift left logical 3-operand"),
	TO_ENUM(m32r_slli, "Shift left logical immediate"),
	TO_ENUM(m32r_sra, "Shirt right arithmetic"),
	TO_ENUM(m32r_sra3, "Shirt right arithmetic 3-operand"),
	TO_ENUM(m32r_srai, "Shirt right arithmetic immediate"),
	TO_ENUM(m32r_srl, "Shift right logical"),
	TO_ENUM(m32r_srl3, "Shift right logical 3-operand"),
	TO_ENUM(m32r_srli, "Shift right logical immediate"),
	TO_ENUM(m32r_st, "Store"),
	TO_ENUM(m32r_stb, "Store byte"),
	TO_ENUM(m32r_sth, "Store halfword"),
	TO_ENUM(m32r_sub, "Substract"),
	TO_ENUM(m32r_subv, "Substract with overflow checking"),
	TO_ENUM(m32r_subx, "Substract with borrow"),
	TO_ENUM(m32r_trap, "Trap"),
	TO_ENUM(m32r_unlock, "Store unlocked"),
	TO_ENUM(m32r_xor, "Exclusive OR"),
	TO_ENUM(m32r_xor3, "Exclusive OR 3-operand"),
	TO_ENUM(m32r_fadd, "Floating-point add"),
	TO_ENUM(m32r_fsub, "Floating-point subtract"),
	TO_ENUM(m32r_fmul, "Floating-point multiply"),
	TO_ENUM(m32r_fdiv, "Floating-point divede"),
	TO_ENUM(m32r_fmadd, "Floating-point multiply and add"),
	TO_ENUM(m32r_fmsub, "Floating-point multiply and subtract"),
	TO_ENUM(m32r_itof, "Integer to float"),
	TO_ENUM(m32r_utof, "Unsigned integer to float"),
	TO_ENUM(m32r_ftoi, "Float to integer"),
	TO_ENUM(m32r_ftos, "Float to short"),
	TO_ENUM(m32r_fcmp, "Floating-point compare"),
	TO_ENUM(m32r_fcmpe, "Floating-point compare with exeption if unordered"),
	TO_ENUM(m32r_bset, "Bit set"),
	TO_ENUM(m32r_bclr, "Bit clear"),
	TO_ENUM(m32r_btst, "Bit test"),
	TO_ENUM(m32r_setpsw, "Set PSW"),
	TO_ENUM(m32r_clrpsw, "Clear PSW"),
	TO_ENUM(m32r_last, "Undocumented instruction m32r_last")
};
